
package com.gensym.util.symbol;

import com.gensym.util.Symbol;

/**
 * Collection of Symbols naming the default G2 Colors
 * @author vkp
 * @version 1.0 - 4/6/98
 */

public interface G2ColorSymbols extends SymbolConstants {

  public static final Symbol
    TRANSPARENT_              = Symbol.intern ("TRANSPARENT"),
    FOREGROUND_               = Symbol.intern ("FOREGROUND"),
    AQUAMARINE_               = Symbol.intern ("AQUAMARINE"),
    BLACK_                    = Symbol.intern ("BLACK"),
    BLUE_                     = Symbol.intern ("BLUE"),
    //BLUE_VIOLET_            = Symbol.intern ("//BLUE-VIOLET"),
    BROWN_                    = Symbol.intern ("BROWN"),
    CADET_BLUE_               = Symbol.intern ("CADET-BLUE"),
    CORAL_                    = Symbol.intern ("CORAL"),
    //CORNFLOWER_BLUE_        = Symbol.intern ("//CORNFLOWER-BLUE"),
    CYAN_                     = Symbol.intern ("CYAN"),
    DARK_GREY_                = Symbol.intern ("DARK-GREY"),      
    DARK_GRAY_                = Symbol.intern ("DARK-GRAY"),
    //DARK_GREEN_             = Symbol.intern ("//DARK-GREEN"),
    //DARK_OLIVE_GREEN_       = Symbol.intern ("//DARK-OLIVE-GREEN"),
    //DARK_ORCHID_            = Symbol.intern ("//DARK-ORCHID"),
    DARK_SLATE_BLUE_          = Symbol.intern ("DARK-SLATE-BLUE"),
    //DARK_SLATE_GRAY_        = Symbol.intern ("//DARK-SLATE-GRAY"),
    //DARK_TURQUOISE_         = Symbol.intern ("//DARK-TURQUOISE"),
    DIM_GREY_                 = Symbol.intern ("DIM-GREY"),
    DIM_GRAY_                 = Symbol.intern ("DIM-GRAY"),
    //FIREBRICK_              = Symbol.intern ("//FIREBRICK"),
    FOREST_GREEN_             = Symbol.intern ("FOREST-GREEN"),
    GOLD_                     = Symbol.intern ("GOLD"),
    GOLDENROD_                = Symbol.intern ("GOLDENROD"),
    GRAY_                     = Symbol.intern ("GRAY"),
    GREY_                     = Symbol.intern ("GREY"),
    GREEN_                    = Symbol.intern ("GREEN"),
    GREEN_YELLOW_             = Symbol.intern ("GREEN-YELLOW"),
    INDIAN_RED_               = Symbol.intern ("INDIAN-RED"),
    KHAKI_                    = Symbol.intern ("KHAKI"),
    LIGHT_BLUE_               = Symbol.intern ("LIGHT-BLUE"),
    LIGHT_GREY_               = Symbol.intern ("LIGHT-GREY"),      
    LIGHT_GRAY_               = Symbol.intern ("LIGHT-GRAY"),
    EXTRA_LIGHT_GRAY_         = Symbol.intern ("EXTRA-LIGHT-GRAY"),
    EXTRA_LIGHT_GREY_         = Symbol.intern ("EXTRA-LIGHT-GREY"),      
    //LIGHT_STEEL_BLUE_       = Symbol.intern ("//LIGHT-STEEL-BLUE"),
    LIME_GREEN_               = Symbol.intern ("LIME-GREEN"),
    MAGENTA_                  = Symbol.intern ("MAGENTA"),
    MAROON_                   = Symbol.intern ("MAROON"),
    MEDIUM_AQUAMARINE_        = Symbol.intern ("MEDIUM-AQUAMARINE"),
    MEDIUM_BLUE_              = Symbol.intern ("MEDIUM-BLUE"),
    //MEDIUM_FOREST_GREEN_    = Symbol.intern ("//MEDIUM-FOREST-GREEN"),
    MEDIUM_GOLDENROD_         = Symbol.intern ("MEDIUM-GOLDENROD"),
    MEDIUM_ORCHID_            = Symbol.intern ("MEDIUM-ORCHID"),
    //MEDIUM_SEA_GREEN_       = Symbol.intern ("//MEDIUM-SEA-GREEN"),
    //MEDIUM_SLATE_BLUE_      = Symbol.intern ("//MEDIUM-SLATE-BLUE"),
    //MEDIUM_SPRING_GREEN_    = Symbol.intern ("//MEDIUM-SPRING-GREEN"),
    //MEDIUM_TURQUOISE_       = Symbol.intern ("//MEDIUM-TURQUOISE"),
    //MEDIUM_VIOLET_RED_      = Symbol.intern ("//MEDIUM-VIOLET-RED"),
    //MIDNIGHT_BLUE_          = Symbol.intern ("//MIDNIGHT-BLUE"),
    //NAVY_BLUE_              = Symbol.intern ("//NAVY-BLUE"),
    ORANGE_                   = Symbol.intern ("ORANGE"),
    PALE_GREEN_               = Symbol.intern ("PALE-GREEN"),
    PINK_                     = Symbol.intern ("PINK"),
    PLUM_                     = Symbol.intern ("PLUM"),
    PURPLE_                   = Symbol.intern ("PURPLE"),
    RED_                      = Symbol.intern ("RED"),
    SALMON_                   = Symbol.intern ("SALMON"),
    //SEA_GREEN_              = Symbol.intern ("//SEA-GREEN"),
    SIENNA_                   = Symbol.intern ("SIENNA"),
    SKY_BLUE_                 = Symbol.intern ("SKY-BLUE"),
    SLATE_BLUE_               = Symbol.intern ("SLATE-BLUE"),
    //SPRING_GREEN_           = Symbol.intern ("//SPRING-GREEN"),
    //STEEL_BLUE_             = Symbol.intern ("//STEEL-BLUE"),
    TAN_                      = Symbol.intern ("TAN"),
    THISTLE_                  = Symbol.intern ("THISTLE"),
    TURQUOISE_                = Symbol.intern ("TURQUOISE"),
    VIOLET_                   = Symbol.intern ("VIOLET"),
    VIOLET_RED_               = Symbol.intern ("VIOLET-RED"),
    WHEAT_                    = Symbol.intern ("WHEAT"),
    WHITE_                    = Symbol.intern ("WHITE"),
    YELLOW_                   = Symbol.intern ("YELLOW"),
    //YELLOW_GREEN_           = Symbol.intern ("//YELLOW-GREEN"),
    SMOKE_                    = Symbol.intern ("SMOKE"),
    FLORAL_WHITE_             = Symbol.intern ("FLORAL-WHITE"),
    LINEN_                    = Symbol.intern ("LINEN"),
    ANTIQUE_WHITE_            = Symbol.intern ("ANTIQUE-WHITE"),
    IVORY_                    = Symbol.intern ("IVORY"),
    AZURE_                    = Symbol.intern ("AZURE"),
    LAVENDER_                 = Symbol.intern ("LAVENDER"),
    LIGHT_STEEL_BLUE_         = Symbol.intern ("LIGHT-STEEL-BLUE"),
    POWDER_BLUE_              = Symbol.intern ("POWDER-BLUE"),
    PALE_TURQUOISE_           = Symbol.intern ("PALE-TURQUOISE"),
    LIGHT_CYAN_               = Symbol.intern ("LIGHT-CYAN"),
    PALE_GOLDENROD_           = Symbol.intern ("PALE-GOLDENROD"),
    LIGHT_GOLDENROD_YELLOW_   = Symbol.intern ("LIGHT-GOLDENROD-YELLOW"),
    LIGHT_YELLOW_             = Symbol.intern ("LIGHT-YELLOW"),
    LIGHT_GOLDENROD_          = Symbol.intern ("LIGHT-GOLDENROD"),
    BEIGE_                    = Symbol.intern ("BEIGE"),
    LIGHT_PINK_               = Symbol.intern ("LIGHT-PINK");

}
