#!/bin/csh -f

# If the following command does not contain the expanded G2 install home, then a problem 
# occurred with the installer, and you should edit it to create the proper value
setenv G2_INSTALL_HOME %ROOTDIR%

cd ${G2_INSTALL_HOME}/odbc
setenv GSI_ROOT ${G2_INSTALL_HOME}/odbc
${G2_INSTALL_HOME}/odbc/bin/g2-odbc $*
