interface mapping {
    readonly attribute short             shortVal;
	readonly attribute long              longVal;
	readonly attribute unsigned short    ushortVal;
	readonly attribute unsigned long     ulongVal;
	readonly attribute float             floatVal;
	readonly attribute double            dblVal;
	readonly attribute char              charVal;
	readonly attribute boolean           booleanVal;
	readonly attribute octet             octetVal;
	readonly attribute string            stringVal;
    struct struct1 {
	    long val1;
        string val2;
        double val3;
    };
	//readonly attribute struct1   myStruct;

    void get_struct1( in struct1 myStruct );
	void set_short(in short val );
	void set_long(in long val );
	void set_ushort(in unsigned short val );
	void set_ulong(in unsigned long val );
	void set_float(in float val );
	void set_double(in double val );
	void set_char(in char val );
	void set_boolean(in boolean val );
	void set_octet(in octet val );
	void set_string(in string val );
	void set_struct1(in struct1 sval );

	void get_short(out short val );
	void get_long(out long val );
	void get_ushort(out unsigned short val );
	void get_ulong(out unsigned long val );
	void get_float(out float val );
	void get_double(out double val );
	void get_char(out char val );
	void get_boolean(out boolean val );
	void get_octet(out octet val );
	void get_string(out string val );

};

