#!/bin/csh -f
setenv LD_LIBRARY_PATH ../javalink/bin
setenv SHLIB_PATH ../javalink/bin
setenv CLASSPATH ./:../javalink/classes:../javalink/classes/core.jar:../javalink/classes/classtools.jar:../javalink/classes/javalink.jar:../javalink/classes/beanbuilder.jar:./NolStudioData.jar:./NolStudioMath.jar:./NolStudioDeploy.jar
java -Xmx240m com.gensym.nols.deploy.NolG2Gateway $*
