interface grid {
	readonly attribute short height;  // height of the grid
	readonly attribute short width;   // width of the grid

	// IDL operation

	// return element [n,m] of the grid:
	long fetch(in short n, in short m);

};