

//Dialog.h

#define GENSYM_REGISTER_USER            13031
#define GENSYM_SETUP_TYPE               32009

prototype DialogShowSdWelcome();
prototype DialogShowSdRegisterUserEx(BYREF STRING, BYREF STRING, BYREF STRING);
prototype DialogShowSdAskDestPath();  
 
prototype DialogShowSdComponentTree(BYREF STRING);
prototype DialogShowObjDialogs();
prototype DialogShowSdSelectFolder();
prototype DialogShowNtAdmin(BYREF LIST, NUMBER);
  
prototype DialogShowSetupType (BYREF NUMBER);
  
// prototype DialogShow ();


// MHD, 10/23/00: This global variable is set in BundleInfo.rul, from
// code generated by InstallGenerator (ISProject.c), based on the
// presence of a setting for each bundle for "typical install only" (true if
// present).  It is used in Setup.rul, which, if true, skips the custom
// vs. typical dialog and just assuming a typical dialog.

BOOL BUNDLE_TYPICAL_ONLY;


// MHD, 10/2/00: The following just keeps us from getting warnings
// about some functions not used now. 

prototype dialog_gag_is_compiler();
function dialog_gag_is_compiler()
STRING byref_string, byref_string2, byref_string3;
BOOL by_ref_bool;
BOOL by_ref_number;
LIST some_list, byref_list;
NUMBER byref_number;
begin
 DialogShowSdWelcome();
 DialogShowSdRegisterUserEx(byref_string, byref_string2, byref_string3);
 DialogShowSdAskDestPath();  
 DialogShowSdComponentTree(byref_string);
 DialogShowObjDialogs();
 DialogShowSdSelectFolder();
 DialogShowNtAdmin(byref_list, 0);
 DialogShowSetupType (byref_number);
 dialog_gag_is_compiler();
end;
