#!/bin/csh -f
echo "ERROR: This script is obsolete.  Please use"
echo "  /gensym/tools/promote-product and "
echo "  /gensym/tools/remove-product instead."
echo "See /gensym/tools/readme-promoting.txt for important information."
