#!/bin/csh

# Make a TAGS file in the current directory for all of the G2/Tw/GSI lisp files,
# in the order of their appearance in the systems definition.

set ETAGS = /home/xemacs/xemacs-21.0-solaris2.5/bin/etags
if ( ! -f $ETAGS ) then
  set ETAGS = etags
endif

set SCRIPTS = /home/development/scripts

$SCRIPTS/write-files-in-order

cd $LISP_DIR

if ( -z "$1" ) then
  set FILE_LIST = /tmp/files-in-order-with-directory.dat
  cat files-in-order.dat | /gensym/bin/add-prefix $LISP_DIR >! $FILE_LIST
else
  set FILE_LIST = files-in-order.dat
endif

${ETAGS} `cat $FILE_LIST`

set MKID = /gensym/bin/mkid
${MKID} `cat $FILE_LIST`

if ( "`whoami`" == "ab" && ! -f $LISP_DIR/CVS/Tag ) then
  # Move the database file to ab.
  /bin/rm -f /home/ab/g2/ID.bak
  /bin/mv /home/ab/g2/ID /home/ab/g2/ID.bak
  /bin/mv ID /home/ab/g2/ID
  /bin/cp -p files-in-order.dat /home/ab/g2/files-in-order.all
endif

# Tell xemacs about the new TAGS file.
# Once everyone is running xemacs, we can do this.
# /home/ab/bin/gnudoit -q '(update-tags-completion-table)'
