#!/bin/sh

echo "  "
echo "  This script is no longer to be used for its old purpose of a"
echo '  "do-it-all" sandbox build script.'
echo "  Please use the 'build' or 'run-translator' scripts instead".
echo "  This script will soon be replaced by a new one which does something else."
echo "  "
