/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_G2JDBCAuthorize */

#ifndef _Included_core_G2JDBCAuthorize
#define _Included_core_G2JDBCAuthorize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_G2JDBCAuthorize
 * Method:    authorize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_core_G2JDBCAuthorize_authorize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
