/* Dynamic linkage to Gigasoft charting library. */
/* Automatically generated by fmw on Thu Apr 13 15:28:42 2006 with script "peimport". */
/* Include this after including pegrpapi.h */

/* Undefines */
#undef PEDebugOutput
#undef PEValidateProperty
#undef PEallocateindmemory
#undef PEappendfromURL
#undef PEbitmapandgradients
#undef PEcopybitmaptoclipboard
#undef PEcopybitmaptofile
#undef PEcopyemftoclipboard
#undef PEcopyemftofile
#undef PEcopyjpegtoclipboard
#undef PEcopyjpegtofile
#undef PEcopyjpegtohglobal
#undef PEcopymetatoclipboard
#undef PEcopymetatofile
#undef PEcopyoletoclipboard
#undef PEcopypngtoclipboard
#undef PEcopypngtofile
#undef PEcopypngtohglobal
#undef PEcopysvgtofile
#undef PEcopysvgtohglobal
#undef PEcreate
#undef PEcreatefromfile
#undef PEcreateserialdate
#undef PEdecipherserialdate
#undef PEdestroy
#undef PEdrawcursor
#undef PEdrawtable
#undef PEexporttext
#undef PEfilterdllmsg
#undef PEgetenhancedmeta
#undef PEgetglobal
#undef PEgetgraph
#undef PEgethelpcontext
#undef PEgethotspot
#undef PEgethotspotdata
#undef PEgetmeta
#undef PEgetpiechart
#undef PEgetsgraph
#undef PEgettextmetrics
#undef PElaunchcolordialog
#undef PElaunchcustomize
#undef PElaunchcustomizeEx
#undef PElaunchexport
#undef PElaunchfontdialog
#undef PElaunchmaximize
#undef PElaunchpopupmenu
#undef PElaunchprintdialog
#undef PElaunchtextexport
#undef PEload
#undef PEloadfromURL
#undef PEloadfromfile
#undef PEloadpartial
#undef PEnget
#undef PEnset
#undef PEpartialresetimage
#undef PEplaymetafile
#undef PEprintgraph
#undef PEconvpixeltograph
#undef PEprocessdllidle
#undef PEreconstruct3dpolygons
#undef PEreinitialize
#undef PEreinitializecustoms
#undef PEreset
#undef PEresetimage
#undef PEresetimageEx
#undef PEsavetofile
#undef PEserializetofile
#undef PEserializetohglobal
#undef PEsetglobal
#undef PEsetgraph
#undef PEsetpiechart
#undef PEsetsgraph
#undef PEstore
#undef PEstorepartial
#undef PEszget
#undef PEszset
#undef PEvget
#undef PEvgetEx
#undef PEvgetcell
#undef PEvgetcellEx
#undef PEvset
#undef PEvsetEx
#undef PEvsetcell
#undef PEvsetcellEx


/* Defines */
#define PEDebugOutput(nId) ((*gTab.pPEDebugOutput)(nId))
#define PEValidateProperty(nCntlType, nProperty) ((*gTab.pPEValidateProperty)(nCntlType, nProperty))
#define PEallocateindmemory(hObject) ((*gTab.pPEallocateindmemory)(hObject))
#define PEappendfromURL(hObject, lpURL, dwFlags) ((*gTab.pPEappendfromURLW)(hObject, lpURL, dwFlags))
#define PEbitmapandgradients(hObject, hTargetDC, hMemDC, pr) ((*gTab.pPEbitmapandgradients)(hObject, hTargetDC, hMemDC, pr))
#define PEcopybitmaptoclipboard(hObject, lpPoint) ((*gTab.pPEcopybitmaptoclipboard)(hObject, lpPoint))
#define PEcopybitmaptofile(hObject, lpPoint, lpszFilename) ((*gTab.pPEcopybitmaptofileW)(hObject, lpPoint, lpszFilename))
#define PEcopyemftoclipboard(hObject, lpPoint) ((*gTab.pPEcopyemftoclipboard)(hObject, lpPoint))
#define PEcopyemftofile(hObject, lpPoint, lpszFilename, _nTargetDPI) ((*gTab.pPEcopyemftofileW)(hObject, lpPoint, lpszFilename, _nTargetDPI))
#define PEcopyjpegtoclipboard(hObject, lpPoint) ((*gTab.pPEcopyjpegtoclipboard)(hObject, lpPoint))
#define PEcopyjpegtofile(hObject, lpPoint, lpszFilename) ((*gTab.pPEcopyjpegtofileW)(hObject, lpPoint, lpszFilename))
#define PEcopyjpegtohglobal(hObject, lpPoint, pHG) ((*gTab.pPEcopyjpegtohglobal)(hObject, lpPoint, pHG))
#define PEcopymetatoclipboard(hObject, lpPoint) ((*gTab.pPEcopymetatoclipboard)(hObject, lpPoint))
#define PEcopymetatofile(hObject, lpPoint, lpszFilename) ((*gTab.pPEcopymetatofileW)(hObject, lpPoint, lpszFilename))
#define PEcopyoletoclipboard(hObject, lpPoint) ((*gTab.pPEcopyoletoclipboard)(hObject, lpPoint))
#define PEcopypngtoclipboard(hObject, lpPoint) ((*gTab.pPEcopypngtoclipboard)(hObject, lpPoint))
#define PEcopypngtofile(hObject, lpPoint, lpszFilename) ((*gTab.pPEcopypngtofileW)(hObject, lpPoint, lpszFilename))
#define PEcopypngtohglobal(hObject, lpPoint, pHG) ((*gTab.pPEcopypngtohglobal)(hObject, lpPoint, pHG))
#define PEcopysvgtofile(hObject, size, lpszFilename, _bCompress) ((*gTab.pPEcopysvgtofileW)(hObject, size, lpszFilename, _bCompress))
#define PEcopysvgtohglobal(hObject, size, pHG, _bCompress) ((*gTab.pPEcopysvgtohglobal)(hObject, size, pHG, _bCompress))
#define PEcreate(nObjectType, dwStyle, lpRect, hParent, nID) ((*gTab.pPEcreate)(nObjectType, dwStyle, lpRect, hParent, nID))
#define PEcreatefromfile(lpFileName, hParent, lpRect, nID) ((*gTab.pPEcreatefromfileW)(lpFileName, hParent, lpRect, nID))
#define PEcreateserialdate(pfSerial, dt, nType) ((*gTab.pPEcreateserialdate)(pfSerial, dt, nType))
#define PEdecipherserialdate(pfSerial, dt, nType) ((*gTab.pPEdecipherserialdate)(pfSerial, dt, nType))
#define PEdestroy(hObject) ((*gTab.pPEdestroy)(hObject))
#define PEdrawcursor(hObject, hdc, nAction) ((*gTab.pPEdrawcursor)(hObject, hdc, nAction))
#define PEdrawtable(hObject, nTAIndex, hdc) ((*gTab.pPEdrawtable)(hObject, nTAIndex, hdc))
#define PEexporttext(hObject, nPrecision, nTableorList, lpszFilename) ((*gTab.pPEexporttextW)(hObject, nPrecision, nTableorList, lpszFilename))
#define PEfilterdllmsg(lpMsg) ((*gTab.pPEfilterdllmsg)(lpMsg))
#define PEgetenhancedmeta(hObject, lpPoint) ((*gTab.pPEgetenhancedmeta)(hObject, lpPoint))
#define PEgetglobal(hObject, lpData) ((*gTab.pPEgetglobal)(hObject, lpData))
#define PEgetgraph(hObject, lpData) ((*gTab.pPEgetgraph)(hObject, lpData))
#define PEgethelpcontext(hWnd) ((*gTab.pPEgethelpcontext)(hWnd))
#define PEgethotspot(hObject, nX, nY) ((*gTab.pPEgethotspot)(hObject, nX, nY))
#define PEgethotspotdata(hObject, nHotSpotArray, nArrayIndex, pHOTSPOTDATA) ((*gTab.pPEgethotspotdata)(hObject, nHotSpotArray, nArrayIndex, pHOTSPOTDATA))
#define PEgetmeta(hObject) ((*gTab.pPEgetmeta)(hObject))
#define PEgetpiechart(hObject, lpData) ((*gTab.pPEgetpiechart)(hObject, lpData))
#define PEgetsgraph(hObject, lpData) ((*gTab.pPEgetsgraph)(hObject, lpData))
#define PEgettextmetrics(hObject,  szText, szFont, bBold, bItalic, bUnderline, fFontSize, bVertical, pnWidth, pnHeight) ((*gTab.pPEgettextmetrics)(hObject,  szText, szFont, bBold, bItalic, bUnderline, fFontSize, bVertical, pnWidth, pnHeight))
#define PElaunchcolordialog(hObject) ((*gTab.pPElaunchcolordialog)(hObject))
#define PElaunchcustomize(hObject) ((*gTab.pPElaunchcustomize)(hObject))
#define PElaunchcustomizeEx(hObject, nPageID) ((*gTab.pPElaunchcustomizeEx)(hObject, nPageID))
#define PElaunchexport(hObject) ((*gTab.pPElaunchexport)(hObject))
#define PElaunchfontdialog(hObject) ((*gTab.pPElaunchfontdialog)(hObject))
#define PElaunchmaximize(hObject) ((*gTab.pPElaunchmaximize)(hObject))
#define PElaunchpopupmenu(hObject, pLocation) ((*gTab.pPElaunchpopupmenu)(hObject, pLocation))
#define PElaunchprintdialog(hObject, bFullPage, pSize) ((*gTab.pPElaunchprintdialog)(hObject, bFullPage, pSize))
#define PElaunchtextexport(hObject, bToFile, lpszFilename) ((*gTab.pPElaunchtextexportW)(hObject, bToFile, lpszFilename))
#define PEload(hObject, lphGlbl) ((*gTab.pPEload)(hObject, lphGlbl))
#define PEloadfromURL(hObject, lpURL, dwFlags) ((*gTab.pPEloadfromURLW)(hObject, lpURL, dwFlags))
#define PEloadfromfile(hObject, lpFileName) ((*gTab.pPEloadfromfileW)(hObject, lpFileName))
#define PEloadpartial(hObject, lphGlbl) ((*gTab.pPEloadpartial)(hObject, lphGlbl))
#define PEnget(hObject, nProperty) ((*gTab.pPEnget)(hObject, nProperty))
#define PEnset(hObject, nProperty, nData) ((*gTab.pPEnset)(hObject, nProperty, nData))
#define PEpartialresetimage(hObject, nStartPoint, nPointsToAdd) ((*gTab.pPEpartialresetimage)(hObject, nStartPoint, nPointsToAdd))
#define PEplaymetafile(hObject, _hDeviceContext, _hOldStyleMetafile) ((*gTab.pPEplaymetafile)(hObject, _hDeviceContext, _hOldStyleMetafile))
#define PEprintgraph(hObject, hDC, nWidth, nHeight, nOrient) ((*gTab.pPEprintgraph)(hObject, hDC, nWidth, nHeight, nOrient))
#define PEconvpixeltograph(hObject, pnAxis, pnX, pnY, pfX, pfY, bRightAxis, bTopAxis, bViceVersa) \
        ((*gTab.pPEconvpixeltograph)(hObject, pnAxis, pnX, pnY, pfX, pfY, bRightAxis, bTopAxis, bViceVersa))
#define PEprocessdllidle() ((*gTab.pPEprocessdllidle)())
#define PEreconstruct3dpolygons(hObject) ((*gTab.pPEreconstruct3dpolygons)(hObject))
#define PEreinitialize(hObject) ((*gTab.pPEreinitialize)(hObject))
#define PEreinitializecustoms(hObject) ((*gTab.pPEreinitializecustoms)(hObject))
#define PEreset(hObject) ((*gTab.pPEreset)(hObject))
#define PEresetimage(hObject, nLength, nHeight) ((*gTab.pPEresetimage)(hObject, nLength, nHeight))
#define PEresetimageEx(hObject, nExtX, nExtY, nOrgX, nOrgY) ((*gTab.pPEresetimageEx)(hObject, nExtX, nExtY, nOrgX, nOrgY))
#define PEsavetofile(hObject, lpFileName) ((*gTab.pPEsavetofileW)(hObject, lpFileName))
#define PEserializetofile(hObject, lpszFilename) ((*gTab.pPEserializetofileW)(hObject, lpszFilename))
#define PEserializetohglobal(hObject, pHG) ((*gTab.pPEserializetohglobal)(hObject, pHG))
#define PEsetglobal(hObject, lpData) ((*gTab.pPEsetglobal)(hObject, lpData))
#define PEsetgraph(hObject, lpData) ((*gTab.pPEsetgraph)(hObject, lpData))
#define PEsetpiechart(hObject, lpData) ((*gTab.pPEsetpiechart)(hObject, lpData))
#define PEsetsgraph(hObject, lpData) ((*gTab.pPEsetsgraph)(hObject, lpData))
#define PEstore(hObject, lphGlbl, lpdwSize) ((*gTab.pPEstore)(hObject, lphGlbl, lpdwSize))
#define PEstorepartial(hObject, lphGlbl, lpdwSize) ((*gTab.pPEstorepartial)(hObject, lphGlbl, lpdwSize))
#define PEszget(hObject, nProperty, szData) ((*gTab.pPEszgetW)(hObject, nProperty, szData))
#define PEszset(hObject, nProperty, szData) ((*gTab.pPEszsetW)(hObject, nProperty, szData))
#define PEvget(hObject, nProperty, lpvDest) ((*gTab.pPEvgetW)(hObject, nProperty, lpvDest))
#define PEvgetEx(hObject, property, nStartingCell, nCellCount, lpData) ((*gTab.pPEvgetEx)(hObject, property, nStartingCell, nCellCount, lpData))
#define PEvgetcell(hObject, nProperty, nCell, lpvDest) ((*gTab.pPEvgetcellW)(hObject, nProperty, nCell, lpvDest))
#define PEvgetcellEx(hObject, nProperty, nSubset, nPoint, lpvDest) ((*gTab.pPEvgetcellExW)(hObject, nProperty, nSubset, nPoint, lpvDest))
#define PEvset(hObject, nProperty, lpvData, nElements) ((*gTab.pPEvsetW)(hObject, nProperty, lpvData, nElements))
#define PEvsetEx(hObject, property, nStartingCell, nCellCount, lpData, lpMemSetValue) ((*gTab.pPEvsetEx)(hObject, property, nStartingCell, nCellCount, lpData, lpMemSetValue))
#define PEvsetcell(hObject, nProperty, nCell, lpvData) ((*gTab.pPEvsetcellW)(hObject, nProperty, nCell, lpvData))
#define PEvsetcellEx(hObject, nProperty, nSubset, nPoint, lpvData) ((*gTab.pPEvsetcellExW)(hObject, nProperty, nSubset, nPoint, lpvData))


/* Dispatch table */
struct {
  BOOL (__stdcall *pPEValidateProperty)(UINT nCntlType, UINT nProperty);
  BOOL (__stdcall *pPEallocateindmemory)(HWND hObject);
  BOOL (__stdcall *pPEappendfromURLW)(HWND hObject, LPWSTR lpURL, DWORD dwFlags);
  BOOL (__stdcall *pPEbitmapandgradients)(HWND hObject, HDC hTargetDC, HDC hMemDC, LPRECT pr);
  BOOL (__stdcall *pPEcopybitmaptoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopybitmaptofileW)(HWND hObject, POINT *lpPoint, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEcopyemftoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopyemftofileW)(HWND hObject, POINT *lpPoint, LPWSTR lpszFilename, int _nTargetDPI);
  BOOL (__stdcall *pPEcopyjpegtoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopyjpegtofileW)(HWND hObject, POINT *lpPoint, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEcopymetatoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopymetatofileW)(HWND hObject, POINT *lpPoint, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEcopyoletoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopypngtoclipboard)(HWND hObject, POINT *lpPoint);
  BOOL (__stdcall *pPEcopypngtofileW)(HWND hObject, POINT *lpPoint, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEcopysvgtofileW)(HWND hObject, POINT size, LPWSTR lpszFilename, BOOL _bCompress);
  BOOL (__stdcall *pPEdestroy)(HWND hObject);
  BOOL (__stdcall *pPEdrawcursor)(HWND hObject, HDC hdc, UINT nAction);
  BOOL (__stdcall *pPEdrawtable)(HWND hObject, UINT nTAIndex, HDC hdc);
  BOOL (__stdcall *pPEexporttextW)(HWND hObject, UINT nPrecision, UINT nTableorList, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEfilterdllmsg)(LPMSG lpMsg);
  BOOL (__stdcall *pPEgetglobal)(HWND hObject, GLOBALPROPERTIES *lpData);
  BOOL (__stdcall *pPEgetgraph)(HWND hObject, GRAPHPROPERTIES *lpData);
  BOOL (__stdcall *pPEgethotspot)(HWND hObject, int nX, int nY);
  BOOL (__stdcall *pPEgetpiechart)(HWND hObject, PIEPROPERTIES *lpData);
  BOOL (__stdcall *pPEgetsgraph)(HWND hObject, SGRAPHPROPERTIES *lpData);
  BOOL (__stdcall *pPElaunchexport)(HWND hObject);
  BOOL (__stdcall *pPElaunchmaximize)(HWND hObject);
  BOOL (__stdcall *pPElaunchpopupmenu)(HWND hObject, POINT *pLocation);
  BOOL (__stdcall *pPElaunchprintdialog)(HWND hObject, BOOL bFullPage, POINT *pSize);
  BOOL (__stdcall *pPElaunchtextexportW)(HWND hObject, BOOL bToFile, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEload)(HWND hObject, HGLOBAL *lphGlbl);
  BOOL (__stdcall *pPEloadfromURLW)(HWND hObject, LPWSTR lpURL, DWORD dwFlags);
  BOOL (__stdcall *pPEloadfromfileW)(HWND hObject, LPWSTR lpFileName);
  BOOL (__stdcall *pPEloadpartial)(HWND hObject, HGLOBAL *lphGlbl);
  BOOL (__stdcall *pPEnset)(HWND hObject, UINT nProperty, int nData);
  BOOL (__stdcall *pPEpartialresetimage)(HWND hObject, int nStartPoint, int nPointsToAdd);
  BOOL (__stdcall *pPEprintgraph)(HWND hObject, int hDC, int nWidth, int nHeight, int nOrient);
  BOOL (__stdcall *pPEconvpixeltograph)(HWND hObject, int* pnAxis, int* pnX, int* pnY, double* pfX, double* pfY, BOOL bRightAxis, BOOL bTopAxis, BOOL bViceVersa);
  BOOL (__stdcall *pPEreconstruct3dpolygons)(HWND hObject);
  BOOL (__stdcall *pPEreinitialize)(HWND hObject);
  BOOL (__stdcall *pPEreinitializecustoms)(HWND hObject);
  BOOL (__stdcall *pPEreset)(HWND hObject);
  BOOL (__stdcall *pPEresetimage)(HWND hObject, UINT nLength, UINT nHeight);
  BOOL (__stdcall *pPEresetimageEx)(HWND hObject, UINT nExtX, UINT nExtY, UINT nOrgX, UINT nOrgY);
  BOOL (__stdcall *pPEsavetofileW)(HWND hObject, LPWSTR lpFileName);
  BOOL (__stdcall *pPEserializetofileW)(HWND hObject, LPWSTR lpszFilename);
  BOOL (__stdcall *pPEsetglobal)(HWND hObject, GLOBALPROPERTIES *lpData);
  BOOL (__stdcall *pPEsetgraph)(HWND hObject, GRAPHPROPERTIES *lpData);
  BOOL (__stdcall *pPEsetpiechart)(HWND hObject, PIEPROPERTIES *lpData);
  BOOL (__stdcall *pPEsetsgraph)(HWND hObject, SGRAPHPROPERTIES *lpData);
  BOOL (__stdcall *pPEstore)(HWND hObject, HGLOBAL *lphGlbl, DWORD *lpdwSize);
  BOOL (__stdcall *pPEstorepartial)(HWND hObject, HGLOBAL *lphGlbl, DWORD *lpdwSize);
  BOOL (__stdcall *pPEszgetW)(HWND hObject, UINT nProperty, LPWSTR szData);
  BOOL (__stdcall *pPEszsetW)(HWND hObject, UINT nProperty, LPWSTR szData);
  BOOL (__stdcall *pPEvgetEx)(HWND hObject, UINT property, int nStartingCell, int nCellCount, void *lpData);
  BOOL (__stdcall *pPEvgetcellExW)(HWND hObject, UINT nProperty, int nSubset, int nPoint, void *lpvDest);
  BOOL (__stdcall *pPEvgetcellW)(HWND hObject, UINT nProperty, int nCell, void *lpvDest);
  BOOL (__stdcall *pPEvsetEx)(HWND hObject, UINT property, int nStartingCell, int nCellCount, void *lpData, void *lpMemSetValue);
  BOOL (__stdcall *pPEvsetW)(HWND hObject, UINT nProperty, void *lpvData, int nElements);
  BOOL (__stdcall *pPEvsetcellExW)(HWND hObject, UINT nProperty, int nSubset, int nPoint, void *lpvData);
  BOOL (__stdcall *pPEvsetcellW)(HWND hObject, UINT nProperty, int nCell, void *lpvData);
  DWORD (__stdcall *pPEcopyjpegtohglobal)(HWND hObject, POINT *lpPoint, HGLOBAL* pHG);
  DWORD (__stdcall *pPEcopypngtohglobal)(HWND hObject, POINT *lpPoint, HGLOBAL* pHG);
  DWORD (__stdcall *pPEcopysvgtohglobal)(HWND hObject, POINT size, HGLOBAL* pHG, BOOL _bCompress);
  DWORD (__stdcall *pPEgethelpcontext)(HWND hWnd);
  DWORD (__stdcall *pPEgethotspotdata)(HWND hObject, int nHotSpotArray, int nArrayIndex, void *pHOTSPOTDATA);
  DWORD (__stdcall *pPEserializetohglobal)(HWND hObject, HGLOBAL* pHG);
  HENHMETAFILE (__stdcall *pPEgetenhancedmeta)(HWND hObject, POINT *lpPoint);
  HMETAFILE (__stdcall *pPEgetmeta)(HWND hObject);
  HWND (__stdcall *pPEcreate)(UINT nObjectType, DWORD dwStyle, RECT *lpRect, HWND hParent, UINT nID);
  HWND (__stdcall *pPEcreatefromfileW)(LPWSTR lpFileName, HWND hParent, RECT *lpRect, UINT nID);
  int (__stdcall *pPElaunchcolordialog)(HWND hObject);
  int (__stdcall *pPElaunchcustomize)(HWND hObject);
  int (__stdcall *pPElaunchcustomizeEx)(HWND hObject, UINT nPageID);
  int (__stdcall *pPElaunchfontdialog)(HWND hObject);
  int (__stdcall *pPEnget)(HWND hObject, UINT nProperty);
  int (__stdcall *pPEvgetW)(HWND hObject, UINT nProperty, void *lpvDest);
  void (__stdcall *pPEDebugOutput)(UINT nId);
  void (__stdcall *pPEcreateserialdate)(double* pfSerial, TM* dt, int nType);
  void (__stdcall *pPEdecipherserialdate)(double* pfSerial, TM* dt, int nType);
  void (__stdcall *pPEgettextmetrics)(HWND hObject,  LPTSTR szText, int szFont, BOOL bBold, BOOL bItalic, BOOL bUnderline, float fFontSize, BOOL bVertical, int *pnWidth, int *pnHeight);
  void (__stdcall *pPEplaymetafile)(HWND hObject, HDC _hDeviceContext, HMETAFILE _hOldStyleMetafile);
  void (__stdcall *pPEprocessdllidle)();
} gTab;

/* Initializer */
#pragma warning(disable: 4113 4047) /* Function type warnings expected */
static void pe_load_functions(HMODULE hMod)
{
  gTab.pPEDebugOutput = get_proc_address(hMod,"PEDebugOutput",1);
  gTab.pPEValidateProperty = get_proc_address(hMod,"PEValidateProperty",2);
  gTab.pPEallocateindmemory = get_proc_address(hMod,"PEallocateindmemory",1);
  gTab.pPEappendfromURLW = get_proc_address(hMod,"PEappendfromURLW",3);
  gTab.pPEbitmapandgradients = get_proc_address(hMod,"PEbitmapandgradients",4);
  gTab.pPEcopybitmaptoclipboard = get_proc_address(hMod,"PEcopybitmaptoclipboard",2);
  gTab.pPEcopybitmaptofileW = get_proc_address(hMod,"PEcopybitmaptofileW",3);
  gTab.pPEcopyemftoclipboard = get_proc_address(hMod,"PEcopyemftoclipboard",2);
  gTab.pPEcopyemftofileW = get_proc_address(hMod,"PEcopyemftofileW",4);
  gTab.pPEcopyjpegtoclipboard = get_proc_address(hMod,"PEcopyjpegtoclipboard",2);
  gTab.pPEcopyjpegtofileW = get_proc_address(hMod,"PEcopyjpegtofileW",3);
  gTab.pPEcopyjpegtohglobal = get_proc_address(hMod,"PEcopyjpegtohglobal",3);
  gTab.pPEcopymetatoclipboard = get_proc_address(hMod,"PEcopymetatoclipboard",2);
  gTab.pPEcopymetatofileW = get_proc_address(hMod,"PEcopymetatofileW",3);
  gTab.pPEcopyoletoclipboard = get_proc_address(hMod,"PEcopyoletoclipboard",2);
  gTab.pPEcopypngtoclipboard = get_proc_address(hMod,"PEcopypngtoclipboard",2);
  gTab.pPEcopypngtofileW = get_proc_address(hMod,"PEcopypngtofileW",3);
  gTab.pPEcopypngtohglobal = get_proc_address(hMod,"PEcopypngtohglobal",3);
  gTab.pPEcopysvgtofileW = get_proc_address(hMod,"PEcopysvgtofileW",4);
  gTab.pPEcopysvgtohglobal = get_proc_address(hMod,"PEcopysvgtohglobal",4);
  gTab.pPEcreate = get_proc_address(hMod,"PEcreate",5);
  gTab.pPEcreatefromfileW = get_proc_address(hMod,"PEcreatefromfileW",4);
  gTab.pPEcreateserialdate = get_proc_address(hMod,"PEcreateserialdate",3);
  gTab.pPEdecipherserialdate = get_proc_address(hMod,"PEdecipherserialdate",3);
  gTab.pPEdestroy = get_proc_address(hMod,"PEdestroy",1);
  gTab.pPEdrawcursor = get_proc_address(hMod,"PEdrawcursor",3);
  gTab.pPEdrawtable = get_proc_address(hMod,"PEdrawtable",3);
  gTab.pPEexporttextW = get_proc_address(hMod,"PEexporttextW",4);
  gTab.pPEfilterdllmsg = get_proc_address(hMod,"PEfilterdllmsg",1);
  gTab.pPEgetenhancedmeta = get_proc_address(hMod,"PEgetenhancedmeta",2);
  gTab.pPEgetglobal = get_proc_address(hMod,"PEgetglobal",2);
  gTab.pPEgetgraph = get_proc_address(hMod,"PEgetgraph",2);
  gTab.pPEgethelpcontext = get_proc_address(hMod,"PEgethelpcontext",1);
  gTab.pPEgethotspot = get_proc_address(hMod,"PEgethotspot",3);
  gTab.pPEgethotspotdata = get_proc_address(hMod,"PEgethotspotdata",4);
  gTab.pPEgetmeta = get_proc_address(hMod,"PEgetmeta",1);
  gTab.pPEgetpiechart = get_proc_address(hMod,"PEgetpiechart",2);
  gTab.pPEgetsgraph = get_proc_address(hMod,"PEgetsgraph",2);
  gTab.pPEgettextmetrics = get_proc_address(hMod,"PEgettextmetrics",10);
  gTab.pPElaunchcolordialog = get_proc_address(hMod,"PElaunchcolordialog",1);
  gTab.pPElaunchcustomize = get_proc_address(hMod,"PElaunchcustomize",1);
  gTab.pPElaunchcustomizeEx = get_proc_address(hMod,"PElaunchcustomizeEx",2);
  gTab.pPElaunchexport = get_proc_address(hMod,"PElaunchexport",1);
  gTab.pPElaunchfontdialog = get_proc_address(hMod,"PElaunchfontdialog",1);
  gTab.pPElaunchmaximize = get_proc_address(hMod,"PElaunchmaximize",1);
  gTab.pPElaunchpopupmenu = get_proc_address(hMod,"PElaunchpopupmenu",2);
  gTab.pPElaunchprintdialog = get_proc_address(hMod,"PElaunchprintdialog",3);
  gTab.pPElaunchtextexportW = get_proc_address(hMod,"PElaunchtextexportW",3);
  gTab.pPEload = get_proc_address(hMod,"PEload",2);
  gTab.pPEloadfromURLW = get_proc_address(hMod,"PEloadfromURLW",3);
  gTab.pPEloadfromfileW = get_proc_address(hMod,"PEloadfromfileW",2);
  gTab.pPEloadpartial = get_proc_address(hMod,"PEloadpartial",2);
  gTab.pPEnget = get_proc_address(hMod,"PEnget",2);
  gTab.pPEnset = get_proc_address(hMod,"PEnset",3);
  gTab.pPEpartialresetimage = get_proc_address(hMod,"PEpartialresetimage",3);
  gTab.pPEplaymetafile = get_proc_address(hMod,"PEplaymetafile",3);
  gTab.pPEprintgraph = get_proc_address(hMod,"PEprintgraph",5);
  gTab.pPEconvpixeltograph = get_proc_address(hMod,"PEconvpixeltograph",9);
  gTab.pPEprocessdllidle = get_proc_address(hMod,"PEprocessdllidle",1);
  gTab.pPEreconstruct3dpolygons = get_proc_address(hMod,"PEreconstruct3dpolygons",1);
  gTab.pPEreinitialize = get_proc_address(hMod,"PEreinitialize",1);
  gTab.pPEreinitializecustoms = get_proc_address(hMod,"PEreinitializecustoms",1);
  gTab.pPEreset = get_proc_address(hMod,"PEreset",1);
  gTab.pPEresetimage = get_proc_address(hMod,"PEresetimage",3);
  gTab.pPEresetimageEx = get_proc_address(hMod,"PEresetimageEx",5);
  gTab.pPEsavetofileW = get_proc_address(hMod,"PEsavetofileW",2);
  gTab.pPEserializetofileW = get_proc_address(hMod,"PEserializetofileW",2);
  gTab.pPEserializetohglobal = get_proc_address(hMod,"PEserializetohglobal",2);
  gTab.pPEsetglobal = get_proc_address(hMod,"PEsetglobal",2);
  gTab.pPEsetgraph = get_proc_address(hMod,"PEsetgraph",2);
  gTab.pPEsetpiechart = get_proc_address(hMod,"PEsetpiechart",2);
  gTab.pPEsetsgraph = get_proc_address(hMod,"PEsetsgraph",2);
  gTab.pPEstore = get_proc_address(hMod,"PEstore",3);
  gTab.pPEstorepartial = get_proc_address(hMod,"PEstorepartial",3);
  gTab.pPEszgetW = get_proc_address(hMod,"PEszgetW",3);
  gTab.pPEszsetW = get_proc_address(hMod,"PEszsetW",3);
  gTab.pPEvgetEx = get_proc_address(hMod,"PEvgetEx",5);
  gTab.pPEvgetW = get_proc_address(hMod,"PEvgetW",3);
  gTab.pPEvgetcellExW = get_proc_address(hMod,"PEvgetcellExW",5);
  gTab.pPEvgetcellW = get_proc_address(hMod,"PEvgetcellW",4);
  gTab.pPEvsetEx = get_proc_address(hMod,"PEvsetEx",6);
  gTab.pPEvsetW = get_proc_address(hMod,"PEvsetW",4);
  gTab.pPEvsetcellExW = get_proc_address(hMod,"PEvsetcellExW",5);
  gTab.pPEvsetcellW = get_proc_address(hMod,"PEvsetcellW",4);
}
