/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyData */

#ifndef _Included_KeyData
#define _Included_KeyData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KeyData
 * Method:    getKey1
 * Signature: (IIII[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_KeyData_getKey1
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
