#ifndef __LICENSE_H
#define __LICENSE_H

#define NETSLEUTH_FAMILY_ID 5

/*
 * This text is based on the bundle/isheild/{netsleuth,generic}-license.txt
 * However, with modifications to transform the web page specific acceptance
 * instructions to a terminal oriented environment.
 */

static char *netsleuth_license_verbiage[] = {
  "NETSLEUTH(tm) END-USER LICENSE AGREEMENT --",
  "",
  "GENSYM CORPORATION (\"GENSYM\") IS WILLING TO LICENSE THE NETSLEUTH",
  "SOFTWARE AND THE ACCOMPANYING DOCUMENTATION INCLUDING AUTHORIZED",
  "COPIES OF EACH (NETSLEUTH) TO LICENSEE ONLY ON THE CONDITION THAT",
  "LICENSEE ACCEPTS ALL OF THE TERMS IN THIS AGREEMENT.",
  "",
  "PLEASE READ THE TERMS CAREFULLY BEFORE ACCEPTING THE LICENSE",
  "AGREEMENT. BY ACCEPTING THE LICENSE AGREEMENT, LICENSEE ACKNOWLEDGES",
  "THAT LICENSEE HAS READ AND UNDERSTANDS THIS AGREEMENT AND AGREES TO BE",
  "BOUND BY ITS TERMS AND CONDITIONS.",
  "",
  "IF LICENSEE DOES NOT ACCEPT THESE LICENSE TERMS, GENSYM DOES NOT GRANT",
  "ANY LICENSE TO NETSLEUTH, AND LICENSEE SHOULD DECLINE THE LICENSE",
  "AGREEMENT.",
  "",
  "",
  "1. LICENSE GRANT",
  "",
  "1.1 LICENSE GRANT - NON EUROPEAN UNION COUNTRIES",
  "",
  "THE FOLLOWING LICENSE GRANT SECTION IS FOR USE IN U.S., CANADA (EXCEPT",
  "QUEBEC), AND ALL OTHER COUNTRIES EXCEPT THE FOLLOWING EUROPEAN UNION",
  "COUNTRIES: AUSTRIA, BELGIUM, DENMARK, FINLAND, GREECE, IRELAND, ITALY,",
  "LUXEMBOURG, THE NETHERLANDS, NORWAY, SWEDEN, AND U.K. SEE BELOW FOR",
  "EUROPEAN UNION LICENSE GRANT SECTION.",
  "",
  "",
  "(A) License Rights",
  "",
  "Subject to the terms and conditions of this Agreement, Gensym grants a",
  "limited, non-exclusive, non-transferable license to use one copy of",
  "NetSleuth for the purpose of performing IP network autodiscovery,",
  "mapping, monitoring and reachability analysis. This copy of NetSleuth",
  "may only be used in a single NetSleuth server configuration, that is,",
  "the Licensee may not use the NetSleuth server component on more than",
  "one computer at the same time. Licensee may make a copy of NetSleuth",
  "solely for archival purposes.",
  "",
  "(B) General License Restrictions",
  "",
  "NetSleuth is licensed to Licensee only under the terms of this",
  "Agreement, and Gensym reserves all rights not expressly granted to",
  "Licensee. Licensee may not use, copy, modify, network, electronically",
  "transmit or transfer NetSleuth, or any copy thereof, except as",
  "expressly provided for in this Agreement.  Licensee may not reverse",
  "engineer, disassemble, decompile, or translate NetSleuth, or otherwise",
  "attempt to derive the source code of NetSleuth. Licensee may not",
  "disclose, sell, rent, lease, or loan any part of NetSleuth or related",
  "documentation to any external third parties.",
  "",
  "No right, title, or interest in or to any trademarks, service marks,",
  "or trade names of Gensym or Gensym's licensors is granted hereunder.",
  "",
  "",
  "1.2 LICENSE GRANT - EUROPEAN UNION COUNTRIES",
  "",
  "THIS LICENSE GRANT IS FOR USE IN FOLLOWING EUROPEAN UNION COUNTRIES:",
  "AUSTRIA, BELGIUM, DENMARK, FINLAND, GREECE, IRELAND, ITALY,",
  "LUXEMBOURG, THE NETHERLANDS, NORWAY, SWEDEN, AND U.K.",
  "",
  "(A) License Rights",
  "",
  "Subject to the terms and conditions of this Agreement, Gensym grants a",
  "limited, non-exclusive, license to use one copy of NetSleuth for the",
  "purpose of performing IP network auto discovery, mapping, monitoring",
  "and reachability analysis. This copy of NetSleuth may only be used in",
  "a single NetSleuth server configuration, that is, the Licensee may not",
  "use the NetSleuth server component on more than one computer at the",
  "same time. Licensee may make a copy of NetSleuth for archival",
  "purposes.  Licensee may transfer its copy of NetSleuth together with",
  "its documentation on a permanent basis, provided that Licensee",
  "notifies Gensym as to the name and address of the recipient and that",
  "such recipient agrees in writing to the terms and conditions of this",
  "Agreement.",
  "",
  "(B) General License Restrictions",
  "",
  "NetSleuth is licensed to Licensee only under the terms of this",
  "Agreement, and Gensym reserves all rights not expressly granted to",
  "Licensee. Licensee may not disclose, use, copy, modify, network,",
  "electronically transmit or transfer NetSleuth, or any copy thereof,",
  "except as expressly provided for in this Agreement. Licensee may not",
  "reverse engineer, disassemble, decompile, or translate NetSleuth, or",
  "otherwise attempt to derive the source code of NetSleuth.  If Licensee",
  "requires access to the source code of NetSleuth to achieve",
  "interoperability of NetSleuth with other software, Licensee will",
  "inform Gensym accordingly.  Gensym can then decide either (i) to",
  "perform the work in order to achieve interoperability and charge its",
  "then-standard rates for such work to Licensee; or (ii) to permit",
  "Licensee to reverse engineer parts of NetSleuth to obtain such source",
  "code but only to the extent necessary to achieve such",
  "interoperability. Licensee may not disclose, sell, rent, lease, or",
  "loan any part of NetSleuth or related documentation to any external",
  "third parties.",
  "",
  "No right, title, or interest in or to any trademarks, service marks,",
  "or trade names of Gensym or Gensym's licensors is granted hereunder.",
  "",
  "2. LIMITED WARRANTY",
  "",
  "Gensym warrants that the software herein will perform substantially in",
  "accordance with the accompanying written materials for a period of six",
  "(6) months (\"Warranty Period\") from the date of receipt. Where",
  "applicable, if Licensee qualifies as a \"consumer\" under the",
  "Magnuson-Moss Act, then Licensee may be entitled to any implied",
  "warranties allowed by law for the period of the express warranty as",
  "set forth above. Some jurisdictions do not allow limitations on how",
  "long an implied warranty lasts, so the above limitation may not apply",
  "to Licensee. Gensym's sole obligation under this warranty shall be",
  "limited to using reasonable efforts to correct material, documented,",
  "reproducible defects in the unaltered NetSleuth that Licensee",
  "describes and documents to Gensym during the Warranty Period. In the",
  "event that Gensym fails to correct a material, documented,",
  "reproducible defect within a reasonable period, Gensym may, in",
  "Gensym's discretion, replace the defective NetSleuth software, or",
  "refund to Licensee the amount that Licensee paid Gensym for the",
  "defective NetSleuth software and cancel this agreement and the",
  "licenses granted herein. In such event, Licensee agrees to return to",
  "Gensym all copies of the Software. Some jurisdictions do not allow the",
  "exclusion or limitation of relief, incidental or consequential",
  "damages, so the above limitation or exclusion may not apply to",
  "Licensee. GENSYM DISCLAIMS ALL OTHER WARRANTIES, STATUTORY OR",
  "OTHERWISE EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO",
  "IMPLIED WARRANTIES OF PERFORMANCE OR MERCHANTABILITY, FITNESS FOR A",
  "PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT WITH RESPECT TO THE",
  "SOFTWARE, THE ACCOMPANYING WRITTEN MATERIALS AND THE PROVISION OF OR",
  "FAILURE TO PROVIDE SUPPORT SERVICES. YOU BEAR ALL RISK RELATING TO",
  "RESULTS AND PERFORMANCE OF NETSLEUTH. GENSYM DOES NOT WARRANT THAT",
  "NETSLEUTH WILL MEET YOUR REQUIREMENT, OPERATE WITHOUT INTERRUPTION, OR",
  "BE ERROR FREE. NO GENSYM AGENT OR THIRD PARTY IS AUTHORIZED TO MAKE",
  "ANY MODIFICATIONS OR ADDITION TO THIS LIMITED WARRANTY. THIS LIMITED",
  "WARRANTY GIVES LICENSEE SPECIFIC LEGAL RIGHTS AND YOU MAY HAVE OTHER",
  "RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION.",
  "",
  "3. MAINTENANCE AND SUPPORT",
  "",
  "Gensym has no obligation to provide maintenance for NetSleuth under",
  "this Agreement. Software Updates will be deemed Software hereunder and",
  "unless subject to terms of a specific update license, will be",
  "furnished to Licensee under the terms of this Agreement. Gensym will",
  "provide Licensee with limited technical support by electronic media",
  "for a period of one year after delivery of NetSleuth to Licensee.",
  "",
  "4. EVALUATION PROGRAM",
  "",
  "You may download an evaluation program which you may use for trial",
  "purposes only. You have 30 days from the delivery date to evaluate",
  "this program. If you decide to use this program after the 30 day trial",
  "period, you must obtain a license from Gensym. Programs licensed for",
  "evaluation purposes are provided \"as is\" and Gensym does not provide",
  "technical support or any warranties for this program.",
  "",
  "5. CONFIDENTIALITY",
  "",
  "NetSleuth is the confidential and proprietary property of Gensym",
  "and/or its licensors.  NetSleuth is protected by United States",
  "copyright law and international treaty. Unauthorized reproduction or",
  "distribution is subject to civil and criminal penalties. Licensee",
  "agrees to take adequate steps to protect NetSleuth from unauthorized",
  "disclosure or use.",
  "",
  "6. TERM, TERMINATION AND SURVIVAL",
  "",
  "(A) This Agreement will immediately terminate without notice if",
  "Licensee fails to comply with any obligation of this Agreement.",
  "",
  "(B) Upon termination, Licensee must immediately cease use of and",
  "destroy NetSleuth or, upon request from Gensym, return NetSleuth to",
  "Gensym.",
  "",
  "7. LIMITATION OF DAMAGES",
  "",
  "TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, GENSYM'S AGGREGATE",
  "LIABILITY TO LICENSEE OR TO ANY THIRD PARTY FOR CLAIMS RELATING TO",
  "THIS AGREEMENT, WHETHER FOR BREACH OR IN TORT, WILL BE LIMITED TO THE",
  "FEES PAID BY LICENSEE FOR SOFTWARE WHICH IS THE SUBJECT MATTER OF THE",
  "CLAIMS. IN NO EVENT WILL GENSYM BE LIABLE FOR ANY INDIRECT, PUNITIVE,",
  "SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGE IN CONNECTION",
  "WITH OR ARISING OUT OF THIS AGREEMENT (INCLUDING LOSS OF BUSINESS,",
  "REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE), HOWEVER IT",
  "ARISES, WHETHER FOR BREACH OR IN TORT, EVEN IF GENSYM HAS BEEN",
  "PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. LIABILITY FOR",
  "DAMAGES WILL BE LIMITED AND EXCLUDED, EVEN IF ANY EXCLUSIVE REMEDY",
  "PROVIDED FOR IN THIS AGREEMENT FAILS OF ITS ESSENTIAL PURPOSE. SOME",
  "JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF SPECIAL,",
  "INDIRECT, CONSEQUENTIAL, EXEMPLARY OR INCIDENTAL DAMAGES OR THE",
  "LIMITATION OF LIABILITY TO SPECIFIED AMOUNTS, SO THE ABOVE LIMITATION",
  "OR EXCLUSION MAY NOT APPLY TO YOU.",
  "",
  "8. U.S. GOVERNMENT RESTRICTED RIGHTS:",
  "",
  "NetSleuth is \"commercial computer software\" or \"commercial computer",
  "software documentation.\" If Licensee is a unit or agency of the",
  "United States Government, then the United States Government's rights",
  "with respect to NetSleuth are limited by the terms of this Agreement,",
  "pursuant to FAR ' 12.212(a) and/or DFARS ' 227.7202-1(a), as",
  "applicable.",
  "",
  "9. EXPORT LAW",
  "",
  "Licensee agrees that NetSleuth nor any product therefrom is being",
  "exported, is being acquired or will be acquired for, shipped,",
  "transferred, or reexported, directly or indirectly except as permitted",
  "by the laws and regulations of the United States and the laws and",
  "regulations of the jurisdiction in which you obtained NetSleuth.",
  "",
  "10. GOVERNING LAW",
  "",
  "This Agreement shall be governed by, and any arbitration hereunder",
  "shall apply, the laws of the Commonwealth of Massachusetts, U.S.A.,",
  "excluding (i) its conflicts of laws principles; (ii) the United",
  "Nations Convention on Contracts for the International Sale of Goods;",
  "(iii) the 1974 Convention on the Limitation Period in the",
  "International Sale of Goods (the \"1974 Convention\"); and (iv) the",
  "Protocol amending the 1974 Convention, done at Vienna April 11,",
  "1980. Any dispute, controversy or claim arising out of or relating to",
  "this Agreement or to a breach hereof, including its interpretation,",
  "performance or termination, shall be finally resolved by",
  "arbitration. The arbitration shall be conducted by three (3)",
  "arbitrators, one to be appointed by Gensym, one to be appointed by you",
  "and a third being nominated by the two arbitrators so selected or, if",
  "they cannot agree on a third arbitrator, by the President of the",
  "American Arbitration Association (\"AAA\"). The arbitration shall be",
  "conducted in English and in accordance with the commercial arbitration",
  "rules of the AAA, which shall administer the arbitration and act as",
  "appointing authority. The arbitration, including the rendering of the",
  "award, shall take place in Boston, Massachusetts, U.S.A. and shall be",
  "the exclusive forum for resolving such dispute, controversy or",
  "claim. The decision of the arbitrators shall be binding upon the",
  "parties hereto, and the expense of the arbitration (including without",
  "limitation the award of attorneys' fees to the prevailing party) shall",
  "be paid as the arbitrators determine. The decision of the arbitrators",
  "shall be executory, and judgment thereon may be entered by any court",
  "of competent jurisdiction. Notwithstanding anything contained in this",
  "paragraph to the contrary, Gensym shall have the right to institute",
  "judicial proceedings against you or anyone acting by, through or under",
  "you, in order to enforce Gensym's rights hereunder through reformation",
  "of contract, specific performance, injunction or similar equitable",
  "relief.",
  "",
  "11. NO ASSIGNMENT",
  "",
  "Licensee may not assign or otherwise transfer any of its rights or",
  "obligations under this Agreement, without the prior written consent of",
  "Gensym. Gensym may assign its right to payment and may assign this",
  "Agreement to an affiliated company.",
  "",
  "12. OFFICIAL LANGUAGE",
  "",
  "The official text of this Agreement is in the English language and any",
  "interpretation or construction of this Agreement will be based",
  "thereon. In the event that this Agreement or any documents or notices",
  "related to it are translated into any other language, the English",
  "language version will control.",
  "",
  "13. ENTIRE AGREEMENT",
  "",
  "This Agreement is the parties' entire agreement relating to NetSleuth.",
  "It supersedes all prior or contemporaneous oral or written",
  "communications, proposals, warranties, and representations with",
  "respect to its subject matter, and following Licensee's acceptance of",
  "this license by clicking on the \"YES\" or \"ACCEPT LICENSE",
  "AGREEMENT\" Button, will prevail over any conflicting or additional",
  "terms of any quote, order, acknowledgment, or any other communications",
  "by or between the parties. No modification to this Agreement will be",
  "binding, unless in writing and signed by an authorized representative",
  "of each party.",
  NULL
};

static char *generic_license_verbiage[] = {
  "By using this product, you indicate your acceptance of the terms and conditions",
  "of the Gensym Master End-User Software License Agreement. These terms apply to",
  "you and any subsequent licensee of this product.",
  NULL
};


static char *click_through_license_verbiage[] = {
"Gensym Corporation",
"Software License Agreement",
"",
"CAUTION: CAREFULLY READ THE TERMS AND CONDITIONS OF THIS AGREEMENT.  BY USING",
"THE ACCESS CODES TO ACTIVATE AND ACCESS THE SOFTWARE YOU (\"LICENSEE\") ARE",
"CONSENTING TO BE BOUND BY AND BECOME A PARTY TO THIS AGREEMENT.  GENSYM",
"CORPORATION (\"GENSYM\") IS PROVIDING THE SOFTWARE TO LICENSEE UNDER THESE TERMS",
"AND CONDITIONS ONLY.  ENTERING THE ACCESS CODES TO ACTIVATE THE SOFTWARE AND/OR",
"ANY USE BY LICENSEE OF THE SOFTWARE CONSTITUTES BINDING ACCEPTANCE OF THESE",
"TERMS AND CONDITIONS.  IF LICENSEE DOES NOT AGREE TO THESE TERMS AND",
"CONDITIONS, CLICK THE \"No\" BUTTON.  DO NOT PROCEED WITH INSTALLATION OF THE",
"SOFTWARE AND PROMPTLY RETURN THE SOFTWARE AND SOFTWARE DOCUMENTATION TO GENSYM",
"FOR A FULL REFUND OF THE LICENSE FEE PAID, IF ANY. THE TERM \"PROMPTLY\" AS USED",
"HEREIN SHALL MEAN NO LATER THAN TEN (10) DAYS FOLLOWING THE DELIVERY OF THE",
"SOFTWARE TO LICENSEE.",
"",
"1. DEFINITIONS.",
"",
"1.1 \"CSS\": means Gensym's annual, fee-based Customer Support Service plan for",
"   Licensed Software.  (Please refer to the Customer Support Services Addendum",
"   (\"CSS Addendum\") for additional information, terms and conditions at:",
"   http://www.Gensym.com/pdf/css_addendum.pdf).  Fees for the Licensed Software",
"   include one initial year of CSS and annual renewal of CSS is optional",
"   thereafter. Unless otherwise agreed in writing, CSS shall commence at the",
"   time of Licensed Software shipment. The CSS Addendum is an integral part of",
"   this Agreement and is incorporated herein.  Updates, upgrades, patches and",
"   other revisions provided to Licensee under CSS shall be considered Licensed",
"   Software and subject to the provisions of this Agreement.",
"",
"1.2 \"Gensym Quotation\": means a written document issued by Gensym that",
"   describes the Licensed Software, the Licensed Software Use, the Use Duration",
"   Period, and license fee.",
"",
"1.3 \"Licensed Software Use\": means the purpose for which the Licensed Software",
"   is licensed for use as specified in the Gensym Quotation including",
"   restrictions placed on its use, if applicable.",
"",
"1.4 \"Use Duration Period\": means the time period for which the Licensed",
"   Software is licensed for use as specified in the Gensym Quotation.",
"",
"2. LICENSE.  Subject to the terms and conditions contained herein, Gensym",
"   grants to Licensee a non-exclusive, non-transferable, limited license to use",
"   the software product(s) accompanying this Agreement and for which valid",
"   control codes have been issued by Gensym together with related manuals in",
"   written or electronic form provided by Gensym (\"Licensed Software\").  If",
"   Licensee receives Licensed Software in conjunction with a software",
"   application provided by a third party, the Licensed Software may only be",
"   used with or as part of such software application.",
"",
"3. SCOPE OF LICENSE.  Licensee may use the Licensed Software at the Licensed",
"   Software Use Location specified in the Gensym Quotation.  Each license",
"   granted herein allows Licensee to use the Licensed Software on a single CPU",
"   device at any one time.  The Licensed Software may be used solely for the",
"   Authorized Number of Users and solely for the Licensed Software Use, if any,",
"   set forth in the Gensym Quotation.  Licensee agrees that any use of Licensed",
"   Software for production, process control, or any other like application is",
"   at Licensee's sole risk.  Licensee acknowledges that the Licensed Software",
"   may contain control codes limiting Licensee's access to the Authorized",
"   Number of Users.",
"",
"Licensee may NOT:",
"",
"(a) make copies of the Licensed Software on any medium except one copy may be",
"    made solely for archival or emergency back-up purposes;",
"(b) use the Licensed Software in any computer service bureau or timesharing",
"    arrangement or transfer it to any third party;",
"(c) reverse engineer, disassemble, decompile, alter, or modify the Licensed",
"    Software in any way, or for any purpose;",
"(d) rent, license, or grant sublicenses, leases, or other rights in the",
"    Licensed Software or otherwise allow the Licensed Software to be accessed by",
"    another party;",
"(e) transfer, sell, assign or otherwise convey this Agreement, the Licensed",
"    Software, or any of the rights herein, directly or indirectly, to any third",
"    party without written permission of Gensym; or",
"(f) modify, eliminate, or circumvent any control codes in the Licensed",
"    Software.",
"",
"The foregoing notwithstanding, if the Licensed Software is licensed to Licensee",
"for use in a country which is a member of the European Community, Licensee may",
"reverse engineer and/or decompile the Licensed Software to the extent that",
"sufficient information is not available for the purpose of creating an",
"interoperable software program (but only for such purposes and to the extent",
"that sufficient information is not provided by Gensym upon written request).",
"Furthermore, Licensee is not restricted in a country which is a member of the",
"European Community from observing, studying or testing the functioning of the",
"Licensed Software solely in order to understand the ideas and principles which",
"underlie any element of the Licensed Software. Licensee may copy the Licensed",
"Software for installation and archival purposes only. Licensee is permitted to",
"make one archival copy to be used only in the event that the original media is",
"damaged beyond use. All copies of the Licensed Software shall bear the original",
"and unmodified intellectual property rights markings that appear on or in the",
"Licensed Software. Licensee may not copy nor allow others to copy the Licensed",
"Software for any other purpose. Licensee agrees not to remove any product",
"identification, copyright notices, or other notices or proprietary restrictions",
"from the Licensed Software.",
"",
"4. LICENSE DURATION PERIOD.  Unless a different Use Duration Period is",
"   specified in the Gensym Quotation, the Use Duration Period and the license",
"   granted hereunder shall be for a period of twelve (12) months.  Licensee",
"   will cease all use of the Licensed Software at the end of the Use Duration",
"   Period and shall return all Licensed Software to Gensym.  Licensee may",
"   extend the Use Duration Period by issuing an order to Gensym and paying an",
"   additional license fee; however, Licensee agrees that any extension of the",
"   Use Duration Period and Licensee's use of the Licensed Software during the",
"   Use Duration Period shall be subject to the terms and condition of this",
"   Agreement.  Licensee acknowledges that the Licensed Software may contain",
"   control codes limiting Licensee's access to the Licensed Software for the",
"   Use Duration Period.",
"",
"5. FEES.  Licensee must pay Gensym the license fees for the Licensed Software",
"   set forth in the Gensym Quotation.  CSS renewal fees are 15% of Gensym's",
"   list price for the Licensed Software at the Bronze support level and 25% of",
"   Gensym's list price for the Licensed Software at the Gold support level.",
"   Gensym's list prices shall be those in effect at the time of CSS",
"   renewal. Gensym reserves the right to modify its list prices at any time.",
"",
"6. INTELLECTUAL PROPERTY RIGHTS IN SOFTWARE.  Gensym or its licensors (or their",
"   licensors) own all right, title and interest in and to the Licensed Software",
"   and the Licensed Software is protected by copyright and constitutes valuable",
"   trade secrets and proprietary data of Gensym or its licensors.  Licensee",
"   shall not in any way disclose any part of the Licensed Software to any",
"   person or entity (except disclosure to Licensee's employees or",
"   sub-contractors as needed consistent with the Licensed Software Use).",
"   Licensee acknowledges it obtains no title to or ownership interest in the",
"   Licensed Software.",
"",
"7. LICENSE DURATION AND TERMINATION.  Licensee may use the Licensed Software",
"   for the License Duration Period or until such time as the license is",
"   terminated pursuant to this Section 7.  The license granted herein, and all",
"   of Gensym's obligations to perform under this Agreement, may be terminated:",
"",
"(a) by Gensym immediately without notice upon any breach of this Agreement",
"   relating to the license grant or the misappropriation of Gensym's",
"   intellectual property rights;",
"(b) by Gensym upon the failure of Licensee to make any payment due within ten",
"   (10) days after written notice of such failure;",
"(c) by Gensym immediately without notice upon the voluntary or involuntary",
"   bankruptcy, insolvency, or liquidation of Licensee; or",
"(d) by either party upon any other material default not described above by the",
"   other party and failure to cure that default within thirty (30) calendar",
"   days after receipt of written notice thereof.",
"",
"8. TERMINATION.",
"",
"8.1 Upon termination of this Agreement or expiration of the Use Duration",
"   Period, Licensee agrees to immediately return the original and all copies of",
"   the Licensed Software including any back-up copies thereof.  Termination",
"   will not excuse performance of Licensee's obligations under this Agreement",
"   including, without limitation, any accrued obligations for payment of fees.",
"",
"8.2 Licensee hereby grants Gensym or Gensym's agent the right of access to",
"   Licensee's facilities upon request during normal business hours, for the",
"   purpose of performing an audit to verify compliance with this Agreement",
"   including the authorized Licensed Software Use and the Authorized Number of",
"   Users.  This access for audit purposes shall be granted while this Agreement",
"   is in effect and for one year after its expiration or termination.",
"",
"9. INDEMNIFICATION.  Gensym, at its own expense, will defend any action brought",
"   against Licensee and shall indemnify Licensee for damages and expenses",
"   finally awarded against Licensee (including reasonable attorney fees) to the",
"   extent that such action is based on a claim that the Licensed Software used",
"   within the scope of this Agreement infringes any U.S. patent, copyright, or",
"   other intellectual property right, or misappropriates any trade secret",
"   provided that Gensym is notified as soon as is practicable, in writing, of",
"   such claim.  Gensym shall have the sole right to control the defense of all",
"   such claims, lawsuits, and other proceedings and have full and complete",
"   authority to negotiate, compromise and settle any such claims.  In no event",
"   shall Licensee attempt to settle any claim, lawsuit, or proceeding without",
"   Gensym's prior written approval.  If, as a result of any claim of",
"   infringement or misappropriation, Licensee is enjoined from using the",
"   Licensed Software, or if Gensym believes that use of the Licensed Software",
"   is likely to be enjoined, Gensym, at its option and expense may: (i) procure",
"   the right for Licensee to continue to use the Licensed Software, or (ii)",
"   replace or modify the Licensed Software so as to make it non-infringing.  If",
"   Gensym determines that neither of these two options is reasonably",
"   practicable, Gensym may terminate the license granted herein upon written",
"   notice and refund to Licensee the unamortized portion of the license fees",
"   paid hereunder based on three years straight-line amortization, such",
"   amortization to commence on the date of shipment of the Licensed Software.",
"   Gensym shall not have any obligation to defend or indemnify Licensee when",
"   the modification of the Licensed Software or the combination of the Licensed",
"   Software with non-Gensym products is a cause of the infringement or if the",
"   Licensed Software subject to the claim is a version for which Gensym has",
"   provided a non-infringing replacement.  The foregoing states the entire",
"   liability of Gensym with respect to infringement or misappropriation of any",
"   intellectual property rights caused by the Licensed Software or any parts",
"   thereof.",
"",
"10. LIMITED WARRANTY.",
"",
"10.1 Gensym warrants that for ninety (90) days from shipment of the Licensed",
"   Software:",
"(a) the physical media on which the Licensed Software is delivered will not be",
"   defective and the programs will be properly recorded upon the physical",
"   media; and,",
"(b) the Licensed Software will function substantially as described in the",
"   Licensed Software documentation.  Gensym cannot guarantee that the Licensed",
"   Software will be free from all software defects, bugs or errors.",
"10.2 If there is a breach of the warranty set forth in Section 10.1(a) or",
"   10.1(b), Gensym's only responsibility and Licensee's sole and exclusive",
"   remedy for any such breach of warranty or for any negligence relating to the",
"   Licensed Software, including without limitation as to any installation,",
"   maintenance, or enhancements, will be for Gensym to use reasonable efforts",
"   to correct reproducible technical errors or defects in the Licensed",
"   Software, and/or at Gensym's sole option, repair or replace all or any",
"   portions of the Licensed Software.  This limited warranty does not cover",
"   damage to Licensed Software resulting from accident, misuse, or modification",
"   by Licensee, its employees, agents or subcontractors, and is only valid if",
"   Gensym receives written notice of breach of warranty within the ninety (90)",
"   day warranty period.",
"10.3 EXCEPT AS PROVIDED IN SECTION 10.1, NO OTHER REPRESENTATIONS OR",
"   WARRANTIES, WHETHER EXPRESS OR IMPLIED, ARE MADE BY GENSYM OR GENSYM'S",
"   LICENSORS WITH RESPECT TO ANY LICENSED SOFTWARE, SOFTWARE DOCUMENTATION, OR",
"   SERVICES FURNISHED HEREUNDER. GENSYM HEREBY DISCLAIMS ALL IMPLIED",
"   WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,",
"   NONINFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE.",
"",
"11. LIMITATION OF LIABILITY.  IN NO EVENT WILL GENSYM OR GENSYM'S LICENSORS BE",
"   LIABLE TO LICENSEE OR ANY OTHER PARTY FOR LOST PROFITS OR FOR ANY",
"   CONSEQUENTIAL, SPECIAL, INCIDENTAL, PUNITIVE, OR OTHER INDIRECT DAMAGES",
"   WHICH MAY ARISE IN CONNECTION WITH THIS AGREEMENT OR ANY LICENSED SOFTWARE,",
"   DOCUMENTATION OR SERVICES, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,",
"   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR",
"   OTHERWISE), EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  IN NO EVENT",
"   WHATSOEVER SHALL GENSYM HAVE ANY LIABILITY UNDER THIS AGREEMENT FOR A",
"   CUMULATIVE AGGREGATE AMOUNT IN EXCESS OF LICENSE FEES PAID TO IT BY LICENSEE",
"   HEREUNDER FOR THE APPLICABLE LICENSED SOFTWARE, DOCUMENTATION OR SERVICES.",
"",
"11. EXPORT. Licensee shall not export or re-export the Licensed Software or any",
"   US source technical data acquired from Gensym or any portions thereof except",
"   in compliance with U.S. export laws, rules and regulations.  Licensee will",
"   indemnify Gensym from any loss, cost, damage, expense, fine or penalty",
"   resulting from Licensee's failure to comply with this Section.",
"",
"12. OTHER PROVISIONS.",
"",
"12.1 Payment terms are net thirty (30) calendar days after the Licensed",
"   Software is shipped to Licensee.  Late payment charges will be imposed at",
"   the lesser of 1% per month or the highest rate permitted by law.",
"",
"12.2 Licensed Software is shipped F.O.B. Gensym. All fees and prices are",
"   exclusive of shipping charges, tariffs, duties, sales, use, value added, and",
"   similar taxes.  Licensee will pay all such taxes and charges, or, in the",
"   case of taxes from which Licensee is exempt, provide Gensym with appropriate",
"   exemption certificates.  Licensee will indemnify Gensym from all claims,",
"   losses or damages in the event any Licensee exemption certificate is",
"   challenged by any taxing authority.  Licensee is not responsible for any",
"   income taxes levied against Gensym.  If Gensym pays taxes or duties on",
"   Licensee's behalf, Licensee will reimburse Gensym for all such payments.",
"",
"12.3 All Licensed Software offerings, prices, CSS, license and service fees are",
"   subject to change at any time without notice.",
"",
"12.4 If any part of this Agreement is held to be unenforceable, the remaining",
"   provisions shall continue in effect.  This Agreement shall inure to the",
"   benefit of Gensym's successors and assigns.",
" ",
"12.5 This Agreement, including the Gensym Quotation and CSS Addendum, represent",
"   the entire agreement between the parties and is governed by laws of the",
"   Commonwealth of Massachusetts, U.S.A., without regard to its choice of law",
"   principles, and without regard to the provisions of any state Uniform",
"   Computer Information Transactions Act or similar federal or state laws or",
"   regulations. The parties expressly disclaim the application of the United",
"   Nations Convention on Contracts for the International Sale of",
"   Goods. Exclusive jurisdiction and venue for all purposes hereunder shall be",
"   the courts of Middlesex County, Massachusetts and the parties accept such",
"   exclusive jurisdiction and venue. To the extent there are any terms and",
"   conditions contained in Licensee's purchase order or other documentation",
"   supplied by Licensee (\"Licensee Documents\"), the terms and conditions",
"   contained in the Licensee Documents shall be deemed to be stricken and the",
"   terms and conditions of this Agreement shall govern.  This Agreement has",
"   been drawn up in English at the express wish of the parties.  Le présent",
"   contrat a été rédigé en anglais à la demande expresse des parties.",
"",
"12.6 Notices from Licensee must be in writing and delivered to Gensym at: 6011",
"   West Courtyard Drive, Suite 300, Austin, TX 78730, USA.",
"   Notices to Licensee from Gensym will be delivered in writing to Licensee's",
"   address listed in the Gensym Quotation.",
"",
"12.7 Gensym shall not be liable for any delay or failure to deliver the",
"   Licensed Software for reasons beyond its reasonable control.",
"",
"12.8 The Licensed Software and related documentation are \"Commercial Items,\" as",
"   that term is defined at 48 C.F.R. Section 2.101, consisting of \"Commercial",
"   Computer Software\" and \"Commercial Computer Software Documentation,\" as such",
"   terms are used in 48 C.F.R. Section 12.212 or 48 C.F.R. Section 227.7202, as",
"   applicable.  Consistent with 48 C.F.R. Section 12.212 or 48 C.F.R. Section",
"   227.7202-1 through 227.7202-4, as applicable, the Commercial Computer",
"   Software and Commercial Computer Software Documentation are being licensed",
"   to U.S. Government Licensees (a) only as Commercial Items; and (b) only with",
"   those rights as are granted to all other Licensees pursuant to the terms and",
"   conditions herein.  Unpublished - rights reserved under the copyright laws",
"   of the United States.",
  NULL
};

#endif
