#!/bin/csh -f

# Check out the RTL files that we then copy into the
# gw/c directory.  Edit this script to include a CVS TAG
# if you are running behind the latest in that spinoff
# edit this to use the spin off you want.

set spinoff = /gensym/ab-9oct95-repos
set r = rtl/c
cd $SRCBOX
cvs -d $spinoff co $r/bigext.h
cvs -d $spinoff co $r/bignmint.h
cvs -d $spinoff co $r/bignum.h
cvs -d $spinoff co $r/c-ifuns.h
cvs -d $spinoff co $r/c-sdefs.h
cvs -d $spinoff co $r/clos.h
cvs -d $spinoff co $r/closinit.h
cvs -d $spinoff co $r/concatnt.h
cvs -d $spinoff co $r/config.h
cvs -d $spinoff co $r/core.h
cvs -d $spinoff co $r/cprim.h
cvs -d $spinoff co $r/defset.h
cvs -d $spinoff co $r/del-eq.h
cvs -d $spinoff co $r/dummy.h
cvs -d $spinoff co $r/equal.h
cvs -d $spinoff co $r/errors.h
cvs -d $spinoff co $r/evalrun.h
cvs -d $spinoff co $r/externs.h
cvs -d $spinoff co $r/ffi.h
cvs -d $spinoff co $r/filesys.h
cvs -d $spinoff co $r/format.h
cvs -d $spinoff co $r/funcall.h
cvs -d $spinoff co $r/gc.h
cvs -d $spinoff co $r/gcobjmap.h
cvs -d $spinoff co $r/gensym.h
cvs -d $spinoff co $r/hash.h
cvs -d $spinoff co $r/ifuns.h
cvs -d $spinoff co $r/initclos.h
cvs -d $spinoff co $r/initvars.h
cvs -d $spinoff co $r/inline.h
cvs -d $spinoff co $r/instance.h
cvs -d $spinoff co $r/kernel.h
cvs -d $spinoff co $r/keywords.h
cvs -d $spinoff co $r/lisplib.h
cvs -d $spinoff co $r/lists.h
cvs -d $spinoff co $r/longname.h
cvs -d $spinoff co $r/ltime.h
cvs -d $spinoff co $r/methargs.h
cvs -d $spinoff co $r/methcomb.h
cvs -d $spinoff co $r/no-pkg.h
cvs -d $spinoff co $r/numbers.h
cvs -d $spinoff co $r/object.h
cvs -d $spinoff co $r/runint.h
cvs -d $spinoff co $r/runtime.h
cvs -d $spinoff co $r/sdefs.h
cvs -d $spinoff co $r/seq_type.h
cvs -d $spinoff co $r/seqmodi.h
cvs -d $spinoff co $r/slotv.h
cvs -d $spinoff co $r/smcompat.h
cvs -d $spinoff co $r/some.h
cvs -d $spinoff co $r/specific.h
cvs -d $spinoff co $r/stat_arr.h
cvs -d $spinoff co $r/strminit.h
cvs -d $spinoff co $r/subtypep.h
cvs -d $spinoff co $r/svarargs.h
cvs -d $spinoff co $r/svargs.h
cvs -d $spinoff co $r/trivialp.h
cvs -d $spinoff co $r/uconfig.h
cvs -d $spinoff co $r/utime.h
cvs -d $spinoff co $r/values.h
cvs -d $spinoff co $r/varkey.h
cvs -d $spinoff co $r/wrapper.h




