/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gensym_gos_deploy_OnlineManager */

#ifndef _Included_com_gensym_gos_deploy_OnlineManager
#define _Included_com_gensym_gos_deploy_OnlineManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gensym_gos_deploy_OnlineManager_serialVersionUID
#define com_gensym_gos_deploy_OnlineManager_serialVersionUID 1LL
/*
 * Class:     com_gensym_gos_deploy_OnlineManager
 * Method:    jsolveNLP
 * Signature: ([D[D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_gensym_gos_deploy_OnlineManager_jsolveNLP
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
