 -- clear
PRINT '====================================================================='
PRINT '   ABTS DATABASE TABLES AND TEST DATA FOR Microsoft SQL Server'
PRINT '====================================================================='
set nocount    on
set dateformat mdy

USE abts
GO

if db_name() = 'abts'
   PRINT '''abts'' database created, and context now in use.'
else
   PRINT 'Error in abts_tables_mssql.SQL, ''USE abts'' failed!  Killing the SPID now.'
GO

PRINT 'Now at the create table section ....'
execute sp_dboption 'abts' ,'trunc. log on chkpt.' ,'true'
execute sp_dboption 'abts' ,'ANSI null default' ,'true'
GO


 -- =========================================
 --    TRIGGERS
 -- =========================================

 -- ====== ABTS_TRIGGER_TABLE

PRINT ' '
PRINT 'Creating table ABTS_TRIGGER_TABLE'
 
CREATE TABLE ABTS_TRIGGER_TABLE (
    MESSAGE       VARCHAR(128))
GO 

 -- ====== ABTS_TRIG_TEST1

CREATE TRIGGER ABTS_TRIG_TEST1 ON ABTS_TRIGGER_TABLE
FOR INSERT, UPDATE
AS
  EXECUTE g2odbc_ins_trigs 'ABTS_TRIG_VIATAB', 'Trigger Alert INSERT'
GO 

PRINT ' '
PRINT 'Granting Permissions'

GRANT ALL ON ABTS_EMP TO PUBLIC
GRANT ALL ON ABTS_EMP2 TO PUBLIC
GRANT ALL ON ABTS_MANY_COLUMNS TO PUBLIC
GRANT ALL ON ABTS_DATATYPES TO PUBLIC
GRANT ALL ON ABTS_TOOBIG_DATA TO PUBLIC
GRANT ALL ON ABTS_FUNCTION_DATA TO PUBLIC
GRANT ALL ON ABTS_EMPTY_TABLE TO PUBLIC
GRANT ALL ON ABTS_PERSONNEL TO PUBLIC
GRANT ALL ON ABTS_UNSUP_DTYPES TO PUBLIC
GRANT ALL ON ABTS_TEXT TO PUBLIC
GRANT ALL ON ABTS_FLOAT TO PUBLIC
GRANT ALL ON ABTS_INT TO PUBLIC
GRANT ALL ON ABTS_EMP_X2 TO PUBLIC
GRANT ALL ON ABTS_ROWS10K TO PUBLIC
GRANT ALL ON ABTS_SCRATCH TO PUBLIC
GRANT ALL ON ABTS_TRIGGER_TABLE TO PUBLIC
GO

GRANT CREATE TABLE TO PUBLIC
GRANT CREATE VIEW TO PUBLIC
GRANT CREATE RULE TO PUBLIC
GRANT CREATE DEFAULT TO PUBLIC
GRANT CREATE PROCEDURE TO PUBLIC
GO

UPDATE STATISTICS ABTS_EMP 
UPDATE STATISTICS ABTS_EMP2 
UPDATE STATISTICS ABTS_MANY_COLUMNS 
UPDATE STATISTICS ABTS_DATATYPES 
UPDATE STATISTICS ABTS_TOOBIG_DATA 
UPDATE STATISTICS ABTS_FUNCTION_DATA 
UPDATE STATISTICS ABTS_EMPTY_TABLE 
UPDATE STATISTICS ABTS_PERSONNEL 
UPDATE STATISTICS ABTS_UNSUP_DTYPES 
UPDATE STATISTICS ABTS_TEXT 
UPDATE STATISTICS ABTS_FLOAT 
UPDATE STATISTICS ABTS_INT 
UPDATE STATISTICS ABTS_EMP_X2 
UPDATE STATISTICS ABTS_ROWS10K 
UPDATE STATISTICS ABTS_SCRATCH 
UPDATE STATISTICS ABTS_TRIGGER_TABLE 
GO
PRINT ' '
PRINT 'All Done!'
