#! /bin/csh -f
if ( $#argv == 0 ) then
  echo "Usage: find-double-reclaims {g2, tw, or gsi command line}"
  exit 1
endif

if (-e trace.done) rm trace.done

cat - <<XXX >! trace.in
set output "cons-trace.out"
start tracing consing
continue
XXX

setenv G2_TRACE_CONTROL_FILE "trace.in"

echo "Starting G2 ..."

$*


