/* chars2.h -- Header File for chars2.c
 * Copyright (c) 1986 - 2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object g2int_gensym_jis_code_to_contiguous(Object);
extern Object g2int_gensym_ksc_code_to_contiguous(Object);
extern Object g2int_legal_gensym_jis_character_code_p(Object);
extern Object g2int_legal_gensym_ksc_character_code_p(Object);
extern Object g2int_map_gensym_han_character_code_to_unicode(Object);
extern Object g2int_map_unicode_to_gensym_character_code_with_cjk_neutrality(Object);
extern Object g2int_map_unicode_to_gensym_han_character_code(Object);
extern Object g2int_unicode_han_character_p(Object);
extern Object g2int_wide_character_is_simple_gensym_character_p(Object);
extern Object g2int_wide_character_p_function(Object);

#else

extern Object g2int_gensym_jis_code_to_contiguous();
extern Object g2int_gensym_ksc_code_to_contiguous();
extern Object g2int_legal_gensym_jis_character_code_p();
extern Object g2int_legal_gensym_ksc_character_code_p();
extern Object g2int_map_gensym_han_character_code_to_unicode();
extern Object g2int_map_unicode_to_gensym_character_code_with_cjk_neutrality();
extern Object g2int_map_unicode_to_gensym_han_character_code();
extern Object g2int_unicode_han_character_p();
extern Object g2int_wide_character_is_simple_gensym_character_p();
extern Object g2int_wide_character_p_function();

#endif

/* variables/constants */
extern Object G2int_current_extended_utf_g_low_half_characterqm;
extern Object G2int_gensym_char_or_code_for_bullet;
extern Object G2int_gensym_char_or_code_for_capital_ligature_oe;
extern Object G2int_gensym_char_or_code_for_linebreak;
extern Object G2int_gensym_char_or_code_for_paragraph_break;
extern Object G2int_gensym_char_or_code_for_small_letter_f_with_hook;
extern Object G2int_gensym_char_or_code_for_small_ligature_oe;
extern Object G2int_gensym_char_or_code_for_trade_mark_sign;
extern Object G2int_gensym_code_for_bullet;
extern Object G2int_gensym_code_for_capital_ligature_oe;
extern Object G2int_gensym_code_for_linebreak;
extern Object G2int_gensym_code_for_paragraph_break;
extern Object G2int_gensym_code_for_small_letter_f_with_hook;
extern Object G2int_gensym_code_for_small_ligature_oe;
extern Object G2int_gensym_code_for_trade_mark_sign;
extern Object G2int_gensym_esc_for_bulletqm;
extern Object G2int_gensym_esc_for_capital_ligature_oeqm;
extern Object G2int_gensym_esc_for_linebreakqm;
extern Object G2int_gensym_esc_for_paragraph_breakqm;
extern Object G2int_gensym_esc_for_small_letter_f_with_hookqm;
extern Object G2int_gensym_esc_for_small_ligature_oeqm;
extern Object G2int_gensym_esc_for_trade_mark_signqm;
extern Object G2int_han_interpretation_mode;
#define G2int_invalid_gensym_full_row FIX((SI_Long)246L)
extern Object G2int_jis_x_0208_to_unicode_map;
extern Object G2int_ks_c_5601_to_unicode_map;
#define G2int_pct0 FIX((SI_Long)48L)
#define G2int_pct1 FIX((SI_Long)49L)
#define G2int_pct2 FIX((SI_Long)50L)
#define G2int_pct3 FIX((SI_Long)51L)
#define G2int_pct4 FIX((SI_Long)52L)
#define G2int_pct5 FIX((SI_Long)53L)
#define G2int_pct6 FIX((SI_Long)54L)
#define G2int_pct7 FIX((SI_Long)55L)
#define G2int_pct8 FIX((SI_Long)56L)
#define G2int_pct9 FIX((SI_Long)57L)
#define G2int_pct_ FIX((SI_Long)45L)
#define G2int_pcta FIX((SI_Long)65L)
#define G2int_pctand FIX((SI_Long)38L)
#define G2int_pctat FIX((SI_Long)64L)
#define G2int_pctb FIX((SI_Long)66L)
#define G2int_pctbq FIX((SI_Long)96L)
#define G2int_pctbs FIX((SI_Long)92L)
#define G2int_pctbullet FIX((SI_Long)8226L)
#define G2int_pctc FIX((SI_Long)67L)
#define G2int_pctcapital_ligature_oe FIX((SI_Long)338L)
#define G2int_pctcb FIX((SI_Long)125L)
#define G2int_pctcbt FIX((SI_Long)93L)
#define G2int_pctcent_sign FIX((SI_Long)162L)
#define G2int_pctcm FIX((SI_Long)44L)
#define G2int_pctcol FIX((SI_Long)58L)
#define G2int_pctcopyright_sign FIX((SI_Long)169L)
#define G2int_pctcp FIX((SI_Long)41L)
#define G2int_pctct FIX((SI_Long)94L)
#define G2int_pctd FIX((SI_Long)68L)
#define G2int_pctdol FIX((SI_Long)36L)
#define G2int_pctdot FIX((SI_Long)46L)
#define G2int_pctdq FIX((SI_Long)34L)
#define G2int_pcte FIX((SI_Long)69L)
#define G2int_pctem_space FIX((SI_Long)8193L)
#define G2int_pcten_space FIX((SI_Long)8194L)
#define G2int_pcteq FIX((SI_Long)61L)
#define G2int_pctesc FIX((SI_Long)27L)
#define G2int_pctescape FIX((SI_Long)27L)
#define G2int_pcteuro_sign FIX((SI_Long)8364L)
#define G2int_pctex FIX((SI_Long)33L)
#define G2int_pctf FIX((SI_Long)70L)
#define G2int_pctfixed_width_space FIX((SI_Long)8199L)
#define G2int_pctg FIX((SI_Long)71L)
#define G2int_pctgt FIX((SI_Long)62L)
#define G2int_pcth FIX((SI_Long)72L)
#define G2int_pcthair_space FIX((SI_Long)8202L)
#define G2int_pcti FIX((SI_Long)73L)
#define G2int_pctinverted_exclamation_point FIX((SI_Long)161L)
#define G2int_pctinverted_question_mark FIX((SI_Long)191L)
#define G2int_pctj FIX((SI_Long)74L)
#define G2int_pctk FIX((SI_Long)75L)
#define G2int_pctl FIX((SI_Long)76L)
#define G2int_pctlatin_small_letter_f_with_hook FIX((SI_Long)402L)
#define G2int_pctleft_pointing_double_angle_quotation_mark FIX((SI_Long)171L)
#define G2int_pctline_separator FIX((SI_Long)8232L)
#define G2int_pctlinefeed FIX((SI_Long)10L)
#define G2int_pctlt FIX((SI_Long)60L)
#define G2int_pctm FIX((SI_Long)77L)
#define G2int_pctn FIX((SI_Long)78L)
#define G2int_pctnewline FIX((SI_Long)10L)
#define G2int_pctno FIX((SI_Long)35L)
#define G2int_pctno_break_space FIX((SI_Long)160L)
#define G2int_pctnull FIX((SI_Long)0L)
#define G2int_pcto FIX((SI_Long)79L)
#define G2int_pctob FIX((SI_Long)123L)
#define G2int_pctobt FIX((SI_Long)91L)
#define G2int_pctop FIX((SI_Long)40L)
#define G2int_pctor FIX((SI_Long)124L)
#define G2int_pctordinary_space FIX((SI_Long)32L)
#define G2int_pctp FIX((SI_Long)80L)
#define G2int_pctpage FIX((SI_Long)12L)
#define G2int_pctparagraph_separator FIX((SI_Long)8233L)
#define G2int_pctpct FIX((SI_Long)37L)
#define G2int_pctplus FIX((SI_Long)43L)
#define G2int_pctpound_sign FIX((SI_Long)163L)
#define G2int_pctq FIX((SI_Long)81L)
#define G2int_pctqm FIX((SI_Long)63L)
#define G2int_pctqu FIX((SI_Long)39L)
#define G2int_pctr FIX((SI_Long)82L)
#define G2int_pctregistered_sign FIX((SI_Long)174L)
#define G2int_pctreturn FIX((SI_Long)13L)
#define G2int_pctright_pointing_double_angle_quotation_mark FIX((SI_Long)187L)
#define G2int_pcts FIX((SI_Long)83L)
#define G2int_pctsc FIX((SI_Long)59L)
#define G2int_pctsl FIX((SI_Long)47L)
#define G2int_pctsmall_ligature_oe FIX((SI_Long)339L)
#define G2int_pctsoft_hyphen FIX((SI_Long)173L)
#define G2int_pctsp FIX((SI_Long)32L)
#define G2int_pctspace FIX((SI_Long)32L)
#define G2int_pctstar FIX((SI_Long)42L)
#define G2int_pctt FIX((SI_Long)84L)
#define G2int_pcttab FIX((SI_Long)9L)
#define G2int_pctthin_space FIX((SI_Long)8201L)
#define G2int_pcttl FIX((SI_Long)126L)
#define G2int_pcttrade_mark_sign FIX((SI_Long)8482L)
#define G2int_pctu FIX((SI_Long)85L)
#define G2int_pctv FIX((SI_Long)86L)
#define G2int_pctw FIX((SI_Long)87L)
#define G2int_pctx FIX((SI_Long)88L)
#define G2int_pcty FIX((SI_Long)89L)
#define G2int_pctyen_sign FIX((SI_Long)165L)
#define G2int_pctz FIX((SI_Long)90L)
#define G2int_pctzero_width_joiner FIX((SI_Long)8205L)
#define G2int_pctzero_width_no_break_space FIX((SI_Long)65279L)
#define G2int_pctzero_width_space FIX((SI_Long)8203L)
extern Object G2int_unicode_to_gensym_full_row_map;
extern Object G2int_unicode_to_jis_x_0208_map;
extern Object G2int_unicode_to_ks_c_5601_map;
#define ab_G2int_pct_ FIX((SI_Long)95L)
#define ab_G2int_pcta FIX((SI_Long)97L)
#define ab_G2int_pctb FIX((SI_Long)98L)
#define ab_G2int_pctc FIX((SI_Long)99L)
#define ab_G2int_pctd FIX((SI_Long)100L)
#define ab_G2int_pcte FIX((SI_Long)101L)
#define ab_G2int_pctf FIX((SI_Long)102L)
#define ab_G2int_pctg FIX((SI_Long)103L)
#define ab_G2int_pcth FIX((SI_Long)104L)
#define ab_G2int_pcti FIX((SI_Long)105L)
#define ab_G2int_pctj FIX((SI_Long)106L)
#define ab_G2int_pctk FIX((SI_Long)107L)
#define ab_G2int_pctl FIX((SI_Long)108L)
#define ab_G2int_pctm FIX((SI_Long)109L)
#define ab_G2int_pctn FIX((SI_Long)110L)
#define ab_G2int_pcto FIX((SI_Long)111L)
#define ab_G2int_pctp FIX((SI_Long)112L)
#define ab_G2int_pctq FIX((SI_Long)113L)
#define ab_G2int_pctr FIX((SI_Long)114L)
#define ab_G2int_pcts FIX((SI_Long)115L)
#define ab_G2int_pctsp FIX((SI_Long)32L)
#define ab_G2int_pctt FIX((SI_Long)116L)
#define ab_G2int_pctu FIX((SI_Long)117L)
#define ab_G2int_pctv FIX((SI_Long)118L)
#define ab_G2int_pctw FIX((SI_Long)119L)
#define ab_G2int_pctx FIX((SI_Long)120L)
#define ab_G2int_pcty FIX((SI_Long)121L)
#define ab_G2int_pctz FIX((SI_Long)122L)
