@echo off

set FAMILY_NAME=g2
set VERSION_TAG=84r1
set FAMILY=%FAMILY_NAME%-%VERSION_TAG%
set DSTBOX=%SRCBOX%\dst\%MACHINE%
set PATH=%PATH%;%SRCBOX%\UTIL

SET SCRIPTBATFILE=%SRCBOX%\bundle\tools\buildis.bat

echo ****************
echo Script: %SCRIPTBATFILE%
echo Building InstallShield Setup for %FAMILY%
echo ****************

set STAGE_DIR=%SRCBOX%\bundle\stage
set INSTALLPROJECT_DIR_NAME=isproj-%FAMILY%


rem Parts of this file is generated by InstallShield IDE.

rem ===============================================
rem Set up tools.
rem ===============================================

set COMPILER=C:\Program Files\Common Files\InstallShield\IScript\Compile.exe
set BUILDER=%IS_HOME%\Program\isbuild.exe

rem ===============================================
rem Set the environment for the compiler
rem ===============================================

set INSTALLPROJECT_DIR=%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%
set INSTALLPROJECT=%INSTALLPROJECT_DIR%\gensym.ipr
set CURRENTBUILD=Default

set INCLUDEIFX=%IS_HOME%\Script\Ifx\Include
set INCLUDEISRT=%IS_HOME%\Script\Isrt\Include
set INCLUDESCRIPT=%INSTALLPROJECT_DIR%\Script Files
set LINKPATHS=-LibPath"%IS_HOME%\Script\Ifx\Lib" -LibPath"%IS_HOME%\Script\Isrt\Lib" 
set RULFILES=%INSTALLPROJECT_DIR%\Script Files\setup.rul
set LIBRARIES="isrt.obl" "ifx.obl" 
set DEFINITIONS=
set SWITCHES=-w50 -e50 -v3 -g

rem ==================================================
rem Compile
rem ==================================================
echo running this:
echo "%COMPILER%" "%RULFILES%" -I"%INCLUDEIFX%" -I"%INCLUDEISRT%" -I"%INCLUDESCRIPT%" %LINKPATHS% %LIBRARIES% %DEFINITIONS% %SWITCHES%
"%COMPILER%" "%RULFILES%" -I"%INCLUDEIFX%" -I"%INCLUDEISRT%" -I"%INCLUDESCRIPT%" %LINKPATHS% %LIBRARIES% %DEFINITIONS% %SWITCHES%

if ERRORLEVEL 1 goto InstallShieldCompileError

rem ==================================================
rem build -- we pass in the -s (silent option). -mhd
rem ==================================================
rem Silent mode:
rem   "%BUILDER%" -s -p"%INSTALLPROJECT%" -m"%CURRENTBUILD%" 
"%BUILDER%" -p"%INSTALLPROJECT%" -m"%CURRENTBUILD%" 
echo Finished compiling and building.
echo   Project file is "%INSTALLPROJECT%".
echo   Exiting buildis.bat
goto end

:InstallShieldCompileError
echo InstallShieldCompileError
goto end

:end
