@echo off

rem Usage: buildipr family_name version_tag
rem   E.g., buildipr  84r1
rem
rem This script builds an IPR (InstallShield Project Repository)
rem for Gensym's bundled product G2 Classic.  In the future, this
rem should probably be broken into several scripts and further
rem generalized.  For now, it is intended to run on the G2 group's
rem Windows 2000 system "2000test".

setlocal

echo Building InstallShield Project Repository for %FAMILY%
set FAMILY_NAME=g2
set VERSION_TAG=%1
set FAMILY=%FAMILY_NAME%-%VERSION_TAG%
set vsbin=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin
set PATH=%PATH%;%SRCBOX%\UTIL;%vsbin%
SET SCRIPTBATFILE=%SRCBOX%\bundle\tools\buildis.bat

echo ****************
echo Script: %SCRIPTBATFILE%
echo Building InstallShield Setup for %FAMILY%
echo ****************

set STAGE_DIR=%SRCBOX%\bundle\stage
set INSTALLPROJECT_DIR_NAME=isproj-%FAMILY%


rem Parts of this file is generated by InstallShield IDE.

rem ===============================================
rem Set up tools.
rem ===============================================

set IS_HOME=C:\Program Files (x86)\InstallShield\2013 SAB
set COMPILER=%IS_HOME%\System\Compile.exe
set BUILDER=%IS_HOME%\System\IsCmdBld.exe

rem ===============================================
rem Set the environment for the compiler
rem ===============================================

set INSTALLPROJECT_DIR=%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%
set INSTALLPROJECT=%INSTALLPROJECT_DIR%\gensym.ipr
set CURRENTBUILD=Default

set INCLUDEIFX=%IS_HOME%\Script\Ifx\Include
set INCLUDEISRT=%IS_HOME%\Script\Isrt\Include
set INCLUDESCRIPT=%INSTALLPROJECT_DIR%\Script Files
set LINKPATHS=-LibPath"%IS_HOME%\Script\Ifx\Lib" -LibPath"%IS_HOME%\Script\Isrt\Lib" 
set RULFILES=%INSTALLPROJECT_DIR%\Script Files\Setup.rul
set LIBRARIES="isrt.obl" "ifx.obl" 
set DEFINITIONS=
set SWITCHES=-w50 -e50 -v3 -g

echo ****************
echo Setting up VC++ environment variables . . .
@echo on
set MSVC=C:\Program Files (x86)\Microsoft Visual Studio 10.0
set INCLUDE=%MSVC%\VC\include
set LIB=%MSVC%\VC\lib
set STRANGELY_NEEDED_VB=

rem We don't know why, but for some reason MSPDB60.DLL is needed in the compile!
rem And that's what this is doing here:   -mhd
set STRANGELY_NEEDED_VB=%MSVC%\VB98

set PATH=%MSVC%\VC\bin;%MSVC%\Common7\IDE;%STRANGELY_NEEDED_VB%;%INCLUDE%;%PATH%
@echo off

SET SCRIPTBATFILE=%SRCBOX%\bundle\tools\buildipr.bat

echo ****************
echo Script: %SCRIPTBATFILE%
echo ****************

echo Setting up other environment variables . . .
@echo on
set PATH=%PATH%;%SRCBOX%\util

set STAGE_DIR=%SRCBOX%\bundle\stage
set INSTALLPROJECT_DIR_NAME=isproj-%FAMILY%
set INSTALLPROJECT_DIR=%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%
set INSTALLPROJECT=%INSTALLPROJECT_DIR%\gensym.ipr

set TOOLS_DIR=%SRCBOX%\bundle\tools
set C_DIR=%SRCBOX%\bundle\c
set FAMILY_FILE=%SRCBOX%\tools\datafiles\families\%FAMILY%.fam
set TREE_DIR=%STAGE_DIR%\%MACHINE%-%FAMILY%
set SBCL_HOME=%SRCBOX%\tools\lisp\sbcl-1.3.7
set SBCL=%SBCL_HOME%\sbcl.exe --no-userinit

set ZIP_FILE_NAME=%MACHINE%.zip

@echo off

rem note: don't run this as administrator, it doesn't work.

echo Generating %FAMILY_FILE%...
if "%2" == "std" echo (load "fam-script-loader.lisp") (in-package :bundle) (format t "new-fam-script-loader") (new-fam-script-loader '%FAMILY%) (make-%FAMILY%-fam "%FAMILY%.fam") (quit) | %SBCL% > %FAMILY_FILE%.log
if "%2" == "ent" echo (pushnew :enterprise *features*) (load "fam-script-loader.lisp") (in-package :bundle) (format t "new-fam-script-loader") (new-fam-script-loader '%FAMILY%) (make-%FAMILY%-fam "%FAMILY%.fam") (quit) | %SBCL% > %FAMILY_FILE%.log
copy /y "%FAMILY%.fam" %FAMILY_FILE%
del /q "%FAMILY%.fam"

echo Making sure "%STAGE_DIR%" exists ...

if not exist "%STAGE_DIR%" mkdir "%STAGE_DIR%"

if exist %STAGE_DIR%\%ZIP_FILE_NAME%  goto SKIPFTP
if not exist %STAGE_DIR%\%ZIP_FILE_NAME% goto USEFTP

:SKIPFTP

echo %ZIP_FILE_NAME% file already exists on local machine,we use this file instead of FTP'ing it from unix box.
goto UNZIPBUNDLE

:USEFTP

REM write code to get the intelnt.zip file from unix machine to windows machine and put it in %STAGE_DIR% 

set UNIX_HOST=burlington
set UNIX_DIR=/gensym/bundles
set TREE_ZIP=%UNIX_DIR%/%FAMILY_NAME%/%VERSION_TAG%/tar/%ZIP_FILE_NAME%

echo *********************************
echo FTP'ing from unix host %UNIX_HOST%
echo   %TOOLS_DIR%\wget -nv -P %STAGE_DIR% ftp://ab:gensym@burlington//%TREE_ZIP%
%TOOLS_DIR%\wget -nv -P %STAGE_DIR% ftp://ab:gensym@burlington//%TREE_ZIP%

goto UNZIPBUNDLE

:UNZIPBUNDLE

echo Deleting %TREE_DIR% with rmdir /s /q %TREE_DIR% 
rmdir /s /q %TREE_DIR% 

echo Unzipping %ZIP_FILE_NAME% to %TREE_DIR%
%TOOLS_DIR%\unzip -q -o %STAGE_DIR%\%ZIP_FILE_NAME% -d %TREE_DIR%

echo Copy OBF files into %TREE_DIR%
rem copy %SRCBOX%\bundle\ok\*v11*.obf %TREE_DIR%\g2
rem copy %SRCBOX%\bundle\ok\g2-2011-megabundle.obf %TREE_DIR%\g2

echo Deleting %STAGE_DIR%\%INSTALLPROJECT_DIR_NAME% with rmdir /s /q %STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%

rmdir /s /q %STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%

rem xcopy "%SRCBOX%\bundle\ishield\isproj" "%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%\" /S /E /Y
if "%2" == "std" xcopy "%SRCBOX%\bundle\ishield\isproj-g2-2015-std" "%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%\" /S /E /Y
if "%2" == "ent" xcopy "%SRCBOX%\bundle\ishield\isproj-g2-2015-ent" "%STAGE_DIR%\%INSTALLPROJECT_DIR_NAME%\" /S /E /Y

echo Building the Install Generator (%C_DIR%\InstallGenerator.exe)

msbuild %C_DIR%\InstallGenerator.sln /m /t:Rebuild /p:Configuration=Release

echo Running install generator
rem %C_DIR%\Release\InstallGenerator "%FAMILY_FILE%" "%INSTALLPROJECT%" "%TREE_DIR%" %2

goto end

:end

echo successfully completed the buildipr.bat execution.

endlocal
