#/bin/sh
CFLAGS="-D__MINGW32__ -D__MSVCRT__ -D__MSVCRT_VERSION__=0x700 -D_WIN32_WINNT=0x0502";export CFLAGS
rm -rf usr
echo "Warnings about system header pragmas being ignored can themselves be ignored."
h-to-ffi.sh -Dtrue=1 -Dfalse=0 /usr/include/mingw/assert.h
h-to-ffi.sh /usr/include/mingw/complex.h
h-to-ffi.sh /usr/include/mingw/conio.h
h-to-ffi.sh /usr/include/mingw/ctype.h
h-to-ffi.sh /usr/include/mingw/dir.h
h-to-ffi.sh /usr/include/mingw/direct.h
h-to-ffi.sh /usr/include/mingw/dirent.h
h-to-ffi.sh /usr/include/mingw/dos.h
h-to-ffi.sh /usr/include/mingw/errno.h
h-to-ffi.sh /usr/include/mingw/excpt.h
h-to-ffi.sh /usr/include/mingw/fcntl.h
h-to-ffi.sh /usr/include/mingw/fenv.h
h-to-ffi.sh /usr/include/mingw/float.h
h-to-ffi.sh /usr/include/mingw/getopt.h
h-to-ffi.sh /usr/include/mingw/gmon.h
h-to-ffi.sh /usr/include/mingw/inttypes.h
h-to-ffi.sh /usr/include/mingw/io.h
h-to-ffi.sh /usr/include/mingw/libgen.h
h-to-ffi.sh /usr/include/mingw/limits.h
h-to-ffi.sh /usr/include/mingw/locale.h
h-to-ffi.sh /usr/include/mingw/malloc.h
h-to-ffi.sh /usr/include/mingw/math.h
h-to-ffi.sh /usr/include/mingw/mbctype.h
h-to-ffi.sh /usr/include/mingw/mbstring.h
h-to-ffi.sh /usr/include/mingw/mem.h
h-to-ffi.sh /usr/include/mingw/memory.h
h-to-ffi.sh /usr/include/mingw/process.h
#h-to-ffi.sh -/usr/include/mingw/profil.h
h-to-ffi.sh /usr/include/mingw/profile.h
h-to-ffi.sh /usr/include/mingw/search.h
h-to-ffi.sh /usr/include/mingw/setjmp.h
h-to-ffi.sh /usr/include/mingw/share.h
h-to-ffi.sh /usr/include/mingw/signal.h
h-to-ffi.sh /usr/include/mingw/stdint.h
h-to-ffi.sh /usr/include/mingw/stdio.h
h-to-ffi.sh /usr/include/mingw/stdlib.h
h-to-ffi.sh /usr/include/mingw/string.h
h-to-ffi.sh /usr/include/mingw/strings.h
h-to-ffi.sh /usr/include/mingw/sys/fcntl.h
h-to-ffi.sh /usr/include/mingw/sys/file.h
h-to-ffi.sh /usr/include/mingw/sys/locking.h
h-to-ffi.sh /usr/include/mingw/sys/param.h
h-to-ffi.sh /usr/include/mingw/sys/stat.h
h-to-ffi.sh /usr/include/mingw/sys/time.h
h-to-ffi.sh /usr/include/mingw/sys/timeb.h
h-to-ffi.sh /usr/include/mingw/sys/types.h
h-to-ffi.sh /usr/include/mingw/sys/unistd.h
h-to-ffi.sh /usr/include/mingw/sys/utime.h
h-to-ffi.sh /usr/include/mingw/tchar.h
h-to-ffi.sh /usr/include/mingw/time.h
h-to-ffi.sh /usr/include/mingw/unistd.h
h-to-ffi.sh /usr/include/mingw/utime.h
h-to-ffi.sh /usr/include/mingw/values.h
#h-to-ffi.sh /usr/include/mingw/varargs.h
h-to-ffi.sh /usr/include/mingw/wchar.h
h-to-ffi.sh /usr/include/mingw/wctype.h
h-to-ffi.sh /usr/include/mingw/_mingw.h
h-to-ffi.sh -include /usr/include/w32api/windows.h /usr/include/w32api/ws2tcpip.h
#
# It's possible that some of these files contain useful info, can
# be parsed, and aren't include by windows.h.
#
#h-to-ffi.sh /usr/include/w32api/accctrl.h
#h-to-ffi.sh /usr/include/w32api/aclapi.h
#h-to-ffi.sh /usr/include/w32api/aclui.h
#h-to-ffi.sh /usr/include/w32api/adsprop.h
#h-to-ffi.sh /usr/include/w32api/afxres.h
#h-to-ffi.sh /usr/include/w32api/amaudio.h
#h-to-ffi.sh /usr/include/w32api/amvideo.h
#h-to-ffi.sh /usr/include/w32api/audevcod.h
#h-to-ffi.sh /usr/include/w32api/aviriff.h
#h-to-ffi.sh /usr/include/w32api/aygshell.h
#h-to-ffi.sh /usr/include/w32api/basetsd.h
#h-to-ffi.sh /usr/include/w32api/basetyps.h
#h-to-ffi.sh /usr/include/w32api/bdatypes.h
#h-to-ffi.sh /usr/include/w32api/cderr.h
#h-to-ffi.sh /usr/include/w32api/cguid.h
#h-to-ffi.sh /usr/include/w32api/cmnquery.h
#h-to-ffi.sh /usr/include/w32api/comcat.h
#h-to-ffi.sh /usr/include/w32api/commctrl.h
#h-to-ffi.sh /usr/include/w32api/commdlg.h
#h-to-ffi.sh /usr/include/w32api/control.h
#h-to-ffi.sh /usr/include/w32api/cpl.h
#h-to-ffi.sh /usr/include/w32api/cplext.h
#h-to-ffi.sh /usr/include/w32api/custcntl.h
#h-to-ffi.sh /usr/include/w32api/d3d9.h
#h-to-ffi.sh /usr/include/w32api/d3d9caps.h
#h-to-ffi.sh /usr/include/w32api/d3d9types.h
#h-to-ffi.sh /usr/include/w32api/dbt.h
#h-to-ffi.sh /usr/include/w32api/dde.h
#h-to-ffi.sh /usr/include/w32api/ddeml.h
#h-to-ffi.sh /usr/include/w32api/ddk/atm.h
#h-to-ffi.sh /usr/include/w32api/ddk/batclass.h
#h-to-ffi.sh /usr/include/w32api/ddk/cfg.h
#h-to-ffi.sh /usr/include/w32api/ddk/cfgmgr32.h
#h-to-ffi.sh /usr/include/w32api/ddk/d4drvif.h
#h-to-ffi.sh /usr/include/w32api/ddk/d4iface.h
#h-to-ffi.sh /usr/include/w32api/ddk/ddkmapi.h
#h-to-ffi.sh /usr/include/w32api/ddk/hidclass.h
#h-to-ffi.sh /usr/include/w32api/ddk/hidpi.h
#h-to-ffi.sh /usr/include/w32api/ddk/hidsdi.h
#h-to-ffi.sh /usr/include/w32api/ddk/hidusage.h
#h-to-ffi.sh /usr/include/w32api/ddk/kbdmou.h
#h-to-ffi.sh /usr/include/w32api/ddk/mcd.h
#h-to-ffi.sh /usr/include/w32api/ddk/miniport.h
#h-to-ffi.sh /usr/include/w32api/ddk/minitape.h
#h-to-ffi.sh /usr/include/w32api/ddk/mountdev.h
#h-to-ffi.sh /usr/include/w32api/ddk/mountmgr.h
#h-to-ffi.sh /usr/include/w32api/ddk/ndis.h
#h-to-ffi.sh /usr/include/w32api/ddk/ndisguid.h
#h-to-ffi.sh /usr/include/w32api/ddk/ndistapi.h
#h-to-ffi.sh /usr/include/w32api/ddk/ndiswan.h
#h-to-ffi.sh /usr/include/w32api/ddk/netevent.h
#h-to-ffi.sh /usr/include/w32api/ddk/netpnp.h
#h-to-ffi.sh /usr/include/w32api/ddk/newdev.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntapi.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntdd8042.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddbeep.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddcdrm.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddcdvd.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddchgr.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntdddisk.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddk.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddkbd.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddmou.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddndis.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddpar.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddpcm.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddscsi.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddser.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddstor.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddtape.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddtdi.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddvdeo.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntddvol.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntifs.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntpoapi.h
#h-to-ffi.sh /usr/include/w32api/ddk/ntstatus.h
#h-to-ffi.sh /usr/include/w32api/ddk/parallel.h
#h-to-ffi.sh /usr/include/w32api/ddk/pfhook.h
#h-to-ffi.sh /usr/include/w32api/ddk/poclass.h
#h-to-ffi.sh /usr/include/w32api/ddk/scsi.h
#h-to-ffi.sh /usr/include/w32api/ddk/scsiscan.h
#h-to-ffi.sh /usr/include/w32api/ddk/scsiwmi.h
#h-to-ffi.sh /usr/include/w32api/ddk/smbus.h
#h-to-ffi.sh /usr/include/w32api/ddk/srb.h
#h-to-ffi.sh /usr/include/w32api/ddk/storport.h
#h-to-ffi.sh /usr/include/w32api/ddk/tdi.h
#h-to-ffi.sh /usr/include/w32api/ddk/tdiinfo.h
#h-to-ffi.sh /usr/include/w32api/ddk/tdikrnl.h
#h-to-ffi.sh /usr/include/w32api/ddk/tdistat.h
#h-to-ffi.sh /usr/include/w32api/ddk/tvout.h
#h-to-ffi.sh /usr/include/w32api/ddk/upssvc.h
#h-to-ffi.sh /usr/include/w32api/ddk/usb.h
#h-to-ffi.sh /usr/include/w32api/ddk/usb100.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbcamdi.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbdi.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbioctl.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbiodef.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbscan.h
#h-to-ffi.sh /usr/include/w32api/ddk/usbuser.h
#h-to-ffi.sh /usr/include/w32api/ddk/video.h
#h-to-ffi.sh /usr/include/w32api/ddk/videoagp.h
#h-to-ffi.sh /usr/include/w32api/ddk/win2k.h
#h-to-ffi.sh /usr/include/w32api/ddk/winddi.h
#h-to-ffi.sh /usr/include/w32api/ddk/winddk.h
#h-to-ffi.sh /usr/include/w32api/ddk/winnt4.h
#h-to-ffi.sh /usr/include/w32api/ddk/winxp.h
#h-to-ffi.sh /usr/include/w32api/ddk/ws2san.h
#h-to-ffi.sh /usr/include/w32api/ddk/xfilter.h
#h-to-ffi.sh /usr/include/w32api/devguid.h
#h-to-ffi.sh /usr/include/w32api/dhcpcsdk.h
#h-to-ffi.sh /usr/include/w32api/dlgs.h
#h-to-ffi.sh /usr/include/w32api/docobj.h
#h-to-ffi.sh /usr/include/w32api/dsadmin.h
#h-to-ffi.sh /usr/include/w32api/dsclient.h
#h-to-ffi.sh /usr/include/w32api/dsgetdc.h
#h-to-ffi.sh /usr/include/w32api/dshow.h
#h-to-ffi.sh /usr/include/w32api/dsquery.h
#h-to-ffi.sh /usr/include/w32api/dsrole.h
#h-to-ffi.sh /usr/include/w32api/dvdevcod.h
#h-to-ffi.sh /usr/include/w32api/dvdmedia.h
#h-to-ffi.sh /usr/include/w32api/dxerr8.h
#h-to-ffi.sh /usr/include/w32api/dxerr9.h
#h-to-ffi.sh /usr/include/w32api/edevdefs.h
#h-to-ffi.sh /usr/include/w32api/errorrep.h
#h-to-ffi.sh /usr/include/w32api/errors.h
#h-to-ffi.sh /usr/include/w32api/evcode.h
#h-to-ffi.sh /usr/include/w32api/exdisp.h
#h-to-ffi.sh /usr/include/w32api/exdispid.h
#h-to-ffi.sh /usr/include/w32api/fltdefs.h
#h-to-ffi.sh /usr/include/w32api/GL/gl.h
#h-to-ffi.sh /usr/include/w32api/GL/glext.h
#h-to-ffi.sh /usr/include/w32api/GL/glu.h
#h-to-ffi.sh /usr/include/w32api/httpext.h
#h-to-ffi.sh /usr/include/w32api/icm.h
#h-to-ffi.sh /usr/include/w32api/idispids.h
#h-to-ffi.sh /usr/include/w32api/il21dec.h
#h-to-ffi.sh /usr/include/w32api/imagehlp.h
#h-to-ffi.sh /usr/include/w32api/imm.h
#h-to-ffi.sh /usr/include/w32api/initguid.h
#h-to-ffi.sh /usr/include/w32api/intshcut.h
#h-to-ffi.sh /usr/include/w32api/ipexport.h
#h-to-ffi.sh /usr/include/w32api/iphlpapi.h
#h-to-ffi.sh /usr/include/w32api/ipifcons.h
#h-to-ffi.sh /usr/include/w32api/ipinfoid.h
#h-to-ffi.sh /usr/include/w32api/iprtrmib.h
#h-to-ffi.sh /usr/include/w32api/iptypes.h
#h-to-ffi.sh /usr/include/w32api/ipxconst.h
#h-to-ffi.sh /usr/include/w32api/ipxrtdef.h
#h-to-ffi.sh /usr/include/w32api/ipxtfflt.h
#h-to-ffi.sh /usr/include/w32api/isguids.h
#h-to-ffi.sh /usr/include/w32api/ks.h
#h-to-ffi.sh /usr/include/w32api/ksmedia.h
#h-to-ffi.sh /usr/include/w32api/largeint.h
#h-to-ffi.sh /usr/include/w32api/lm.h
#h-to-ffi.sh /usr/include/w32api/lmaccess.h
#h-to-ffi.sh /usr/include/w32api/lmalert.h
#h-to-ffi.sh /usr/include/w32api/lmapibuf.h
#h-to-ffi.sh /usr/include/w32api/lmat.h
#h-to-ffi.sh /usr/include/w32api/lmaudit.h
#h-to-ffi.sh /usr/include/w32api/lmbrowsr.h
#h-to-ffi.sh /usr/include/w32api/lmchdev.h
#h-to-ffi.sh /usr/include/w32api/lmconfig.h
#h-to-ffi.sh /usr/include/w32api/lmcons.h
#h-to-ffi.sh /usr/include/w32api/lmerr.h
#h-to-ffi.sh /usr/include/w32api/lmerrlog.h
#h-to-ffi.sh /usr/include/w32api/lmmsg.h
#h-to-ffi.sh /usr/include/w32api/lmremutl.h
#h-to-ffi.sh /usr/include/w32api/lmrepl.h
#h-to-ffi.sh /usr/include/w32api/lmserver.h
#h-to-ffi.sh /usr/include/w32api/lmshare.h
#h-to-ffi.sh /usr/include/w32api/lmsname.h
#h-to-ffi.sh /usr/include/w32api/lmstats.h
#h-to-ffi.sh /usr/include/w32api/lmsvc.h
#h-to-ffi.sh /usr/include/w32api/lmuse.h
#h-to-ffi.sh /usr/include/w32api/lmuseflg.h
#h-to-ffi.sh /usr/include/w32api/lmwksta.h
#h-to-ffi.sh /usr/include/w32api/lzexpand.h
#h-to-ffi.sh /usr/include/w32api/mapi.h
#h-to-ffi.sh /usr/include/w32api/mciavi.h
#h-to-ffi.sh /usr/include/w32api/mcx.h
#h-to-ffi.sh /usr/include/w32api/mgm.h
#h-to-ffi.sh /usr/include/w32api/mgmtapi.h
#h-to-ffi.sh /usr/include/w32api/mlang.h
#h-to-ffi.sh /usr/include/w32api/mmreg.h
#h-to-ffi.sh /usr/include/w32api/mmsystem.h
#h-to-ffi.sh /usr/include/w32api/mpegtype.h
#h-to-ffi.sh /usr/include/w32api/mprapi.h
#h-to-ffi.sh /usr/include/w32api/mq.h
#h-to-ffi.sh /usr/include/w32api/msacm.h
#h-to-ffi.sh /usr/include/w32api/mshtml.h
#h-to-ffi.sh /usr/include/w32api/mswsock.h
#h-to-ffi.sh /usr/include/w32api/nb30.h
#h-to-ffi.sh /usr/include/w32api/nddeapi.h
#h-to-ffi.sh /usr/include/w32api/nspapi.h
#h-to-ffi.sh /usr/include/w32api/ntdef.h
#h-to-ffi.sh /usr/include/w32api/ntdll.h
#h-to-ffi.sh /usr/include/w32api/ntdsapi.h
#h-to-ffi.sh /usr/include/w32api/ntdsbcli.h
#h-to-ffi.sh /usr/include/w32api/ntldap.h
#h-to-ffi.sh /usr/include/w32api/ntsecapi.h
#h-to-ffi.sh /usr/include/w32api/ntsecpkg.h
#h-to-ffi.sh /usr/include/w32api/oaidl.h
#h-to-ffi.sh /usr/include/w32api/objbase.h
#h-to-ffi.sh /usr/include/w32api/objfwd.h
#h-to-ffi.sh /usr/include/w32api/objidl.h
#h-to-ffi.sh /usr/include/w32api/objsafe.h
#h-to-ffi.sh /usr/include/w32api/objsel.h
#h-to-ffi.sh /usr/include/w32api/ocidl.h
#h-to-ffi.sh /usr/include/w32api/odbcinst.h
#h-to-ffi.sh /usr/include/w32api/ole.h
#h-to-ffi.sh /usr/include/w32api/ole2.h
#h-to-ffi.sh /usr/include/w32api/ole2ver.h
#h-to-ffi.sh /usr/include/w32api/oleacc.h
#h-to-ffi.sh /usr/include/w32api/oleauto.h
#h-to-ffi.sh /usr/include/w32api/olectl.h
#h-to-ffi.sh /usr/include/w32api/olectlid.h
#h-to-ffi.sh /usr/include/w32api/oledlg.h
#h-to-ffi.sh /usr/include/w32api/oleidl.h
#h-to-ffi.sh /usr/include/w32api/pbt.h
#h-to-ffi.sh /usr/include/w32api/poppack.h
#h-to-ffi.sh /usr/include/w32api/powrprof.h
#h-to-ffi.sh /usr/include/w32api/prsht.h
#h-to-ffi.sh /usr/include/w32api/psapi.h
#h-to-ffi.sh /usr/include/w32api/pshpack1.h
#h-to-ffi.sh /usr/include/w32api/pshpack2.h
#h-to-ffi.sh /usr/include/w32api/pshpack4.h
#h-to-ffi.sh /usr/include/w32api/pshpack8.h
#h-to-ffi.sh /usr/include/w32api/qedit.h
#h-to-ffi.sh /usr/include/w32api/rapi.h
#h-to-ffi.sh /usr/include/w32api/ras.h
#h-to-ffi.sh /usr/include/w32api/rasdlg.h
#h-to-ffi.sh /usr/include/w32api/raserror.h
#h-to-ffi.sh /usr/include/w32api/rassapi.h
#h-to-ffi.sh /usr/include/w32api/reason.h
#h-to-ffi.sh /usr/include/w32api/regstr.h
#h-to-ffi.sh /usr/include/w32api/richedit.h
#h-to-ffi.sh /usr/include/w32api/richole.h
#h-to-ffi.sh /usr/include/w32api/routprot.h
#h-to-ffi.sh /usr/include/w32api/rpc.h
#h-to-ffi.sh /usr/include/w32api/rpcdce.h
#h-to-ffi.sh /usr/include/w32api/rpcdce2.h
#h-to-ffi.sh /usr/include/w32api/rpcdcep.h
#h-to-ffi.sh /usr/include/w32api/rpcndr.h
#h-to-ffi.sh /usr/include/w32api/rpcnsi.h
#h-to-ffi.sh /usr/include/w32api/rpcnsip.h
#h-to-ffi.sh /usr/include/w32api/rpcnterr.h
#h-to-ffi.sh /usr/include/w32api/rpcproxy.h
#h-to-ffi.sh /usr/include/w32api/rtutils.h
#h-to-ffi.sh /usr/include/w32api/schannel.h
#h-to-ffi.sh /usr/include/w32api/schnlsp.h
#h-to-ffi.sh /usr/include/w32api/scrnsave.h
#h-to-ffi.sh /usr/include/w32api/sddl.h
#h-to-ffi.sh /usr/include/w32api/secext.h
#h-to-ffi.sh /usr/include/w32api/security.h
#h-to-ffi.sh /usr/include/w32api/servprov.h
#h-to-ffi.sh /usr/include/w32api/setupapi.h
#h-to-ffi.sh /usr/include/w32api/shellapi.h
#h-to-ffi.sh /usr/include/w32api/shldisp.h
#h-to-ffi.sh /usr/include/w32api/shlguid.h
#h-to-ffi.sh /usr/include/w32api/shlobj.h
#h-to-ffi.sh /usr/include/w32api/shlwapi.h
#h-to-ffi.sh /usr/include/w32api/snmp.h
#h-to-ffi.sh /usr/include/w32api/sql.h
#h-to-ffi.sh /usr/include/w32api/sqlext.h
#h-to-ffi.sh /usr/include/w32api/sqltypes.h
#h-to-ffi.sh /usr/include/w32api/sqlucode.h
#h-to-ffi.sh /usr/include/w32api/sspi.h
#h-to-ffi.sh /usr/include/w32api/stm.h
#h-to-ffi.sh /usr/include/w32api/strmif.h
#h-to-ffi.sh /usr/include/w32api/subauth.h
#h-to-ffi.sh /usr/include/w32api/svcguid.h
#h-to-ffi.sh /usr/include/w32api/tlhelp32.h
#h-to-ffi.sh /usr/include/w32api/tmschema.h
#h-to-ffi.sh /usr/include/w32api/unknwn.h
#h-to-ffi.sh /usr/include/w32api/userenv.h
#h-to-ffi.sh /usr/include/w32api/usp10.h
#h-to-ffi.sh /usr/include/w32api/uxtheme.h
#h-to-ffi.sh /usr/include/w32api/vfw.h
#h-to-ffi.sh /usr/include/w32api/vidcap.h
#h-to-ffi.sh /usr/include/w32api/vmr9.h
#h-to-ffi.sh /usr/include/w32api/vptype.h
#h-to-ffi.sh /usr/include/w32api/w32api.h
#h-to-ffi.sh /usr/include/w32api/winable.h
#h-to-ffi.sh /usr/include/w32api/winbase.h
#h-to-ffi.sh /usr/include/w32api/winber.h
#h-to-ffi.sh /usr/include/w32api/wincon.h
#h-to-ffi.sh /usr/include/w32api/wincrypt.h
#h-to-ffi.sh /usr/include/w32api/windef.h
#h-to-ffi.sh /usr/include/w32api/windns.h
#h-to-ffi.sh /usr/include/w32api/windows.h
#h-to-ffi.sh /usr/include/w32api/windowsx.h
#h-to-ffi.sh /usr/include/w32api/winerror.h
#h-to-ffi.sh /usr/include/w32api/wingdi.h
#h-to-ffi.sh /usr/include/w32api/wininet.h
#h-to-ffi.sh /usr/include/w32api/winioctl.h
#h-to-ffi.sh /usr/include/w32api/winldap.h
#h-to-ffi.sh /usr/include/w32api/winnetwk.h
#h-to-ffi.sh /usr/include/w32api/winnls.h
#h-to-ffi.sh /usr/include/w32api/winnt.h
#h-to-ffi.sh /usr/include/w32api/winperf.h
#h-to-ffi.sh /usr/include/w32api/winreg.h
#h-to-ffi.sh /usr/include/w32api/winresrc.h
#h-to-ffi.sh /usr/include/w32api/winsnmp.h
#h-to-ffi.sh /usr/include/w32api/winsock.h
#h-to-ffi.sh /usr/include/w32api/winsock2.h
#h-to-ffi.sh /usr/include/w32api/winspool.h
#h-to-ffi.sh /usr/include/w32api/winsvc.h
#h-to-ffi.sh /usr/include/w32api/winuser.h
#h-to-ffi.sh /usr/include/w32api/winver.h
#h-to-ffi.sh /usr/include/w32api/ws2spi.h
#h-to-ffi.sh /usr/include/w32api/wsahelp.h
#h-to-ffi.sh /usr/include/w32api/wsipx.h
#h-to-ffi.sh /usr/include/w32api/wsnetbs.h
#h-to-ffi.sh /usr/include/w32api/wtsapi32.h
#h-to-ffi.sh /usr/include/w32api/wtypes.h
#h-to-ffi.sh /usr/include/w32api/xprtdefs.h
#h-to-ffi.sh /usr/include/w32api/zmouse.h
