=== Customer Support Services

(((customer support services))) 
Phone support is available from 9am to
6pm US Eastern time on Monday through Friday at the phone numbers
listed below.

Gensym Global Support Phone Numbers for Standard and Gold Customers:

[horizontal]
United States:: Toll-Free - 1-855-453-8174; Toll - 1-512-861-2859
United Kingdom:: 0808-189-1290
France:: 0800-915549

If your country is not listed above, you can dial the US Toll Number
1-512-861-2859 to reach our support organization.

You can submit a ticket at anytime by going to our support portal at
https://support.ignitetech.com or sending an email to
support@ignitetech.com. While you are able to submit tickets
electronically by either method, our support portal is designed to
collect key information to help resolve your issue faster, so the
support portal is the preferred method for submitting tickets.

If you have any questions about Gensym Global Support, please check
our support overview or review our FAQs on the support portal. You are
also welcome to submit a ticket or call us and we would be happy to
answer your questions.
