#if !defined(AFX_G2GATEWAY4_H__DE1C9A5D_5364_4041_9894_6C90106B3D06__INCLUDED_)
#define AFX_G2GATEWAY4_H__DE1C9A5D_5364_4041_9894_6C90106B3D06__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CG2Gateway4 wrapper class

class CG2Gateway4 : public CWnd
{
protected:
	DECLARE_DYNCREATE(CG2Gateway4)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xac4c85d0, 0xb16c, 0x11d1, { 0xa7, 0x18, 0x0, 0x60, 0x8, 0xc5, 0xf9, 0x33 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long Connect(BOOL WaitFlag);
	void Disconnect();
	// method 'Call' not emitted because of invalid return type or parameter type
	// method 'CallDeferred' not emitted because of invalid return type or parameter type
	// method 'Start' not emitted because of invalid return type or parameter type
	LPDISPATCH GetNamedObject(LPCTSTR ObjectName, LPCTSTR ObjectClass);
	LPDISPATCH CreateObjectInstance(LPCTSTR ClassName);
	BOOL GetIsG2Connected();
	BOOL GetIsG2Running();
	CString GetG2Location();
	void SetG2Location(LPCTSTR lpszNewValue);
	CString GetInterfaceClass();
	void SetInterfaceClass(LPCTSTR lpszNewValue);
	CString GetRemoteInitializationString();
	void SetRemoteInitializationString(LPCTSTR lpszNewValue);
	long GetCallTimeout();
	void SetCallTimeout(long nNewValue);
	void PostMessage(VARIANT* Message);
	void OnStartPage(LPUNKNOWN piUnk);
	void OnEndPage();
	// method 'MakeG2ComVariable' not emitted because of invalid return type or parameter type
	long GetG2RunState();
	BOOL GetG2Symbols();
	void SetG2Symbols(BOOL bNewValue);
	BOOL GetDisconnectOnReset();
	void SetDisconnectOnReset(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_G2GATEWAY4_H__DE1C9A5D_5364_4041_9894_6C90106B3D06__INCLUDED_)
