/* osrrr.h -- Header File for osrrr.c
 * Copyright (c) 1986 - 2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kelement_type;
extern Object Qequal;
extern Object Kfill_pointer;
extern Object Kinitial_element;
extern Object Qstring_char;
extern Object Ktest;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object allocate_byte_vector_16(Object);
extern Object c_g2_stream_open(Object,Object);
extern Object c_g2_stream_write_string(Object,Object,Object);
extern Object c_spawn_command_line_process(Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object copy_byte_vector_16_portion_carefully(Object,Object,Object,Object,Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_portion_of_string_into_gensym_string(Object,Object,Object,Object,Object);
extern Object copy_text_string(Object);
extern Object def_bombout_clean_up_function(Object);
extern Object do_not_catch_aborts_p(void);
extern Object exit_lisp_process(int,...);
extern Object exit_on_abort_p(void);
extern Object export_text_string(int,...);
extern Object extend_current_gensym_string(int,...);
extern Object g2_error_handler_given_updated_message_buffer(void);
extern Object g2_unrecoverable_error_exit(void);
extern Object g2int_error_handler(void);
extern Object g2int_handle_broken_pipe_signal(void);
extern Object g2int_signal_handler(void);
extern Object g2int_signal_handler_for_launch(void);
extern Object get_command_line_flag_argument(int,...);
extern Object get_command_line_keyword_argument(int,...);
extern Object get_command_line_keyword_argument_as_integer(int,...);
extern Object get_decoded_real_time(void);
extern Object get_g2_signal_handler(Object);
extern Object get_gensym_environment_variable(Object);
extern Object get_raw_network_info(void);
extern Object get_signal_description_string(Object);
extern Object initialize_information_from_caught_signal(void);
extern Object initialize_information_from_trapped_error(void);
extern Object initialize_post_mortem_internal_buffer(void);
extern Object initialize_post_mortem_report_buffer(void);
extern Object initialize_post_mortem_ring_buffer(void);
extern Object initialize_post_mortem_ring_buffer_length(void);
extern Object initialize_post_mortem_ring_buffer_logfile_namestring(void);
extern Object internal_error_given_format_info(Object,Object,Object);
extern Object maybe_email_error_report(Object);
extern Object maybe_email_string_to_address(Object,Object,Object);
extern Object maybe_wait_for_return_key(int,...);
extern Object maybe_write_abort_file(Object);
extern Object maybe_write_string_to_directory(Object,Object,Object);
extern Object memq_function(Object,Object);
extern Object minimal_internal_error_given_format_info(Object,Object,Object);
extern Object notify_console_of_internal_error(Object,Object);
extern Object notify_engineer(int,...);
extern Object notify_user(int,...);
extern Object pause_for_internal_error(Object);
extern Object print_internal_error_data_on_console(Object);
extern Object read_number_for_gensym_environment_variable(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_raw_network_info(Object,Object);
extern Object reclaim_text_string(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object register_all_signal_handlers(void);
extern Object register_all_signal_handlers_for_launch(void);
extern Object register_all_signal_handlers_unconditionally(void);
extern Object reset_structure_being_reclaimed_after_bombout(void);
extern Object shutdown_or_exit(int,...);
extern Object signal_code_number_from_name_symbol(Object);
extern Object signal_floating_point_exception_stack_error(void);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object twrite_ascii_from_gensym_string(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_general_string(Object);
extern Object twrite_system_version(int,...);
extern Object twrite_wide_character(Object);
extern Object update_backtrace_text_buffer_for_internal_error(void);
extern Object warn_user_of_previously_aborted_g2(void);
extern Object write_internal_error(Object,Object,Object);
extern Object write_local_identification_info_text_string_1(Object);
extern Object write_string_to_temporary_file(Object,Object);

#else

extern Object allocate_byte_vector_16();
extern Object c_g2_stream_open();
extern Object c_g2_stream_write_string();
extern Object c_spawn_command_line_process();
extern Object chestnut_floorf_function();
extern Object copy_byte_vector_16_portion_carefully();
extern Object copy_out_current_wide_string();
extern Object copy_portion_of_string_into_gensym_string();
extern Object copy_text_string();
extern Object def_bombout_clean_up_function();
extern Object do_not_catch_aborts_p();
extern Object exit_lisp_process();
extern Object exit_on_abort_p();
extern Object export_text_string();
extern Object extend_current_gensym_string();
extern Object g2_error_handler_given_updated_message_buffer();
extern Object g2_unrecoverable_error_exit();
extern Object g2int_error_handler();
extern Object g2int_handle_broken_pipe_signal();
extern Object g2int_signal_handler();
extern Object g2int_signal_handler_for_launch();
extern Object get_command_line_flag_argument();
extern Object get_command_line_keyword_argument();
extern Object get_command_line_keyword_argument_as_integer();
extern Object get_decoded_real_time();
extern Object get_g2_signal_handler();
extern Object get_gensym_environment_variable();
extern Object get_raw_network_info();
extern Object get_signal_description_string();
extern Object initialize_information_from_caught_signal();
extern Object initialize_information_from_trapped_error();
extern Object initialize_post_mortem_internal_buffer();
extern Object initialize_post_mortem_report_buffer();
extern Object initialize_post_mortem_ring_buffer();
extern Object initialize_post_mortem_ring_buffer_length();
extern Object initialize_post_mortem_ring_buffer_logfile_namestring();
extern Object internal_error_given_format_info();
extern Object maybe_email_error_report();
extern Object maybe_email_string_to_address();
extern Object maybe_wait_for_return_key();
extern Object maybe_write_abort_file();
extern Object maybe_write_string_to_directory();
extern Object memq_function();
extern Object minimal_internal_error_given_format_info();
extern Object notify_console_of_internal_error();
extern Object notify_engineer();
extern Object notify_user();
extern Object pause_for_internal_error();
extern Object print_internal_error_data_on_console();
extern Object read_number_for_gensym_environment_variable();
extern Object reclaim_gensym_string();
extern Object reclaim_raw_network_info();
extern Object reclaim_text_string();
extern Object record_system_variable();
extern Object register_all_signal_handlers();
extern Object register_all_signal_handlers_for_launch();
extern Object register_all_signal_handlers_unconditionally();
extern Object reset_structure_being_reclaimed_after_bombout();
extern Object shutdown_or_exit();
extern Object signal_code_number_from_name_symbol();
extern Object signal_floating_point_exception_stack_error();
extern Object tformat();
extern Object tformat_text_string();
extern Object twrite_ascii_from_gensym_string();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_general_string();
extern Object twrite_system_version();
extern Object twrite_wide_character();
extern Object update_backtrace_text_buffer_for_internal_error();
extern Object warn_user_of_previously_aborted_g2();
extern Object write_internal_error();
extern Object write_local_identification_info_text_string_1();
extern Object write_string_to_temporary_file();

#endif

/* variables/constants */
extern Object Abort_file_written_p;
extern Object All_signal_handlers_registered_p;
extern Object Arithmetic_errors_are_stack_errors_p;
extern Object Backtrace_stack_for_internal_error;
extern Object Backtrace_text_buffer_for_internal_error;
extern Object Bombout_clean_up_functions;
extern Object Buffer_for_internal_error_on_console;
extern Object Buffer_for_internal_error_on_logbook;
extern Object Buffer_for_write_internal_error;
extern Object Build_identification_string;
extern Object Current_gensym_string;
extern Object Current_post_mortem_ring_buffer;
extern Object Current_post_mortem_ring_buffer_length;
extern Object Current_system_name;
extern Object Current_twriting_output_type;
extern Object Current_wide_string;
extern Object Current_wide_string_list;
extern Object Depth_of_post_mortem_checkpoint_reporting;
extern Object Do_error_trapping_qm;
extern Object Email_abort_message_sent_p;
extern Object Error_within_error_p;
extern Object Fill_pointer_for_current_gensym_string;
extern Object Fill_pointer_for_current_wide_string;
extern Object G2_machine_type;
extern Object G2_operating_system;
#define G2_stream_foreign_file_op_failure FIX((SI_Long)-1L)
#define G2_stream_open_mode_for_output FIX((SI_Long)1L)
extern Object Gensym_error_argument_list;
extern Object Gensym_error_format_string;
extern Object Gensym_error_message_buffer;
extern Object Gensym_error_sure_of_format_info_p;
extern Object Idling_wait_state_string;
extern Object Index_of_top_of_backtrace_stack;
extern Object Information_from_caught_signal;
extern Object Information_from_trapped_error;
extern Object Input_gensym_string_for_buffer_for_internal_error_on_console;
extern Object Input_gensym_string_for_gensym_error_message_buffer;
extern Object Input_string_for_backtrace_text_buffer_for_internal_error;
extern Object Input_string_for_buffer_for_internal_error_on_logbook;
extern Object Input_string_for_buffer_for_write_internal_error;
extern Object Inside_avoid_arithmetic_errors_p;
extern Object Internal_error_trapped_format_string;
extern Object Internal_signal_caught_format_string;
#define Length_of_backtrace_text_buffer_for_internal_error FIX((SI_Long)4000L)
#define Length_of_buffer_for_internal_error_on_console FIX((SI_Long)4000L)
#define Length_of_buffer_for_internal_error_on_logbook FIX((SI_Long)4000L)
#define Length_of_buffer_for_write_internal_error FIX((SI_Long)4000L)
#define Length_of_gensym_error_message_buffer FIX((SI_Long)1000L)
extern Object Log_post_mortem_ring_buffer_to_file_p;
extern Object Post_mortem_internal_buffer;
extern Object Post_mortem_report_buffer;
extern Object Post_mortem_ring_buffer_logfile_line_count;
extern Object Post_mortem_ring_buffer_logfile_namestring;
extern Object Post_mortem_ring_buffer_logfile_stream;
extern Object Shutdown_catch_tag;
extern Object Sigfpe;
extern Object Signal_code_registry;
#define Size_of_backtrace_stack_for_internal_error FIX((SI_Long)1000L)
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
extern Object System_has_paused;
extern Object System_is_running;
extern Object Task_to_warn_user_of_previously_aborted_g2;
extern Object Temporary_file_count;
extern Object Top_level_error_catcher_tag;
extern Object Top_level_error_seen;
extern Object Total_length_of_current_gensym_string;
extern Object Total_length_of_current_wide_string;
