/* userinit.c -- Lisp-to-C Translator Top-Level Forms
 * Copyright (c) 1986 - 2017 Gensym Corporation.  All Rights Reserved.
 */

#include "user.h"


INCLUDE_LISP_PACKAGE_SELECTIVELY

void userinit()
{
    extern void load_INIT();
    extern void bootstrap_INIT();
    extern void systems_INIT();
    extern void delta_INIT();
    extern void g2_config_INIT();
    extern void tw_patches_INIT();
    extern void loop_INIT();
    extern void glbasics_INIT();
    extern void os_foreign_INIT();
    extern void basics_INIT();
    extern void os_time_INIT();
    extern void os_settings_INIT();
    extern void os_memory_INIT();
    extern void primitives_INIT();
    extern void characters_INIT();
    extern void jismap_INIT();
    extern void ksmap2_INIT();
    extern void gbmap_INIT();
    extern void gbmapr_INIT();
    extern void characters2_INIT();
    extern void keyboards_INIT();
    extern void keydefs_INIT();
    extern void utilities0_INIT();
    extern void utilities1_INIT();
    extern void utilities2_INIT();
    extern void letters_INIT();
    extern void unicode_INIT();
    extern void iso2022_INIT();
    extern void transcode_INIT();
    extern void iso8859_INIT();
    extern void utilities3_INIT();
    extern void times_INIT();
    extern void f_keys_INIT();
    extern void os_error_INIT();
    extern void platforms_INIT();
    extern void launch_INIT();
    extern void pathnames_INIT();
    extern void file_parse_INIT();
    extern void streams_INIT();
    extern void schedule_INIT();
    extern void clocks_INIT();
    extern void networks_INIT();
    extern void int0_INIT();
    extern void int1_INIT();
    extern void neterror_INIT();
    extern void netevent_INIT();
    extern void int2_INIT();
    extern void int3a_INIT();
    extern void int3b_INIT();
    extern void int4_INIT();
    extern void windows1_INIT();
    extern void windows2_INIT();
    extern void windows3_INIT();
    extern void windows3a_INIT();
    extern void windows4_INIT();
    extern void images_INIT();
    extern void fonts_INIT();
    extern void hb72_INIT();
    extern void hm14_INIT();
    extern void hm18_INIT();
    extern void hm24_INIT();
    extern void slavic14_INIT();
    extern void slavic18_INIT();
    extern void slavic24_INIT();
    extern void hebrew14_INIT();
    extern void hebrew18_INIT();
    extern void hebrew24_INIT();
    extern void thai14_INIT();
    extern void thai18_INIT();
    extern void thai24_INIT();
    extern void sequences1_INIT();
    extern void telestubs_INIT();
    extern void dialogs_INIT();
    extern void native_tw_INIT();
    extern void rings_INIT();
    extern void font_files_INIT();
    extern void telewindows_INIT();
    extern void translate_INIT();

    INIT_names(4839);
    load_INIT();
    bootstrap_INIT();
    systems_INIT();
    delta_INIT();
    g2_config_INIT();
    tw_patches_INIT();
    loop_INIT();
    glbasics_INIT();
    os_foreign_INIT();
    basics_INIT();
    os_time_INIT();
    os_settings_INIT();
    os_memory_INIT();
    primitives_INIT();
    characters_INIT();
    jismap_INIT();
    ksmap2_INIT();
    gbmap_INIT();
    gbmapr_INIT();
    characters2_INIT();
    keyboards_INIT();
    keydefs_INIT();
    utilities0_INIT();
    utilities1_INIT();
    utilities2_INIT();
    letters_INIT();
    unicode_INIT();
    iso2022_INIT();
    transcode_INIT();
    iso8859_INIT();
    utilities3_INIT();
    times_INIT();
    f_keys_INIT();
    os_error_INIT();
    platforms_INIT();
    launch_INIT();
    pathnames_INIT();
    file_parse_INIT();
    streams_INIT();
    schedule_INIT();
    clocks_INIT();
    networks_INIT();
    int0_INIT();
    int1_INIT();
    neterror_INIT();
    netevent_INIT();
    int2_INIT();
    int3a_INIT();
    int3b_INIT();
    int4_INIT();
    windows1_INIT();
    windows2_INIT();
    windows3_INIT();
    windows3a_INIT();
    windows4_INIT();
    images_INIT();
    fonts_INIT();
    hb72_INIT();
    hm14_INIT();
    hm18_INIT();
    hm24_INIT();
    slavic14_INIT();
    slavic18_INIT();
    slavic24_INIT();
    hebrew14_INIT();
    hebrew18_INIT();
    hebrew24_INIT();
    thai14_INIT();
    thai18_INIT();
    thai24_INIT();
    sequences1_INIT();
    telestubs_INIT();
    dialogs_INIT();
    native_tw_INIT();
    rings_INIT();
    font_files_INIT();
    telewindows_INIT();
    translate_INIT();
}

