/* cells.h -- Header File for cells.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qblock;
extern Object Qeval;
extern Object Qfloat;
extern Object Qinteger;
extern Object Qnumber;
extern Object Qread;
extern Object Qunsigned_byte;
extern Object Qwrite;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_cell_of_g2_cell_array(Object,Object);
extern Object activate_cell_of_g2_cell_array_1(Object);
extern Object activate_g2_cell_array(Object);
extern Object activate_g2_designation_cell(Object);
extern Object activate_g2_expression_cell(Object);
extern Object activate_g2_query_cell(Object);
extern Object add_class_to_environment(int,...);
extern Object add_computation_style_to_set_of_all_permanent_computation_styles(Object);
extern Object adjust_managed_array(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_vector(Object);
extern Object analyze_byte_code_body_for_free_reference_consistency(Object);
extern Object analyze_cell_for_consistency_1(Object);
extern Object analyze_compiled_form(Object,Object,Object);
extern Object analyze_g2_cell_array_for_consistency(Object);
extern Object analyze_g2_designation_cell_for_consistency(Object);
extern Object analyze_g2_expression_cell_for_consistency(Object);
extern Object analyze_g2_query_cell_for_consistency(Object);
extern Object attempt_expression_cell_execution(Object,Object,Object);
extern Object attempt_expression_cell_execution_during_slot_putter(Object);
extern Object begin_g2_cell_array_evaluations(Object);
extern Object buffer_size_for_partial_buffer(Object,Object);
extern Object bytes_per_simple_vector(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_expression_cell_computation(Object);
extern Object cancel_scheduled_expression_cell_execution(Object,Object);
extern Object change_slot_value(int,...);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clean_up_wake_ups_state_if_any(void);
extern Object cleanup_for_g2_expression_cell(Object);
extern Object cleanup_g2_cell_array(Object);
extern Object clear_computation_context_variables(void);
extern Object clear_optimized_constants(void);
extern Object clone_frame(int,...);
extern Object compare_computation_styles_for_installation_differences(Object,Object);
extern Object compile_expression(Object,Object,Object);
extern Object compile_expression_cell_for_stack(Object,Object,Object);
extern Object compile_generic_formula(Object,Object,Object,Object);
extern Object compiled_cell_expression_p(Object);
extern Object computation_style_equal(Object,Object);
extern Object compute_hash_of_computation_style(Object);
extern Object compute_new_designation_cell_value(Object,Object,Object);
extern Object compute_new_query_cell_value(Object,Object,Object);
extern Object constant_queue_push_right(Object,Object);
extern Object convert_absent_slot_to_tracing_and_breakpoints(Object,Object,Object,Object);
extern Object convert_cell_type_to_type_specification(Object);
extern Object copy_computation_style(Object,Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_for_g2_cell_array(Object);
extern Object copy_frame_for_g2_cell_array_cell(Object);
extern Object copy_frame_for_g2_expression_cell(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_out_current_wide_string(void);
extern Object deactivate_cell_of_g2_cell_array(Object,Object);
extern Object deactivate_cell_of_g2_cell_array_1(Object);
extern Object deactivate_g2_cell_array(Object);
extern Object deactivate_g2_designation_cell(Object);
extern Object deactivate_g2_expression_cell(Object);
extern Object deactivate_g2_query_cell(Object);
extern Object deinstall_chaining_links(Object);
extern Object delete_all_frame_notes_for_component_particular(Object,Object);
extern Object delete_cell_from_g2_cell_array(Object,Object);
extern Object delete_eval_element_1(Object,Object);
extern Object delete_frame(Object);
extern Object denote_component_of_block(int,...);
extern Object deregister_use_of_computation_style(Object);
extern Object direct_structure_method(Object,Object);
extern Object enter_cell_evaluation_message(void);
extern Object enter_skipped_cell_evaluation_message(void);
extern Object eval_cons_1(Object,Object);
extern Object evaluate_designation(Object,Object);
extern Object event_update_status_of_cell_array_showing(Object,Object);
extern Object exit_cell_expression_evaluation_message(Object);
extern Object exit_skipped_cell_evaluation_message(void);
extern Object expression_cell_computation_in_progress_p(Object,Object);
extern Object find_matching_permanent_computation_style_if_any(Object);
extern Object find_new_location_for_cell(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object future_task_schedule_2(Object);
extern Object g2_cell_array_expression_cells_have_byte_code_bodies_p(Object);
extern Object g2_cell_array_managed_array_function(Object);
extern Object g2_expression_cell_byte_code_body_function(Object);
extern Object generate_cell_chaining_links(Object,Object,Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_entry_to_set_of_all_permanent_computation_styles(Object);
extern Object get_simple_part_feature(Object,Object);
extern Object get_subpart_collection(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object in_order_p(Object);
extern Object increment_profiling_calls(Object);
extern Object initialize_g2_cell_array(Object);
extern Object initialize_g2_cell_array_after_reading(Object);
extern Object initialize_set_of_all_permanent_computation_style(void);
extern Object install_chaining_links(Object);
extern Object issue_tracing_and_breakpoint_exit_message(Object,Object);
extern Object issue_tracing_and_breakpoints_entry_message(Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_class_type_specification(Object);
extern Object make_computation_style_function(void);
extern Object make_empty_expression_cell(Object);
extern Object make_frame(Object);
extern Object make_permanent_query_cell_stream_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_query_cell_stream_1_1(Object,Object,Object);
extern Object make_query_cell_stream_to_cached_value(Object,Object);
extern Object make_thread_array(Object);
extern Object memq_function(Object,Object);
extern Object modify_tracing_and_breakpoints_context_on_entry(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_dependent_frame_1(void);
extern Object note_g2_cell_array_runs_while_inactive_change(Object,Object);
extern Object open_wake_up_collection_function(Object);
extern Object outstanding_query_cell_stream_count(void);
extern Object posit_profiling_structure(Object);
extern Object push_optimized_constant(Object);
extern Object put_computation_style_break_message_level_where_slot_is_absent(Object,Object);
extern Object put_computation_style_invokable_via_backward_chaining_where_slot_is_absent(Object,Object);
extern Object put_computation_style_invokable_via_forward_chaining_where_slot_is_absent(Object,Object);
extern Object put_computation_style_may_cause_backward_chaining_where_slot_is_absent(Object,Object);
extern Object put_computation_style_may_cause_forward_chaining_where_slot_is_absent(Object,Object);
extern Object put_computation_style_reference_count_where_slot_is_absent(Object,Object);
extern Object put_computation_style_trace_message_level_where_slot_is_absent(Object,Object);
extern Object put_computation_style_warning_message_level_where_slot_is_absent(Object,Object);
extern Object put_g2_expression_cell_chaining_links(Object,Object,Object);
extern Object put_g2_expression_cell_expression_where_slot_is_absent(Object,Object);
extern Object query_cell_stream_iterate_to_undeleted_frame(Object);
extern Object query_cell_stream_structure_memory_usage(void);
extern Object rebuild_backpointers_of_cells_of_g2_cell_array(Object,Object);
extern Object rebuild_backpointers_of_g2_cell_array(Object,Object);
extern Object rebuild_backpointers_of_g2_expression_cell_chaining_links(Object,Object);
extern Object reclaim_environment_vector(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_evaluation_place_reference(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_g2_cell_array_parent_frame_value(Object,Object);
extern Object reclaim_g2_designation_cell_frame_serial_number_qm_value(Object,Object);
extern Object reclaim_g2_expression_cell_cached_value_value(Object,Object);
extern Object reclaim_g2_expression_cell_computation_style_value(Object,Object);
extern Object reclaim_g2_expression_cell_g2_cell_array_value(Object,Object);
extern Object reclaim_g2_query_cell_cached_value_value(Object,Object);
extern Object reclaim_g2_query_cell_frame_serial_number_qm_value(Object,Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_managed_number_or_value_function(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_query_cell_cached_value(Object,Object);
extern Object reclaim_query_cell_stream(Object);
extern Object reclaim_query_cell_stream_1_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_set_of_all_permanent_computation_style(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_temporary_constant_1(Object);
extern Object reclaim_text_string(Object);
extern Object recompile_cell_array(Object);
extern Object recompile_item(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object redirect_chaining_link_recipient(Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object register_designation_cell(Object,Object,Object);
extern Object register_designation_cell_designation(Object,Object,Object,Object);
extern Object register_expression_cell_during_compilation(int,...);
extern Object register_expression_cell_during_slot_putter(Object,Object,Object);
extern Object register_query_cell(Object);
extern Object register_query_cell_designation(Object,Object,Object,Object);
extern Object register_use_of_computation_style(Object);
extern Object remove_compilation_from_obsolete_expression_cell(Object);
extern Object remove_compilations_from_obsolete_cell_array(Object);
extern Object savable_computation_style_p(Object);
extern Object schedule_expression_cell_execution(Object,Object,Object);
extern Object schedule_expression_cell_execution_for_true_value_update(Object,Object,Object,Object,Object,Object);
extern Object schedule_expression_cell_execution_given_cell(Object,Object,Object);
extern Object schedule_g2_cell_array_update(Object);
extern Object schedule_or_deschedule_g2_expression_cell_cyclic_task(Object,Object,Object);
extern Object serve_eval_list_of_designation_values(Object);
extern Object set_wake_ups_function(Object);
extern Object showing_p(Object,Object);
extern Object shrink_or_delete_managed_array_null_elements(Object);
extern Object shutdown_g2_cell_array_evaluations(Object);
extern Object slot_value_list_2(Object,Object);
extern Object stack_eval(Object,Object,Object,Object,Object,Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object type_specification_subtype_p(Object,Object);
extern Object update_designation_cell_cached_value(Object,Object,Object,Object,Object);
extern Object update_expression_cell_cached_value(Object,Object,Object,Object,Object);
extern Object update_g2_cell_value(Object,Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_query_cell_cached_value(Object,Object,Object,Object,Object);
extern Object var_count(Object);
extern Object withdraw_backward_chaining(Object);

#else

extern Object activate_cell_of_g2_cell_array();
extern Object activate_cell_of_g2_cell_array_1();
extern Object activate_g2_cell_array();
extern Object activate_g2_designation_cell();
extern Object activate_g2_expression_cell();
extern Object activate_g2_query_cell();
extern Object add_class_to_environment();
extern Object add_computation_style_to_set_of_all_permanent_computation_styles();
extern Object adjust_managed_array();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_vector();
extern Object analyze_byte_code_body_for_free_reference_consistency();
extern Object analyze_cell_for_consistency_1();
extern Object analyze_compiled_form();
extern Object analyze_g2_cell_array_for_consistency();
extern Object analyze_g2_designation_cell_for_consistency();
extern Object analyze_g2_expression_cell_for_consistency();
extern Object analyze_g2_query_cell_for_consistency();
extern Object attempt_expression_cell_execution();
extern Object attempt_expression_cell_execution_during_slot_putter();
extern Object begin_g2_cell_array_evaluations();
extern Object buffer_size_for_partial_buffer();
extern Object bytes_per_simple_vector();
extern Object c_native_clock_ticks_or_cache();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_expression_cell_computation();
extern Object cancel_scheduled_expression_cell_execution();
extern Object change_slot_value();
extern Object check_if_superior_classes_are_defined();
extern Object clean_up_wake_ups_state_if_any();
extern Object cleanup_for_g2_expression_cell();
extern Object cleanup_g2_cell_array();
extern Object clear_computation_context_variables();
extern Object clear_optimized_constants();
extern Object clone_frame();
extern Object compare_computation_styles_for_installation_differences();
extern Object compile_expression();
extern Object compile_expression_cell_for_stack();
extern Object compile_generic_formula();
extern Object compiled_cell_expression_p();
extern Object computation_style_equal();
extern Object compute_hash_of_computation_style();
extern Object compute_new_designation_cell_value();
extern Object compute_new_query_cell_value();
extern Object constant_queue_push_right();
extern Object convert_absent_slot_to_tracing_and_breakpoints();
extern Object convert_cell_type_to_type_specification();
extern Object copy_computation_style();
extern Object copy_for_slot_value();
extern Object copy_frame_for_g2_cell_array();
extern Object copy_frame_for_g2_cell_array_cell();
extern Object copy_frame_for_g2_expression_cell();
extern Object copy_frame_serial_number();
extern Object copy_out_current_wide_string();
extern Object deactivate_cell_of_g2_cell_array();
extern Object deactivate_cell_of_g2_cell_array_1();
extern Object deactivate_g2_cell_array();
extern Object deactivate_g2_designation_cell();
extern Object deactivate_g2_expression_cell();
extern Object deactivate_g2_query_cell();
extern Object deinstall_chaining_links();
extern Object delete_all_frame_notes_for_component_particular();
extern Object delete_cell_from_g2_cell_array();
extern Object delete_eval_element_1();
extern Object delete_frame();
extern Object denote_component_of_block();
extern Object deregister_use_of_computation_style();
extern Object direct_structure_method();
extern Object enter_cell_evaluation_message();
extern Object enter_skipped_cell_evaluation_message();
extern Object eval_cons_1();
extern Object evaluate_designation();
extern Object event_update_status_of_cell_array_showing();
extern Object exit_cell_expression_evaluation_message();
extern Object exit_skipped_cell_evaluation_message();
extern Object expression_cell_computation_in_progress_p();
extern Object find_matching_permanent_computation_style_if_any();
extern Object find_new_location_for_cell();
extern Object frame_serial_number_setf_helper_1();
extern Object future_task_schedule_2();
extern Object g2_cell_array_expression_cells_have_byte_code_bodies_p();
extern Object g2_cell_array_managed_array_function();
extern Object g2_expression_cell_byte_code_body_function();
extern Object generate_cell_chaining_links();
extern Object gensym_cons_1();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_entry_to_set_of_all_permanent_computation_styles();
extern Object get_simple_part_feature();
extern Object get_subpart_collection();
extern Object getfq_function_no_default();
extern Object in_order_p();
extern Object increment_profiling_calls();
extern Object initialize_g2_cell_array();
extern Object initialize_g2_cell_array_after_reading();
extern Object initialize_set_of_all_permanent_computation_style();
extern Object install_chaining_links();
extern Object issue_tracing_and_breakpoint_exit_message();
extern Object issue_tracing_and_breakpoints_entry_message();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_class_type_specification();
extern Object make_computation_style_function();
extern Object make_empty_expression_cell();
extern Object make_frame();
extern Object make_permanent_query_cell_stream_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_query_cell_stream_1_1();
extern Object make_query_cell_stream_to_cached_value();
extern Object make_thread_array();
extern Object memq_function();
extern Object modify_tracing_and_breakpoints_context_on_entry();
extern Object mutate_global_property();
extern Object note_change_to_block_1();
extern Object note_change_to_dependent_frame_1();
extern Object note_g2_cell_array_runs_while_inactive_change();
extern Object open_wake_up_collection_function();
extern Object outstanding_query_cell_stream_count();
extern Object posit_profiling_structure();
extern Object push_optimized_constant();
extern Object put_computation_style_break_message_level_where_slot_is_absent();
extern Object put_computation_style_invokable_via_backward_chaining_where_slot_is_absent();
extern Object put_computation_style_invokable_via_forward_chaining_where_slot_is_absent();
extern Object put_computation_style_may_cause_backward_chaining_where_slot_is_absent();
extern Object put_computation_style_may_cause_forward_chaining_where_slot_is_absent();
extern Object put_computation_style_reference_count_where_slot_is_absent();
extern Object put_computation_style_trace_message_level_where_slot_is_absent();
extern Object put_computation_style_warning_message_level_where_slot_is_absent();
extern Object put_g2_expression_cell_chaining_links();
extern Object put_g2_expression_cell_expression_where_slot_is_absent();
extern Object query_cell_stream_iterate_to_undeleted_frame();
extern Object query_cell_stream_structure_memory_usage();
extern Object rebuild_backpointers_of_cells_of_g2_cell_array();
extern Object rebuild_backpointers_of_g2_cell_array();
extern Object rebuild_backpointers_of_g2_expression_cell_chaining_links();
extern Object reclaim_environment_vector();
extern Object reclaim_eval_list_1();
extern Object reclaim_evaluation_place_reference();
extern Object reclaim_frame_serial_number();
extern Object reclaim_g2_cell_array_parent_frame_value();
extern Object reclaim_g2_designation_cell_frame_serial_number_qm_value();
extern Object reclaim_g2_expression_cell_cached_value_value();
extern Object reclaim_g2_expression_cell_computation_style_value();
extern Object reclaim_g2_expression_cell_g2_cell_array_value();
extern Object reclaim_g2_query_cell_cached_value_value();
extern Object reclaim_g2_query_cell_frame_serial_number_qm_value();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_managed_number_or_value_function();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_query_cell_cached_value();
extern Object reclaim_query_cell_stream();
extern Object reclaim_query_cell_stream_1_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_set_of_all_permanent_computation_style();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_temporary_constant_1();
extern Object reclaim_text_string();
extern Object recompile_cell_array();
extern Object recompile_item();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object redirect_chaining_link_recipient();
extern Object regenerate_optimized_constant();
extern Object register_designation_cell();
extern Object register_designation_cell_designation();
extern Object register_expression_cell_during_compilation();
extern Object register_expression_cell_during_slot_putter();
extern Object register_query_cell();
extern Object register_query_cell_designation();
extern Object register_use_of_computation_style();
extern Object remove_compilation_from_obsolete_expression_cell();
extern Object remove_compilations_from_obsolete_cell_array();
extern Object savable_computation_style_p();
extern Object schedule_expression_cell_execution();
extern Object schedule_expression_cell_execution_for_true_value_update();
extern Object schedule_expression_cell_execution_given_cell();
extern Object schedule_g2_cell_array_update();
extern Object schedule_or_deschedule_g2_expression_cell_cyclic_task();
extern Object serve_eval_list_of_designation_values();
extern Object set_wake_ups_function();
extern Object showing_p();
extern Object shrink_or_delete_managed_array_null_elements();
extern Object shutdown_g2_cell_array_evaluations();
extern Object slot_value_list_2();
extern Object stack_eval();
extern Object text_string_p();
extern Object tformat();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object type_specification_subtype_p();
extern Object update_designation_cell_cached_value();
extern Object update_expression_cell_cached_value();
extern Object update_g2_cell_value();
extern Object update_object_pool_meters_list();
extern Object update_query_cell_cached_value();
extern Object var_count();
extern Object withdraw_backward_chaining();

#endif

/* variables/constants */
extern Object Available_eval_conses_tail_vector;
extern Object Available_eval_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Breakpoint_level, Qbreakpoint_level);
#define Breakpoint_shift FIX((SI_Long)8L)
DECLARE_VARIABLE_WITH_SYMBOL(Cell, Qcell);
DECLARE_VARIABLE_WITH_SYMBOL(Cell_contents, Qcell_contents);
DECLARE_VARIABLE_WITH_SYMBOL(Cell_index_currently_being_registered, Qcell_index_currently_being_registered);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_query_cell_streams, Qchain_of_available_query_cell_streams);
extern Object Chain_of_available_query_cell_streams_vector;
extern Object Chain_of_available_schedule_tasks_vector;
extern Object Class_description_gkbprop;
#define Completely_unspecified_debugging_code FIX((SI_Long)65535L)
DECLARE_VARIABLE_WITH_SYMBOL(Current_block_of_dependent_frame, Qcurrent_block_of_dependent_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_activity, Qcurrent_computation_activity);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_instance, Qcurrent_computation_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_style, Qcurrent_computation_style);
DECLARE_VARIABLE_WITH_SYMBOL(Current_environment, Qcurrent_environment);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_reset, Qdebugging_reset);
extern Object Deferred_task_queue_vector;
extern Object Environment_allocation_schemes;
DECLARE_VARIABLE_WITH_SYMBOL(Evaluating_simulator_procedure_qm, Qevaluating_simulator_procedure_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Explanation_variables, Qexplanation_variables);
DECLARE_VARIABLE_WITH_SYMBOL(Expression_cell_index, Qexpression_cell_index);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(G2_cell_array_cell_class_description, Qg2_cell_array_cell_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_cell_array_class_description, Qg2_cell_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_designation_cell_class_description, Qg2_designation_cell_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_expression_cell_class_description, Qg2_expression_cell_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_query_cell_class_description, Qg2_query_cell_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Managed_array_unique_marker;
extern Object Maximum_in_place_array_size;
#define Maximum_number_of_generic_methods FIX((SI_Long)57L)
#define Message_field_mask FIX((SI_Long)15L)
DECLARE_VARIABLE_WITH_SYMBOL(New_table, Qnew_table);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Number_of_buckets_in_computation_style_set;
extern Object Numeric_data_type_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_current_task, Qpriority_of_current_task);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Query_cell_stream_count, Qquery_cell_stream_count);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Saved_breakpoint_level, Qsaved_breakpoint_level);
DECLARE_VARIABLE_WITH_SYMBOL(Saved_source_stepping_level, Qsaved_source_stepping_level);
DECLARE_VARIABLE_WITH_SYMBOL(Saved_tracing_level, Qsaved_tracing_level);
DECLARE_VARIABLE_WITH_SYMBOL(Saved_warning_level, Qsaved_warning_level);
DECLARE_VARIABLE_WITH_SYMBOL(Set_of_all_permanent_computation_style, Qset_of_all_permanent_computation_style);
DECLARE_VARIABLE_WITH_SYMBOL(Source_stepping_level, Qsource_stepping_level);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_expiration, Qstack_expiration);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Subparts, Qsubparts);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Table_to_map_generic_method_id_to_generic_method_name, Qtable_to_map_generic_method_id_to_generic_method_name);
DECLARE_VARIABLE_WITH_SYMBOL(The_only_dynamic_computation_style, Qthe_only_dynamic_computation_style);
extern Object The_type_description_of_query_cell_stream;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Tracing_message_level, Qtracing_message_level);
#define Tracing_shift FIX((SI_Long)4L)
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
#define Warning_shift FIX((SI_Long)0L)
