/* cmds1.h -- Header File for cmds1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand_optional;
extern Object Qblock;
extern Object Qdelete;
extern Object Qeq;
extern Object Qignore;
extern Object Qinspect;
extern Object Qinteger;
extern Object Qmember;
extern Object Qnot;
extern Object Qsequence;
extern Object Qsort;
extern Object Qsymbol;
extern Object Ktype;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object abort_user_mouse_tracking(Object);
extern Object abort_user_mouse_tracking_on_current_workstation(void);
extern Object add_twng_disconnect_callback(Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_vector(Object);
extern Object allow_table_command_p(Object);
extern Object apply_kb_procedure(Object,Object);
extern Object argument_list_description_matches_template_p(Object,Object);
extern Object assq_function(Object,Object);
extern Object begin_dragging_selection_handle(Object,Object,Object,Object,Object,Object,Object);
extern Object block_clonable_via_ui_command_p(Object);
extern Object block_is_allowed_to_have_frame_p(Object);
extern Object block_is_upon_kb_workspace_qm(Object);
extern Object block_of_edit_workspace_p(Object);
extern Object block_of_selection_focus_blackboard_function(Object);
extern Object block_transferable_via_ui_command_p(Object);
extern Object call_twng_disconnect_callbacks(Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_editing(void);
extern Object cancel_native_login_dialog(Object);
extern Object caption_native_window(Object,Object);
extern Object change_mode(void);
extern Object change_size_permitted_p(Object);
extern Object change_slot_value(int,...);
extern Object change_ui_property(Object,Object,Object);
extern Object check_type_or_stack_error(int,...);
extern Object check_user_ldap(Object,Object,Object);
extern Object circulate_down(Object);
extern Object circulate_up(Object);
extern Object classic_ui_p(Object);
extern Object clear_all_twng_disconnect_callbacks(void);
extern Object clear_kb(int,...);
extern Object clear_twng_disconnect_callbacks(Object);
extern Object close_telewindows_connection(Object);
extern Object close_telewindows_connection_1(Object);
extern Object coerce_text_region_to_scrap(Object);
extern Object coerce_to_free_text_type_of_slot(Object);
extern Object collect_subclasses(Object);
extern Object command_applicable_p(int,...);
extern Object command_argument_value(Object);
extern Object command_available_p(Object,Object);
extern Object command_enabled_for_ui_p(int,...);
extern Object command_unrestricted_p(int,...);
extern Object completely_shut_down_g2(int,...);
extern Object compute_blocks_to_resize_from_selection(Object,Object);
extern Object compute_category_members(Object);
extern Object compute_category_members_1(Object);
extern Object compute_filtered_blocks_from_selection(Object,Object);
extern Object compute_type_of_slot_or_stack_error(Object);
extern Object compute_user_visible_layer_position_of_item(Object);
extern Object confirm_or_cancel(int,...);
extern Object confirm_run_state_changes_p(void);
extern Object constant_queue_push_right(Object,Object);
extern Object convert_description_list_to_managed_array(int,...);
extern Object convert_text_to_text_string(int,...);
extern Object copy_as_wide_string(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_gensym_tree_with_text_strings(Object);
extern Object copy_list_using_dragging_conses_1(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_wide_string(Object);
extern Object copy_wide_string_with_case_conversion(Object,Object);
extern Object create_node_for_table_of_attributes_pane(Object,Object,Object,Object,Object,Object);
extern Object create_node_for_table_of_hidden_attributes_pane(Object,Object,Object,Object,Object,Object);
extern Object create_or_destroy_table_of_attributes_pane(Object,Object);
extern Object create_or_destroy_table_of_hidden_attributes_pane(Object,Object);
extern Object delete_frame(Object);
extern Object detail_pane(Object);
extern Object detect_and_break_deadlocks_for_ui(void);
extern Object detect_deadlocks_for_ui(void);
extern Object display_credits(int,...);
extern Object do_copy_and_insert_within_editor(void);
extern Object do_cut_and_insert_within_editor(void);
extern Object do_cut_within_editor(int,...);
extern Object do_delete_within_editor(void);
extern Object do_deletion_of_module_after_confirmation(Object,Object);
extern Object do_g2_login_button(Object);
extern Object do_insert_within_editor(void);
extern Object do_move_within_editor(void);
extern Object do_paste_within_editor(void);
extern Object drag_connection_vertex_permitted_p(Object);
extern Object drag_selection_handle(Object);
extern Object drag_selection_handle_permitted_p(Object);
extern Object draw_selection_handles_for_block(Object,Object);
extern Object draw_selection_handles_for_connection(Object,Object);
extern Object draw_selection_handles_for_current_image_plane(Object,Object,Object,Object);
extern Object draw_selection_handles_for_text_cell(Object,Object);
extern Object edit_name_of_block(Object);
extern Object editable_slot_p(Object,Object,Object,Object);
extern Object empty_text_region_p(Object);
extern Object end_editing(void);
extern Object enter_change_password_dialog(void);
extern Object enter_dialog(int,...);
extern Object enter_editing_context(int,...);
extern Object enter_editing_context_on_text_box(int,...);
extern Object enter_move_dragging_context(int,...);
extern Object enter_transfer_dragging_context(int,...);
extern Object enter_user_settings_editor(Object);
extern Object entity_like_p(Object);
extern Object establish_next_workstation_context_continuation(Object,Object,Object,Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_truth_value_is_true_p(Object);
extern Object event_plist_blackboard_function(Object);
extern Object extend_parsing_as_appropriate(int,...);
extern Object find_control_in_dialog_spec(Object,Object);
extern Object find_current_edit_state(Object);
extern Object find_frame_of_class_in_mouse_pointer(Object,Object);
extern Object find_native_view_or_stack_error(int,...);
extern Object find_native_window(int,...);
extern Object flatten_gensym_tree(Object);
extern Object frame_acts_like_arrow_button_p(Object);
extern Object frame_blackboard_function(Object);
extern Object frame_for_selection_blackboard_function(Object);
extern Object g2_command_is_enabled(Object,Object,Object);
extern Object g2_drop_item_behind_system_rpc_internal(Object,Object,Object);
extern Object g2_drop_item_to_back(Object,Object);
extern Object g2_drop_item_to_bottom(Object);
extern Object g2_drop_item_to_bottom_system_rpc_internal(Object,Object);
extern Object g2_get_item_layer_position(Object);
extern Object g2_get_item_layer_position_system_rpc_internal(Object,Object);
extern Object g2_last_input_event(Object);
extern Object g2_last_input_event_info(Object);
extern Object g2_launch_operate_on_area(Object,Object,Object,Object);
extern Object g2_lift_item_in_front_of_system_rpc_internal(Object,Object,Object);
extern Object g2_lift_item_to_front(Object,Object);
extern Object g2_lift_item_to_top(Object);
extern Object g2_lift_item_to_top_system_rpc_internal(Object,Object);
extern Object g2_ok_file_readable_p(void);
extern Object g2_refresh_image_definition(Object);
extern Object g2_register_callback_on_twng_exit(Object,Object);
extern Object g2_system_command(Object,Object,Object,Object);
extern Object g2_system_command_1(Object,Object,Object,Object);
extern Object g2_ui_close_current_editor(Object,Object);
extern Object g2_ui_create_property_grid(int,...);
extern Object g2_ui_finish_editing_session(Object,Object);
extern Object g2_ui_get_text_from_current_editor(Object);
extern Object g2_ui_insert_text_into_current_editor(Object,Object,Object);
extern Object g2_ui_launch_editor(Object,Object,Object);
extern Object g2_ui_launch_editor_extended(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object g2_ui_launch_editor_returning_handle(Object,Object,Object);
extern Object g2_ui_manage_property_grid(Object,Object,Object,Object);
extern Object g2_unregister_callback_on_twng_exit(Object,Object);
extern Object g2_window_blackboard_function(Object);
extern Object g2_window_for_gensym_window_qm(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object gensym_window_point_to_user_window_point(Object,Object,Object);
extern Object get_alias_for_slot_name_if_any(Object,Object);
extern Object get_attribute_description_evaluation_value(Object,Object);
extern Object get_attribute_texts_of_item_for_pane(Object);
extern Object get_callback_procedure(int,...);
extern Object get_directory_contents(Object);
extern Object get_g2gl_process_parent_of_workspace_if_any(int,...);
extern Object get_gensym_window_for_g2_window(Object);
extern Object get_hidden_attribute_texts_of_item_for_pane(Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_list_of_all_user_visible_attributes_for_pane(Object,Object);
extern Object get_list_of_all_virtual_attributes_for_pane(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_default_kb_pathname(int,...);
extern Object get_reference_to_item(Object);
extern Object get_slot_description_if_editable_attribute(Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_system_table_suite_for_module_or_nil(Object);
extern Object get_type_of_slot_for_user_edit(Object,Object,Object);
extern Object get_type_of_slot_if_any(int,...);
extern Object get_ui_command_function(Object);
extern Object get_ui_command_pursuer(Object);
extern Object get_ui_command_translator(Object);
extern Object get_universal_date(void);
extern Object get_validated_launch_help_procedure_qm(void);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object global_keyboard_command_permitted_p(Object);
extern Object goto_frame_instance(Object);
extern Object handle_command(Object,Object);
extern Object handle_create_new_module_window_menu_choice(Object,Object);
extern Object handle_file_related_window_menu_choice(Object);
extern Object handle_image_plane_event(Object,Object,Object,Object);
extern Object handle_login_dialog_message(Object);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_of_workspace(Object);
extern Object image_plane_of_workspace_on_window(Object,Object);
extern Object image_plane_of_workspace_on_workstation(Object,Object);
extern Object inform_ui_client_interfaces_of_general_update(Object,Object);
extern Object insert_text_string_at_cursor(int,...);
extern Object inspect_permitted_p(void);
extern Object intern_wide_string(int,...);
extern Object intern_wide_string_no_reclaim(int,...);
extern Object inverse_scalef_function(Object,Object);
extern Object is_in_ldap_mode_p(void);
extern Object item_has_unsaved_changes_visible_in_tables_p(Object);
extern Object item_is_either_not_permanent_or_from_an_editable_module_p(Object);
extern Object item_may_be_deleted_by_user(Object);
extern Object item_menu_command_permitted_p(Object,Object);
extern Object kb_has_modularity_information_p(void);
extern Object launch_editor_1(int,...);
extern Object launch_editor_2(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object leave_package_preparation_mode(void);
extern Object lengthw(Object);
extern Object load_kb_permitted_p(void);
extern Object log_out_workstation(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lower_block_to_bottom(Object);
extern Object lower_image_plane_to_bottom(Object);
extern Object main_menu_command_permitted_p(Object);
extern Object make_32bit_integer(Object,Object);
extern Object make_class_header_string(Object);
extern Object make_dialog_control(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_dialog_spec(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_error_text(Object,Object);
extern Object make_gensym_list_1(Object);
extern Object make_help_workspace(Object);
extern Object make_menu_description(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_new_top_level_kb_workspace(int,...);
extern Object make_partial_command(Object,Object);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_proprietary_now(void);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_system_rpc_1(Object,Object,Object);
extern Object make_text_representation_for_slot_value(int,...);
extern Object make_ui_command(int,...);
extern Object make_virtual_attribute_class_header_string(Object);
extern Object manage_dialog(Object,Object,Object,Object);
extern Object manage_native_editor(int,...);
extern Object map_g2_window_to_gensym_window(Object);
extern Object map_to_gensym_window_or_stack_error(Object);
extern Object mdi_frame_p(Object);
extern Object mega_refresh(Object);
extern Object memq_function(Object,Object);
extern Object menu_obtains_p(Object,Object);
extern Object modify_control_in_dialog_spec(Object,Object,Object);
extern Object most_interesting_frame_blackboard_function(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object move_items_to_mouse_of_window(Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object n_32bit_integer_high_part(Object);
extern Object n_32bit_integer_low_part(Object);
extern Object name_block_permitted_p(Object);
extern Object named_kb_workspace_tester_function(Object);
extern Object named_workspaces_exist_p(void);
extern Object native_editor_p(Object);
extern Object native_editor_window(Object);
extern Object native_login_dialog_p(Object);
extern Object neatly_stack_image_planes_in_window(Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object notify_user(int,...);
extern Object notify_user_of_breakpoint(Object);
extern Object of_class_p_function(Object,Object);
extern Object order_blocks(Object,Object,Object);
extern Object original_x_in_window_blackboard_function(Object);
extern Object original_y_in_window_blackboard_function(Object);
extern Object package_internal_data_property(Object,Object,Object,Object);
extern Object package_internal_data_with_slot(Object,Object,Object,Object);
extern Object pane_blackboard_function(Object);
extern Object parse_editor_prompt_filter(Object);
extern Object parse_slot_name_denotation(Object,Object);
extern Object parseable_symbol_from_key_code(Object);
extern Object post_menu_named_function(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object post_native_login_dialog(int,...);
extern Object primary_selection_color(Object);
extern Object processed_editor_toolbar(Object);
extern Object put_symbol_valued_slot(Object,Object,Object);
extern Object put_up_aliases_table(Object);
extern Object put_up_attributes_table(int,...);
extern Object put_up_special_character_help_workspace(void);
extern Object put_up_table_of_network_info(void);
extern Object put_up_virtual_attributes_table(Object,Object,Object);
extern Object put_workspace_on_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object raise_block_to_top(Object);
extern Object raise_image_plane_to_top(int,...);
extern Object raw_stack_error_named_error(Object,Object);
extern Object read_symbol_list_from_text_string(Object);
extern Object recent_loaded_kb_available_p(void);
extern Object recent_loaded_kb_tester_function(Object);
extern Object reclaim_32bit_integer(Object);
extern Object reclaim_error_text_but_not_string(Object);
extern Object reclaim_eval_alist(Object);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_evaluation_structure(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_tree_with_text_strings(Object);
extern Object reclaim_list_of_block_snapshots(Object);
extern Object reclaim_managed_simple_vector(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_wide_string(Object);
extern Object record_block_for_tformat(Object);
extern Object refresh_image_definition_from_file(Object);
extern Object refresh_window(Object);
extern Object regenerate_optimized_constant(Object);
extern Object reinstall_authorized_users(void);
extern Object release_mouse_pointer_if_any(Object);
extern Object remove_tracing_and_breakpoints(void);
extern Object remove_twng_disconnect_callback(Object,Object);
extern Object render_thing_in_xor_overlay_p(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object requeue_mouse_motion_event(Object);
extern Object resize_block_permitted_p(Object);
extern Object resize_native_login_dialog(Object);
extern Object return_from_breakpoint(int,...);
extern Object return_from_current_workstation_context(int,...);
extern Object return_from_system_defined_rpc(Object,Object);
extern Object save_kb(int,...);
extern Object save_kb_permitted_p(void);
extern Object scalef_function(Object,Object);
extern Object secondary_selection_color(Object);
extern Object selection_handle_mouse_cursor(Object);
extern Object serve_text_of_attribute(Object,Object,Object);
extern Object set_simulate_proprietary_mode(Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_stripping_flags_as_specified(Object,Object,Object);
extern Object set_ui_command_function(Object,Object);
extern Object set_ui_command_pursuer(Object,Object);
extern Object set_ui_command_translator(Object,Object);
extern Object show_or_hide(int,...);
extern Object shrink_wrap_workspace(Object);
extern Object shut_down_ab_process(int,...);
extern Object slot_denotation_of_editable_slot_or_stack_error(Object,Object,Object);
extern Object slot_name_blackboard_function(Object);
extern Object slot_value_as_string(Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object snapshot_command_argument(Object);
extern Object spot_blackboard_function(Object);
extern Object start_procedure_invocation_in_place(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object stored_callback_procedure(Object);
extern Object stringw(Object);
extern Object strip_all_texts(void);
extern Object strip_choice_obtains_p(Object,Object);
extern Object symbolize(Object);
extern Object synthesize_mouse_pointer(int,...);
extern Object system_pause(int,...);
extern Object system_procedure_argument_list_error(Object,Object,Object,Object);
extern Object system_reset(void);
extern Object system_restart(void);
extern Object system_resume(void);
extern Object system_rpc_error(Object,Object,Object);
extern Object system_start(void);
extern Object system_state_change_from_scheduler(Object);
extern Object system_state_change_from_scheduler_1(Object);
extern Object system_table_installed_p(Object);
extern Object system_table_tester_function(Object);
extern Object text_can_be_pasted_in_current_workstation_p(void);
extern Object text_cell_p(Object);
extern Object text_string_for_item_or_value(Object);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tformat_text_string(int,...);
extern Object tformat_warning_about_modules_that_require_this_if_necessary(Object);
extern Object timestamp_blackboard_function(Object);
extern Object toggle_visible_grid(Object);
extern Object token_from_text_string(Object,Object,Object);
extern Object transfer_item_to_mouse_of_window(Object,Object);
extern Object transfer_items_to_mouse_of_window(int,...);
extern Object translate_control_id_for_dialog(Object);
extern Object translate_dialog_spec(Object);
extern Object translate_flags_for_dialog(Object,Object);
extern Object translate_label_for_dialog(Object);
extern Object translate_style_for_dialog(Object);
extern Object translated_string_for_symbol(int,...);
extern Object translation_for_symbol_qm(int,...);
extern Object turn_off_explanation_caching_for_all(void);
extern Object turn_on_explanation_caching_for_all(void);
extern Object twng_window_p(Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_changed_modules_note(void);
extern Object twrite_character(Object);
extern Object twrite_general_string(Object);
extern Object twrite_login_failure_translation_symbol(Object);
extern Object type_of_slot_if_editable(int,...);
extern Object ui_stack_error_for_non_connected_window(Object,Object);
extern Object unmangle_slot_component_alias(Object);
extern Object upcase_text_string_in_place(Object);
extern Object update_att_tables(Object,Object);
extern Object update_mouse_cursor(Object);
extern Object update_property_grid_all(Object);
extern Object update_property_pane_after_edit(Object);
extern Object update_table_of_attributes_pane(Object,Object);
extern Object update_table_of_hidden_attributes_pane(Object,Object);
extern Object user_menu_choice_runnable_p(Object,Object);
extern Object user_workspace_p(Object);
extern Object valid_image_plane_p(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object visible_grid_permitted_p(Object);
extern Object window_blackboard_function(Object);
extern Object workstation_blackboard_function(Object);
extern Object workstation_context_specifics_blackboard_function(Object);
extern Object write_stored_value(Object);
extern Object x_in_window_blackboard_function(Object);
extern Object x_in_workspace_blackboard_function(Object);
extern Object y_in_window_blackboard_function(Object);
extern Object y_in_workspace_blackboard_function(Object);

#else

extern Object abort_current_workstation_context();
extern Object abort_user_mouse_tracking();
extern Object abort_user_mouse_tracking_on_current_workstation();
extern Object add_twng_disconnect_callback();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_vector();
extern Object allow_table_command_p();
extern Object apply_kb_procedure();
extern Object argument_list_description_matches_template_p();
extern Object assq_function();
extern Object begin_dragging_selection_handle();
extern Object block_clonable_via_ui_command_p();
extern Object block_is_allowed_to_have_frame_p();
extern Object block_is_upon_kb_workspace_qm();
extern Object block_of_edit_workspace_p();
extern Object block_of_selection_focus_blackboard_function();
extern Object block_transferable_via_ui_command_p();
extern Object call_twng_disconnect_callbacks();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_editing();
extern Object cancel_native_login_dialog();
extern Object caption_native_window();
extern Object change_mode();
extern Object change_size_permitted_p();
extern Object change_slot_value();
extern Object change_ui_property();
extern Object check_type_or_stack_error();
extern Object check_user_ldap();
extern Object circulate_down();
extern Object circulate_up();
extern Object classic_ui_p();
extern Object clear_all_twng_disconnect_callbacks();
extern Object clear_kb();
extern Object clear_twng_disconnect_callbacks();
extern Object close_telewindows_connection();
extern Object close_telewindows_connection_1();
extern Object coerce_text_region_to_scrap();
extern Object coerce_to_free_text_type_of_slot();
extern Object collect_subclasses();
extern Object command_applicable_p();
extern Object command_argument_value();
extern Object command_available_p();
extern Object command_enabled_for_ui_p();
extern Object command_unrestricted_p();
extern Object completely_shut_down_g2();
extern Object compute_blocks_to_resize_from_selection();
extern Object compute_category_members();
extern Object compute_category_members_1();
extern Object compute_filtered_blocks_from_selection();
extern Object compute_type_of_slot_or_stack_error();
extern Object compute_user_visible_layer_position_of_item();
extern Object confirm_or_cancel();
extern Object confirm_run_state_changes_p();
extern Object constant_queue_push_right();
extern Object convert_description_list_to_managed_array();
extern Object convert_text_to_text_string();
extern Object copy_as_wide_string();
extern Object copy_frame_serial_number();
extern Object copy_gensym_tree_with_text_strings();
extern Object copy_list_using_dragging_conses_1();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_wide_string();
extern Object copy_wide_string_with_case_conversion();
extern Object create_node_for_table_of_attributes_pane();
extern Object create_node_for_table_of_hidden_attributes_pane();
extern Object create_or_destroy_table_of_attributes_pane();
extern Object create_or_destroy_table_of_hidden_attributes_pane();
extern Object delete_frame();
extern Object detail_pane();
extern Object detect_and_break_deadlocks_for_ui();
extern Object detect_deadlocks_for_ui();
extern Object display_credits();
extern Object do_copy_and_insert_within_editor();
extern Object do_cut_and_insert_within_editor();
extern Object do_cut_within_editor();
extern Object do_delete_within_editor();
extern Object do_deletion_of_module_after_confirmation();
extern Object do_g2_login_button();
extern Object do_insert_within_editor();
extern Object do_move_within_editor();
extern Object do_paste_within_editor();
extern Object drag_connection_vertex_permitted_p();
extern Object drag_selection_handle();
extern Object drag_selection_handle_permitted_p();
extern Object draw_selection_handles_for_block();
extern Object draw_selection_handles_for_connection();
extern Object draw_selection_handles_for_current_image_plane();
extern Object draw_selection_handles_for_text_cell();
extern Object edit_name_of_block();
extern Object editable_slot_p();
extern Object empty_text_region_p();
extern Object end_editing();
extern Object enter_change_password_dialog();
extern Object enter_dialog();
extern Object enter_editing_context();
extern Object enter_editing_context_on_text_box();
extern Object enter_move_dragging_context();
extern Object enter_transfer_dragging_context();
extern Object enter_user_settings_editor();
extern Object entity_like_p();
extern Object establish_next_workstation_context_continuation();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object evaluation_truth_value_is_true_p();
extern Object event_plist_blackboard_function();
extern Object extend_parsing_as_appropriate();
extern Object find_control_in_dialog_spec();
extern Object find_current_edit_state();
extern Object find_frame_of_class_in_mouse_pointer();
extern Object find_native_view_or_stack_error();
extern Object find_native_window();
extern Object flatten_gensym_tree();
extern Object frame_acts_like_arrow_button_p();
extern Object frame_blackboard_function();
extern Object frame_for_selection_blackboard_function();
extern Object g2_command_is_enabled();
extern Object g2_drop_item_behind_system_rpc_internal();
extern Object g2_drop_item_to_back();
extern Object g2_drop_item_to_bottom();
extern Object g2_drop_item_to_bottom_system_rpc_internal();
extern Object g2_get_item_layer_position();
extern Object g2_get_item_layer_position_system_rpc_internal();
extern Object g2_last_input_event();
extern Object g2_last_input_event_info();
extern Object g2_launch_operate_on_area();
extern Object g2_lift_item_in_front_of_system_rpc_internal();
extern Object g2_lift_item_to_front();
extern Object g2_lift_item_to_top();
extern Object g2_lift_item_to_top_system_rpc_internal();
extern Object g2_ok_file_readable_p();
extern Object g2_refresh_image_definition();
extern Object g2_register_callback_on_twng_exit();
extern Object g2_system_command();
extern Object g2_system_command_1();
extern Object g2_ui_close_current_editor();
extern Object g2_ui_create_property_grid();
extern Object g2_ui_finish_editing_session();
extern Object g2_ui_get_text_from_current_editor();
extern Object g2_ui_insert_text_into_current_editor();
extern Object g2_ui_launch_editor();
extern Object g2_ui_launch_editor_extended();
extern Object g2_ui_launch_editor_returning_handle();
extern Object g2_ui_manage_property_grid();
extern Object g2_unregister_callback_on_twng_exit();
extern Object g2_window_blackboard_function();
extern Object g2_window_for_gensym_window_qm();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_list_4();
extern Object gensym_window_point_to_user_window_point();
extern Object get_alias_for_slot_name_if_any();
extern Object get_attribute_description_evaluation_value();
extern Object get_attribute_texts_of_item_for_pane();
extern Object get_callback_procedure();
extern Object get_directory_contents();
extern Object get_g2gl_process_parent_of_workspace_if_any();
extern Object get_gensym_window_for_g2_window();
extern Object get_hidden_attribute_texts_of_item_for_pane();
extern Object get_instance_with_name_if_any();
extern Object get_list_of_all_user_visible_attributes_for_pane();
extern Object get_list_of_all_virtual_attributes_for_pane();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_default_kb_pathname();
extern Object get_reference_to_item();
extern Object get_slot_description_if_editable_attribute();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_system_table_suite_for_module_or_nil();
extern Object get_type_of_slot_for_user_edit();
extern Object get_type_of_slot_if_any();
extern Object get_ui_command_function();
extern Object get_ui_command_pursuer();
extern Object get_ui_command_translator();
extern Object get_universal_date();
extern Object get_validated_launch_help_procedure_qm();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object global_keyboard_command_permitted_p();
extern Object goto_frame_instance();
extern Object handle_command();
extern Object handle_create_new_module_window_menu_choice();
extern Object handle_file_related_window_menu_choice();
extern Object handle_image_plane_event();
extern Object handle_login_dialog_message();
extern Object image_plane_blackboard_function();
extern Object image_plane_of_workspace();
extern Object image_plane_of_workspace_on_window();
extern Object image_plane_of_workspace_on_workstation();
extern Object inform_ui_client_interfaces_of_general_update();
extern Object insert_text_string_at_cursor();
extern Object inspect_permitted_p();
extern Object intern_wide_string();
extern Object intern_wide_string_no_reclaim();
extern Object inverse_scalef_function();
extern Object is_in_ldap_mode_p();
extern Object item_has_unsaved_changes_visible_in_tables_p();
extern Object item_is_either_not_permanent_or_from_an_editable_module_p();
extern Object item_may_be_deleted_by_user();
extern Object item_menu_command_permitted_p();
extern Object kb_has_modularity_information_p();
extern Object launch_editor_1();
extern Object launch_editor_2();
extern Object leave_package_preparation_mode();
extern Object lengthw();
extern Object load_kb_permitted_p();
extern Object log_out_workstation();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lower_block_to_bottom();
extern Object lower_image_plane_to_bottom();
extern Object main_menu_command_permitted_p();
extern Object make_32bit_integer();
extern Object make_class_header_string();
extern Object make_dialog_control();
extern Object make_dialog_spec();
extern Object make_error_text();
extern Object make_gensym_list_1();
extern Object make_help_workspace();
extern Object make_menu_description();
extern Object make_new_top_level_kb_workspace();
extern Object make_partial_command();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_proprietary_now();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_system_rpc_1();
extern Object make_text_representation_for_slot_value();
extern Object make_ui_command();
extern Object make_virtual_attribute_class_header_string();
extern Object manage_dialog();
extern Object manage_native_editor();
extern Object map_g2_window_to_gensym_window();
extern Object map_to_gensym_window_or_stack_error();
extern Object mdi_frame_p();
extern Object mega_refresh();
extern Object memq_function();
extern Object menu_obtains_p();
extern Object modify_control_in_dialog_spec();
extern Object most_interesting_frame_blackboard_function();
extern Object mouse_pointer_blackboard_function();
extern Object move_items_to_mouse_of_window();
extern Object mutate_global_property();
extern Object n_32bit_integer_high_part();
extern Object n_32bit_integer_low_part();
extern Object name_block_permitted_p();
extern Object named_kb_workspace_tester_function();
extern Object named_workspaces_exist_p();
extern Object native_editor_p();
extern Object native_editor_window();
extern Object native_login_dialog_p();
extern Object neatly_stack_image_planes_in_window();
extern Object non_menu_choice_permitted_p();
extern Object notify_user();
extern Object notify_user_of_breakpoint();
extern Object of_class_p_function();
extern Object order_blocks();
extern Object original_x_in_window_blackboard_function();
extern Object original_y_in_window_blackboard_function();
extern Object package_internal_data_property();
extern Object package_internal_data_with_slot();
extern Object pane_blackboard_function();
extern Object parse_editor_prompt_filter();
extern Object parse_slot_name_denotation();
extern Object parseable_symbol_from_key_code();
extern Object post_menu_named_function();
extern Object post_native_login_dialog();
extern Object primary_selection_color();
extern Object processed_editor_toolbar();
extern Object put_symbol_valued_slot();
extern Object put_up_aliases_table();
extern Object put_up_attributes_table();
extern Object put_up_special_character_help_workspace();
extern Object put_up_table_of_network_info();
extern Object put_up_virtual_attributes_table();
extern Object put_workspace_on_pane_function();
extern Object raise_block_to_top();
extern Object raise_image_plane_to_top();
extern Object raw_stack_error_named_error();
extern Object read_symbol_list_from_text_string();
extern Object recent_loaded_kb_available_p();
extern Object recent_loaded_kb_tester_function();
extern Object reclaim_32bit_integer();
extern Object reclaim_error_text_but_not_string();
extern Object reclaim_eval_alist();
extern Object reclaim_eval_cons_1();
extern Object reclaim_evaluation_structure();
extern Object reclaim_evaluation_value();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_tree_with_text_strings();
extern Object reclaim_list_of_block_snapshots();
extern Object reclaim_managed_simple_vector();
extern Object reclaim_schedule_task_args();
extern Object reclaim_slot_value();
extern Object reclaim_text_string();
extern Object reclaim_wide_string();
extern Object record_block_for_tformat();
extern Object refresh_image_definition_from_file();
extern Object refresh_window();
extern Object regenerate_optimized_constant();
extern Object reinstall_authorized_users();
extern Object release_mouse_pointer_if_any();
extern Object remove_tracing_and_breakpoints();
extern Object remove_twng_disconnect_callback();
extern Object render_thing_in_xor_overlay_p();
extern Object replenish_lookup_cons_pool();
extern Object requeue_mouse_motion_event();
extern Object resize_block_permitted_p();
extern Object resize_native_login_dialog();
extern Object return_from_breakpoint();
extern Object return_from_current_workstation_context();
extern Object return_from_system_defined_rpc();
extern Object save_kb();
extern Object save_kb_permitted_p();
extern Object scalef_function();
extern Object secondary_selection_color();
extern Object selection_handle_mouse_cursor();
extern Object serve_text_of_attribute();
extern Object set_simulate_proprietary_mode();
extern Object set_skip_list_entry();
extern Object set_stripping_flags_as_specified();
extern Object set_ui_command_function();
extern Object set_ui_command_pursuer();
extern Object set_ui_command_translator();
extern Object show_or_hide();
extern Object shrink_wrap_workspace();
extern Object shut_down_ab_process();
extern Object slot_denotation_of_editable_slot_or_stack_error();
extern Object slot_name_blackboard_function();
extern Object slot_value_as_string();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object snapshot_command_argument();
extern Object spot_blackboard_function();
extern Object start_procedure_invocation_in_place();
extern Object stored_callback_procedure();
extern Object stringw();
extern Object strip_all_texts();
extern Object strip_choice_obtains_p();
extern Object symbolize();
extern Object synthesize_mouse_pointer();
extern Object system_pause();
extern Object system_procedure_argument_list_error();
extern Object system_reset();
extern Object system_restart();
extern Object system_resume();
extern Object system_rpc_error();
extern Object system_start();
extern Object system_state_change_from_scheduler();
extern Object system_state_change_from_scheduler_1();
extern Object system_table_installed_p();
extern Object system_table_tester_function();
extern Object text_can_be_pasted_in_current_workstation_p();
extern Object text_cell_p();
extern Object text_string_for_item_or_value();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tformat_text_string();
extern Object tformat_warning_about_modules_that_require_this_if_necessary();
extern Object timestamp_blackboard_function();
extern Object toggle_visible_grid();
extern Object token_from_text_string();
extern Object transfer_item_to_mouse_of_window();
extern Object transfer_items_to_mouse_of_window();
extern Object translate_control_id_for_dialog();
extern Object translate_dialog_spec();
extern Object translate_flags_for_dialog();
extern Object translate_label_for_dialog();
extern Object translate_style_for_dialog();
extern Object translated_string_for_symbol();
extern Object translation_for_symbol_qm();
extern Object turn_off_explanation_caching_for_all();
extern Object turn_on_explanation_caching_for_all();
extern Object twng_window_p();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_changed_modules_note();
extern Object twrite_character();
extern Object twrite_general_string();
extern Object twrite_login_failure_translation_symbol();
extern Object type_of_slot_if_editable();
extern Object ui_stack_error_for_non_connected_window();
extern Object unmangle_slot_component_alias();
extern Object upcase_text_string_in_place();
extern Object update_att_tables();
extern Object update_mouse_cursor();
extern Object update_property_grid_all();
extern Object update_property_pane_after_edit();
extern Object update_table_of_attributes_pane();
extern Object update_table_of_hidden_attributes_pane();
extern Object user_menu_choice_runnable_p();
extern Object user_workspace_p();
extern Object valid_image_plane_p();
extern Object validate_item_or_evaluation_value();
extern Object visible_grid_permitted_p();
extern Object window_blackboard_function();
extern Object workstation_blackboard_function();
extern Object workstation_context_specifics_blackboard_function();
extern Object write_stored_value();
extern Object x_in_window_blackboard_function();
extern Object x_in_workspace_blackboard_function();
extern Object y_in_window_blackboard_function();
extern Object y_in_workspace_blackboard_function();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Alternate_symbols_for_translation, Qalternate_symbols_for_translation);
extern Object Alternate_translations_for_login_dialogs;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_embedded_option_semantics_graph, Qcache_embedded_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_restricted_use_option_semantics_graph, Qcache_restricted_use_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_runtime_option_semantics_graph, Qcache_runtime_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
#define Cbs_dropdown FIX((SI_Long)2L)
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chart_class_description, Qchart_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_workspace, Qcurrent_edit_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_this_name, Qcurrent_indicator_for_category_of_this_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_pathname_qm, Qcurrent_kb_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_rpc_icp_socket_qm, Qcurrent_system_rpc_icp_socket_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Default_kb_pathname_qm, Qdefault_kb_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Edit_states, Qedit_states);
#define Editor_add_toolbar_button FIX((SI_Long)6L)
#define Editor_cancel FIX((SI_Long)7L)
DECLARE_VARIABLE_WITH_SYMBOL(Editor_caption_text_override_qm, Qeditor_caption_text_override_qm);
#define Editor_exit_new FIX((SI_Long)48L)
DECLARE_VARIABLE_WITH_SYMBOL(Editor_prompt_filter_qm, Qeditor_prompt_filter_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_toolbar_user_callback, Qeditor_toolbar_user_callback);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_window_handle, Qeditor_window_handle);
extern Object End_of_recovery_list;
DECLARE_VARIABLE_WITH_SYMBOL(Entity_class_description, Qentity_class_description);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
extern Object Frame_or_frames_with_this_name_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(G2_login_class_description, Qg2_login_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2passwdexe_is_executable_p, Qg2passwdexe_is_executable_p);
DECLARE_VARIABLE_WITH_SYMBOL(Global_keyboard_command_choices, Qglobal_keyboard_command_choices);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nms_menu_choiced_item_id, Qglobal_nms_menu_choiced_item_id);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nmsci_id_for_attributes_pane, Qglobal_nmsci_id_for_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nmsci_id_for_hidden_attributes_pane, Qglobal_nmsci_id_for_hidden_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_attributes_pane, Qglobal_table_of_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_attributes_pane_pointer, Qglobal_table_of_attributes_pane_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_hidden_attributes_pane, Qglobal_table_of_hidden_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_hidden_attributes_pane_pointer, Qglobal_table_of_hidden_attributes_pane_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_class_description, Qgraph_class_description);
#define Higher_than_any_priority FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Highest_state_index, Qhighest_state_index);
#define Icp_window_protocol_supports_manage_dialog FIX((SI_Long)72L)
#define Illegal_key_code FIX((SI_Long)-1L)
extern Object Illegal_key_index;
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
DECLARE_VARIABLE_WITH_SYMBOL(Inspect_command_class_description, Qinspect_command_class_description);
extern Object Instances_specific_to_this_class_kbprop;
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
extern Object Key_index_bits;
extern Object Launch_editor_options_type;
DECLARE_VARIABLE_WITH_SYMBOL(Learned_list_to_expedite_ui, Qlearned_list_to_expedite_ui);
DECLARE_VARIABLE_WITH_SYMBOL(Main_menu_choices, Qmain_menu_choices);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
#define Maximum_open_editors FIX((SI_Long)4096L)
#define Mb_iconasterisk FIX((SI_Long)64L)
#define Mb_iconexclamation FIX((SI_Long)48L)
#define Mb_iconhand FIX((SI_Long)16L)
#define Mb_iconquestion FIX((SI_Long)32L)
DECLARE_VARIABLE_WITH_SYMBOL(Message_class_description, Qmessage_class_description);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(N_32bit_constants, Q32bit_constants);
DECLARE_VARIABLE_WITH_SYMBOL(Native_alias_creation_dialog, Qnative_alias_creation_dialog);
DECLARE_VARIABLE_WITH_SYMBOL(Native_login_dialog, Qnative_login_dialog);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Non_menu_choices, Qnon_menu_choices);
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
extern Object Old_eval_cons_list;
extern Object Override_limited_license_block_on_inspect_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Override_preferred_editor, Qoverride_preferred_editor);
DECLARE_VARIABLE_WITH_SYMBOL(Package_preparation_mode, Qpackage_preparation_mode);
extern Object Plus_missing_argument_plus;
DECLARE_VARIABLE_WITH_SYMBOL(Printer_setup, Qprinter_setup);
DECLARE_VARIABLE_WITH_SYMBOL(Readout_table_class_description, Qreadout_table_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Redo_saved_changes, Qredo_saved_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Relations_tag_list, Qrelations_tag_list);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Scrap_class_description, Qscrap_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Short_menus_qm, Qshort_menus_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simulate_proprietary_qm, Qsimulate_proprietary_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Snapshots_of_related_blocks, Qsnapshots_of_related_blocks);
DECLARE_VARIABLE_WITH_SYMBOL(Sparse_known_pathnames_list, Qsparse_known_pathnames_list);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Statement_class_description, Qstatement_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_defined_rpcs, Qsystem_defined_rpcs);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Text_box_class_description, Qtext_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Unevaluated_expression, Qunevaluated_expression);
#define Unicode_bit FIX((SI_Long)16777216L)
extern Object Unicode_character_bits;
DECLARE_VARIABLE_WITH_SYMBOL(User_menu_choice_class_description, Quser_menu_choice_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
extern Object Within_side_limits;
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
#define Ws_caption FIX((SI_Long)192L)
#define Ws_clipchildren FIX((SI_Long)512L)
#define Ws_ex_clientedge FIX((SI_Long)512L)
#define Ws_sysmenu FIX((SI_Long)8L)
#define Ws_tabstop FIX((SI_Long)1L)
#define Ws_visible FIX((SI_Long)4096L)
#define Ws_vscroll FIX((SI_Long)32L)
