/* cnct1.h -- Header File for cnct1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qblock;
extern Object Qcons;
extern Object Qeq;
extern Object Qvector;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_for_connection(Object);
extern Object add_class_to_environment(int,...);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object assq_function(Object,Object);
extern Object bytes_per_simple_vector(Object);
extern Object change_connection_attribute(Object,Object,Object);
extern Object change_connection_attribute_1(Object,Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object cleanup_for_connection_post(Object);
extern Object clear_connection_item_table_skip_list(Object);
extern Object clear_connections_found_in_search(Object);
extern Object clear_optimized_constants(void);
extern Object collect_subclasses(Object);
extern Object compute_connection_vertices(Object);
extern Object compute_scaled_line_pattern(Object,Object,Object);
extern Object connection_arrows_of_connection(Object);
extern Object connection_class_of_connection(Object);
extern Object connection_cons_1(Object,Object);
extern Object connection_cons_memory_usage(void);
extern Object connection_frame_of_connection_qm(Object);
extern Object connection_item_name_or_names(Object);
extern Object connection_item_structure_memory_usage(void);
extern Object connection_line_pattern(Object);
extern Object connection_line_pattern_absolute_p(Object);
extern Object connection_line_pattern_dashes(Object);
extern Object connection_line_pattern_explicit_p(Object);
extern Object connection_list_2(Object,Object);
extern Object connection_list_3(Object,Object,Object);
extern Object connection_list_4(Object,Object,Object,Object);
extern Object connection_list_trace_hook(Object);
extern Object connection_p_function(Object);
extern Object connection_post_equal(Object,Object);
extern Object connection_spot_structure_memory_usage(void);
extern Object connection_striped_p(Object);
extern Object connection_structure_memory_usage(void);
extern Object connection_structures(Object);
extern Object connection_within_module_p(Object,Object);
extern Object copy_list_using_connection_conses_1(Object);
extern Object copy_list_using_scope_conses(Object);
extern Object copy_list_using_slot_value_conses_1(Object);
extern Object copy_tree_using_connection_conses_1(Object);
extern Object deactivate_for_connection(Object);
extern Object decache_roles_for_connection_post_and_namesakes(Object,Object);
extern Object decache_roles_for_entities_related_to_this_connection(Object);
extern Object delete_connection_cons_1(Object,Object);
extern Object delete_connection_element_1(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object downgrade_connections(Object);
extern Object enlarge_workspace_for_connection(Object,Object);
extern Object enlarge_workspace_if_necessary(int,...);
extern Object find_closest_connection_vertex(Object,Object,Object,Object);
extern Object frame_serial_number_for_connection_function(Object);
extern Object generate_spot_for_connection(Object,Object);
extern Object generate_spot_for_loose_end(Object,Object);
extern Object generic_directly_connected_p(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_connection_color(Object,Object);
extern Object get_cross_section_regions_function(Object);
extern Object get_direction_of_connection(int,...);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_module_block_is_in(Object);
extern Object get_module_connection_is_in(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object instantiated_connection_class_p(Object);
extern Object inverse_scalef_function(Object,Object);
extern Object invoke_rules_for_direct_connection_chaining(Object,Object);
extern Object invoke_rules_for_indirect_connection_chaining(Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lookup_stock_line_pattern_element(Object);
extern Object loose_end_p_function(Object);
extern Object loose_end_spot_structure_memory_usage(void);
extern Object make_connection_1(void);
extern Object make_connection_item_1(Object);
extern Object make_connection_item_table_skip_list_sentinel(Object,Object);
extern Object make_connection_list_1(Object);
extern Object make_connection_spot_1(void);
extern Object make_loose_end_spot_1(void);
extern Object make_permanent_connection_item_structure_internal(void);
extern Object make_permanent_connection_spot_structure_internal(void);
extern Object make_permanent_connection_structure_internal(void);
extern Object make_permanent_loose_end_spot_structure_internal(void);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_thread_array(Object);
extern Object move_connection_vertex_by(Object,Object,Object,Object);
extern Object move_diagonal_connection_vertex_by(Object,Object,Object,Object);
extern Object move_if_loose_end(Object,Object,Object);
extern Object move_item_by(int,...);
extern Object move_orthogonal_connection_vertex_by(Object,Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object name_or_names_like_p(Object,Object);
extern Object note_change_of_connection_for_drawing(Object);
extern Object note_change_to_connection_1(Object);
extern Object note_change_to_connection_2(Object);
extern Object note_deletion_of_connection(Object);
extern Object note_deletion_of_connection_2(Object);
extern Object note_deletion_of_connection_for_drawing(Object);
extern Object note_name_change_for_connection_post(Object,Object,Object);
extern Object output_connection_p_function(Object,Object);
extern Object outstanding_connection_conses(void);
extern Object outstanding_connection_count(void);
extern Object outstanding_connection_item_count(void);
extern Object outstanding_connection_spot_count(void);
extern Object outstanding_loose_end_spot_count(void);
extern Object push_connection_vertex_spot_if_close(Object,Object);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object push_selection_handle_spot(Object,Object,Object,Object,Object,Object);
extern Object put_attribute_value(int,...);
extern Object put_control_block_input_1_where_slot_is_absent(Object,Object);
extern Object put_control_block_input_2_where_slot_is_absent(Object,Object);
extern Object put_control_block_input_where_slot_is_absent(Object,Object);
extern Object put_control_block_output_where_slot_is_absent(Object,Object);
extern Object reclaim_connection_1(Object);
extern Object reclaim_connection_cons_1(Object);
extern Object reclaim_connection_item_1(Object);
extern Object reclaim_connection_item_table_nodes(Object,Object);
extern Object reclaim_connection_list_1(Object);
extern Object reclaim_connection_list_star_1(Object);
extern Object reclaim_connection_spot_1(Object);
extern Object reclaim_connection_tree_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_loose_end_spot_1(Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_structure_if_any(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_subworkspace_connection_post_from_connection(Object,Object,Object,Object);
extern Object render_connection_in_xor_overlay_p_function(Object);
extern Object replenish_connection_cons_pool(void);
extern Object replenish_connection_list_pool(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object scalef_function(Object,Object);
extern Object scope_cons(Object,Object);
extern Object selection_handles_visible_p(Object,Object);
extern Object send_ws_representations_item_remove_as_subblock(Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object structure_type_p(Object,Object);
extern Object subclasses(Object);
extern Object type_of_named_structure(Object);
extern Object update_connection_images(Object,Object,Object);
extern Object update_extreme_edges_from_connection(Object);
extern Object update_object_pool_meters_list(Object);
extern Object upgrade_block_connections(Object);
extern Object upgrade_connections(Object);
extern Object workspace_of_connection_frame(Object);
extern Object workspace_of_connection_qm(Object);

#else

extern Object activate_for_connection();
extern Object add_class_to_environment();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object assq_function();
extern Object bytes_per_simple_vector();
extern Object change_connection_attribute();
extern Object change_connection_attribute_1();
extern Object check_if_superior_classes_are_defined();
extern Object chestnut_modf_function();
extern Object cleanup_for_connection_post();
extern Object clear_connection_item_table_skip_list();
extern Object clear_connections_found_in_search();
extern Object clear_optimized_constants();
extern Object collect_subclasses();
extern Object compute_connection_vertices();
extern Object compute_scaled_line_pattern();
extern Object connection_arrows_of_connection();
extern Object connection_class_of_connection();
extern Object connection_cons_1();
extern Object connection_cons_memory_usage();
extern Object connection_frame_of_connection_qm();
extern Object connection_item_name_or_names();
extern Object connection_item_structure_memory_usage();
extern Object connection_line_pattern();
extern Object connection_line_pattern_absolute_p();
extern Object connection_line_pattern_dashes();
extern Object connection_line_pattern_explicit_p();
extern Object connection_list_2();
extern Object connection_list_3();
extern Object connection_list_4();
extern Object connection_list_trace_hook();
extern Object connection_p_function();
extern Object connection_post_equal();
extern Object connection_spot_structure_memory_usage();
extern Object connection_striped_p();
extern Object connection_structure_memory_usage();
extern Object connection_structures();
extern Object connection_within_module_p();
extern Object copy_list_using_connection_conses_1();
extern Object copy_list_using_scope_conses();
extern Object copy_list_using_slot_value_conses_1();
extern Object copy_tree_using_connection_conses_1();
extern Object deactivate_for_connection();
extern Object decache_roles_for_connection_post_and_namesakes();
extern Object decache_roles_for_entities_related_to_this_connection();
extern Object delete_connection_cons_1();
extern Object delete_connection_element_1();
extern Object direct_structure_method();
extern Object downgrade_connections();
extern Object enlarge_workspace_for_connection();
extern Object enlarge_workspace_if_necessary();
extern Object find_closest_connection_vertex();
extern Object frame_serial_number_for_connection_function();
extern Object generate_spot_for_connection();
extern Object generate_spot_for_loose_end();
extern Object generic_directly_connected_p();
extern Object gensym_cons_1();
extern Object get_connection_color();
extern Object get_cross_section_regions_function();
extern Object get_direction_of_connection();
extern Object get_lookup_slot_value_given_default();
extern Object get_module_block_is_in();
extern Object get_module_connection_is_in();
extern Object get_slot_description_of_class_description_function();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object instantiated_connection_class_p();
extern Object inverse_scalef_function();
extern Object invoke_rules_for_direct_connection_chaining();
extern Object invoke_rules_for_indirect_connection_chaining();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lookup_stock_line_pattern_element();
extern Object loose_end_p_function();
extern Object loose_end_spot_structure_memory_usage();
extern Object make_connection_1();
extern Object make_connection_item_1();
extern Object make_connection_item_table_skip_list_sentinel();
extern Object make_connection_list_1();
extern Object make_connection_spot_1();
extern Object make_loose_end_spot_1();
extern Object make_permanent_connection_item_structure_internal();
extern Object make_permanent_connection_spot_structure_internal();
extern Object make_permanent_connection_structure_internal();
extern Object make_permanent_loose_end_spot_structure_internal();
extern Object make_skip_list_element_1();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_thread_array();
extern Object move_connection_vertex_by();
extern Object move_diagonal_connection_vertex_by();
extern Object move_if_loose_end();
extern Object move_item_by();
extern Object move_orthogonal_connection_vertex_by();
extern Object mutate_global_property();
extern Object name_or_names_like_p();
extern Object note_change_of_connection_for_drawing();
extern Object note_change_to_connection_1();
extern Object note_change_to_connection_2();
extern Object note_deletion_of_connection();
extern Object note_deletion_of_connection_2();
extern Object note_deletion_of_connection_for_drawing();
extern Object note_name_change_for_connection_post();
extern Object output_connection_p_function();
extern Object outstanding_connection_conses();
extern Object outstanding_connection_count();
extern Object outstanding_connection_item_count();
extern Object outstanding_connection_spot_count();
extern Object outstanding_loose_end_spot_count();
extern Object push_connection_vertex_spot_if_close();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object push_selection_handle_spot();
extern Object put_attribute_value();
extern Object put_control_block_input_1_where_slot_is_absent();
extern Object put_control_block_input_2_where_slot_is_absent();
extern Object put_control_block_input_where_slot_is_absent();
extern Object put_control_block_output_where_slot_is_absent();
extern Object reclaim_connection_1();
extern Object reclaim_connection_cons_1();
extern Object reclaim_connection_item_1();
extern Object reclaim_connection_item_table_nodes();
extern Object reclaim_connection_list_1();
extern Object reclaim_connection_list_star_1();
extern Object reclaim_connection_spot_1();
extern Object reclaim_connection_tree_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_loose_end_spot_1();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_structure_if_any();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_subworkspace_connection_post_from_connection();
extern Object render_connection_in_xor_overlay_p_function();
extern Object replenish_connection_cons_pool();
extern Object replenish_connection_list_pool();
extern Object replenish_lookup_cons_pool();
extern Object scalef_function();
extern Object scope_cons();
extern Object selection_handles_visible_p();
extern Object send_ws_representations_item_remove_as_subblock();
extern Object set_skip_list_entry();
extern Object slot_value_cons_1();
extern Object structure_type_p();
extern Object subclasses();
extern Object type_of_named_structure();
extern Object update_connection_images();
extern Object update_extreme_edges_from_connection();
extern Object update_object_pool_meters_list();
extern Object upgrade_block_connections();
extern Object upgrade_connections();
extern Object workspace_of_connection_frame();
extern Object workspace_of_connection_qm();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Available_connection_conses, Qavailable_connection_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_connection_conses_tail, Qavailable_connection_conses_tail);
extern Object Available_connection_conses_tail_vector;
extern Object Available_connection_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_connection_items, Qchain_of_available_connection_items);
extern Object Chain_of_available_connection_items_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_connection_spots, Qchain_of_available_connection_spots);
extern Object Chain_of_available_connection_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_connections, Qchain_of_available_connections);
extern Object Chain_of_available_connections_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_loose_end_spots, Qchain_of_available_loose_end_spots);
extern Object Chain_of_available_loose_end_spots_vector;
extern Object Class_description_gkbprop;
extern Object Connection_being_deleted_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_cons_counter, Qconnection_cons_counter);
extern Object Connection_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_count, Qconnection_count);
extern Object Connection_existed_at_start_of_save_flag;
extern Object Connection_found_in_search_flag;
extern Object Connection_has_been_written_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_item_count, Qconnection_item_count);
extern Object Connection_needs_indexing_flag;
extern Object Connection_not_directed_internal_flag;
extern Object Connection_overlap_cache_flag;
extern Object Connection_overlap_cache_valid_flag;
extern Object Connection_permanently_changed_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_post_class_description, Qconnection_post_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_spot_count, Qconnection_spot_count);
extern Object Connection_vertex_hit_distance;
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_default_line_color, Qcurrent_default_line_color);
DECLARE_VARIABLE_WITH_SYMBOL(Current_draw_document_p, Qcurrent_draw_document_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Default_junction_class_description, Qdefault_junction_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Dont_include_offset_for_end_position_qm, Qdont_include_offset_for_end_position_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_bottom_edge_so_far, Qextreme_bottom_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_left_edge_so_far, Qextreme_left_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_right_edge_so_far, Qextreme_right_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_top_edge_so_far, Qextreme_top_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_v5_mode_windows_p, Qg2_has_v5_mode_windows_p);
DECLARE_VARIABLE_WITH_SYMBOL(Geometric_change_to_connection_is_temporary_p, Qgeometric_change_to_connection_is_temporary_p);
DECLARE_VARIABLE_WITH_SYMBOL(In_suspend_resume_p, Qin_suspend_resume_p);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Invisible_entity_class_description, Qinvisible_entity_class_description);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_class_description, Qloose_end_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_spot_count, Qloose_end_spot_count);
extern Object Maximum_x_or_y_separation_allowing_fixnum_vector_distance_calculation;
extern Object Minus_of_isqrt_of_most_positive_fixnum;
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Object_class_description, Qobject_class_description);
extern Object Savable_connection_flags;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
extern Object The_type_description_of_connection;
extern Object The_type_description_of_connection_item;
extern Object The_type_description_of_connection_spot;
extern Object The_type_description_of_loose_end_spot;
extern Object Transient_connection_flag;
