/* cycles.h -- Header File for cycles.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kabort;
extern Object Qblock;
extern Object Qeval;
extern Object Qfirst;
extern Object Qmember;
extern Object Qquote;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object accept_data_and_reschedule_if_necessary(Object);
extern Object add_grammar_rules_function(Object);
extern Object adjust_counters_for_evaluation(Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object assemble_uncached_compound_method_flags(Object,Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object call_data_server_accept_data_functions(void);
extern Object cancel_all_field_edits_in_session(void);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_data_server_accept_data_calls(void);
extern Object change_slot_value(int,...);
extern Object chestnut_modf_function(Object,Object);
extern Object clear_g2_schedule(void);
extern Object clear_inform_messages(void);
extern Object clear_optimized_constants(void);
extern Object clear_procedure_invocations_1(void);
extern Object collect_subclasses(Object);
extern Object complete_save_after_running_if_necessary(void);
extern Object constant_queue_push_right(Object,Object);
extern Object continue_data_server_data_acceptance(Object,Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_out_current_wide_string(void);
extern Object data_server_requests_accept_data_calls(Object);
extern Object decode_universal_date(Object);
extern Object defer_current_g2_running_tasks(void);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object deinstall_system_table_for_timing_parameters(Object);
extern Object delete_connection_leaving_stubs_if_appropriate(Object);
extern Object delete_frame(Object);
extern Object delete_item(Object);
extern Object dequeue_and_execute_next_task(void);
extern Object disable_and_clear_system_profiling(void);
extern Object do_legacy_multisecond_heartbeat_adjustments(void);
extern Object do_legacy_subsecond_heartbeat_adjustments(void);
extern Object finish_all_table_updates(void);
extern Object fixnum_time_interval(Object);
extern Object frame_status_and_notes_reflects_flags_of_frame_p(Object);
extern Object future_task_schedule_2(Object);
extern Object g2_generate_new_random_seed(void);
extern Object g2_get_random_seed(void);
extern Object g2_repeat_random_function(void);
extern Object g2_set_random_seed(Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_decoded_real_time(void);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_superblock_of_connection_frame(Object);
extern Object get_symbol_properties_function(Object);
extern Object get_universal_date(void);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object handle_collected_updates_to_sensor_attributes(void);
extern Object initialize_interval_for_telewindows_modernization(void);
extern Object initialize_items_needing_initialization(void);
extern Object install_system_table_for_timing_parameters(Object);
extern Object intern_text_string(int,...);
extern Object invoke_interlace_abstraction_if_offered(void);
extern Object kill_all_instances_of_all_g2gl_processes(void);
extern Object licence_on_this_machine_expires_today_ok_message(void);
extern Object license_on_this_machine_has_expired_ok_message(void);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_all_indexed_attribute_hash_tables(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_timestamp_list_1(Object);
extern Object match_machine_id_for_this_machine_online(Object,Object);
extern Object minimum_scheduling_interval_function(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object notify_data_server_of_start_or_reset(Object);
extern Object notify_http_servers_of_g2_reset(void);
extern Object notify_sockets_of_g2_reset(void);
extern Object optimize_telewindows_z_layer_model(void);
extern Object post_prominent_notification(int,...);
extern Object preset_gensym_time_for_initialization(void);
extern Object print_decoded_date(Object,Object,Object);
extern Object print_list_without_message(Object);
extern Object push_optimized_constant(Object);
extern Object put_scheduler_mode(Object,Object,Object);
extern Object raw_stack_error_named_error(Object,Object);
extern Object reclaim_all_indexed_attribute_hash_tables(void);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_timestamp_list_1(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_transient_relation_instances(Object,Object);
extern Object repeat_random_function_on_reset_qm_function(Object);
extern Object requeue_deferred_running_tasks(void);
extern Object reset_all_scheduler_lag_time_variables(void);
extern Object reset_debugging_parameters(void);
extern Object reset_g2_random_state(Object);
extern Object resynchronize_gensym_time_and_actual_time(void);
extern Object run_one_scheduler_cycle(void);
extern Object run_state_change_hook(Object);
extern Object schedule_data_server_accept_data_calls(void);
extern Object schedule_g2_legacy_heartbeat_tasks_if_necessary(void);
extern Object schedule_immediate_data_server_accept_data_calls(void);
extern Object schedule_task_to_accept_data(Object);
extern Object schedule_tasks_for_updating_g2_meters_last_gensym_times(void);
extern Object schedule_tw_modernization_tasks_if_necessary(void);
extern Object scheduler_enabled_p(void);
extern Object scheduler_mode_function(Object);
extern Object scope_cons(Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object start_adaptive_font_fallback(void);
extern Object superior_frame(Object);
extern Object system_pause(int,...);
extern Object system_reset(void);
extern Object system_restart(void);
extern Object system_resume(void);
extern Object system_start(void);
extern Object system_table_installed_p(Object);
extern Object take_actions_at_start_of_clock_tick(Object);
extern Object tasks_enqueued_for_current_execution_qm(void);
extern Object terminate_kb_save_or_backup_if_error_occurs(void);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tick_the_clock(Object);
extern Object tick_the_g2_fast_time_clock(Object);
extern Object tick_the_g2_real_time_clock(Object);
extern Object tick_the_g2_simulated_time_clock(Object);
extern Object tick_the_nupec_catch_up_clock(Object);
extern Object tick_the_real_time_clock(Object);
extern Object timestamp_cons_1(Object,Object);
extern Object twrite(Object);
extern Object twrite_general_string(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object undo_kb_state_changes(void);
extern Object unpack_future_tasks_into_current_task_queues(Object);
extern Object update_g2_run_state(void);
extern Object update_g2_time_to_tick_after_scheduling_change(void);
extern Object update_memory_limits(Object);
extern Object update_meter_values(Object);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_representations_of_slot_value(int,...);
extern Object update_scheduler_time_lag(Object,Object);
extern Object warn_upon_start_or_resume(void);
extern Object write_interface_mode_from_slot(Object,Object);
extern Object write_timing_scheduler_mode_from_slot(Object,Object);

#else

extern Object accept_data_and_reschedule_if_necessary();
extern Object add_grammar_rules_function();
extern Object adjust_counters_for_evaluation();
extern Object allocate_byte_vector_16();
extern Object assemble_uncached_compound_method_flags();
extern Object assq_function();
extern Object c_native_clock_ticks_or_cache();
extern Object call_data_server_accept_data_functions();
extern Object cancel_all_field_edits_in_session();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_data_server_accept_data_calls();
extern Object change_slot_value();
extern Object chestnut_modf_function();
extern Object clear_g2_schedule();
extern Object clear_inform_messages();
extern Object clear_optimized_constants();
extern Object clear_procedure_invocations_1();
extern Object collect_subclasses();
extern Object complete_save_after_running_if_necessary();
extern Object constant_queue_push_right();
extern Object continue_data_server_data_acceptance();
extern Object copy_frame_serial_number();
extern Object copy_out_current_wide_string();
extern Object data_server_requests_accept_data_calls();
extern Object decode_universal_date();
extern Object defer_current_g2_running_tasks();
extern Object define_type_specification_explicit_complex_type();
extern Object deinstall_system_table_for_timing_parameters();
extern Object delete_connection_leaving_stubs_if_appropriate();
extern Object delete_frame();
extern Object delete_item();
extern Object dequeue_and_execute_next_task();
extern Object disable_and_clear_system_profiling();
extern Object do_legacy_multisecond_heartbeat_adjustments();
extern Object do_legacy_subsecond_heartbeat_adjustments();
extern Object finish_all_table_updates();
extern Object fixnum_time_interval();
extern Object frame_status_and_notes_reflects_flags_of_frame_p();
extern Object future_task_schedule_2();
extern Object g2_generate_new_random_seed();
extern Object g2_get_random_seed();
extern Object g2_repeat_random_function();
extern Object g2_set_random_seed();
extern Object gensym_cons_1();
extern Object get_decoded_real_time();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value_given_default();
extern Object get_superblock_of_connection_frame();
extern Object get_symbol_properties_function();
extern Object get_universal_date();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object handle_collected_updates_to_sensor_attributes();
extern Object initialize_interval_for_telewindows_modernization();
extern Object initialize_items_needing_initialization();
extern Object install_system_table_for_timing_parameters();
extern Object intern_text_string();
extern Object invoke_interlace_abstraction_if_offered();
extern Object kill_all_instances_of_all_g2gl_processes();
extern Object licence_on_this_machine_expires_today_ok_message();
extern Object license_on_this_machine_has_expired_ok_message();
extern Object lookup_kb_specific_property_value();
extern Object make_all_indexed_attribute_hash_tables();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_timestamp_list_1();
extern Object match_machine_id_for_this_machine_online();
extern Object minimum_scheduling_interval_function();
extern Object mutate_global_property();
extern Object note_change_to_block_1();
extern Object notify_data_server_of_start_or_reset();
extern Object notify_http_servers_of_g2_reset();
extern Object notify_sockets_of_g2_reset();
extern Object optimize_telewindows_z_layer_model();
extern Object post_prominent_notification();
extern Object preset_gensym_time_for_initialization();
extern Object print_decoded_date();
extern Object print_list_without_message();
extern Object push_optimized_constant();
extern Object put_scheduler_mode();
extern Object raw_stack_error_named_error();
extern Object reclaim_all_indexed_attribute_hash_tables();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_timestamp_list_1();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_transient_relation_instances();
extern Object repeat_random_function_on_reset_qm_function();
extern Object requeue_deferred_running_tasks();
extern Object reset_all_scheduler_lag_time_variables();
extern Object reset_debugging_parameters();
extern Object reset_g2_random_state();
extern Object resynchronize_gensym_time_and_actual_time();
extern Object run_one_scheduler_cycle();
extern Object run_state_change_hook();
extern Object schedule_data_server_accept_data_calls();
extern Object schedule_g2_legacy_heartbeat_tasks_if_necessary();
extern Object schedule_immediate_data_server_accept_data_calls();
extern Object schedule_task_to_accept_data();
extern Object schedule_tasks_for_updating_g2_meters_last_gensym_times();
extern Object schedule_tw_modernization_tasks_if_necessary();
extern Object scheduler_enabled_p();
extern Object scheduler_mode_function();
extern Object scope_cons();
extern Object set_evaluation_value_to_category_function();
extern Object set_property_value_function();
extern Object set_slot_value_to_evaluation_value_function();
extern Object start_adaptive_font_fallback();
extern Object superior_frame();
extern Object system_pause();
extern Object system_reset();
extern Object system_restart();
extern Object system_resume();
extern Object system_start();
extern Object system_table_installed_p();
extern Object take_actions_at_start_of_clock_tick();
extern Object tasks_enqueued_for_current_execution_qm();
extern Object terminate_kb_save_or_backup_if_error_occurs();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tick_the_clock();
extern Object tick_the_g2_fast_time_clock();
extern Object tick_the_g2_real_time_clock();
extern Object tick_the_g2_simulated_time_clock();
extern Object tick_the_nupec_catch_up_clock();
extern Object tick_the_real_time_clock();
extern Object timestamp_cons_1();
extern Object twrite();
extern Object twrite_general_string();
extern Object type_error_in_setter();
extern Object type_specification_type_p__with_explanation();
extern Object undo_kb_state_changes();
extern Object unpack_future_tasks_into_current_task_queues();
extern Object update_g2_run_state();
extern Object update_g2_time_to_tick_after_scheduling_change();
extern Object update_memory_limits();
extern Object update_meter_values();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_representations_of_slot_value();
extern Object update_scheduler_time_lag();
extern Object warn_upon_start_or_resume();
extern Object write_interface_mode_from_slot();
extern Object write_timing_scheduler_mode_from_slot();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Cache_nupec_semantics_graph, Qcache_nupec_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
extern Object Chain_of_available_schedule_tasks_vector;
extern Object Class_instance_delta_masks;
DECLARE_VARIABLE_WITH_SYMBOL(Collected_updates_to_sensor_attributes, Qcollected_updates_to_sensor_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_updates_to_sensor_attributes_p, Qcollecting_updates_to_sensor_attributes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Control_sequence_record, Qcontrol_sequence_record);
DECLARE_VARIABLE_WITH_SYMBOL(Countdown_for_checking, Qcountdown_for_checking);
extern Object Counter_for_sleep_management_adjustment;
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
extern Object Current_inner_procedure_loop_cache_index;
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Daily_countdown, Qdaily_countdown);
extern Object Data_server_accept_data_task;
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_parameters, Qdata_server_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_reset, Qdebugging_reset);
DECLARE_VARIABLE_WITH_SYMBOL(Default_format_structure, Qdefault_format_structure);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Delete_connections_without_leaving_stubs_qm, Qdelete_connections_without_leaving_stubs_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Embedded_fuzzy_conditionals_list, Qembedded_fuzzy_conditionals_list);
extern Object End_of_recovery_list;
extern Object Engage_context_pipelining_p;
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fixnum_time_of_last_g2_tick, Qfixnum_time_of_last_g2_tick);
extern Object Fixnum_time_units_per_second;
DECLARE_VARIABLE_WITH_SYMBOL(Fixnum_time_until_g2_time_tick, Qfixnum_time_until_g2_time_tick);
#define Fixnum_time_until_real_time_tick FIX((SI_Long)1L)
DECLARE_VARIABLE_WITH_SYMBOL(Force_clock_tick, Qforce_clock_tick);
extern Object Format_redefinition_list;
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_been_started_qm, Qg2_has_been_started_qm);
DECLARE_VARIABLE_WITH_SYMBOL(G2_meter_task_count, Qg2_meter_task_count);
#define G2_meter_task_limit FIX((SI_Long)100L)
extern Object G2_meters_scheduler_time_lag_variable_names_format;
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_to_tick_p_base, Qg2_time_to_tick_p_base);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_base_time_as_managed_float, Qgensym_base_time_as_managed_float);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_at_start, Qgensym_time_at_start);
extern Object Global_daylight_saving_time_adjustment;
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_attributes_pane, Qglobal_table_of_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_hidden_attributes_pane, Qglobal_table_of_hidden_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Hour_of_last_message, Qhour_of_last_message);
DECLARE_VARIABLE_WITH_SYMBOL(Hourly_countdown, Qhourly_countdown);
extern Object Icp_socket_processing_time_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_non_real_time_clock_ticks_qm, Qinhibit_non_real_time_clock_ticks_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_updating_module_related_frame_notes_for_all_workspaces_qm, Qinhibit_updating_module_related_frame_notes_for_all_workspaces_qm);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Interval_for_telewindows_modernization, Qinterval_for_telewindows_modernization);
DECLARE_VARIABLE_WITH_SYMBOL(Items_needing_initialization, Qitems_needing_initialization);
DECLARE_VARIABLE_WITH_SYMBOL(Journal_shutout_scan_p, Qjournal_shutout_scan_p);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
extern Object Legacy_multisecond_heartbeat_adjustment_interval;
extern Object Legacy_multisecond_heartbeat_adjustment_priority;
DECLARE_VARIABLE_WITH_SYMBOL(Legacy_subsecond_heartbeat_adjustment_interval, Qlegacy_subsecond_heartbeat_adjustment_interval);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_all_data_servers, Qlist_of_all_data_servers);
extern Object Local_recovery_list;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
DECLARE_VARIABLE_WITH_SYMBOL(Meter_lag_time_variables, Qmeter_lag_time_variables);
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
extern Object Modulus_counter_for_evaluation;
extern Object Most_negative_fixnum_as_float;
extern Object Most_positive_fixnum_as_float;
DECLARE_VARIABLE_WITH_SYMBOL(Most_recent_g2_time, Qmost_recent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Multiplicative_counter_for_evaluation, Qmultiplicative_counter_for_evaluation);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Nupec_catch_up_mode_caught_up_qm, Qnupec_catch_up_mode_caught_up_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Place_for_for_telewindows_modernization, Qplace_for_for_telewindows_modernization);
DECLARE_VARIABLE_WITH_SYMBOL(Previous_modulus_counter_for_evaluation, Qprevious_modulus_counter_for_evaluation);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_10_last_gensym_time, Qpriority_10_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_1_last_gensym_time, Qpriority_1_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_2_last_gensym_time, Qpriority_2_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_3_last_gensym_time, Qpriority_3_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_4_last_gensym_time, Qpriority_4_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_5_last_gensym_time, Qpriority_5_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_6_last_gensym_time, Qpriority_6_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_7_last_gensym_time, Qpriority_7_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_8_last_gensym_time, Qpriority_8_last_gensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_9_last_gensym_time, Qpriority_9_last_gensym_time);
extern Object Priority_for_telewindows_modernization;
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
extern Object Procedure_invocations_lock;
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Random_variation, Qrandom_variation);
DECLARE_VARIABLE_WITH_SYMBOL(Real_time_of_last_g2_tick, Qreal_time_of_last_g2_tick);
DECLARE_VARIABLE_WITH_SYMBOL(Real_time_to_tick_p_base, Qreal_time_to_tick_p_base);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
extern Object Recursive_attribute_nesting_has_occurred_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Reference_date_for_interval_encoding, Qreference_date_for_interval_encoding);
DECLARE_VARIABLE_WITH_SYMBOL(Safe_to_access_attribute_display_update_interval_p, Qsafe_to_access_attribute_display_update_interval_p);
extern Object Scheduled_tasks_time_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Seconds_from_1900_to_1970;
DECLARE_VARIABLE_WITH_SYMBOL(Separate_imminent_actions_p, Qseparate_imminent_actions_p);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_aborted, Qsystem_has_aborted);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(System_window, Qsystem_window);
DECLARE_VARIABLE_WITH_SYMBOL(Time_slice_start_time, Qtime_slice_start_time);
DECLARE_VARIABLE_WITH_SYMBOL(Timing_parameters, Qtiming_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Unevaluated_expression, Qunevaluated_expression);
DECLARE_VARIABLE_WITH_SYMBOL(User_random_seed_qm, Quser_random_seed_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_qm, Qwarmbooting_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_with_catch_up_qm, Qwarmbooting_with_catch_up_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Window_instigating_this_rule_instance_qm, Qwindow_instigating_this_rule_instance_qm);
extern Object Within_side_limits;
