/* edit2.h -- Header File for edit2.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kabort;
extern Object Qdelete;
extern Object Qsymbol;
extern Object Qtype;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object accept_kfep_conversion(void);
extern Object add_class_to_environment(int,...);
extern Object add_keymap_to_workstation_context(Object,Object);
extern Object add_to_workspace(int,...);
extern Object add_token_to_parsing_context(Object,Object);
extern Object advance_parsing_context(Object,Object);
extern Object advance_parsing_context_index(Object,Object);
extern Object advance_parsing_context_token_stream(void);
extern Object advance_parsing_for_token(Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_array(int,...);
extern Object assq_function(Object,Object);
extern Object blank_p(Object);
extern Object block_showing_representation_blackboard_function(Object);
extern Object bytes_per_simple_vector(Object);
extern Object calculate_rightmost_start_position_for_bounded_reverse_search(Object,Object,Object,Object);
extern Object cancel_editing(void);
extern Object cell_of_table_blackboard_function(Object);
extern Object change_color_of_text_cell(int,...);
extern Object change_color_of_text_region(Object,Object);
extern Object change_edit_box(int,...);
extern Object change_edit_box_cursor_position(int,...);
extern Object change_slot_description_value_function(Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object change_text_cell_property(Object,Object,Object);
extern Object change_the_text_of(int,...);
extern Object check_cyrillic_code_entry_text(int,...);
extern Object check_hangul_code_entry_text(int,...);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object check_insertion_of_symbol_entry_text(int,...);
extern Object check_kanji_code_entry_text(int,...);
extern Object check_special_character_entry_text(int,...);
extern Object chestnut_modf_function(Object,Object);
extern Object choose_font_format_per_font_size(Object,Object);
extern Object choose_token_menu_item_format_per_system_tables(int,...);
extern Object clear_optimized_constants(void);
extern Object clear_parsing_context(Object);
extern Object clear_parsing_tokens(Object);
extern Object coerce_scrap_to_text_string(int,...);
extern Object coerce_text_region_to_scrap(Object);
extern Object comment_token_p(Object);
extern Object common_text_string_length(Object,Object);
extern Object compile_for_current_edit_state(Object,Object,Object);
extern Object complete_and_extend_final_token_if_necessary(Object);
extern Object compute_distance_of_text_line_from_top(Object,Object);
extern Object compute_height_for_text(Object,Object,Object);
extern Object compute_minimum_left_edge_of_character_in_line_of_text(Object,Object,Object,Object);
extern Object compute_parsing_context_prompts(Object);
extern Object compute_prompts_for_incomplete_token(Object);
extern Object constant_queue_delete(int,...);
extern Object constant_queue_next(Object,Object);
extern Object convert_text_region_to_text_string(int,...);
extern Object convert_text_string_to_text(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_and_translate_subcommand_choice_symbol_list(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_for_phrase(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_author_or_authors(Object,Object);
extern Object copy_list_using_grammar_conses_1(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_symbol_name(int,...);
extern Object copy_text_region_to_cut_buffer_if_appropriate(Object);
extern Object copy_text_string(Object);
extern Object copy_text_string_to_cut_buffer(Object,Object);
extern Object copy_text_string_with_case_conversion(Object,Object);
extern Object create_parsing_context(int,...);
extern Object current_natural_language_for_editor(void);
extern Object decode_frame_author_or_authors(Object,Object);
extern Object decode_frame_author_or_authors_1(Object);
extern Object decode_window_position(Object,Object,Object);
extern Object delete_any_text_regions(int,...);
extern Object delete_excess_scraps_if_any(Object);
extern Object delete_frame(Object);
extern Object delete_image_plane(Object);
extern Object delete_kfep_conversion_text_region_if_any(int,...);
extern Object delete_parsing_context(Object);
extern Object delete_subblocks_of_class(Object,Object);
extern Object denote_slot_using_slot_value_conses(Object,Object);
extern Object detail_pane(Object);
extern Object determine_corrected_text_position_if_necessary(int,...);
extern Object determine_final_token(Object);
extern Object digit_char_pw_function(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object disable_text_region_operation_subcommands_in_current_editor(void);
extern Object display_editor_notification_1(Object);
extern Object do_copy_within_editor(void);
extern Object do_cut_and_insert_within_editor(void);
extern Object do_cut_within_editor(int,...);
extern Object do_delete_within_editor(void);
extern Object do_edit_subcommand(Object);
extern Object do_insert_within_editor(void);
extern Object do_kfep_conversion_edit(Object);
extern Object do_kfep_conversion_edit_from_outside(Object);
extern Object do_move_within_editor(void);
extern Object do_paste_within_editor(void);
extern Object do_pathname_component_conversion_if_necessary(Object,Object);
extern Object do_trial_kfep_conversion(int,...);
extern Object draw_text_segment_in_text_box(Object,Object,Object,Object);
extern Object editor_has_non_empty_text_region_p(void);
extern Object editor_subcommand_name_function(Object);
extern Object embedded_rule_p(Object);
extern Object empty_text_region_p(Object);
extern Object enable_or_disable_edit_end_and_update_buttons(Object);
extern Object enable_or_disable_editor_subcommand_button(Object,Object);
extern Object enable_or_disable_radio_button_subcommand(Object,Object,Object);
extern Object enable_or_disable_subcommand(int,...);
extern Object encode_unix_time_after_failure(Object,Object,Object,Object,Object,Object);
extern Object end_editorless_parsing(Object,Object,Object);
extern Object enlarge_workspace_for_block_rectangle_if_necessary(Object,Object);
extern Object enqueue_workstation_event(int,...);
extern Object enter_context_in_current_workstation(int,...);
extern Object enter_cyrillic_input_mode(void);
extern Object enter_editing_context(int,...);
extern Object enter_editing_context_on_text_box(int,...);
extern Object enter_escape_context(int,...);
extern Object enter_hangul_input_mode(void);
extern Object enter_kana_conversion_mode(Object);
extern Object enter_subcommand_context(Object);
extern Object equalw(Object,Object);
extern Object erase_any_kfep_conversion_choices(void);
extern Object erase_any_temporary_information_on_edit_workspace(int,...);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_structure_for_frame_edit_timestamp(Object);
extern Object exit_cyrillic_input_mode(void);
extern Object exit_hangul_input_mode(void);
extern Object exit_kfep_mode_if_necessary(int,...);
extern Object expand_or_shrink_kfep_conversion_text_region(Object);
extern Object extend_current_gensym_string(int,...);
extern Object extend_current_wide_string(Object);
extern Object extend_parsing_as_appropriate(int,...);
extern Object extend_parsing_context(int,...);
extern Object extract_parse_result(Object);
extern Object find_image_plane_for_workspace_in_pane(Object,Object);
extern Object find_line_index_for_text_tail(Object,Object,Object);
extern Object find_next_character_if_any(Object,Object,Object);
extern Object find_next_instance_of_search_string(int,...);
extern Object find_position_adjacent_to_end_of_kfep_conversion_text_region(Object);
extern Object find_position_in_text(int,...);
extern Object find_position_in_text_given_image_plane(int,...);
extern Object find_previous_character_if_any(Object,Object,Object,Object);
extern Object find_search_string_in_superior_editor(int,...);
extern Object find_string_in_text(int,...);
extern Object find_string_in_text_prior_to_bounds(int,...);
extern Object find_text_tail_for_line(Object,Object);
extern Object find_word_boundary_in_text(Object,Object,Object,Object,Object);
extern Object finish_parsing_insofar_as_possible(void);
extern Object first_subblock(Object);
extern Object first_text_region_in_edit_state(Object);
extern Object fixup_author_or_authors_value(Object);
extern Object fixup_frame_author_or_authors_tail(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object g2_copy_text_to_clipboard(Object,Object);
extern Object generate_reason_for_parsing_failure(Object);
extern Object generate_spot_for_button_menu(Object,Object,Object);
extern Object generate_spot_for_scrap(Object,Object);
extern Object generate_spot_for_subcommand_menu(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_decode_unix_time(Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object get_cfep_edit_subcomand_choices_if_appropriate(void);
extern Object get_current_frame_edit_timestamp(void);
extern Object get_current_user_name(void);
extern Object get_current_user_name_if_any_case_insensitive(void);
extern Object get_default_image_x_scale(Object);
extern Object get_default_image_y_scale(Object);
extern Object get_edit_subcommand_menu_core_choices(void);
extern Object get_gensym_window_parameter(Object,Object);
extern Object get_hfep_edit_subcomand_choices_if_appropriate(void);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_kfep_conversion_choice_index_delta_for_arrow(Object);
extern Object get_kfep_edit_subcomand_choices_if_appropriate(void);
extern Object get_language_for_current_workstation_if_any(void);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_natural_language_for_editor(Object);
extern Object get_next_text_line(Object);
extern Object get_next_token_from_text_if_available(int,...);
extern Object get_or_make_category_for_category_symbol(Object);
extern Object get_or_make_menu_content_structure_for_parsing_token(Object);
extern Object get_overall_minimum_width_for_subcommand_menu_column(Object);
extern Object get_reference_to_item(Object);
extern Object get_scrap_if_any(void);
extern Object get_selected_text_region_for_edit_box(void);
extern Object get_slot_component_features(Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_compiler_for_current_edit_state_if_any(void);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_table_cell_indices(Object,Object);
extern Object get_text_region_position(int,...);
extern Object get_unicode_set_width_as_text_width(Object,Object);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object grammar_cons_1(Object,Object);
extern Object handle_parsing_or_compilation_problem(int,...);
extern Object handle_paste_availability_event_in_g2(Object,Object,Object);
extern Object handle_paste_event_in_g2(Object,Object,Object,Object);
extern Object handle_spaces_intelligently_p(Object);
extern Object highlight_or_unhighlight_cell(int,...);
extern Object highlight_or_unhighlight_kfep_conversion_choice(Object,Object);
extern Object image_plane_blackboard_function(Object);
extern Object incomplete_phrases_for_previous_token(void);
extern Object incomplete_token_can_be_construed_as_complete(Object);
extern Object indicate_editor_subcommand_button_pending_state(Object,Object,Object);
extern Object indicate_subcommand_pending_state(int,...);
extern Object indicate_subcommand_pending_state_for_block_cell(Object,Object,Object,Object,Object,Object);
extern Object indicate_subcommand_pending_state_for_text_cell(Object,Object,Object,Object,Object,Object);
extern Object initialize_edit_subcommand_menu(Object);
extern Object initialize_kana_to_kanji_converters(void);
extern Object initialize_parser_state_for_current_parsing_context(Object);
extern Object initialize_parser_state_for_free_text(void);
extern Object innermost_spot_blackboard_function(Object);
extern Object insert_character_at_cursor_from_outside(int,...);
extern Object insert_text_string_at_cursor(int,...);
extern Object insert_text_string_in_text_being_edited(int,...);
extern Object install_current_edit_state_compiled_result(Object,Object,Object);
extern Object intern_text_string(int,...);
extern Object intern_wide_string(int,...);
extern Object inverse_magnify(Object,Object);
extern Object inverse_scalef_function(Object,Object);
extern Object iso_8859_5_to_gensym_cyrillic(Object);
extern Object ksc_to_gensym_ksc(Object);
extern Object legal_gensym_jis_character_code_p(Object);
extern Object legal_gensym_ksc_character_code_p(Object);
extern Object length_of_text_in_region(Object);
extern Object lengthw(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_frame_description_reference_of_frame_style(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_category_instance_menus(Object,Object,Object);
extern Object make_context_description(Object,Object,Object,Object);
extern Object make_edit_box_change_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_edit_subcommand_menu(void);
extern Object make_editor_subcommand_button(int,...);
extern Object make_empty_text(void);
extern Object make_format_frame(Object);
extern Object make_frame(Object);
extern Object make_hfep_hanc_type_function(void);
extern Object make_icon_cell_for_entity(Object,Object,Object,Object,Object);
extern Object make_incomplete_phrase_structure_1(Object,Object,Object,Object);
extern Object make_keymap(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_kfep_conversion_choice_menu(Object);
extern Object make_kfep_conversion_text_region(Object,Object,Object);
extern Object make_menu_content_structure_for_character_position(Object,Object,Object);
extern Object make_menu_content_structure_for_token_position(Object,Object);
extern Object make_or_reformat_table(int,...);
extern Object make_parsing_context_1(void);
extern Object make_parsing_token_1(void);
extern Object make_permanent_parsing_context_structure_internal(void);
extern Object make_permanent_parsing_token_structure_internal(void);
extern Object make_permanent_subcommand_state_structure_internal(void);
extern Object make_permanent_text_inserter_spot_structure_internal(void);
extern Object make_phrase_rule_completion_1(Object,Object,Object);
extern Object make_subcommand_menu(int,...);
extern Object make_subcommand_menu_button_spot_1(void);
extern Object make_subcommand_state_1(Object,Object,Object);
extern Object make_text_cell(int,...);
extern Object make_text_inserter_spot_1(void);
extern Object make_text_region(int,...);
extern Object make_thread_array(Object);
extern Object make_workspace(int,...);
extern Object map_composed_character_to_base_character_for_editor(Object);
extern Object map_editor_special_character_type_in(Object,Object);
extern Object map_extended_utf_g_characters_to_unicode(Object,Object);
extern Object map_gensym_han_character_code_to_unicode(Object);
extern Object maybe_skip_comment_tokens(Object);
extern Object memq_function(Object,Object);
extern Object mouse_motion_in_subcommand_state(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object mouse_up_in_subcommand_state(Object);
extern Object move_edit_cursor(Object,Object,Object);
extern Object move_or_delete_from_cursor(int,...);
extern Object mutate_global_property(Object,Object,Object);
extern Object nest_draw_area_for_frame_1(Object);
extern Object new_get_available_image_plane(Object,Object,Object,Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_kb_state_change_to_slot_by_saving_text(Object,Object);
extern Object note_kfep_conversion_choice(Object,Object,Object);
extern Object obtain_paste_request_id_for_editor(Object);
extern Object ordinary_space_p(Object);
extern Object outstanding_parsing_context_count(void);
extern Object outstanding_parsing_token_count(void);
extern Object outstanding_subcommand_state_count(void);
extern Object outstanding_text_inserter_spot_count(void);
extern Object parse_text_for_slot(int,...);
extern Object parsing_context_cursor_token_function(Object);
extern Object parsing_context_p_function(Object);
extern Object parsing_context_structure_memory_usage(void);
extern Object parsing_token_incomplete_p(Object);
extern Object parsing_token_incomplete_phrases_function(Object);
extern Object parsing_token_structure_memory_usage(void);
extern Object paste_from_current_scrap_if_any(void);
extern Object paste_text_string(int,...);
extern Object pending_romaji_character_in_text_p(void);
extern Object phrase_cons(Object,Object);
extern Object pop_for_token(void);
extern Object print_decoded_time(Object,Object,Object,Object,Object,Object);
extern Object prune_edit_undo_stack(void);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_up_edit_workspace(int,...);
extern Object put_up_kfep_conversion_choices(Object);
extern Object reason_for_bad_parse_as_string(Object);
extern Object reclaim_chain_of_incomplete_phrases(Object);
extern Object reclaim_edit_box_change_1(Object);
extern Object reclaim_edit_undo_or_redo_stack(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_list_if_list(Object);
extern Object reclaim_gensym_tree_function(Object);
extern Object reclaim_grammar_tree_1(Object);
extern Object reclaim_hfep_hanc_type_function(Object);
extern Object reclaim_managed_floats_in_phrases(Object);
extern Object reclaim_managed_longs_in_phrases(Object);
extern Object reclaim_most_recent_reason_for_bad_parse_qm(Object);
extern Object reclaim_parsing_context(Object);
extern Object reclaim_parsing_context_1_1(Object);
extern Object reclaim_parsing_token_1(Object);
extern Object reclaim_parsing_token_and_accompanying_data(Object);
extern Object reclaim_pending_procedure_signature_workspaces(Object);
extern Object reclaim_phrase_rule_completions(Object);
extern Object reclaim_sexp_annotation_hash_qm(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_structure_if_any(Object);
extern Object reclaim_subcommand_function_arglist_qm_value(Object,Object);
extern Object reclaim_subcommand_state_1(Object);
extern Object reclaim_text_inserter_spot_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_text_strings_in_phrases(Object);
extern Object reclaim_vectors_for_phrase_conses(Object);
extern Object reclaim_wide_string(Object);
extern Object recompile_cell_array(Object);
extern Object recompile_item(Object);
extern Object recompile_item_1(Object);
extern Object recompile_slot_of_frame_1(int,...);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reformat_text(int,...);
extern Object reformat_text_box_in_place(int,...);
extern Object regenerate_optimized_constant(Object);
extern Object relative_index_of_first_non_whitespace_character(Object,Object);
extern Object release_mouse_pointers(Object);
extern Object remove_token_from_parsing_context(Object);
extern Object request_paste_availability_for_editor(void);
extern Object request_paste_availability_status(Object,Object);
extern Object request_paste_for_editor(void);
extern Object request_paste_of_cut_buffer_text(Object,Object);
extern Object retreat_parsing_context(Object,Object);
extern Object return_from_current_workstation_context(int,...);
extern Object reverse_text_region(Object);
extern Object scalef_function(Object,Object);
extern Object scrap_text(int,...);
extern Object scrap_text_region(int,...);
extern Object scroll_text_into_view(Object,Object,Object);
extern Object search_backward_incrementally_for_text_in_editor(int,...);
extern Object search_for_longest_prefix_with_kfep_word_choices(int,...);
extern Object search_forward_incrementally_for_text_in_editor(int,...);
extern Object search_incrementally_for_text_in_editor(Object,Object,Object);
extern Object select_text_region_in_scrap(Object,Object,Object);
extern Object set_up_kfep_conversion_text_region(int,...);
extern Object shift_block(Object,Object,Object);
extern Object shift_cursor_token(Object,Object);
extern Object shrink_wrap_workspace(Object);
extern Object skip_kfep_conversion(void);
extern Object slot_value_cons_1(Object,Object);
extern Object stop_blinker(Object,Object);
extern Object string_eq_w(Object,Object);
extern Object string_equalw(Object,Object);
extern Object string_upcasew(Object);
extern Object stripped_text_p(Object);
extern Object subcommand_enabled_p(Object,Object);
extern Object subcommand_state_structure_memory_usage(void);
extern Object symbol_name_text_string(Object);
extern Object text_being_edited_may_have_no_value_p(void);
extern Object text_break_p(Object);
extern Object text_can_be_copied_within_editor_p(void);
extern Object text_can_be_cut_within_editor_p(void);
extern Object text_can_be_deleted_within_editor_p(void);
extern Object text_can_be_pasted_in_current_workstation_p(void);
extern Object text_can_be_transferred_within_editor_p(void);
extern Object text_cell_of_table_blackboard_function(Object);
extern Object text_empty_p(Object);
extern Object text_inserter_spot_structure_memory_usage(void);
extern Object text_region_oriented_backward_p(Object);
extern Object text_region_oriented_forward_p(Object);
extern Object text_string_length(Object);
extern Object text_string_matches_current_scrap_p(Object);
extern Object text_string_p(Object);
extern Object text_string_substring(Object,Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object there_is_a_scrap_p(void);
extern Object transform_image(int,...);
extern Object translate_subcommand_menu_choice(Object,Object);
extern Object translate_subcommand_menu_choice_as_appropriate(Object,Object);
extern Object translation_for_symbol_qm(int,...);
extern Object twrite(Object);
extern Object twrite_frame_edit_timestamp(Object);
extern Object twrite_wide_character(Object);
extern Object type_of_slot_if_editable(int,...);
extern Object unambiguous_parsing_token_p(Object);
extern Object unconvert_kfep_conversion_text_region(void);
extern Object undo_or_redo_edit(Object);
extern Object undo_or_redo_edit_possible_p(Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object unicode_uppercase_if_lowercase(Object);
extern Object update_authors_and_time_of_frame_edit(Object,Object);
extern Object update_authors_attribute(Object,Object,Object,Object);
extern Object update_border_of_text_box(Object,Object,Object,Object,Object);
extern Object update_edit_operation_subcommands(Object);
extern Object update_edit_operation_subcommands_in_current_editor(void);
extern Object update_frame_status(Object,Object,Object);
extern Object update_images(int,...);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_kfep_buttons(void);
extern Object update_kfep_conversion_choices_as_appropriate(int,...);
extern Object update_object_pool_meters_list(Object);
extern Object update_parsing_context_completions_as_appropriate(int,...);
extern Object update_text_in_edit_box(Object,Object,Object,Object,Object,Object,Object);
extern Object update_text_region(int,...);
extern Object use_built_in_subcommand_menu_choice_translation(Object,Object);
extern Object use_return_key_as_end_key_in_current_editor_p(void);
extern Object wide_character_assoc(Object,Object);
extern Object wide_character_member(Object,Object);
extern Object wide_string_compare(Object,Object,Object,Object);
extern Object within_text_region_p(Object,Object,Object);
extern Object workstation_context_specifics_blackboard_function(Object);

#else

extern Object abort_current_workstation_context();
extern Object accept_kfep_conversion();
extern Object add_class_to_environment();
extern Object add_keymap_to_workstation_context();
extern Object add_to_workspace();
extern Object add_token_to_parsing_context();
extern Object advance_parsing_context();
extern Object advance_parsing_context_index();
extern Object advance_parsing_context_token_stream();
extern Object advance_parsing_for_token();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_array();
extern Object assq_function();
extern Object blank_p();
extern Object block_showing_representation_blackboard_function();
extern Object bytes_per_simple_vector();
extern Object calculate_rightmost_start_position_for_bounded_reverse_search();
extern Object cancel_editing();
extern Object cell_of_table_blackboard_function();
extern Object change_color_of_text_cell();
extern Object change_color_of_text_region();
extern Object change_edit_box();
extern Object change_edit_box_cursor_position();
extern Object change_slot_description_value_function();
extern Object change_slot_value();
extern Object change_text_cell_property();
extern Object change_the_text_of();
extern Object check_cyrillic_code_entry_text();
extern Object check_hangul_code_entry_text();
extern Object check_if_superior_classes_are_defined();
extern Object check_insertion_of_symbol_entry_text();
extern Object check_kanji_code_entry_text();
extern Object check_special_character_entry_text();
extern Object chestnut_modf_function();
extern Object choose_font_format_per_font_size();
extern Object choose_token_menu_item_format_per_system_tables();
extern Object clear_optimized_constants();
extern Object clear_parsing_context();
extern Object clear_parsing_tokens();
extern Object coerce_scrap_to_text_string();
extern Object coerce_text_region_to_scrap();
extern Object comment_token_p();
extern Object common_text_string_length();
extern Object compile_for_current_edit_state();
extern Object complete_and_extend_final_token_if_necessary();
extern Object compute_distance_of_text_line_from_top();
extern Object compute_height_for_text();
extern Object compute_minimum_left_edge_of_character_in_line_of_text();
extern Object compute_parsing_context_prompts();
extern Object compute_prompts_for_incomplete_token();
extern Object constant_queue_delete();
extern Object constant_queue_next();
extern Object convert_text_region_to_text_string();
extern Object convert_text_string_to_text();
extern Object convert_text_to_text_string();
extern Object copy_and_translate_subcommand_choice_symbol_list();
extern Object copy_constant_wide_string_given_length();
extern Object copy_for_phrase();
extern Object copy_for_slot_value();
extern Object copy_frame_author_or_authors();
extern Object copy_list_using_grammar_conses_1();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_out_current_wide_string();
extern Object copy_symbol_name();
extern Object copy_text_region_to_cut_buffer_if_appropriate();
extern Object copy_text_string();
extern Object copy_text_string_to_cut_buffer();
extern Object copy_text_string_with_case_conversion();
extern Object create_parsing_context();
extern Object current_natural_language_for_editor();
extern Object decode_frame_author_or_authors();
extern Object decode_frame_author_or_authors_1();
extern Object decode_window_position();
extern Object delete_any_text_regions();
extern Object delete_excess_scraps_if_any();
extern Object delete_frame();
extern Object delete_image_plane();
extern Object delete_kfep_conversion_text_region_if_any();
extern Object delete_parsing_context();
extern Object delete_subblocks_of_class();
extern Object denote_slot_using_slot_value_conses();
extern Object detail_pane();
extern Object determine_corrected_text_position_if_necessary();
extern Object determine_final_token();
extern Object digit_char_pw_function();
extern Object direct_structure_method();
extern Object disable_text_region_operation_subcommands_in_current_editor();
extern Object display_editor_notification_1();
extern Object do_copy_within_editor();
extern Object do_cut_and_insert_within_editor();
extern Object do_cut_within_editor();
extern Object do_delete_within_editor();
extern Object do_edit_subcommand();
extern Object do_insert_within_editor();
extern Object do_kfep_conversion_edit();
extern Object do_kfep_conversion_edit_from_outside();
extern Object do_move_within_editor();
extern Object do_paste_within_editor();
extern Object do_pathname_component_conversion_if_necessary();
extern Object do_trial_kfep_conversion();
extern Object draw_text_segment_in_text_box();
extern Object editor_has_non_empty_text_region_p();
extern Object editor_subcommand_name_function();
extern Object embedded_rule_p();
extern Object empty_text_region_p();
extern Object enable_or_disable_edit_end_and_update_buttons();
extern Object enable_or_disable_editor_subcommand_button();
extern Object enable_or_disable_radio_button_subcommand();
extern Object enable_or_disable_subcommand();
extern Object encode_unix_time_after_failure();
extern Object end_editorless_parsing();
extern Object enlarge_workspace_for_block_rectangle_if_necessary();
extern Object enqueue_workstation_event();
extern Object enter_context_in_current_workstation();
extern Object enter_cyrillic_input_mode();
extern Object enter_editing_context();
extern Object enter_editing_context_on_text_box();
extern Object enter_escape_context();
extern Object enter_hangul_input_mode();
extern Object enter_kana_conversion_mode();
extern Object enter_subcommand_context();
extern Object equalw();
extern Object erase_any_kfep_conversion_choices();
extern Object erase_any_temporary_information_on_edit_workspace();
extern Object eval_cons_1();
extern Object evaluation_structure_for_frame_edit_timestamp();
extern Object exit_cyrillic_input_mode();
extern Object exit_hangul_input_mode();
extern Object exit_kfep_mode_if_necessary();
extern Object expand_or_shrink_kfep_conversion_text_region();
extern Object extend_current_gensym_string();
extern Object extend_current_wide_string();
extern Object extend_parsing_as_appropriate();
extern Object extend_parsing_context();
extern Object extract_parse_result();
extern Object find_image_plane_for_workspace_in_pane();
extern Object find_line_index_for_text_tail();
extern Object find_next_character_if_any();
extern Object find_next_instance_of_search_string();
extern Object find_position_adjacent_to_end_of_kfep_conversion_text_region();
extern Object find_position_in_text();
extern Object find_position_in_text_given_image_plane();
extern Object find_previous_character_if_any();
extern Object find_search_string_in_superior_editor();
extern Object find_string_in_text();
extern Object find_string_in_text_prior_to_bounds();
extern Object find_text_tail_for_line();
extern Object find_word_boundary_in_text();
extern Object finish_parsing_insofar_as_possible();
extern Object first_subblock();
extern Object first_text_region_in_edit_state();
extern Object fixup_author_or_authors_value();
extern Object fixup_frame_author_or_authors_tail();
extern Object frame_serial_number_setf_helper_1();
extern Object g2_copy_text_to_clipboard();
extern Object generate_reason_for_parsing_failure();
extern Object generate_spot_for_button_menu();
extern Object generate_spot_for_scrap();
extern Object generate_spot_for_subcommand_menu();
extern Object gensym_cons_1();
extern Object gensym_decode_unix_time();
extern Object gensym_list_2();
extern Object gensym_list_4();
extern Object get_cfep_edit_subcomand_choices_if_appropriate();
extern Object get_current_frame_edit_timestamp();
extern Object get_current_user_name();
extern Object get_current_user_name_if_any_case_insensitive();
extern Object get_default_image_x_scale();
extern Object get_default_image_y_scale();
extern Object get_edit_subcommand_menu_core_choices();
extern Object get_gensym_window_parameter();
extern Object get_hfep_edit_subcomand_choices_if_appropriate();
extern Object get_instance_with_name_if_any();
extern Object get_kfep_conversion_choice_index_delta_for_arrow();
extern Object get_kfep_edit_subcomand_choices_if_appropriate();
extern Object get_language_for_current_workstation_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_natural_language_for_editor();
extern Object get_next_text_line();
extern Object get_next_token_from_text_if_available();
extern Object get_or_make_category_for_category_symbol();
extern Object get_or_make_menu_content_structure_for_parsing_token();
extern Object get_overall_minimum_width_for_subcommand_menu_column();
extern Object get_reference_to_item();
extern Object get_scrap_if_any();
extern Object get_selected_text_region_for_edit_box();
extern Object get_slot_component_features();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_compiler_for_current_edit_state_if_any();
extern Object get_slot_value_function();
extern Object get_table_cell_indices();
extern Object get_text_region_position();
extern Object get_unicode_set_width_as_text_width();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace();
extern Object getfq_function_no_default();
extern Object grammar_cons_1();
extern Object handle_parsing_or_compilation_problem();
extern Object handle_paste_availability_event_in_g2();
extern Object handle_paste_event_in_g2();
extern Object handle_spaces_intelligently_p();
extern Object highlight_or_unhighlight_cell();
extern Object highlight_or_unhighlight_kfep_conversion_choice();
extern Object image_plane_blackboard_function();
extern Object incomplete_phrases_for_previous_token();
extern Object incomplete_token_can_be_construed_as_complete();
extern Object indicate_editor_subcommand_button_pending_state();
extern Object indicate_subcommand_pending_state();
extern Object indicate_subcommand_pending_state_for_block_cell();
extern Object indicate_subcommand_pending_state_for_text_cell();
extern Object initialize_edit_subcommand_menu();
extern Object initialize_kana_to_kanji_converters();
extern Object initialize_parser_state_for_current_parsing_context();
extern Object initialize_parser_state_for_free_text();
extern Object innermost_spot_blackboard_function();
extern Object insert_character_at_cursor_from_outside();
extern Object insert_text_string_at_cursor();
extern Object insert_text_string_in_text_being_edited();
extern Object install_current_edit_state_compiled_result();
extern Object intern_text_string();
extern Object intern_wide_string();
extern Object inverse_magnify();
extern Object inverse_scalef_function();
extern Object iso_8859_5_to_gensym_cyrillic();
extern Object ksc_to_gensym_ksc();
extern Object legal_gensym_jis_character_code_p();
extern Object legal_gensym_ksc_character_code_p();
extern Object length_of_text_in_region();
extern Object lengthw();
extern Object load_and_initialize_type_description();
extern Object lookup_frame_description_reference_of_frame_style();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_category_instance_menus();
extern Object make_context_description();
extern Object make_edit_box_change_1();
extern Object make_edit_subcommand_menu();
extern Object make_editor_subcommand_button();
extern Object make_empty_text();
extern Object make_format_frame();
extern Object make_frame();
extern Object make_hfep_hanc_type_function();
extern Object make_icon_cell_for_entity();
extern Object make_incomplete_phrase_structure_1();
extern Object make_keymap();
extern Object make_kfep_conversion_choice_menu();
extern Object make_kfep_conversion_text_region();
extern Object make_menu_content_structure_for_character_position();
extern Object make_menu_content_structure_for_token_position();
extern Object make_or_reformat_table();
extern Object make_parsing_context_1();
extern Object make_parsing_token_1();
extern Object make_permanent_parsing_context_structure_internal();
extern Object make_permanent_parsing_token_structure_internal();
extern Object make_permanent_subcommand_state_structure_internal();
extern Object make_permanent_text_inserter_spot_structure_internal();
extern Object make_phrase_rule_completion_1();
extern Object make_subcommand_menu();
extern Object make_subcommand_menu_button_spot_1();
extern Object make_subcommand_state_1();
extern Object make_text_cell();
extern Object make_text_inserter_spot_1();
extern Object make_text_region();
extern Object make_thread_array();
extern Object make_workspace();
extern Object map_composed_character_to_base_character_for_editor();
extern Object map_editor_special_character_type_in();
extern Object map_extended_utf_g_characters_to_unicode();
extern Object map_gensym_han_character_code_to_unicode();
extern Object maybe_skip_comment_tokens();
extern Object memq_function();
extern Object mouse_motion_in_subcommand_state();
extern Object mouse_pointer_blackboard_function();
extern Object mouse_up_in_subcommand_state();
extern Object move_edit_cursor();
extern Object move_or_delete_from_cursor();
extern Object mutate_global_property();
extern Object nest_draw_area_for_frame_1();
extern Object new_get_available_image_plane();
extern Object non_menu_choice_permitted_p();
extern Object note_change_to_block_1();
extern Object note_kb_state_change_to_slot_by_saving_text();
extern Object note_kfep_conversion_choice();
extern Object obtain_paste_request_id_for_editor();
extern Object ordinary_space_p();
extern Object outstanding_parsing_context_count();
extern Object outstanding_parsing_token_count();
extern Object outstanding_subcommand_state_count();
extern Object outstanding_text_inserter_spot_count();
extern Object parse_text_for_slot();
extern Object parsing_context_cursor_token_function();
extern Object parsing_context_p_function();
extern Object parsing_context_structure_memory_usage();
extern Object parsing_token_incomplete_p();
extern Object parsing_token_incomplete_phrases_function();
extern Object parsing_token_structure_memory_usage();
extern Object paste_from_current_scrap_if_any();
extern Object paste_text_string();
extern Object pending_romaji_character_in_text_p();
extern Object phrase_cons();
extern Object pop_for_token();
extern Object print_decoded_time();
extern Object prune_edit_undo_stack();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_up_edit_workspace();
extern Object put_up_kfep_conversion_choices();
extern Object reason_for_bad_parse_as_string();
extern Object reclaim_chain_of_incomplete_phrases();
extern Object reclaim_edit_box_change_1();
extern Object reclaim_edit_undo_or_redo_stack();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_list_if_list();
extern Object reclaim_gensym_tree_function();
extern Object reclaim_grammar_tree_1();
extern Object reclaim_hfep_hanc_type_function();
extern Object reclaim_managed_floats_in_phrases();
extern Object reclaim_managed_longs_in_phrases();
extern Object reclaim_most_recent_reason_for_bad_parse_qm();
extern Object reclaim_parsing_context();
extern Object reclaim_parsing_context_1_1();
extern Object reclaim_parsing_token_1();
extern Object reclaim_parsing_token_and_accompanying_data();
extern Object reclaim_pending_procedure_signature_workspaces();
extern Object reclaim_phrase_rule_completions();
extern Object reclaim_sexp_annotation_hash_qm();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_structure_if_any();
extern Object reclaim_subcommand_function_arglist_qm_value();
extern Object reclaim_subcommand_state_1();
extern Object reclaim_text_inserter_spot_1();
extern Object reclaim_text_string();
extern Object reclaim_text_strings_in_phrases();
extern Object reclaim_vectors_for_phrase_conses();
extern Object reclaim_wide_string();
extern Object recompile_cell_array();
extern Object recompile_item();
extern Object recompile_item_1();
extern Object recompile_slot_of_frame_1();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object reformat_text();
extern Object reformat_text_box_in_place();
extern Object regenerate_optimized_constant();
extern Object relative_index_of_first_non_whitespace_character();
extern Object release_mouse_pointers();
extern Object remove_token_from_parsing_context();
extern Object request_paste_availability_for_editor();
extern Object request_paste_availability_status();
extern Object request_paste_for_editor();
extern Object request_paste_of_cut_buffer_text();
extern Object retreat_parsing_context();
extern Object return_from_current_workstation_context();
extern Object reverse_text_region();
extern Object scalef_function();
extern Object scrap_text();
extern Object scrap_text_region();
extern Object scroll_text_into_view();
extern Object search_backward_incrementally_for_text_in_editor();
extern Object search_for_longest_prefix_with_kfep_word_choices();
extern Object search_forward_incrementally_for_text_in_editor();
extern Object search_incrementally_for_text_in_editor();
extern Object select_text_region_in_scrap();
extern Object set_up_kfep_conversion_text_region();
extern Object shift_block();
extern Object shift_cursor_token();
extern Object shrink_wrap_workspace();
extern Object skip_kfep_conversion();
extern Object slot_value_cons_1();
extern Object stop_blinker();
extern Object string_eq_w();
extern Object string_equalw();
extern Object string_upcasew();
extern Object stripped_text_p();
extern Object subcommand_enabled_p();
extern Object subcommand_state_structure_memory_usage();
extern Object symbol_name_text_string();
extern Object text_being_edited_may_have_no_value_p();
extern Object text_break_p();
extern Object text_can_be_copied_within_editor_p();
extern Object text_can_be_cut_within_editor_p();
extern Object text_can_be_deleted_within_editor_p();
extern Object text_can_be_pasted_in_current_workstation_p();
extern Object text_can_be_transferred_within_editor_p();
extern Object text_cell_of_table_blackboard_function();
extern Object text_empty_p();
extern Object text_inserter_spot_structure_memory_usage();
extern Object text_region_oriented_backward_p();
extern Object text_region_oriented_forward_p();
extern Object text_string_length();
extern Object text_string_matches_current_scrap_p();
extern Object text_string_p();
extern Object text_string_substring();
extern Object tformat();
extern Object tformat_text_string();
extern Object there_is_a_scrap_p();
extern Object transform_image();
extern Object translate_subcommand_menu_choice();
extern Object translate_subcommand_menu_choice_as_appropriate();
extern Object translation_for_symbol_qm();
extern Object twrite();
extern Object twrite_frame_edit_timestamp();
extern Object twrite_wide_character();
extern Object type_of_slot_if_editable();
extern Object unambiguous_parsing_token_p();
extern Object unconvert_kfep_conversion_text_region();
extern Object undo_or_redo_edit();
extern Object undo_or_redo_edit_possible_p();
extern Object unicode_lowercase_if_uppercase();
extern Object unicode_uppercase_if_lowercase();
extern Object update_authors_and_time_of_frame_edit();
extern Object update_authors_attribute();
extern Object update_border_of_text_box();
extern Object update_edit_operation_subcommands();
extern Object update_edit_operation_subcommands_in_current_editor();
extern Object update_frame_status();
extern Object update_images();
extern Object update_images_of_block();
extern Object update_kfep_buttons();
extern Object update_kfep_conversion_choices_as_appropriate();
extern Object update_object_pool_meters_list();
extern Object update_parsing_context_completions_as_appropriate();
extern Object update_text_in_edit_box();
extern Object update_text_region();
extern Object use_built_in_subcommand_menu_choice_translation();
extern Object use_return_key_as_end_key_in_current_editor_p();
extern Object wide_character_assoc();
extern Object wide_character_member();
extern Object wide_string_compare();
extern Object within_text_region_p();
extern Object workstation_context_specifics_blackboard_function();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Action_button_class_description, Qaction_button_class_description);
#define Additional_time_for_synthetic_paste_event_timestamps FIX((SI_Long)13L)
extern Object Allowable_non_alpha_characters_in_kfep_conversions;
extern Object Alphabet_whitespace_chars;
DECLARE_VARIABLE_WITH_SYMBOL(Ascii_to_kana_map, Qascii_to_kana_map);
extern Object Background_color_for_disabled_subcommands;
extern Object Background_color_for_enabled_subcommands;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
extern Object Bad_phrase;
extern Object Basic_core_edit_subcommand_choices;
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
extern Object Built_in_subcommand_menu_choice_translations;
DECLARE_VARIABLE_WITH_SYMBOL(Button_class_description, Qbutton_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_nupec_semantics_graph, Qcache_nupec_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cell, Qcell);
extern Object Cfep_edit_subcommand_choices;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_parsing_contexts, Qchain_of_available_parsing_contexts);
extern Object Chain_of_available_parsing_contexts_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_parsing_tokens, Qchain_of_available_parsing_tokens);
extern Object Chain_of_available_parsing_tokens_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_subcommand_states, Qchain_of_available_subcommand_states);
extern Object Chain_of_available_subcommand_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_text_inserter_spots, Qchain_of_available_text_inserter_spots);
extern Object Chain_of_available_text_inserter_spots_vector;
extern Object Class_description_gkbprop;
extern Object Core_edit_subcommand_choices;
extern Object Core_edit_subcommand_choices_after_removals;
DECLARE_VARIABLE_WITH_SYMBOL(Current_character_index_after_token, Qcurrent_character_index_after_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_workspace, Qcurrent_edit_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Current_extended_utf_g_low_half_character_qm, Qcurrent_extended_utf_g_low_half_character_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_grammar, Qcurrent_grammar);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_symbol_token, Qcurrent_indicator_for_category_of_symbol_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_this_name, Qcurrent_indicator_for_category_of_this_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_line_index_for_end_of_token, Qcurrent_line_index_for_end_of_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_localization_purpose_qm, Qcurrent_localization_purpose_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_character, Qcurrent_parsing_context_character);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_line, Qcurrent_parsing_context_line);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_qm, Qcurrent_parsing_context_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_text, Qcurrent_parsing_context_text);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_text_length, Qcurrent_parsing_context_text_length);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
extern Object Default_kanji_conversion_text_region_highlight_color;
DECLARE_VARIABLE_WITH_SYMBOL(Default_language, Qdefault_language);
DECLARE_VARIABLE_WITH_SYMBOL(Dial_class_description, Qdial_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_update_frame_authors_qm, Qdo_not_update_frame_authors_qm);
extern Object Edit_operation_subcommand_names;
extern Object Edit_operation_subcommand_names_after_removals;
DECLARE_VARIABLE_WITH_SYMBOL(Editing_context, Qediting_context);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
extern Object Editor_special_character_alist;
DECLARE_VARIABLE_WITH_SYMBOL(Editor_specific_natural_language_override_qm, Qeditor_specific_natural_language_override_qm);
extern Object Ellipsis_text_string;
extern Object Ellipsis_text_string_length;
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fixup_authors_to_skip, Qfixup_authors_to_skip);
DECLARE_VARIABLE_WITH_SYMBOL(Fonts, Qfonts);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(G2_comment_tokenizer, Qg2_comment_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_linebreak, Qgensym_char_or_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_paragraph_break, Qgensym_char_or_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_bullet, Qgensym_code_for_bullet);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_capital_ligature_oe, Qgensym_code_for_capital_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_linebreak, Qgensym_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_paragraph_break, Qgensym_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_letter_f_with_hook, Qgensym_code_for_small_letter_f_with_hook);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_ligature_oe, Qgensym_code_for_small_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_trade_mark_sign, Qgensym_code_for_trade_mark_sign);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_linebreak_qm, Qgensym_esc_for_linebreak_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_paragraph_break_qm, Qgensym_esc_for_paragraph_break_qm);
extern Object Gensym_to_unicode_full_row_map;
extern Object Global_daylight_saving_time_adjustment;
extern Object Global_grammar;
DECLARE_VARIABLE_WITH_SYMBOL(Han_interpretation_mode, Qhan_interpretation_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Hfep_capability_qm, Qhfep_capability_qm);
extern Object Hfep_edit_subcommand_choices;
extern Object Highlight_color_for_disabled_non_pending_subcommands;
extern Object Highlight_color_for_disabled_pending_subcommands;
extern Object Highlight_color_for_enabled_non_pending_subcommands;
extern Object Highlight_color_for_enabled_pending_subcommands;
extern Object Highlight_color_for_non_pending_off_radio_button_subcommands;
extern Object Highlight_color_for_non_pending_on_radio_button_subcommands;
extern Object Highlight_color_for_pending_off_radio_button_subcommands;
extern Object Highlight_color_for_pending_on_radio_button_subcommands;
DECLARE_VARIABLE_WITH_SYMBOL(Icon_cell_class_description, Qicon_cell_class_description);
#define Icp_window_protocol_supports_native_cut_and_paste FIX((SI_Long)19L)
DECLARE_VARIABLE_WITH_SYMBOL(In_recompile_item_p, Qin_recompile_item_p);
extern Object Include_original_choice_in_subcommand_menu_choice_translation_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
#define Invalid_unicode_full_row FIX((SI_Long)7L)
DECLARE_VARIABLE_WITH_SYMBOL(Iso_latin1_special_character_code_map, Qiso_latin1_special_character_code_map);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Item_list_class_description, Qitem_list_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Journal_shutout_scan_p, Qjournal_shutout_scan_p);
DECLARE_VARIABLE_WITH_SYMBOL(Keep_edit_workspace_hidden_no_matter_what_qm, Qkeep_edit_workspace_hidden_no_matter_what_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_capability_qm, Qkfep_capability_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_conversion_choice_menu_class_description, Qkfep_conversion_choice_menu_class_description);
extern Object Kfep_conversion_text_region_expansion_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_converters_have_been_initialized_qm, Qkfep_converters_have_been_initialized_qm);
extern Object Kfep_edit_subcommand_choices;
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_search_limit_1, Qkfep_search_limit_1);
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_search_limit_2, Qkfep_search_limit_2);
DECLARE_VARIABLE_WITH_SYMBOL(Language_parameters, Qlanguage_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Localization_context, Qlocalization_context);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
DECLARE_VARIABLE_WITH_SYMBOL(Meter_class_description, Qmeter_class_description);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
#define Most_positive_workspace_coordinate FIX((SI_Long)16777215L)
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(New_table, Qnew_table);
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Note_as_kb_state_change_qm, Qnote_as_kb_state_change_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Parsing_context_count, Qparsing_context_count);
DECLARE_VARIABLE_WITH_SYMBOL(Parsing_token_count, Qparsing_token_count);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Readout_table_class_description, Qreadout_table_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Region_invalidation_is_preferred, Qregion_invalidation_is_preferred);
DECLARE_VARIABLE_WITH_SYMBOL(Reverse_iso_latin1_special_character_code_map, Qreverse_iso_latin1_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Scrap_class_description, Qscrap_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_subtable_class_description, Qsimulation_subtable_class_description);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Slider_readout_class_description, Qslider_readout_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Special_variable_for_use_value_macro, Qspecial_variable_for_use_value_macro);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Statement_class_description, Qstatement_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Subcommand_state_count, Qsubcommand_state_count);
extern Object Text_color_for_disabled_subcommands;
extern Object Text_color_for_enabled_subcommands;
DECLARE_VARIABLE_WITH_SYMBOL(Text_inserter_spot_count, Qtext_inserter_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Text_of_definition_being_compiled, Qtext_of_definition_being_compiled);
DECLARE_VARIABLE_WITH_SYMBOL(Text_region_class_description, Qtext_region_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Text_time_stamp_seconds, Qtext_time_stamp_seconds);
extern Object The_type_description_of_parsing_context;
extern Object The_type_description_of_parsing_token;
extern Object The_type_description_of_subcommand_state;
extern Object The_type_description_of_text_inserter_spot;
DECLARE_VARIABLE_WITH_SYMBOL(Time_of_frame_edit_base_time, Qtime_of_frame_edit_base_time);
extern Object Time_of_last_allowable_frame_edit_time;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Trace_parsing_context_p, Qtrace_parsing_context_p);
DECLARE_VARIABLE_WITH_SYMBOL(Trace_parsing_context_tokenizing_p, Qtrace_parsing_context_tokenizing_p);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(User_menu_choice_class_description, Quser_menu_choice_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_class_description, Qvariable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_name_box_class_description, Qworkspace_name_box_class_description);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
