/* edit1.h -- Header File for edit1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand_optional;
extern Object Kabort;
extern Object Qblock;
extern Object Qcompile;
extern Object Qcons;
extern Object Qdelete;
extern Object Qfixnum;
extern Object Qfloat;
extern Object Qfunction;
extern Object Qinteger;
extern Object Qnumber;
extern Object Qopen;
extern Object Qsequence;
extern Object Qstring;
extern Object Qsymbol;
extern Object Qthe;
extern Object Ktype;
extern Object Qtype;
extern Object Qunsigned_byte;
extern Object Kupcase;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object abort_editing_current_workstation_context(void);
extern Object accept_kfep_conversion(void);
extern Object add_class_to_environment(int,...);
extern Object add_constituent_to_incomplete_phrases(Object,Object,Object);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_keymap_to_workstation_context(Object,Object);
extern Object add_parameter_string_to_workspace(Object,Object,Object);
extern Object add_signature_to_workspace(Object,Object,Object,Object);
extern Object add_space_out_text_if_no_lisp(Object);
extern Object add_subblock(Object,Object);
extern Object add_title_of_signature_to_signature_workspace(Object,Object,Object);
extern Object add_to_workspace(int,...);
extern Object advance_parsing_for_token(Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_long_box(void);
extern Object allow_continuation_of_editing_context_upon_confirmation(void);
extern Object alpha_numeric_p(Object);
extern Object argument_list_description_function(Object);
extern Object arrows_usable_for_kfep_conversion_choices_p(Object);
extern Object assemble_parameters_for_built_in_function(Object);
extern Object assemble_parameters_for_foreign_function_declaration(Object);
extern Object assemble_parameters_for_function(Object);
extern Object assemble_parameters_for_method(Object);
extern Object assemble_parameters_for_procedure(Object);
extern Object assemble_parameters_for_remote_procedure_declaration(Object);
extern Object assemble_parameters_for_tabular_function_of_1_arg(Object);
extern Object assq_function(Object,Object);
extern Object attribute_table_p(Object);
extern Object auto_insert_text_from_block(Object,Object);
extern Object auto_insert_text_in_editor(Object);
extern Object backtrace_cons_1(Object,Object);
extern Object blank_p(Object);
extern Object block_of_selection_focus_blackboard_function(Object);
extern Object bracket_open_or_close_qm(Object);
extern Object button_menu_spot_structure_memory_usage(void);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object cancel_editing(void);
extern Object category_menu_button_spot_structure_memory_usage(void);
extern Object cell_of_table_blackboard_function(Object);
extern Object change_color_of_text_box(int,...);
extern Object change_edit_box(int,...);
extern Object change_edit_box_cursor_position(int,...);
extern Object change_frame_description_reference_of_image_plane(Object,Object);
extern Object change_slot_description_value_function(Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object change_text_cell_property(Object,Object,Object);
extern Object character_index_blackboard_function(Object);
extern Object character_index_of_source_position(Object);
extern Object character_sequence_token_menu_button_spot_structure_memory_usage(void);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object choose_font_format_per_font_size(Object,Object);
extern Object choose_token_menu_item_format_per_system_tables(int,...);
extern Object cleanup_for_edit_workspace(Object);
extern Object clear_optimized_constants(void);
extern Object clear_text_region_from_edit_box(int,...);
extern Object close_signature_window_if_appropriate(void);
extern Object coerce_text_region_to_scrap(Object);
extern Object collect_subclasses(Object);
extern Object colon_content_p(Object);
extern Object color_or_metacolor_p(Object);
extern Object command_argument_value(Object);
extern Object compile_attributes_to_edit_using_multiline_editor_for_slot(int,...);
extern Object compile_for_current_edit_state(Object,Object,Object);
extern Object compile_item_or_datum_or_no_item_attribute_for_slot(int,...);
extern Object compute_distance_of_text_line_from_top(Object,Object);
extern Object compute_edit_search_box_location(Object);
extern Object conclude_into_attribute_component(int,...);
extern Object conclude_into_virtual_attribute_component(Object,Object,Object,Object,Object,Object);
extern Object confirm_or_cancel(int,...);
extern Object constant_queue_next(Object,Object);
extern Object construct_workspace_for_signature(Object,Object,Object);
extern Object continue_edit_after_mouse_watch(Object);
extern Object continue_editing_by_doing_insert_selected_text_command(Object);
extern Object continue_editing_by_posting_cut_copy_paste_menu(Object);
extern Object continuous_spaces_filter_lisp(Object);
extern Object convert_current_menu_choice(void);
extern Object convert_key_code_to_gensym_character(Object);
extern Object convert_key_code_to_unicode(Object);
extern Object convert_text_region_to_text_string(int,...);
extern Object convert_text_to_text_string(int,...);
extern Object convert_to_hiragana_if_possible(Object);
extern Object convert_to_katakana_if_possible(Object);
extern Object copy_as_wide_string(Object);
extern Object copy_current_wide_string(void);
extern Object copy_current_wide_string_possibly_noting_creation(void);
extern Object copy_for_phrase(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_list_using_gensym_conses_1(Object);
extern Object copy_list_using_grammar_conses_1(Object);
extern Object copy_list_using_token_stack_conses_1(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_symbol_name_parsably(Object,Object);
extern Object copy_text(Object);
extern Object copy_text_string(Object);
extern Object copy_tree_using_grammar_conses_1(Object);
extern Object copy_tree_using_token_stack_conses_1(Object);
extern Object count_current_number_of_token_menu_choices(void);
extern Object create_or_revive_workspace_for_procedure_signature(Object,Object,Object);
extern Object create_search_workspace(Object);
extern Object current_natural_language_for_editor(void);
extern Object current_punctuation_alist(void);
extern Object current_workstation_has_pending_events_p(void);
extern Object decode_procedure_type_field(Object);
extern Object delete_any_text_regions(int,...);
extern Object delete_character(Object);
extern Object delete_frame(Object);
extern Object delete_frame_after_checking_serial_number(Object,Object);
extern Object delete_frame_after_checking_serial_number_with_list(Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_image_plane(Object);
extern Object delete_intelligently_from_text_being_edited(int,...);
extern Object delete_item(Object);
extern Object delete_subblocks_of_class(Object,Object);
extern Object delete_token_stack_cons_1(Object,Object);
extern Object delete_token_stack_element_1(Object,Object);
extern Object deselect_current_text_region(Object);
extern Object detail_pane(Object);
extern Object determine_appropriate_tokenizer(void);
extern Object digit_string_overflowed_by_digit_char_lists(Object,Object,Object);
extern Object digit_string_underflowed_by_digit_char_lists(Object,Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object disable_text_region_operation_subcommands_in_current_editor(void);
extern Object display_editor_notification_1(Object);
extern Object do_copy_and_insert_within_editor(void);
extern Object do_copy_within_editor(void);
extern Object do_cut_and_insert_within_editor(void);
extern Object do_cut_within_editor(int,...);
extern Object do_delete_within_editor(void);
extern Object do_insert_within_editor(void);
extern Object do_move_within_editor(void);
extern Object do_paste_within_editor(void);
extern Object do_trial_kfep_conversion(int,...);
extern Object dont_space_before_character_p(Object);
extern Object edit_box_spot_structure_memory_usage(void);
extern Object edit_context_remains_valid_p(Object);
extern Object edit_state_for_search_p(Object);
extern Object editor_newline(void);
extern Object editor_post_command_hook(Object,Object);
extern Object empty_text_region_p(Object);
extern Object enable_or_disable_edit_end_and_update_buttons(Object);
extern Object enable_or_disable_radio_button_subcommand(Object,Object,Object);
extern Object enable_or_disable_subcommand(int,...);
extern Object encode_current_source_position(void);
extern Object end_editing(void);
extern Object enlarge_workspace_if_necessary(int,...);
extern Object enter_button_down_context(Object,Object);
extern Object enter_context_in_current_workstation(int,...);
extern Object enter_cyrillic_input_mode(void);
extern Object enter_dialog(int,...);
extern Object enter_edit_menu_state(Object);
extern Object enter_editing_context(int,...);
extern Object enter_editing_context_1(int,...);
extern Object enter_escape_context(int,...);
extern Object enter_hangul_input_mode(void);
extern Object enter_kana_conversion_mode(Object);
extern Object enter_mouse_watch_state(Object,Object);
extern Object enter_subcommand_context(Object);
extern Object enter_text_marking_state(Object,Object,Object);
extern Object erase_any_temporary_information_on_edit_workspace(int,...);
extern Object establish_next_workstation_context_continuation(Object,Object,Object,Object);
extern Object event_blackboard_function(Object);
extern Object exclude_editor_prompt_p(Object);
extern Object exit_cyrillic_input_mode(void);
extern Object exit_editing_context_upon_denial_of_confirmation(void);
extern Object exit_hangul_input_mode(void);
extern Object exit_kfep_mode_if_necessary(int,...);
extern Object expand_or_shrink_kfep_conversion_text_region(Object);
extern Object extend_current_gensym_string(int,...);
extern Object extend_parsing_as_appropriate(int,...);
extern Object extend_parsing_or_exit_editor_as_appropriate(void);
extern Object fill_wide_string_1(Object,Object,Object,Object);
extern Object filter_editor_menus(Object);
extern Object find_base_plane_in_stack_of_coupled_image_planes(Object);
extern Object find_end_of_line_of_text(Object,Object);
extern Object find_end_of_text(int,...);
extern Object find_frame_of_class_in_mouse_pointer(Object,Object);
extern Object find_frame_transform_if_any(Object,Object);
extern Object find_image_plane_for_workspace_in_pane(Object,Object);
extern Object find_next_character_if_any(Object,Object,Object);
extern Object find_next_instance_of_search_string(int,...);
extern Object find_object_near_workstation_event(int,...);
extern Object find_position_adjacent_to_end_of_kfep_conversion_text_region(Object);
extern Object find_position_in_text(int,...);
extern Object find_position_in_text_given_image_plane(int,...);
extern Object find_previous_character_if_any(Object,Object,Object,Object);
extern Object find_text_tail_for_line(Object,Object);
extern Object finish_parsing_insofar_as_possible(void);
extern Object first_subblock(Object);
extern Object force_process_drawing(void);
extern Object frame_blackboard_function(Object);
extern Object frame_has_been_reprocessed_p_function(Object,Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object g2_list_insert_at_beginning(Object,Object);
extern Object g2_use_scrolling_editor(Object);
extern Object general_valid_edit_state_p(Object);
extern Object generate_float_vector(Object);
extern Object generate_spot_for_button_menu(Object,Object,Object);
extern Object generate_spot_for_category_menu(Object,Object);
extern Object generate_spot_for_character_sequence_token_menu(Object,Object);
extern Object generate_spot_for_edit_box(Object,Object);
extern Object generate_spot_for_editor_notification(Object,Object);
extern Object generate_spot_for_kfep_conversion_choice_menu(Object,Object);
extern Object generate_spot_for_pathname_component_token_menu(Object,Object);
extern Object generate_spot_for_pure_input_table(Object,Object,Object);
extern Object generate_spot_for_replacement_token_menu(Object,Object);
extern Object generate_spot_for_token_menu(Object,Object);
extern Object generate_text_box_spot(Object,Object,Object);
extern Object generate_workspace_background_spot(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_ksc_code_to_contiguous(Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object get_alias_for_slot_name_if_any(Object,Object);
extern Object get_attribute_description_evaluation_value(Object,Object);
extern Object get_attribute_table_row_alias_string(Object,Object);
extern Object get_built_in_function_argument_names(Object);
extern Object get_category_of_token(Object);
extern Object get_character_index_past_separator(Object);
extern Object get_current_edit_state_parse_if_any(void);
extern Object get_evaluation_value_for_attribute(Object,Object);
extern Object get_from_g2_text(Object,Object,Object);
extern Object get_gensym_window_parameter(Object,Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_menu_content_structure_for_last_token_position(Object);
extern Object get_natural_language_for_editor(Object);
extern Object get_next_text_line(Object);
extern Object get_next_token_from_text_if_available(int,...);
extern Object get_or_make_category_for_category_symbol(Object);
extern Object get_or_make_menu_content_structure_for_current_token_position(void);
extern Object get_primary_name_for_frame_if_any(Object);
extern Object get_property_value_function(int,...);
extern Object get_reference_to_item(Object);
extern Object get_selected_edit_cursor_character_index(void);
extern Object get_selected_edit_cursor_line_index(void);
extern Object get_selected_text_region_for_edit_box(void);
extern Object get_slot_component_features(Object,Object,Object);
extern Object get_slot_component_group(int,...);
extern Object get_slot_component_value(Object,Object,Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_slot_value_compiler_for_current_edit_state_if_any(void);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_superior_edit_state_if_any(Object);
extern Object get_symbol_properties_function(Object);
extern Object get_table_cell(Object,Object,Object);
extern Object get_text_region_position(int,...);
extern Object get_tokenizer_for_category(Object);
extern Object get_type_of_slot_component_if_any(Object,Object,Object,Object,Object);
extern Object get_type_of_slot_if_any(int,...);
extern Object get_ui_command_function(Object);
extern Object get_ui_command_pursuer(Object);
extern Object get_ui_command_translator(Object);
extern Object get_ui_parameter(int,...);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object grammar_cons_1(Object,Object);
extern Object handle_character_in_text_event(Object);
extern Object handle_cyrillic_character_in_text_event(Object);
extern Object handle_hangul_character_in_text_event(Object);
extern Object handle_insertion_of_symbol(Object);
extern Object handle_mouse_down_event_in_edit_context(Object);
extern Object handle_parsing_ambiguity(Object);
extern Object handle_parsing_or_compilation_problem(int,...);
extern Object handle_spaces_intelligently_p(Object);
extern Object handle_uncompilable_edit_state_result(Object,Object,Object);
extern Object has_text_regions_p(int,...);
extern Object highlight_or_unhighlight_attribute(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object highlight_or_unhighlight_cell(int,...);
extern Object highlight_or_unhighlight_for_slot(int,...);
extern Object highlight_or_unhighlight_selected_token_menu_choice(Object);
extern Object highlight_or_unhighlight_text_box(int,...);
extern Object highlight_or_unhighlight_token_menu_text_cell(Object,Object,Object);
extern Object highlight_or_unhighlight_what_is_being_edited(Object);
extern Object home_cursor(void);
extern Object home_down_cursor(void);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_of_selection_focus_blackboard_function(Object);
extern Object in_order_p(Object);
extern Object incomplete_phrases_for_previous_token(void);
extern Object initialize_digits_of_extremal_fixnum_as_string(void);
extern Object initialize_digits_of_most_negative_fixnum_as_string(void);
extern Object initialize_digits_of_most_positive_fixnum_as_string(void);
extern Object initialize_edit_subcommand_menu(Object);
extern Object initialize_most_fixnum_digits(void);
extern Object innermost_spot_blackboard_function(Object);
extern Object insert_character_at_cursor_from_outside(int,...);
extern Object insert_ellipsis_as_appropriate(int,...);
extern Object insert_in_g2_text(Object,Object,Object);
extern Object insert_n_spaces_or_tab(void);
extern Object insert_text_string_at_cursor(int,...);
extern Object insert_text_string_at_cursor_from_outside(int,...);
extern Object insert_text_string_in_text_being_edited(int,...);
extern Object insert_text_within_editor_from_text_region(Object);
extern Object insert_token_menu_text_cell_text_at_cursor(Object,Object);
extern Object insert_typed_in_character_at_cursor(Object);
extern Object install_current_edit_state_compiled_result(Object,Object,Object);
extern Object instance_of_category_acceptable_p(Object,Object,Object);
extern Object instance_of_token_acceptable_in_current_edit_state_p(Object,Object,Object);
extern Object intercepted_text_p(Object);
extern Object intern_text_string(int,...);
extern Object inverse_scalef_function(Object,Object);
extern Object invisible_proprietary_procedure(Object);
extern Object java_editing_category_p(Object);
extern Object kfep_conversion_choice_menu_button_spot_structure_memory_usage(void);
extern Object ks2_bytes_to_ksc5601(Object,Object);
extern Object ksc_to_gensym_ksc(Object);
extern Object lengthw(Object);
extern Object line_index_blackboard_function(Object);
extern Object line_index_of_source_position(Object);
extern Object list_prefix_p(Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_frame_description_reference_of_block_qm(Object);
extern Object lookup_frame_description_reference_of_frame_style(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_box_for_signatures(Object);
extern Object make_button_menu_spot_1(void);
extern Object make_caption_text_for_edit_workspace(int,...);
extern Object make_category_instance_menus(Object,Object,Object);
extern Object make_category_menu_button_spot_1(void);
extern Object make_category_menu_table(Object);
extern Object make_category_menu_table_row(Object);
extern Object make_character_sequence_token_menu_button_spot_1(void);
extern Object make_context_description(Object,Object,Object,Object);
extern Object make_description_box(Object);
extern Object make_description_box_with_text(Object);
extern Object make_description_of_barrier_to_destabilization(void);
extern Object make_edit_box(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_edit_box_spot_1(void);
extern Object make_edit_state_1(void);
extern Object make_edit_subcommand_menu(void);
extern Object make_empty_text(void);
extern Object make_entity(int,...);
extern Object make_evaluation_quantity(Object);
extern Object make_format_frame(Object);
extern Object make_frame(Object);
extern Object make_free_text_box(int,...);
extern Object make_incomplete_phrase_structure_1(Object,Object,Object,Object);
extern Object make_keymap(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_kfep_conversion_choice_menu_button_spot_1(void);
extern Object make_lost_spaces_text_element(Object);
extern Object make_menu_button_spot_1(void);
extern Object make_menu_content_structure_for_character_position(Object,Object,Object);
extern Object make_menu_content_structure_for_token_position(Object,Object);
extern Object make_menu_of_names_from_directory(Object,Object);
extern Object make_message(int,...);
extern Object make_or_reformat_table(int,...);
extern Object make_parameters_from_rpd_arg_description(Object);
extern Object make_partial_command(Object,Object);
extern Object make_pathname_component_token_menu_button_spot_1(void);
extern Object make_permanent_button_menu_spot_structure_internal(void);
extern Object make_permanent_category_menu_button_spot_structure_internal(void);
extern Object make_permanent_character_sequence_token_menu_button_spot_structure_internal(void);
extern Object make_permanent_edit_box_spot_structure_internal(void);
extern Object make_permanent_kfep_conversion_choice_menu_button_spot_structure_internal(void);
extern Object make_permanent_menu_button_spot_structure_internal(void);
extern Object make_permanent_pathname_component_token_menu_button_spot_structure_internal(void);
extern Object make_permanent_replacement_token_menu_button_spot_structure_internal(void);
extern Object make_permanent_subcommand_menu_button_spot_structure_internal(void);
extern Object make_permanent_text_marking_state_structure_internal(void);
extern Object make_permanent_token_menu_button_spot_structure_internal(void);
extern Object make_phrase_rule_completion_1(Object,Object,Object);
extern Object make_position_after_token(Object,Object,Object);
extern Object make_procedure_signature_workspace_entry(Object,Object);
extern Object make_replacement_token_menu_button_spot_1(void);
extern Object make_runtime_float_for_tokenizer(Object);
extern Object make_runtime_long_for_tokenizer(Object);
extern Object make_sexp_annotation_hash(void);
extern Object make_slot_value_float(Object);
extern Object make_slot_value_list_1(Object);
extern Object make_slot_value_long(Object);
extern Object make_stringw_function(Object,Object);
extern Object make_subcommand_menu_button_spot_1(void);
extern Object make_text_cell(int,...);
extern Object make_text_cell_plist_for_color_background(Object);
extern Object make_text_marking_state_1(Object,Object,Object,Object);
extern Object make_text_region(int,...);
extern Object make_text_representation_for_slot_value_itself(Object,Object,Object);
extern Object make_text_value_using_current_edit_state(Object,Object);
extern Object make_thread_array(Object);
extern Object make_token_menu_button_spot_1(void);
extern Object make_token_menu_table(int,...);
extern Object make_token_stack_list_1(Object);
extern Object make_transient_item(Object);
extern Object make_ui_command(int,...);
extern Object make_workspace(int,...);
extern Object make_workspace_background_spot_1(void);
extern Object map_gensym_keyboard_character_to_cyrillic_alternate(Object);
extern Object mark_occurrences_of_string_in_text(Object,Object,Object,Object);
extern Object match_adjacent_symbol_boundary(int,...);
extern Object maybe_offer_to_save_incomplete_statement(void);
extern Object memq_function(Object,Object);
extern Object menu_button_spot_structure_memory_usage(void);
extern Object mouse_motion_in_text_marking(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object mouse_up_in_editing_context(Object);
extern Object mouse_up_in_text_marking(Object);
extern Object move_cursor_by_page_in_editor(Object);
extern Object move_cursor_handling_shift_variant(Object,Object,Object,Object,Object,Object);
extern Object move_down_line(int,...);
extern Object move_or_delete_from_cursor(int,...);
extern Object move_or_delete_from_cursor_to_next_adjacent_word(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object native_editor_commands_p(void);
extern Object native_editor_display_notification(Object,Object);
extern Object native_editor_replace_text(Object,Object,Object,Object,Object,Object);
extern Object native_editor_show_completions(Object,Object);
extern Object native_editor_workspace_p(Object);
extern Object nest_draw_area_for_frame_1(Object);
extern Object new_get_available_image_plane(Object,Object,Object,Object);
extern Object new_get_next_token_from_wide_text_if_available_1(Object,Object,Object,Object,Object,Object,Object);
extern Object newline_p(Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object not_in_kb_loading_editing_context(void);
extern Object note_change_to_block_1(Object,Object);
extern Object note_kb_state_change_to_slot_by_saving_text(Object,Object);
extern Object note_use_of_managed_float_in_phrase(Object);
extern Object note_use_of_managed_long_in_phrase(Object);
extern Object note_use_of_text_string_in_phrase(Object);
extern Object notify_user(int,...);
extern Object nreverse_canonically(Object);
extern Object of_class_p_function(Object,Object);
extern Object offer_to_recompile_items_made_incomplete_if_appropriate(void);
extern Object offer_to_recompile_now_after_edit(void);
extern Object old_read_attribute_name_from_text_string(int,...);
extern Object outstanding_button_menu_spot_count(void);
extern Object outstanding_category_menu_button_spot_count(void);
extern Object outstanding_character_sequence_token_menu_button_spot_count(void);
extern Object outstanding_edit_box_spot_count(void);
extern Object outstanding_kfep_conversion_choice_menu_button_spot_count(void);
extern Object outstanding_menu_button_spot_count(void);
extern Object outstanding_pathname_component_token_menu_button_spot_count(void);
extern Object outstanding_replacement_token_menu_button_spot_count(void);
extern Object outstanding_subcommand_menu_button_spot_count(void);
extern Object outstanding_text_marking_state_count(void);
extern Object outstanding_token_menu_button_spot_count(void);
extern Object outstanding_token_stack_conses(void);
extern Object parameters_for_token_if_any(Object,Object);
extern Object parameters_for_token_if_any1(Object,Object);
extern Object parse_constant_designation(Object,Object);
extern Object parse_first_var_before_space_or_eof_lisp(Object);
extern Object parse_var_of_class_from_rule_or_gf_text_lisp(Object,Object);
extern Object parsing_context_p_function(Object);
extern Object partial_string_acceptable_p_function(Object,Object,Object);
extern Object paste_from_current_scrap_if_any(void);
extern Object paste_text_string(int,...);
extern Object pathname_component_token_menu_button_spot_structure_memory_usage(void);
extern Object phrase_cons(Object,Object);
extern Object pick_cell_from_table(int,...);
extern Object pop_for_token(void);
extern Object post_command_menu(int,...);
extern Object prefer_native_editor_p(Object);
extern Object procedure_method_name_function(Object);
extern Object procedure_signature_hook(void);
extern Object procedure_signature_token_hook(Object);
extern Object procedure_signatures_can_be_shown_p(void);
extern Object process_hfep_output(Object,Object);
extern Object push_for_token(Object,Object,Object,Object,Object,Object,Object);
extern Object push_item_to_end_of_current_localization_domains(Object);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_barrier_on_destabilization_via_editing(Object,Object);
extern Object put_image_on_image_plane(int,...);
extern Object put_preferred_editor_where_slot_is_absent(Object,Object);
extern Object put_up_edit_workspace(int,...);
extern Object put_up_menus(Object,Object,Object);
extern Object put_up_menus_1(Object,Object,Object);
extern Object put_workspace_on_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object raise_image_plane_to_top(int,...);
extern Object read_attribute_name_from_text_string_1(Object,Object,Object);
extern Object read_evaluation_quantity_from_text_string(int,...);
extern Object read_fixnum_from_string(int,...);
extern Object read_float_from_string(Object,Object,Object);
extern Object read_long_from_string(int,...);
extern Object read_number_from_text_string(int,...);
extern Object read_possibly_out_of_bounds_numeric_token(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object read_symbol_from_text_string(int,...);
extern Object reason_for_bad_parse_as_string(Object);
extern Object reason_permanent_items_attribute_is_not_editable(int,...);
extern Object reason_permanent_items_module_is_not_editable(int,...);
extern Object reclaim_backtrace_list_1(Object);
extern Object reclaim_button_menu_spot_1(Object);
extern Object reclaim_category_menu_button_spot_1(Object);
extern Object reclaim_character_sequence_token_menu_button_spot_1(Object);
extern Object reclaim_edit_box_spot_1(Object);
extern Object reclaim_edit_undo_or_redo_stack(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_grammar_list_1(Object);
extern Object reclaim_grammar_tree_1(Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_if_menu_content_structure(Object);
extern Object reclaim_if_position_after_token(Object);
extern Object reclaim_item_and_fsn_list(Object);
extern Object reclaim_items_made_incomplete_list(void);
extern Object reclaim_kfep_conversion_choice_menu_button_spot_1(Object);
extern Object reclaim_menu_button_spot_1(Object);
extern Object reclaim_menu_content_structure(Object);
extern Object reclaim_menu_content_structure_for_character_position(Object);
extern Object reclaim_pathname_component_token_menu_button_spot_1(Object);
extern Object reclaim_pending_procedure_signature_workspaces(Object);
extern Object reclaim_phrase_rule_completions(Object);
extern Object reclaim_procedure_signature_workspace_entry(Object);
extern Object reclaim_replacement_token_menu_button_spot_1(Object);
extern Object reclaim_simple_text_string(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_structure_if_any(Object);
extern Object reclaim_subcommand_menu_button_spot_1(Object);
extern Object reclaim_text(Object);
extern Object reclaim_text_marking_state_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_token_cons_1(Object);
extern Object reclaim_token_list_1(Object);
extern Object reclaim_token_menu_button_spot_1(Object);
extern Object reclaim_token_stack_cons_1(Object);
extern Object reclaim_token_stack_list_1(Object);
extern Object reclaim_token_stack_list_star_1(Object);
extern Object reclaim_token_stack_tree_1(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_item_made_incomplete_if_appropriate(Object);
extern Object record_items_made_incomplete_and_delete(Object,Object);
extern Object record_procedure_signature_workspace(Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reduce_noting_source_position(Object);
extern Object reformat_text_box_in_place(int,...);
extern Object regenerate_optimized_constant(Object);
extern Object release_mouse_pointers(Object);
extern Object remove_any_other_visible_signatures(Object);
extern Object remove_last_item_in_current_localization_domains(void);
extern Object remove_record_of_procedure_signature_workspace(Object);
extern Object replace_entire_edit_box_text(Object);
extern Object replace_pending_delete_text_region(Object,Object);
extern Object replacement_token_menu_button_spot_structure_memory_usage(void);
extern Object replenish_grammar_cons_pool(void);
extern Object replenish_slot_value_cons_pool(void);
extern Object replenish_token_stack_cons_pool(void);
extern Object replenish_token_stack_list_pool(Object);
extern Object request_paste_availability_for_editor(void);
extern Object request_paste_for_editor(void);
extern Object requeue_workstation_event(Object,Object);
extern Object reset_hangul_input_automaton(void);
extern Object restrict_destabilization_p(Object,Object);
extern Object resume_native_editor(Object);
extern Object return_from_current_workstation_context(int,...);
extern Object return_from_edit_menu(Object);
extern Object return_from_search_in_editor(Object);
extern Object returned_values_description_function(Object);
extern Object run_hfep_automaton(Object);
extern Object run_top_level_event_handler(Object);
extern Object runtime_reclaim_pending_procedure_signature_workspaces(void);
extern Object scalef_function(Object,Object);
extern Object scroll_line_down(Object);
extern Object scroll_line_up(Object);
extern Object scroll_text_into_view(Object,Object,Object);
extern Object select_current_text_region(Object);
extern Object select_next_or_previous_editor_component_group(Object);
extern Object select_next_token_menu_choice(Object);
extern Object select_text_region_in_scrap(Object,Object,Object);
extern Object selected_workspace_blackboard_function(Object);
extern Object set_frame_style_of_block(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_token_menu_string_to_display_function(Object,Object);
extern Object set_token_menu_string_to_insert_function(Object,Object);
extern Object set_ui_command_function(Object,Object);
extern Object set_ui_command_pursuer(Object,Object);
extern Object set_ui_command_translator(Object,Object);
extern Object set_up_args_for_move_cursor_handling_shift_variant(Object,Object,Object,Object,Object);
extern Object shift_block(Object,Object,Object);
extern Object should_this_editor_state_scroll_qm(Object);
extern Object show_signature_if_prior_token_has_one(Object);
extern Object shrink_wrap_workspace(Object);
extern Object simplify_associative_list_operation_all_at_once(Object);
extern Object skip_kfep_conversion(void);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object snapshot_command_argument(Object);
extern Object string_equalw(Object,Object);
extern Object stringw(Object);
extern Object subcategoryp(Object,Object);
extern Object subcommand_menu_button_spot_structure_memory_usage(void);
extern Object subtype_p_using_type_descriptions(Object,Object);
extern Object suspend_native_editor(Object);
extern Object syntactically_numeric_substring_p(int,...);
extern Object text_being_edited_may_have_no_value_p(void);
extern Object text_blank_p(Object);
extern Object text_can_be_pasted_in_current_workstation_p(void);
extern Object text_cell_of_table_blackboard_function(Object);
extern Object text_for_item_or_value(Object);
extern Object text_marking_state_structure_memory_usage(void);
extern Object text_plist_blackboard_function(Object);
extern Object text_region_oriented_forward_p(Object);
extern Object text_string_from_current_source(Object,Object);
extern Object text_string_length(Object);
extern Object text_string_matches_current_scrap_p(Object);
extern Object text_string_p(Object);
extern Object text_string_qm_to_insert_from_text_region(Object,Object);
extern Object text_string_search(Object,Object,Object,Object);
extern Object text_string_substring(Object,Object,Object);
extern Object text_to_insert_from_text_cell(Object);
extern Object text_visible_p(Object,Object,Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object token_cons_1(Object,Object);
extern Object token_from_text_string(Object,Object,Object);
extern Object token_list_3(Object,Object,Object);
extern Object token_menu_button_spot_structure_memory_usage(void);
extern Object token_menu_choices_exist_p(void);
extern Object token_menu_string_to_display(Object,Object,Object);
extern Object token_menu_string_to_display_for_entry(int,...);
extern Object token_menu_string_to_insert_qm(Object,Object);
extern Object token_stack_cons_1(Object,Object);
extern Object token_stack_cons_memory_usage(void);
extern Object token_stack_list_2(Object,Object);
extern Object token_stack_list_3(Object,Object,Object);
extern Object token_stack_list_4(Object,Object,Object,Object);
extern Object token_stack_list_trace_hook(Object);
extern Object tokenize_number_from_user(Object,Object,Object);
extern Object transform_image(int,...);
extern Object try_to_conclude_exported_attribute_for_current_edit_state(Object);
extern Object try_to_end_editing(int,...);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_character(Object);
extern Object twrite_data_type(Object);
extern Object twrite_denotation_for_item(Object);
extern Object twrite_edit_backtrace_info(void);
extern Object twrite_general_string(Object);
extern Object twrite_parameter_list(Object);
extern Object twrite_parameter_list_type_field(Object);
extern Object twrite_portion_of_string_unparsably(Object,Object,Object);
extern Object twrite_return_types(Object);
extern Object twrite_signature(Object,Object);
extern Object twrite_symbol(int,...);
extern Object twrite_wide_character(Object);
extern Object type_description_of(Object);
extern Object unconvert_kfep_conversion_text_region(void);
extern Object undo_or_redo_edit(Object);
extern Object undo_or_redo_edit_possible_p(Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object update_all_representations_in_table(Object,Object);
extern Object update_authors_and_time_of_frame_edit(Object,Object);
extern Object update_change_log_attribute(Object,Object,Object);
extern Object update_cyrillic_input_buttons(void);
extern Object update_edit_menus_or_autocomplete_as_appropriate(Object,Object,Object);
extern Object update_edit_operation_subcommands_in_current_editor(void);
extern Object update_hangul_input_buttons(void);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_text_region(int,...);
extern Object use_return_key_as_end_key_in_current_editor_p(void);
extern Object valid_image_plane_p(Object);
extern Object wide_character_member(Object,Object);
extern Object word_delimiting_character_p(Object);
extern Object word_like_sequence_in_text_p(Object,Object,Object,Object,Object,Object);
extern Object word_like_sequence_in_text_region_p(Object);
extern Object workspace_showing_on_ui_client_p(Object);
extern Object workstation_context_specifics_blackboard_function(Object);
extern Object write_attributes_to_edit_using_multiline_editor_from_slot(Object,Object);
extern Object write_class_instance_header_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object x_in_window_blackboard_function(Object);
extern Object y_in_window_blackboard_function(Object);

#else

extern Object abort_current_workstation_context();
extern Object abort_editing_current_workstation_context();
extern Object accept_kfep_conversion();
extern Object add_class_to_environment();
extern Object add_constituent_to_incomplete_phrases();
extern Object add_grammar_rules_for_list();
extern Object add_keymap_to_workstation_context();
extern Object add_parameter_string_to_workspace();
extern Object add_signature_to_workspace();
extern Object add_space_out_text_if_no_lisp();
extern Object add_subblock();
extern Object add_title_of_signature_to_signature_workspace();
extern Object add_to_workspace();
extern Object advance_parsing_for_token();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_long_box();
extern Object allow_continuation_of_editing_context_upon_confirmation();
extern Object alpha_numeric_p();
extern Object argument_list_description_function();
extern Object arrows_usable_for_kfep_conversion_choices_p();
extern Object assemble_parameters_for_built_in_function();
extern Object assemble_parameters_for_foreign_function_declaration();
extern Object assemble_parameters_for_function();
extern Object assemble_parameters_for_method();
extern Object assemble_parameters_for_procedure();
extern Object assemble_parameters_for_remote_procedure_declaration();
extern Object assemble_parameters_for_tabular_function_of_1_arg();
extern Object assq_function();
extern Object attribute_table_p();
extern Object auto_insert_text_from_block();
extern Object auto_insert_text_in_editor();
extern Object backtrace_cons_1();
extern Object blank_p();
extern Object block_of_selection_focus_blackboard_function();
extern Object bracket_open_or_close_qm();
extern Object button_menu_spot_structure_memory_usage();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object cancel_editing();
extern Object category_menu_button_spot_structure_memory_usage();
extern Object cell_of_table_blackboard_function();
extern Object change_color_of_text_box();
extern Object change_edit_box();
extern Object change_edit_box_cursor_position();
extern Object change_frame_description_reference_of_image_plane();
extern Object change_slot_description_value_function();
extern Object change_slot_value();
extern Object change_text_cell_property();
extern Object character_index_blackboard_function();
extern Object character_index_of_source_position();
extern Object character_sequence_token_menu_button_spot_structure_memory_usage();
extern Object check_if_superior_classes_are_defined();
extern Object chestnut_modf_function();
extern Object choose_font_format_per_font_size();
extern Object choose_token_menu_item_format_per_system_tables();
extern Object cleanup_for_edit_workspace();
extern Object clear_optimized_constants();
extern Object clear_text_region_from_edit_box();
extern Object close_signature_window_if_appropriate();
extern Object coerce_text_region_to_scrap();
extern Object collect_subclasses();
extern Object colon_content_p();
extern Object color_or_metacolor_p();
extern Object command_argument_value();
extern Object compile_attributes_to_edit_using_multiline_editor_for_slot();
extern Object compile_for_current_edit_state();
extern Object compile_item_or_datum_or_no_item_attribute_for_slot();
extern Object compute_distance_of_text_line_from_top();
extern Object compute_edit_search_box_location();
extern Object conclude_into_attribute_component();
extern Object conclude_into_virtual_attribute_component();
extern Object confirm_or_cancel();
extern Object constant_queue_next();
extern Object construct_workspace_for_signature();
extern Object continue_edit_after_mouse_watch();
extern Object continue_editing_by_doing_insert_selected_text_command();
extern Object continue_editing_by_posting_cut_copy_paste_menu();
extern Object continuous_spaces_filter_lisp();
extern Object convert_current_menu_choice();
extern Object convert_key_code_to_gensym_character();
extern Object convert_key_code_to_unicode();
extern Object convert_text_region_to_text_string();
extern Object convert_text_to_text_string();
extern Object convert_to_hiragana_if_possible();
extern Object convert_to_katakana_if_possible();
extern Object copy_as_wide_string();
extern Object copy_current_wide_string();
extern Object copy_current_wide_string_possibly_noting_creation();
extern Object copy_for_phrase();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_list_using_gensym_conses_1();
extern Object copy_list_using_grammar_conses_1();
extern Object copy_list_using_token_stack_conses_1();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_out_current_wide_string();
extern Object copy_symbol_name_parsably();
extern Object copy_text();
extern Object copy_text_string();
extern Object copy_tree_using_grammar_conses_1();
extern Object copy_tree_using_token_stack_conses_1();
extern Object count_current_number_of_token_menu_choices();
extern Object create_or_revive_workspace_for_procedure_signature();
extern Object create_search_workspace();
extern Object current_natural_language_for_editor();
extern Object current_punctuation_alist();
extern Object current_workstation_has_pending_events_p();
extern Object decode_procedure_type_field();
extern Object delete_any_text_regions();
extern Object delete_character();
extern Object delete_frame();
extern Object delete_frame_after_checking_serial_number();
extern Object delete_frame_after_checking_serial_number_with_list();
extern Object delete_gensym_element_1();
extern Object delete_image_plane();
extern Object delete_intelligently_from_text_being_edited();
extern Object delete_item();
extern Object delete_subblocks_of_class();
extern Object delete_token_stack_cons_1();
extern Object delete_token_stack_element_1();
extern Object deselect_current_text_region();
extern Object detail_pane();
extern Object determine_appropriate_tokenizer();
extern Object digit_string_overflowed_by_digit_char_lists();
extern Object digit_string_underflowed_by_digit_char_lists();
extern Object direct_structure_method();
extern Object disable_text_region_operation_subcommands_in_current_editor();
extern Object display_editor_notification_1();
extern Object do_copy_and_insert_within_editor();
extern Object do_copy_within_editor();
extern Object do_cut_and_insert_within_editor();
extern Object do_cut_within_editor();
extern Object do_delete_within_editor();
extern Object do_insert_within_editor();
extern Object do_move_within_editor();
extern Object do_paste_within_editor();
extern Object do_trial_kfep_conversion();
extern Object dont_space_before_character_p();
extern Object edit_box_spot_structure_memory_usage();
extern Object edit_context_remains_valid_p();
extern Object edit_state_for_search_p();
extern Object editor_newline();
extern Object editor_post_command_hook();
extern Object empty_text_region_p();
extern Object enable_or_disable_edit_end_and_update_buttons();
extern Object enable_or_disable_radio_button_subcommand();
extern Object enable_or_disable_subcommand();
extern Object encode_current_source_position();
extern Object end_editing();
extern Object enlarge_workspace_if_necessary();
extern Object enter_button_down_context();
extern Object enter_context_in_current_workstation();
extern Object enter_cyrillic_input_mode();
extern Object enter_dialog();
extern Object enter_edit_menu_state();
extern Object enter_editing_context();
extern Object enter_editing_context_1();
extern Object enter_escape_context();
extern Object enter_hangul_input_mode();
extern Object enter_kana_conversion_mode();
extern Object enter_mouse_watch_state();
extern Object enter_subcommand_context();
extern Object enter_text_marking_state();
extern Object erase_any_temporary_information_on_edit_workspace();
extern Object establish_next_workstation_context_continuation();
extern Object event_blackboard_function();
extern Object exclude_editor_prompt_p();
extern Object exit_cyrillic_input_mode();
extern Object exit_editing_context_upon_denial_of_confirmation();
extern Object exit_hangul_input_mode();
extern Object exit_kfep_mode_if_necessary();
extern Object expand_or_shrink_kfep_conversion_text_region();
extern Object extend_current_gensym_string();
extern Object extend_parsing_as_appropriate();
extern Object extend_parsing_or_exit_editor_as_appropriate();
extern Object fill_wide_string_1();
extern Object filter_editor_menus();
extern Object find_base_plane_in_stack_of_coupled_image_planes();
extern Object find_end_of_line_of_text();
extern Object find_end_of_text();
extern Object find_frame_of_class_in_mouse_pointer();
extern Object find_frame_transform_if_any();
extern Object find_image_plane_for_workspace_in_pane();
extern Object find_next_character_if_any();
extern Object find_next_instance_of_search_string();
extern Object find_object_near_workstation_event();
extern Object find_position_adjacent_to_end_of_kfep_conversion_text_region();
extern Object find_position_in_text();
extern Object find_position_in_text_given_image_plane();
extern Object find_previous_character_if_any();
extern Object find_text_tail_for_line();
extern Object finish_parsing_insofar_as_possible();
extern Object first_subblock();
extern Object force_process_drawing();
extern Object frame_blackboard_function();
extern Object frame_has_been_reprocessed_p_function();
extern Object frame_serial_number_setf_helper_1();
extern Object g2_list_insert_at_beginning();
extern Object g2_use_scrolling_editor();
extern Object general_valid_edit_state_p();
extern Object generate_float_vector();
extern Object generate_spot_for_button_menu();
extern Object generate_spot_for_category_menu();
extern Object generate_spot_for_character_sequence_token_menu();
extern Object generate_spot_for_edit_box();
extern Object generate_spot_for_editor_notification();
extern Object generate_spot_for_kfep_conversion_choice_menu();
extern Object generate_spot_for_pathname_component_token_menu();
extern Object generate_spot_for_pure_input_table();
extern Object generate_spot_for_replacement_token_menu();
extern Object generate_spot_for_token_menu();
extern Object generate_text_box_spot();
extern Object generate_workspace_background_spot();
extern Object gensym_cons_1();
extern Object gensym_ksc_code_to_contiguous();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object gensym_list_4();
extern Object get_alias_for_slot_name_if_any();
extern Object get_attribute_description_evaluation_value();
extern Object get_attribute_table_row_alias_string();
extern Object get_built_in_function_argument_names();
extern Object get_category_of_token();
extern Object get_character_index_past_separator();
extern Object get_current_edit_state_parse_if_any();
extern Object get_evaluation_value_for_attribute();
extern Object get_from_g2_text();
extern Object get_gensym_window_parameter();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_menu_content_structure_for_last_token_position();
extern Object get_natural_language_for_editor();
extern Object get_next_text_line();
extern Object get_next_token_from_text_if_available();
extern Object get_or_make_category_for_category_symbol();
extern Object get_or_make_menu_content_structure_for_current_token_position();
extern Object get_primary_name_for_frame_if_any();
extern Object get_property_value_function();
extern Object get_reference_to_item();
extern Object get_selected_edit_cursor_character_index();
extern Object get_selected_edit_cursor_line_index();
extern Object get_selected_text_region_for_edit_box();
extern Object get_slot_component_features();
extern Object get_slot_component_group();
extern Object get_slot_component_value();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_slot_value_compiler_for_current_edit_state_if_any();
extern Object get_slot_value_function();
extern Object get_superior_edit_state_if_any();
extern Object get_symbol_properties_function();
extern Object get_table_cell();
extern Object get_text_region_position();
extern Object get_tokenizer_for_category();
extern Object get_type_of_slot_component_if_any();
extern Object get_type_of_slot_if_any();
extern Object get_ui_command_function();
extern Object get_ui_command_pursuer();
extern Object get_ui_command_translator();
extern Object get_ui_parameter();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object grammar_cons_1();
extern Object handle_character_in_text_event();
extern Object handle_cyrillic_character_in_text_event();
extern Object handle_hangul_character_in_text_event();
extern Object handle_insertion_of_symbol();
extern Object handle_mouse_down_event_in_edit_context();
extern Object handle_parsing_ambiguity();
extern Object handle_parsing_or_compilation_problem();
extern Object handle_spaces_intelligently_p();
extern Object handle_uncompilable_edit_state_result();
extern Object has_text_regions_p();
extern Object highlight_or_unhighlight_attribute();
extern Object highlight_or_unhighlight_cell();
extern Object highlight_or_unhighlight_for_slot();
extern Object highlight_or_unhighlight_selected_token_menu_choice();
extern Object highlight_or_unhighlight_text_box();
extern Object highlight_or_unhighlight_token_menu_text_cell();
extern Object highlight_or_unhighlight_what_is_being_edited();
extern Object home_cursor();
extern Object home_down_cursor();
extern Object image_plane_blackboard_function();
extern Object image_plane_of_selection_focus_blackboard_function();
extern Object in_order_p();
extern Object incomplete_phrases_for_previous_token();
extern Object initialize_digits_of_extremal_fixnum_as_string();
extern Object initialize_digits_of_most_negative_fixnum_as_string();
extern Object initialize_digits_of_most_positive_fixnum_as_string();
extern Object initialize_edit_subcommand_menu();
extern Object initialize_most_fixnum_digits();
extern Object innermost_spot_blackboard_function();
extern Object insert_character_at_cursor_from_outside();
extern Object insert_ellipsis_as_appropriate();
extern Object insert_in_g2_text();
extern Object insert_n_spaces_or_tab();
extern Object insert_text_string_at_cursor();
extern Object insert_text_string_at_cursor_from_outside();
extern Object insert_text_string_in_text_being_edited();
extern Object insert_text_within_editor_from_text_region();
extern Object insert_token_menu_text_cell_text_at_cursor();
extern Object insert_typed_in_character_at_cursor();
extern Object install_current_edit_state_compiled_result();
extern Object instance_of_category_acceptable_p();
extern Object instance_of_token_acceptable_in_current_edit_state_p();
extern Object intercepted_text_p();
extern Object intern_text_string();
extern Object inverse_scalef_function();
extern Object invisible_proprietary_procedure();
extern Object java_editing_category_p();
extern Object kfep_conversion_choice_menu_button_spot_structure_memory_usage();
extern Object ks2_bytes_to_ksc5601();
extern Object ksc_to_gensym_ksc();
extern Object lengthw();
extern Object line_index_blackboard_function();
extern Object line_index_of_source_position();
extern Object list_prefix_p();
extern Object load_and_initialize_type_description();
extern Object lookup_frame_description_reference_of_block_qm();
extern Object lookup_frame_description_reference_of_frame_style();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_box_for_signatures();
extern Object make_button_menu_spot_1();
extern Object make_caption_text_for_edit_workspace();
extern Object make_category_instance_menus();
extern Object make_category_menu_button_spot_1();
extern Object make_category_menu_table();
extern Object make_category_menu_table_row();
extern Object make_character_sequence_token_menu_button_spot_1();
extern Object make_context_description();
extern Object make_description_box();
extern Object make_description_box_with_text();
extern Object make_description_of_barrier_to_destabilization();
extern Object make_edit_box();
extern Object make_edit_box_spot_1();
extern Object make_edit_state_1();
extern Object make_edit_subcommand_menu();
extern Object make_empty_text();
extern Object make_entity();
extern Object make_evaluation_quantity();
extern Object make_format_frame();
extern Object make_frame();
extern Object make_free_text_box();
extern Object make_incomplete_phrase_structure_1();
extern Object make_keymap();
extern Object make_kfep_conversion_choice_menu_button_spot_1();
extern Object make_lost_spaces_text_element();
extern Object make_menu_button_spot_1();
extern Object make_menu_content_structure_for_character_position();
extern Object make_menu_content_structure_for_token_position();
extern Object make_menu_of_names_from_directory();
extern Object make_message();
extern Object make_or_reformat_table();
extern Object make_parameters_from_rpd_arg_description();
extern Object make_partial_command();
extern Object make_pathname_component_token_menu_button_spot_1();
extern Object make_permanent_button_menu_spot_structure_internal();
extern Object make_permanent_category_menu_button_spot_structure_internal();
extern Object make_permanent_character_sequence_token_menu_button_spot_structure_internal();
extern Object make_permanent_edit_box_spot_structure_internal();
extern Object make_permanent_kfep_conversion_choice_menu_button_spot_structure_internal();
extern Object make_permanent_menu_button_spot_structure_internal();
extern Object make_permanent_pathname_component_token_menu_button_spot_structure_internal();
extern Object make_permanent_replacement_token_menu_button_spot_structure_internal();
extern Object make_permanent_subcommand_menu_button_spot_structure_internal();
extern Object make_permanent_text_marking_state_structure_internal();
extern Object make_permanent_token_menu_button_spot_structure_internal();
extern Object make_phrase_rule_completion_1();
extern Object make_position_after_token();
extern Object make_procedure_signature_workspace_entry();
extern Object make_replacement_token_menu_button_spot_1();
extern Object make_runtime_float_for_tokenizer();
extern Object make_runtime_long_for_tokenizer();
extern Object make_sexp_annotation_hash();
extern Object make_slot_value_float();
extern Object make_slot_value_list_1();
extern Object make_slot_value_long();
extern Object make_stringw_function();
extern Object make_subcommand_menu_button_spot_1();
extern Object make_text_cell();
extern Object make_text_cell_plist_for_color_background();
extern Object make_text_marking_state_1();
extern Object make_text_region();
extern Object make_text_representation_for_slot_value_itself();
extern Object make_text_value_using_current_edit_state();
extern Object make_thread_array();
extern Object make_token_menu_button_spot_1();
extern Object make_token_menu_table();
extern Object make_token_stack_list_1();
extern Object make_transient_item();
extern Object make_ui_command();
extern Object make_workspace();
extern Object make_workspace_background_spot_1();
extern Object map_gensym_keyboard_character_to_cyrillic_alternate();
extern Object mark_occurrences_of_string_in_text();
extern Object match_adjacent_symbol_boundary();
extern Object maybe_offer_to_save_incomplete_statement();
extern Object memq_function();
extern Object menu_button_spot_structure_memory_usage();
extern Object mouse_motion_in_text_marking();
extern Object mouse_pointer_blackboard_function();
extern Object mouse_up_in_editing_context();
extern Object mouse_up_in_text_marking();
extern Object move_cursor_by_page_in_editor();
extern Object move_cursor_handling_shift_variant();
extern Object move_down_line();
extern Object move_or_delete_from_cursor();
extern Object move_or_delete_from_cursor_to_next_adjacent_word();
extern Object mutate_global_property();
extern Object native_editor_commands_p();
extern Object native_editor_display_notification();
extern Object native_editor_replace_text();
extern Object native_editor_show_completions();
extern Object native_editor_workspace_p();
extern Object nest_draw_area_for_frame_1();
extern Object new_get_available_image_plane();
extern Object new_get_next_token_from_wide_text_if_available_1();
extern Object newline_p();
extern Object non_menu_choice_permitted_p();
extern Object not_in_kb_loading_editing_context();
extern Object note_change_to_block_1();
extern Object note_kb_state_change_to_slot_by_saving_text();
extern Object note_use_of_managed_float_in_phrase();
extern Object note_use_of_managed_long_in_phrase();
extern Object note_use_of_text_string_in_phrase();
extern Object notify_user();
extern Object nreverse_canonically();
extern Object of_class_p_function();
extern Object offer_to_recompile_items_made_incomplete_if_appropriate();
extern Object offer_to_recompile_now_after_edit();
extern Object old_read_attribute_name_from_text_string();
extern Object outstanding_button_menu_spot_count();
extern Object outstanding_category_menu_button_spot_count();
extern Object outstanding_character_sequence_token_menu_button_spot_count();
extern Object outstanding_edit_box_spot_count();
extern Object outstanding_kfep_conversion_choice_menu_button_spot_count();
extern Object outstanding_menu_button_spot_count();
extern Object outstanding_pathname_component_token_menu_button_spot_count();
extern Object outstanding_replacement_token_menu_button_spot_count();
extern Object outstanding_subcommand_menu_button_spot_count();
extern Object outstanding_text_marking_state_count();
extern Object outstanding_token_menu_button_spot_count();
extern Object outstanding_token_stack_conses();
extern Object parameters_for_token_if_any();
extern Object parameters_for_token_if_any1();
extern Object parse_constant_designation();
extern Object parse_first_var_before_space_or_eof_lisp();
extern Object parse_var_of_class_from_rule_or_gf_text_lisp();
extern Object parsing_context_p_function();
extern Object partial_string_acceptable_p_function();
extern Object paste_from_current_scrap_if_any();
extern Object paste_text_string();
extern Object pathname_component_token_menu_button_spot_structure_memory_usage();
extern Object phrase_cons();
extern Object pick_cell_from_table();
extern Object pop_for_token();
extern Object post_command_menu();
extern Object prefer_native_editor_p();
extern Object procedure_method_name_function();
extern Object procedure_signature_hook();
extern Object procedure_signature_token_hook();
extern Object procedure_signatures_can_be_shown_p();
extern Object process_hfep_output();
extern Object push_for_token();
extern Object push_item_to_end_of_current_localization_domains();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_barrier_on_destabilization_via_editing();
extern Object put_image_on_image_plane();
extern Object put_preferred_editor_where_slot_is_absent();
extern Object put_up_edit_workspace();
extern Object put_up_menus();
extern Object put_up_menus_1();
extern Object put_workspace_on_pane_function();
extern Object raise_image_plane_to_top();
extern Object read_attribute_name_from_text_string_1();
extern Object read_evaluation_quantity_from_text_string();
extern Object read_fixnum_from_string();
extern Object read_float_from_string();
extern Object read_long_from_string();
extern Object read_number_from_text_string();
extern Object read_possibly_out_of_bounds_numeric_token();
extern Object read_symbol_from_text_string();
extern Object reason_for_bad_parse_as_string();
extern Object reason_permanent_items_attribute_is_not_editable();
extern Object reason_permanent_items_module_is_not_editable();
extern Object reclaim_backtrace_list_1();
extern Object reclaim_button_menu_spot_1();
extern Object reclaim_category_menu_button_spot_1();
extern Object reclaim_character_sequence_token_menu_button_spot_1();
extern Object reclaim_edit_box_spot_1();
extern Object reclaim_edit_undo_or_redo_stack();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_grammar_list_1();
extern Object reclaim_grammar_tree_1();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_if_menu_content_structure();
extern Object reclaim_if_position_after_token();
extern Object reclaim_item_and_fsn_list();
extern Object reclaim_items_made_incomplete_list();
extern Object reclaim_kfep_conversion_choice_menu_button_spot_1();
extern Object reclaim_menu_button_spot_1();
extern Object reclaim_menu_content_structure();
extern Object reclaim_menu_content_structure_for_character_position();
extern Object reclaim_pathname_component_token_menu_button_spot_1();
extern Object reclaim_pending_procedure_signature_workspaces();
extern Object reclaim_phrase_rule_completions();
extern Object reclaim_procedure_signature_workspace_entry();
extern Object reclaim_replacement_token_menu_button_spot_1();
extern Object reclaim_simple_text_string();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_structure_if_any();
extern Object reclaim_subcommand_menu_button_spot_1();
extern Object reclaim_text();
extern Object reclaim_text_marking_state_1();
extern Object reclaim_text_string();
extern Object reclaim_token_cons_1();
extern Object reclaim_token_list_1();
extern Object reclaim_token_menu_button_spot_1();
extern Object reclaim_token_stack_cons_1();
extern Object reclaim_token_stack_list_1();
extern Object reclaim_token_stack_list_star_1();
extern Object reclaim_token_stack_tree_1();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_item_made_incomplete_if_appropriate();
extern Object record_items_made_incomplete_and_delete();
extern Object record_procedure_signature_workspace();
extern Object record_system_variable();
extern Object reduce_noting_source_position();
extern Object reformat_text_box_in_place();
extern Object regenerate_optimized_constant();
extern Object release_mouse_pointers();
extern Object remove_any_other_visible_signatures();
extern Object remove_last_item_in_current_localization_domains();
extern Object remove_record_of_procedure_signature_workspace();
extern Object replace_entire_edit_box_text();
extern Object replace_pending_delete_text_region();
extern Object replacement_token_menu_button_spot_structure_memory_usage();
extern Object replenish_grammar_cons_pool();
extern Object replenish_slot_value_cons_pool();
extern Object replenish_token_stack_cons_pool();
extern Object replenish_token_stack_list_pool();
extern Object request_paste_availability_for_editor();
extern Object request_paste_for_editor();
extern Object requeue_workstation_event();
extern Object reset_hangul_input_automaton();
extern Object restrict_destabilization_p();
extern Object resume_native_editor();
extern Object return_from_current_workstation_context();
extern Object return_from_edit_menu();
extern Object return_from_search_in_editor();
extern Object returned_values_description_function();
extern Object run_hfep_automaton();
extern Object run_top_level_event_handler();
extern Object runtime_reclaim_pending_procedure_signature_workspaces();
extern Object scalef_function();
extern Object scroll_line_down();
extern Object scroll_line_up();
extern Object scroll_text_into_view();
extern Object select_current_text_region();
extern Object select_next_or_previous_editor_component_group();
extern Object select_next_token_menu_choice();
extern Object select_text_region_in_scrap();
extern Object selected_workspace_blackboard_function();
extern Object set_frame_style_of_block();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_token_menu_string_to_display_function();
extern Object set_token_menu_string_to_insert_function();
extern Object set_ui_command_function();
extern Object set_ui_command_pursuer();
extern Object set_ui_command_translator();
extern Object set_up_args_for_move_cursor_handling_shift_variant();
extern Object shift_block();
extern Object should_this_editor_state_scroll_qm();
extern Object show_signature_if_prior_token_has_one();
extern Object shrink_wrap_workspace();
extern Object simplify_associative_list_operation_all_at_once();
extern Object skip_kfep_conversion();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object snapshot_command_argument();
extern Object string_equalw();
extern Object stringw();
extern Object subcategoryp();
extern Object subcommand_menu_button_spot_structure_memory_usage();
extern Object subtype_p_using_type_descriptions();
extern Object suspend_native_editor();
extern Object syntactically_numeric_substring_p();
extern Object text_being_edited_may_have_no_value_p();
extern Object text_blank_p();
extern Object text_can_be_pasted_in_current_workstation_p();
extern Object text_cell_of_table_blackboard_function();
extern Object text_for_item_or_value();
extern Object text_marking_state_structure_memory_usage();
extern Object text_plist_blackboard_function();
extern Object text_region_oriented_forward_p();
extern Object text_string_from_current_source();
extern Object text_string_length();
extern Object text_string_matches_current_scrap_p();
extern Object text_string_p();
extern Object text_string_qm_to_insert_from_text_region();
extern Object text_string_search();
extern Object text_string_substring();
extern Object text_to_insert_from_text_cell();
extern Object text_visible_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object token_cons_1();
extern Object token_from_text_string();
extern Object token_list_3();
extern Object token_menu_button_spot_structure_memory_usage();
extern Object token_menu_choices_exist_p();
extern Object token_menu_string_to_display();
extern Object token_menu_string_to_display_for_entry();
extern Object token_menu_string_to_insert_qm();
extern Object token_stack_cons_1();
extern Object token_stack_cons_memory_usage();
extern Object token_stack_list_2();
extern Object token_stack_list_3();
extern Object token_stack_list_4();
extern Object token_stack_list_trace_hook();
extern Object tokenize_number_from_user();
extern Object transform_image();
extern Object try_to_conclude_exported_attribute_for_current_edit_state();
extern Object try_to_end_editing();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_character();
extern Object twrite_data_type();
extern Object twrite_denotation_for_item();
extern Object twrite_edit_backtrace_info();
extern Object twrite_general_string();
extern Object twrite_parameter_list();
extern Object twrite_parameter_list_type_field();
extern Object twrite_portion_of_string_unparsably();
extern Object twrite_return_types();
extern Object twrite_signature();
extern Object twrite_symbol();
extern Object twrite_wide_character();
extern Object type_description_of();
extern Object unconvert_kfep_conversion_text_region();
extern Object undo_or_redo_edit();
extern Object undo_or_redo_edit_possible_p();
extern Object unicode_lowercase_if_uppercase();
extern Object update_all_representations_in_table();
extern Object update_authors_and_time_of_frame_edit();
extern Object update_change_log_attribute();
extern Object update_cyrillic_input_buttons();
extern Object update_edit_menus_or_autocomplete_as_appropriate();
extern Object update_edit_operation_subcommands_in_current_editor();
extern Object update_hangul_input_buttons();
extern Object update_images_of_block();
extern Object update_object_pool_meters_list();
extern Object update_text_region();
extern Object use_return_key_as_end_key_in_current_editor_p();
extern Object valid_image_plane_p();
extern Object wide_character_member();
extern Object word_delimiting_character_p();
extern Object word_like_sequence_in_text_p();
extern Object word_like_sequence_in_text_region_p();
extern Object workspace_showing_on_ui_client_p();
extern Object workstation_context_specifics_blackboard_function();
extern Object write_attributes_to_edit_using_multiline_editor_from_slot();
extern Object write_class_instance_header_from_slot();
extern Object write_symbol_list();
extern Object x_in_window_blackboard_function();
extern Object y_in_window_blackboard_function();

#endif

/* variables/constants */
extern Object Allowable_non_alpha_characters_in_kfep_conversions;
extern Object Attributes_to_edit_using_scrolling_editor;
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_grammar_conses_tail_vector;
extern Object Available_grammar_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_token_stack_conses, Qavailable_token_stack_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_token_stack_conses_tail, Qavailable_token_stack_conses_tail);
extern Object Available_token_stack_conses_tail_vector;
extern Object Available_token_stack_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Button_class_description, Qbutton_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Button_menu_spot_count, Qbutton_menu_spot_count);
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Category_instance_menu_workspace_class_description, Qcategory_instance_menu_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Category_menu_button_spot_count, Qcategory_menu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Category_menu_class_description, Qcategory_menu_class_description);
extern Object Category_symbols_for_symbol_token_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Cell, Qcell);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_button_menu_spots, Qchain_of_available_button_menu_spots);
extern Object Chain_of_available_button_menu_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_category_menu_button_spots, Qchain_of_available_category_menu_button_spots);
extern Object Chain_of_available_category_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_character_sequence_token_menu_button_spots, Qchain_of_available_character_sequence_token_menu_button_spots);
extern Object Chain_of_available_character_sequence_token_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_edit_box_spots, Qchain_of_available_edit_box_spots);
extern Object Chain_of_available_edit_box_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_kfep_conversion_choice_menu_button_spots, Qchain_of_available_kfep_conversion_choice_menu_button_spots);
extern Object Chain_of_available_kfep_conversion_choice_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_menu_button_spots, Qchain_of_available_menu_button_spots);
extern Object Chain_of_available_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_pathname_component_token_menu_button_spots, Qchain_of_available_pathname_component_token_menu_button_spots);
extern Object Chain_of_available_pathname_component_token_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_replacement_token_menu_button_spots, Qchain_of_available_replacement_token_menu_button_spots);
extern Object Chain_of_available_replacement_token_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_subcommand_menu_button_spots, Qchain_of_available_subcommand_menu_button_spots);
extern Object Chain_of_available_subcommand_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_text_marking_states, Qchain_of_available_text_marking_states);
extern Object Chain_of_available_text_marking_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_token_menu_button_spots, Qchain_of_available_token_menu_button_spots);
extern Object Chain_of_available_token_menu_button_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_recycled_edit_states, Qchain_of_recycled_edit_states);
DECLARE_VARIABLE_WITH_SYMBOL(Character_sequence_token_menu_button_spot_count, Qcharacter_sequence_token_menu_button_spot_count);
extern Object Class_description_gkbprop;
extern Object Close_paren_token;
extern Object Close_pending_procedure_signature_workspaces_on_close;
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_denotation_errors_p, Qcollecting_denotation_errors_p);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_character_index_after_token, Qcurrent_character_index_after_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_priority, Qcurrent_drawing_priority);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_workspace, Qcurrent_edit_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_grammar, Qcurrent_grammar);
DECLARE_VARIABLE_WITH_SYMBOL(Current_hfep_c_act, Qcurrent_hfep_c_act);
DECLARE_VARIABLE_WITH_SYMBOL(Current_hfep_c_state, Qcurrent_hfep_c_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_hfep_cchar, Qcurrent_hfep_cchar);
DECLARE_VARIABLE_WITH_SYMBOL(Current_hfep_nchar, Qcurrent_hfep_nchar);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_symbol_token, Qcurrent_indicator_for_category_of_symbol_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_this_name, Qcurrent_indicator_for_category_of_this_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_serial_number, Qcurrent_kb_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_line_index_for_end_of_token, Qcurrent_line_index_for_end_of_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_event, Qcurrent_workstation_event);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
extern Object Default_tokenizer;
DECLARE_VARIABLE_WITH_SYMBOL(Denotation_error_list, Qdenotation_error_list);
extern Object Deselect_text_region_after_copy_p;
DECLARE_VARIABLE_WITH_SYMBOL(Digits_of_extremal_fixnum_as_string, Qdigits_of_extremal_fixnum_as_string);
DECLARE_VARIABLE_WITH_SYMBOL(Digits_of_largest_float_as_string, Qdigits_of_largest_float_as_string);
DECLARE_VARIABLE_WITH_SYMBOL(Digits_of_most_negative_fixnum_as_string, Qdigits_of_most_negative_fixnum_as_string);
DECLARE_VARIABLE_WITH_SYMBOL(Digits_of_most_positive_fixnum_as_string, Qdigits_of_most_positive_fixnum_as_string);
DECLARE_VARIABLE_WITH_SYMBOL(Digits_of_smallest_normalized_float_as_string, Qdigits_of_smallest_normalized_float_as_string);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_parameter_strings_for_internal_proprietary_procedures, Qdisable_parameter_strings_for_internal_proprietary_procedures);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_is_locked_qm, Qdrawing_is_locked_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Edit_box_class_description, Qedit_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Edit_box_spot_count, Qedit_box_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_background_color_override_qm, Qeditor_background_color_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_caption_text_override_qm, Qeditor_caption_text_override_qm);
extern Object Editor_command_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Editor_font_size_override_qm, Qeditor_font_size_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_frame_style_override_qm, Qeditor_frame_style_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_initial_editor_height_override_qm, Qeditor_initial_editor_height_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_prompt_filter_qm, Qeditor_prompt_filter_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_scroll_decision_override_qm, Qeditor_scroll_decision_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_specific_natural_language_override_qm, Qeditor_specific_natural_language_override_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_text_color_override_qm, Qeditor_text_color_override_qm);
extern Object Ellipsis_text_string;
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fonts, Qfonts);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Foreign_function_declaration_class_description, Qforeign_function_declaration_class_description);
extern Object Frame_or_frames_with_this_name_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Function_definition_class_description, Qfunction_definition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_load_kb_tokenizer, Qg2_load_kb_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(G2_operating_system, Qg2_operating_system);
DECLARE_VARIABLE_WITH_SYMBOL(G2_simple_tokenizer, Qg2_simple_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(G2_standard_tokenizer, Qg2_standard_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(G2_symbol_tokenizer, Qg2_symbol_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(Generate_source_annotation_info, Qgenerate_source_annotation_info);
extern Object Global_grammar;
DECLARE_VARIABLE_WITH_SYMBOL(Icon_cell_class_description, Qicon_cell_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_editor_workspace_class_description, Qicon_editor_workspace_class_description);
#define Icp_window_protocol_supports_native_cut_and_paste FIX((SI_Long)19L)
#define Icp_window_protocol_supports_request_for_paste_availability FIX((SI_Long)20L)
DECLARE_VARIABLE_WITH_SYMBOL(In_recompile_item_p, Qin_recompile_item_p);
DECLARE_VARIABLE_WITH_SYMBOL(Incomplete_phrases_at_frontier, Qincomplete_phrases_at_frontier);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inspect_command_class_description, Qinspect_command_class_description);
extern Object Instances_specific_to_this_class_kbprop;
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Items_made_incomplete, Qitems_made_incomplete);
DECLARE_VARIABLE_WITH_SYMBOL(Items_made_incomplete_were_recorded_qm, Qitems_made_incomplete_were_recorded_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Java_tokenizer, Qjava_tokenizer);
DECLARE_VARIABLE_WITH_SYMBOL(Keep_edit_workspace_hidden_no_matter_what_qm, Qkeep_edit_workspace_hidden_no_matter_what_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Key_cap_to_gensym_cyrillic_character_code_map, Qkey_cap_to_gensym_cyrillic_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_conversion_choice_menu_button_spot_count, Qkfep_conversion_choice_menu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Kfep_conversion_choice_menu_class_description, Qkfep_conversion_choice_menu_class_description);
extern Object Ks_c_5601_to_unicode_map;
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Localization_context, Qlocalization_context);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
extern Object Maximum_proglem_length_to_show_in_the_editor;
extern Object Maximum_text_box_width_or_height;
DECLARE_VARIABLE_WITH_SYMBOL(Menu_button_spot_count, Qmenu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Menu_parameters, Qmenu_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Message_class_description, Qmessage_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Method_declaration_class_description, Qmethod_declaration_class_description);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Most_fixnum_digits, Qmost_fixnum_digits);
DECLARE_VARIABLE_WITH_SYMBOL(Most_lefthand_float_digits, Qmost_lefthand_float_digits);
DECLARE_VARIABLE_WITH_SYMBOL(Most_righthand_float_zeros, Qmost_righthand_float_zeros);
DECLARE_VARIABLE_WITH_SYMBOL(Name_box_class_description, Qname_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Name_of_current_editor_command_qm, Qname_of_current_editor_command_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Native_editor_already_updated, Qnative_editor_already_updated);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Open_paren_token;
DECLARE_VARIABLE_WITH_SYMBOL(Operation_around_record_of_items_made_incomplete, Qoperation_around_record_of_items_made_incomplete);
DECLARE_VARIABLE_WITH_SYMBOL(Override_preferred_editor, Qoverride_preferred_editor);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_component_token_menu_button_spot_count, Qpathname_component_token_menu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Phrase_copying_needs_annotation_rehashing, Qphrase_copying_needs_annotation_rehashing);
extern Object Plus_missing_argument_plus;
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
extern Object Punctuation_alist;
DECLARE_VARIABLE_WITH_SYMBOL(Recording_items_made_incomplete_qm, Qrecording_items_made_incomplete_qm);
extern Object Relative_horizontal_displacement_for_search_workspace;
extern Object Relative_vertical_displacement_for_search_workspace;
DECLARE_VARIABLE_WITH_SYMBOL(Remote_procedure_declaration_class_description, Qremote_procedure_declaration_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Replacement_token_menu_button_spot_count, Qreplacement_token_menu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Scrap_class_description, Qscrap_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Shift_variant_for_cursor_movement_p, Qshift_variant_for_cursor_movement_p);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Subcommand_menu_button_spot_count, Qsubcommand_menu_button_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_scrolling_into_view_global_flag_qm, Qsuppress_scrolling_into_view_global_flag_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Table_class_description, Qtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Tabular_function_of_1_arg_class_description, Qtabular_function_of_1_arg_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Text_box_class_description, Qtext_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Text_marking_state_count, Qtext_marking_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Text_of_definition_being_compiled, Qtext_of_definition_being_compiled);
DECLARE_VARIABLE_WITH_SYMBOL(Text_region_class_description, Qtext_region_class_description);
extern Object The_type_description_of_button_menu_spot;
extern Object The_type_description_of_category_menu_button_spot;
extern Object The_type_description_of_character_sequence_token_menu_button_spot;
extern Object The_type_description_of_edit_box_spot;
extern Object The_type_description_of_edit_state;
extern Object The_type_description_of_kfep_conversion_choice_menu_button_spot;
extern Object The_type_description_of_menu_button_spot;
extern Object The_type_description_of_pathname_component_token_menu_button_spot;
extern Object The_type_description_of_replacement_token_menu_button_spot;
extern Object The_type_description_of_subcommand_menu_button_spot;
extern Object The_type_description_of_text_marking_state;
extern Object The_type_description_of_token_menu_button_spot;
DECLARE_VARIABLE_WITH_SYMBOL(Token_menu_button_spot_count, Qtoken_menu_button_spot_count);
extern Object Token_menu_string_to_display_function_prop;
extern Object Token_menu_string_to_insert_function_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Token_stack_cons_counter, Qtoken_stack_cons_counter);
extern Object Token_stack_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Tokenize_with_editing_context_p, Qtokenize_with_editing_context_p);
extern Object Tokenizer_for_category_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_in_box_class_description, Qtype_in_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
#define Unicode_bit FIX((SI_Long)16777216L)
#define Use_full_size_of_with_output_wide_string_cutoff FIX((SI_Long)256L)
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
#define Wide_string_list_maximum_length FIX((SI_Long)1024L)
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
