/* evt.h -- Header File for evt.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qnum_eq;
extern Object Qand;
extern Object Qcond;
extern Object Qdo;
extern Object Qeq;
extern Object Qfirst;
extern Object Qfloat;
extern Object Qforce_output;
extern Object Qgo;
extern Object Qinteger;
extern Object Qlength;
extern Object Qnot;
extern Object Qnreverse;
extern Object Qnull;
extern Object Qnumber;
extern Object Qquote;
extern Object Qreturn;
extern Object Qsequence;
extern Object Qsetf;
extern Object Qsetq;
extern Object Qsymbol;
extern Object Qsymbolp;
extern Object Qtype;
extern Object Qunless;
extern Object Qwhen;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_variable_data_to_gesture(Object,Object,Object,Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object allocate_managed_simple_vector(Object);
extern Object assemble_gesture_code_sequence(Object,Object);
extern Object assq_function(Object,Object);
extern Object bytes_per_simple_vector(Object);
extern Object call_primitive_gesture(Object,Object,Object);
extern Object clear_optimized_constants(void);
extern Object compute_effective_gesture_method(Object,Object,Object);
extern Object compute_effective_gesture_method_of_class_description(Object,Object,Object);
extern Object constant_symbol_value_node_of_symbol_p(Object,Object);
extern Object copy_gesture_local(Object);
extern Object copy_if_evaluation_value_1(Object);
extern Object copy_tree_using_gensym_conses_1(Object);
extern Object direct_structure_method(Object,Object);
extern Object do_not_put_slot_in_attribute_tables_p(int,...);
extern Object emit_compiled_gesture(Object);
extern Object emit_compiled_gesture_expression(Object);
extern Object emit_compiled_gesture_statement(Object,Object);
extern Object emit_gesture_instruction_with_constants(Object,Object);
extern Object emit_primitive_gesture_value_node(Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_sequence_aref(Object,Object);
extern Object evaluation_sequence_insert_at_beginning(Object,Object);
extern Object evaluation_sequence_insert_at_end(Object,Object);
extern Object evaluation_sequence_remove_element_at_index(Object,Object);
extern Object evaluation_sequence_without_elements(Object,Object,Object);
extern Object evaluation_value_eq(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gesture_function_structure_memory_usage(void);
extern Object gesture_local_structure_memory_usage(void);
extern Object gesture_locals_match_p(Object,Object);
extern Object gesture_thread_structure_memory_usage(void);
extern Object gesture_value_runtime_subtype_p(Object,Object);
extern Object get_cast_operator(Object,Object);
extern Object get_gesture_local_by_index(Object,Object);
extern Object get_instruction_for_gesture_value_node(Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object make_gesture_function_1(void);
extern Object make_gesture_local_1(Object,Object,Object);
extern Object make_gesture_thread_1(void);
extern Object make_gesture_value_node(Object,Object,Object);
extern Object make_permanent_gesture_function_structure_internal(void);
extern Object make_permanent_gesture_local_structure_internal(void);
extern Object make_permanent_gesture_thread_structure_internal(void);
extern Object make_thread_array(Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object new_gesture_code_sequence(void);
extern Object new_gesture_local(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_dependent_frame_1(void);
extern Object outstanding_gesture_function_count(void);
extern Object outstanding_gesture_local_count(void);
extern Object outstanding_gesture_thread_count(void);
extern Object phrase_cons(Object,Object);
extern Object primitive_gesture_value_node_p(Object);
extern Object push_optimized_constant(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_gesture_function(Object);
extern Object reclaim_gesture_function_internal_1(Object);
extern Object reclaim_gesture_local_1(Object);
extern Object reclaim_gesture_thread_1(Object);
extern Object reclaim_managed_simple_vector(Object);
extern Object reclaim_slot_value(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_slot_value_cons_pool(void);
extern Object resolve_gesture_local_variable(Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_slot_description_value_without_noting(Object,Object,Object);
extern Object tw_change_slot_description_value(Object,Object,Object,Object,Object);
extern Object tw_method_is_congruent_to_declaration_p(Object,Object);
extern Object tw_put_attribute_description_value(Object,Object,Object,Object);
extern Object type_specification_subtype_in_kb_p(Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object write_evaluation_value(int,...);
extern Object write_gesture_code_instruction(Object,Object);

#else

extern Object add_variable_data_to_gesture();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object allocate_managed_simple_vector();
extern Object assemble_gesture_code_sequence();
extern Object assq_function();
extern Object bytes_per_simple_vector();
extern Object call_primitive_gesture();
extern Object clear_optimized_constants();
extern Object compute_effective_gesture_method();
extern Object compute_effective_gesture_method_of_class_description();
extern Object constant_symbol_value_node_of_symbol_p();
extern Object copy_gesture_local();
extern Object copy_if_evaluation_value_1();
extern Object copy_tree_using_gensym_conses_1();
extern Object direct_structure_method();
extern Object do_not_put_slot_in_attribute_tables_p();
extern Object emit_compiled_gesture();
extern Object emit_compiled_gesture_expression();
extern Object emit_compiled_gesture_statement();
extern Object emit_gesture_instruction_with_constants();
extern Object emit_primitive_gesture_value_node();
extern Object eval_cons_1();
extern Object evaluation_sequence_aref();
extern Object evaluation_sequence_insert_at_beginning();
extern Object evaluation_sequence_insert_at_end();
extern Object evaluation_sequence_remove_element_at_index();
extern Object evaluation_sequence_without_elements();
extern Object evaluation_value_eq();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object gesture_function_structure_memory_usage();
extern Object gesture_local_structure_memory_usage();
extern Object gesture_locals_match_p();
extern Object gesture_thread_structure_memory_usage();
extern Object gesture_value_runtime_subtype_p();
extern Object get_cast_operator();
extern Object get_gesture_local_by_index();
extern Object get_instruction_for_gesture_value_node();
extern Object get_lookup_slot_value_given_default();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object getfq_function_no_default();
extern Object load_and_initialize_type_description();
extern Object make_gesture_function_1();
extern Object make_gesture_local_1();
extern Object make_gesture_thread_1();
extern Object make_gesture_value_node();
extern Object make_permanent_gesture_function_structure_internal();
extern Object make_permanent_gesture_local_structure_internal();
extern Object make_permanent_gesture_thread_structure_internal();
extern Object make_thread_array();
extern Object memq_function();
extern Object mutate_global_property();
extern Object new_gesture_code_sequence();
extern Object new_gesture_local();
extern Object note_change_to_block_1();
extern Object note_change_to_dependent_frame_1();
extern Object outstanding_gesture_function_count();
extern Object outstanding_gesture_local_count();
extern Object outstanding_gesture_thread_count();
extern Object phrase_cons();
extern Object primitive_gesture_value_node_p();
extern Object push_optimized_constant();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_gesture_function();
extern Object reclaim_gesture_function_internal_1();
extern Object reclaim_gesture_local_1();
extern Object reclaim_gesture_thread_1();
extern Object reclaim_managed_simple_vector();
extern Object reclaim_slot_value();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_slot_value_cons_pool();
extern Object resolve_gesture_local_variable();
extern Object set_non_savable_lookup_slot_value();
extern Object set_slot_description_value_without_noting();
extern Object tw_change_slot_description_value();
extern Object tw_method_is_congruent_to_declaration_p();
extern Object tw_put_attribute_description_value();
extern Object type_specification_subtype_in_kb_p();
extern Object update_object_pool_meters_list();
extern Object validate_item_or_evaluation_value();
extern Object write_evaluation_value();
extern Object write_gesture_code_instruction();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_gesture_instruction_names, Qall_gesture_instruction_names);
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
extern Object Catch_frame;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gesture_functions, Qchain_of_available_gesture_functions);
extern Object Chain_of_available_gesture_functions_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gesture_locals, Qchain_of_available_gesture_locals);
extern Object Chain_of_available_gesture_locals_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gesture_threads, Qchain_of_available_gesture_threads);
extern Object Chain_of_available_gesture_threads_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_code_sequence, Qcurrent_gesture_code_sequence);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_code_sequences, Qcurrent_gesture_code_sequences);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_frame_pointer, Qcurrent_gesture_frame_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_label_index, Qcurrent_gesture_label_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_sequence_index, Qcurrent_gesture_sequence_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gesture_stack_pointer, Qcurrent_gesture_stack_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
extern Object Frame_gesture_offset;
extern Object Frame_header_size;
extern Object Frame_pc_offset;
extern Object Frame_previous_offset;
extern Object Frame_type_offset;
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_function_count, Qgesture_function_count);
extern Object Gesture_function_prop;
extern Object Gesture_instruction_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_local_count, Qgesture_local_count);
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_source_recording_p, Qgesture_source_recording_p);
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_source_stack, Qgesture_source_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_thread_count, Qgesture_thread_count);
DECLARE_VARIABLE_WITH_SYMBOL(Gesture_unbound_value, Qgesture_unbound_value);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object No_previous_frame;
extern Object Normal_frame;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Obsolete_gesture_instruction_map;
extern Object Per_call_stack_slop;
extern Object Protected_frame;
DECLARE_VARIABLE_WITH_SYMBOL(Secret_return_value, Qsecret_return_value);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object The_type_description_of_gesture_function;
extern Object The_type_description_of_gesture_local;
extern Object The_type_description_of_gesture_thread;
DECLARE_VARIABLE_WITH_SYMBOL(Tracing_in_events_modules_p, Qtracing_in_events_modules_p);
DECLARE_VARIABLE_WITH_SYMBOL(Tw_evaluate_trace_level, Qtw_evaluate_trace_level);
extern Object Tw_predefined_user_attributes;
DECLARE_VARIABLE_WITH_SYMBOL(Tw_source_debug_p, Qtw_source_debug_p);
