/* fclts.h -- Header File for fclts.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qnum_lt;
extern Object Kabort;
extern Object Qblock;
extern Object Qdelete;
extern Object Qeq;
extern Object Qlog;
extern Object Qquote;
extern Object Qset;
extern Object Ktest;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object act_on_choice_of_a_button(Object,Object,Object,Object);
extern Object act_on_choice_of_a_chart(Object,Object,Object,Object);
extern Object act_on_choice_of_a_dial(Object,Object,Object,Object);
extern Object act_on_choice_of_a_entity(Object,Object,Object,Object);
extern Object act_on_choice_of_a_freeform_table(Object,Object,Object,Object);
extern Object act_on_choice_of_a_graph(Object,Object,Object,Object);
extern Object act_on_choice_of_a_message(Object,Object,Object,Object);
extern Object act_on_choice_of_a_meter(Object,Object,Object,Object);
extern Object act_on_choice_of_a_readout_table(Object,Object,Object,Object);
extern Object act_on_choice_of_a_text_box(Object,Object,Object,Object);
extern Object act_on_choice_of_a_trend_chart(Object,Object,Object,Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_intercepted_token_to_text(Object);
extern Object add_keymap_to_workstation_context(Object,Object);
extern Object add_subworkspace(Object,Object);
extern Object add_subworkspace_connection_posts(Object,Object);
extern Object add_to_workspace(int,...);
extern Object align_blocks(Object,Object);
extern Object align_for_operate_on_area(Object);
extern Object allocate_byte_vector_16(Object);
extern Object block_may_be_deleted_without_prompting_p(Object);
extern Object bounding_box_spot_structure_memory_usage(void);
extern Object bounding_state_structure_memory_usage(void);
extern Object bytes_per_simple_vector(Object);
extern Object c_get_places_bar(Object,Object);
extern Object c_get_system_drives_list(Object,Object);
extern Object c_get_system_special_folders(Object,Object);
extern Object change_edges_of_block(Object,Object,Object,Object,Object);
extern Object change_size_of_chart(Object,Object,Object,Object,Object);
extern Object change_size_of_graph(Object,Object,Object,Object,Object);
extern Object change_size_of_trend_chart(Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle(int,...);
extern Object change_size_per_bounding_rectangle_for_action_button(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_block(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_chart(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_connection(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_entity(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_graph(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_kb_workspace(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_text_box(Object,Object,Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle_for_trend_chart(Object,Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object change_text_box_property(Object,Object,Object);
extern Object change_workspace_edges_after_including_margin(Object,Object,Object,Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object check_savability_of_kb_in_terms_of_modularity(int,...);
extern Object choose_font_format_per_fonts_table(Object,Object);
extern Object classic_handle_file_related_window_menu_choice(Object);
extern Object clear_optimized_constants(void);
extern Object clone_area(void);
extern Object clone_blocks(Object);
extern Object clone_connections_for_block(Object,Object,Object);
extern Object clone_frame(int,...);
extern Object coerce_to_directory_string(Object);
extern Object collect_subclasses(Object);
extern Object compile_color_set_spec_for_slot(int,...);
extern Object compute_list_of_modules_putting_top_in_front(void);
extern Object compute_module_deletion_choices(void);
extern Object compute_pathname_filter_for_file_type(int,...);
extern Object constant_queue_next(Object,Object);
extern Object convert_text_string_to_text(Object);
extern Object convert_to_magnification(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_gensym_tree_with_text_strings(Object);
extern Object copy_list_using_gensym_conses_1(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_text(Object);
extern Object copy_text_string(Object);
extern Object copy_wide_string(Object);
extern Object count_instances_of_g2gl_process(Object);
extern Object current_kb_directory_qm(void);
extern Object default_interesting_directories(void);
extern Object delete_area(void);
extern Object delete_block_for_user(int,...);
extern Object delete_blocks_for_operate_on_area_after_confirmation(Object);
extern Object delete_blocks_for_operate_on_area_upon_confirmation(Object);
extern Object delete_connection_to_stub(Object);
extern Object delete_connections_of_block_not_within_area_of_workspace(Object,Object,Object,Object,Object);
extern Object delete_connections_of_blocks_within_area(Object,Object,Object,Object,Object);
extern Object delete_frame(Object);
extern Object delete_frame_after_checking_serial_number(Object,Object);
extern Object delete_hand_created_module_information_if_appropriate(Object);
extern Object delete_item_from_list_and_reclaim_cons_cells(Object,Object,Object,Object);
extern Object delete_workspace_for_user(int,...);
extern Object describe_restrictions_on_temporary_workspace(Object,Object);
extern Object destabilizing_item_deletion_p(Object);
extern Object detail_pane(Object);
extern Object dial_spot_structure_memory_usage(void);
extern Object dialog_message_string_for_delete_block(Object);
extern Object direct_structure_method(Object,Object);
extern Object display_table_p(Object);
extern Object distribute_blocks(Object,Object);
extern Object do_addition_of_optional_subtable_from_menu(Object,Object,Object,Object,Object,Object,Object);
extern Object double_nul_string_to_list(Object);
extern Object dragging_cons_function(Object,Object);
extern Object encode_pathname_os(Object);
extern Object end_icp_message_group(void);
extern Object enlarge_workspace_for_block_rectangle_if_necessary(Object,Object);
extern Object enter_bounding_dialog(int,...);
extern Object enter_button_down_context(Object,Object);
extern Object enter_close_box_widget_pending_context(Object,Object);
extern Object enter_context_in_current_workstation(int,...);
extern Object enter_dialog(int,...);
extern Object enter_editing_context(int,...);
extern Object enter_image_plane_dragging_context(int,...);
extern Object enter_keys_in_bounding_state(Object);
extern Object enter_min_sizing_dialog(Object,Object,Object,Object);
extern Object enter_move_dragging_context(int,...);
extern Object enter_sizing_dialog(Object,Object,Object,Object);
extern Object enter_text_editor_on_text_cell(int,...);
extern Object enter_transfer_dragging_context(int,...);
extern Object establish_next_workstation_context_continuation(Object,Object,Object,Object);
extern Object execute_command_on_return(Object);
extern Object exit_current_workstation_context_in_return_function(Object);
extern Object find_frame_of_class_in_mouse_pointer(Object,Object);
extern Object find_image_plane_showing_workspace(Object);
extern Object find_position_in_text_given_image_plane(int,...);
extern Object finish_parsing_insofar_as_possible(void);
extern Object fit_bounding_box_around_block(Object,Object,Object);
extern Object fit_entity_around_text_box_or_bounding_rectangle(Object,Object,Object,Object,Object,Object);
extern Object fix_up_bounding_state_if_necessary_after_transfer(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object g2_abort_callback_userdefine(Object);
extern Object g2_get_invalid_workspace_to_handle(void);
extern Object g2_more_invalid_workspaces_to_be_handled(void);
extern Object g2_register_workspace_invalidation_handling_procedure(Object);
extern Object generate_spot_for_bounding_box(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_file_as_directory(Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_parse_namestring_function(Object,Object,Object);
extern Object get_block_at_other_end_of_connection(Object,Object);
extern Object get_gensym_environment_variable(Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_pathname_for_file_command(Object,Object,Object,Object);
extern Object get_property_value_function(int,...);
extern Object get_raw_network_info(void);
extern Object get_saving_parameters(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_init_form(int,...);
extern Object get_slot_represented_by_text_cell_if_any(Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_table_cell_edges(Object,Object);
extern Object get_text_to_edit_from_text_cell(Object);
extern Object get_total_title_bar_text_width(Object);
extern Object get_ui_parameter(int,...);
extern Object get_workspace(Object);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object go_to_maybe_newly_created_subworkspace(Object,Object);
extern Object goto_frame_instance(Object);
extern Object hand_place_on_return(Object);
extern Object hand_place_on_return_move_style(Object);
extern Object handle_command(Object,Object);
extern Object handle_create_new_module_window_menu_choice(Object,Object);
extern Object handle_file_command(int,...);
extern Object handle_file_related_window_menu_choice(Object);
extern Object handle_inspect_command(int,...);
extern Object has_only_one_subblock_p(Object);
extern Object heuristic_maximum_edge(Object,Object,Object);
extern Object highlight_or_unhighlight_button(Object,Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_of_workspace(Object);
extern Object in_block_p(Object,Object,Object);
extern Object in_order_p(Object);
extern Object include_yes_no_menu_choice_p(Object);
extern Object incomplete_box_translation_and_text_p(Object);
extern Object instantiated_class_p(Object);
extern Object interesting_directories(void);
extern Object inverse_scalef_function(Object,Object);
extern Object invoke_workspace_invalidation_handler_if_any(Object,Object);
extern Object item_deletion_causes_workspace_deletion_p(Object);
extern Object list_blocks_within_area_of_workspace(Object,Object,Object,Object,Object,Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object magnify_icon(Object,Object,Object,Object,Object,Object);
extern Object make_and_set_up_kb_load_file_command(Object);
extern Object make_bounding_box(Object,Object);
extern Object make_bounding_box_spot_1(void);
extern Object make_bounding_state_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_button(int,...);
extern Object make_command_frame(int,...);
extern Object make_context_description(Object,Object,Object,Object);
extern Object make_dial(Object);
extern Object make_dial_spot_1(void);
extern Object make_dialog_message(Object);
extern Object make_empty_text(void);
extern Object make_entity(int,...);
extern Object make_evaluation_truth_value_function(Object);
extern Object make_format_frame(Object);
extern Object make_frame(Object);
extern Object make_free_text_box(int,...);
extern Object make_graph(Object);
extern Object make_incomplete_box_translation_and_text(void);
extern Object make_keymap(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_lost_spaces_text_element(Object);
extern Object make_message(int,...);
extern Object make_meter(Object);
extern Object make_meter_or_dial_spot_1(void);
extern Object make_meter_spot_1(void);
extern Object make_new_top_level_kb_workspace(int,...);
extern Object make_or_reformat_table(int,...);
extern Object make_permanent_bounding_box_spot_structure_internal(void);
extern Object make_permanent_bounding_state_structure_internal(void);
extern Object make_permanent_dial_spot_structure_internal(void);
extern Object make_permanent_meter_or_dial_spot_structure_internal(void);
extern Object make_permanent_meter_spot_structure_internal(void);
extern Object make_readout_table(Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_system_frame(Object);
extern Object make_table_describing_restrictions(Object);
extern Object make_text_box(Object);
extern Object make_text_cell(int,...);
extern Object make_text_cell_plist_for_color_background(Object);
extern Object make_text_representation_for_slot_value(int,...);
extern Object make_thread_array(Object);
extern Object make_trend_chart(Object);
extern Object make_workspace(int,...);
extern Object manifest_item_creation(Object,Object,Object,Object);
extern Object map_to_black_or_white(Object);
extern Object map_to_color_value_1(Object);
extern Object memq_function(Object,Object);
extern Object meter_or_dial_spot_structure_memory_usage(void);
extern Object meter_spot_structure_memory_usage(void);
extern Object midline_x_of_block_function(Object);
extern Object midline_y_of_block_function(Object);
extern Object module_contains_text_stripped_frames_p(Object);
extern Object mouse_down_on_close_box_widget_in_bounding_state(Object);
extern Object mouse_down_on_image_plane_in_bounding_state(Object);
extern Object mouse_motion_in_bounding_state(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object mouse_up_in_bounding_state(Object);
extern Object move_area(void);
extern Object move_area_to_bottom(void);
extern Object move_area_to_l_r_center(void);
extern Object move_area_to_left(void);
extern Object move_area_to_right(void);
extern Object move_area_to_t_b_center(void);
extern Object move_area_to_top(void);
extern Object move_blocks_with_their_external_connections(Object,Object,Object,Object);
extern Object move_image_plane(Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object name_for_frame_p(Object,Object);
extern Object native_file_dialog_p(Object);
extern Object native_handle_file_related_window_menu_choice(Object);
extern Object native_simple_dialogs_p(Object);
extern Object neatly_stack_image_planes_in_pane(int,...);
extern Object neatly_stack_image_planes_in_window(Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object notify_user(int,...);
extern Object obtain_simple_text_string(Object);
extern Object obtain_text_string(Object);
extern Object operate_on_area_of_workspace(Object,Object,Object,Object);
extern Object os_pathname_nondirectory(Object,Object);
extern Object outstanding_bounding_box_spot_count(void);
extern Object outstanding_bounding_state_count(void);
extern Object outstanding_dial_spot_count(void);
extern Object outstanding_meter_or_dial_spot_count(void);
extern Object outstanding_meter_spot_count(void);
extern Object post_file_dialog(int,...);
extern Object post_native_file_dialog(Object,Object,Object,Object,Object,Object,Object);
extern Object post_simple_dialog(Object,Object,Object,Object,Object,Object,Object);
extern Object preflight_file_related_window_menu_choice(Object);
extern Object prepare_blocks_for_operation_on_area(int,...);
extern Object problem_item_in_limbo_p(Object);
extern Object push_back_mouse_motion_event(void);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_colors_on_1st_level_color_menu(Object,Object,Object);
extern Object put_colors_on_2nd_level_color_menu(Object,Object,Object);
extern Object put_do_not_dismiss_color_menu_after_choosing_qm_where_slot_is_absent(Object,Object);
extern Object put_up_attributes_table(int,...);
extern Object put_up_table_of_network_info(void);
extern Object put_workspace_on_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object reclaim_bounding_box_spot_1(Object);
extern Object reclaim_bounding_state_1(Object);
extern Object reclaim_dial_spot_1(Object);
extern Object reclaim_dragging_list_function(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_tree_with_text_strings(Object);
extern Object reclaim_hand_placement_return_information(Object);
extern Object reclaim_meter_or_dial_spot_1(Object);
extern Object reclaim_meter_spot_1(Object);
extern Object reclaim_move_style_hand_placement_return_information(Object);
extern Object reclaim_raw_network_info(Object,Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_structure_if_any(Object);
extern Object reclaim_text(Object);
extern Object reclaim_text_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reformat_table_in_place(int,...);
extern Object reformat_text_box_in_place(int,...);
extern Object regenerate_optimized_constant(Object);
extern Object release_mouse_pointers(Object);
extern Object remove_as_subblock_if_necessary(int,...);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_slot_value_cons_pool(void);
extern Object requeue_event_and_abort_workstation_context(Object);
extern Object restore_chart_to_normal_size(Object);
extern Object restore_graph_to_normal_size(Object);
extern Object restore_item_to_normal_size(Object);
extern Object restore_size_of_text_box(Object);
extern Object restore_trend_chart_to_normal_size(Object);
extern Object return_from_current_workstation_context(int,...);
extern Object rotated_by_90_p(Object);
extern Object scalef_function(Object,Object);
extern Object scope_cons(Object,Object);
extern Object secure_icp_string(int,...);
extern Object select_edge_or_corner_of_bounding_box(int,...);
extern Object send_icp_file_dialog(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_file_dialog_ex(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_simple_dialog(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_simple_dialog_ex(Object,Object,Object,Object,Object,Object);
extern Object send_ws_representations_item_moved(Object,Object,Object);
extern Object send_ws_representations_item_virtual_attribute_change(Object,Object,Object);
extern Object server_and_client_share_file_system_p(Object);
extern Object set_cursor_position(Object,Object);
extern Object set_edges_of_block(Object,Object,Object,Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_neither_permanent_nor_transient_and_propagate(Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_up_bounding_dialog_ws(int,...);
extern Object shift_block(Object,Object,Object);
extern Object shrink_wrap_workspace(Object);
extern Object sizing_no_minimum(void);
extern Object sizing_ok(void);
extern Object sizing_quit(void);
extern Object sizing_restore(void);
extern Object sizing_update(void);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object sort_list(Object,Object,Object);
extern Object start_procedure_invocation_in_place(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object start_tracking_mouse_in_current_workstation_context(void);
extern Object stop_tracking_mouse_in_current_workstation_context(void);
extern Object store_hand_created_module_information_if_appropriate(Object);
extern Object string_equalw(Object,Object);
extern Object subworkspace_connection_posts_p(Object);
extern Object superior_frame(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object transfer_area(void);
extern Object twrite(Object);
extern Object twrite_symbol(int,...);
extern Object update_border_of_bounding_box(Object,Object,Object,Object,Object);
extern Object update_border_of_text_box(Object,Object,Object,Object,Object);
extern Object update_extreme_edges_from_background_images(Object);
extern Object update_extreme_edges_from_elements_function(Object,Object);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object user_writable_slot_of_instance_p(Object,Object,Object);
extern Object warp_cursor_for_bounding_state_button(Object,Object);
extern Object windows_platform_p(void);
extern Object workspace_can_appear_on_workstation_p(Object,Object);
extern Object workspace_can_be_hidden_qm(Object);
extern Object workspace_is_for_virtual_attribute_table_p(Object);
extern Object workspace_subblocks_may_be_deleted_without_prompting_p(Object);
extern Object workspaces_can_be_shown_at_this_kb_level_p(Object,Object);
extern Object workstation_context_specifics_blackboard_function(Object);
extern Object write_color_menu_ordering_from_slot(Object,Object);
extern Object write_color_set_spec_from_slot(Object,Object);
extern Object write_number_of_menu_columns_spec_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object x_in_window_blackboard_function(Object);
extern Object x_in_workspace_blackboard_function(Object);
extern Object x_in_workspace_coordinates(Object,Object);
extern Object y_in_window_blackboard_function(Object);
extern Object y_in_workspace_blackboard_function(Object);
extern Object y_in_workspace_coordinates(Object,Object);

#else

extern Object abort_current_workstation_context();
extern Object act_on_choice_of_a_button();
extern Object act_on_choice_of_a_chart();
extern Object act_on_choice_of_a_dial();
extern Object act_on_choice_of_a_entity();
extern Object act_on_choice_of_a_freeform_table();
extern Object act_on_choice_of_a_graph();
extern Object act_on_choice_of_a_message();
extern Object act_on_choice_of_a_meter();
extern Object act_on_choice_of_a_readout_table();
extern Object act_on_choice_of_a_text_box();
extern Object act_on_choice_of_a_trend_chart();
extern Object add_class_to_environment();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_intercepted_token_to_text();
extern Object add_keymap_to_workstation_context();
extern Object add_subworkspace();
extern Object add_subworkspace_connection_posts();
extern Object add_to_workspace();
extern Object align_blocks();
extern Object align_for_operate_on_area();
extern Object allocate_byte_vector_16();
extern Object block_may_be_deleted_without_prompting_p();
extern Object bounding_box_spot_structure_memory_usage();
extern Object bounding_state_structure_memory_usage();
extern Object bytes_per_simple_vector();
extern Object c_get_places_bar();
extern Object c_get_system_drives_list();
extern Object c_get_system_special_folders();
extern Object change_edges_of_block();
extern Object change_size_of_chart();
extern Object change_size_of_graph();
extern Object change_size_of_trend_chart();
extern Object change_size_per_bounding_rectangle();
extern Object change_size_per_bounding_rectangle_for_action_button();
extern Object change_size_per_bounding_rectangle_for_block();
extern Object change_size_per_bounding_rectangle_for_chart();
extern Object change_size_per_bounding_rectangle_for_connection();
extern Object change_size_per_bounding_rectangle_for_entity();
extern Object change_size_per_bounding_rectangle_for_graph();
extern Object change_size_per_bounding_rectangle_for_kb_workspace();
extern Object change_size_per_bounding_rectangle_for_text_box();
extern Object change_size_per_bounding_rectangle_for_trend_chart();
extern Object change_slot_value();
extern Object change_text_box_property();
extern Object change_workspace_edges_after_including_margin();
extern Object check_if_superior_classes_are_defined();
extern Object check_savability_of_kb_in_terms_of_modularity();
extern Object choose_font_format_per_fonts_table();
extern Object classic_handle_file_related_window_menu_choice();
extern Object clear_optimized_constants();
extern Object clone_area();
extern Object clone_blocks();
extern Object clone_connections_for_block();
extern Object clone_frame();
extern Object coerce_to_directory_string();
extern Object collect_subclasses();
extern Object compile_color_set_spec_for_slot();
extern Object compute_list_of_modules_putting_top_in_front();
extern Object compute_module_deletion_choices();
extern Object compute_pathname_filter_for_file_type();
extern Object constant_queue_next();
extern Object convert_text_string_to_text();
extern Object convert_to_magnification();
extern Object copy_constant_wide_string_given_length();
extern Object copy_frame_serial_number();
extern Object copy_gensym_tree_with_text_strings();
extern Object copy_list_using_gensym_conses_1();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_out_current_wide_string();
extern Object copy_text();
extern Object copy_text_string();
extern Object copy_wide_string();
extern Object count_instances_of_g2gl_process();
extern Object current_kb_directory_qm();
extern Object default_interesting_directories();
extern Object delete_area();
extern Object delete_block_for_user();
extern Object delete_blocks_for_operate_on_area_after_confirmation();
extern Object delete_blocks_for_operate_on_area_upon_confirmation();
extern Object delete_connection_to_stub();
extern Object delete_connections_of_block_not_within_area_of_workspace();
extern Object delete_connections_of_blocks_within_area();
extern Object delete_frame();
extern Object delete_frame_after_checking_serial_number();
extern Object delete_hand_created_module_information_if_appropriate();
extern Object delete_item_from_list_and_reclaim_cons_cells();
extern Object delete_workspace_for_user();
extern Object describe_restrictions_on_temporary_workspace();
extern Object destabilizing_item_deletion_p();
extern Object detail_pane();
extern Object dial_spot_structure_memory_usage();
extern Object dialog_message_string_for_delete_block();
extern Object direct_structure_method();
extern Object display_table_p();
extern Object distribute_blocks();
extern Object do_addition_of_optional_subtable_from_menu();
extern Object double_nul_string_to_list();
extern Object dragging_cons_function();
extern Object encode_pathname_os();
extern Object end_icp_message_group();
extern Object enlarge_workspace_for_block_rectangle_if_necessary();
extern Object enter_bounding_dialog();
extern Object enter_button_down_context();
extern Object enter_close_box_widget_pending_context();
extern Object enter_context_in_current_workstation();
extern Object enter_dialog();
extern Object enter_editing_context();
extern Object enter_image_plane_dragging_context();
extern Object enter_keys_in_bounding_state();
extern Object enter_min_sizing_dialog();
extern Object enter_move_dragging_context();
extern Object enter_sizing_dialog();
extern Object enter_text_editor_on_text_cell();
extern Object enter_transfer_dragging_context();
extern Object establish_next_workstation_context_continuation();
extern Object execute_command_on_return();
extern Object exit_current_workstation_context_in_return_function();
extern Object find_frame_of_class_in_mouse_pointer();
extern Object find_image_plane_showing_workspace();
extern Object find_position_in_text_given_image_plane();
extern Object finish_parsing_insofar_as_possible();
extern Object fit_bounding_box_around_block();
extern Object fit_entity_around_text_box_or_bounding_rectangle();
extern Object fix_up_bounding_state_if_necessary_after_transfer();
extern Object frame_serial_number_setf_helper_1();
extern Object g2_abort_callback_userdefine();
extern Object g2_get_invalid_workspace_to_handle();
extern Object g2_more_invalid_workspaces_to_be_handled();
extern Object g2_register_workspace_invalidation_handling_procedure();
extern Object generate_spot_for_bounding_box();
extern Object gensym_cons_1();
extern Object gensym_file_as_directory();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object gensym_list_4();
extern Object gensym_namestring();
extern Object gensym_parse_namestring_function();
extern Object get_block_at_other_end_of_connection();
extern Object get_gensym_environment_variable();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_pathname_for_file_command();
extern Object get_property_value_function();
extern Object get_raw_network_info();
extern Object get_saving_parameters();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_init_form();
extern Object get_slot_represented_by_text_cell_if_any();
extern Object get_slot_value_function();
extern Object get_slot_value_if_any_function();
extern Object get_symbol_properties_function();
extern Object get_table_cell_edges();
extern Object get_text_to_edit_from_text_cell();
extern Object get_total_title_bar_text_width();
extern Object get_ui_parameter();
extern Object get_workspace();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object go_to_maybe_newly_created_subworkspace();
extern Object goto_frame_instance();
extern Object hand_place_on_return();
extern Object hand_place_on_return_move_style();
extern Object handle_command();
extern Object handle_create_new_module_window_menu_choice();
extern Object handle_file_command();
extern Object handle_file_related_window_menu_choice();
extern Object handle_inspect_command();
extern Object has_only_one_subblock_p();
extern Object heuristic_maximum_edge();
extern Object highlight_or_unhighlight_button();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object image_plane_blackboard_function();
extern Object image_plane_of_workspace();
extern Object in_block_p();
extern Object in_order_p();
extern Object include_yes_no_menu_choice_p();
extern Object incomplete_box_translation_and_text_p();
extern Object instantiated_class_p();
extern Object interesting_directories();
extern Object inverse_scalef_function();
extern Object invoke_workspace_invalidation_handler_if_any();
extern Object item_deletion_causes_workspace_deletion_p();
extern Object list_blocks_within_area_of_workspace();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object magnify_icon();
extern Object make_and_set_up_kb_load_file_command();
extern Object make_bounding_box();
extern Object make_bounding_box_spot_1();
extern Object make_bounding_state_1();
extern Object make_button();
extern Object make_command_frame();
extern Object make_context_description();
extern Object make_dial();
extern Object make_dial_spot_1();
extern Object make_dialog_message();
extern Object make_empty_text();
extern Object make_entity();
extern Object make_evaluation_truth_value_function();
extern Object make_format_frame();
extern Object make_frame();
extern Object make_free_text_box();
extern Object make_graph();
extern Object make_incomplete_box_translation_and_text();
extern Object make_keymap();
extern Object make_lost_spaces_text_element();
extern Object make_message();
extern Object make_meter();
extern Object make_meter_or_dial_spot_1();
extern Object make_meter_spot_1();
extern Object make_new_top_level_kb_workspace();
extern Object make_or_reformat_table();
extern Object make_permanent_bounding_box_spot_structure_internal();
extern Object make_permanent_bounding_state_structure_internal();
extern Object make_permanent_dial_spot_structure_internal();
extern Object make_permanent_meter_or_dial_spot_structure_internal();
extern Object make_permanent_meter_spot_structure_internal();
extern Object make_readout_table();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_system_frame();
extern Object make_table_describing_restrictions();
extern Object make_text_box();
extern Object make_text_cell();
extern Object make_text_cell_plist_for_color_background();
extern Object make_text_representation_for_slot_value();
extern Object make_thread_array();
extern Object make_trend_chart();
extern Object make_workspace();
extern Object manifest_item_creation();
extern Object map_to_black_or_white();
extern Object map_to_color_value_1();
extern Object memq_function();
extern Object meter_or_dial_spot_structure_memory_usage();
extern Object meter_spot_structure_memory_usage();
extern Object midline_x_of_block_function();
extern Object midline_y_of_block_function();
extern Object module_contains_text_stripped_frames_p();
extern Object mouse_down_on_close_box_widget_in_bounding_state();
extern Object mouse_down_on_image_plane_in_bounding_state();
extern Object mouse_motion_in_bounding_state();
extern Object mouse_pointer_blackboard_function();
extern Object mouse_up_in_bounding_state();
extern Object move_area();
extern Object move_area_to_bottom();
extern Object move_area_to_l_r_center();
extern Object move_area_to_left();
extern Object move_area_to_right();
extern Object move_area_to_t_b_center();
extern Object move_area_to_top();
extern Object move_blocks_with_their_external_connections();
extern Object move_image_plane();
extern Object mutate_global_property();
extern Object name_for_frame_p();
extern Object native_file_dialog_p();
extern Object native_handle_file_related_window_menu_choice();
extern Object native_simple_dialogs_p();
extern Object neatly_stack_image_planes_in_pane();
extern Object neatly_stack_image_planes_in_window();
extern Object non_menu_choice_permitted_p();
extern Object note_change_to_block_1();
extern Object notify_user();
extern Object obtain_simple_text_string();
extern Object obtain_text_string();
extern Object operate_on_area_of_workspace();
extern Object os_pathname_nondirectory();
extern Object outstanding_bounding_box_spot_count();
extern Object outstanding_bounding_state_count();
extern Object outstanding_dial_spot_count();
extern Object outstanding_meter_or_dial_spot_count();
extern Object outstanding_meter_spot_count();
extern Object post_file_dialog();
extern Object post_native_file_dialog();
extern Object post_simple_dialog();
extern Object preflight_file_related_window_menu_choice();
extern Object prepare_blocks_for_operation_on_area();
extern Object problem_item_in_limbo_p();
extern Object push_back_mouse_motion_event();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_colors_on_1st_level_color_menu();
extern Object put_colors_on_2nd_level_color_menu();
extern Object put_do_not_dismiss_color_menu_after_choosing_qm_where_slot_is_absent();
extern Object put_up_attributes_table();
extern Object put_up_table_of_network_info();
extern Object put_workspace_on_pane_function();
extern Object reclaim_bounding_box_spot_1();
extern Object reclaim_bounding_state_1();
extern Object reclaim_dial_spot_1();
extern Object reclaim_dragging_list_function();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_tree_with_text_strings();
extern Object reclaim_hand_placement_return_information();
extern Object reclaim_meter_or_dial_spot_1();
extern Object reclaim_meter_spot_1();
extern Object reclaim_move_style_hand_placement_return_information();
extern Object reclaim_raw_network_info();
extern Object reclaim_slot_value();
extern Object reclaim_structure_if_any();
extern Object reclaim_text();
extern Object reclaim_text_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object reformat_table_in_place();
extern Object reformat_text_box_in_place();
extern Object regenerate_optimized_constant();
extern Object release_mouse_pointers();
extern Object remove_as_subblock_if_necessary();
extern Object replenish_lookup_cons_pool();
extern Object replenish_slot_value_cons_pool();
extern Object requeue_event_and_abort_workstation_context();
extern Object restore_chart_to_normal_size();
extern Object restore_graph_to_normal_size();
extern Object restore_item_to_normal_size();
extern Object restore_size_of_text_box();
extern Object restore_trend_chart_to_normal_size();
extern Object return_from_current_workstation_context();
extern Object rotated_by_90_p();
extern Object scalef_function();
extern Object scope_cons();
extern Object secure_icp_string();
extern Object select_edge_or_corner_of_bounding_box();
extern Object send_icp_file_dialog();
extern Object send_icp_file_dialog_ex();
extern Object send_icp_simple_dialog();
extern Object send_icp_simple_dialog_ex();
extern Object send_ws_representations_item_moved();
extern Object send_ws_representations_item_virtual_attribute_change();
extern Object server_and_client_share_file_system_p();
extern Object set_cursor_position();
extern Object set_edges_of_block();
extern Object set_lookup_slot_value_1();
extern Object set_neither_permanent_nor_transient_and_propagate();
extern Object set_skip_list_entry();
extern Object set_up_bounding_dialog_ws();
extern Object shift_block();
extern Object shrink_wrap_workspace();
extern Object sizing_no_minimum();
extern Object sizing_ok();
extern Object sizing_quit();
extern Object sizing_restore();
extern Object sizing_update();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_4();
extern Object sort_list();
extern Object start_procedure_invocation_in_place();
extern Object start_tracking_mouse_in_current_workstation_context();
extern Object stop_tracking_mouse_in_current_workstation_context();
extern Object store_hand_created_module_information_if_appropriate();
extern Object string_equalw();
extern Object subworkspace_connection_posts_p();
extern Object superior_frame();
extern Object tformat();
extern Object tformat_text_string();
extern Object transfer_area();
extern Object twrite();
extern Object twrite_symbol();
extern Object update_border_of_bounding_box();
extern Object update_border_of_text_box();
extern Object update_extreme_edges_from_background_images();
extern Object update_extreme_edges_from_elements_function();
extern Object update_images_of_block();
extern Object update_object_pool_meters_list();
extern Object user_writable_slot_of_instance_p();
extern Object warp_cursor_for_bounding_state_button();
extern Object windows_platform_p();
extern Object workspace_can_appear_on_workstation_p();
extern Object workspace_can_be_hidden_qm();
extern Object workspace_is_for_virtual_attribute_table_p();
extern Object workspace_subblocks_may_be_deleted_without_prompting_p();
extern Object workspaces_can_be_shown_at_this_kb_level_p();
extern Object workstation_context_specifics_blackboard_function();
extern Object write_color_menu_ordering_from_slot();
extern Object write_color_set_spec_from_slot();
extern Object write_number_of_menu_columns_spec_from_slot();
extern Object write_symbol_list();
extern Object x_in_window_blackboard_function();
extern Object x_in_workspace_blackboard_function();
extern Object x_in_workspace_coordinates();
extern Object y_in_window_blackboard_function();
extern Object y_in_workspace_blackboard_function();
extern Object y_in_workspace_coordinates();

#endif

/* variables/constants */
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Bounding_box_class_description, Qbounding_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Bounding_box_spot_count, Qbounding_box_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Bounding_state_count, Qbounding_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Button_class_description, Qbutton_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Button_label_class_description, Qbutton_label_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Category_instance_menu_workspace_class_description, Qcategory_instance_menu_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_bounding_box_spots, Qchain_of_available_bounding_box_spots);
extern Object Chain_of_available_bounding_box_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_bounding_states, Qchain_of_available_bounding_states);
extern Object Chain_of_available_bounding_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_dial_spots, Qchain_of_available_dial_spots);
extern Object Chain_of_available_dial_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_meter_or_dial_spots, Qchain_of_available_meter_or_dial_spots);
extern Object Chain_of_available_meter_or_dial_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_meter_spots, Qchain_of_available_meter_spots);
extern Object Chain_of_available_meter_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chart, Qchart);
DECLARE_VARIABLE_WITH_SYMBOL(Chart_class_description, Qchart_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Color_parameters, Qcolor_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_color_map, Qcurrent_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_pane, Qcurrent_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
extern Object Default_chart_height;
extern Object Default_chart_width;
extern Object Default_trend_chart_height;
extern Object Default_trend_chart_width;
DECLARE_VARIABLE_WITH_SYMBOL(Dial_spot_count, Qdial_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_on_window, Qdrawing_on_window);
DECLARE_VARIABLE_WITH_SYMBOL(Entity_class_description, Qentity_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_bottom_edge_so_far, Qextreme_bottom_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_left_edge_so_far, Qextreme_left_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_right_edge_so_far, Qextreme_right_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_top_edge_so_far, Qextreme_top_edge_so_far);
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(For_image_plane, Qfor_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Force_change_to_minimum_size_p, Qforce_change_to_minimum_size_p);
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_v5_mode_windows_p, Qg2_has_v5_mode_windows_p);
DECLARE_VARIABLE_WITH_SYMBOL(G2_operating_system, Qg2_operating_system);
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Grammar_categories_getting_yes_no_feature, Qgrammar_categories_getting_yes_no_feature);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_class_description, Qgraph_class_description);
#define Greatest_magnification FIX((SI_Long)4096L)
DECLARE_VARIABLE_WITH_SYMBOL(Height_for_change_size_qm, Qheight_for_change_size_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
#define Icp_window_protocol_supports_file_dialog_ex FIX((SI_Long)45L)
#define Icp_window_protocol_supports_simple_dialog_ex FIX((SI_Long)64L)
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_updating_module_related_frame_notes_for_all_workspaces_qm, Qinhibit_updating_module_related_frame_notes_for_all_workspaces_qm);
extern Object Instances_specific_to_this_class_kbprop;
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Junction_blocks_not_to_be_deleted, Qjunction_blocks_not_to_be_deleted);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Logbook_page_class_description, Qlogbook_page_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_bottom_edge_of_visible_workspace_area, Qloose_bottom_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_class_description, Qloose_end_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_left_edge_of_visible_workspace_area, Qloose_left_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_right_edge_of_visible_workspace_area, Qloose_right_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_top_edge_of_visible_workspace_area, Qloose_top_edge_of_visible_workspace_area);
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
extern Object Maximum_text_box_width_or_height;
DECLARE_VARIABLE_WITH_SYMBOL(Meter_class_description, Qmeter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Meter_or_dial_spot_count, Qmeter_or_dial_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Meter_spot_count, Qmeter_spot_count);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Module_information, Qmodule_information);
DECLARE_VARIABLE_WITH_SYMBOL(Modules_and_system_tables_a_list, Qmodules_and_system_tables_a_list);
DECLARE_VARIABLE_WITH_SYMBOL(Name_box_class_description, Qname_box_class_description);
extern Object Native_load_kb_file_dialog_buttons;
extern Object Native_save_module_file_dialog_buttons;
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Non_kb_workspace_class_description, Qnon_kb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(On_window_without_drawing, Qon_window_without_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_invocation_class_description, Qprocedure_invocation_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Region_invalidation_is_preferred, Qregion_invalidation_is_preferred);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Server_parameters, Qserver_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_dialog_fill_text_p, Qsimple_dialog_fill_text_p);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_dialog_plist_qm, Qsimple_dialog_plist_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_dialog_title_qm, Qsimple_dialog_title_qm);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
extern Object Sizing_dialog_message_string;
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Statement_class_description, Qstatement_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Table_class_description, Qtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Temporary_workspace_class_description, Qtemporary_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Text_box_class_description, Qtext_box_class_description);
extern Object The_type_description_of_bounding_box_spot;
extern Object The_type_description_of_bounding_state;
extern Object The_type_description_of_dial_spot;
extern Object The_type_description_of_meter_or_dial_spot;
extern Object The_type_description_of_meter_spot;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
#define Use_full_size_of_with_output_wide_string_cutoff FIX((SI_Long)256L)
extern Object Use_new_load_kb_qm;
#define Wide_string_list_maximum_length FIX((SI_Long)1024L)
DECLARE_VARIABLE_WITH_SYMBOL(Width_for_change_size_qm, Qwidth_for_change_size_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_event_type_queue, Qworkspace_invalidation_handling_event_type_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_fsn_queue, Qworkspace_invalidation_handling_fsn_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_procedure_fsn_qm, Qworkspace_invalidation_handling_procedure_fsn_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_procedure_qm, Qworkspace_invalidation_handling_procedure_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_window_queue, Qworkspace_invalidation_handling_window_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_invalidation_handling_workspace_queue, Qworkspace_invalidation_handling_workspace_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_name_box_class_description, Qworkspace_name_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
extern Object Ws_protocol_handle_moves_from_edge_change_p;
