/* fltrs.h -- Header File for fltrs.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qplus;
extern Object Qminus;
extern Object Qslash;
extern Object Qnum_lt;
extern Object Qnum_eq;
extern Object Qnum_gt;
extern Object Qand;
extern Object Qbreak;
extern Object Qcons;
extern Object Qdeclaration;
extern Object Qdeclare;
extern Object Qdelete;
extern Object Qfind;
extern Object Qinspect;
extern Object Qinteger;
extern Object Qmember;
extern Object Qnot;
extern Object Qprint;
extern Object Qquote;
extern Object Qread;
extern Object Qreturn;
extern Object Qsequence;
extern Object Qset;
extern Object Qspace;
extern Object Qsymbol;
extern Object Qsymbol_value;
extern Object Qthe;
extern Object Qtype;
extern Object Qunless;
extern Object Qunsigned_byte;
extern Object Qwhen;
extern Object Qwrite;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_alias_to_configuration(Object,Object,Object,Object);
extern Object add_check_boxes_to_current_dialog(Object,Object);
extern Object add_class_to_environment(int,...);
extern Object add_frame_note(int,...);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_or_delete_mode_name_from_directory_of_names(Object,Object);
extern Object add_or_delete_mode_names_from_directory_of_names(Object,Object);
extern Object add_or_delete_mode_names_from_item_configuration(Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object allow_unsavable_change_p(Object);
extern Object assq_function(Object,Object);
extern Object atomic_products_authorized(Object);
extern Object attribute_is_visible_via_the_text_of_p(Object,Object,Object);
extern Object attribute_operation_is_allowed_p(Object,Object,Object,Object);
extern Object block_can_be_dependent_p(Object);
extern Object block_has_stable_heirarchy_p(Object);
extern Object block_is_invisible_to_unsavable_change_protection_p(Object);
extern Object block_is_optimizable_p(Object);
extern Object block_is_unstable_p(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object car_or_atom(Object);
extern Object cdr_or_atom(Object);
extern Object change_mode(void);
extern Object change_slot_value(int,...);
extern Object check_and_install_new_g2_user_mode_for_login(Object,Object);
extern Object check_for_disallowed_mouse_chord(Object,Object,Object);
extern Object check_if_module_is_editable(Object,Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object choose_font_format_per_fonts_table(Object,Object);
extern Object circulate_down(Object);
extern Object circulate_up(Object);
extern Object class_definition_name(Object);
extern Object class_description_matches_restriction_class_spec(Object,Object,Object);
extern Object class_is_visible_to_user_p(Object);
extern Object class_of_block_for_object_configuration(Object);
extern Object clear_optimized_constants(void);
extern Object close_telewindows_connection(Object);
extern Object collect_subclasses(Object);
extern Object command_is_excluded_absolutely_p(int,...);
extern Object compile_g2_user_mode_for_login_for_slot(int,...);
extern Object compile_g2_user_mode_for_login_qm_for_slot(int,...);
extern Object compile_global_keyboard_command_restrictions_for_slot(int,...);
extern Object compile_main_menu_restrictions_for_slot(int,...);
extern Object compile_object_configuration(Object,Object);
extern Object compile_object_configuration_for_slot(int,...);
extern Object compile_simulated_products_qm_for_slot(int,...);
extern Object compile_user_restrictions(Object,Object);
extern Object compile_user_restrictions_for_slot(int,...);
extern Object compute_all_restrictions(int,...);
extern Object compute_global_keyboard_restrictions(void);
extern Object compute_main_menu_restrictions(void);
extern Object compute_menu_restrictions_for_click_on_table(Object,Object,Object);
extern Object compute_menu_restrictions_for_click_on_workspace(Object);
extern Object compute_menu_restrictions_for_workspace(Object);
extern Object compute_name_of_system_frame(Object);
extern Object compute_new_restriction_set(Object,Object,Object,Object);
extern Object compute_non_menu_restrictions_for_item(Object);
extern Object compute_restrictions_of_type(int,...);
extern Object compute_snap_grid_for_block(int,...);
extern Object compute_user_restrictions_in_kb_restrictions(Object);
extern Object compute_visible_slots_for_attribute_table(Object);
extern Object cons_car_cddr(Object);
extern Object constant_queue_next(Object,Object);
extern Object constant_queue_push_right(Object,Object);
extern Object contains_either_really_transient_or_proprietary_p(Object);
extern Object contains_either_really_transient_or_proprietary_p_1(Object,Object);
extern Object contains_proprietary_p(Object);
extern Object contains_proprietary_p_1(Object,Object);
extern Object convert_key_code_to_key_symbol(Object);
extern Object convert_mouse_code_to_mouse_select(Object);
extern Object convert_user_restrictions_into_object_configuration(Object,Object);
extern Object copy_as_wide_string(Object);
extern Object copy_class_restrictions_into_instance_configuration(Object,Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_for_phrase(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_list_using_eval_conses_1(Object);
extern Object copy_list_using_filter_conses_1(Object);
extern Object copy_list_using_phrase_conses(Object);
extern Object copy_list_using_slot_value_conses_1(Object);
extern Object copy_out_current_gensym_string(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_symbol_name(int,...);
extern Object copy_text_string(Object);
extern Object copy_tree_using_filter_conses_1(Object);
extern Object copy_tree_using_slot_value_conses_1(Object);
extern Object copy_user_restrictions_into_object_configuration(Object,Object);
extern Object create_new_module(Object);
extern Object current_workstation_if_usable_for_dialog(Object);
extern Object currently_active_event_handlers_via_object_configuration_1(Object,Object,Object);
extern Object currently_checked_out_file_is_up_to_date_p(Object);
extern Object decache_dynamic_menus(int,...);
extern Object decode_unix_time_as_managed_float(Object);
extern Object def_semi_open_category_1(int,...);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object deinstall_system_table_for_kb_configuration(Object);
extern Object delete_filter_cons_1(Object,Object);
extern Object delete_filter_element_1(Object,Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_slot_value_element_1(Object,Object);
extern Object delete_user_interface_clause(Object,Object,Object);
extern Object describe_item_configuration_keymap(Object,Object);
extern Object describe_keymap_into_table_rows(Object,Object);
extern Object detail_pane(Object);
extern Object differentiate_pressing_from_releasing(Object);
extern Object disambiguate_mouse_button(Object,Object);
extern Object disambiguate_mouse_button_in_phrase(Object,Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object do_not_put_slot_in_attribute_tables_p(int,...);
extern Object do_scc_command(int,...);
extern Object dont_include_workspace(Object);
extern Object edit_attribute_allowed_p(Object,Object,Object);
extern Object ensure_proprietary_section(Object);
extern Object ensure_user_interface_clause(Object,Object,Object,Object);
extern Object ensure_user_interface_section(Object);
extern Object ensure_user_mode_section(Object,Object,Object);
extern Object enter_change_user_mode_in_running(Object,Object);
extern Object enter_dialog(int,...);
extern Object enter_dialog_for_t2(int,...);
extern Object enter_package_preparation_mode(void);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object eval_list_3(Object,Object,Object);
extern Object eval_list_4(Object,Object,Object,Object);
extern Object evaluation_truth_value_is_true_p(Object);
extern Object event_interpretation_for_clause(Object);
extern Object exported_key_modifier_bits(Object);
extern Object extend_current_gensym_string(int,...);
extern Object file_is_in_source_code_control_p(Object);
extern Object filter_attribute_visibility_restrictions(Object,Object,Object);
extern Object filter_cons_1(Object,Object);
extern Object filter_cons_function(Object,Object);
extern Object filter_cons_memory_usage(void);
extern Object filter_copy(Object);
extern Object filter_list_2(Object,Object);
extern Object filter_list_3(Object,Object,Object);
extern Object filter_list_4(Object,Object,Object,Object);
extern Object filter_list_trace_hook(Object);
extern Object filter_menu_restriction_for_kb(Object,Object,Object);
extern Object filter_new_restriction_set(Object,Object);
extern Object filter_non_menu_restriction(Object,Object,Object);
extern Object filter_restrictions_for_item(Object,Object,Object,Object);
extern Object filter_table_restrictions(Object,Object,Object);
extern Object filter_visibility_restrictions(Object,Object,Object);
extern Object filter_workspace_menu_restriction(Object,Object,Object);
extern Object find_user_interface_clause(Object,Object,Object,Object);
extern Object fix_acceptable_applicable_items_for_object_configuration(Object);
extern Object fix_associative_list(Object,Object);
extern Object fix_item_filter_phrase(Object);
extern Object fix_mode_restriction(Object);
extern Object fix_network_configuration_clause(Object);
extern Object fix_object_configuration_clause(Object);
extern Object fix_tailing_associative_list(Object,Object);
extern Object fix_up_double_click_configuration_clauses(Object);
extern Object frame_matches_restriction_class_spec(Object,Object,Object);
extern Object frame_or_attribute_operation_is_allowed_for_mode_p(Object,Object,Object,Object,Object);
extern Object frame_or_attribute_operation_is_allowed_p(Object,Object,Object,Object);
extern Object frame_system_operation_is_allowed_p(Object,Object);
extern Object funcall_function_to_inferior_blocks(Object,Object);
extern Object g2_clear_movement_grid(Object,Object,Object);
extern Object g2_clear_movement_limits(Object,Object,Object);
extern Object g2_describe_g2_license(void);
extern Object g2_equiv(Object,Object);
extern Object g2_get_movement_grid(Object,Object,Object);
extern Object g2_get_movement_limits(Object,Object,Object);
extern Object g2_identification_for_write_locks(void);
extern Object g2_item_is_editable(Object);
extern Object g2_set_all_items_in_module_explicitly_editable(Object);
extern Object g2_set_equivalent(Object,Object);
extern Object g2_set_item_and_all_its_subblocks_explicitly_editable(Object);
extern Object g2_set_item_explicitly_editable(Object);
extern Object g2_set_movement_grid(Object,Object,Object,Object,Object);
extern Object g2_set_movement_limits(Object,Object,Object,Object,Object,Object,Object);
extern Object g2_stream_directory_p(Object);
extern Object g2_stream_file_is_readable_p(Object);
extern Object g2_stream_file_is_writable_p(Object);
extern Object g2_subset(Object,Object);
extern Object g2_xor(Object,Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_namestring_of_directory_as_file(Object);
extern Object get_alias_for_slot_name_if_any(Object,Object);
extern Object get_comment_in_object_configuration(Object,Object);
extern Object get_current_ui_client_interface(void);
extern Object get_current_user_name(void);
extern Object get_g2_license_level(void);
extern Object get_global_snap_grid(void);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_module_block_is_in(Object);
extern Object get_property_clause(Object,Object);
extern Object get_property_value_in_object_configuration(Object,Object,Object);
extern Object get_reason_module_is_not_editable(int,...);
extern Object get_saving_parameters(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_slot_init_form(int,...);
extern Object get_slot_name_for_alias_if_any(Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_true_pathname_of_module_if_any(Object);
extern Object get_ui_parameter(int,...);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object global_keyboard_command_permitted_p(Object);
extern Object global_keyboard_command_user_restrictions_function(Object);
extern Object grid_alignment_constraint_for_block(Object);
extern Object grid_spec_must_be_positive(Object);
extern Object handle_dependent_or_stable_status_change_for_item(Object);
extern Object handle_dependent_or_stable_status_change_for_item_for_filters(Object,Object);
extern Object handle_stable_hierarchy_or_inline_status_change_for_item(int,...);
extern Object import_mouse_chord(Object,Object,Object);
extern Object in_order_p(Object);
extern Object include_slot_in_attribute_table_for_mode_p(Object,Object,Object,Object);
extern Object include_slot_in_attribute_table_p(Object,Object,Object);
extern Object initialize_after_reading_for_kb_configuration(Object);
extern Object install_system_table_for_kb_configuration(Object);
extern Object interpret_event_via_object_configuration_1(Object,Object,Object);
extern Object invoke_interlace_abstraction_if_offered(void);
extern Object item_explicitly_editable_p(Object);
extern Object item_is_either_not_permanent_or_from_an_editable_module_p(Object);
extern Object item_menu_command_permitted_p(Object,Object);
extern Object key_bindings_due_to_object_configurations(Object);
extern Object key_bindings_for_class_description_on_workspace(Object,Object);
extern Object key_bindings_for_class_description_on_workspace_1(Object,Object,Object);
extern Object key_code_from_list(Object);
extern Object key_code_function(Object,Object,Object);
extern Object key_code_match_for_filters_p(Object,Object);
extern Object key_code_mouse_button_name(Object);
extern Object key_symbol(Object);
extern Object leave_dialog_for_t2(Object);
extern Object leave_package_preparation_mode(void);
extern Object license_level(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value_with_default(Object,Object,Object);
extern Object lookup_key_in_item_configuration(Object,Object,Object);
extern Object main_menu_command_permitted_p(Object);
extern Object main_menu_user_restrictions_function(Object);
extern Object make_acceptable_applicable_items_for_object_configuration(Object);
extern Object make_declaration_clause_for_item_configuration(int,...);
extern Object make_eval_list_1(Object);
extern Object make_event_interpretation(Object,Object,Object);
extern Object make_filter_list_1(Object);
extern Object make_new_alias(Object);
extern Object make_or_reformat_table(int,...);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_phrase_list(Object);
extern Object make_table_describing_restrictions(Object);
extern Object make_table_spacer_cells(int,...);
extern Object make_text_cell(int,...);
extern Object make_user_mode_alias_1(void);
extern Object map_over_external_names_in_object_configuration(Object,Object);
extern Object map_over_matching_user_interface_clauses(int,...);
extern Object map_over_matching_user_interface_clauses_1(Object,Object,Object,Object,Object,Object,Object);
extern Object marshall_exceptional_float_arguments(void);
extern Object massage_configuration_value(Object);
extern Object massage_user_declaration_clause(Object);
extern Object memq_function(Object,Object);
extern Object modules_with_unsaved_changes(void);
extern Object most_interesting_frame_in_spot(Object);
extern Object movement_limits_for_block(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object namestring_as_gensym_string(Object);
extern Object network_access_allowed_p(int,...);
extern Object no_manual_connections_p(Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_dependent_or_stable_status_change(Object);
extern Object notify_user_1(Object);
extern Object nreverse_evaluation_sequence(Object);
extern Object nstring_downcasew(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object ole_drop_allowed_p(Object,Object);
extern Object optimize_telewindows_z_layer_model(void);
extern Object outstanding_filter_conses(void);
extern Object parse_user_interface_gesture(Object);
extern Object parse_user_interface_key_chord(Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_flatten_tree(Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_3(Object,Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object prohibit_nothing(Object);
extern Object propagate_change_in_object_configuration(Object,Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_class_restrictions(Object,Object,Object);
extern Object put_frame_style(Object,Object,Object);
extern Object put_global_keyboard_command_user_restrictions(Object,Object,Object);
extern Object put_initial_g2_user_mode_for_this_kb(Object,Object,Object);
extern Object put_instance_configuration(Object,Object,Object);
extern Object put_main_menu_user_restrictions(Object,Object,Object);
extern Object put_name_or_names_for_frame(Object,Object,Object);
extern Object put_object_configuration(Object,Object,Object);
extern Object put_simulated_optional_modules(Object,Object,Object);
extern Object put_user_restrictions(Object,Object,Object);
extern Object raw_stack_error_named_error(Object,Object);
extern Object reason_permanent_items_attribute_is_not_editable(int,...);
extern Object reason_permanent_items_module_is_not_editable(int,...);
extern Object reason_that_the_current_user_is_not_the_only_editor(Object,Object);
extern Object reason_to_exclude_slot_description_for_compute_class_description_node_attributes(Object);
extern Object reclaim_absolutely_prohibited_restriction_set(void);
extern Object reclaim_event_interpretation(Object);
extern Object reclaim_filter_cons_1(Object);
extern Object reclaim_filter_list_1(Object);
extern Object reclaim_filter_list_function(Object);
extern Object reclaim_filter_list_star_1(Object);
extern Object reclaim_filter_tree_1(Object);
extern Object reclaim_filter_tree_function(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_instance_configuration_value(Object,Object);
extern Object reclaim_list_of_block_snapshots(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_object_configuration_value(Object,Object);
extern Object reclaim_permitted_restriction_set(void);
extern Object reclaim_prohibited_restriction_set(void);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object recompute_editability_of_modules(void);
extern Object reconsider_formatting(Object);
extern Object reconstruct_g2_time_at_start(Object);
extern Object record_block_for_tformat(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object reinstall_authorized_users(void);
extern Object remove_dialog_info_from_ui_client_interface_dialog_list(Object,Object);
extern Object remove_from_restriction_set(Object,Object);
extern Object remove_separator_symbol_from_phrase(Object);
extern Object remove_tracing_and_breakpoints(void);
extern Object rename_slots_in_restrictions(Object);
extern Object replenish_filter_cons_pool(void);
extern Object replenish_filter_list_pool(Object);
extern Object replenish_stack_change_cons_pool(void);
extern Object selection_enabled_p(int,...);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_grammar_transform_can_return_bad_phrase_p(Object);
extern Object set_inherit_stdio_handles(Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_reason_module_is_not_editable(Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object setup_atomic_products_for_simulation(Object);
extern Object setup_current_simulated_product_authorization(void);
extern Object slot_denotation_member(Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object start_adaptive_font_fallback(void);
extern Object string_for_localized_symbol(Object);
extern Object string_to_display_for_keyboard_symbol(Object,Object);
extern Object string_to_insert_for_keyboard_symbol(Object);
extern Object subworkspace_connection_posts_p(Object);
extern Object superior_frame(Object);
extern Object system_table_installed_p(Object);
extern Object t2_continuation_for_warn_about_editing_item(Object,Object,Object,Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object text_string_search_simple(Object,Object);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tformat_text_string(int,...);
extern Object toggle_visible_grid(Object);
extern Object try_to_obtain_write_lock_for_kb(Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_class_spec_for_restrictions(Object,Object,Object);
extern Object twrite_general_string(Object);
extern Object twrite_key_code(Object);
extern Object twrite_key_code_for_filters(Object);
extern Object twrite_key_modifier_bits(Object,Object);
extern Object twrite_list_function(Object,Object,Object,Object,Object);
extern Object twrite_mouse_button_for_filters(Object);
extern Object twrite_n_digit_number_with_0_pad(Object,Object);
extern Object twrite_symbol(int,...);
extern Object twrite_wide_character(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_slot_feature_assq_if_editable(Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object unedit_up_to_date_modules(void);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_frame_name_references(Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_slot_value(int,...);
extern Object update_user_mode_state(Object,Object);
extern Object validate_as_possible_user_mode(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object validate_user_mode_for_user(Object,Object);
extern Object visible_atomic_product_maybe_simulated_on_this_machine_p(Object);
extern Object warn_about_editing_item(Object,Object,Object);
extern Object warn_about_editing_item_callback(Object,Object,Object);
extern Object warn_about_editing_item_for_workstation(Object,Object,Object,Object);
extern Object warn_about_editing_item_for_workstation_1(Object,Object,Object);
extern Object warn_on_unsavable_change_p(Object);
extern Object workspaces_can_be_shown_at_this_kb_level_p(Object,Object);
extern Object write_class_restrictions_from_slot(Object,Object);
extern Object write_global_keyboard_command_restrictions_from_slot(Object,Object);
extern Object write_list_of_classes_in_object_configuration(int,...);
extern Object write_main_menu_restrictions_from_slot(Object,Object);
extern Object write_mode_restriction(Object);
extern Object write_name_denotation(Object);
extern Object write_object_configuration(Object);
extern Object write_object_configuration_clause(Object);
extern Object write_object_configuration_from_slot(Object,Object);
extern Object write_psueudo_authorized_optional_modules_from_slot(Object,Object);
extern Object write_restriction_clause(Object);
extern Object write_restriction_clause_1(int,...);
extern Object write_simulated_products_qm_from_slot(Object,Object);
extern Object write_symbol_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object write_user_interface_clause(Object);
extern Object write_user_restrictions(Object);
extern Object write_user_restrictions_from_object_configuration(Object);
extern Object write_user_restrictions_from_slot(Object,Object);

#else

extern Object add_alias_to_configuration();
extern Object add_check_boxes_to_current_dialog();
extern Object add_class_to_environment();
extern Object add_frame_note();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_or_delete_mode_name_from_directory_of_names();
extern Object add_or_delete_mode_names_from_directory_of_names();
extern Object add_or_delete_mode_names_from_item_configuration();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object allow_unsavable_change_p();
extern Object assq_function();
extern Object atomic_products_authorized();
extern Object attribute_is_visible_via_the_text_of_p();
extern Object attribute_operation_is_allowed_p();
extern Object block_can_be_dependent_p();
extern Object block_has_stable_heirarchy_p();
extern Object block_is_invisible_to_unsavable_change_protection_p();
extern Object block_is_optimizable_p();
extern Object block_is_unstable_p();
extern Object bytes_per_double_float_simple_array();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object car_or_atom();
extern Object cdr_or_atom();
extern Object change_mode();
extern Object change_slot_value();
extern Object check_and_install_new_g2_user_mode_for_login();
extern Object check_for_disallowed_mouse_chord();
extern Object check_if_module_is_editable();
extern Object check_if_superior_classes_are_defined();
extern Object choose_font_format_per_fonts_table();
extern Object circulate_down();
extern Object circulate_up();
extern Object class_definition_name();
extern Object class_description_matches_restriction_class_spec();
extern Object class_is_visible_to_user_p();
extern Object class_of_block_for_object_configuration();
extern Object clear_optimized_constants();
extern Object close_telewindows_connection();
extern Object collect_subclasses();
extern Object command_is_excluded_absolutely_p();
extern Object compile_g2_user_mode_for_login_for_slot();
extern Object compile_g2_user_mode_for_login_qm_for_slot();
extern Object compile_global_keyboard_command_restrictions_for_slot();
extern Object compile_main_menu_restrictions_for_slot();
extern Object compile_object_configuration();
extern Object compile_object_configuration_for_slot();
extern Object compile_simulated_products_qm_for_slot();
extern Object compile_user_restrictions();
extern Object compile_user_restrictions_for_slot();
extern Object compute_all_restrictions();
extern Object compute_global_keyboard_restrictions();
extern Object compute_main_menu_restrictions();
extern Object compute_menu_restrictions_for_click_on_table();
extern Object compute_menu_restrictions_for_click_on_workspace();
extern Object compute_menu_restrictions_for_workspace();
extern Object compute_name_of_system_frame();
extern Object compute_new_restriction_set();
extern Object compute_non_menu_restrictions_for_item();
extern Object compute_restrictions_of_type();
extern Object compute_snap_grid_for_block();
extern Object compute_user_restrictions_in_kb_restrictions();
extern Object compute_visible_slots_for_attribute_table();
extern Object cons_car_cddr();
extern Object constant_queue_next();
extern Object constant_queue_push_right();
extern Object contains_either_really_transient_or_proprietary_p();
extern Object contains_either_really_transient_or_proprietary_p_1();
extern Object contains_proprietary_p();
extern Object contains_proprietary_p_1();
extern Object convert_key_code_to_key_symbol();
extern Object convert_mouse_code_to_mouse_select();
extern Object convert_user_restrictions_into_object_configuration();
extern Object copy_as_wide_string();
extern Object copy_class_restrictions_into_instance_configuration();
extern Object copy_constant_wide_string_given_length();
extern Object copy_for_phrase();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_list_using_eval_conses_1();
extern Object copy_list_using_filter_conses_1();
extern Object copy_list_using_phrase_conses();
extern Object copy_list_using_slot_value_conses_1();
extern Object copy_out_current_gensym_string();
extern Object copy_out_current_wide_string();
extern Object copy_symbol_name();
extern Object copy_text_string();
extern Object copy_tree_using_filter_conses_1();
extern Object copy_tree_using_slot_value_conses_1();
extern Object copy_user_restrictions_into_object_configuration();
extern Object create_new_module();
extern Object current_workstation_if_usable_for_dialog();
extern Object currently_active_event_handlers_via_object_configuration_1();
extern Object currently_checked_out_file_is_up_to_date_p();
extern Object decache_dynamic_menus();
extern Object decode_unix_time_as_managed_float();
extern Object def_semi_open_category_1();
extern Object define_type_specification_explicit_complex_type();
extern Object deinstall_system_table_for_kb_configuration();
extern Object delete_filter_cons_1();
extern Object delete_filter_element_1();
extern Object delete_frame_note_if_any();
extern Object delete_slot_value_element_1();
extern Object delete_user_interface_clause();
extern Object describe_item_configuration_keymap();
extern Object describe_keymap_into_table_rows();
extern Object detail_pane();
extern Object differentiate_pressing_from_releasing();
extern Object disambiguate_mouse_button();
extern Object disambiguate_mouse_button_in_phrase();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object do_not_put_slot_in_attribute_tables_p();
extern Object do_scc_command();
extern Object dont_include_workspace();
extern Object edit_attribute_allowed_p();
extern Object ensure_proprietary_section();
extern Object ensure_user_interface_clause();
extern Object ensure_user_interface_section();
extern Object ensure_user_mode_section();
extern Object enter_change_user_mode_in_running();
extern Object enter_dialog();
extern Object enter_dialog_for_t2();
extern Object enter_package_preparation_mode();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object eval_list_3();
extern Object eval_list_4();
extern Object evaluation_truth_value_is_true_p();
extern Object event_interpretation_for_clause();
extern Object exported_key_modifier_bits();
extern Object extend_current_gensym_string();
extern Object file_is_in_source_code_control_p();
extern Object filter_attribute_visibility_restrictions();
extern Object filter_cons_1();
extern Object filter_cons_function();
extern Object filter_cons_memory_usage();
extern Object filter_copy();
extern Object filter_list_2();
extern Object filter_list_3();
extern Object filter_list_4();
extern Object filter_list_trace_hook();
extern Object filter_menu_restriction_for_kb();
extern Object filter_new_restriction_set();
extern Object filter_non_menu_restriction();
extern Object filter_restrictions_for_item();
extern Object filter_table_restrictions();
extern Object filter_visibility_restrictions();
extern Object filter_workspace_menu_restriction();
extern Object find_user_interface_clause();
extern Object fix_acceptable_applicable_items_for_object_configuration();
extern Object fix_associative_list();
extern Object fix_item_filter_phrase();
extern Object fix_mode_restriction();
extern Object fix_network_configuration_clause();
extern Object fix_object_configuration_clause();
extern Object fix_tailing_associative_list();
extern Object fix_up_double_click_configuration_clauses();
extern Object frame_matches_restriction_class_spec();
extern Object frame_or_attribute_operation_is_allowed_for_mode_p();
extern Object frame_or_attribute_operation_is_allowed_p();
extern Object frame_system_operation_is_allowed_p();
extern Object funcall_function_to_inferior_blocks();
extern Object g2_clear_movement_grid();
extern Object g2_clear_movement_limits();
extern Object g2_describe_g2_license();
extern Object g2_equiv();
extern Object g2_get_movement_grid();
extern Object g2_get_movement_limits();
extern Object g2_identification_for_write_locks();
extern Object g2_item_is_editable();
extern Object g2_set_all_items_in_module_explicitly_editable();
extern Object g2_set_equivalent();
extern Object g2_set_item_and_all_its_subblocks_explicitly_editable();
extern Object g2_set_item_explicitly_editable();
extern Object g2_set_movement_grid();
extern Object g2_set_movement_limits();
extern Object g2_stream_directory_p();
extern Object g2_stream_file_is_readable_p();
extern Object g2_stream_file_is_writable_p();
extern Object g2_subset();
extern Object g2_xor();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_namestring_of_directory_as_file();
extern Object get_alias_for_slot_name_if_any();
extern Object get_comment_in_object_configuration();
extern Object get_current_ui_client_interface();
extern Object get_current_user_name();
extern Object get_g2_license_level();
extern Object get_global_snap_grid();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_module_block_is_in();
extern Object get_property_clause();
extern Object get_property_value_in_object_configuration();
extern Object get_reason_module_is_not_editable();
extern Object get_saving_parameters();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_slot_init_form();
extern Object get_slot_name_for_alias_if_any();
extern Object get_slot_value_function();
extern Object get_symbol_properties_function();
extern Object get_true_pathname_of_module_if_any();
extern Object get_ui_parameter();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object global_keyboard_command_permitted_p();
extern Object global_keyboard_command_user_restrictions_function();
extern Object grid_alignment_constraint_for_block();
extern Object grid_spec_must_be_positive();
extern Object handle_dependent_or_stable_status_change_for_item();
extern Object handle_dependent_or_stable_status_change_for_item_for_filters();
extern Object handle_stable_hierarchy_or_inline_status_change_for_item();
extern Object import_mouse_chord();
extern Object in_order_p();
extern Object include_slot_in_attribute_table_for_mode_p();
extern Object include_slot_in_attribute_table_p();
extern Object initialize_after_reading_for_kb_configuration();
extern Object install_system_table_for_kb_configuration();
extern Object interpret_event_via_object_configuration_1();
extern Object invoke_interlace_abstraction_if_offered();
extern Object item_explicitly_editable_p();
extern Object item_is_either_not_permanent_or_from_an_editable_module_p();
extern Object item_menu_command_permitted_p();
extern Object key_bindings_due_to_object_configurations();
extern Object key_bindings_for_class_description_on_workspace();
extern Object key_bindings_for_class_description_on_workspace_1();
extern Object key_code_from_list();
extern Object key_code_function();
extern Object key_code_match_for_filters_p();
extern Object key_code_mouse_button_name();
extern Object key_symbol();
extern Object leave_dialog_for_t2();
extern Object leave_package_preparation_mode();
extern Object license_level();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lookup_kb_specific_property_value_with_default();
extern Object lookup_key_in_item_configuration();
extern Object main_menu_command_permitted_p();
extern Object main_menu_user_restrictions_function();
extern Object make_acceptable_applicable_items_for_object_configuration();
extern Object make_declaration_clause_for_item_configuration();
extern Object make_eval_list_1();
extern Object make_event_interpretation();
extern Object make_filter_list_1();
extern Object make_new_alias();
extern Object make_or_reformat_table();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_phrase_list();
extern Object make_table_describing_restrictions();
extern Object make_table_spacer_cells();
extern Object make_text_cell();
extern Object make_user_mode_alias_1();
extern Object map_over_external_names_in_object_configuration();
extern Object map_over_matching_user_interface_clauses();
extern Object map_over_matching_user_interface_clauses_1();
extern Object marshall_exceptional_float_arguments();
extern Object massage_configuration_value();
extern Object massage_user_declaration_clause();
extern Object memq_function();
extern Object modules_with_unsaved_changes();
extern Object most_interesting_frame_in_spot();
extern Object movement_limits_for_block();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object namestring_as_gensym_string();
extern Object network_access_allowed_p();
extern Object no_manual_connections_p();
extern Object non_menu_choice_permitted_p();
extern Object note_change_to_block_1();
extern Object note_dependent_or_stable_status_change();
extern Object notify_user_1();
extern Object nreverse_evaluation_sequence();
extern Object nstring_downcasew();
extern Object obtain_simple_gensym_string();
extern Object ole_drop_allowed_p();
extern Object optimize_telewindows_z_layer_model();
extern Object outstanding_filter_conses();
extern Object parse_user_interface_gesture();
extern Object parse_user_interface_key_chord();
extern Object phrase_cons();
extern Object phrase_flatten_tree();
extern Object phrase_list_2();
extern Object phrase_list_3();
extern Object phrase_list_4();
extern Object prohibit_nothing();
extern Object propagate_change_in_object_configuration();
extern Object push_optimized_constant();
extern Object put_class_restrictions();
extern Object put_frame_style();
extern Object put_global_keyboard_command_user_restrictions();
extern Object put_initial_g2_user_mode_for_this_kb();
extern Object put_instance_configuration();
extern Object put_main_menu_user_restrictions();
extern Object put_name_or_names_for_frame();
extern Object put_object_configuration();
extern Object put_simulated_optional_modules();
extern Object put_user_restrictions();
extern Object raw_stack_error_named_error();
extern Object reason_permanent_items_attribute_is_not_editable();
extern Object reason_permanent_items_module_is_not_editable();
extern Object reason_that_the_current_user_is_not_the_only_editor();
extern Object reason_to_exclude_slot_description_for_compute_class_description_node_attributes();
extern Object reclaim_absolutely_prohibited_restriction_set();
extern Object reclaim_event_interpretation();
extern Object reclaim_filter_cons_1();
extern Object reclaim_filter_list_1();
extern Object reclaim_filter_list_function();
extern Object reclaim_filter_list_star_1();
extern Object reclaim_filter_tree_1();
extern Object reclaim_filter_tree_function();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_string();
extern Object reclaim_instance_configuration_value();
extern Object reclaim_list_of_block_snapshots();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_object_configuration_value();
extern Object reclaim_permitted_restriction_set();
extern Object reclaim_prohibited_restriction_set();
extern Object reclaim_schedule_task_args();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_text_string();
extern Object recompute_editability_of_modules();
extern Object reconsider_formatting();
extern Object reconstruct_g2_time_at_start();
extern Object record_block_for_tformat();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object reinstall_authorized_users();
extern Object remove_dialog_info_from_ui_client_interface_dialog_list();
extern Object remove_from_restriction_set();
extern Object remove_separator_symbol_from_phrase();
extern Object remove_tracing_and_breakpoints();
extern Object rename_slots_in_restrictions();
extern Object replenish_filter_cons_pool();
extern Object replenish_filter_list_pool();
extern Object replenish_stack_change_cons_pool();
extern Object selection_enabled_p();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_grammar_transform_can_return_bad_phrase_p();
extern Object set_inherit_stdio_handles();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_property_value_function();
extern Object set_reason_module_is_not_editable();
extern Object set_slot_value_to_evaluation_value_function();
extern Object setup_atomic_products_for_simulation();
extern Object setup_current_simulated_product_authorization();
extern Object slot_denotation_member();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object slot_value_list_4();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object start_adaptive_font_fallback();
extern Object string_for_localized_symbol();
extern Object string_to_display_for_keyboard_symbol();
extern Object string_to_insert_for_keyboard_symbol();
extern Object subworkspace_connection_posts_p();
extern Object superior_frame();
extern Object system_table_installed_p();
extern Object t2_continuation_for_warn_about_editing_item();
extern Object text_string_length();
extern Object text_string_p();
extern Object text_string_search_simple();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tformat_text_string();
extern Object toggle_visible_grid();
extern Object try_to_obtain_write_lock_for_kb();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_class_spec_for_restrictions();
extern Object twrite_general_string();
extern Object twrite_key_code();
extern Object twrite_key_code_for_filters();
extern Object twrite_key_modifier_bits();
extern Object twrite_list_function();
extern Object twrite_mouse_button_for_filters();
extern Object twrite_n_digit_number_with_0_pad();
extern Object twrite_symbol();
extern Object twrite_wide_character();
extern Object type_error_in_setter();
extern Object type_slot_feature_assq_if_editable();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object unedit_up_to_date_modules();
extern Object update_all_representations_of_slot();
extern Object update_frame_name_references();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_slot_value();
extern Object update_user_mode_state();
extern Object validate_as_possible_user_mode();
extern Object validate_item_or_evaluation_value();
extern Object validate_user_mode_for_user();
extern Object visible_atomic_product_maybe_simulated_on_this_machine_p();
extern Object warn_about_editing_item();
extern Object warn_about_editing_item_callback();
extern Object warn_about_editing_item_for_workstation();
extern Object warn_about_editing_item_for_workstation_1();
extern Object warn_on_unsavable_change_p();
extern Object workspaces_can_be_shown_at_this_kb_level_p();
extern Object write_class_restrictions_from_slot();
extern Object write_global_keyboard_command_restrictions_from_slot();
extern Object write_list_of_classes_in_object_configuration();
extern Object write_main_menu_restrictions_from_slot();
extern Object write_mode_restriction();
extern Object write_name_denotation();
extern Object write_object_configuration();
extern Object write_object_configuration_clause();
extern Object write_object_configuration_from_slot();
extern Object write_psueudo_authorized_optional_modules_from_slot();
extern Object write_restriction_clause();
extern Object write_restriction_clause_1();
extern Object write_simulated_products_qm_from_slot();
extern Object write_symbol_from_slot();
extern Object write_symbol_list();
extern Object write_user_interface_clause();
extern Object write_user_restrictions();
extern Object write_user_restrictions_from_object_configuration();
extern Object write_user_restrictions_from_slot();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Absolutely_prohibited_restriction_set, Qabsolutely_prohibited_restriction_set);
DECLARE_VARIABLE_WITH_SYMBOL(Absolutely_selected_choice_qm, Qabsolutely_selected_choice_qm);
#define Alternate_bit FIX((SI_Long)524288L)
DECLARE_VARIABLE_WITH_SYMBOL(Arrow_button_class_description, Qarrow_button_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_products_of_this_machine, Qauthorized_products_of_this_machine);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_user_class_description, Qauthorized_user_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Available_filter_conses, Qavailable_filter_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_filter_conses_tail, Qavailable_filter_conses_tail);
extern Object Available_filter_conses_tail_vector;
extern Object Available_filter_conses_vector;
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Choice_conflict, Qchoice_conflict);
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Compiled_items_deferred_for_analysis, Qcompiled_items_deferred_for_analysis);
DECLARE_VARIABLE_WITH_SYMBOL(Conditional_selected_choice_qm, Qconditional_selected_choice_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Conditional_termination_state_qm, Qconditional_termination_state_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Contains_either_really_transient_or_proprietary_p_1, Qcontains_either_really_transient_or_proprietary_p_1);
DECLARE_VARIABLE_WITH_SYMBOL(Contains_proprietary_p_1, Qcontains_proprietary_p_1);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
#define Control_bit FIX((SI_Long)8388608L)
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_filters_search_result, Qcurrent_filters_search_result);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Currently_active_event_handlers_via_object_configuration, Qcurrently_active_event_handlers_via_object_configuration);
extern Object Declared_properties_attributes;
DECLARE_VARIABLE_WITH_SYMBOL(Defer_consistency_analysis_qm, Qdefer_consistency_analysis_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_subworkspace_connection_posts, Qdisable_subworkspace_connection_posts);
#define Double_bit FIX((SI_Long)65536L)
extern Object Double_mask;
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Exact_class_names_for_menu_restrictions, Qexact_class_names_for_menu_restrictions);
DECLARE_VARIABLE_WITH_SYMBOL(Explanation_table_class_description, Qexplanation_table_class_description);
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Filter_cons_counter, Qfilter_cons_counter);
extern Object Filter_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Foremost_attribute_for_multiplexed_chaining_qm, Qforemost_attribute_for_multiplexed_chaining_qm);
DECLARE_VARIABLE_WITH_SYMBOL(G2_identification_for_write_locks, Qg2_identification_for_write_locks);
DECLARE_VARIABLE_WITH_SYMBOL(G2_login_class_description, Qg2_login_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start_as_text_string, Qg2_time_at_start_as_text_string);
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Global_keyboard_command_choices, Qglobal_keyboard_command_choices);
DECLARE_VARIABLE_WITH_SYMBOL(Grid, Qgrid);
#define Higher_than_any_priority FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Icon_editor_table_info_frame_class_description, Qicon_editor_table_info_frame_class_description);
#define Illegal_key_code FIX((SI_Long)-1L)
extern Object Illegal_key_index;
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(In_edit_warning_context_p, Qin_edit_warning_context_p);
DECLARE_VARIABLE_WITH_SYMBOL(In_recompile_item_p, Qin_recompile_item_p);
extern Object Info_for_restrictable_frame_system_operation_prop;
extern Object Instances_specific_to_this_class_kbprop;
extern Object Item_menu_choices;
DECLARE_VARIABLE_WITH_SYMBOL(Items_warned_in_edit_warning_context, Qitems_warned_in_edit_warning_context);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
#define Kb_format_revision_for_kb_restrictions_reclassification FIX((SI_Long)243L)
DECLARE_VARIABLE_WITH_SYMBOL(Kb_restrictions, Qkb_restrictions);
extern Object Kb_specific_property_names;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
extern Object Key_index_bits;
extern Object Key_modifier_bits;
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Local_host_name, Qlocal_host_name);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_class_description, Qloose_end_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Main_menu_choices, Qmain_menu_choices);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Menu_and_attribute_visibility_configurations_restriction_types;
extern Object Menu_configuration_operation_types;
DECLARE_VARIABLE_WITH_SYMBOL(Message_class_description, Qmessage_class_description);
extern Object Module_is_explictly_editable_p_kbprop;
extern Object Module_is_locked_p_kbprop;
extern Object Module_is_writable_p_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Modules_and_system_tables_a_list, Qmodules_and_system_tables_a_list);
DECLARE_VARIABLE_WITH_SYMBOL(Mutable_slot_description_list_head, Qmutable_slot_description_list_head);
DECLARE_VARIABLE_WITH_SYMBOL(Name_box_class_description, Qname_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(Non_menu_choices, Qnon_menu_choices);
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_class_description, Qok_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Optional_modules_map, Qoptional_modules_map);
DECLARE_VARIABLE_WITH_SYMBOL(Package_preparation_mode, Qpackage_preparation_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Permitted_restriction_set, Qpermitted_restriction_set);
DECLARE_VARIABLE_WITH_SYMBOL(Prohibited_restriction_set, Qprohibited_restriction_set);
DECLARE_VARIABLE_WITH_SYMBOL(Pseudo_class_slot_description, Qpseudo_class_slot_description);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Relations_tag_list, Qrelations_tag_list);
DECLARE_VARIABLE_WITH_SYMBOL(Restrict_edits_to_modules_having_read_only_files_p, Qrestrict_edits_to_modules_having_read_only_files_p);
DECLARE_VARIABLE_WITH_SYMBOL(Saving_parameters, Qsaving_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Scrap_class_description, Qscrap_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(See_also_for_warn_about_editing_item, Qsee_also_for_warn_about_editing_item);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
#define Shift_bit FIX((SI_Long)262144L)
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Slot_alias_for_restrictions, Qslot_alias_for_restrictions);
DECLARE_VARIABLE_WITH_SYMBOL(Slot_description_for_restrictions, Qslot_description_for_restrictions);
DECLARE_VARIABLE_WITH_SYMBOL(Snapshots_of_related_blocks, Qsnapshots_of_related_blocks);
DECLARE_VARIABLE_WITH_SYMBOL(Source_code_control_support_enabled_p, Qsource_code_control_support_enabled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Superior_frame_for_restrictions_frame_qm, Qsuperior_frame_for_restrictions_frame_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Superior_frame_for_restrictions_superior_qm, Qsuperior_frame_for_restrictions_superior_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Table_menu_choices, Qtable_menu_choices);
DECLARE_VARIABLE_WITH_SYMBOL(Tcp_listener_port_number, Qtcp_listener_port_number);
DECLARE_VARIABLE_WITH_SYMBOL(Text_representation_of_our_ok_object, Qtext_representation_of_our_ok_object);
extern Object Things_to_rename_in_restrictions;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
#define Unicode_bit FIX((SI_Long)16777216L)
extern Object Unicode_character_bits;
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_menu_choices, Qworkspace_menu_choices);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_strings_parsably_qm, Qwrite_strings_parsably_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
