/* fonts.h -- Header File for fonts.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qbit;
extern Object Qcar;
extern Object Qcdr;
extern Object Qcons;
extern Object Kelement_type;
extern Object Qerror;
extern Object Kinitial_contents;
extern Object Kinitial_element;
extern Object Qmake_array;
extern Object Knewest;
extern Object Qnull;
extern Object Qunsigned_byte;
extern Object Qvector;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object accumulate_thrashing_cost_and_decache(Object,Object,Object,Object);
extern Object add_character_description_1(int,...);
extern Object add_from_line_of_text_to_current_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object add_from_line_of_text_to_current_window_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object add_icp_message_handler(Object,Object);
extern Object adjust_to_previous_base_character(Object,Object);
extern Object allocate_byte_vector(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_vector(Object);
extern Object allocate_scratchpad_raster(Object,Object,Object,Object);
extern Object allocate_temporary_character_bitmap(Object,Object);
extern Object asian_font_read_in_already_p(Object);
extern Object assign_corresponding_icp_object_index(Object,Object,Object);
extern Object bitmap_array_structure_memory_usage(void);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object c_load_outline_font(Object,Object);
extern Object c_x11_allocate_x_font(Object,Object);
extern Object c_x11_draw_string_in_font(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_x11_draw_string_in_font_with_clipping(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object change_non_kanji_character_description(int,...);
extern Object character_description_structure_memory_usage(void);
extern Object character_image_structure_memory_usage(void);
extern Object check_if_native_fonts_enabled(void);
extern Object check_if_outline_font_restricted(Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object classify_character_for_text_line_drawing_function(Object);
extern Object clear_optimized_constants(void);
extern Object compute_cost_of_decaching_large_scaled_font_bucket(Object);
extern Object compute_cost_of_decaching_scaled_font(Object);
extern Object compute_lines_per_em_as_text_width(Object,Object);
extern Object compute_minimum_left_edge_of_character_in_line_of_text(Object,Object,Object,Object);
extern Object compute_size_for_character_image(Object);
extern Object compute_size_of_large_scaled_font_bucket(Object);
extern Object compute_size_of_scaled_font(Object);
extern Object compute_true_size_for_character_image(Object);
extern Object compute_true_size_of_scaled_font(Object);
extern Object compute_width_of_text_line(int,...);
extern Object convert_character_bitmap_to_managed_rectangle_array(int,...);
extern Object convert_character_bitmap_to_rectangle_array(int,...);
extern Object convert_character_bitmap_to_rectangle_list(int,...);
extern Object convert_character_rectangle_array_to_character_bitmap(int,...);
extern Object convert_current_scratchpad_raster_to_stored_raster(Object,Object,Object,Object,Object);
extern Object convert_gensym_bitmap_to_managed_rectangle_array(Object,Object,Object);
extern Object convert_gensym_bitmap_to_rectangle_array(Object,Object,Object);
extern Object convert_kanji_code_to_font_file_name_and_index(Object);
extern Object convert_list_to_simple_vector(Object);
extern Object copy_foreign_string_arg_if_appropriate(Object);
extern Object copy_from_bitmap_array_to_character_bitmap(Object,Object,Object,Object,Object);
extern Object copy_from_fontrip_bitmap_to_character_bitmap(Object,Object,Object,Object,Object,Object,Object);
extern Object copy_from_gensym_bitmap_to_character_bitmap(int,...);
extern Object copy_list_using_fonts_conses_1(Object);
extern Object copy_text_string_with_case_conversion(Object,Object);
extern Object copy_tree_using_fonts_conses_1(Object);
extern Object create_fixed14_font(void);
extern Object decache_graph_rendering(Object);
extern Object decache_icon_rendering(Object);
extern Object decache_large_scaled_font_bucket(Object);
extern Object decache_scaled_font(Object);
extern Object define_ab_font(int,...);
extern Object define_stubs_for_kanji_fonts(void);
extern Object delete_character_images_in_one_scaled_font(Object,Object);
extern Object delete_character_images_in_scaled_fonts(void);
extern Object delete_fonts_cons_1(Object,Object);
extern Object delete_fonts_element_1(Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_large_scaled_font_bucket(Object);
extern Object delete_scaled_font(Object);
extern Object direct_structure_method(Object,Object);
extern Object emit_icp_read_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object emit_icp_write_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object enlarge_index_space(Object,Object);
extern Object establish_new_object_index_for_font_map(int,...);
extern Object fill_outline_character_font_bitmap_using_outline_font(Object,Object,Object,Object,Object,Object,Object);
extern Object fill_rectangle_in_character_bitmap(Object,Object,Object,Object,Object,Object);
extern Object find_bitmap_font_match(Object,Object,Object,Object);
extern Object font_digit_line_height_as_text_width(Object);
extern Object font_digit_text_width(Object);
extern Object fonts_cons_1(Object,Object);
extern Object fonts_cons_memory_usage(void);
extern Object fonts_list_2(Object,Object);
extern Object fonts_list_3(Object,Object,Object);
extern Object fonts_list_4(Object,Object,Object,Object);
extern Object fonts_list_trace_hook(Object);
extern Object format_symbol(int,...);
extern Object g2_stream_close(Object);
extern Object g2_stream_open_for_random_access_binary_input(Object);
extern Object g2_stream_read_into_byte_vector(Object,Object,Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_jis_code_to_contiguous(Object);
extern Object gensym_ksc_code_to_contiguous(Object);
extern Object gensym_ksc_to_ksc(Object);
extern Object gensym_make_pathname_with_copied_components(Object,Object,Object,Object,Object,Object,Object);
extern Object gensym_merge_pathnames_function(Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_probe_file(Object);
extern Object get_asian_bitmap_font_file_pathname(Object,Object,Object,Object);
extern Object get_asian_font_file_name(Object);
extern Object get_asian_subfont_information_for_character(Object,Object);
extern Object get_character_bitmap_of_font_character(Object,Object);
extern Object get_cjk_language_of_unicode(Object,Object);
extern Object get_cjk_language_of_unicode_a(Object,Object);
extern Object get_cjk_language_of_unicode_b(Object,Object);
extern Object get_font_han_unification_mode_for_window(Object);
extern Object get_icp_object_index_for_font_map(Object,Object);
extern Object get_jis_row_and_column(Object);
extern Object get_lowercase_symbol_name(Object);
extern Object get_or_make_cyrillic_character_image(Object,Object,Object,Object);
extern Object get_or_make_hebrew_character_image(Object,Object,Object,Object);
extern Object get_or_make_kanji_character_image(Object,Object,Object,Object);
extern Object get_or_make_kanji_character_image_if_any(Object,Object,Object,Object);
extern Object get_or_make_scaled_font_1(Object,Object,Object,Object);
extern Object get_or_make_substitute_kanji_character_image(Object,Object,Object);
extern Object get_or_make_thai_character_image(Object,Object,Object,Object);
extern Object get_or_use_g2_hangul_star_pathname(int,...);
extern Object get_or_use_g2_kanji_star_pathname(int,...);
extern Object get_or_use_g2_minm_star_pathname(int,...);
extern Object get_or_use_tw_hangul_star_pathname(int,...);
extern Object get_or_use_tw_kanji_star_pathname(int,...);
extern Object get_or_use_tw_minm_star_pathname(int,...);
extern Object get_orientation_code(Object);
extern Object get_outline_font_info_list(Object,Object,Object);
extern Object get_outline_handle_and_char_id(int,...);
extern Object get_reflection_and_rotation_from_orientation_code(Object);
extern Object get_set_width_for_character(Object,Object);
extern Object get_unicode_set_width_as_text_width(Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_icp_add_from_line_of_text_to_current_window(void);
extern Object handle_icp_orient_and_paint_line_of_text_to_current_scratchpad_raster(void);
extern Object handle_icp_paint_from_line_of_text_to_current_scratchpad_raster(void);
extern Object icp_error_internal(Object,Object,Object,Object,Object);
extern Object icp_message_functions_icp_prologue(Object);
extern Object initialize_default_g2_hangul_star_pathname(void);
extern Object initialize_default_g2_kanji_star_pathname(void);
extern Object initialize_default_g2_minm_star_pathname(void);
extern Object initialize_default_tw_hangul_star_pathname(void);
extern Object initialize_default_tw_kanji_star_pathname(void);
extern Object initialize_default_tw_minm_star_pathname(void);
extern Object initialize_icp_object_type(Object,Object,Object,Object);
extern Object initialize_icp_object_type_compile(Object,Object,Object);
extern Object initialize_native_font_set_width_equivalence_table(Object);
extern Object initializer_for_pathname_for_disabling_g2_hangul_star_command_line(void);
extern Object initializer_for_pathname_for_disabling_g2_kanji_star_command_line(void);
extern Object initializer_for_pathname_for_disabling_g2_minm_star_command_line(void);
extern Object initializer_for_pathname_for_disabling_tw_hangul_star_command_line(void);
extern Object initializer_for_pathname_for_disabling_tw_kanji_star_command_line(void);
extern Object initializer_for_pathname_for_disabling_tw_minm_star_command_line(void);
extern Object install_lru_element_in_queue(Object,Object);
extern Object instantaneous_icp_reader_byte_count(void);
extern Object instantaneous_icp_writer_byte_count(void);
extern Object internal_make_raster_for_character_using_outline_font_if_possible(Object,Object,Object,Object,Object,Object,Object);
extern Object jis_to_shift_jis(Object);
extern Object kanji_font_cache_vector_137_vector_memory_usage(void);
extern Object large_scaled_font_bucket_structure_memory_usage(void);
extern Object legal_gensym_jis_character_code_p(Object);
extern Object legal_gensym_ksc_character_code_p(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object load_bitmap_data_of_font_character(Object,Object,Object,Object,Object,Object);
extern Object load_bitmap_font_data_if_necessary_1(Object,Object,Object);
extern Object load_chinese_font(void);
extern Object load_hangul_font(void);
extern Object load_outline_font_file(Object,Object,Object);
extern Object make_ab_font(int,...);
extern Object make_ab_font_structure_1(Object,Object,Object,Object,Object,Object);
extern Object make_bitmap_array(int,...);
extern Object make_bitmap_array_internal_1(void);
extern Object make_character_description_1(Object,Object,Object,Object,Object,Object);
extern Object make_character_image_1(Object,Object,Object,Object,Object,Object,Object);
extern Object make_character_image_if_appropriate(Object,Object,Object,Object);
extern Object make_character_raster(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_corresponding_icp_font_map(Object);
extern Object make_corresponding_icp_symbol(Object);
extern Object make_decacheable_large_scaled_font_bucket(int,...);
extern Object make_decacheable_scaled_font(int,...);
extern Object make_fonts_list_1(Object);
extern Object make_gensym_bitmap(Object,Object);
extern Object make_kanji_font_cache_vector(void);
extern Object make_large_scaled_font_bucket(Object,Object);
extern Object make_large_scaled_font_bucket_internal_1(Object,Object);
extern Object make_minimal_character_description_1(Object,Object);
extern Object make_native_font_1(void);
extern Object make_native_font_if_appropriate(Object,Object,Object,Object,Object);
extern Object make_native_font_set_width_equivalence_table(void);
extern Object make_non_kanji_font_vector(void);
extern Object make_outline_character_raster_using_outline_font(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_outline_font_info(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_permanent_ab_font_structure_internal(void);
extern Object make_permanent_bitmap_array_structure_internal(void);
extern Object make_permanent_character_description_structure_internal(void);
extern Object make_permanent_character_image_structure_internal(void);
extern Object make_permanent_kanji_font_cache_vector_137_vector_internal(void);
extern Object make_permanent_large_scaled_font_bucket_structure_internal(void);
extern Object make_permanent_list(Object);
extern Object make_permanent_minimal_character_description_structure_internal(void);
extern Object make_permanent_native_font_set_width_equivalence_table_256_vector_internal(void);
extern Object make_permanent_native_font_structure_internal(void);
extern Object make_permanent_non_kanji_font_vector_257_vector_internal(void);
extern Object make_permanent_scaled_font_kanji_font_cache_vector_1096_vector_internal(void);
extern Object make_permanent_scaled_font_non_kanji_font_vector_2049_vector_internal(void);
extern Object make_permanent_scaled_font_structure_internal(void);
extern Object make_raster_for_character_using_outline_font_if_possible(Object,Object,Object,Object,Object,Object,Object);
extern Object make_scaled_font(Object,Object,Object,Object,Object);
extern Object make_scaled_font_internal_1(Object,Object,Object,Object,Object);
extern Object make_scaled_font_kanji_font_cache_vector(void);
extern Object make_scaled_font_non_kanji_font_vector(void);
extern Object make_thread_array(Object);
extern Object map_halfwidth_to_fullwidth(Object);
extern Object map_to_x_font(int,...);
extern Object map_unicode_to_ab_cyrillic_font_code_if_any(Object);
extern Object map_unicode_to_ab_hebrew_font_code_if_any(Object);
extern Object map_unicode_to_ab_latin_font_code_or_zero(Object);
extern Object map_unicode_to_ab_thai_font_code_if_any(Object);
extern Object memq_function(Object,Object);
extern Object minimal_character_description_structure_memory_usage(void);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_icp_plist(Object,Object,Object);
extern Object native_font_set_width_equivalence_table_256_vector_memory_usage(void);
extern Object native_font_structure_memory_usage(void);
extern Object new_make_ab_font(int,...);
extern Object newline_p(Object);
extern Object non_kanji_font_vector_257_vector_memory_usage(void);
extern Object note_increase_in_size_of_large_scaled_font_bucket(Object);
extern Object note_increase_in_size_of_scaled_font(Object);
extern Object notify_user_at_console(int,...);
extern Object number_of_rectangles_for_character_image(Object,Object,Object);
extern Object obtain_simple_gensym_string(Object);
extern Object offset_position_for_rendering_non_spacing_mark(int,...);
extern Object orient_and_paint_line_of_text_to_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object oriented_x_value(Object,Object,Object);
extern Object oriented_y_value(Object,Object,Object);
extern Object out_kanji_font_cache_vector_137_vectors(void);
extern Object out_native_font_set_width_equivalence_table_256_vectors(void);
extern Object out_non_kanji_font_vector_257_vectors(void);
extern Object out_scaled_font_kanji_font_cache_vector_1096_vectors(void);
extern Object out_scaled_font_non_kanji_font_vector_2049_vectors(void);
extern Object outstanding_bitmap_array_count(void);
extern Object outstanding_character_description_count(void);
extern Object outstanding_character_image_count(void);
extern Object outstanding_fonts_conses(void);
extern Object outstanding_large_scaled_font_bucket_count(void);
extern Object outstanding_minimal_character_description_count(void);
extern Object outstanding_native_font_count(void);
extern Object outstanding_scaled_font_count(void);
extern Object paint_from_line_of_text_to_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object paint_solid_rectangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object);
extern Object print_character_bitmap(int,...);
extern Object provide_pathname_for_launch_time_load(Object,Object,Object,Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object read_asian_bitmap_font_data_from_file(Object,Object,Object,Object);
extern Object read_bitmap_array_from_file(Object,Object,Object);
extern Object read_bitmap_array_from_stream(Object,Object,Object,Object);
extern Object read_bitmap_array_stream_into_byte_vector(Object,Object,Object,Object);
extern Object read_icp_boolean(void);
extern Object read_icp_corresponding_object_index(void);
extern Object read_icp_integer(void);
extern Object read_icp_text_string(void);
extern Object read_icp_unsigned_integer(void);
extern Object reclaim_all_scaled_fonts(int,...);
extern Object reclaim_bitmap_array_1(Object);
extern Object reclaim_cached_structures_for_window(Object);
extern Object reclaim_character_description_1(Object);
extern Object reclaim_character_image_1(Object);
extern Object reclaim_character_raster(Object);
extern Object reclaim_fonts_cons_1(Object);
extern Object reclaim_fonts_list_1(Object);
extern Object reclaim_fonts_list_star_1(Object);
extern Object reclaim_fonts_tree_1(Object);
extern Object reclaim_gensym_bitmap(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_icp_object_map(Object,Object,Object);
extern Object reclaim_icp_object_map_for_font_map(Object);
extern Object reclaim_icp_port_entry(Object,Object,Object,Object);
extern Object reclaim_icp_port_entry_for_font_map(Object,Object);
extern Object reclaim_kanji_font_cache_vector(Object);
extern Object reclaim_large_scaled_font_bucket_1(Object);
extern Object reclaim_large_scaled_font_bucket_contents(Object);
extern Object reclaim_minimal_character_description_1(Object);
extern Object reclaim_native_font_1(Object);
extern Object reclaim_native_font_function(Object);
extern Object reclaim_native_font_set_width_equivalence_table(Object);
extern Object reclaim_non_kanji_font_vector(Object);
extern Object reclaim_non_kanji_font_vector_function(Object);
extern Object reclaim_scaled_font(Object);
extern Object reclaim_scaled_font_1_1(Object);
extern Object reclaim_scaled_font_character_image_cache(Object);
extern Object reclaim_scaled_font_kanji_font_cache_vector(Object);
extern Object reclaim_scaled_font_non_kanji_font_vector(Object);
extern Object reclaim_stored_raster(Object,Object,Object,Object,Object,Object);
extern Object reclaim_temporary_character_bitmap(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_vector_of_byte_vectors(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_lru_element(Object);
extern Object render_character_image(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object render_string_using_native_font(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object replenish_fonts_cons_pool(void);
extern Object replenish_fonts_list_pool(Object);
extern Object replenish_vector_pool_cons_pool(void);
extern Object resumable_icp_pop(void);
extern Object resumable_icp_pop_list_if_end_marker(void);
extern Object resumable_icp_push(Object);
extern Object run_some_informational_tests_for_mhd(void);
extern Object scale_scale(Object,Object,Object);
extern Object scaled_font_kanji_font_cache_vector_1096_vector_memory_usage(void);
extern Object scaled_font_non_kanji_font_vector_2049_vector_memory_usage(void);
extern Object scaled_font_structure_memory_usage(void);
extern Object scalef_function(Object,Object);
extern Object send_icp_add_to_list_of_symbols(Object,Object,Object);
extern Object set_access_form_for_font_map(Object,Object);
extern Object set_current_ab_font(Object);
extern Object set_icp_object_index_for_font_map(Object,Object,Object);
extern Object set_kanji_character_description(Object,Object,Object);
extern Object set_non_kanji_character_description(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object start_writing_icp_message(Object);
extern Object symbol_name_text_string(Object);
extern Object telewindows_authorized_for_chinese_p(Object);
extern Object telewindows_authorized_for_japanese_p(Object);
extern Object telewindows_authorized_for_korean_p(Object);
extern Object test_read_bitmap_array_from_stream(int,...);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object update_object_pool_meters_list(Object);
extern Object warn_of_outline_font_failure_if_appropriate(Object);
extern Object write_icp_boolean(Object);
extern Object write_icp_corresponding_object_index(Object);
extern Object write_icp_integer(Object);
extern Object write_icp_maybe_suspend(void);
extern Object write_icp_text_string(Object);
extern Object write_icp_unsigned_integer(Object);

#else

extern Object accumulate_thrashing_cost_and_decache();
extern Object add_character_description_1();
extern Object add_from_line_of_text_to_current_window();
extern Object add_from_line_of_text_to_current_window_1();
extern Object add_icp_message_handler();
extern Object adjust_to_previous_base_character();
extern Object allocate_byte_vector();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_vector();
extern Object allocate_scratchpad_raster();
extern Object allocate_temporary_character_bitmap();
extern Object asian_font_read_in_already_p();
extern Object assign_corresponding_icp_object_index();
extern Object bitmap_array_structure_memory_usage();
extern Object bytes_per_simple_vector();
extern Object bytes_per_typed_simple_array();
extern Object c_load_outline_font();
extern Object c_x11_allocate_x_font();
extern Object c_x11_draw_string_in_font();
extern Object c_x11_draw_string_in_font_with_clipping();
extern Object change_non_kanji_character_description();
extern Object character_description_structure_memory_usage();
extern Object character_image_structure_memory_usage();
extern Object check_if_native_fonts_enabled();
extern Object check_if_outline_font_restricted();
extern Object chestnut_floorf_function();
extern Object chestnut_modf_function();
extern Object classify_character_for_text_line_drawing_function();
extern Object clear_optimized_constants();
extern Object compute_cost_of_decaching_large_scaled_font_bucket();
extern Object compute_cost_of_decaching_scaled_font();
extern Object compute_lines_per_em_as_text_width();
extern Object compute_minimum_left_edge_of_character_in_line_of_text();
extern Object compute_size_for_character_image();
extern Object compute_size_of_large_scaled_font_bucket();
extern Object compute_size_of_scaled_font();
extern Object compute_true_size_for_character_image();
extern Object compute_true_size_of_scaled_font();
extern Object compute_width_of_text_line();
extern Object convert_character_bitmap_to_managed_rectangle_array();
extern Object convert_character_bitmap_to_rectangle_array();
extern Object convert_character_bitmap_to_rectangle_list();
extern Object convert_character_rectangle_array_to_character_bitmap();
extern Object convert_current_scratchpad_raster_to_stored_raster();
extern Object convert_gensym_bitmap_to_managed_rectangle_array();
extern Object convert_gensym_bitmap_to_rectangle_array();
extern Object convert_kanji_code_to_font_file_name_and_index();
extern Object convert_list_to_simple_vector();
extern Object copy_foreign_string_arg_if_appropriate();
extern Object copy_from_bitmap_array_to_character_bitmap();
extern Object copy_from_fontrip_bitmap_to_character_bitmap();
extern Object copy_from_gensym_bitmap_to_character_bitmap();
extern Object copy_list_using_fonts_conses_1();
extern Object copy_text_string_with_case_conversion();
extern Object copy_tree_using_fonts_conses_1();
extern Object create_fixed14_font();
extern Object decache_graph_rendering();
extern Object decache_icon_rendering();
extern Object decache_large_scaled_font_bucket();
extern Object decache_scaled_font();
extern Object define_ab_font();
extern Object define_stubs_for_kanji_fonts();
extern Object delete_character_images_in_one_scaled_font();
extern Object delete_character_images_in_scaled_fonts();
extern Object delete_fonts_cons_1();
extern Object delete_fonts_element_1();
extern Object delete_gensym_element_1();
extern Object delete_large_scaled_font_bucket();
extern Object delete_scaled_font();
extern Object direct_structure_method();
extern Object emit_icp_read_trace();
extern Object emit_icp_write_trace();
extern Object enlarge_index_space();
extern Object establish_new_object_index_for_font_map();
extern Object fill_outline_character_font_bitmap_using_outline_font();
extern Object fill_rectangle_in_character_bitmap();
extern Object find_bitmap_font_match();
extern Object font_digit_line_height_as_text_width();
extern Object font_digit_text_width();
extern Object fonts_cons_1();
extern Object fonts_cons_memory_usage();
extern Object fonts_list_2();
extern Object fonts_list_3();
extern Object fonts_list_4();
extern Object fonts_list_trace_hook();
extern Object format_symbol();
extern Object g2_stream_close();
extern Object g2_stream_open_for_random_access_binary_input();
extern Object g2_stream_read_into_byte_vector();
extern Object gensym_cons_1();
extern Object gensym_jis_code_to_contiguous();
extern Object gensym_ksc_code_to_contiguous();
extern Object gensym_ksc_to_ksc();
extern Object gensym_make_pathname_with_copied_components();
extern Object gensym_merge_pathnames_function();
extern Object gensym_namestring();
extern Object gensym_probe_file();
extern Object get_asian_bitmap_font_file_pathname();
extern Object get_asian_font_file_name();
extern Object get_asian_subfont_information_for_character();
extern Object get_character_bitmap_of_font_character();
extern Object get_cjk_language_of_unicode();
extern Object get_cjk_language_of_unicode_a();
extern Object get_cjk_language_of_unicode_b();
extern Object get_font_han_unification_mode_for_window();
extern Object get_icp_object_index_for_font_map();
extern Object get_jis_row_and_column();
extern Object get_lowercase_symbol_name();
extern Object get_or_make_cyrillic_character_image();
extern Object get_or_make_hebrew_character_image();
extern Object get_or_make_kanji_character_image();
extern Object get_or_make_kanji_character_image_if_any();
extern Object get_or_make_scaled_font_1();
extern Object get_or_make_substitute_kanji_character_image();
extern Object get_or_make_thai_character_image();
extern Object get_or_use_g2_hangul_star_pathname();
extern Object get_or_use_g2_kanji_star_pathname();
extern Object get_or_use_g2_minm_star_pathname();
extern Object get_or_use_tw_hangul_star_pathname();
extern Object get_or_use_tw_kanji_star_pathname();
extern Object get_or_use_tw_minm_star_pathname();
extern Object get_orientation_code();
extern Object get_outline_font_info_list();
extern Object get_outline_handle_and_char_id();
extern Object get_reflection_and_rotation_from_orientation_code();
extern Object get_set_width_for_character();
extern Object get_unicode_set_width_as_text_width();
extern Object getfq_function_no_default();
extern Object handle_icp_add_from_line_of_text_to_current_window();
extern Object handle_icp_orient_and_paint_line_of_text_to_current_scratchpad_raster();
extern Object handle_icp_paint_from_line_of_text_to_current_scratchpad_raster();
extern Object icp_error_internal();
extern Object icp_message_functions_icp_prologue();
extern Object initialize_default_g2_hangul_star_pathname();
extern Object initialize_default_g2_kanji_star_pathname();
extern Object initialize_default_g2_minm_star_pathname();
extern Object initialize_default_tw_hangul_star_pathname();
extern Object initialize_default_tw_kanji_star_pathname();
extern Object initialize_default_tw_minm_star_pathname();
extern Object initialize_icp_object_type();
extern Object initialize_icp_object_type_compile();
extern Object initialize_native_font_set_width_equivalence_table();
extern Object initializer_for_pathname_for_disabling_g2_hangul_star_command_line();
extern Object initializer_for_pathname_for_disabling_g2_kanji_star_command_line();
extern Object initializer_for_pathname_for_disabling_g2_minm_star_command_line();
extern Object initializer_for_pathname_for_disabling_tw_hangul_star_command_line();
extern Object initializer_for_pathname_for_disabling_tw_kanji_star_command_line();
extern Object initializer_for_pathname_for_disabling_tw_minm_star_command_line();
extern Object install_lru_element_in_queue();
extern Object instantaneous_icp_reader_byte_count();
extern Object instantaneous_icp_writer_byte_count();
extern Object internal_make_raster_for_character_using_outline_font_if_possible();
extern Object jis_to_shift_jis();
extern Object kanji_font_cache_vector_137_vector_memory_usage();
extern Object large_scaled_font_bucket_structure_memory_usage();
extern Object legal_gensym_jis_character_code_p();
extern Object legal_gensym_ksc_character_code_p();
extern Object load_and_initialize_type_description();
extern Object load_bitmap_data_of_font_character();
extern Object load_bitmap_font_data_if_necessary_1();
extern Object load_chinese_font();
extern Object load_hangul_font();
extern Object load_outline_font_file();
extern Object make_ab_font();
extern Object make_ab_font_structure_1();
extern Object make_bitmap_array();
extern Object make_bitmap_array_internal_1();
extern Object make_character_description_1();
extern Object make_character_image_1();
extern Object make_character_image_if_appropriate();
extern Object make_character_raster();
extern Object make_corresponding_icp_font_map();
extern Object make_corresponding_icp_symbol();
extern Object make_decacheable_large_scaled_font_bucket();
extern Object make_decacheable_scaled_font();
extern Object make_fonts_list_1();
extern Object make_gensym_bitmap();
extern Object make_kanji_font_cache_vector();
extern Object make_large_scaled_font_bucket();
extern Object make_large_scaled_font_bucket_internal_1();
extern Object make_minimal_character_description_1();
extern Object make_native_font_1();
extern Object make_native_font_if_appropriate();
extern Object make_native_font_set_width_equivalence_table();
extern Object make_non_kanji_font_vector();
extern Object make_outline_character_raster_using_outline_font();
extern Object make_outline_font_info();
extern Object make_permanent_ab_font_structure_internal();
extern Object make_permanent_bitmap_array_structure_internal();
extern Object make_permanent_character_description_structure_internal();
extern Object make_permanent_character_image_structure_internal();
extern Object make_permanent_kanji_font_cache_vector_137_vector_internal();
extern Object make_permanent_large_scaled_font_bucket_structure_internal();
extern Object make_permanent_list();
extern Object make_permanent_minimal_character_description_structure_internal();
extern Object make_permanent_native_font_set_width_equivalence_table_256_vector_internal();
extern Object make_permanent_native_font_structure_internal();
extern Object make_permanent_non_kanji_font_vector_257_vector_internal();
extern Object make_permanent_scaled_font_kanji_font_cache_vector_1096_vector_internal();
extern Object make_permanent_scaled_font_non_kanji_font_vector_2049_vector_internal();
extern Object make_permanent_scaled_font_structure_internal();
extern Object make_raster_for_character_using_outline_font_if_possible();
extern Object make_scaled_font();
extern Object make_scaled_font_internal_1();
extern Object make_scaled_font_kanji_font_cache_vector();
extern Object make_scaled_font_non_kanji_font_vector();
extern Object make_thread_array();
extern Object map_halfwidth_to_fullwidth();
extern Object map_to_x_font();
extern Object map_unicode_to_ab_cyrillic_font_code_if_any();
extern Object map_unicode_to_ab_hebrew_font_code_if_any();
extern Object map_unicode_to_ab_latin_font_code_or_zero();
extern Object map_unicode_to_ab_thai_font_code_if_any();
extern Object memq_function();
extern Object minimal_character_description_structure_memory_usage();
extern Object mutate_global_property();
extern Object mutate_icp_plist();
extern Object native_font_set_width_equivalence_table_256_vector_memory_usage();
extern Object native_font_structure_memory_usage();
extern Object new_make_ab_font();
extern Object newline_p();
extern Object non_kanji_font_vector_257_vector_memory_usage();
extern Object note_increase_in_size_of_large_scaled_font_bucket();
extern Object note_increase_in_size_of_scaled_font();
extern Object notify_user_at_console();
extern Object number_of_rectangles_for_character_image();
extern Object obtain_simple_gensym_string();
extern Object offset_position_for_rendering_non_spacing_mark();
extern Object orient_and_paint_line_of_text_to_current_scratchpad_raster();
extern Object oriented_x_value();
extern Object oriented_y_value();
extern Object out_kanji_font_cache_vector_137_vectors();
extern Object out_native_font_set_width_equivalence_table_256_vectors();
extern Object out_non_kanji_font_vector_257_vectors();
extern Object out_scaled_font_kanji_font_cache_vector_1096_vectors();
extern Object out_scaled_font_non_kanji_font_vector_2049_vectors();
extern Object outstanding_bitmap_array_count();
extern Object outstanding_character_description_count();
extern Object outstanding_character_image_count();
extern Object outstanding_fonts_conses();
extern Object outstanding_large_scaled_font_bucket_count();
extern Object outstanding_minimal_character_description_count();
extern Object outstanding_native_font_count();
extern Object outstanding_scaled_font_count();
extern Object paint_from_line_of_text_to_current_scratchpad_raster();
extern Object paint_solid_rectangle_in_current_scratchpad_raster();
extern Object print_character_bitmap();
extern Object provide_pathname_for_launch_time_load();
extern Object push_optimized_constant();
extern Object read_asian_bitmap_font_data_from_file();
extern Object read_bitmap_array_from_file();
extern Object read_bitmap_array_from_stream();
extern Object read_bitmap_array_stream_into_byte_vector();
extern Object read_icp_boolean();
extern Object read_icp_corresponding_object_index();
extern Object read_icp_integer();
extern Object read_icp_text_string();
extern Object read_icp_unsigned_integer();
extern Object reclaim_all_scaled_fonts();
extern Object reclaim_bitmap_array_1();
extern Object reclaim_cached_structures_for_window();
extern Object reclaim_character_description_1();
extern Object reclaim_character_image_1();
extern Object reclaim_character_raster();
extern Object reclaim_fonts_cons_1();
extern Object reclaim_fonts_list_1();
extern Object reclaim_fonts_list_star_1();
extern Object reclaim_fonts_tree_1();
extern Object reclaim_gensym_bitmap();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_string();
extern Object reclaim_icp_object_map();
extern Object reclaim_icp_object_map_for_font_map();
extern Object reclaim_icp_port_entry();
extern Object reclaim_icp_port_entry_for_font_map();
extern Object reclaim_kanji_font_cache_vector();
extern Object reclaim_large_scaled_font_bucket_1();
extern Object reclaim_large_scaled_font_bucket_contents();
extern Object reclaim_minimal_character_description_1();
extern Object reclaim_native_font_1();
extern Object reclaim_native_font_function();
extern Object reclaim_native_font_set_width_equivalence_table();
extern Object reclaim_non_kanji_font_vector();
extern Object reclaim_non_kanji_font_vector_function();
extern Object reclaim_scaled_font();
extern Object reclaim_scaled_font_1_1();
extern Object reclaim_scaled_font_character_image_cache();
extern Object reclaim_scaled_font_kanji_font_cache_vector();
extern Object reclaim_scaled_font_non_kanji_font_vector();
extern Object reclaim_stored_raster();
extern Object reclaim_temporary_character_bitmap();
extern Object reclaim_text_string();
extern Object reclaim_vector_of_byte_vectors();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_lru_element();
extern Object render_character_image();
extern Object render_string_using_native_font();
extern Object replenish_fonts_cons_pool();
extern Object replenish_fonts_list_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object resumable_icp_pop();
extern Object resumable_icp_pop_list_if_end_marker();
extern Object resumable_icp_push();
extern Object run_some_informational_tests_for_mhd();
extern Object scale_scale();
extern Object scaled_font_kanji_font_cache_vector_1096_vector_memory_usage();
extern Object scaled_font_non_kanji_font_vector_2049_vector_memory_usage();
extern Object scaled_font_structure_memory_usage();
extern Object scalef_function();
extern Object send_icp_add_to_list_of_symbols();
extern Object set_access_form_for_font_map();
extern Object set_current_ab_font();
extern Object set_icp_object_index_for_font_map();
extern Object set_kanji_character_description();
extern Object set_non_kanji_character_description();
extern Object start_writing_icp_message();
extern Object symbol_name_text_string();
extern Object telewindows_authorized_for_chinese_p();
extern Object telewindows_authorized_for_japanese_p();
extern Object telewindows_authorized_for_korean_p();
extern Object test_read_bitmap_array_from_stream();
extern Object text_string_length();
extern Object text_string_p();
extern Object update_object_pool_meters_list();
extern Object warn_of_outline_font_failure_if_appropriate();
extern Object write_icp_boolean();
extern Object write_icp_corresponding_object_index();
extern Object write_icp_integer();
extern Object write_icp_maybe_suspend();
extern Object write_icp_text_string();
extern Object write_icp_unsigned_integer();

#endif

/* variables/constants */
extern Object Ab_font_prop;
extern Object Ab_latin_font_code_to_bcid_map;
DECLARE_VARIABLE_WITH_SYMBOL(All_ab_font_names, Qall_ab_font_names);
DECLARE_VARIABLE_WITH_SYMBOL(Always_impose_device_set_widths_qm, Qalways_impose_device_set_widths_qm);
extern Object Arial_14;
extern Object Arial_18;
extern Object Arial_24;
extern Object Asian_bitmap_subfont_data_info;
extern Object Asian_font_file_loaded_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Available_fonts_conses, Qavailable_fonts_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_fonts_conses_tail, Qavailable_fonts_conses_tail);
extern Object Available_fonts_conses_tail_vector;
extern Object Available_fonts_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_kanji_font_cache_vector_137_vectors, Qavailable_kanji_font_cache_vector_137_vectors);
extern Object Available_kanji_font_cache_vector_137_vectors_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_native_font_set_width_equivalence_table_256_vectors, Qavailable_native_font_set_width_equivalence_table_256_vectors);
extern Object Available_native_font_set_width_equivalence_table_256_vectors_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_non_kanji_font_vector_257_vectors, Qavailable_non_kanji_font_vector_257_vectors);
extern Object Available_non_kanji_font_vector_257_vectors_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_scaled_font_kanji_font_cache_vector_1096_vectors, Qavailable_scaled_font_kanji_font_cache_vector_1096_vectors);
extern Object Available_scaled_font_kanji_font_cache_vector_1096_vectors_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_scaled_font_non_kanji_font_vector_2049_vectors, Qavailable_scaled_font_non_kanji_font_vector_2049_vectors);
extern Object Available_scaled_font_non_kanji_font_vector_2049_vectors_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Bitmap_array_count, Qbitmap_array_count);
extern Object Bitmap_font_data_handle_prop;
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Cache_chinese_semantics_graph, Qcache_chinese_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_japanese_semantics_graph, Qcache_japanese_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_korean_semantics_graph, Qcache_korean_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_bitmap_arrays, Qchain_of_available_bitmap_arrays);
extern Object Chain_of_available_bitmap_arrays_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_character_descriptions, Qchain_of_available_character_descriptions);
extern Object Chain_of_available_character_descriptions_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_character_images, Qchain_of_available_character_images);
extern Object Chain_of_available_character_images_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_large_scaled_font_buckets, Qchain_of_available_large_scaled_font_buckets);
extern Object Chain_of_available_large_scaled_font_buckets_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_minimal_character_descriptions, Qchain_of_available_minimal_character_descriptions);
extern Object Chain_of_available_minimal_character_descriptions_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_native_fonts, Qchain_of_available_native_fonts);
extern Object Chain_of_available_native_fonts_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_scaled_fonts, Qchain_of_available_scaled_fonts);
extern Object Chain_of_available_scaled_fonts_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Character_bitmap_scratch_list, Qcharacter_bitmap_scratch_list);
DECLARE_VARIABLE_WITH_SYMBOL(Character_description_count, Qcharacter_description_count);
#define Character_image_base_size FIX((SI_Long)32L)
DECLARE_VARIABLE_WITH_SYMBOL(Character_image_count, Qcharacter_image_count);
extern Object Chinesettf_14;
extern Object Chinesettf_18;
extern Object Chinesettf_24;
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
extern Object Command_line_arguments;
extern Object Cons_pool_conses_to_make_at_a_time;
extern Object Corresponding_cyrillic_font_name_and_magnification_prop;
extern Object Corresponding_hebrew_font_name_and_magnification_prop;
extern Object Corresponding_kanji_font_name_and_magnification_prop;
extern Object Corresponding_thai_font_name_and_magnification_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_kanji_font_cache_vector_137_vectors, Qcount_of_kanji_font_cache_vector_137_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_native_font_set_width_equivalence_table_256_vectors, Qcount_of_native_font_set_width_equivalence_table_256_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_non_kanji_font_vector_257_vectors, Qcount_of_non_kanji_font_vector_257_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_scaled_font_kanji_font_cache_vector_1096_vectors, Qcount_of_scaled_font_kanji_font_cache_vector_1096_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_scaled_font_non_kanji_font_vector_2049_vectors, Qcount_of_scaled_font_non_kanji_font_vector_2049_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_ab_font_qm, Qcurrent_ab_font_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_read_trace_level, Qcurrent_icp_read_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_write_trace_level, Qcurrent_icp_write_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_color_value_list, Qcurrent_scratchpad_color_value_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster, Qcurrent_scratchpad_raster);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_depth, Qcurrent_scratchpad_raster_depth);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_height, Qcurrent_scratchpad_raster_height);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_list, Qcurrent_scratchpad_raster_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_tiled_p, Qcurrent_scratchpad_raster_tiled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_type, Qcurrent_scratchpad_raster_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_width, Qcurrent_scratchpad_raster_width);
DECLARE_VARIABLE_WITH_SYMBOL(Current_standard_icp_object_index_space, Qcurrent_standard_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_name, Qcurrent_system_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_temporary_icp_object_index_space, Qcurrent_temporary_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_max_for_stored_raster_qm, Qcurrent_x_max_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_offset_for_stored_raster_qm, Qcurrent_x_offset_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_max_for_stored_raster_qm, Qcurrent_y_max_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_offset_for_stored_raster_qm, Qcurrent_y_offset_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Decache_occurred_since_last_update_qm, Qdecache_occurred_since_last_update_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Default_g2_hangul_star_pathname, Qdefault_g2_hangul_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Default_g2_kanji_star_pathname, Qdefault_g2_kanji_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Default_g2_minm_star_pathname, Qdefault_g2_minm_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Default_tw_hangul_star_pathname, Qdefault_tw_hangul_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Default_tw_kanji_star_pathname, Qdefault_tw_kanji_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Default_tw_minm_star_pathname, Qdefault_tw_minm_star_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Defvar_for_informational_tests_for_mhd, Qdefvar_for_informational_tests_for_mhd);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Enable_native_fonts_qm, Qenable_native_fonts_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Fonts, Qfonts);
DECLARE_VARIABLE_WITH_SYMBOL(Fonts_cons_counter, Qfonts_cons_counter);
extern Object Fonts_cons_counter_vector;
#define Gensym_noncharacter_code FIX((SI_Long)256L)
DECLARE_VARIABLE_WITH_SYMBOL(Get_object_on_kb_workspace_for_item, Qget_object_on_kb_workspace_for_item);
extern Object Graph_rendering_lru_queue;
extern Object Hangulttf_14;
extern Object Hangulttf_18;
extern Object Hangulttf_24;
extern Object Hebrew_14;
extern Object Hebrew_18;
extern Object Hebrew_24;
extern Object Hebrew_72;
extern Object Hm14_native_font_name;
extern Object Hm18_native_font_name;
extern Object Hm24_native_font_name;
extern Object Icon_rendering_lru_queue;
DECLARE_VARIABLE_WITH_SYMBOL(Icp_printing_message_handler_array, Qicp_printing_message_handler_array);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_read_trace_cutoff_level_qm, Qicp_read_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_suspend, Qicp_suspend);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_write_trace_cutoff_level_qm, Qicp_write_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_corresponding_icp_object_making, Qinhibit_corresponding_icp_object_making);
extern Object Isqrt_of_most_positive_fixnum;
#define Jis_level_1_kanji_start FIX((SI_Long)524L)
#define Jis_level_2_kanji_start FIX((SI_Long)3489L)
#define Jis_symbols_1_start FIX((SI_Long)0L)
#define Jis_undefined_start FIX((SI_Long)6879L)
extern Object Kanji_character_depression_prop;
#define Kanji_character_entry_base_size FIX((SI_Long)32L)
extern Object Kanji_character_margin_prop;
#define Kanji_font_cache_sub_vector_length FIX((SI_Long)137L)
DECLARE_VARIABLE_WITH_SYMBOL(Kanji_row_to_font_file_name_mapping_vector, Qkanji_row_to_font_file_name_mapping_vector);
#define Ksc_hangul_start FIX((SI_Long)986L)
#define Ksc_hanja_start FIX((SI_Long)3336L)
#define Ksc_symbols_1_start FIX((SI_Long)0L)
#define Ksc_undefined_start FIX((SI_Long)8224L)
#define Large_scaled_font_bucket_base_size FIX((SI_Long)16L)
DECLARE_VARIABLE_WITH_SYMBOL(Large_scaled_font_bucket_count, Qlarge_scaled_font_bucket_count);
extern Object Large_scaled_font_bucket_decaching_cost_constant;
extern Object Large_scaled_font_bucket_lru_queue;
extern Object Large_scaled_font_bucket_memory_limit_info;
extern Object Lowercase_symbol_name_prop;
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_byte_vector_length;
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
DECLARE_VARIABLE_WITH_SYMBOL(Memory_limit_variable_names_for_decacheable_structures, Qmemory_limit_variable_names_for_decacheable_structures);
DECLARE_VARIABLE_WITH_SYMBOL(Minimal_character_description_count, Qminimal_character_description_count);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Names_and_sizes_for_decacheable_structures, Qnames_and_sizes_for_decacheable_structures);
DECLARE_VARIABLE_WITH_SYMBOL(Native_font_count, Qnative_font_count);
#define Native_font_set_width_equivalence_table_size FIX((SI_Long)256L)
#define Number_of_character_orientations FIX((SI_Long)8L)
DECLARE_VARIABLE_WITH_SYMBOL(On_monochrome_raster_list_p, Qon_monochrome_raster_list_p);
DECLARE_VARIABLE_WITH_SYMBOL(Only_impose_device_set_widths_to_squeeze_qm, Qonly_impose_device_set_widths_to_squeeze_qm);
extern Object Outline_font_failure_warning_sent_qm_prop;
extern Object Outline_font_handle_prop;
extern Object Outline_font_info_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Paint_only_target_monochrome_raster_p, Qpaint_only_target_monochrome_raster_p);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_g2_hangul_star_command_line, Qpathname_for_disabling_g2_hangul_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_g2_kanji_star_command_line, Qpathname_for_disabling_g2_kanji_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_g2_minm_star_command_line, Qpathname_for_disabling_g2_minm_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_tw_hangul_star_command_line, Qpathname_for_disabling_tw_hangul_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_tw_kanji_star_command_line, Qpathname_for_disabling_tw_kanji_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Pathname_for_disabling_tw_minm_star_command_line, Qpathname_for_disabling_tw_minm_star_command_line);
DECLARE_VARIABLE_WITH_SYMBOL(Plist_of_corresponding_icp_object_maps_for_font_maps, Qplist_of_corresponding_icp_object_maps_for_font_maps);
DECLARE_VARIABLE_WITH_SYMBOL(Pop_fonts_stack, Qpop_fonts_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Prefer_bitmap_to_scaled_outline_font_at_full_scale_qm, Qprefer_bitmap_to_scaled_outline_font_at_full_scale_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Prefer_bitmap_to_scaled_outline_font_qm, Qprefer_bitmap_to_scaled_outline_font_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Prefer_bitmap_to_scaled_outline_if_matched_at_any_scale_qm, Qprefer_bitmap_to_scaled_outline_if_matched_at_any_scale_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Process_specific_system_pathname, Qprocess_specific_system_pathname);
#define Protobcid_character_mapping_protocol FIX((SI_Long)2L)
#define Protodirectindex_character_mapping_protocol FIX((SI_Long)7L)
#define Protoextunix_character_mapping_protocol FIX((SI_Long)10L)
#define Protojis_character_mapping_protocol FIX((SI_Long)9L)
#define Protomsl_character_mapping_protocol FIX((SI_Long)4L)
#define Protopsencode_character_mapping_protocol FIX((SI_Long)1L)
#define Protopsname_character_mapping_protocol FIX((SI_Long)6L)
#define Protoshiftjis_character_mapping_protocol FIX((SI_Long)8L)
#define Protosymset_character_mapping_protocol FIX((SI_Long)0L)
#define Protounicode_character_mapping_protocol FIX((SI_Long)3L)
#define Protouser_character_mapping_protocol FIX((SI_Long)5L)
DECLARE_VARIABLE_WITH_SYMBOL(Reclaim_fonts_stack, Qreclaim_fonts_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Reclaimed_temporary_character_bitmaps, Qreclaimed_temporary_character_bitmaps);
DECLARE_VARIABLE_WITH_SYMBOL(Resumable_icp_state, Qresumable_icp_state);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
extern Object Scale_at_or_below_which_to_prefer_jis_bitmaps_qm;
extern Object Scale_at_or_below_which_to_prefer_ksc_bitmaps_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Scaled_font_count, Qscaled_font_count);
extern Object Scaled_font_decaching_cost_constant;
extern Object Scaled_font_lru_queue;
extern Object Scaled_font_memory_limit_info;
DECLARE_VARIABLE_WITH_SYMBOL(Scratch_character_rectangle_array, Qscratch_character_rectangle_array);
DECLARE_VARIABLE_WITH_SYMBOL(Scratchpad_raster, Qscratchpad_raster);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
extern Object Slavic_14;
extern Object Slavic_18;
extern Object Slavic_24;
extern Object Slavic_72;
DECLARE_VARIABLE_WITH_SYMBOL(Special_variable_for_use_value_macro, Qspecial_variable_for_use_value_macro);
#define Standard_resolution_for_gensym_fonts_in_dpi FIX((SI_Long)70L)
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Supported_combining_classes, Qsupported_combining_classes);
extern Object Swiss_721_swa_14;
extern Object Swiss_721_swa_18;
extern Object Swiss_721_swa_24;
DECLARE_VARIABLE_WITH_SYMBOL(System_window, Qsystem_window);
extern Object Thai_14;
extern Object Thai_18;
extern Object Thai_24;
extern Object Thai_72;
extern Object The_type_description_of_ab_font;
extern Object The_type_description_of_bitmap_array;
extern Object The_type_description_of_character_description;
extern Object The_type_description_of_character_image;
extern Object The_type_description_of_large_scaled_font_bucket;
extern Object The_type_description_of_minimal_character_description;
extern Object The_type_description_of_native_font;
extern Object The_type_description_of_scaled_font;
#define Transparent_color_value FIX((SI_Long)16777216L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
#define Unicode_cyrillic_character_block_start FIX((SI_Long)1024L)
#define Unicode_hebrew_character_block_start FIX((SI_Long)1456L)
#define Unicode_hebrew_precomposed_character_block_start FIX((SI_Long)64285L)
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_index_to_slavic_font_direct_index_map, Qunicode_index_to_slavic_font_direct_index_map);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_offset_for_gensym_cyrillic, Qunicode_offset_for_gensym_cyrillic);
#define Unicode_thai_character_block_start FIX((SI_Long)3584L)
#define Unicode_thai_glyph_variants_start FIX((SI_Long)63232L)
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_to_jis_x_0208_map, Qunicode_to_jis_x_0208_map);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_to_ks_c_5601_map, Qunicode_to_ks_c_5601_map);
DECLARE_VARIABLE_WITH_SYMBOL(Use_scaleable_set_widths_qm, Quse_scaleable_set_widths_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_resumable_icp_messages_p, Qwriting_resumable_icp_messages_p);
#define X11_copy FIX((SI_Long)1L)
#define X11_stippled FIX((SI_Long)4L)
#define X11_xor FIX((SI_Long)2L)
