/* frms3.h -- Header File for frms3.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qcons;
extern Object Qvector;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object allocate_frame(Object,Object,Object,Object,Object);
extern Object ancestor_not_activatable_function_p(Object);
extern Object assq_function(Object,Object);
extern Object bottom_edge_of_block_function(Object);
extern Object bytes_per_simple_vector(Object);
extern Object change_edges_of_block(Object,Object,Object,Object,Object);
extern Object clear_blocks_found_in_search(Object);
extern Object clear_cached_explanations(Object);
extern Object clear_optimized_constants(void);
extern Object compare_and_swap_connections(Object,Object,Object);
extern Object compare_and_swap_subblocks(Object,Object,Object);
extern Object compare_and_swap_superblock_qm(Object,Object,Object);
extern Object constant_queue_next(Object,Object);
extern Object constant_queue_push_right(Object,Object);
extern Object copy_list_using_journal_conses_1(Object);
extern Object copy_tree_using_journal_conses_1(Object);
extern Object defer_consistency_analysis_of_item(Object);
extern Object delete_journal_cons_1(Object,Object);
extern Object delete_journal_element_1(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object explanation_related_features_enabled_func_qm(void);
extern Object first_subblock(Object);
extern Object frame_flags_revised_function(void);
extern Object gensym_cons_1(Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object has_only_one_subblock_p(Object);
extern Object icon_slot_group_structure_memory_usage(void);
extern Object initialize_after_reading_for_system_item(Object);
extern Object initialize_default_icon_slot_group(void);
extern Object initialize_for_system_item(Object);
extern Object initialize_frame(Object);
extern Object journal_cons_1(Object,Object);
extern Object journal_cons_memory_usage(void);
extern Object journal_list_2(Object,Object);
extern Object journal_list_3(Object,Object,Object);
extern Object journal_list_4(Object,Object,Object,Object);
extern Object journal_list_trace_hook(Object);
extern Object last_subblock(Object);
extern Object left_edge_of_block_function(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_empty_constant_queue(void);
extern Object make_frame(Object);
extern Object make_frame_internal(Object,Object,Object,Object,Object);
extern Object make_frame_of_class_description(Object);
extern Object make_frame_without_computed_initializations(Object,Object,Object);
extern Object make_icon_slot_group_1(void);
extern Object make_journal_list_1(Object);
extern Object make_permanent_icon_slot_group_structure_internal(void);
extern Object make_thread_array(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_as_preexisting_frame_if_appropriate(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_block_2(Object,Object);
extern Object note_change_to_block_or_struct_or_seq(Object,Object);
extern Object note_change_to_dependent_frame_1(void);
extern Object note_change_to_edges_of_block(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object on_frame_saved_for_kb_frame(Object);
extern Object outstanding_icon_slot_group_count(void);
extern Object outstanding_journal_conses(void);
extern Object permanently_retract_consistency_analysis(Object);
extern Object prepare_to_saving_frame_for_kb_frame(Object);
extern Object push_optimized_constant(Object);
extern Object put_frame_flags(Object,Object,Object);
extern Object reclaim_icon_slot_group_1(Object);
extern Object reclaim_journal_cons_1(Object);
extern Object reclaim_journal_list_1(Object);
extern Object reclaim_journal_list_function(Object);
extern Object reclaim_journal_list_star_1(Object);
extern Object reclaim_journal_tree_1(Object);
extern Object reclaim_journal_tree_function(Object);
extern Object recompile_item(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_journal_cons_pool(void);
extern Object replenish_journal_list_pool(Object);
extern Object schedule_task_to_invoke_existential_rules(Object,Object);
extern Object second_subblock(Object);
extern Object send_ws_representations_item_moved(Object,Object,Object);
extern Object send_ws_representations_item_resized(Object,Object,Object,Object,Object);
extern Object set_block_permanently_changed_function(Object);
extern Object set_edges_of_block(Object,Object,Object,Object,Object);
extern Object set_item_was_created_by_load_function(Object);
extern Object superblock_qm_function(Object);
extern Object update_object_pool_meters_list(Object);
extern Object upgrade_subblocks(Object);

#else

extern Object allocate_frame();
extern Object ancestor_not_activatable_function_p();
extern Object assq_function();
extern Object bottom_edge_of_block_function();
extern Object bytes_per_simple_vector();
extern Object change_edges_of_block();
extern Object clear_blocks_found_in_search();
extern Object clear_cached_explanations();
extern Object clear_optimized_constants();
extern Object compare_and_swap_connections();
extern Object compare_and_swap_subblocks();
extern Object compare_and_swap_superblock_qm();
extern Object constant_queue_next();
extern Object constant_queue_push_right();
extern Object copy_list_using_journal_conses_1();
extern Object copy_tree_using_journal_conses_1();
extern Object defer_consistency_analysis_of_item();
extern Object delete_journal_cons_1();
extern Object delete_journal_element_1();
extern Object direct_structure_method();
extern Object explanation_related_features_enabled_func_qm();
extern Object first_subblock();
extern Object frame_flags_revised_function();
extern Object gensym_cons_1();
extern Object getfq_function_no_default();
extern Object has_only_one_subblock_p();
extern Object icon_slot_group_structure_memory_usage();
extern Object initialize_after_reading_for_system_item();
extern Object initialize_default_icon_slot_group();
extern Object initialize_for_system_item();
extern Object initialize_frame();
extern Object journal_cons_1();
extern Object journal_cons_memory_usage();
extern Object journal_list_2();
extern Object journal_list_3();
extern Object journal_list_4();
extern Object journal_list_trace_hook();
extern Object last_subblock();
extern Object left_edge_of_block_function();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_empty_constant_queue();
extern Object make_frame();
extern Object make_frame_internal();
extern Object make_frame_of_class_description();
extern Object make_frame_without_computed_initializations();
extern Object make_icon_slot_group_1();
extern Object make_journal_list_1();
extern Object make_permanent_icon_slot_group_structure_internal();
extern Object make_thread_array();
extern Object mutate_global_property();
extern Object note_as_preexisting_frame_if_appropriate();
extern Object note_change_to_block_1();
extern Object note_change_to_block_2();
extern Object note_change_to_block_or_struct_or_seq();
extern Object note_change_to_dependent_frame_1();
extern Object note_change_to_edges_of_block();
extern Object on_frame_saved_for_kb_frame();
extern Object outstanding_icon_slot_group_count();
extern Object outstanding_journal_conses();
extern Object permanently_retract_consistency_analysis();
extern Object prepare_to_saving_frame_for_kb_frame();
extern Object push_optimized_constant();
extern Object put_frame_flags();
extern Object reclaim_icon_slot_group_1();
extern Object reclaim_journal_cons_1();
extern Object reclaim_journal_list_1();
extern Object reclaim_journal_list_function();
extern Object reclaim_journal_list_star_1();
extern Object reclaim_journal_tree_1();
extern Object reclaim_journal_tree_function();
extern Object recompile_item();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_journal_cons_pool();
extern Object replenish_journal_list_pool();
extern Object schedule_task_to_invoke_existential_rules();
extern Object second_subblock();
extern Object send_ws_representations_item_moved();
extern Object send_ws_representations_item_resized();
extern Object set_block_permanently_changed_function();
extern Object set_edges_of_block();
extern Object set_item_was_created_by_load_function();
extern Object superblock_qm_function();
extern Object update_object_pool_meters_list();
extern Object upgrade_subblocks();

#endif

/* variables/constants */
extern Object Always_forward_chain_if_possible_flag;
extern Object Ancestor_not_activatable_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Available_journal_conses, Qavailable_journal_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_journal_conses_tail, Qavailable_journal_conses_tail);
extern Object Available_journal_conses_tail_vector;
extern Object Available_journal_conses_vector;
extern Object Backward_chains_to_old_rule_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
extern Object Block_existed_at_start_of_save_flag;
extern Object Block_found_in_search_flag;
extern Object Block_has_been_referenced_flag;
extern Object Block_has_been_written_flag;
extern Object Block_is_currently_being_dragged_flag;
extern Object Block_is_transformed_flag;
extern Object Block_overlap_cache_flag;
extern Object Block_overlap_cache_valid_flag;
extern Object Block_permanently_changed_flag;
extern Object Bytes_per_rtl_ptr;
extern Object Cache_data_for_explanation_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Called_within_clear_text_loading, Qcalled_within_clear_text_loading);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_icon_slot_groups, Qchain_of_available_icon_slot_groups);
extern Object Chain_of_available_icon_slot_groups_vector;
extern Object Class_description_gkbprop;
extern Object Class_of_frame_is_user_defined_flag;
extern Object Compiled_as_new_rule_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Compiled_items_deferred_for_analysis, Qcompiled_items_deferred_for_analysis);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Current_block_of_dependent_frame, Qcurrent_block_of_dependent_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
extern Object Currently_evaluating_formula_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Default_icon_slot_group, Qdefault_icon_slot_group);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_consistency_analysis_qm, Qdefer_consistency_analysis_qm);
extern Object Depth_first_flag;
extern Object Do_not_save_in_kb_flag;
extern Object Do_not_strip_text_flag;
extern Object Dont_backward_chain_flag;
extern Object Failed_flag;
extern Object First_definition_mark_flag;
extern Object Forward_chain_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Frame_being_made, Qframe_being_made);
extern Object Frame_flags_read_flag;
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_v5_mode_windows_p, Qg2_has_v5_mode_windows_p);
extern Object Has_indexed_attributes_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Icon_slot_group_count, Qicon_slot_group_count);
extern Object Immutable_consistency_analysis_flag;
extern Object Initial_rule_flag;
extern Object Invocable_via_backward_chaining_flag;
extern Object Invocable_via_forward_chaining_flag;
extern Object Item_has_icon_views_flag;
extern Object Item_mark_flag;
extern Object Item_was_created_by_load_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Journal_cons_counter, Qjournal_cons_counter);
extern Object Journal_cons_counter_vector;
extern Object Journal_expiration_flag;
extern Object Manually_disabled_flag;
extern Object May_cause_data_seeking_flag;
extern Object May_cause_forward_chaining_flag;
extern Object May_refer_to_inactive_items_flag;
extern Object Module_information_instance_mark_flag;
extern Object Multiple_compilations_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Note_as_kb_state_change_qm, Qnote_as_kb_state_change_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
#define Old_mask_for_saved_frame_flags FIX((SI_Long)7531546L)
extern Object One_shot_flag;
extern Object Opaque_block_flag;
extern Object Overlapping_block_flag;
extern Object Passive_flag;
extern Object Preexisting_frame_flag;
extern Object Previous_render_state_was_xor_flag;
extern Object Queued_by_local_data_server_flag;
extern Object Recent_procedure_flag;
extern Object Render_frame_in_xor_overlay_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
extern Object Runs_while_inactive_flag;
extern Object Savable_kb_workspace_flag;
extern Object Second_definition_mark_flag;
extern Object Self_referenced_flag;
extern Object Sketch_definition_flag;
extern Object Strip_text_flag;
extern Object Table_collected_flag;
extern Object Table_may_not_be_wysiwyg_flag;
extern Object The_type_description_of_icon_slot_group;
extern Object Tracking_item_in_set_flag;
extern Object Tracking_item_mark_flag;
extern Object Transient_flag;
extern Object Was_once_permanent_flag;
extern Object Workspace_was_active_flag;
extern Object Ws_protocol_handle_moves_from_edge_change_p;
extern Object Ws_protocol_trace_p;
