/* frms5.h -- Header File for frms5.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qblock;
extern Object Qcons;
extern Object Qdelete;
extern Object Qget;
extern Object Qmember;
extern Object Qquote;
extern Object Qsequence;
extern Object Qset;
extern Object Qsymbol;
extern Object Qtype;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object ab_subtypep(Object,Object);
extern Object ab_subtypep_1(Object,Object);
extern Object ab_typep_function(Object,Object);
extern Object add_as_frame_with_name(Object,Object);
extern Object add_class_to_environment(int,...);
extern Object add_deleted_item_to_list(Object,Object);
extern Object add_frame_note(int,...);
extern Object add_frame_note_1(Object,Object,Object,Object,Object);
extern Object add_frame_note_particular_to_component_particulars(Object,Object,Object,Object);
extern Object add_frame_note_to_component_particulars(Object,Object,Object,Object,Object,Object);
extern Object add_frame_note_to_component_particulars_1(Object,Object,Object,Object,Object);
extern Object add_frame_representation_if_necessary(Object,Object);
extern Object add_grammar_rules_function(Object);
extern Object add_or_delete_as_workspace_belonging_to_module(Object,Object,Object);
extern Object add_or_delete_class_or_name_for_frame(int,...);
extern Object add_to_directory_of_names(Object,Object);
extern Object add_to_directory_of_names_1(Object,Object,Object,Object,Object,Object,Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object add_to_frame_note_particulars_list_if_necessary_1(Object,Object,Object);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object analyze_compiled_items_for_consistency(Object);
extern Object assq_function(Object,Object);
extern Object cache_evaluator_slot_info(Object);
extern Object change_attribute_description_evaluation_value(Object,Object,Object);
extern Object change_primary_name_of_frame(Object,Object,Object);
extern Object change_secondary_name_of_frame(Object,Object,Object);
extern Object change_slot_description_value_function(Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object check_for_frame_being_embedded(Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clear_optimized_constants(void);
extern Object collect_subclasses(Object);
extern Object compile_module_name_qm_for_slot(int,...);
extern Object compile_uuid_for_slot(int,...);
extern Object component_particulars_with_frame_notes(void);
extern Object conclude_into_attribute_component(int,...);
extern Object convert_text_string_to_text(Object);
extern Object convert_type_or_unit_of_measure_to_type(Object);
extern Object convert_uuid_representation_to_internal(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_evaluation_item_reference(Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_list_using_slot_value_conses_1(Object);
extern Object copy_list_using_stack_change_conses_1(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_tree_using_stack_change_conses_1(Object);
extern Object decache_dynamic_menus(int,...);
extern Object default_category_slot_access_committer(Object,Object,Object);
extern Object default_category_slot_access_extracter(Object,Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object delete_all_frame_notes_for_component_particular(Object,Object);
extern Object delete_as_frame_with_name(Object,Object);
extern Object delete_duplicates_from_list(int,...);
extern Object delete_frame(Object);
extern Object delete_frame_note_from_all_component_particulars_of_frame(Object,Object);
extern Object delete_frame_note_from_component_particulars(Object,Object,Object);
extern Object delete_frame_note_from_component_particulars_1(Object,Object,Object,Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_frame_note_if_any_1(Object,Object);
extern Object delete_frame_note_particular_from_component_particulars(Object,Object,Object,Object);
extern Object delete_frame_notes_of_types_in_list(Object,Object,Object);
extern Object delete_from_directory_of_names(Object,Object);
extern Object delete_from_directory_of_names_1(Object,Object,Object,Object,Object,Object);
extern Object delete_from_frame_note_particulars_list(Object,Object,Object);
extern Object delete_from_frame_note_particulars_list_1(Object,Object);
extern Object delete_from_frame_note_particulars_list_2(Object,Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_image_planes_workspace_is_on(Object);
extern Object delete_multiple_frame_notes_if_any(Object,Object);
extern Object delete_representation(int,...);
extern Object delete_slot_value_element_1(Object,Object);
extern Object delete_stack_change_cons_1(Object,Object);
extern Object delete_stack_change_element_1(Object,Object);
extern Object denote_component_of_block(int,...);
extern Object detach_table_from_frames_it_represents(Object);
extern Object do_block_specific_deletion_stuff(Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object embedded_frame_parent_status(Object,Object);
extern Object ensure_named_frame_is_first_fetched(Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_item_reference_uuid(Object);
extern Object find_similar_class_name(Object);
extern Object find_similar_slot_name(Object,Object);
extern Object flatten_first_n_distinct_elements_of_menu_tree(Object);
extern Object frame_has_note_p(Object,Object);
extern Object frame_incomplete_p(Object);
extern Object frame_not_bad_p(Object);
extern Object frame_note_of_type_for_component_particular_p(Object,Object);
extern Object frame_note_subtype_p(Object,Object);
extern Object frame_serial_number_for_connection_function(Object);
extern Object frame_status_and_notes_reflects_flags_of_frame_p(Object);
extern Object frame_status_union(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object get_alias_for_slot_name_if_any(Object,Object);
extern Object get_attribute_description_evaluation_value(Object,Object);
extern Object get_attribute_description_from_class_description(Object,Object,Object);
extern Object get_cached_debugging_name(Object);
extern Object get_containing_module(Object);
extern Object get_directory_contents(Object);
extern Object get_entry_for_component_particulars(Object,Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_item_active(Object);
extern Object get_item_notes(Object);
extern Object get_item_or_item_list_for_uuid(Object);
extern Object get_item_reference_for_new_uuid(void);
extern Object get_item_reference_for_uuid(Object,Object,Object);
extern Object get_item_status(Object);
extern Object get_kb_parent_information(Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_module_block_is_in(Object);
extern Object get_or_make_entry_for_component_particulars(Object,Object);
extern Object get_particulars_of_frame_note_from_component_particulars(Object,Object,Object);
extern Object get_particulars_of_frame_notes_for_component_particulars(Object);
extern Object get_primary_name_for_frame_if_any(Object);
extern Object get_property_value_function(int,...);
extern Object get_property_value_in_object_configuration(Object,Object,Object);
extern Object get_reference_to_item(Object);
extern Object get_reference_to_item_no_copy(Object);
extern Object get_secondary_name_for_frame_if_any(Object);
extern Object get_slot_component_putter_if_any(Object,Object,Object,Object,Object);
extern Object get_slot_component_value(Object,Object,Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_slot_evaluation_value_1(Object,Object,Object);
extern Object get_slot_feature_if_any(int,...);
extern Object get_slot_name_for_alias_if_any(Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_unique_name_for_frame_if_any(Object);
extern Object getfq_function(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object grammar_cons_1(Object,Object);
extern Object grammar_list_2(Object,Object);
extern Object in_directory_of_names_1(Object,Object,Object,Object,Object,Object,Object);
extern Object in_directory_of_names_p(Object,Object);
extern Object inform_ui_client_interfaces_of_top_level_workspace_assignment_change(Object,Object,Object);
extern Object initial_containing_module(Object);
extern Object initial_item_active(Object);
extern Object initial_item_notes(Object);
extern Object initial_item_status(Object);
extern Object initialize_for_kb_workspace(Object);
extern Object install_item_in_model_if_models_used(Object);
extern Object intern_text_string(int,...);
extern Object item_uuid(Object);
extern Object item_workspace_p(Object);
extern Object journal_cons_1(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object maintain_authorized_user(Object);
extern Object make_evaluator_slot_info_1(void);
extern Object make_menu_of_names_from_directory(Object,Object);
extern Object make_menu_of_names_from_directory_if_few_enough(Object,Object,Object);
extern Object make_menu_of_names_unless_too_many_qm(Object,Object,Object,Object);
extern Object make_menu_tree_of_names_from_directory(Object,Object,Object,Object,Object);
extern Object make_new_name_for_frame(int,...);
extern Object make_stack_change_list_1(Object);
extern Object malformed_symbol_name_p(Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object name_or_names_like_p(Object,Object);
extern Object name_or_names_same_p(Object,Object);
extern Object native_menu_bar_p(Object);
extern Object native_menu_bar_really_needs_updating_p(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_dependent_frame_1(void);
extern Object note_deletion_of_block_1(Object);
extern Object note_deletion_of_block_2(Object);
extern Object note_deletion_of_block_for_selection(Object);
extern Object note_modification_of_module_for_clear_text(Object,Object);
extern Object note_name_change_for_block(Object,Object,Object);
extern Object note_name_change_for_kb_workspace(Object,Object,Object);
extern Object note_permanent_change(Object,Object);
extern Object note_permanent_change_to_component(Object,Object,Object,Object);
extern Object note_use_of_text_string_in_phrase(Object);
extern Object notify_user(int,...);
extern Object outstanding_stack_change_conses(void);
extern Object push_optimized_constant(Object);
extern Object put_attribute_description_value(Object,Object,Object,Object);
extern Object put_initialization_interval_where_slot_is_absent(Object,Object);
extern Object put_kb_name_for_workspace_where_slot_is_absent(Object,Object);
extern Object put_kb_name_where_slot_is_absent(Object,Object);
extern Object put_module_this_is_part_of_qm(Object,Object,Object);
extern Object put_name_or_names_for_frame(Object,Object,Object);
extern Object put_new_uuid(Object);
extern Object put_uuid(Object,Object,Object);
extern Object reclaim_evaluation_item_reference(Object);
extern Object reclaim_frame_representations_value(Object,Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_frame_status_and_notes_value(Object,Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_list_if_list(Object);
extern Object reclaim_grammar_cons_1(Object);
extern Object reclaim_grammar_list_1(Object);
extern Object reclaim_grammar_tree_1(Object);
extern Object reclaim_grammar_tree_function(Object);
extern Object reclaim_items_deleted_since_load_or_save(void);
extern Object reclaim_journal_list_1(Object);
extern Object reclaim_name_or_names_for_frame_value(Object,Object);
extern Object reclaim_relation_instances(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_function(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_function(Object);
extern Object reclaim_stack_change_cons_1(Object);
extern Object reclaim_stack_change_list_1(Object);
extern Object reclaim_stack_change_list_star_1(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_uuid_value(Object,Object);
extern Object reclaim_wide_string(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_as_block_being_dragged(Object);
extern Object remove_as_subblock_if_necessary(int,...);
extern Object remove_block_from_native_views(Object);
extern Object remove_element_from_all_g2_lists(Object,Object);
extern Object remove_from_frame_representations_if_present(Object,Object);
extern Object remove_transient_relation_instances(Object,Object);
extern Object replenish_stack_change_cons_pool(void);
extern Object replenish_stack_change_list_pool(Object);
extern Object reserve_words(Object);
extern Object send_representation_deletion_notification(Object);
extern Object serve_item_p(Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_slot_component_value(Object,Object,Object,Object,Object,Object);
extern Object set_slot_description_value_without_noting(Object,Object,Object);
extern Object set_slot_value_and_update_representations(int,...);
extern Object set_slot_value_function(Object,Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_equal_p(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_number_p(Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_cons_memory_usage(void);
extern Object stack_change_list_2(Object,Object);
extern Object stack_change_list_3(Object,Object,Object);
extern Object stack_change_list_4(Object,Object,Object,Object);
extern Object stack_change_list_trace_hook(Object);
extern Object subtype_p_using_type_descriptions(Object,Object);
extern Object subworkspace_is_named_like_its_parent_p(Object);
extern Object superior_frame(Object);
extern Object symbol_name_text_string(Object);
extern Object text_category_slot_access_committer(Object,Object,Object);
extern Object text_category_slot_access_extracter(Object,Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object text_string_substring(Object,Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_frame_notes(Object,Object);
extern Object twrite_general_string(Object);
extern Object twrite_symbol(int,...);
extern Object twrite_uuid_printed_representation_as_string(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_as_frame_with_name(Object,Object,Object);
extern Object update_frame_name_references(Object);
extern Object update_frame_status(Object,Object,Object);
extern Object update_frame_status_of_parent_of_embedded_frame(Object,Object,Object,Object);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_frame_notes(Object);
extern Object update_representations_of_slot_value(int,...);
extern Object update_subscriptions_from_virtual_attribute_change(Object,Object,Object);
extern Object user_attribute_slot_description_or_virtual_attribute(Object,Object,Object,Object);
extern Object valid_uuid_p(Object);
extern Object virtual_attribute_defined_for_class_qm(Object,Object);
extern Object write_frame_notes_of_inferior_frame(Object);
extern Object write_frame_status_and_notes_from_slot(Object,Object);
extern Object write_module_name_qm_from_slot(Object,Object);
extern Object write_status_of_component_particulars(Object,Object);
extern Object write_uuid_from_slot(Object,Object);

#else

extern Object ab_subtypep();
extern Object ab_subtypep_1();
extern Object ab_typep_function();
extern Object add_as_frame_with_name();
extern Object add_class_to_environment();
extern Object add_deleted_item_to_list();
extern Object add_frame_note();
extern Object add_frame_note_1();
extern Object add_frame_note_particular_to_component_particulars();
extern Object add_frame_note_to_component_particulars();
extern Object add_frame_note_to_component_particulars_1();
extern Object add_frame_representation_if_necessary();
extern Object add_grammar_rules_function();
extern Object add_or_delete_as_workspace_belonging_to_module();
extern Object add_or_delete_class_or_name_for_frame();
extern Object add_to_directory_of_names();
extern Object add_to_directory_of_names_1();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object add_to_frame_note_particulars_list_if_necessary_1();
extern Object add_virtual_attribute();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object analyze_compiled_items_for_consistency();
extern Object assq_function();
extern Object cache_evaluator_slot_info();
extern Object change_attribute_description_evaluation_value();
extern Object change_primary_name_of_frame();
extern Object change_secondary_name_of_frame();
extern Object change_slot_description_value_function();
extern Object change_slot_value();
extern Object check_for_frame_being_embedded();
extern Object check_if_superior_classes_are_defined();
extern Object clear_optimized_constants();
extern Object collect_subclasses();
extern Object compile_module_name_qm_for_slot();
extern Object compile_uuid_for_slot();
extern Object component_particulars_with_frame_notes();
extern Object conclude_into_attribute_component();
extern Object convert_text_string_to_text();
extern Object convert_type_or_unit_of_measure_to_type();
extern Object convert_uuid_representation_to_internal();
extern Object copy_constant_wide_string_given_length();
extern Object copy_evaluation_item_reference();
extern Object copy_evaluation_value_1();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_list_using_slot_value_conses_1();
extern Object copy_list_using_stack_change_conses_1();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_tree_using_stack_change_conses_1();
extern Object decache_dynamic_menus();
extern Object default_category_slot_access_committer();
extern Object default_category_slot_access_extracter();
extern Object define_type_specification_explicit_complex_type();
extern Object delete_all_frame_notes_for_component_particular();
extern Object delete_as_frame_with_name();
extern Object delete_duplicates_from_list();
extern Object delete_frame();
extern Object delete_frame_note_from_all_component_particulars_of_frame();
extern Object delete_frame_note_from_component_particulars();
extern Object delete_frame_note_from_component_particulars_1();
extern Object delete_frame_note_if_any();
extern Object delete_frame_note_if_any_1();
extern Object delete_frame_note_particular_from_component_particulars();
extern Object delete_frame_notes_of_types_in_list();
extern Object delete_from_directory_of_names();
extern Object delete_from_directory_of_names_1();
extern Object delete_from_frame_note_particulars_list();
extern Object delete_from_frame_note_particulars_list_1();
extern Object delete_from_frame_note_particulars_list_2();
extern Object delete_gensym_element_1();
extern Object delete_image_planes_workspace_is_on();
extern Object delete_multiple_frame_notes_if_any();
extern Object delete_representation();
extern Object delete_slot_value_element_1();
extern Object delete_stack_change_cons_1();
extern Object delete_stack_change_element_1();
extern Object denote_component_of_block();
extern Object detach_table_from_frames_it_represents();
extern Object do_block_specific_deletion_stuff();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object embedded_frame_parent_status();
extern Object ensure_named_frame_is_first_fetched();
extern Object eval_cons_1();
extern Object evaluation_item_reference_uuid();
extern Object find_similar_class_name();
extern Object find_similar_slot_name();
extern Object flatten_first_n_distinct_elements_of_menu_tree();
extern Object frame_has_note_p();
extern Object frame_incomplete_p();
extern Object frame_not_bad_p();
extern Object frame_note_of_type_for_component_particular_p();
extern Object frame_note_subtype_p();
extern Object frame_serial_number_for_connection_function();
extern Object frame_status_and_notes_reflects_flags_of_frame_p();
extern Object frame_status_union();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object get_alias_for_slot_name_if_any();
extern Object get_attribute_description_evaluation_value();
extern Object get_attribute_description_from_class_description();
extern Object get_cached_debugging_name();
extern Object get_containing_module();
extern Object get_directory_contents();
extern Object get_entry_for_component_particulars();
extern Object get_instance_with_name_if_any();
extern Object get_item_active();
extern Object get_item_notes();
extern Object get_item_or_item_list_for_uuid();
extern Object get_item_reference_for_new_uuid();
extern Object get_item_reference_for_uuid();
extern Object get_item_status();
extern Object get_kb_parent_information();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_module_block_is_in();
extern Object get_or_make_entry_for_component_particulars();
extern Object get_particulars_of_frame_note_from_component_particulars();
extern Object get_particulars_of_frame_notes_for_component_particulars();
extern Object get_primary_name_for_frame_if_any();
extern Object get_property_value_function();
extern Object get_property_value_in_object_configuration();
extern Object get_reference_to_item();
extern Object get_reference_to_item_no_copy();
extern Object get_secondary_name_for_frame_if_any();
extern Object get_slot_component_putter_if_any();
extern Object get_slot_component_value();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_slot_evaluation_value_1();
extern Object get_slot_feature_if_any();
extern Object get_slot_name_for_alias_if_any();
extern Object get_slot_value_function();
extern Object get_symbol_properties_function();
extern Object get_unique_name_for_frame_if_any();
extern Object getfq_function();
extern Object getfq_function_no_default();
extern Object grammar_cons_1();
extern Object grammar_list_2();
extern Object in_directory_of_names_1();
extern Object in_directory_of_names_p();
extern Object inform_ui_client_interfaces_of_top_level_workspace_assignment_change();
extern Object initial_containing_module();
extern Object initial_item_active();
extern Object initial_item_notes();
extern Object initial_item_status();
extern Object initialize_for_kb_workspace();
extern Object install_item_in_model_if_models_used();
extern Object intern_text_string();
extern Object item_uuid();
extern Object item_workspace_p();
extern Object journal_cons_1();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object maintain_authorized_user();
extern Object make_evaluator_slot_info_1();
extern Object make_menu_of_names_from_directory();
extern Object make_menu_of_names_from_directory_if_few_enough();
extern Object make_menu_of_names_unless_too_many_qm();
extern Object make_menu_tree_of_names_from_directory();
extern Object make_new_name_for_frame();
extern Object make_stack_change_list_1();
extern Object malformed_symbol_name_p();
extern Object memq_function();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object name_or_names_like_p();
extern Object name_or_names_same_p();
extern Object native_menu_bar_p();
extern Object native_menu_bar_really_needs_updating_p();
extern Object note_change_to_block_1();
extern Object note_change_to_dependent_frame_1();
extern Object note_deletion_of_block_1();
extern Object note_deletion_of_block_2();
extern Object note_deletion_of_block_for_selection();
extern Object note_modification_of_module_for_clear_text();
extern Object note_name_change_for_block();
extern Object note_name_change_for_kb_workspace();
extern Object note_permanent_change();
extern Object note_permanent_change_to_component();
extern Object note_use_of_text_string_in_phrase();
extern Object notify_user();
extern Object outstanding_stack_change_conses();
extern Object push_optimized_constant();
extern Object put_attribute_description_value();
extern Object put_initialization_interval_where_slot_is_absent();
extern Object put_kb_name_for_workspace_where_slot_is_absent();
extern Object put_kb_name_where_slot_is_absent();
extern Object put_module_this_is_part_of_qm();
extern Object put_name_or_names_for_frame();
extern Object put_new_uuid();
extern Object put_uuid();
extern Object reclaim_evaluation_item_reference();
extern Object reclaim_frame_representations_value();
extern Object reclaim_frame_serial_number();
extern Object reclaim_frame_status_and_notes_value();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_list_if_list();
extern Object reclaim_grammar_cons_1();
extern Object reclaim_grammar_list_1();
extern Object reclaim_grammar_tree_1();
extern Object reclaim_grammar_tree_function();
extern Object reclaim_items_deleted_since_load_or_save();
extern Object reclaim_journal_list_1();
extern Object reclaim_name_or_names_for_frame_value();
extern Object reclaim_relation_instances();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_function();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_function();
extern Object reclaim_stack_change_cons_1();
extern Object reclaim_stack_change_list_1();
extern Object reclaim_stack_change_list_star_1();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_text_string();
extern Object reclaim_uuid_value();
extern Object reclaim_wide_string();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_as_block_being_dragged();
extern Object remove_as_subblock_if_necessary();
extern Object remove_block_from_native_views();
extern Object remove_element_from_all_g2_lists();
extern Object remove_from_frame_representations_if_present();
extern Object remove_transient_relation_instances();
extern Object replenish_stack_change_cons_pool();
extern Object replenish_stack_change_list_pool();
extern Object reserve_words();
extern Object send_representation_deletion_notification();
extern Object serve_item_p();
extern Object set_evaluation_value_to_category_function();
extern Object set_lookup_slot_value_1();
extern Object set_property_value_function();
extern Object set_slot_component_value();
extern Object set_slot_description_value_without_noting();
extern Object set_slot_value_and_update_representations();
extern Object set_slot_value_function();
extern Object set_slot_value_to_evaluation_value_function();
extern Object slot_value_cons_1();
extern Object slot_value_equal_p();
extern Object slot_value_list_2();
extern Object slot_value_number_p();
extern Object stack_change_cons_1();
extern Object stack_change_cons_memory_usage();
extern Object stack_change_list_2();
extern Object stack_change_list_3();
extern Object stack_change_list_4();
extern Object stack_change_list_trace_hook();
extern Object subtype_p_using_type_descriptions();
extern Object subworkspace_is_named_like_its_parent_p();
extern Object superior_frame();
extern Object symbol_name_text_string();
extern Object text_category_slot_access_committer();
extern Object text_category_slot_access_extracter();
extern Object text_string_length();
extern Object text_string_p();
extern Object text_string_substring();
extern Object tformat();
extern Object tformat_text_string();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_frame_notes();
extern Object twrite_general_string();
extern Object twrite_symbol();
extern Object twrite_uuid_printed_representation_as_string();
extern Object type_error_in_setter();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object unicode_lowercase_if_uppercase();
extern Object update_all_representations_of_slot();
extern Object update_as_frame_with_name();
extern Object update_frame_name_references();
extern Object update_frame_status();
extern Object update_frame_status_of_parent_of_embedded_frame();
extern Object update_images_of_block();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_frame_notes();
extern Object update_representations_of_slot_value();
extern Object update_subscriptions_from_virtual_attribute_change();
extern Object user_attribute_slot_description_or_virtual_attribute();
extern Object valid_uuid_p();
extern Object virtual_attribute_defined_for_class_qm();
extern Object write_frame_notes_of_inferior_frame();
extern Object write_frame_status_and_notes_from_slot();
extern Object write_module_name_qm_from_slot();
extern Object write_status_of_component_particulars();
extern Object write_uuid_from_slot();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Abbreviate_frame_notes_p, Qabbreviate_frame_notes_p);
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Any_cached_evaluator_slot_info_p, Qany_cached_evaluator_slot_info_p);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_user_class_description, Qauthorized_user_class_description);
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_stack_change_conses, Qavailable_stack_change_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_stack_change_conses_tail, Qavailable_stack_change_conses_tail);
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_with_relation_instances_from_kb_read, Qblocks_with_relation_instances_from_kb_read);
extern Object Bytes_per_rtl_ptr;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_post_class_description, Qconnection_post_class_description);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Directory_nil, Qdirectory_nil);
extern Object Directory_of_names_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Dynamic_menus_modification_tick, Qdynamic_menus_modification_tick);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Explanation_table_class_description, Qexplanation_table_class_description);
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Flattened_menu_maximum_remaining_elements, Qflattened_menu_maximum_remaining_elements);
DECLARE_VARIABLE_WITH_SYMBOL(Flattened_menu_reverse, Qflattened_menu_reverse);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_count, Qframe_note_count);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index, Qframe_note_index);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index_has_been_written_qm, Qframe_note_index_has_been_written_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index_skip, Qframe_note_index_skip);
extern Object Frame_note_writer_1_prop;
extern Object Frame_or_frames_with_this_name_kbprop;
extern Object Inferior_frame_note_types_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Items_deleted_since_load_or_save, Qitems_deleted_since_load_or_save);
DECLARE_VARIABLE_WITH_SYMBOL(Items_deleted_since_load_or_save_tail, Qitems_deleted_since_load_or_save_tail);
DECLARE_VARIABLE_WITH_SYMBOL(Just_update_representations_of_slot_value, Qjust_update_representations_of_slot_value);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags, Qkb_flags);
extern Object Kb_specific_property_names;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
extern Object List_of_embedding_slots;
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
#define Maximum_length_of_menu_of_names FIX((SI_Long)10000L)
extern Object Menu_too_many_instances;
DECLARE_VARIABLE_WITH_SYMBOL(Method_class_description, Qmethod_class_description);
extern Object Namelike_slot_p_prop;
extern Object No_component_value;
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Pseudo_class_slot_description, Qpseudo_class_slot_description);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_kb_p, Qreading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Releasing_kb_qm, Qreleasing_kb_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_subtable_class_description, Qsimulation_subtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_change_cons_counter, Qstack_change_cons_counter);
extern Object Stack_change_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
extern Object Superior_frame_note_type_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
extern Object Workstations_in_service;
