/* g2-gsi.h -- Header File for g2-gsi.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qand;
extern Object Qcar;
extern Object Qeq;
extern Object Qerror;
extern Object Qfloat;
extern Object Qinteger;
extern Object Kkey;
extern Object Qmember;
extern Object Qnot;
extern Object Qnumber;
extern Object Qquote;
extern Object Qstring;
extern Object Qsymbol;
extern Object Ktest;
extern Object Qthe;
extern Object Qunsigned_byte;
extern Object Qvariable;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_for_gsi_data_service(Object);
extern Object activate_for_gsi_interface(Object);
extern Object activate_for_gsi_message_service(Object);
extern Object activate_g2_to_g2_data_interface_with_or_without_configuration(Object);
extern Object activate_gsi_interface(Object,Object);
extern Object activate_gsi_interface_with_socket(Object,Object,Object);
extern Object activate_if_possible_and_propagate_for_gsi_interface(Object);
extern Object activate_variables_for_gsi_interface(Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_sensor_to_group_if_it_fits(Object,Object,Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_structure(Object);
extern Object assign_corresponding_icp_object_index(Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object body_of_deactivate_for_g2_to_g2_data_interface(Object);
extern Object body_of_deactivate_for_gsi_interface(Object,Object);
extern Object break_out_of_debug_messages(void);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object change_attribute_description_evaluation_value(Object,Object,Object);
extern Object change_gsi_interface_status(Object,Object);
extern Object change_slot_value(int,...);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object cleanup_for_gsi_interface(Object);
extern Object clear_optimized_constants(void);
extern Object clear_pending_gsi_sensor_request(Object);
extern Object collect_modifications_and_modify_gsi_sensor_definition(Object,Object);
extern Object collect_subclasses(Object);
extern Object compile_attributes_which_identify_a_network_item_reference_for_slot(int,...);
extern Object compile_gsi_application_name_symbol_for_slot(int,...);
extern Object compile_gsi_host_configuration_for_slot(int,...);
extern Object compile_gsi_interface_name_for_slot(int,...);
extern Object compile_gsi_variable_grouping_specification_for_slot(int,...);
extern Object compile_network_attribute_translation(Object);
extern Object compile_network_class_attribute_translation(Object);
extern Object compile_options_for_item_reference_for_slot(int,...);
extern Object compile_process_initialization_string_for_slot(int,...);
extern Object compile_timeout_interval_or_default_for_slot(int,...);
extern Object compile_timeout_interval_or_default_or_none_for_slot(int,...);
extern Object constant_queue_push_right(Object,Object);
extern Object convert_text_string_to_text(Object);
extern Object copy_as_wide_string(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_managed_float(Object);
extern Object copy_managed_long(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_tree_using_slot_value_conses_1(Object);
extern Object copy_wide_string(Object);
extern Object datum_ok_for_g2_list_or_array_p(Object,Object);
extern Object deactivate_dataservice_for_gsi_data_service(Object);
extern Object deactivate_for_gsi_data_service(Object);
extern Object deactivate_for_gsi_interface(Object);
extern Object deactivate_for_gsi_message_service(Object);
extern Object def_data_server(int,...);
extern Object def_data_server_pretty_printer(Object,Object);
extern Object define_or_configure_gsi_sensor(Object,Object,Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object delete_frame(Object);
extern Object delete_gsi_element_1(Object,Object);
extern Object delete_icp_element_1(Object,Object);
extern Object deregister_all_icp_connection_loss_callbacks(Object);
extern Object deregister_item_with_socket(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object disconnect_socket_from_gsi_interface(Object);
extern Object enable_control_of_disable_interleaving_of_large_messages(void);
extern Object enable_references_for_item_passing(void);
extern Object encode_unix_time_after_failure(Object,Object,Object,Object,Object,Object);
extern Object end_icp_message_group(void);
extern Object enqueue_gsi_request_for_sensor(Object,Object,Object);
extern Object establish_new_object_index_for_gsi_icp_interface(int,...);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_quantity_eq(Object,Object);
extern Object evaluation_quantity_gt(Object,Object);
extern Object evaluation_quantity_gt_eq(Object,Object);
extern Object evaluation_quantity_lt(Object,Object);
extern Object evaluation_quantity_sl_eq(Object,Object);
extern Object evaluation_value_eql(int,...);
extern Object finalize_gsi_connection(Object,Object);
extern Object finalize_gsi_connection_1(Object);
extern Object fix_5_0_beta_icp_connection_forms_if_necessary(Object,Object,Object);
extern Object fixnum_time_interval(Object);
extern Object flush_and_shutdown_icp_socket(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object framep_function(Object);
extern Object future_task_schedule_2(Object);
extern Object g2_list_insert_at_end(int,...);
extern Object g2_set_gsi_interface_interval_to_poll_external_system(Object,Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object get_attribute_description_evaluation_value(Object,Object);
extern Object get_attribute_description_from_class_description(Object,Object,Object);
extern Object get_current_value(Object,Object);
extern Object get_decoded_real_time(void);
extern Object get_effective_data_type(Object);
extern Object get_gsi_identifying_attribute_values(Object,Object);
extern Object get_gsi_interface_for_gsi_sensor_if_any(Object);
extern Object get_gsi_interface_status(Object);
extern Object get_icp_object_index_for_gsi_icp_interface(Object,Object);
extern Object get_icp_object_index_for_registered_item(Object,Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_gsi_sensor(Object,Object);
extern Object get_primary_name_for_frame_if_any(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object gsi_begin_collecting_data(Object,Object);
extern Object gsi_collect_one_shot_data(Object);
extern Object gsi_cons_1(Object,Object);
extern Object gsi_data_service_p_function(Object);
extern Object gsi_deliver_messages(Object,Object,Object,Object,Object);
extern Object gsi_ds_put_value(Object,Object,Object,Object);
extern Object gsi_icp_interface_structure_memory_usage(void);
extern Object gsi_icp_socket_connected_p(Object);
extern Object gsi_initialize_data_server(void);
extern Object gsi_interface_connects_while_inactive_p(Object);
extern Object gsi_interface_current_icp_socket(Object);
extern Object gsi_interface_p_function(Object);
extern Object gsi_item_attribute_value(Object,Object);
extern Object gsi_list_3(Object,Object,Object);
extern Object gsi_list_4(Object,Object,Object,Object);
extern Object gsi_message_service_p_function(Object);
extern Object gsi_pause_data_server_qm(void);
extern Object gsi_process_gsi_interfaces(void);
extern Object gsi_receive_status_for_gsi_sensor(Object,Object);
extern Object gsi_receive_value_for_gsi_sensor(Object,Object,Object,Object,Object);
extern Object gsi_receive_value_for_ping_request(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object gsi_register_item(Object,Object,Object);
extern Object gsi_requests_accept_data_calls_p(void);
extern Object gsi_reset_data_server_qm(void);
extern Object gsi_resume_data_server_qm(void);
extern Object gsi_set_external_variable(Object,Object,Object);
extern Object gsi_shut_down_data_server_qm(void);
extern Object gsi_start_data_server_qm(void);
extern Object gsi_stop_collecting_data(Object);
extern Object gsi_stop_collecting_data_from_known_interface(Object,Object);
extern Object handle_gsi_connect_attempt_failure(Object,Object);
extern Object handle_gsi_shut_down_connection(Object,Object);
extern Object handle_update_to_located_sensor_attribute(int,...);
extern Object handle_update_to_sensor_attribute(Object,Object,Object,Object,Object,Object);
extern Object handle_update_to_sensor_data_type(Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_in_progress_p(Object);
extern Object icp_connection_is_secure(Object);
extern Object icp_connection_open_p(Object);
extern Object icp_error_internal(Object,Object,Object,Object,Object);
extern Object initialize_after_reading_for_gsi_interface(Object);
extern Object initialize_icp_object_type(Object,Object,Object,Object);
extern Object initialize_icp_object_type_compile(Object,Object,Object);
extern Object install_true_value_update(Object,Object,Object,Object,Object);
extern Object install_true_value_updates_for_gsi(Object,Object,Object);
extern Object invoke_rules_for_attribute_change_chaining(Object,Object,Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object localnetp(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_corresponding_icp_gsi_icp_interface(Object);
extern Object make_gsi_icp_interface_1(Object,Object,Object,Object);
extern Object make_gsi_list_1(Object);
extern Object make_icp_connection(int,...);
extern Object make_permanent_gsi_icp_interface_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_sensor_group_structure_internal(void);
extern Object make_permanent_sensor_groups_header_structure_internal(void);
extern Object make_sensor_group_1(Object,Object,Object);
extern Object make_sensor_groups_header_1(void);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_thread_array(Object);
extern Object manually_disable_for_gsi_interface(Object);
extern Object manually_enable_for_gsi_interface(Object);
extern Object maybe_begin_collecting_data_for_interface(Object);
extern Object maybe_declare_all_gsi_sensors(void);
extern Object maybe_stop_collecting_data_for_interface(Object);
extern Object maybe_warn_about_missing_identifying_attributes(Object,Object);
extern Object memq_function(Object,Object);
extern Object mutate_g2_array(Object,Object,Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_ancestor_manually_enabled_for_gsi_interface(Object);
extern Object note_ancestor_not_activatable_for_gsi_interface(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_name_change_for_gsi_data_service(Object,Object,Object);
extern Object note_name_change_for_gsi_interface(Object,Object,Object);
extern Object note_runs_while_inactive_change_for_network_interface(Object);
extern Object notify_user_1(Object);
extern Object outstanding_gsi_icp_interface_count(void);
extern Object outstanding_sensor_group_count(void);
extern Object outstanding_sensor_groups_header_count(void);
extern Object parse_gsi_schedule_tree(void);
extern Object phrase_cons(Object,Object);
extern Object post_on_message_board(int,...);
extern Object print_constant(int,...);
extern Object process_gsi_sensor_values(Object);
extern Object process_requests_for_gsi_interfaces(void);
extern Object push_optimized_constant(Object);
extern Object put_attribute_value(int,...);
extern Object put_attributes_which_identify_a_sensor_where_slot_is_absent(Object,Object);
extern Object put_class_of_remote_interface_where_slot_is_absent(Object,Object);
extern Object put_creation_attributes_where_slot_is_absent(Object,Object);
extern Object put_current_evaluation_value(Object,Object,Object,Object,Object);
extern Object put_current_value(int,...);
extern Object put_data_server_for_messages(Object,Object,Object);
extern Object put_grouping_specification(Object,Object,Object);
extern Object put_gsi_connection_configuration(Object,Object,Object);
extern Object put_gsi_interface_name(Object,Object,Object);
extern Object put_gsi_interface_status(Object,Object,Object);
extern Object put_gsi_interface_timeout_period_where_slot_is_absent(Object,Object);
extern Object put_gsi_variable_status(Object,Object,Object);
extern Object put_identifying_attributes(Object,Object,Object);
extern Object put_interval_to_poll_external_system(Object,Object,Object);
extern Object put_item_reference_options_where_slot_is_absent(Object,Object);
extern Object put_names_of_remote_interface_where_slot_is_absent(Object,Object);
extern Object put_remote_process_initialization_string(Object,Object,Object);
extern Object put_sensor_grouping_specification_where_slot_is_absent(Object,Object);
extern Object put_sensor_in_new_sensor_group(Object,Object,Object,Object,Object);
extern Object raw_stack_error_named_error(Object,Object);
extern Object reclaim_evaluation_quantity(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gsi_collection_interval_value(Object,Object);
extern Object reclaim_gsi_cons_1(Object);
extern Object reclaim_gsi_icp_interface_1(Object);
extern Object reclaim_gsi_icp_interface_function(Object);
extern Object reclaim_gsi_list_1(Object);
extern Object reclaim_gsi_list_with_evaluation_values(Object);
extern Object reclaim_gsi_value_vector(Object);
extern Object reclaim_icp_object_map(Object,Object,Object);
extern Object reclaim_icp_object_map_for_gsi_icp_interface(Object);
extern Object reclaim_icp_port_entry(Object,Object,Object,Object);
extern Object reclaim_icp_port_entry_for_gsi_icp_interface(Object,Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_list_of_block_snapshots(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_sensor_group_1(Object);
extern Object reclaim_sensor_groups_header_1(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_text_string(Object);
extern Object reconfigure_gsi_sensor_attribute(Object);
extern Object record_block_for_tformat(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object register_icp_connection_loss_callback(Object,Object);
extern Object register_item_with_socket(Object,Object,Object);
extern Object remove_pending_requests_from_gsi_interface(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object reset_gsi_collection_interval(Object);
extern Object resumable_icp_pop(void);
extern Object resumable_icp_pop_list_if_end_marker(void);
extern Object resumable_icp_push(Object);
extern Object resume_activation(Object);
extern Object schedule_data_server_accept_data_calls(void);
extern Object send_icp_begin_sensor_list(void);
extern Object send_icp_define_gsi_interface(Object);
extern Object send_icp_define_gsi_sensor(Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_end_sensor_list(void);
extern Object send_icp_get_values_for_sensors_in_list(void);
extern Object send_icp_initialize_data_server(Object);
extern Object send_icp_load_sensor_list_element(Object,Object,Object);
extern Object send_icp_modify_gsi_sensor_definition(Object,Object,Object,Object,Object);
extern Object send_icp_pause_data_server(void);
extern Object send_icp_register_corresponding_icp_object(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_reset_data_server(void);
extern Object send_icp_resume_data_server(void);
extern Object send_icp_send_data_values_if_any(Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_set_values_for_sensors_in_list(void);
extern Object send_icp_start_data_server(void);
extern Object send_icp_stop_sending_values_for_sensors_in_list(void);
extern Object send_icp_write_user_message_string(Object,Object,Object,Object);
extern Object send_message_series_for_gsi_request(Object,Object);
extern Object sensor_group_structure_memory_usage(void);
extern Object sensor_groups_header_structure_memory_usage(void);
extern Object serve_unique_item_or_evaluation_value_of_role(Object,Object,Object,Object);
extern Object set_access_form_for_gsi_icp_interface(Object,Object);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_icp_object_index_for_gsi_icp_interface(Object,Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_value_function(Object,Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object setup_network_connection_for_connect(int,...);
extern Object shutdown_icp_socket_connection(int,...);
extern Object slot_value_compiler_for_timeout_interval_or_default(Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object stop_processing_on_gsi_interface(Object);
extern Object string_or_symbol_equal(Object,Object);
extern Object suspend_activation(Object);
extern Object task_to_detect_failure(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tformat_text_string(int,...);
extern Object time_slice_expired_p(void);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_fixnum(Object);
extern Object twrite_general_string(Object);
extern Object twrite_symbol(int,...);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_of_variable_or_parameter_value(Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object update_gsi_interface_countdown_timer(Object);
extern Object update_gsi_variable_to_interface_connections(Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_slot_value(int,...);
extern Object valid_icp_connection_specification_from_parse(Object,Object);
extern Object write_attributes_which_identify_a_network_item_reference_from_slot(Object,Object);
extern Object write_class_attribute_translation(Object);
extern Object write_gsi_application_name_symbol_from_slot(Object,Object);
extern Object write_gsi_host_configuration_from_slot(Object,Object);
extern Object write_gsi_interface_name_from_slot(Object,Object);
extern Object write_gsi_interface_status_code_from_slot(Object,Object);
extern Object write_gsi_variable_grouping_specification_from_slot(Object,Object);
extern Object write_gsi_variable_status_code_from_slot(Object,Object);
extern Object write_icp_maybe_suspend(void);
extern Object write_interface_warning_message_level_from_slot(Object,Object);
extern Object write_message_group_upon_gsi_interface_activation(Object,Object,Object);
extern Object write_name_denotation(Object);
extern Object write_name_or_class_qualified_name(Object);
extern Object write_options_for_item_reference_from_slot(Object,Object);
extern Object write_process_initialization_string_from_slot(Object,Object);
extern Object write_timeout_interval_or_default_from_slot(Object,Object);
extern Object write_timeout_interval_or_default_or_none_from_slot(Object,Object);

#else

extern Object activate_for_gsi_data_service();
extern Object activate_for_gsi_interface();
extern Object activate_for_gsi_message_service();
extern Object activate_g2_to_g2_data_interface_with_or_without_configuration();
extern Object activate_gsi_interface();
extern Object activate_gsi_interface_with_socket();
extern Object activate_if_possible_and_propagate_for_gsi_interface();
extern Object activate_variables_for_gsi_interface();
extern Object add_class_to_environment();
extern Object add_grammar_rules_function();
extern Object add_sensor_to_group_if_it_fits();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_structure();
extern Object assign_corresponding_icp_object_index();
extern Object assq_function();
extern Object body_of_deactivate_for_g2_to_g2_data_interface();
extern Object body_of_deactivate_for_gsi_interface();
extern Object break_out_of_debug_messages();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object c_native_clock_ticks_or_cache();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object change_attribute_description_evaluation_value();
extern Object change_gsi_interface_status();
extern Object change_slot_value();
extern Object check_if_superior_classes_are_defined();
extern Object cleanup_for_gsi_interface();
extern Object clear_optimized_constants();
extern Object clear_pending_gsi_sensor_request();
extern Object collect_modifications_and_modify_gsi_sensor_definition();
extern Object collect_subclasses();
extern Object compile_attributes_which_identify_a_network_item_reference_for_slot();
extern Object compile_gsi_application_name_symbol_for_slot();
extern Object compile_gsi_host_configuration_for_slot();
extern Object compile_gsi_interface_name_for_slot();
extern Object compile_gsi_variable_grouping_specification_for_slot();
extern Object compile_network_attribute_translation();
extern Object compile_network_class_attribute_translation();
extern Object compile_options_for_item_reference_for_slot();
extern Object compile_process_initialization_string_for_slot();
extern Object compile_timeout_interval_or_default_for_slot();
extern Object compile_timeout_interval_or_default_or_none_for_slot();
extern Object constant_queue_push_right();
extern Object convert_text_string_to_text();
extern Object copy_as_wide_string();
extern Object copy_constant_wide_string_given_length();
extern Object copy_evaluation_value_1();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_managed_float();
extern Object copy_managed_long();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_tree_using_slot_value_conses_1();
extern Object copy_wide_string();
extern Object datum_ok_for_g2_list_or_array_p();
extern Object deactivate_dataservice_for_gsi_data_service();
extern Object deactivate_for_gsi_data_service();
extern Object deactivate_for_gsi_interface();
extern Object deactivate_for_gsi_message_service();
extern Object def_data_server();
extern Object def_data_server_pretty_printer();
extern Object define_or_configure_gsi_sensor();
extern Object define_type_specification_explicit_complex_type();
extern Object delete_frame();
extern Object delete_gsi_element_1();
extern Object delete_icp_element_1();
extern Object deregister_all_icp_connection_loss_callbacks();
extern Object deregister_item_with_socket();
extern Object direct_structure_method();
extern Object disconnect_socket_from_gsi_interface();
extern Object enable_control_of_disable_interleaving_of_large_messages();
extern Object enable_references_for_item_passing();
extern Object encode_unix_time_after_failure();
extern Object end_icp_message_group();
extern Object enqueue_gsi_request_for_sensor();
extern Object establish_new_object_index_for_gsi_icp_interface();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object evaluation_quantity_eq();
extern Object evaluation_quantity_gt();
extern Object evaluation_quantity_gt_eq();
extern Object evaluation_quantity_lt();
extern Object evaluation_quantity_sl_eq();
extern Object evaluation_value_eql();
extern Object finalize_gsi_connection();
extern Object finalize_gsi_connection_1();
extern Object fix_5_0_beta_icp_connection_forms_if_necessary();
extern Object fixnum_time_interval();
extern Object flush_and_shutdown_icp_socket();
extern Object frame_serial_number_setf_helper_1();
extern Object framep_function();
extern Object future_task_schedule_2();
extern Object g2_list_insert_at_end();
extern Object g2_set_gsi_interface_interval_to_poll_external_system();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_list_3();
extern Object get_attribute_description_evaluation_value();
extern Object get_attribute_description_from_class_description();
extern Object get_current_value();
extern Object get_decoded_real_time();
extern Object get_effective_data_type();
extern Object get_gsi_identifying_attribute_values();
extern Object get_gsi_interface_for_gsi_sensor_if_any();
extern Object get_gsi_interface_status();
extern Object get_icp_object_index_for_gsi_icp_interface();
extern Object get_icp_object_index_for_registered_item();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_gsi_sensor();
extern Object get_primary_name_for_frame_if_any();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_function();
extern Object get_slot_value_if_any_function();
extern Object get_symbol_properties_function();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object gsi_begin_collecting_data();
extern Object gsi_collect_one_shot_data();
extern Object gsi_cons_1();
extern Object gsi_data_service_p_function();
extern Object gsi_deliver_messages();
extern Object gsi_ds_put_value();
extern Object gsi_icp_interface_structure_memory_usage();
extern Object gsi_icp_socket_connected_p();
extern Object gsi_initialize_data_server();
extern Object gsi_interface_connects_while_inactive_p();
extern Object gsi_interface_current_icp_socket();
extern Object gsi_interface_p_function();
extern Object gsi_item_attribute_value();
extern Object gsi_list_3();
extern Object gsi_list_4();
extern Object gsi_message_service_p_function();
extern Object gsi_pause_data_server_qm();
extern Object gsi_process_gsi_interfaces();
extern Object gsi_receive_status_for_gsi_sensor();
extern Object gsi_receive_value_for_gsi_sensor();
extern Object gsi_receive_value_for_ping_request();
extern Object gsi_register_item();
extern Object gsi_requests_accept_data_calls_p();
extern Object gsi_reset_data_server_qm();
extern Object gsi_resume_data_server_qm();
extern Object gsi_set_external_variable();
extern Object gsi_shut_down_data_server_qm();
extern Object gsi_start_data_server_qm();
extern Object gsi_stop_collecting_data();
extern Object gsi_stop_collecting_data_from_known_interface();
extern Object handle_gsi_connect_attempt_failure();
extern Object handle_gsi_shut_down_connection();
extern Object handle_update_to_located_sensor_attribute();
extern Object handle_update_to_sensor_attribute();
extern Object handle_update_to_sensor_data_type();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_in_progress_p();
extern Object icp_connection_is_secure();
extern Object icp_connection_open_p();
extern Object icp_error_internal();
extern Object initialize_after_reading_for_gsi_interface();
extern Object initialize_icp_object_type();
extern Object initialize_icp_object_type_compile();
extern Object install_true_value_update();
extern Object install_true_value_updates_for_gsi();
extern Object invoke_rules_for_attribute_change_chaining();
extern Object load_and_initialize_type_description();
extern Object localnetp();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_corresponding_icp_gsi_icp_interface();
extern Object make_gsi_icp_interface_1();
extern Object make_gsi_list_1();
extern Object make_icp_connection();
extern Object make_permanent_gsi_icp_interface_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_sensor_group_structure_internal();
extern Object make_permanent_sensor_groups_header_structure_internal();
extern Object make_sensor_group_1();
extern Object make_sensor_groups_header_1();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_thread_array();
extern Object manually_disable_for_gsi_interface();
extern Object manually_enable_for_gsi_interface();
extern Object maybe_begin_collecting_data_for_interface();
extern Object maybe_declare_all_gsi_sensors();
extern Object maybe_stop_collecting_data_for_interface();
extern Object maybe_warn_about_missing_identifying_attributes();
extern Object memq_function();
extern Object mutate_g2_array();
extern Object mutate_global_property();
extern Object note_ancestor_manually_enabled_for_gsi_interface();
extern Object note_ancestor_not_activatable_for_gsi_interface();
extern Object note_change_to_block_1();
extern Object note_name_change_for_gsi_data_service();
extern Object note_name_change_for_gsi_interface();
extern Object note_runs_while_inactive_change_for_network_interface();
extern Object notify_user_1();
extern Object outstanding_gsi_icp_interface_count();
extern Object outstanding_sensor_group_count();
extern Object outstanding_sensor_groups_header_count();
extern Object parse_gsi_schedule_tree();
extern Object phrase_cons();
extern Object post_on_message_board();
extern Object print_constant();
extern Object process_gsi_sensor_values();
extern Object process_requests_for_gsi_interfaces();
extern Object push_optimized_constant();
extern Object put_attribute_value();
extern Object put_attributes_which_identify_a_sensor_where_slot_is_absent();
extern Object put_class_of_remote_interface_where_slot_is_absent();
extern Object put_creation_attributes_where_slot_is_absent();
extern Object put_current_evaluation_value();
extern Object put_current_value();
extern Object put_data_server_for_messages();
extern Object put_grouping_specification();
extern Object put_gsi_connection_configuration();
extern Object put_gsi_interface_name();
extern Object put_gsi_interface_status();
extern Object put_gsi_interface_timeout_period_where_slot_is_absent();
extern Object put_gsi_variable_status();
extern Object put_identifying_attributes();
extern Object put_interval_to_poll_external_system();
extern Object put_item_reference_options_where_slot_is_absent();
extern Object put_names_of_remote_interface_where_slot_is_absent();
extern Object put_remote_process_initialization_string();
extern Object put_sensor_grouping_specification_where_slot_is_absent();
extern Object put_sensor_in_new_sensor_group();
extern Object raw_stack_error_named_error();
extern Object reclaim_evaluation_quantity();
extern Object reclaim_evaluation_value();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gsi_collection_interval_value();
extern Object reclaim_gsi_cons_1();
extern Object reclaim_gsi_icp_interface_1();
extern Object reclaim_gsi_icp_interface_function();
extern Object reclaim_gsi_list_1();
extern Object reclaim_gsi_list_with_evaluation_values();
extern Object reclaim_gsi_value_vector();
extern Object reclaim_icp_object_map();
extern Object reclaim_icp_object_map_for_gsi_icp_interface();
extern Object reclaim_icp_port_entry();
extern Object reclaim_icp_port_entry_for_gsi_icp_interface();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_list_of_block_snapshots();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_sensor_group_1();
extern Object reclaim_sensor_groups_header_1();
extern Object reclaim_slot_value();
extern Object reclaim_text_string();
extern Object reconfigure_gsi_sensor_attribute();
extern Object record_block_for_tformat();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object register_icp_connection_loss_callback();
extern Object register_item_with_socket();
extern Object remove_pending_requests_from_gsi_interface();
extern Object replenish_lookup_cons_pool();
extern Object reset_gsi_collection_interval();
extern Object resumable_icp_pop();
extern Object resumable_icp_pop_list_if_end_marker();
extern Object resumable_icp_push();
extern Object resume_activation();
extern Object schedule_data_server_accept_data_calls();
extern Object send_icp_begin_sensor_list();
extern Object send_icp_define_gsi_interface();
extern Object send_icp_define_gsi_sensor();
extern Object send_icp_end_sensor_list();
extern Object send_icp_get_values_for_sensors_in_list();
extern Object send_icp_initialize_data_server();
extern Object send_icp_load_sensor_list_element();
extern Object send_icp_modify_gsi_sensor_definition();
extern Object send_icp_pause_data_server();
extern Object send_icp_register_corresponding_icp_object();
extern Object send_icp_reset_data_server();
extern Object send_icp_resume_data_server();
extern Object send_icp_send_data_values_if_any();
extern Object send_icp_set_values_for_sensors_in_list();
extern Object send_icp_start_data_server();
extern Object send_icp_stop_sending_values_for_sensors_in_list();
extern Object send_icp_write_user_message_string();
extern Object send_message_series_for_gsi_request();
extern Object sensor_group_structure_memory_usage();
extern Object sensor_groups_header_structure_memory_usage();
extern Object serve_unique_item_or_evaluation_value_of_role();
extern Object set_access_form_for_gsi_icp_interface();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_icp_object_index_for_gsi_icp_interface();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_property_value_function();
extern Object set_skip_list_entry();
extern Object set_slot_value_function();
extern Object set_slot_value_to_evaluation_value_function();
extern Object setup_network_connection_for_connect();
extern Object shutdown_icp_socket_connection();
extern Object slot_value_compiler_for_timeout_interval_or_default();
extern Object slot_value_cons_1();
extern Object slot_value_list_3();
extern Object stop_processing_on_gsi_interface();
extern Object string_or_symbol_equal();
extern Object suspend_activation();
extern Object task_to_detect_failure();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tformat_text_string();
extern Object time_slice_expired_p();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_fixnum();
extern Object twrite_general_string();
extern Object twrite_symbol();
extern Object type_error_in_setter();
extern Object type_specification_of_variable_or_parameter_value();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object update_gsi_interface_countdown_timer();
extern Object update_gsi_variable_to_interface_connections();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_slot_value();
extern Object valid_icp_connection_specification_from_parse();
extern Object write_attributes_which_identify_a_network_item_reference_from_slot();
extern Object write_class_attribute_translation();
extern Object write_gsi_application_name_symbol_from_slot();
extern Object write_gsi_host_configuration_from_slot();
extern Object write_gsi_interface_name_from_slot();
extern Object write_gsi_interface_status_code_from_slot();
extern Object write_gsi_variable_grouping_specification_from_slot();
extern Object write_gsi_variable_status_code_from_slot();
extern Object write_icp_maybe_suspend();
extern Object write_interface_warning_message_level_from_slot();
extern Object write_message_group_upon_gsi_interface_activation();
extern Object write_name_denotation();
extern Object write_name_or_class_qualified_name();
extern Object write_options_for_item_reference_from_slot();
extern Object write_process_initialization_string_from_slot();
extern Object write_timeout_interval_or_default_from_slot();
extern Object write_timeout_interval_or_default_or_none_from_slot();

#endif

/* variables/constants */
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Cache_gsi_semantics_graph, Qcache_gsi_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
#define Cancel_collection FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gsi_icp_interfaces, Qchain_of_available_gsi_icp_interfaces);
extern Object Chain_of_available_gsi_icp_interfaces_vector;
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_sensor_groups, Qchain_of_available_sensor_groups);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_sensor_groups_headers, Qchain_of_available_sensor_groups_headers);
extern Object Chain_of_available_sensor_groups_headers_vector;
extern Object Chain_of_available_sensor_groups_vector;
extern Object Class_description_gkbprop;
#define Collect_one_now FIX((SI_Long)0L)
DECLARE_VARIABLE_WITH_SYMBOL(Collected_updates_to_sensor_attributes, Qcollected_updates_to_sensor_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_updates_to_sensor_attributes_p, Qcollecting_updates_to_sensor_attributes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_instance, Qcurrent_computation_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
extern Object Data_server_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_parameters, Qdata_server_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_reset, Qdebugging_reset);
#define Default_gsi_interface_countdown_timer_limit FIX((SI_Long)10L)
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
DECLARE_VARIABLE_WITH_SYMBOL(Deleting_ui_client_interfaces_for_clear_kb, Qdeleting_ui_client_interfaces_for_clear_kb);
DECLARE_VARIABLE_WITH_SYMBOL(Deregister_and_register_item_p, Qderegister_and_register_item_p);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(G2_array_class_description, Qg2_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_list_class_description, Qg2_list_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
extern Object Global_daylight_saving_time_adjustment;
#define Gsi_64bit_float_type_tag FIX((SI_Long)6L)
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_application_name, Qgsi_application_name);
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_connection_checkup_interval_in_ms, Qgsi_connection_checkup_interval_in_ms);
extern Object Gsi_connection_established;
extern Object Gsi_connection_initializing;
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_icp_interface_count, Qgsi_icp_interface_count);
#define Gsi_integer_type_tag FIX((SI_Long)1L)
#define Gsi_interface_assumed_dead FIX((SI_Long)-1L)
#define Gsi_interface_icp_connection_dead FIX((SI_Long)-2L)
#define Gsi_interface_initializing FIX((SI_Long)0L)
#define Gsi_interface_running_ok FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_interface_status_changed_p, Qgsi_interface_status_changed_p);
#define Gsi_interface_waiting_for_response FIX((SI_Long)1L)
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_interfaces_to_process_head, Qgsi_interfaces_to_process_head);
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_interfaces_to_process_tail, Qgsi_interfaces_to_process_tail);
#define Gsi_logical_type_tag FIX((SI_Long)5L)
#define Gsi_long_type_tag FIX((SI_Long)51L)
#define Gsi_null_type_tag FIX((SI_Long)0L)
#define Gsi_string_type_tag FIX((SI_Long)4L)
#define Gsi_symbol_type_tag FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
extern Object Icp_connection_awaiting_acknowledgement;
extern Object Icp_connection_closed;
extern Object Icp_connection_running;
DECLARE_VARIABLE_WITH_SYMBOL(Icp_socket_transacting_message_group, Qicp_socket_transacting_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_sockets_now_initializing_gsi, Qicp_sockets_now_initializing_gsi);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_suspend, Qicp_suspend);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_corresponding_icp_object_making, Qinhibit_corresponding_icp_object_making);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
extern Object Instances_specific_to_this_class_kbprop;
#define Iterations_for_gsi_temporary_float_processing FIX((SI_Long)100L)
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_all_gsi_interfaces, Qlist_of_all_gsi_interfaces);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_gsi_values_to_process_head, Qlist_of_gsi_values_to_process_head);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_gsi_values_to_process_tail, Qlist_of_gsi_values_to_process_tail);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Maintaining_gsi_interface_status_changed_p, Qmaintaining_gsi_interface_status_changed_p);
DECLARE_VARIABLE_WITH_SYMBOL(Max_gsi_sensors_in_a_group, Qmax_gsi_sensors_in_a_group);
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
#define No_error FIX((SI_Long)0L)
DECLARE_VARIABLE_WITH_SYMBOL(No_grouping_tag_for_grouping_specification, Qno_grouping_tag_for_grouping_specification);
extern Object No_specific_property_value;
#define No_value_to_set Qnil
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Overflow_byte_count, Qoverflow_byte_count);
DECLARE_VARIABLE_WITH_SYMBOL(Parameter_class_description, Qparameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_current_task, Qpriority_of_current_task);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Remote_gsi_interface_list, Qremote_gsi_interface_list);
DECLARE_VARIABLE_WITH_SYMBOL(Resumable_icp_state, Qresumable_icp_state);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Sensor_group_count, Qsensor_group_count);
DECLARE_VARIABLE_WITH_SYMBOL(Sensor_groups_header_count, Qsensor_groups_header_count);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Snapshots_of_related_blocks, Qsnapshots_of_related_blocks);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Task_scheduled_to_process_gsi_values_qm, Qtask_scheduled_to_process_gsi_values_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Task_to_process_gsi_interfaces, Qtask_to_process_gsi_interfaces);
DECLARE_VARIABLE_WITH_SYMBOL(Task_to_process_gsi_values, Qtask_to_process_gsi_values);
extern Object The_type_description_of_gsi_icp_interface;
extern Object The_type_description_of_sensor_group;
extern Object The_type_description_of_sensor_groups_header;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Use_new_message_group_for_send_icp_enlarge_index_space_p, Quse_new_message_group_for_send_icp_enlarge_index_space_p);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_class_description, Qvariable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variables_that_did_not_have_values, Qvariables_that_did_not_have_values);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_resumable_icp_messages_p, Qwriting_resumable_icp_messages_p);
