/* g2dsnp.h -- Header File for g2dsnp.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qerror;
extern Object Qsecond;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_target_nupec_synchronization(Object);
extern Object add_class_to_environment(int,...);
extern Object add_icp_message_handler(Object,Object);
extern Object add_icp_message_type_code(Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_float_array(int,...);
extern Object assign_corresponding_icp_object_index(Object,Object,Object);
extern Object break_out_of_debug_messages(void);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object change_slot_value(int,...);
extern Object check_for_target_nupec_timeout(void);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clear_optimized_constants(void);
extern Object collect_subclasses(Object);
extern Object constant_queue_push_right(Object,Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_out_current_wide_string(void);
extern Object decode_gensym_time(Object);
extern Object delete_frame(Object);
extern Object detail_pane(Object);
extern Object direct_structure_method(Object,Object);
extern Object emit_icp_read_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object emit_icp_write_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object encode_gensym_time(Object,Object,Object,Object,Object,Object);
extern Object end_icp_message_group(void);
extern Object enlarge_index_space(Object,Object);
extern Object establish_new_object_index_for_nupec_synchronize_variable_or_parameter(int,...);
extern Object eval_list_2(Object,Object);
extern Object eval_list_4(Object,Object,Object,Object);
extern Object evaluate_designation(Object,Object);
extern Object expand_history_ring_buffer(Object);
extern Object fixnum_time_interval(Object);
extern Object g2_event_cycle_handling_windows_quit(void);
extern Object generate_designation_for_block(Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_history_g2_time(int,...);
extern Object get_history_value_for_cascaded_ring_buffer(Object,Object);
extern Object get_icp_object_index_for_nupec_synchronize_variable_or_parameter(Object,Object);
extern Object get_oldest_active_element_index_for_cascaded_ring_buffer(Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_total_cascaded_ring_buffer_length(Object);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object handle_icp_define_nupec_synchronize_variable_or_parameter(void);
extern Object handle_icp_define_nupec_synchronize_variable_or_parameter__body(Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nupec_synchronize(void);
extern Object handle_icp_nupec_synchronize__body(Object,Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nupec_synchronize_control_message(void);
extern Object handle_icp_nupec_synchronize_control_message__body(Object,Object);
extern Object handle_icp_receive_nupec_synchronize_history_block(void);
extern Object handle_icp_receive_nupec_synchronize_history_block__body(Object,Object);
extern Object history_cons_1(Object,Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object icp_error_internal(Object,Object,Object,Object,Object);
extern Object increment_active_element_index_for_cascaded_ring_buffer(Object,Object);
extern Object initialize_icp_object_type(Object,Object,Object,Object);
extern Object initialize_icp_object_type_compile(Object,Object,Object);
extern Object instantaneous_icp_reader_byte_count(void);
extern Object instantaneous_icp_writer_byte_count(void);
extern Object intern_text_string(int,...);
extern Object invoke_rules_for_nupec_synchronization_chaining(void);
extern Object load_and_initialize_type_description(Object,Object);
extern Object local_nupec_variable_structure_memory_usage(void);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_corresponding_icp_nupec_synchronize_variable_or_parameter(Object);
extern Object make_corresponding_icp_symbol(Object);
extern Object make_entity(int,...);
extern Object make_history_ring_buffer_1(void);
extern Object make_local_nupec_variable_1(Object);
extern Object make_nupec_variable_or_parameter_1(Object,Object,Object,Object,Object);
extern Object make_or_reformat_cascaded_ring_buffer(Object,Object,Object,Object);
extern Object make_permanent_local_nupec_variable_structure_internal(void);
extern Object make_permanent_nupec_synchronize_variable_or_parameter_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_source_nupec_synchronization_structure_internal(void);
extern Object make_permanent_target_nupec_synchronization_structure_internal(void);
extern Object make_source_nupec_synchronization_1(Object,Object,Object);
extern Object make_target_nupec_synchronization_1(Object,Object,Object);
extern Object make_thread_array(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object notify_user_1(Object);
extern Object nupec_synchronize(Object,Object);
extern Object nupec_synchronize_variable_or_parameter_structure_memory_usage(void);
extern Object outstanding_local_nupec_variable_count(void);
extern Object outstanding_nupec_synchronize_variable_or_parameter_count(void);
extern Object outstanding_source_nupec_synchronization_count(void);
extern Object outstanding_target_nupec_synchronization_count(void);
extern Object perform_work_on_nupec_synchronization(Object);
extern Object print_designation(Object);
extern Object push_optimized_constant(Object);
extern Object put_up_attributes_table(int,...);
extern Object put_up_nupec_synchronization_progress_display(void);
extern Object read_icp_byte(void);
extern Object read_icp_corresponding_object_index(void);
extern Object read_icp_integer(void);
extern Object read_icp_nupec_designation(void);
extern Object read_icp_nupec_history_block(void);
extern Object read_icp_nupec_synchronize_datum(void);
extern Object read_icp_text_string(void);
extern Object read_icp_unsigned_integer(void);
extern Object reason_to_reject_nupec_synchronization_qm(void);
extern Object receive_nupec_synchronize(void);
extern Object receive_nupec_synchronize_task(void);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_eval_tree_1(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_history_buffer(Object);
extern Object reclaim_history_cons_1(Object);
extern Object reclaim_icp_object_map(Object,Object,Object);
extern Object reclaim_icp_object_map_for_nupec_synchronize_variable_or_parameter(Object);
extern Object reclaim_icp_port_entry(Object,Object,Object,Object);
extern Object reclaim_icp_port_entry_for_nupec_synchronize_variable_or_parameter(Object,Object);
extern Object reclaim_if_managed_array(Object);
extern Object reclaim_list_of_block_snapshots(Object);
extern Object reclaim_local_nupec_variable_1(Object);
extern Object reclaim_managed_array(Object);
extern Object reclaim_managed_float_array(Object);
extern Object reclaim_managed_number_or_value_function(Object);
extern Object reclaim_nupec_designation(Object);
extern Object reclaim_nupec_history_block(Object);
extern Object reclaim_nupec_synchronize_internal_1(Object);
extern Object reclaim_nupec_synchronize_variable_or_parameter(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_source_nupec_synchronization_1(Object);
extern Object reclaim_target_nupec_synchronization_1(Object);
extern Object reclaim_temporary_constant_1(Object);
extern Object reclaim_text_string(Object);
extern Object record_block_for_tformat(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object resumable_icp_pop(void);
extern Object resumable_icp_pop_list_if_end_marker(void);
extern Object resumable_icp_push(Object);
extern Object send_icp_define_nupec_synchronize_variable_or_parameter(Object,Object,Object,Object,Object,Object);
extern Object send_icp_nupec_synchronize(Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_nupec_synchronize_control_message(Object,Object);
extern Object send_icp_receive_nupec_synchronize_history_block(Object,Object);
extern Object send_nupec_source_variables(Object,Object);
extern Object set_access_form_for_nupec_synchronize_variable_or_parameter(Object,Object);
extern Object set_icp_object_index_for_nupec_synchronize_variable_or_parameter(Object,Object,Object);
extern Object source_nupec_synchronization_structure_memory_usage(void);
extern Object start_writing_icp_message(Object);
extern Object store_corresponding_icp_object(Object,Object);
extern Object store_managed_number_or_value_function(Object,Object);
extern Object symbol_name_text_string(Object);
extern Object system_pause(int,...);
extern Object system_resume(void);
extern Object target_nupec_synchronization_structure_memory_usage(void);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_general_string(Object);
extern Object update_object_pool_meters_list(Object);
extern Object write_confirmed_for_nupec_synchronize_control_message(void);
extern Object write_end_of_synch_for_nupec_synchronize_control_message(void);
extern Object write_group_sent_for_nupec_synchronize_control_message(Object);
extern Object write_icp_byte(Object);
extern Object write_icp_corresponding_object_index(Object);
extern Object write_icp_integer(Object);
extern Object write_icp_maybe_suspend(void);
extern Object write_icp_nupec_designation(Object);
extern Object write_icp_nupec_history_block(Object);
extern Object write_icp_nupec_synchronize_datum(Object);
extern Object write_icp_text_string(Object);
extern Object write_icp_unsigned_integer(Object);
extern Object write_message_group_for_nupec_synchronize(Object);
extern Object write_nupec_synchronization_progress_display_value_from_slot(Object,Object);
extern Object write_symbol_from_slot(Object,Object);
extern Object write_warning_message_header(Object);

#else

extern Object abort_target_nupec_synchronization();
extern Object add_class_to_environment();
extern Object add_icp_message_handler();
extern Object add_icp_message_type_code();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_array();
extern Object allocate_managed_float_array();
extern Object assign_corresponding_icp_object_index();
extern Object break_out_of_debug_messages();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object c_native_clock_ticks_or_cache();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object change_slot_value();
extern Object check_for_target_nupec_timeout();
extern Object check_if_superior_classes_are_defined();
extern Object clear_optimized_constants();
extern Object collect_subclasses();
extern Object constant_queue_push_right();
extern Object copy_constant_wide_string_given_length();
extern Object copy_out_current_wide_string();
extern Object decode_gensym_time();
extern Object delete_frame();
extern Object detail_pane();
extern Object direct_structure_method();
extern Object emit_icp_read_trace();
extern Object emit_icp_write_trace();
extern Object encode_gensym_time();
extern Object end_icp_message_group();
extern Object enlarge_index_space();
extern Object establish_new_object_index_for_nupec_synchronize_variable_or_parameter();
extern Object eval_list_2();
extern Object eval_list_4();
extern Object evaluate_designation();
extern Object expand_history_ring_buffer();
extern Object fixnum_time_interval();
extern Object g2_event_cycle_handling_windows_quit();
extern Object generate_designation_for_block();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object get_history_g2_time();
extern Object get_history_value_for_cascaded_ring_buffer();
extern Object get_icp_object_index_for_nupec_synchronize_variable_or_parameter();
extern Object get_oldest_active_element_index_for_cascaded_ring_buffer();
extern Object get_slot_value_function();
extern Object get_total_cascaded_ring_buffer_length();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object handle_icp_define_nupec_synchronize_variable_or_parameter();
extern Object handle_icp_define_nupec_synchronize_variable_or_parameter__body();
extern Object handle_icp_nupec_synchronize();
extern Object handle_icp_nupec_synchronize__body();
extern Object handle_icp_nupec_synchronize_control_message();
extern Object handle_icp_nupec_synchronize_control_message__body();
extern Object handle_icp_receive_nupec_synchronize_history_block();
extern Object handle_icp_receive_nupec_synchronize_history_block__body();
extern Object history_cons_1();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object icp_error_internal();
extern Object increment_active_element_index_for_cascaded_ring_buffer();
extern Object initialize_icp_object_type();
extern Object initialize_icp_object_type_compile();
extern Object instantaneous_icp_reader_byte_count();
extern Object instantaneous_icp_writer_byte_count();
extern Object intern_text_string();
extern Object invoke_rules_for_nupec_synchronization_chaining();
extern Object load_and_initialize_type_description();
extern Object local_nupec_variable_structure_memory_usage();
extern Object lookup_kb_specific_property_value();
extern Object make_corresponding_icp_nupec_synchronize_variable_or_parameter();
extern Object make_corresponding_icp_symbol();
extern Object make_entity();
extern Object make_history_ring_buffer_1();
extern Object make_local_nupec_variable_1();
extern Object make_nupec_variable_or_parameter_1();
extern Object make_or_reformat_cascaded_ring_buffer();
extern Object make_permanent_local_nupec_variable_structure_internal();
extern Object make_permanent_nupec_synchronize_variable_or_parameter_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_source_nupec_synchronization_structure_internal();
extern Object make_permanent_target_nupec_synchronization_structure_internal();
extern Object make_source_nupec_synchronization_1();
extern Object make_target_nupec_synchronization_1();
extern Object make_thread_array();
extern Object mutate_global_property();
extern Object notify_user_1();
extern Object nupec_synchronize();
extern Object nupec_synchronize_variable_or_parameter_structure_memory_usage();
extern Object outstanding_local_nupec_variable_count();
extern Object outstanding_nupec_synchronize_variable_or_parameter_count();
extern Object outstanding_source_nupec_synchronization_count();
extern Object outstanding_target_nupec_synchronization_count();
extern Object perform_work_on_nupec_synchronization();
extern Object print_designation();
extern Object push_optimized_constant();
extern Object put_up_attributes_table();
extern Object put_up_nupec_synchronization_progress_display();
extern Object read_icp_byte();
extern Object read_icp_corresponding_object_index();
extern Object read_icp_integer();
extern Object read_icp_nupec_designation();
extern Object read_icp_nupec_history_block();
extern Object read_icp_nupec_synchronize_datum();
extern Object read_icp_text_string();
extern Object read_icp_unsigned_integer();
extern Object reason_to_reject_nupec_synchronization_qm();
extern Object receive_nupec_synchronize();
extern Object receive_nupec_synchronize_task();
extern Object reclaim_eval_cons_1();
extern Object reclaim_eval_list_1();
extern Object reclaim_eval_tree_1();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_history_buffer();
extern Object reclaim_history_cons_1();
extern Object reclaim_icp_object_map();
extern Object reclaim_icp_object_map_for_nupec_synchronize_variable_or_parameter();
extern Object reclaim_icp_port_entry();
extern Object reclaim_icp_port_entry_for_nupec_synchronize_variable_or_parameter();
extern Object reclaim_if_managed_array();
extern Object reclaim_list_of_block_snapshots();
extern Object reclaim_local_nupec_variable_1();
extern Object reclaim_managed_array();
extern Object reclaim_managed_float_array();
extern Object reclaim_managed_number_or_value_function();
extern Object reclaim_nupec_designation();
extern Object reclaim_nupec_history_block();
extern Object reclaim_nupec_synchronize_internal_1();
extern Object reclaim_nupec_synchronize_variable_or_parameter();
extern Object reclaim_schedule_task_args();
extern Object reclaim_source_nupec_synchronization_1();
extern Object reclaim_target_nupec_synchronization_1();
extern Object reclaim_temporary_constant_1();
extern Object reclaim_text_string();
extern Object record_block_for_tformat();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object resumable_icp_pop();
extern Object resumable_icp_pop_list_if_end_marker();
extern Object resumable_icp_push();
extern Object send_icp_define_nupec_synchronize_variable_or_parameter();
extern Object send_icp_nupec_synchronize();
extern Object send_icp_nupec_synchronize_control_message();
extern Object send_icp_receive_nupec_synchronize_history_block();
extern Object send_nupec_source_variables();
extern Object set_access_form_for_nupec_synchronize_variable_or_parameter();
extern Object set_icp_object_index_for_nupec_synchronize_variable_or_parameter();
extern Object source_nupec_synchronization_structure_memory_usage();
extern Object start_writing_icp_message();
extern Object store_corresponding_icp_object();
extern Object store_managed_number_or_value_function();
extern Object symbol_name_text_string();
extern Object system_pause();
extern Object system_resume();
extern Object target_nupec_synchronization_structure_memory_usage();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_general_string();
extern Object update_object_pool_meters_list();
extern Object write_confirmed_for_nupec_synchronize_control_message();
extern Object write_end_of_synch_for_nupec_synchronize_control_message();
extern Object write_group_sent_for_nupec_synchronize_control_message();
extern Object write_icp_byte();
extern Object write_icp_corresponding_object_index();
extern Object write_icp_integer();
extern Object write_icp_maybe_suspend();
extern Object write_icp_nupec_designation();
extern Object write_icp_nupec_history_block();
extern Object write_icp_nupec_synchronize_datum();
extern Object write_icp_text_string();
extern Object write_icp_unsigned_integer();
extern Object write_message_group_for_nupec_synchronize();
extern Object write_nupec_synchronization_progress_display_value_from_slot();
extern Object write_symbol_from_slot();
extern Object write_warning_message_header();

#endif

/* Externally callable routines */

#ifdef USE_PROTOTYPES

extern double read_icp_double_float_1(void);
extern Object write_icp_double_float_1(double);

#else

extern double read_icp_double_float_1();
extern Object write_icp_double_float_1();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Abort_for_icp_catcher_qm, Qabort_for_icp_catcher_qm);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_local_nupec_variables, Qchain_of_available_local_nupec_variables);
extern Object Chain_of_available_local_nupec_variables_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_nupec_synchronize_variable_or_parameters, Qchain_of_available_nupec_synchronize_variable_or_parameters);
extern Object Chain_of_available_nupec_synchronize_variable_or_parameters_vector;
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_source_nupec_synchronizations, Qchain_of_available_source_nupec_synchronizations);
extern Object Chain_of_available_source_nupec_synchronizations_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_target_nupec_synchronizations, Qchain_of_available_target_nupec_synchronizations);
extern Object Chain_of_available_target_nupec_synchronizations_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_read_trace_level, Qcurrent_icp_read_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_write_trace_level, Qcurrent_icp_write_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_source_nupec_synchronization, Qcurrent_source_nupec_synchronization);
DECLARE_VARIABLE_WITH_SYMBOL(Current_standard_icp_object_index_space, Qcurrent_standard_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_target_nupec_synchronization, Qcurrent_target_nupec_synchronization);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_temporary_icp_object_index_space, Qcurrent_temporary_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_reset, Qdebugging_reset);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
extern Object Fixnum_time_units_per_second;
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_at_start, Qgensym_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_read_trace_cutoff_level_qm, Qicp_read_trace_cutoff_level_qm);
extern Object Icp_socket_processing_time_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Icp_suspend, Qicp_suspend);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_write_trace_cutoff_level_qm, Qicp_write_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inference_engine_parameters, Qinference_engine_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_corresponding_icp_object_making, Qinhibit_corresponding_icp_object_making);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Local_nupec_variable_count, Qlocal_nupec_variable_count);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Managed_array_unique_marker;
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_time_slice_size, Qmaximum_time_slice_size);
extern Object Most_negative_fixnum_as_float;
extern Object Most_positive_fixnum_as_float;
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
extern Object Nupec_allowable_history_values_per_message_group;
extern Object Nupec_allowable_message_groups_in_progress;
extern Object Nupec_allowable_variables_per_message_group;
#define Nupec_designation_cons_type_tag FIX((SI_Long)2L)
#define Nupec_designation_null_type_tag FIX((SI_Long)0L)
#define Nupec_designation_symbol_type_tag FIX((SI_Long)1L)
extern Object Nupec_fixnum_timeout_interval;
#define Nupec_synchronize_datum_float_type FIX((SI_Long)3L)
#define Nupec_synchronize_datum_integer_type FIX((SI_Long)2L)
#define Nupec_synchronize_datum_null_type FIX((SI_Long)0L)
#define Nupec_synchronize_datum_symbol_type FIX((SI_Long)1L)
#define Nupec_synchronize_datum_text_type FIX((SI_Long)4L)
DECLARE_VARIABLE_WITH_SYMBOL(Nupec_synchronize_variable_or_parameter_count, Qnupec_synchronize_variable_or_parameter_count);
extern Object Print_nupec_message_states;
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Resumable_icp_state, Qresumable_icp_state);
DECLARE_VARIABLE_WITH_SYMBOL(Scheduler_enabled_qm, Qscheduler_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
extern Object Smallest_ring_buffer_vector_size;
DECLARE_VARIABLE_WITH_SYMBOL(Snapshots_of_related_blocks, Qsnapshots_of_related_blocks);
extern Object Some_time_ago;
DECLARE_VARIABLE_WITH_SYMBOL(Source_nupec_synchronization_count, Qsource_nupec_synchronization_count);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Target_nupec_synchronization_count, Qtarget_nupec_synchronization_count);
extern Object The_type_description_of_local_nupec_variable;
extern Object The_type_description_of_nupec_synchronize_variable_or_parameter;
extern Object The_type_description_of_source_nupec_synchronization;
extern Object The_type_description_of_target_nupec_synchronization;
DECLARE_VARIABLE_WITH_SYMBOL(Time_slice_start_time, Qtime_slice_start_time);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_class_description, Qvariable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_resumable_icp_messages_p, Qwriting_resumable_icp_messages_p);
