/* g2pts.h -- Header File for g2pts.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_telewindows_for_protocol_out_of_synch_case_6(void);
extern Object abort_telewindows_top_level(Object);
extern Object accept_saved_user_settings_for_telewindows(Object,Object);
extern Object accept_telewindows_connection_license_info(Object,Object);
extern Object accept_telewindows_connection_license_level(Object,Object);
extern Object add_vectors_to_gsi_history(Object,Object,Object);
extern Object call_gsi_callback(int,...);
extern Object call_gsi_close_fd_callback(Object);
extern Object call_gsi_not_writing_fd_callback(Object);
extern Object call_gsi_open_fd_callback(Object);
extern Object call_gsi_writing_fd_callback(Object);
extern Object convert_gsi_value_to_value(Object);
extern Object convert_value_to_gsi_value(Object);
extern Object current_gsi_string_conversion_style(void);
extern Object default_owner_for_gsi_objects(void);
extern Object entering_signal_handler_function(void);
extern Object filter_text_for_gsi_p(void);
extern Object find_new_gsi_context(void);
extern Object find_or_load_gsi_application(Object);
extern Object get_icp_socket_from_context(Object,Object);
extern Object get_telewindows_command_line_args_if_valid(void);
extern Object gsi_add_leaf_to_item_instance(Object,Object,Object,Object,Object,Object);
extern Object gsi_add_resumable_circularity(Object);
extern Object gsi_array_type_from_g2_element_type(Object);
extern Object gsi_attribute_qualified_name(Object);
extern Object gsi_build_item_instance(Object,Object,Object,Object,Object,Object,Object);
extern Object gsi_check_if_all_items_are_built(Object);
extern Object gsi_connection_error(int,...);
extern Object gsi_current_context_number(void);
extern Object gsi_deregister_items_wrapper_for_known_sensor(Object,Object);
extern Object gsi_error(int,...);
extern Object gsi_failure_p(Object);
extern Object gsi_fatal_error(int,...);
extern Object gsi_get_item_of_attribute_named(Object,Object);
extern Object gsi_handle_define_remote_procedure_name(Object);
extern Object gsi_intern(Object);
extern Object gsi_list_type_from_g2_element_type(Object);
extern Object gsi_make_appropriate_array(int,...);
extern Object gsi_make_array_for_user_or_gsi(Object,Object);
extern Object gsi_make_attributes_for_user_or_gsi(Object,Object);
extern Object gsi_maybe_initiate_delayed_connection(Object);
extern Object gsi_message(int,...);
extern Object gsi_option_is_set_p(Object);
extern Object gsi_preflight_item(Object,Object);
extern Object gsi_prepare_for_recursive_descent(void);
extern Object gsi_priority_of_data_service_function(void);
extern Object gsi_push_onto_appropriate_list(int,...);
extern Object gsi_receive_add_history_range(Object,Object,Object);
extern Object gsi_receive_add_homogeneous_history_range(Object,Object,Object);
extern Object gsi_reclaim_contents(Object,Object);
extern Object gsi_send_item(Object,Object);
extern Object gsi_simple_content_copy_internal(Object,Object);
extern Object gsi_start_or_call_local_function_or_handle_return_values(Object,Object,Object,Object);
extern Object gsi_type_from_g2_element_type(Object);
extern Object gsi_type_from_leaf_type(Object);
extern Object gsi_warning(int,...);
extern Object make_gsi_attribute_for_user_or_gsi(Object);
extern Object make_gsi_history(int,...);
extern Object make_gsi_history_from_specification(Object,Object,Object);
extern Object make_gsi_instance(int,...);
extern Object make_gsi_sequence(Object);
extern Object make_gsi_structure(Object);
extern Object maybe_call_gsi_shutdown_context_callback(Object);
extern Object paste_for_telewindows(Object,Object,Object);
extern Object reclaim_gsi_instance(Object,Object);
extern Object reclaim_gsi_remote_procedures(Object);
extern Object reclaim_gsi_sensor_attribute_list(Object);
extern Object reclaim_gsi_transfer_wrapper_array(Object);
extern Object reclaim_telewindows_workstation_function(Object);
extern Object refresh_telewindow(int,...);
extern Object register_gsi_connection_callbacks(Object,Object);
extern Object reroute_telewindows_connection(Object,Object,Object,Object,Object);
extern Object reshape_telewindow(Object,Object);
extern Object resolve_gsi_context(Object,Object);
extern Object run_one_gsi_scheduler_cycle(void);
extern Object run_one_tw_scheduler_cycle(void);
extern Object send_telewindows_workstation_event(Object,Object);
extern Object set_gsi_attribute_name(Object,Object);
extern Object signal_gsi_extend_current_gensym_string_error(void);
extern Object signal_gsi_extend_current_text_string_error(void);
extern Object signal_gsi_icp_message_out_of_synch_case_2_error(void);
extern Object signal_gsi_icp_message_too_long_error(void);
extern Object signal_gsi_index_space_full_error(void);
extern Object signal_gsi_maximum_gensym_string_length_error(Object,Object);
extern Object signal_gsi_maximum_text_string_length_error(Object,Object);
extern Object signal_gsi_network_error(Object,Object);
extern Object signal_gsi_undefined_structure_method_error(void);
extern Object simple_text_string_copy_from_attribute_name(Object,Object);
extern Object telewindows_authorized_for_chinese_p(Object);
extern Object telewindows_authorized_for_japanese_p(Object);
extern Object telewindows_authorized_for_korean_p(Object);
extern Object telewindows_check_version_of_remote_g2(Object);
extern Object telewindows_icp_socket_qm_function(Object);
extern Object text_conversion_style_for_gsi(Object,Object);
extern Object tw_handle_kill_remote_process(Object,Object);
extern Object tw_handle_remote_process_exists_p(Object,Object);
extern Object tw_handle_spawn_remote_command_line_process(Object,Object);
extern Object tw_handle_spawn_remote_executable_process(Object,Object);
extern Object tw_priority_of_data_service_function(void);
extern Object update_paste_availability_status_for_telewindows(Object,Object);
extern Object write_icp_gsi_value_vector(Object);
extern Object write_icp_gsi_values(Object);
extern Object write_list_of_text_lines_to_gensym_window(Object,Object,Object,Object,Object);

#else

extern Object abort_telewindows_for_protocol_out_of_synch_case_6();
extern Object abort_telewindows_top_level();
extern Object accept_saved_user_settings_for_telewindows();
extern Object accept_telewindows_connection_license_info();
extern Object accept_telewindows_connection_license_level();
extern Object add_vectors_to_gsi_history();
extern Object call_gsi_callback();
extern Object call_gsi_close_fd_callback();
extern Object call_gsi_not_writing_fd_callback();
extern Object call_gsi_open_fd_callback();
extern Object call_gsi_writing_fd_callback();
extern Object convert_gsi_value_to_value();
extern Object convert_value_to_gsi_value();
extern Object current_gsi_string_conversion_style();
extern Object default_owner_for_gsi_objects();
extern Object entering_signal_handler_function();
extern Object filter_text_for_gsi_p();
extern Object find_new_gsi_context();
extern Object find_or_load_gsi_application();
extern Object get_icp_socket_from_context();
extern Object get_telewindows_command_line_args_if_valid();
extern Object gsi_add_leaf_to_item_instance();
extern Object gsi_add_resumable_circularity();
extern Object gsi_array_type_from_g2_element_type();
extern Object gsi_attribute_qualified_name();
extern Object gsi_build_item_instance();
extern Object gsi_check_if_all_items_are_built();
extern Object gsi_connection_error();
extern Object gsi_current_context_number();
extern Object gsi_deregister_items_wrapper_for_known_sensor();
extern Object gsi_error();
extern Object gsi_failure_p();
extern Object gsi_fatal_error();
extern Object gsi_get_item_of_attribute_named();
extern Object gsi_handle_define_remote_procedure_name();
extern Object gsi_intern();
extern Object gsi_list_type_from_g2_element_type();
extern Object gsi_make_appropriate_array();
extern Object gsi_make_array_for_user_or_gsi();
extern Object gsi_make_attributes_for_user_or_gsi();
extern Object gsi_maybe_initiate_delayed_connection();
extern Object gsi_message();
extern Object gsi_option_is_set_p();
extern Object gsi_preflight_item();
extern Object gsi_prepare_for_recursive_descent();
extern Object gsi_priority_of_data_service_function();
extern Object gsi_push_onto_appropriate_list();
extern Object gsi_receive_add_history_range();
extern Object gsi_receive_add_homogeneous_history_range();
extern Object gsi_reclaim_contents();
extern Object gsi_send_item();
extern Object gsi_simple_content_copy_internal();
extern Object gsi_start_or_call_local_function_or_handle_return_values();
extern Object gsi_type_from_g2_element_type();
extern Object gsi_type_from_leaf_type();
extern Object gsi_warning();
extern Object make_gsi_attribute_for_user_or_gsi();
extern Object make_gsi_history();
extern Object make_gsi_history_from_specification();
extern Object make_gsi_instance();
extern Object make_gsi_sequence();
extern Object make_gsi_structure();
extern Object maybe_call_gsi_shutdown_context_callback();
extern Object paste_for_telewindows();
extern Object reclaim_gsi_instance();
extern Object reclaim_gsi_remote_procedures();
extern Object reclaim_gsi_sensor_attribute_list();
extern Object reclaim_gsi_transfer_wrapper_array();
extern Object reclaim_telewindows_workstation_function();
extern Object refresh_telewindow();
extern Object register_gsi_connection_callbacks();
extern Object reroute_telewindows_connection();
extern Object reshape_telewindow();
extern Object resolve_gsi_context();
extern Object run_one_gsi_scheduler_cycle();
extern Object run_one_tw_scheduler_cycle();
extern Object send_telewindows_workstation_event();
extern Object set_gsi_attribute_name();
extern Object signal_gsi_extend_current_gensym_string_error();
extern Object signal_gsi_extend_current_text_string_error();
extern Object signal_gsi_icp_message_out_of_synch_case_2_error();
extern Object signal_gsi_icp_message_too_long_error();
extern Object signal_gsi_index_space_full_error();
extern Object signal_gsi_maximum_gensym_string_length_error();
extern Object signal_gsi_maximum_text_string_length_error();
extern Object signal_gsi_network_error();
extern Object signal_gsi_undefined_structure_method_error();
extern Object simple_text_string_copy_from_attribute_name();
extern Object telewindows_authorized_for_chinese_p();
extern Object telewindows_authorized_for_japanese_p();
extern Object telewindows_authorized_for_korean_p();
extern Object telewindows_check_version_of_remote_g2();
extern Object telewindows_icp_socket_qm_function();
extern Object text_conversion_style_for_gsi();
extern Object tw_handle_kill_remote_process();
extern Object tw_handle_remote_process_exists_p();
extern Object tw_handle_spawn_remote_command_line_process();
extern Object tw_handle_spawn_remote_executable_process();
extern Object tw_priority_of_data_service_function();
extern Object update_paste_availability_status_for_telewindows();
extern Object write_icp_gsi_value_vector();
extern Object write_icp_gsi_values();
extern Object write_list_of_text_lines_to_gensym_window();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Compilations_were_removed_in_this_kb_module_qm, Qcompilations_were_removed_in_this_kb_module_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_telewindows_workstation, Qcurrent_telewindows_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Derived_icp_input_port, Qderived_icp_input_port);
DECLARE_VARIABLE_WITH_SYMBOL(Derived_icp_output_port, Qderived_icp_output_port);
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_maximum_contexts_exceeded, Qgsi_maximum_contexts_exceeded);
