/* g2rpc3.h -- Header File for g2rpc3.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qcar;
extern Object Qeq;
extern Object Qfloat;
extern Object Qget;
extern Object Qinteger;
extern Object Kkey;
extern Object Qnumber;
extern Object Qquote;
extern Object Qreturn;
extern Object Qsequence;
extern Object Qsymbol;
extern Object Qthe;
extern Object Ktype;
extern Object Qtype;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_history_spec_for_object_passing(Object,Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_float_array(int,...);
extern Object allocate_managed_simple_vector(Object);
extern Object assq_function(Object,Object);
extern Object bandwidth_needed_for_resumable_node(Object,Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object call_remote_procedure_after_checks(Object,Object,Object,Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cdr_of_second_in_place(Object);
extern Object change_slot_value(int,...);
extern Object change_slot_value_for_object_passing(Object,Object,Object);
extern Object check_remote_procedure_result_list_types(Object,Object,Object);
extern Object check_resumable_value_list_contents(Object,Object);
extern Object check_resumable_value_vector_contents(Object,Object);
extern Object check_that_remote_procedure_can_receive_values(Object,Object);
extern Object check_toplevel_resumable_node_integrity(Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object class_type_specification_p(Object);
extern Object clear_optimized_constants(void);
extern Object collect_subclasses(Object);
extern Object compile_interface_home_attribute_for_slot(int,...);
extern Object compile_local_item_home_for_slot(int,...);
extern Object constant_queue_push_right(Object,Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_history_state_into_resumable_history_node(Object,Object,Object,Object);
extern Object copy_list_using_icp_conses_1(Object);
extern Object copy_managed_float(Object);
extern Object copy_numeric_history_state_into_resumable_history_node(Object,Object,Object,Object,Object,Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object count_of_symbolic_attributes(Object);
extern Object create_empty_g2_list_structure(void);
extern Object deferred_abort_rpc_for_failed_resumable_object(Object,Object,Object);
extern Object delete_frame(Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object denote_slot_using_slot_value_conses(Object,Object);
extern Object deregister_item_with_socket(Object,Object);
extern Object deregister_on_network_lisp_side(Object,Object);
extern Object enable_references_for_item_passing(void);
extern Object end_icp_message_group(void);
extern Object ensure_registration_on_network(Object,Object);
extern Object equalw(Object,Object);
extern Object establish_new_object_index_for_resumable_object(int,...);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_truth_value_value_function(Object);
extern Object evaluation_value_eql(int,...);
extern Object evaluation_value_type(Object);
extern Object evaluation_value_value(Object);
extern Object fix_frame_with_substitute_class_for_miscellaneous_parameters(Object);
extern Object frame_or_evaluation_value_user_attribute_value(Object,Object,Object);
extern Object frame_serial_number_0(void);
extern Object g2_build_remote_object(Object,Object,Object,Object);
extern Object g2_continue_rpc_after_final_object_build(Object);
extern Object g2_get_attribute_for_object_passing(Object,Object);
extern Object g2_item_creation_attributes_for_network(Object,Object);
extern Object g2_item_home(Object);
extern Object g2_item_identifying_attributes_for_network(Object,Object);
extern Object g2_list_insert_for_object_passing(Object,Object);
extern Object g2_list_length(Object);
extern Object g2_local_home(void);
extern Object g2_lookup_item_from_reference_attributes(Object,Object);
extern Object g2_lookup_network_interface_for_home(Object);
extern Object g2_lookup_or_create_item_from_reference_attributes(Object,Object,Object);
extern Object g2_maybe_continue_rpc_after_object_building(Object);
extern Object g2_receive_add_attribute_history_object(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object g2_receive_add_history_range(Object,Object,Object);
extern Object g2_receive_add_homogeneous_history_range(Object,Object,Object);
extern Object g2_receive_add_homogeneous_value_list_range(Object,Object);
extern Object g2_receive_add_value_list_range(Object);
extern Object g2_reclaim_sending_resumable_object(int,...);
extern Object g2_send_add_homogeneous_value_list_range(Object,Object,Object,Object);
extern Object g2_send_add_value_list_range(Object,Object,Object);
extern Object g2_set_resumable_node_homogeneous_element_type(Object,Object);
extern Object g2_transmit_add_history_range(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object g2_transmit_add_homogeneous_history_range(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object g2_write_history_timestamp(Object);
extern Object g2_write_icp_attribute_value(Object,Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object get_attribute_names_for_object_passing(Object,Object,Object,Object);
extern Object get_available_object_passing_bandwidth(Object);
extern Object get_bandwidth_for_untagged_history_value(Object,Object,Object);
extern Object get_cached_history_array_transmission_info(Object,Object,Object,Object,Object,Object,Object);
extern Object get_current_value_attribute_spec_structure_for_object_passing(Object,Object);
extern Object get_current_value_system_attribute_for_object_passing(Object);
extern Object get_exported_attribute_names_for_object_passing(Object,Object,Object,Object);
extern Object get_following_history_timestamp(Object,Object,Object,Object);
extern Object get_history_array_transmission_info(Object,Object,Object,Object);
extern Object get_history_ring_buffer_if_any(Object,Object);
extern Object get_icp_object_index_for_registered_item(Object,Object);
extern Object get_icp_object_index_for_resumable_instance_node(Object,Object);
extern Object get_icp_object_index_for_symbol(Object,Object);
extern Object get_import_declarations_attribute_spec_structure_for_object_passing(Object,Object);
extern Object get_import_declarations_system_attribute_for_object_passing(Object);
extern Object get_index_of_timestamp_if_any(Object,Object);
extern Object get_item_from_local_handle(Object,Object);
extern Object get_item_from_network_handle_lisp_side(Object,Object);
extern Object get_list_of_all_user_visible_attributes(Object);
extern Object get_local_host_addresses(void);
extern Object get_local_host_name(void);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_name_attribute_spec_structure_for_object_passing(Object,Object);
extern Object get_name_system_attribute_for_object_passing(Object);
extern Object get_network_handle_from_item_lisp_side(Object,Object);
extern Object get_or_make_up_designation_for_block(Object);
extern Object get_package_declaration_attribute_spec_structure_for_object_passing(Object,Object);
extern Object get_package_declaration_system_attribute_for_object_passing(Object);
extern Object get_property_value_function(int,...);
extern Object get_rpc_priority_from_computation_context(void);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_evaluation_value_1(Object,Object,Object);
extern Object get_slot_name_for_alias_if_any(Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_text_attribute_spec_structure_for_object_passing(Object,Object);
extern Object get_text_system_attribute_for_object_passing(Object);
extern Object get_uncached_history_array_transmission_info(Object,Object,Object,Object,Object,Object,Object);
extern Object get_value_list_transmission_info(Object,Object,Object,Object);
extern Object get_value_vector_transmission_info(Object,Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object history_cons_1(Object,Object);
extern Object history_list_3(Object,Object,Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object icp_cons_1(Object,Object);
extern Object icp_list_2(Object,Object);
extern Object icp_list_4(Object,Object,Object,Object);
extern Object icp_socket_of_interface_object(Object);
extern Object identifying_or_creation_attributes_of_item_for_interface(Object,Object,Object);
extern Object initialize_g2_array(Object);
extern Object interface_home_attribute_function(void);
extern Object item_or_value_eql(Object,Object);
extern Object item_references_enabled_p(Object);
extern Object later_timestamp_than(Object,Object);
extern Object local_item_home_function(void);
extern Object locate_new_history_index_if_any(Object,Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lookup_or_create_item_from_reference_attributes(Object,Object,Object,Object);
extern Object lookup_remote_procedure_identifier_from_index(Object);
extern Object make_cascaded_ring_buffer_1(void);
extern Object make_cascaded_ring_buffer_for_history_object_passing(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_history_ring_buffer_1(void);
extern Object make_object_passing_info_1(void);
extern Object make_outgoing_remote_procedure_call(Object,Object,Object,Object);
extern Object make_outgoing_remote_procedure_identifier_from_declaration(Object);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_remote_procedure_item_info(Object,Object,Object,Object,Object,Object);
extern Object make_resumable_history_node_1(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_resumable_object_list_node_1(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_resumable_object_node_1(Object,Object,Object,Object,Object,Object,Object);
extern Object make_resumable_object_vector_node_internal_1(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_resumable_value_list_node_1(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_resumable_value_vector_node_internal_1(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_sending_resumable_object_given_options(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_sending_resumable_object_internal_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_toplevel_resumable_node(Object,Object,Object,Object);
extern Object memq_function(Object,Object);
extern Object merge_object_passing_property_lists(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object name_for_local_home(void);
extern Object note_change_to_block_or_struct_or_seq(Object,Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object proc_cons_1(Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_interface_home_attribute(Object,Object,Object);
extern Object put_interface_home_attribute_where_slot_is_absent(Object,Object);
extern Object put_local_item_home(Object,Object,Object);
extern Object put_local_item_home_where_slot_is_absent(Object,Object);
extern Object put_show_uuids_in_attribute_tables_where_slot_is_absent(Object,Object);
extern Object raw_stack_error_named_error(Object,Object);
extern Object read_icp_attribute_value(void);
extern Object read_icp_evaluation_truth_value(void);
extern Object read_icp_fixnum(void);
extern Object read_icp_history_timestamp(void);
extern Object read_icp_managed_double_float(void);
extern Object read_icp_possibly_interned_symbol(void);
extern Object read_icp_text_string(void);
extern Object receive_object_passing_remote_procedure_error(Object,Object,Object);
extern Object receive_remote_procedure_values(Object,Object);
extern Object receive_start_or_call_remote_procedure(Object,Object,Object,Object);
extern Object reclaim_empty_g2_list_structure(Object);
extern Object reclaim_eval_tree_1(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_icp_cons_1(Object);
extern Object reclaim_icp_list_1(Object);
extern Object reclaim_icp_tree_1(Object);
extern Object reclaim_managed_float_array(Object);
extern Object reclaim_managed_number_or_value_function(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_network_addresses(Object);
extern Object reclaim_receiving_resumable_object(Object);
extern Object reclaim_receiving_rpc_arglist_structure_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_transformed_rpc_argument_list(Object,Object);
extern Object record_object_building_problem_on_receiving_side_1(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object register_all_items_in_value(Object,Object);
extern Object register_item_with_socket(Object,Object,Object);
extern Object register_on_network_lisp_side(Object,Object);
extern Object remote_procedure_error(Object,Object,Object,Object);
extern Object remote_procedure_item_info_excluded_attributes(Object);
extern Object remote_procedure_item_info_include_all_system_attributes(Object);
extern Object remote_procedure_item_info_included_attributes(Object);
extern Object remote_procedure_item_info_included_system_attributes(Object);
extern Object remote_procedure_item_info_kind(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object same_timestamp_as(Object,Object);
extern Object send_icp_continue_building_resumable_object(Object);
extern Object send_rpc_call(Object,Object,Object,Object,Object);
extern Object set_index_of_circular_resumable_node(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_value_function(Object,Object,Object,Object);
extern Object show_uuids_in_attribute_tables_function(void);
extern Object signal_code_body_invocation_error(int,...);
extern Object situate_previous_index_in_identical_timestamps(Object,Object,Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object slot_value_number_p(Object);
extern Object string_equalw(Object,Object);
extern Object suspend_object_passing_transmission(int,...);
extern Object symbol_name_text_string(Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tformat_text_string(int,...);
extern Object time_slice_expired_p(void);
extern Object transform_rpc_argument_or_result_list(int,...);
extern Object transmit_resumable_history_range(Object,Object,Object);
extern Object transmit_resumable_node(Object,Object,Object);
extern Object transmit_resumable_object(Object,Object);
extern Object transmit_resumable_object_message_group(Object,Object);
extern Object transmit_resumable_object_with_catch_handlers(Object);
extern Object transmit_resumable_value_list_range(Object,Object,Object);
extern Object transmit_resumable_value_vector_range(Object,Object,Object);
extern Object try_to_transmit_resumable_object(Object);
extern Object type_specification_type_p(Object,Object);
extern Object user_attribute_slot_description_or_virtual_attribute(Object,Object,Object,Object);
extern Object valid_datum_type_specification_p(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object var_count(Object);
extern Object var_rpc_info_from_index(Object,Object);
extern Object writable_exported_attribute_for_object_passing_p(Object,Object);
extern Object write_evaluation_value(int,...);
extern Object write_icp_abort_building_object(Object);
extern Object write_icp_add_attribute_history_object(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object write_icp_add_attribute_object(Object,Object,Object,Object);
extern Object write_icp_add_attribute_object_list(Object,Object,Object,Object,Object);
extern Object write_icp_add_attribute_object_vector(Object,Object,Object,Object,Object);
extern Object write_icp_add_attribute_value(Object,Object,Object);
extern Object write_icp_add_attribute_value_list(Object,Object,Object,Object,Object,Object);
extern Object write_icp_add_attribute_value_vector(Object,Object,Object,Object,Object,Object);
extern Object write_icp_add_circular_attribute(Object,Object);
extern Object write_icp_add_history_range(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object write_icp_add_homogeneous_history_range(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object write_icp_add_homogeneous_value_list_range(Object,Object,Object,Object);
extern Object write_icp_add_homogeneous_value_vector_range(Object,Object,Object,Object);
extern Object write_icp_add_resumable_circularity(Object);
extern Object write_icp_add_value_list_range(Object,Object,Object);
extern Object write_icp_add_value_vector_range(Object,Object,Object);
extern Object write_icp_ascend_to_parent(Object);
extern Object write_icp_attribute_value(Object,Object);
extern Object write_icp_byte(Object);
extern Object write_icp_evaluation_sequence(Object);
extern Object write_icp_evaluation_structure(Object);
extern Object write_icp_evaluation_truth_value(Object);
extern Object write_icp_finish_building_object(Object);
extern Object write_icp_fixnum(Object);
extern Object write_icp_history_timestamp(Object);
extern Object write_icp_managed_double_float(Object);
extern Object write_icp_possibly_interned_symbol(Object,Object);
extern Object write_icp_resumable_sequence_element_type(Object);
extern Object write_icp_suspend_building_object(Object);
extern Object write_icp_text_string(Object);
extern Object write_interface_home_attribute_from_slot(Object,Object);
extern Object write_local_item_home_from_slot(Object,Object);
extern Object write_name_denotation(Object);

#else

extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_history_spec_for_object_passing();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_managed_array();
extern Object allocate_managed_float_array();
extern Object allocate_managed_simple_vector();
extern Object assq_function();
extern Object bandwidth_needed_for_resumable_node();
extern Object bytes_per_double_float_simple_array();
extern Object call_remote_procedure_after_checks();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cdr_of_second_in_place();
extern Object change_slot_value();
extern Object change_slot_value_for_object_passing();
extern Object check_remote_procedure_result_list_types();
extern Object check_resumable_value_list_contents();
extern Object check_resumable_value_vector_contents();
extern Object check_that_remote_procedure_can_receive_values();
extern Object check_toplevel_resumable_node_integrity();
extern Object chestnut_floorf_function();
extern Object class_type_specification_p();
extern Object clear_optimized_constants();
extern Object collect_subclasses();
extern Object compile_interface_home_attribute_for_slot();
extern Object compile_local_item_home_for_slot();
extern Object constant_queue_push_right();
extern Object copy_constant_wide_string_given_length();
extern Object copy_evaluation_value_1();
extern Object copy_frame_serial_number();
extern Object copy_history_state_into_resumable_history_node();
extern Object copy_list_using_icp_conses_1();
extern Object copy_managed_float();
extern Object copy_numeric_history_state_into_resumable_history_node();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object count_of_symbolic_attributes();
extern Object create_empty_g2_list_structure();
extern Object deferred_abort_rpc_for_failed_resumable_object();
extern Object delete_frame();
extern Object delete_frame_note_if_any();
extern Object denote_slot_using_slot_value_conses();
extern Object deregister_item_with_socket();
extern Object deregister_on_network_lisp_side();
extern Object enable_references_for_item_passing();
extern Object end_icp_message_group();
extern Object ensure_registration_on_network();
extern Object equalw();
extern Object establish_new_object_index_for_resumable_object();
extern Object eval_cons_1();
extern Object evaluation_truth_value_value_function();
extern Object evaluation_value_eql();
extern Object evaluation_value_type();
extern Object evaluation_value_value();
extern Object fix_frame_with_substitute_class_for_miscellaneous_parameters();
extern Object frame_or_evaluation_value_user_attribute_value();
extern Object frame_serial_number_0();
extern Object g2_build_remote_object();
extern Object g2_continue_rpc_after_final_object_build();
extern Object g2_get_attribute_for_object_passing();
extern Object g2_item_creation_attributes_for_network();
extern Object g2_item_home();
extern Object g2_item_identifying_attributes_for_network();
extern Object g2_list_insert_for_object_passing();
extern Object g2_list_length();
extern Object g2_local_home();
extern Object g2_lookup_item_from_reference_attributes();
extern Object g2_lookup_network_interface_for_home();
extern Object g2_lookup_or_create_item_from_reference_attributes();
extern Object g2_maybe_continue_rpc_after_object_building();
extern Object g2_receive_add_attribute_history_object();
extern Object g2_receive_add_history_range();
extern Object g2_receive_add_homogeneous_history_range();
extern Object g2_receive_add_homogeneous_value_list_range();
extern Object g2_receive_add_value_list_range();
extern Object g2_reclaim_sending_resumable_object();
extern Object g2_send_add_homogeneous_value_list_range();
extern Object g2_send_add_value_list_range();
extern Object g2_set_resumable_node_homogeneous_element_type();
extern Object g2_transmit_add_history_range();
extern Object g2_transmit_add_homogeneous_history_range();
extern Object g2_write_history_timestamp();
extern Object g2_write_icp_attribute_value();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_list_3();
extern Object gensym_list_4();
extern Object get_attribute_names_for_object_passing();
extern Object get_available_object_passing_bandwidth();
extern Object get_bandwidth_for_untagged_history_value();
extern Object get_cached_history_array_transmission_info();
extern Object get_current_value_attribute_spec_structure_for_object_passing();
extern Object get_current_value_system_attribute_for_object_passing();
extern Object get_exported_attribute_names_for_object_passing();
extern Object get_following_history_timestamp();
extern Object get_history_array_transmission_info();
extern Object get_history_ring_buffer_if_any();
extern Object get_icp_object_index_for_registered_item();
extern Object get_icp_object_index_for_resumable_instance_node();
extern Object get_icp_object_index_for_symbol();
extern Object get_import_declarations_attribute_spec_structure_for_object_passing();
extern Object get_import_declarations_system_attribute_for_object_passing();
extern Object get_index_of_timestamp_if_any();
extern Object get_item_from_local_handle();
extern Object get_item_from_network_handle_lisp_side();
extern Object get_list_of_all_user_visible_attributes();
extern Object get_local_host_addresses();
extern Object get_local_host_name();
extern Object get_lookup_slot_value_given_default();
extern Object get_name_attribute_spec_structure_for_object_passing();
extern Object get_name_system_attribute_for_object_passing();
extern Object get_network_handle_from_item_lisp_side();
extern Object get_or_make_up_designation_for_block();
extern Object get_package_declaration_attribute_spec_structure_for_object_passing();
extern Object get_package_declaration_system_attribute_for_object_passing();
extern Object get_property_value_function();
extern Object get_rpc_priority_from_computation_context();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_evaluation_value_1();
extern Object get_slot_name_for_alias_if_any();
extern Object get_slot_value_function();
extern Object get_slot_value_if_any_function();
extern Object get_symbol_properties_function();
extern Object get_text_attribute_spec_structure_for_object_passing();
extern Object get_text_system_attribute_for_object_passing();
extern Object get_uncached_history_array_transmission_info();
extern Object get_value_list_transmission_info();
extern Object get_value_vector_transmission_info();
extern Object getfq_function_no_default();
extern Object history_cons_1();
extern Object history_list_3();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object icp_cons_1();
extern Object icp_list_2();
extern Object icp_list_4();
extern Object icp_socket_of_interface_object();
extern Object identifying_or_creation_attributes_of_item_for_interface();
extern Object initialize_g2_array();
extern Object interface_home_attribute_function();
extern Object item_or_value_eql();
extern Object item_references_enabled_p();
extern Object later_timestamp_than();
extern Object local_item_home_function();
extern Object locate_new_history_index_if_any();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lookup_or_create_item_from_reference_attributes();
extern Object lookup_remote_procedure_identifier_from_index();
extern Object make_cascaded_ring_buffer_1();
extern Object make_cascaded_ring_buffer_for_history_object_passing();
extern Object make_history_ring_buffer_1();
extern Object make_object_passing_info_1();
extern Object make_outgoing_remote_procedure_call();
extern Object make_outgoing_remote_procedure_identifier_from_declaration();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_remote_procedure_item_info();
extern Object make_resumable_history_node_1();
extern Object make_resumable_object_list_node_1();
extern Object make_resumable_object_node_1();
extern Object make_resumable_object_vector_node_internal_1();
extern Object make_resumable_value_list_node_1();
extern Object make_resumable_value_vector_node_internal_1();
extern Object make_sending_resumable_object_given_options();
extern Object make_sending_resumable_object_internal_1();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_toplevel_resumable_node();
extern Object memq_function();
extern Object merge_object_passing_property_lists();
extern Object mutate_global_property();
extern Object name_for_local_home();
extern Object note_change_to_block_or_struct_or_seq();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object proc_cons_1();
extern Object push_optimized_constant();
extern Object put_interface_home_attribute();
extern Object put_interface_home_attribute_where_slot_is_absent();
extern Object put_local_item_home();
extern Object put_local_item_home_where_slot_is_absent();
extern Object put_show_uuids_in_attribute_tables_where_slot_is_absent();
extern Object raw_stack_error_named_error();
extern Object read_icp_attribute_value();
extern Object read_icp_evaluation_truth_value();
extern Object read_icp_fixnum();
extern Object read_icp_history_timestamp();
extern Object read_icp_managed_double_float();
extern Object read_icp_possibly_interned_symbol();
extern Object read_icp_text_string();
extern Object receive_object_passing_remote_procedure_error();
extern Object receive_remote_procedure_values();
extern Object receive_start_or_call_remote_procedure();
extern Object reclaim_empty_g2_list_structure();
extern Object reclaim_eval_tree_1();
extern Object reclaim_evaluation_value();
extern Object reclaim_gensym_list_1();
extern Object reclaim_icp_cons_1();
extern Object reclaim_icp_list_1();
extern Object reclaim_icp_tree_1();
extern Object reclaim_managed_float_array();
extern Object reclaim_managed_number_or_value_function();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_network_addresses();
extern Object reclaim_receiving_resumable_object();
extern Object reclaim_receiving_rpc_arglist_structure_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_text_string();
extern Object reclaim_transformed_rpc_argument_list();
extern Object record_object_building_problem_on_receiving_side_1();
extern Object regenerate_optimized_constant();
extern Object register_all_items_in_value();
extern Object register_item_with_socket();
extern Object register_on_network_lisp_side();
extern Object remote_procedure_error();
extern Object remote_procedure_item_info_excluded_attributes();
extern Object remote_procedure_item_info_include_all_system_attributes();
extern Object remote_procedure_item_info_included_attributes();
extern Object remote_procedure_item_info_included_system_attributes();
extern Object remote_procedure_item_info_kind();
extern Object replenish_lookup_cons_pool();
extern Object same_timestamp_as();
extern Object send_icp_continue_building_resumable_object();
extern Object send_rpc_call();
extern Object set_index_of_circular_resumable_node();
extern Object set_non_savable_lookup_slot_value();
extern Object set_skip_list_entry();
extern Object set_slot_value_function();
extern Object show_uuids_in_attribute_tables_function();
extern Object signal_code_body_invocation_error();
extern Object situate_previous_index_in_identical_timestamps();
extern Object slot_value_list_4();
extern Object slot_value_number_p();
extern Object string_equalw();
extern Object suspend_object_passing_transmission();
extern Object symbol_name_text_string();
extern Object text_string_length();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tformat_text_string();
extern Object time_slice_expired_p();
extern Object transform_rpc_argument_or_result_list();
extern Object transmit_resumable_history_range();
extern Object transmit_resumable_node();
extern Object transmit_resumable_object();
extern Object transmit_resumable_object_message_group();
extern Object transmit_resumable_object_with_catch_handlers();
extern Object transmit_resumable_value_list_range();
extern Object transmit_resumable_value_vector_range();
extern Object try_to_transmit_resumable_object();
extern Object type_specification_type_p();
extern Object user_attribute_slot_description_or_virtual_attribute();
extern Object valid_datum_type_specification_p();
extern Object validate_item_or_evaluation_value();
extern Object var_count();
extern Object var_rpc_info_from_index();
extern Object writable_exported_attribute_for_object_passing_p();
extern Object write_evaluation_value();
extern Object write_icp_abort_building_object();
extern Object write_icp_add_attribute_history_object();
extern Object write_icp_add_attribute_object();
extern Object write_icp_add_attribute_object_list();
extern Object write_icp_add_attribute_object_vector();
extern Object write_icp_add_attribute_value();
extern Object write_icp_add_attribute_value_list();
extern Object write_icp_add_attribute_value_vector();
extern Object write_icp_add_circular_attribute();
extern Object write_icp_add_history_range();
extern Object write_icp_add_homogeneous_history_range();
extern Object write_icp_add_homogeneous_value_list_range();
extern Object write_icp_add_homogeneous_value_vector_range();
extern Object write_icp_add_resumable_circularity();
extern Object write_icp_add_value_list_range();
extern Object write_icp_add_value_vector_range();
extern Object write_icp_ascend_to_parent();
extern Object write_icp_attribute_value();
extern Object write_icp_byte();
extern Object write_icp_evaluation_sequence();
extern Object write_icp_evaluation_structure();
extern Object write_icp_evaluation_truth_value();
extern Object write_icp_finish_building_object();
extern Object write_icp_fixnum();
extern Object write_icp_history_timestamp();
extern Object write_icp_managed_double_float();
extern Object write_icp_possibly_interned_symbol();
extern Object write_icp_resumable_sequence_element_type();
extern Object write_icp_suspend_building_object();
extern Object write_icp_text_string();
extern Object write_interface_home_attribute_from_slot();
extern Object write_local_item_home_from_slot();
extern Object write_name_denotation();

#endif

/* Externally callable routines */

#ifdef USE_PROTOTYPES

extern double read_icp_double_float_1(void);
extern Object write_icp_double_float_1(double);

#else

extern double read_icp_double_float_1();
extern Object write_icp_double_float_1();

#endif

/* variables/constants */
#define Attribute_value_evaluation_sequence_tag FIX((SI_Long)14L)
#define Attribute_value_evaluation_structure_tag FIX((SI_Long)15L)
#define Attribute_value_float_tag FIX((SI_Long)6L)
#define Attribute_value_integer_tag FIX((SI_Long)5L)
#define Attribute_value_null_tag FIX((SI_Long)13L)
#define Attribute_value_text_tag FIX((SI_Long)8L)
#define Attribute_value_truth_value_tag FIX((SI_Long)9L)
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_icp_conses_tail_vector;
extern Object Available_icp_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Cached_name_for_local_home, Qcached_name_for_local_home);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
extern Object Chain_of_available_schedule_tasks_vector;
extern Object Class_description_gkbprop;
extern Object Compute_name_for_local_home_p;
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_instance, Qcurrent_computation_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_network_interface, Qcurrent_network_interface);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_receiving_resumable_object, Qcurrent_receiving_resumable_object);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
extern Object Frame_or_frames_with_this_name_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(G2_array_class_description, Qg2_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_list_class_description, Qg2_list_class_description);
extern Object G2_list_structure_marker;
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(G2_to_g2_uses_references_p, Qg2_to_g2_uses_references_p);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Item_array_class_description, Qitem_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Item_list_class_description, Qitem_list_class_description);
#define Last_kb_flags_saved_with_item_reference_parameters FIX((SI_Long)272L)
DECLARE_VARIABLE_WITH_SYMBOL(List_of_user_overridable_system_slots, Qlist_of_user_overridable_system_slots);
DECLARE_VARIABLE_WITH_SYMBOL(Local_host_name, Qlocal_host_name);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Managed_array_unique_marker;
extern Object Managed_float_array_unique_marker;
extern Object Maximum_in_place_array_size;
DECLARE_VARIABLE_WITH_SYMBOL(Minimnal_bandwidth_for_resumable_sequence_range, Qminimnal_bandwidth_for_resumable_sequence_range);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_bandwidth_per_timeslice, Qminimum_bandwidth_per_timeslice);
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Most_recent_bandwidth_per_timeslice_qm, Qmost_recent_bandwidth_per_timeslice_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Name_for_local_home, Qname_for_local_home);
#define No_resumable_object_index FIX((SI_Long)-1L)
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
extern Object Numeric_data_type_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Object_class_description, Qobject_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Previous_timestamp_qm, Qprevious_timestamp_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Rpc_throw_tag, Qrpc_throw_tag);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Size_of_cached_subsequence_for_resumable_history, Qsize_of_cached_subsequence_for_resumable_history);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Value_array_class_description, Qvalue_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Value_list_class_description, Qvalue_list_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
