/* gram4a.h -- Header File for gram4a.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qminus;
extern Object Qand;
extern Object Qcase;
extern Object Qcount;
extern Object Qdelete;
extern Object Qdo;
extern Object Qevery;
extern Object Qfirst;
extern Object Qfloat;
extern Object Qgo;
extern Object Qinteger;
extern Object Qlast;
extern Object Qmember;
extern Object Qnot;
extern Object Qnumber;
extern Object Qprint;
extern Object Qquote;
extern Object Qreturn;
extern Object Qsecond;
extern Object Qsequence;
extern Object Qset;
extern Object Qsymbol;
extern Object Qthe;
extern Object Qunsigned_byte;
extern Object Qvalues;
extern Object Qwhen;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object action_button_priority_function(Object);
extern Object add_5_dot_0_evaluation_settings(Object,Object);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_tracing_and_breakpoint_evaluation_settings(Object,Object);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_long_box(void);
extern Object breakdown_tracing_and_breakpoints_levels(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object cascaded_ring_buffer_empty_qm(Object);
extern Object change_slot_description_value_function(Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object clear_g2_list(Object);
extern Object clear_history_buffer(Object);
extern Object clear_optimized_constants(void);
extern Object compile_constant_designation_list_for_slot(int,...);
extern Object compile_constant_designation_list_qm_for_slot(int,...);
extern Object compile_constant_designation_or_datum_list(Object,Object);
extern Object compile_constant_variable_designation_qm_for_slot(int,...);
extern Object compile_float_list_for_slot(int,...);
extern Object compile_g2_array_length_for_slot(int,...);
extern Object compile_integer_list_for_slot(int,...);
extern Object compile_list_of_datum_constants_for_slot(int,...);
extern Object compile_list_of_item_and_datum_constants_qm_for_slot(int,...);
extern Object compile_quantity_for_slot(int,...);
extern Object compile_quantity_list_for_slot(int,...);
extern Object compile_quoted_symbol_list_for_slot(int,...);
extern Object compile_symbol_list_for_slot(int,...);
extern Object compile_truth_value_list_for_slot(int,...);
extern Object compile_whole_string_list_for_slot(int,...);
extern Object constant_designation_to_evaluation_value(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_as_wide_string(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_evaluation_constant_to_phrase(Object,Object,Object);
extern Object copy_evaluation_sequence_to_phrase(Object);
extern Object copy_evaluation_structure_to_phrase(Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_for_phrase(Object);
extern Object copy_if_evaluation_value_1(Object);
extern Object copy_managed_float(Object);
extern Object copy_managed_long(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_wide_string(Object);
extern Object def_action_template(Object);
extern Object def_function_template(Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object delete_frame(Object);
extern Object delete_frame_for_rpc(Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object eval_list_2(Object,Object);
extern Object evaluate_designation(Object,Object);
extern Object evaluation_truth_value_true_p(Object);
extern Object evaluation_value_to_constant_designation_phrase(Object);
extern Object evaluation_value_to_initial_values_phrase(Object,Object,Object);
extern Object evaluation_value_to_symbol_or_class_qualified_name_phrase(Object);
extern Object evaluation_value_value(Object);
extern Object g2_array_aref_item_or_evaluation_value(Object,Object);
extern Object g2_list_empty_p(Object);
extern Object g2_list_insert_at_end(int,...);
extern Object g2_list_structure_next(Object,Object);
extern Object generate_designation_for_block(Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_default_collection_time_for_put_current_value(Object);
extern Object get_display_evaluation_attributes(Object);
extern Object get_effective_data_type(Object);
extern Object get_evaluation_attributes(Object);
extern Object get_evaluation_value_of_variable_or_parameter(Object,Object);
extern Object get_foundation_class_for_class(Object);
extern Object get_g2_array_sequence(Object);
extern Object get_g2_list_sequence(Object);
extern Object get_generic_action_button_evaluation_attributes(Object);
extern Object get_history(Object);
extern Object get_history_current_time_as_evaluation_value(Object,Object,Object);
extern Object get_history_evaluation_structure(Object,Object);
extern Object get_history_evaluation_structure_from_cascade(Object,Object,Object,Object,Object,Object);
extern Object get_history_g2_time_as_evaluation_value(Object,Object,Object);
extern Object get_history_using_unix_time(Object);
extern Object get_item_history_information(Object,Object);
extern Object get_last_recorded_value_text(Object);
extern Object get_list_contents_as_sequence(Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_new_table_evaluation_attributes(Object);
extern Object get_or_make_history_buffer(Object,Object);
extern Object get_procedure_evaluation_attributes(Object);
extern Object get_property_value_function(int,...);
extern Object get_reference_to_item(Object);
extern Object get_rule_evaluation_attributes(Object);
extern Object get_simulation_subtable_evaluation_attributes(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_user_menu_choice_evaluation_attributes(Object);
extern Object get_user_spelling(Object,Object);
extern Object get_value_structure(Object);
extern Object get_value_structure_using_unix_time(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object initial_effective_data_type(Object);
extern Object initial_evaluation_attributes(Object);
extern Object initial_g2_array_sequence(Object);
extern Object initial_g2_list_sequence(Object);
extern Object initial_history(Object);
extern Object initial_history_using_unix_time(Object);
extern Object initial_last_recorded_value_text(Object);
extern Object initial_value_structure(Object);
extern Object initial_value_structure_using_unix_time(Object);
extern Object initial_values_to_evaluation_value(Object,Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_evaluation_long(Object);
extern Object make_slot_constant_using_phrase_conses(Object,Object);
extern Object mutate_g2_array(Object,Object,Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_text_category_evaluator_interface(Object);
extern Object note_use_of_managed_float_in_phrase(Object);
extern Object note_use_of_managed_long_in_phrase(Object);
extern Object parse_text_string(int,...);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_3(Object,Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object phrase_number_p(Object);
extern Object print_constant(int,...);
extern Object print_constant_list(Object,Object);
extern Object print_datum_constant_list(Object);
extern Object print_designation(Object);
extern Object print_designation_list(Object);
extern Object print_item_and_datum_constant_list(int,...);
extern Object print_item_or_datum_constant(Object);
extern Object print_quoted_symbol_list(Object);
extern Object push_optimized_constant(Object);
extern Object put_current_evaluation_value(Object,Object,Object,Object,Object);
extern Object put_current_value_for_virtual_attribute(Object,Object);
extern Object put_current_value_for_virtual_attribute_1(Object,Object,Object,Object);
extern Object put_evaluation_value_of_variable_or_parameter(Object,Object,Object);
extern Object put_has_no_value(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object regenerate_optimized_constant(Object);
extern Object reparse_nth_element_designation(Object);
extern Object reparse_nth_element_designation_1(Object,Object,Object,Object);
extern Object reserve_words(Object);
extern Object sequences_to_initial_values_phrase(Object,Object,Object,Object);
extern Object serve_item_p(Object);
extern Object set_evaluation_attributes(Object,Object);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_g2_array_sequence(Object,Object);
extern Object set_g2_list_sequence(Object,Object);
extern Object set_history(Object,Object);
extern Object set_history_evaluation_structure(Object,Object,Object);
extern Object set_history_using_unix_time(Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object set_value_structure(Object,Object);
extern Object set_value_structure_using_unix_time(Object,Object);
extern Object simplify_associative_list_operation_all_at_once(Object);
extern Object slot_value_number_p(Object);
extern Object store_history_value(Object,Object,Object,Object,Object);
extern Object symbol_or_class_qualified_name_to_evaluation_value(Object);
extern Object symbolic_type_specification_subtype_p(Object,Object);
extern Object text_category_slot_access_committer(Object,Object,Object);
extern Object text_category_slot_access_extracter(Object,Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object truth_value_phrase_p(Object);
extern Object truth_value_phrase_value(Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_of_variable_or_parameter_value(Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object write_constant_designation_from_slot(Object,Object);
extern Object write_constant_designation_list_from_slot(Object,Object);
extern Object write_constant_designation_list_qm_from_slot(Object,Object);
extern Object write_constant_variable_designation_qm_from_slot(Object,Object);
extern Object write_evaluation_value(int,...);
extern Object write_float_list_from_slot(Object,Object);
extern Object write_g2_array_length_from_slot(Object,Object);
extern Object write_integer_list_from_slot(Object,Object);
extern Object write_list_in_chicago_style(int,...);
extern Object write_list_of_datum_constants_from_slot(Object,Object);
extern Object write_list_of_item_and_datum_constants_qm_from_slot(Object,Object);
extern Object write_quantity_list_from_slot(Object,Object);
extern Object write_quoted_symbol_list_from_slot(Object,Object);
extern Object write_symbol_list_from_slot(Object,Object);
extern Object write_truth_value_list_from_slot(Object,Object);
extern Object write_whole_string_list_from_slot(Object,Object);

#else

extern Object action_button_priority_function();
extern Object add_5_dot_0_evaluation_settings();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_tracing_and_breakpoint_evaluation_settings();
extern Object add_virtual_attribute();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object allocate_managed_array();
extern Object allocate_managed_long_box();
extern Object breakdown_tracing_and_breakpoints_levels();
extern Object bytes_per_double_float_simple_array();
extern Object cascaded_ring_buffer_empty_qm();
extern Object change_slot_description_value_function();
extern Object change_slot_value();
extern Object clear_g2_list();
extern Object clear_history_buffer();
extern Object clear_optimized_constants();
extern Object compile_constant_designation_list_for_slot();
extern Object compile_constant_designation_list_qm_for_slot();
extern Object compile_constant_designation_or_datum_list();
extern Object compile_constant_variable_designation_qm_for_slot();
extern Object compile_float_list_for_slot();
extern Object compile_g2_array_length_for_slot();
extern Object compile_integer_list_for_slot();
extern Object compile_list_of_datum_constants_for_slot();
extern Object compile_list_of_item_and_datum_constants_qm_for_slot();
extern Object compile_quantity_for_slot();
extern Object compile_quantity_list_for_slot();
extern Object compile_quoted_symbol_list_for_slot();
extern Object compile_symbol_list_for_slot();
extern Object compile_truth_value_list_for_slot();
extern Object compile_whole_string_list_for_slot();
extern Object constant_designation_to_evaluation_value();
extern Object convert_text_to_text_string();
extern Object copy_as_wide_string();
extern Object copy_constant_wide_string_given_length();
extern Object copy_evaluation_constant_to_phrase();
extern Object copy_evaluation_sequence_to_phrase();
extern Object copy_evaluation_structure_to_phrase();
extern Object copy_evaluation_value_1();
extern Object copy_for_phrase();
extern Object copy_if_evaluation_value_1();
extern Object copy_managed_float();
extern Object copy_managed_long();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_wide_string();
extern Object def_action_template();
extern Object def_function_template();
extern Object define_type_specification_explicit_complex_type();
extern Object delete_frame();
extern Object delete_frame_for_rpc();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object eval_list_2();
extern Object evaluate_designation();
extern Object evaluation_truth_value_true_p();
extern Object evaluation_value_to_constant_designation_phrase();
extern Object evaluation_value_to_initial_values_phrase();
extern Object evaluation_value_to_symbol_or_class_qualified_name_phrase();
extern Object evaluation_value_value();
extern Object g2_array_aref_item_or_evaluation_value();
extern Object g2_list_empty_p();
extern Object g2_list_insert_at_end();
extern Object g2_list_structure_next();
extern Object generate_designation_for_block();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object get_default_collection_time_for_put_current_value();
extern Object get_display_evaluation_attributes();
extern Object get_effective_data_type();
extern Object get_evaluation_attributes();
extern Object get_evaluation_value_of_variable_or_parameter();
extern Object get_foundation_class_for_class();
extern Object get_g2_array_sequence();
extern Object get_g2_list_sequence();
extern Object get_generic_action_button_evaluation_attributes();
extern Object get_history();
extern Object get_history_current_time_as_evaluation_value();
extern Object get_history_evaluation_structure();
extern Object get_history_evaluation_structure_from_cascade();
extern Object get_history_g2_time_as_evaluation_value();
extern Object get_history_using_unix_time();
extern Object get_item_history_information();
extern Object get_last_recorded_value_text();
extern Object get_list_contents_as_sequence();
extern Object get_lookup_slot_value();
extern Object get_new_table_evaluation_attributes();
extern Object get_or_make_history_buffer();
extern Object get_procedure_evaluation_attributes();
extern Object get_property_value_function();
extern Object get_reference_to_item();
extern Object get_rule_evaluation_attributes();
extern Object get_simulation_subtable_evaluation_attributes();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_symbol_properties_function();
extern Object get_user_menu_choice_evaluation_attributes();
extern Object get_user_spelling();
extern Object get_value_structure();
extern Object get_value_structure_using_unix_time();
extern Object getfq_function_no_default();
extern Object initial_effective_data_type();
extern Object initial_evaluation_attributes();
extern Object initial_g2_array_sequence();
extern Object initial_g2_list_sequence();
extern Object initial_history();
extern Object initial_history_using_unix_time();
extern Object initial_last_recorded_value_text();
extern Object initial_value_structure();
extern Object initial_value_structure_using_unix_time();
extern Object initial_values_to_evaluation_value();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_evaluation_long();
extern Object make_slot_constant_using_phrase_conses();
extern Object mutate_g2_array();
extern Object mutate_global_property();
extern Object note_change_to_block_1();
extern Object note_text_category_evaluator_interface();
extern Object note_use_of_managed_float_in_phrase();
extern Object note_use_of_managed_long_in_phrase();
extern Object parse_text_string();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object phrase_list_3();
extern Object phrase_list_4();
extern Object phrase_number_p();
extern Object print_constant();
extern Object print_constant_list();
extern Object print_datum_constant_list();
extern Object print_designation();
extern Object print_designation_list();
extern Object print_item_and_datum_constant_list();
extern Object print_item_or_datum_constant();
extern Object print_quoted_symbol_list();
extern Object push_optimized_constant();
extern Object put_current_evaluation_value();
extern Object put_current_value_for_virtual_attribute();
extern Object put_current_value_for_virtual_attribute_1();
extern Object put_evaluation_value_of_variable_or_parameter();
extern Object put_has_no_value();
extern Object reclaim_eval_list_1();
extern Object reclaim_evaluation_value();
extern Object reclaim_gensym_list_1();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object regenerate_optimized_constant();
extern Object reparse_nth_element_designation();
extern Object reparse_nth_element_designation_1();
extern Object reserve_words();
extern Object sequences_to_initial_values_phrase();
extern Object serve_item_p();
extern Object set_evaluation_attributes();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_g2_array_sequence();
extern Object set_g2_list_sequence();
extern Object set_history();
extern Object set_history_evaluation_structure();
extern Object set_history_using_unix_time();
extern Object set_property_value_function();
extern Object set_slot_value_to_evaluation_value_function();
extern Object set_value_structure();
extern Object set_value_structure_using_unix_time();
extern Object simplify_associative_list_operation_all_at_once();
extern Object slot_value_number_p();
extern Object store_history_value();
extern Object symbol_or_class_qualified_name_to_evaluation_value();
extern Object symbolic_type_specification_subtype_p();
extern Object text_category_slot_access_committer();
extern Object text_category_slot_access_extracter();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object truth_value_phrase_p();
extern Object truth_value_phrase_value();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object type_error_in_setter();
extern Object type_specification_of_variable_or_parameter_value();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object validate_item_or_evaluation_value();
extern Object write_constant_designation_from_slot();
extern Object write_constant_designation_list_from_slot();
extern Object write_constant_designation_list_qm_from_slot();
extern Object write_constant_variable_designation_qm_from_slot();
extern Object write_evaluation_value();
extern Object write_float_list_from_slot();
extern Object write_g2_array_length_from_slot();
extern Object write_integer_list_from_slot();
extern Object write_list_in_chicago_style();
extern Object write_list_of_datum_constants_from_slot();
extern Object write_list_of_item_and_datum_constants_qm_from_slot();
extern Object write_quantity_list_from_slot();
extern Object write_quoted_symbol_list_from_slot();
extern Object write_symbol_list_from_slot();
extern Object write_truth_value_list_from_slot();
extern Object write_whole_string_list_from_slot();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Allow_no_value_p, Qallow_no_value_p);
DECLARE_VARIABLE_WITH_SYMBOL(Append_into_arrays_and_lists, Qappend_into_arrays_and_lists);
DECLARE_VARIABLE_WITH_SYMBOL(Array_initialization_evaluation_values_use_designations_p, Qarray_initialization_evaluation_values_use_designations_p);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Breakpoint_level, Qbreakpoint_level);
DECLARE_VARIABLE_WITH_SYMBOL(Chart, Qchart);
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Data_point_value, Qdata_point_value);
DECLARE_VARIABLE_WITH_SYMBOL(Default_language, Qdefault_language);
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
DECLARE_VARIABLE_WITH_SYMBOL(Delete_old_elements_from_arrays_and_lists, Qdelete_old_elements_from_arrays_and_lists);
DECLARE_VARIABLE_WITH_SYMBOL(Designation_marker, Qdesignation_marker);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
extern Object G2_array_length_maximum;
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_at_start, Qgensym_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Managed_array_unique_marker;
extern Object Maximum_in_place_array_size;
extern Object May_refer_to_inactive_items_flag;
#define Message_field_mask FIX((SI_Long)15L)
extern Object Most_negative_fixnum_as_float;
extern Object Most_positive_fixnum_as_float;
DECLARE_VARIABLE_WITH_SYMBOL(New_table, Qnew_table);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Numeric_data_type_gkbprop;
extern Object Phrase_sequence_marker;
extern Object Phrase_structure_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
extern Object Runs_while_inactive_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_subtable_class_description, Qsimulation_subtable_class_description);
extern Object Some_time_ago;
DECLARE_VARIABLE_WITH_SYMBOL(Source_stepping_level, Qsource_stepping_level);
extern Object Symbol_initial_value_marker;
extern Object Symbol_initial_value_marker_symbol;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Tracing_message_level, Qtracing_message_level);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_class_description, Qvariable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Virtual_attributes_not_local_to_a_class, Qvirtual_attributes_not_local_to_a_class);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
