/* gram6a.h -- Header File for gram6a.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qdeclaration;
extern Object Qeq;
extern Object Qfloat;
extern Object Qinteger;
extern Object Qmember;
extern Object Qnot;
extern Object Qnumber;
extern Object Qopen;
extern Object Qquote;
extern Object Qsequence;
extern Object Qsymbol;
extern Object Ktest;
extern Object Qthe;
extern Object Qunsigned_byte;
extern Object Qvalues;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_initial_value_for_declared_type(Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object antonym_of(Object);
extern Object assq_function(Object,Object);
extern Object attribute_definition_type_specification(Object);
extern Object bad_attribute_name(Object);
extern Object badly_formed_attribute_name(void);
extern Object body_of_put_for_simulation_frame(Object,Object,Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object change_connection_attribute(Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object check_value_attribute_initialization_type(Object);
extern Object circularity_in_potential_definition_inheritance(Object);
extern Object class_instantiation_warning_incompatible_class(Object,Object,Object,Object);
extern Object class_instantiation_warning_not_defined(Object,Object,Object);
extern Object class_instantiation_warning_undefined_type_specification_class(Object,Object,Object,Object);
extern Object class_type_specification_p(Object);
extern Object clear_optimized_constants(void);
extern Object collect_subclasses(Object);
extern Object color_or_metacolor_p(Object);
extern Object compile_attribute_descriptions_for_slot(int,...);
extern Object compile_class_for_slot(int,...);
extern Object compile_connection_arrows_for_slot(int,...);
extern Object compile_connection_class_for_slot(int,...);
extern Object compile_connection_line_pattern_for_slot(int,...);
extern Object compile_cross_section_pattern_for_slot(int,...);
extern Object compile_default_overrides_for_object_definitions_for_slot(int,...);
extern Object compile_item_class_for_slot(int,...);
extern Object compile_list_of_classes_for_slot(int,...);
extern Object compile_list_of_connection_classes_for_slot(int,...);
extern Object compile_list_of_item_classes_for_slot(int,...);
extern Object compile_list_of_message_classes_for_slot(int,...);
extern Object compile_list_of_object_classes_for_slot(int,...);
extern Object compile_message_class_for_slot(int,...);
extern Object compile_new_class_for_slot(int,...);
extern Object compile_object_class_for_slot(int,...);
extern Object compile_old_attribute_descriptions_for_slot(int,...);
extern Object compile_old_default_settings_for_slot(int,...);
extern Object compile_old_superior_class_for_slot(int,...);
extern Object compile_previous_capabilities_for_slot(int,...);
extern Object compile_stub_length_for_slot(int,...);
extern Object compile_symbolic_value_list_for_slot(int,...);
extern Object compute_connection_arrows_spec(Object);
extern Object compute_connection_arrows_structure(Object);
extern Object connection_arrows_adjective_phrase(Object,Object);
extern Object connection_arrows_scale_index(Object);
extern Object connection_line_pattern_absolute_p(Object);
extern Object connection_line_pattern_dashes(Object);
extern Object connection_line_pattern_explicit_p(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_for_phrase(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_list_using_eval_conses_1(Object);
extern Object copy_list_using_frame_conses_1(Object);
extern Object copy_list_using_phrase_conses(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_tree_using_frame_conses_1(Object);
extern Object cut_out_fifth_element(Object);
extern Object cut_out_fourth_element(Object);
extern Object cut_out_sixth_element(Object);
extern Object decode_arrow_spec_1(Object);
extern Object def_semi_open_category_1(int,...);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object definition_class_is_subclass_of_obj_conn_mess_definition_p(Object);
extern Object direct_superiors_are_defined_p(Object);
extern Object direct_superiors_give_ancestors_different_precedence(Object,Object,Object,Object);
extern Object do_valid_superior_tests(Object,Object,Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object eval_list_4(Object,Object,Object,Object);
extern Object evaluation_truth_value_is_true_p(Object);
extern Object expt2(Object);
extern Object fix_attribute_description(Object,Object);
extern Object fix_attribute_description_initial_value(Object,Object);
extern Object fix_connection_arrows_stub_spec(Object);
extern Object fix_connection_line_pattern_stub_spec(Object);
extern Object fix_connection_style_stub_spec(Object);
extern Object fix_old_attribute_description(Object,Object);
extern Object fix_stub_info(Object);
extern Object fix_up_cross_section_pattern(Object);
extern Object fix_up_symbolic_value_list(Object);
extern Object flatten_phrase_tree(Object);
extern Object frame_cons_1(Object,Object);
extern Object frame_list_3(Object,Object,Object);
extern Object generate_float_vector(Object);
extern Object get_class_feature_if_any(Object,Object);
extern Object get_foundation_class_for_class(Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_specialized_definition_class(Object);
extern Object get_symbol_properties_function(Object);
extern Object getfq_function(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object incorrect_foundation_class_for_this_definition_p(Object,Object,Object);
extern Object instantiate_object_in_attribute(Object);
extern Object instantiate_object_in_attribute_1(Object,Object);
extern Object instantiate_variable(Object);
extern Object instantiated_class_p(Object);
extern Object invalidates_direct_superiors_for_potential_definition(Object,Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_stock_line_pattern_element(Object);
extern Object make_bad_region_text_string(Object);
extern Object make_class_inheritance_path_for_user_defined_class(Object,Object);
extern Object make_eval_list_1(Object);
extern Object make_frame(Object);
extern Object make_phrase_list(Object);
extern Object make_simulation_subtable_and_install(void);
extern Object make_simulation_subtable_with_specific_class_and_install(Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object memq_2_cddddr(Object);
extern Object memq_2_cdddr(Object);
extern Object memq_3_cddddr(Object);
extern Object memq_3_cdr_cddddr(Object);
extern Object memq_function(Object,Object);
extern Object merging_paths_common_ancestor_rule_2_violation_p(Object);
extern Object most_refined_foundation_class_of_direct_superiors(int,...);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_use_of_managed_float_in_phrase(Object);
extern Object parsed_attribute_initial_value_matches_type_p(Object,Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_3(Object,Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object phrase_number_p(Object);
extern Object position_in_float_list(Object,Object,Object);
extern Object potential_definition_cannot_inherit_foundation_class(Object,Object,Object);
extern Object potential_definition_class_type_is_incompatible(Object,Object,Object);
extern Object potential_definition_has_different_class_type(Object,Object,Object);
extern Object potential_definition_superior_not_the_mixed_hierarchy_type(Object,Object,Object);
extern Object prepare_for_indexed_attributes_moveage(Object,Object,Object);
extern Object print_constant(int,...);
extern Object process_pre_4_dot_0_attribute_descriptions_and_default_overrides(Object,Object,Object,Object,Object,Object,Object);
extern Object process_pre_4_dot_0_capabilities_of_class(Object,Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_attributes_specific_to_class(Object,Object,Object);
extern Object put_capabilities_and_restrictions(Object,Object,Object);
extern Object put_connection_arrows(Object,Object,Object);
extern Object put_default_settings(Object,Object,Object);
extern Object put_line_pattern(Object,Object,Object);
extern Object put_superior_class(Object,Object,Object);
extern Object reclaim_frame_list_1(Object);
extern Object reclaim_frame_tree_1(Object);
extern Object reclaim_slot_value(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object reserved_system_slot_name_p(Object,Object);
extern Object scope_cons(Object,Object);
extern Object second_none(Object);
extern Object sequence_type_specification_p(Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_grammar_transform_can_return_bad_phrase_p(Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object structure_type_specification_p(Object);
extern Object subclass_appears_after_superior_for_potential_definition(Object,Object,Object);
extern Object symbolic_type_specification_p(Object);
extern Object system_class_is_not_user_subclassable_p(Object);
extern Object system_slot_is_present_only_on_non_user_subclassable_system_slots(Object);
extern Object system_slot_is_user_subclassable_1(Object,Object);
extern Object system_slot_override_but_no_foundation_class(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object truth_value_phrase_p(Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_connection_arrow(Object);
extern Object twrite_general_string(Object);
extern Object twrite_line_pattern_element(Object);
extern Object twrite_list_function(Object,Object,Object,Object,Object);
extern Object twrite_symbol(int,...);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_for_user_or_datum_type(Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object update_connection_images(Object,Object,Object);
extern Object valid_dash_element(Object);
extern Object valid_dash_length(Object);
extern Object valid_dash_symbol(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object variable_spec_transform(Object);
extern Object workspace_of_connection_qm(Object);
extern Object write_class_inheritance_path_of_definition_from_slot(Object,Object);
extern Object write_connection_arrows_from_slot(Object,Object);
extern Object write_connection_instance_style_from_slot(Object,Object);
extern Object write_connection_line_pattern_from_slot(Object,Object);
extern Object write_cross_section_component(Object);
extern Object write_cross_section_pattern_from_slot(Object,Object);
extern Object write_default_override(Object,Object);
extern Object write_list_in_chicago_style(int,...);
extern Object write_list_of_classes_from_slot(Object,Object);
extern Object write_list_of_connection_classes_from_slot(Object,Object);
extern Object write_list_of_item_classes_from_slot(Object,Object);
extern Object write_list_of_message_classes_from_slot(Object,Object);
extern Object write_list_of_object_classes_from_slot(Object,Object);
extern Object write_list_of_slots_from_slot(Object,Object);
extern Object write_number_qm_from_slot(Object,Object);
extern Object write_old_attribute_description(Object,Object);
extern Object write_old_attribute_descriptions_from_slot(Object,Object);
extern Object write_old_default_settings_from_slot(Object,Object);
extern Object write_old_superior_class_from_slot(Object,Object);
extern Object write_previous_capabilities_from_slot(Object,Object);
extern Object write_region_specification_list(Object);
extern Object write_stub_length_from_slot(Object,Object);
extern Object write_symbol_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object write_symbol_with_a_or_an(int,...);

#else

extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_initial_value_for_declared_type();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object antonym_of();
extern Object assq_function();
extern Object attribute_definition_type_specification();
extern Object bad_attribute_name();
extern Object badly_formed_attribute_name();
extern Object body_of_put_for_simulation_frame();
extern Object bytes_per_double_float_simple_array();
extern Object change_connection_attribute();
extern Object change_slot_value();
extern Object check_value_attribute_initialization_type();
extern Object circularity_in_potential_definition_inheritance();
extern Object class_instantiation_warning_incompatible_class();
extern Object class_instantiation_warning_not_defined();
extern Object class_instantiation_warning_undefined_type_specification_class();
extern Object class_type_specification_p();
extern Object clear_optimized_constants();
extern Object collect_subclasses();
extern Object color_or_metacolor_p();
extern Object compile_attribute_descriptions_for_slot();
extern Object compile_class_for_slot();
extern Object compile_connection_arrows_for_slot();
extern Object compile_connection_class_for_slot();
extern Object compile_connection_line_pattern_for_slot();
extern Object compile_cross_section_pattern_for_slot();
extern Object compile_default_overrides_for_object_definitions_for_slot();
extern Object compile_item_class_for_slot();
extern Object compile_list_of_classes_for_slot();
extern Object compile_list_of_connection_classes_for_slot();
extern Object compile_list_of_item_classes_for_slot();
extern Object compile_list_of_message_classes_for_slot();
extern Object compile_list_of_object_classes_for_slot();
extern Object compile_message_class_for_slot();
extern Object compile_new_class_for_slot();
extern Object compile_object_class_for_slot();
extern Object compile_old_attribute_descriptions_for_slot();
extern Object compile_old_default_settings_for_slot();
extern Object compile_old_superior_class_for_slot();
extern Object compile_previous_capabilities_for_slot();
extern Object compile_stub_length_for_slot();
extern Object compile_symbolic_value_list_for_slot();
extern Object compute_connection_arrows_spec();
extern Object compute_connection_arrows_structure();
extern Object connection_arrows_adjective_phrase();
extern Object connection_arrows_scale_index();
extern Object connection_line_pattern_absolute_p();
extern Object connection_line_pattern_dashes();
extern Object connection_line_pattern_explicit_p();
extern Object copy_constant_wide_string_given_length();
extern Object copy_for_phrase();
extern Object copy_for_slot_value();
extern Object copy_list_using_eval_conses_1();
extern Object copy_list_using_frame_conses_1();
extern Object copy_list_using_phrase_conses();
extern Object copy_out_current_wide_string();
extern Object copy_tree_using_frame_conses_1();
extern Object cut_out_fifth_element();
extern Object cut_out_fourth_element();
extern Object cut_out_sixth_element();
extern Object decode_arrow_spec_1();
extern Object def_semi_open_category_1();
extern Object define_type_specification_explicit_complex_type();
extern Object definition_class_is_subclass_of_obj_conn_mess_definition_p();
extern Object direct_superiors_are_defined_p();
extern Object direct_superiors_give_ancestors_different_precedence();
extern Object do_valid_superior_tests();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object eval_list_4();
extern Object evaluation_truth_value_is_true_p();
extern Object expt2();
extern Object fix_attribute_description();
extern Object fix_attribute_description_initial_value();
extern Object fix_connection_arrows_stub_spec();
extern Object fix_connection_line_pattern_stub_spec();
extern Object fix_connection_style_stub_spec();
extern Object fix_old_attribute_description();
extern Object fix_stub_info();
extern Object fix_up_cross_section_pattern();
extern Object fix_up_symbolic_value_list();
extern Object flatten_phrase_tree();
extern Object frame_cons_1();
extern Object frame_list_3();
extern Object generate_float_vector();
extern Object get_class_feature_if_any();
extern Object get_foundation_class_for_class();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value_given_default();
extern Object get_slot_description_of_class_description_function();
extern Object get_specialized_definition_class();
extern Object get_symbol_properties_function();
extern Object getfq_function();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object incorrect_foundation_class_for_this_definition_p();
extern Object instantiate_object_in_attribute();
extern Object instantiate_object_in_attribute_1();
extern Object instantiate_variable();
extern Object instantiated_class_p();
extern Object invalidates_direct_superiors_for_potential_definition();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_stock_line_pattern_element();
extern Object make_bad_region_text_string();
extern Object make_class_inheritance_path_for_user_defined_class();
extern Object make_eval_list_1();
extern Object make_frame();
extern Object make_phrase_list();
extern Object make_simulation_subtable_and_install();
extern Object make_simulation_subtable_with_specific_class_and_install();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object memq_2_cddddr();
extern Object memq_2_cdddr();
extern Object memq_3_cddddr();
extern Object memq_3_cdr_cddddr();
extern Object memq_function();
extern Object merging_paths_common_ancestor_rule_2_violation_p();
extern Object most_refined_foundation_class_of_direct_superiors();
extern Object mutate_global_property();
extern Object note_change_to_block_1();
extern Object note_use_of_managed_float_in_phrase();
extern Object parsed_attribute_initial_value_matches_type_p();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object phrase_list_3();
extern Object phrase_list_4();
extern Object phrase_number_p();
extern Object position_in_float_list();
extern Object potential_definition_cannot_inherit_foundation_class();
extern Object potential_definition_class_type_is_incompatible();
extern Object potential_definition_has_different_class_type();
extern Object potential_definition_superior_not_the_mixed_hierarchy_type();
extern Object prepare_for_indexed_attributes_moveage();
extern Object print_constant();
extern Object process_pre_4_dot_0_attribute_descriptions_and_default_overrides();
extern Object process_pre_4_dot_0_capabilities_of_class();
extern Object push_optimized_constant();
extern Object put_attributes_specific_to_class();
extern Object put_capabilities_and_restrictions();
extern Object put_connection_arrows();
extern Object put_default_settings();
extern Object put_line_pattern();
extern Object put_superior_class();
extern Object reclaim_frame_list_1();
extern Object reclaim_frame_tree_1();
extern Object reclaim_slot_value();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_lookup_cons_pool();
extern Object reserved_system_slot_name_p();
extern Object scope_cons();
extern Object second_none();
extern Object sequence_type_specification_p();
extern Object set_evaluation_value_to_category_function();
extern Object set_grammar_transform_can_return_bad_phrase_p();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_property_value_function();
extern Object set_skip_list_entry();
extern Object set_slot_value_to_evaluation_value_function();
extern Object slot_value_cons_1();
extern Object structure_type_specification_p();
extern Object subclass_appears_after_superior_for_potential_definition();
extern Object symbolic_type_specification_p();
extern Object system_class_is_not_user_subclassable_p();
extern Object system_slot_is_present_only_on_non_user_subclassable_system_slots();
extern Object system_slot_is_user_subclassable_1();
extern Object system_slot_override_but_no_foundation_class();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object truth_value_phrase_p();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_connection_arrow();
extern Object twrite_general_string();
extern Object twrite_line_pattern_element();
extern Object twrite_list_function();
extern Object twrite_symbol();
extern Object type_error_in_setter();
extern Object type_specification_for_user_or_datum_type();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object update_connection_images();
extern Object valid_dash_element();
extern Object valid_dash_length();
extern Object valid_dash_symbol();
extern Object validate_item_or_evaluation_value();
extern Object variable_spec_transform();
extern Object workspace_of_connection_qm();
extern Object write_class_inheritance_path_of_definition_from_slot();
extern Object write_connection_arrows_from_slot();
extern Object write_connection_instance_style_from_slot();
extern Object write_connection_line_pattern_from_slot();
extern Object write_cross_section_component();
extern Object write_cross_section_pattern_from_slot();
extern Object write_default_override();
extern Object write_list_in_chicago_style();
extern Object write_list_of_classes_from_slot();
extern Object write_list_of_connection_classes_from_slot();
extern Object write_list_of_item_classes_from_slot();
extern Object write_list_of_message_classes_from_slot();
extern Object write_list_of_object_classes_from_slot();
extern Object write_list_of_slots_from_slot();
extern Object write_number_qm_from_slot();
extern Object write_old_attribute_description();
extern Object write_old_attribute_descriptions_from_slot();
extern Object write_old_default_settings_from_slot();
extern Object write_old_superior_class_from_slot();
extern Object write_previous_capabilities_from_slot();
extern Object write_region_specification_list();
extern Object write_stub_length_from_slot();
extern Object write_symbol_from_slot();
extern Object write_symbol_list();
extern Object write_symbol_with_a_or_an();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Attribute_nesting_depth, Qattribute_nesting_depth);
#define Attribute_nesting_limit FIX((SI_Long)20L)
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Bad_phrase;
extern Object Cached_system_slot_is_present_only_on_non_user_subclassable_system_slots_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
extern Object Classes_for_class_definition;
extern Object Classes_for_object_definition;
extern Object Connection_arrow_permitted_scales;
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_definition_class_description, Qconnection_definition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Default_junction_class_description, Qdefault_junction_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Definition_class_description, Qdefinition_class_description);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_being_made, Qframe_being_made);
DECLARE_VARIABLE_WITH_SYMBOL(Grammar_categories_getting_choose_existing_class_feature, Qgrammar_categories_getting_choose_existing_class_feature);
extern Object Inferior_classes_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Leave_text_representation_as_a_single_line_qm, Qleave_text_representation_as_a_single_line_qm);
#define Managed_array_index_offset FIX((SI_Long)2L)
#define Maximum_connection_dash_count FIX((SI_Long)256L)
#define Maximum_connection_dash_length FIX((SI_Long)127L)
extern Object Maximum_in_place_array_size;
DECLARE_VARIABLE_WITH_SYMBOL(Message_class_description, Qmessage_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Message_definition_class_description, Qmessage_definition_class_description);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Object_class_description, Qobject_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Object_definition_class_description, Qobject_definition_class_description);
extern Object Phrase_sequence_marker;
extern Object Phrase_structure_marker;
extern Object Potential_inferior_class_definitions_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
extern Object Recursive_attribute_nesting_has_occurred_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_subtable_class_description, Qsimulation_subtable_class_description);
extern Object Stock_line_pattern_type;
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
extern Object Symbol_properties_table;
extern Object System_class_overrides_for_class_definition;
extern Object System_class_overrides_for_object_definition;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Write_strings_parsably_qm, Qwrite_strings_parsably_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
