/* grphs1.h -- Header File for grphs1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qblock;
extern Object Qdouble_float;
extern Object Qeq;
extern Object Qeval;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_class_to_environment(int,...);
extern Object add_form_to_graph_line_drawing_description(Object);
extern Object add_graph_clear(void);
extern Object add_graph_clear_rectangle(Object,Object,Object,Object);
extern Object add_graph_color_to_use(Object);
extern Object add_graph_data_extrema(Object);
extern Object add_graph_line(Object,Object,Object,Object,Object);
extern Object add_graph_line_width_to_use(Object);
extern Object add_graph_marker(Object,Object,Object);
extern Object add_graph_new_dateline(Object,Object);
extern Object add_graph_rectangle(Object,Object,Object,Object);
extern Object add_graph_shading(Object);
extern Object adjust_and_compute_x_value_on_graph(Object,Object,Object,Object);
extern Object adjust_managed_array(int,...);
extern Object adjust_managed_float_array(int,...);
extern Object adjust_x_value_according_to_dateline(Object,Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_managed_float_box(void);
extern Object bogus_preflight_from_printing_to_graphs(Object);
extern Object bytes_per_simple_vector(Object);
extern Object change_slot_value(int,...);
extern Object change_text_box_property(Object,Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object choose_format_for_graph_rendering(Object);
extern Object cleanup_for_graph(Object);
extern Object cleanup_for_graph_grid(Object);
extern Object clear_data_clipping_rectangles(void);
extern Object clear_optimized_constants(void);
extern Object clear_plot_marker_data(Object);
extern Object collect_subclasses(Object);
extern Object color_value_given_color_or_default(Object);
extern Object combine_new_extrema_with_existing_ones(Object,Object,Object,Object,Object);
extern Object compute_erase_dateline(Object);
extern Object compute_erase_dateline_1(Object,Object);
extern Object compute_graph_line_color_value(Object,Object);
extern Object compute_next_larger_size_for_ring_buffer_vectors(Object);
extern Object compute_size_for_graphs_of_size_upon_workspace(Object,Object,Object,Object);
extern Object compute_size_of_graph_rendering_1(Object,Object);
extern Object compute_x_value_on_graph(Object,Object);
extern Object compute_y_value_on_graph(Object,Object,Object);
extern Object compute_y_value_on_graph_new(Object);
extern Object compute_y_value_on_graph_new_with_less_truncation(Object);
extern Object constant_queue_next(Object,Object);
extern Object copy_plot_data_ring_buffer(int,...);
extern Object copy_ring_buffer_shell_slots(Object,Object);
extern Object copy_ring_buffer_vector(Object);
extern Object copy_text_string(Object);
extern Object data_exists_for_plot_p(Object);
extern Object decache_all_graph_renderings_of_graph_grid(Object);
extern Object decache_and_remove_all_graph_renderings_from_graph_grid(Object);
extern Object decache_graph_rendering(Object);
extern Object direct_structure_method(Object,Object);
extern Object draw_block_outline_in_current_image_plane(int,...);
extern Object draw_current_graph_rendering(Object,Object,Object,Object);
extern Object draw_data_for_graph_grid(Object,Object);
extern Object draw_data_for_plot(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_data_point(Object,Object,Object,Object,Object,Object,Object);
extern Object draw_extra_grid_lines(Object,Object,Object,Object);
extern Object draw_extra_horizontal_grid_line(Object,Object,Object,Object,Object);
extern Object draw_for_graph(Object);
extern Object draw_for_graph_grid(Object);
extern Object draw_for_table(Object);
extern Object draw_graph_axis_label(Object,Object);
extern Object draw_graph_grid(Object,Object);
extern Object draw_graph_grid_and_data(Object,Object);
extern Object draw_graph_grid_current_time_display(Object);
extern Object draw_graphic_element(int,...);
extern Object draw_horizontal_grid_lines(Object,Object,Object,Object);
extern Object draw_new_scrolled_vertical_grid_lines(Object);
extern Object draw_only_new_data_for_graph_grid(Object);
extern Object draw_plot_marker(Object,Object,Object,Object,Object,Object);
extern Object draw_rectangle_outline_in_window(Object,Object,Object,Object,Object,Object,Object);
extern Object draw_text_segment_1(Object,Object,Object,Object,Object,Object,Object);
extern Object draw_vertical_grid_lines(Object);
extern Object expand_plot_data_ring_buffer(Object);
extern Object extend_extrema_if_necessary(Object,Object);
extern Object extend_maximum_x_value_if_necessary(Object);
extern Object extend_maximum_y_value_if_necessary(Object);
extern Object extend_minimum_x_value_if_necessary(Object);
extern Object extend_minimum_y_value_if_necessary(Object);
extern Object fill_out_table_spot(Object,Object,Object);
extern Object format_frame_to_reformat_by_if_any(Object,Object);
extern Object generate_spot_for_aggregate(Object,Object);
extern Object generate_spot_for_graph_axis_label(Object,Object);
extern Object generate_spot_for_input_table(Object,Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_erase_dateline_on_graph(Object);
extern Object get_graph_rendering_for_current_window(Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_marker_dimensions(Object,Object,Object,Object);
extern Object get_memory_limit_info_given_size(Object,Object);
extern Object get_or_make_graph_rendering(Object);
extern Object get_reference_to_item(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object graph_cons_1(Object,Object);
extern Object graph_list_2(Object,Object);
extern Object graph_list_3(Object,Object,Object);
extern Object graph_list_4(Object,Object,Object,Object);
extern Object graph_needs_formatting_qm(Object,Object,Object);
extern Object graph_rendering_has_wrong_scale_qm(Object);
extern Object increase_allocation_limit_for_graphs_if_necessary(Object,Object,Object,Object);
extern Object initialize_to_managed_float_box(void);
extern Object inner_full_paint_2d_grid(Object);
extern Object inner_partial_paint_2d_grid(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_decacheable_graph_rendering(int,...);
extern Object make_free_text_box(int,...);
extern Object make_graph_axis_label(int,...);
extern Object make_graph_not_up_to_date(Object);
extern Object make_graph_rendering_structure(Object);
extern Object make_graph_rendering_structure_if_necessary(Object);
extern Object make_graph_table_spot_1(void);
extern Object make_graphs_opaque_1(void);
extern Object make_new_graph_rendering(Object,Object,Object);
extern Object make_or_reformat_graph_grid(int,...);
extern Object make_permanent_plot_data_ring_buffer_structure_internal(void);
extern Object make_plot_data_ring_buffer_1(void);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_thread_array(Object);
extern Object map_to_color_value(Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object native_printing_p(void);
extern Object note_change_to_block_1(Object,Object);
extern Object outstanding_plot_data_ring_buffer_count(void);
extern Object paint_background_for_opaque_block(Object);
extern Object paint_clipped_rectangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object);
extern Object paint_clipped_triangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object);
extern Object paint_filled_triangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object);
extern Object paint_graph_from_graph_rendering(Object,Object,Object);
extern Object paint_graph_line_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object);
extern Object paint_graph_on_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object);
extern Object paint_graph_rendering_raster(void);
extern Object paint_graph_rendering_raster_1(void);
extern Object paint_graph_to_native_printer(Object);
extern Object paint_line_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object);
extern Object paint_nupec_plot_marker(Object,Object,Object,Object,Object,Object);
extern Object paint_plot_marker(Object,Object,Object,Object);
extern Object paint_shaded_line_in_current_scratchpad_raster(Object,Object,Object,Object,Object);
extern Object paint_solid_rectangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object);
extern Object paint_wide_line_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object);
extern Object plot_color_given_plot(Object);
extern Object plot_data_ring_buffer_structure_memory_usage(void);
extern Object plot_line_width_given_plot(Object);
extern Object plot_marker_and_or_line_width(Object);
extern Object plot_marker_given_plot(Object);
extern Object plot_marker_or_shading_key_given_plot(Object);
extern Object plot_max_given_plot_min_and_max(Object);
extern Object plot_min_and_max_given_plot(Object);
extern Object plot_min_given_plot_min_and_max(Object);
extern Object plot_shading_given_plot(Object);
extern Object point_not_on_graph_qm(Object);
extern Object polychrome_rasters_for_graphs_p(Object);
extern Object printing_p(void);
extern Object printing_window_p(Object);
extern Object project_chart_call_back(Object,Object);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_plot_pattern_where_slot_is_absent(Object,Object);
extern Object reclaim_data_buffer_for_plot_value(Object,Object);
extern Object reclaim_desired_high_value_for_horizontal_axis_value(Object,Object);
extern Object reclaim_desired_high_value_for_vertical_axis_value(Object,Object);
extern Object reclaim_desired_low_value_for_horizontal_axis_value(Object,Object);
extern Object reclaim_desired_low_value_for_vertical_axis_value(Object,Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_graph_list_1(Object);
extern Object reclaim_graph_tree_1(Object);
extern Object reclaim_high_value_for_horizontal_axis_value(Object,Object);
extern Object reclaim_high_value_for_horizontal_grid_lines_value(Object,Object);
extern Object reclaim_high_value_for_vertical_axis_value(Object,Object);
extern Object reclaim_high_value_for_vertical_grid_lines_value(Object,Object);
extern Object reclaim_horizontal_axis_range_value(Object,Object);
extern Object reclaim_horizontal_grid_line_spacing_value(Object,Object);
extern Object reclaim_interval_between_horizontal_grid_lines_value(Object,Object);
extern Object reclaim_interval_between_vertical_grid_lines_value(Object,Object);
extern Object reclaim_line_drawing_description_for_graph_grid_qm_value(Object,Object);
extern Object reclaim_low_value_for_horizontal_axis_value(Object,Object);
extern Object reclaim_low_value_for_horizontal_grid_lines_value(Object,Object);
extern Object reclaim_low_value_for_vertical_axis_value(Object,Object);
extern Object reclaim_low_value_for_vertical_grid_lines_value(Object,Object);
extern Object reclaim_managed_number_or_value_function(Object);
extern Object reclaim_plot_data_ring_buffer_1(Object);
extern Object reclaim_plot_marker_indices(Object);
extern Object reclaim_ring_buffer_vector(Object);
extern Object reclaim_tail_pointer_for_line_drawing_description_value(Object,Object);
extern Object reclaim_tail_pointer_for_line_segments_value(Object,Object);
extern Object reclaim_vertical_axis_range_value(Object,Object);
extern Object reclaim_vertical_grid_line_spacing_value(Object,Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reformat_as_appropriate_for_graph(Object,Object);
extern Object reformat_as_appropriate_for_table(Object,Object);
extern Object reformat_graph_based_on_edit_if_necessary(Object,Object);
extern Object reformat_table_in_place(int,...);
extern Object regenerate_optimized_constant(Object);
extern Object remove_graph_rendering_from_chart(Object,Object);
extern Object remove_graph_rendering_from_graph_grid(Object,Object);
extern Object remove_graph_rendering_from_trend_chart(Object,Object);
extern Object replenish_eval_cons_pool(void);
extern Object replenish_graph_cons_pool(void);
extern Object replenish_lookup_cons_pool(void);
extern Object rotate_managed_array(Object,Object);
extern Object rotate_managed_float_array(Object,Object);
extern Object round_for_graphs(Object);
extern Object scalef_function(Object,Object);
extern Object send_icp_end_message_block(void);
extern Object send_icp_prepare_for_painting_graph(Object);
extern Object set_current_background_color_value(Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object spot_generator_for_table_format_for_graphs(Object,Object);
extern Object store_new_data_extrema(Object,Object);
extern Object text_string_p(Object);
extern Object update_color_values_for_graph(Object,Object,Object,Object);
extern Object update_colors_of_current_graph_rendering(void);
extern Object update_graph_data_extrema(Object,Object,Object,Object);
extern Object update_graph_dateline(Object,Object,Object);
extern Object update_graph_rendering(void);
extern Object update_object_pool_meters_list(Object);
extern Object update_ring_raster_for_graph_given_color_values(Object,Object);
extern Object update_ring_raster_for_graph_given_color_values_2(Object,Object);

#else

extern Object add_class_to_environment();
extern Object add_form_to_graph_line_drawing_description();
extern Object add_graph_clear();
extern Object add_graph_clear_rectangle();
extern Object add_graph_color_to_use();
extern Object add_graph_data_extrema();
extern Object add_graph_line();
extern Object add_graph_line_width_to_use();
extern Object add_graph_marker();
extern Object add_graph_new_dateline();
extern Object add_graph_rectangle();
extern Object add_graph_shading();
extern Object adjust_and_compute_x_value_on_graph();
extern Object adjust_managed_array();
extern Object adjust_managed_float_array();
extern Object adjust_x_value_according_to_dateline();
extern Object alias_slot_name();
extern Object allocate_managed_float_box();
extern Object bogus_preflight_from_printing_to_graphs();
extern Object bytes_per_simple_vector();
extern Object change_slot_value();
extern Object change_text_box_property();
extern Object check_if_superior_classes_are_defined();
extern Object choose_format_for_graph_rendering();
extern Object cleanup_for_graph();
extern Object cleanup_for_graph_grid();
extern Object clear_data_clipping_rectangles();
extern Object clear_optimized_constants();
extern Object clear_plot_marker_data();
extern Object collect_subclasses();
extern Object color_value_given_color_or_default();
extern Object combine_new_extrema_with_existing_ones();
extern Object compute_erase_dateline();
extern Object compute_erase_dateline_1();
extern Object compute_graph_line_color_value();
extern Object compute_next_larger_size_for_ring_buffer_vectors();
extern Object compute_size_for_graphs_of_size_upon_workspace();
extern Object compute_size_of_graph_rendering_1();
extern Object compute_x_value_on_graph();
extern Object compute_y_value_on_graph();
extern Object compute_y_value_on_graph_new();
extern Object compute_y_value_on_graph_new_with_less_truncation();
extern Object constant_queue_next();
extern Object copy_plot_data_ring_buffer();
extern Object copy_ring_buffer_shell_slots();
extern Object copy_ring_buffer_vector();
extern Object copy_text_string();
extern Object data_exists_for_plot_p();
extern Object decache_all_graph_renderings_of_graph_grid();
extern Object decache_and_remove_all_graph_renderings_from_graph_grid();
extern Object decache_graph_rendering();
extern Object direct_structure_method();
extern Object draw_block_outline_in_current_image_plane();
extern Object draw_current_graph_rendering();
extern Object draw_data_for_graph_grid();
extern Object draw_data_for_plot();
extern Object draw_data_point();
extern Object draw_extra_grid_lines();
extern Object draw_extra_horizontal_grid_line();
extern Object draw_for_graph();
extern Object draw_for_graph_grid();
extern Object draw_for_table();
extern Object draw_graph_axis_label();
extern Object draw_graph_grid();
extern Object draw_graph_grid_and_data();
extern Object draw_graph_grid_current_time_display();
extern Object draw_graphic_element();
extern Object draw_horizontal_grid_lines();
extern Object draw_new_scrolled_vertical_grid_lines();
extern Object draw_only_new_data_for_graph_grid();
extern Object draw_plot_marker();
extern Object draw_rectangle_outline_in_window();
extern Object draw_text_segment_1();
extern Object draw_vertical_grid_lines();
extern Object expand_plot_data_ring_buffer();
extern Object extend_extrema_if_necessary();
extern Object extend_maximum_x_value_if_necessary();
extern Object extend_maximum_y_value_if_necessary();
extern Object extend_minimum_x_value_if_necessary();
extern Object extend_minimum_y_value_if_necessary();
extern Object fill_out_table_spot();
extern Object format_frame_to_reformat_by_if_any();
extern Object generate_spot_for_aggregate();
extern Object generate_spot_for_graph_axis_label();
extern Object generate_spot_for_input_table();
extern Object gensym_cons_1();
extern Object get_erase_dateline_on_graph();
extern Object get_graph_rendering_for_current_window();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_marker_dimensions();
extern Object get_memory_limit_info_given_size();
extern Object get_or_make_graph_rendering();
extern Object get_reference_to_item();
extern Object get_slot_description_of_class_description_function();
extern Object getfq_function_no_default();
extern Object graph_cons_1();
extern Object graph_list_2();
extern Object graph_list_3();
extern Object graph_list_4();
extern Object graph_needs_formatting_qm();
extern Object graph_rendering_has_wrong_scale_qm();
extern Object increase_allocation_limit_for_graphs_if_necessary();
extern Object initialize_to_managed_float_box();
extern Object inner_full_paint_2d_grid();
extern Object inner_partial_paint_2d_grid();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_decacheable_graph_rendering();
extern Object make_free_text_box();
extern Object make_graph_axis_label();
extern Object make_graph_not_up_to_date();
extern Object make_graph_rendering_structure();
extern Object make_graph_rendering_structure_if_necessary();
extern Object make_graph_table_spot_1();
extern Object make_graphs_opaque_1();
extern Object make_new_graph_rendering();
extern Object make_or_reformat_graph_grid();
extern Object make_permanent_plot_data_ring_buffer_structure_internal();
extern Object make_plot_data_ring_buffer_1();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_thread_array();
extern Object map_to_color_value();
extern Object memq_function();
extern Object mutate_global_property();
extern Object native_printing_p();
extern Object note_change_to_block_1();
extern Object outstanding_plot_data_ring_buffer_count();
extern Object paint_background_for_opaque_block();
extern Object paint_clipped_rectangle_in_current_scratchpad_raster();
extern Object paint_clipped_triangle_in_current_scratchpad_raster();
extern Object paint_filled_triangle_in_current_scratchpad_raster();
extern Object paint_graph_from_graph_rendering();
extern Object paint_graph_line_in_current_scratchpad_raster();
extern Object paint_graph_on_scratchpad_raster();
extern Object paint_graph_rendering_raster();
extern Object paint_graph_rendering_raster_1();
extern Object paint_graph_to_native_printer();
extern Object paint_line_in_current_scratchpad_raster();
extern Object paint_nupec_plot_marker();
extern Object paint_plot_marker();
extern Object paint_shaded_line_in_current_scratchpad_raster();
extern Object paint_solid_rectangle_in_current_scratchpad_raster();
extern Object paint_wide_line_in_current_scratchpad_raster();
extern Object plot_color_given_plot();
extern Object plot_data_ring_buffer_structure_memory_usage();
extern Object plot_line_width_given_plot();
extern Object plot_marker_and_or_line_width();
extern Object plot_marker_given_plot();
extern Object plot_marker_or_shading_key_given_plot();
extern Object plot_max_given_plot_min_and_max();
extern Object plot_min_and_max_given_plot();
extern Object plot_min_given_plot_min_and_max();
extern Object plot_shading_given_plot();
extern Object point_not_on_graph_qm();
extern Object polychrome_rasters_for_graphs_p();
extern Object printing_p();
extern Object printing_window_p();
extern Object project_chart_call_back();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_plot_pattern_where_slot_is_absent();
extern Object reclaim_data_buffer_for_plot_value();
extern Object reclaim_desired_high_value_for_horizontal_axis_value();
extern Object reclaim_desired_high_value_for_vertical_axis_value();
extern Object reclaim_desired_low_value_for_horizontal_axis_value();
extern Object reclaim_desired_low_value_for_vertical_axis_value();
extern Object reclaim_eval_list_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_graph_list_1();
extern Object reclaim_graph_tree_1();
extern Object reclaim_high_value_for_horizontal_axis_value();
extern Object reclaim_high_value_for_horizontal_grid_lines_value();
extern Object reclaim_high_value_for_vertical_axis_value();
extern Object reclaim_high_value_for_vertical_grid_lines_value();
extern Object reclaim_horizontal_axis_range_value();
extern Object reclaim_horizontal_grid_line_spacing_value();
extern Object reclaim_interval_between_horizontal_grid_lines_value();
extern Object reclaim_interval_between_vertical_grid_lines_value();
extern Object reclaim_line_drawing_description_for_graph_grid_qm_value();
extern Object reclaim_low_value_for_horizontal_axis_value();
extern Object reclaim_low_value_for_horizontal_grid_lines_value();
extern Object reclaim_low_value_for_vertical_axis_value();
extern Object reclaim_low_value_for_vertical_grid_lines_value();
extern Object reclaim_managed_number_or_value_function();
extern Object reclaim_plot_data_ring_buffer_1();
extern Object reclaim_plot_marker_indices();
extern Object reclaim_ring_buffer_vector();
extern Object reclaim_tail_pointer_for_line_drawing_description_value();
extern Object reclaim_tail_pointer_for_line_segments_value();
extern Object reclaim_vertical_axis_range_value();
extern Object reclaim_vertical_grid_line_spacing_value();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object reformat_as_appropriate_for_graph();
extern Object reformat_as_appropriate_for_table();
extern Object reformat_graph_based_on_edit_if_necessary();
extern Object reformat_table_in_place();
extern Object regenerate_optimized_constant();
extern Object remove_graph_rendering_from_chart();
extern Object remove_graph_rendering_from_graph_grid();
extern Object remove_graph_rendering_from_trend_chart();
extern Object replenish_eval_cons_pool();
extern Object replenish_graph_cons_pool();
extern Object replenish_lookup_cons_pool();
extern Object rotate_managed_array();
extern Object rotate_managed_float_array();
extern Object round_for_graphs();
extern Object scalef_function();
extern Object send_icp_end_message_block();
extern Object send_icp_prepare_for_painting_graph();
extern Object set_current_background_color_value();
extern Object set_non_savable_lookup_slot_value();
extern Object set_skip_list_entry();
extern Object slot_value_list_2();
extern Object spot_generator_for_table_format_for_graphs();
extern Object store_new_data_extrema();
extern Object text_string_p();
extern Object update_color_values_for_graph();
extern Object update_colors_of_current_graph_rendering();
extern Object update_graph_data_extrema();
extern Object update_graph_dateline();
extern Object update_graph_rendering();
extern Object update_object_pool_meters_list();
extern Object update_ring_raster_for_graph_given_color_values();
extern Object update_ring_raster_for_graph_given_color_values_2();

#endif

/* variables/constants */
extern Object Available_eval_conses_tail_vector;
extern Object Available_eval_conses_vector;
extern Object Available_graph_conses_tail_vector;
extern Object Available_graph_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Bogus_preflight_from_printing_to_graphs, Qbogus_preflight_from_printing_to_graphs);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_plot_data_ring_buffers, Qchain_of_available_plot_data_ring_buffers);
extern Object Chain_of_available_plot_data_ring_buffers_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chart_class_description, Qchart_class_description);
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_block_of_dependent_frame, Qcurrent_block_of_dependent_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_cascaded_ring_buffer, Qcurrent_cascaded_ring_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_data_buffer_for_plot, Qcurrent_data_buffer_for_plot);
DECLARE_VARIABLE_WITH_SYMBOL(Current_default_line_color, Qcurrent_default_line_color);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_graph_grid, Qcurrent_graph_grid);
DECLARE_VARIABLE_WITH_SYMBOL(Current_graph_grid_in_minimal_update, Qcurrent_graph_grid_in_minimal_update);
DECLARE_VARIABLE_WITH_SYMBOL(Current_graph_rendering, Qcurrent_graph_rendering);
DECLARE_VARIABLE_WITH_SYMBOL(Current_graph_rendering_structure, Qcurrent_graph_rendering_structure);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_index, Qcurrent_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_minimal_grid_draw_has_seen_one_image_plane_p, Qcurrent_minimal_grid_draw_has_seen_one_image_plane_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_plot, Qcurrent_plot);
DECLARE_VARIABLE_WITH_SYMBOL(Current_plot_number, Qcurrent_plot_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_color_value_list, Qcurrent_scratchpad_color_value_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster, Qcurrent_scratchpad_raster);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_depth, Qcurrent_scratchpad_raster_depth);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_height, Qcurrent_scratchpad_raster_height);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_list, Qcurrent_scratchpad_raster_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_tiled_p, Qcurrent_scratchpad_raster_tiled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_type, Qcurrent_scratchpad_raster_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_width, Qcurrent_scratchpad_raster_width);
DECLARE_VARIABLE_WITH_SYMBOL(Current_text_box_format, Qcurrent_text_box_format);
DECLARE_VARIABLE_WITH_SYMBOL(Current_text_cell_plist, Qcurrent_text_cell_plist);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Data_point_value, Qdata_point_value);
extern Object Default_axis_half_range;
extern Object Default_data_point_y_size;
DECLARE_VARIABLE_WITH_SYMBOL(Default_duration_for_data_point, Qdefault_duration_for_data_point);
extern Object Default_graph_left_margin_width;
DECLARE_VARIABLE_WITH_SYMBOL(Default_graph_line_color_value, Qdefault_graph_line_color_value);
extern Object Default_graph_right_margin_width;
extern Object Default_interval_between_vertical_grid_lines;
extern Object Default_marker_half_size;
extern Object Default_marker_size;
extern Object Default_number_of_markers;
extern Object Default_number_of_vertical_grid_lines;
DECLARE_VARIABLE_WITH_SYMBOL(Desired_high_value_for_horizontal_axis, Qdesired_high_value_for_horizontal_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Desired_high_value_for_vertical_axis, Qdesired_high_value_for_vertical_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Desired_low_value_for_horizontal_axis, Qdesired_low_value_for_horizontal_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Desired_low_value_for_vertical_axis, Qdesired_low_value_for_vertical_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Erase_dateline, Qerase_dateline);
DECLARE_VARIABLE_WITH_SYMBOL(Erase_instead_qm, Qerase_instead_qm);
extern Object Erase_zone_ratio;
DECLARE_VARIABLE_WITH_SYMBOL(Fixnum_maximum_y_value, Qfixnum_maximum_y_value);
DECLARE_VARIABLE_WITH_SYMBOL(Fixnum_minimum_y_value, Qfixnum_minimum_y_value);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_background_color_value, Qgraph_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_class_description, Qgraph_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_grid_class_description, Qgraph_grid_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_grid_for_data, Qgraph_grid_for_data);
extern Object Graph_rendering_lru_queue;
extern Object Graph_rendering_memory_limit_info;
DECLARE_VARIABLE_WITH_SYMBOL(Grid_height, Qgrid_height);
DECLARE_VARIABLE_WITH_SYMBOL(Grid_width, Qgrid_width);
DECLARE_VARIABLE_WITH_SYMBOL(Handy_float_1, Qhandy_float_1);
DECLARE_VARIABLE_WITH_SYMBOL(High_value_for_horizontal_grid_lines, Qhigh_value_for_horizontal_grid_lines);
DECLARE_VARIABLE_WITH_SYMBOL(High_value_for_vertical_grid_lines, Qhigh_value_for_vertical_grid_lines);
DECLARE_VARIABLE_WITH_SYMBOL(History_time_per_pixel, Qhistory_time_per_pixel);
DECLARE_VARIABLE_WITH_SYMBOL(History_time_to_evaluate_display_expression_with, Qhistory_time_to_evaluate_display_expression_with);
DECLARE_VARIABLE_WITH_SYMBOL(Horizontal_grid_line_color_qm, Qhorizontal_grid_line_color_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Horizontal_grid_line_spacing, Qhorizontal_grid_line_spacing);
DECLARE_VARIABLE_WITH_SYMBOL(Horizontal_grid_line_width, Qhorizontal_grid_line_width);
#define Icp_window_protocol_supports_monochrome_raster_lists FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Index_for_stop_time, Qindex_for_stop_time);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Interval_between_horizontal_grid_lines, Qinterval_between_horizontal_grid_lines);
DECLARE_VARIABLE_WITH_SYMBOL(Interval_between_plot_markers, Qinterval_between_plot_markers);
DECLARE_VARIABLE_WITH_SYMBOL(Interval_between_vertical_grid_lines, Qinterval_between_vertical_grid_lines);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Joes_graph_hax_p, Qjoes_graph_hax_p);
DECLARE_VARIABLE_WITH_SYMBOL(Joes_graph_hax_trace_p, Qjoes_graph_hax_trace_p);
extern Object Largest_ring_buffer_vector_size;
DECLARE_VARIABLE_WITH_SYMBOL(Last_history_time_for_data_point_on_pixel, Qlast_history_time_for_data_point_on_pixel);
DECLARE_VARIABLE_WITH_SYMBOL(Low_and_high_values_specified_for_vertical_axis_qm, Qlow_and_high_values_specified_for_vertical_axis_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Low_value_for_horizontal_axis, Qlow_value_for_horizontal_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Low_value_for_horizontal_grid_lines, Qlow_value_for_horizontal_grid_lines);
DECLARE_VARIABLE_WITH_SYMBOL(Low_value_for_vertical_axis, Qlow_value_for_vertical_axis);
DECLARE_VARIABLE_WITH_SYMBOL(Low_value_for_vertical_grid_lines, Qlow_value_for_vertical_grid_lines);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Managed_array_unique_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Many_more_data_points_than_pixels_qm, Qmany_more_data_points_than_pixels_qm);
extern Object Maximum_in_place_array_size;
extern Object Maximum_number_of_horizontal_grid_lines;
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_x_value_for_new_data, Qmaximum_x_value_for_new_data);
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_y_value, Qmaximum_y_value);
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_y_value_for_new_data, Qmaximum_y_value_for_new_data);
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_y_value_for_pixel, Qmaximum_y_value_for_pixel);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_and_maximum_y_value_set_qm, Qminimum_and_maximum_y_value_set_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_distance_for_data_points, Qminimum_distance_for_data_points);
extern Object Minimum_range_to_maximum_value_ratio;
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_x_value_for_new_data, Qminimum_x_value_for_new_data);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_y_value, Qminimum_y_value);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_y_value_for_new_data, Qminimum_y_value_for_new_data);
DECLARE_VARIABLE_WITH_SYMBOL(Minimum_y_value_for_pixel, Qminimum_y_value_for_pixel);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Most_recent_extremum_maximum_for_pixel_p, Qmost_recent_extremum_maximum_for_pixel_p);
DECLARE_VARIABLE_WITH_SYMBOL(Most_recent_extremum_maximum_p, Qmost_recent_extremum_maximum_p);
DECLARE_VARIABLE_WITH_SYMBOL(New_dateline_qm, Qnew_dateline_qm);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Offset_ratio_for_plot_markers;
DECLARE_VARIABLE_WITH_SYMBOL(On_monochrome_raster_list_p, Qon_monochrome_raster_list_p);
DECLARE_VARIABLE_WITH_SYMBOL(Paint_only_target_monochrome_raster_p, Qpaint_only_target_monochrome_raster_p);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_class_description, Qplot_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_data_ring_buffer_count, Qplot_data_ring_buffer_count);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_marker_qm, Qplot_marker_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_max_qm, Qplot_max_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_min_and_max_qm, Qplot_min_and_max_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Plot_min_qm, Qplot_min_qm);
extern Object Plus_sign_marker_half_size;
extern Object Plus_sign_marker_size;
DECLARE_VARIABLE_WITH_SYMBOL(Printing_pass_number, Qprinting_pass_number);
DECLARE_VARIABLE_WITH_SYMBOL(Redraw_as_well_as_reformat_p, Qredraw_as_well_as_reformat_p);
DECLARE_VARIABLE_WITH_SYMBOL(Ring_buffer_for_history_time, Qring_buffer_for_history_time);
DECLARE_VARIABLE_WITH_SYMBOL(Scale_y_data_points_qm, Qscale_y_data_points_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Scratchpad_raster, Qscratchpad_raster);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
extern Object The_type_description_of_plot_data_ring_buffer;
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
DECLARE_VARIABLE_WITH_SYMBOL(Vertical_axis_range, Qvertical_axis_range);
DECLARE_VARIABLE_WITH_SYMBOL(Vertical_grid_line_color_qm, Qvertical_grid_line_color_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Vertical_grid_line_spacing, Qvertical_grid_line_spacing);
DECLARE_VARIABLE_WITH_SYMBOL(Vertical_grid_line_width, Qvertical_grid_line_width);
DECLARE_VARIABLE_WITH_SYMBOL(X_data_min_set_qm, Qx_data_min_set_qm);
DECLARE_VARIABLE_WITH_SYMBOL(X_value_on_graph, Qx_value_on_graph);
