/* hbrw14.c
 * Input file:  hebrew14.lisp
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */

#include "user.h"
#include "hbrw14.h"


void hebrew14_INIT()
{
    Object string_constant, Qroman, Qhebrew14, AB_package;

    x_note_fn_call(71,0);
    SET_PACKAGE("AB");
    AB_package = STATIC_PACKAGE("AB");
    Qhebrew14 = STATIC_SYMBOL("HEBREW14",AB_package);
    Qroman = STATIC_SYMBOL("ROMAN",AB_package);
    define_ab_font(16,Qhebrew14,Qroman,FIX((SI_Long)14L),FIX((SI_Long)12L),
	    FIX((SI_Long)16L),FIX((SI_Long)18L),Nil,Nil,Nil,
	    FIX((SI_Long)14L),FIX((SI_Long)70L),FIX((SI_Long)70L),
	    FIX((SI_Long)3484L),FIX((SI_Long)3484L),FIX((SI_Long)-1L),
	    FIX((SI_Long)-3L));
    string_constant = STATIC_STRING("0");
    add_character_description_1(9,FIX((SI_Long)20L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)21L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)22L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1742L),Nil);
    add_character_description_1(9,FIX((SI_Long)23L),FIX((SI_Long)9L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)8L),
	    FIX((SI_Long)13L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2324L),Nil);
    add_character_description_1(9,FIX((SI_Long)24L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)25L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)26L),FIX((SI_Long)4L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)1L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)968L),Nil);
    add_character_description_1(9,FIX((SI_Long)27L),FIX((SI_Long)8L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)14L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1938L),Nil);
    add_character_description_1(9,FIX((SI_Long)28L),FIX((SI_Long)11L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)13L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2710L),Nil);
    add_character_description_1(9,FIX((SI_Long)29L),FIX((SI_Long)8L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1938L),Nil);
    add_character_description_1(9,FIX((SI_Long)30L),FIX((SI_Long)11L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2841L),Nil);
    add_character_description_1(9,FIX((SI_Long)31L),FIX((SI_Long)8L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1938L),Nil);
    add_character_description_1(9,FIX((SI_Long)32L),FIX((SI_Long)5L),
	    FIX((SI_Long)2L),FIX((SI_Long)-3L),FIX((SI_Long)1L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)33L),FIX((SI_Long)5L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)5L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)34L),FIX((SI_Long)5L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)4L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)35L),FIX((SI_Long)5L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)5L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)36L),FIX((SI_Long)5L),
	    FIX((SI_Long)2L),FIX((SI_Long)-3L),FIX((SI_Long)1L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)37L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)38L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)3L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)39L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)-2L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)40L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)3L),
	    FIX((SI_Long)2L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)41L),FIX((SI_Long)5L),
	    FIX((SI_Long)2L),FIX((SI_Long)8L),FIX((SI_Long)1L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)42L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)43L),FIX((SI_Long)5L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)5L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)44L),FIX((SI_Long)5L),
	    FIX((SI_Long)2L),FIX((SI_Long)4L),FIX((SI_Long)1L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)45L),FIX((SI_Long)5L),
	    FIX((SI_Long)2L),FIX((SI_Long)-3L),FIX((SI_Long)1L),
	    FIX((SI_Long)2L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)46L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)6L),FIX((SI_Long)4L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1334L),Nil);
    add_character_description_1(9,FIX((SI_Long)47L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)8L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)48L),FIX((SI_Long)4L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)1L),
	    FIX((SI_Long)9L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)958L),Nil);
    add_character_description_1(9,FIX((SI_Long)49L),FIX((SI_Long)5L),
	    FIX((SI_Long)5L),FIX((SI_Long)8L),FIX((SI_Long)1L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)50L),FIX((SI_Long)5L),
	    FIX((SI_Long)-2L),FIX((SI_Long)8L),FIX((SI_Long)1L),
	    FIX((SI_Long)1L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1160L),Nil);
    add_character_description_1(9,FIX((SI_Long)51L),FIX((SI_Long)4L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)1L),
	    FIX((SI_Long)7L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)968L),Nil);
    add_character_description_1(9,FIX((SI_Long)52L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)53L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)54L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)55L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)56L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)57L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)58L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)59L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)60L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)61L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)62L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)63L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)64L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1961L),Nil);
    add_character_description_1(9,FIX((SI_Long)65L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1888L),Nil);
    add_character_description_1(9,FIX((SI_Long)66L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1390L),Nil);
    add_character_description_1(9,FIX((SI_Long)67L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1771L),Nil);
    add_character_description_1(9,FIX((SI_Long)68L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2098L),Nil);
    add_character_description_1(9,FIX((SI_Long)69L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)1L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)859L),Nil);
    add_character_description_1(9,FIX((SI_Long)70L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1332L),Nil);
    add_character_description_1(9,FIX((SI_Long)71L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2086L),Nil);
    add_character_description_1(9,FIX((SI_Long)72L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2055L),Nil);
    add_character_description_1(9,FIX((SI_Long)73L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),FIX((SI_Long)4L),FIX((SI_Long)1L),
	    FIX((SI_Long)4L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)859L),Nil);
    add_character_description_1(9,FIX((SI_Long)74L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1774L),Nil);
    add_character_description_1(9,FIX((SI_Long)75L),FIX((SI_Long)6L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1606L),Nil);
    add_character_description_1(9,FIX((SI_Long)76L),FIX((SI_Long)6L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)5L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1613L),Nil);
    add_character_description_1(9,FIX((SI_Long)77L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2086L),Nil);
    add_character_description_1(9,FIX((SI_Long)78L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2094L),Nil);
    add_character_description_1(9,FIX((SI_Long)79L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)1L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)859L),Nil);
    add_character_description_1(9,FIX((SI_Long)80L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)3L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1228L),Nil);
    add_character_description_1(9,FIX((SI_Long)81L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2001L),Nil);
    add_character_description_1(9,FIX((SI_Long)82L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)-1L),FIX((SI_Long)6L),
	    FIX((SI_Long)9L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1844L),Nil);
    add_character_description_1(9,FIX((SI_Long)83L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1973L),Nil);
    add_character_description_1(9,FIX((SI_Long)84L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1904L),Nil);
    add_character_description_1(9,FIX((SI_Long)85L),FIX((SI_Long)6L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)5L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1608L),Nil);
    add_character_description_1(9,FIX((SI_Long)86L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1667L),Nil);
    add_character_description_1(9,FIX((SI_Long)87L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1916L),Nil);
    add_character_description_1(9,FIX((SI_Long)88L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1774L),Nil);
    add_character_description_1(9,FIX((SI_Long)89L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)90L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2239L),Nil);
    add_character_description_1(9,FIX((SI_Long)91L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)92L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)93L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)94L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)95L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)96L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1718L),Nil);
    add_character_description_1(9,FIX((SI_Long)97L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1718L),Nil);
    add_character_description_1(9,FIX((SI_Long)98L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)4L),FIX((SI_Long)4L),
	    FIX((SI_Long)4L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1718L),Nil);
    add_character_description_1(9,FIX((SI_Long)99L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),FIX((SI_Long)5L),FIX((SI_Long)2L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)822L),Nil);
    add_character_description_1(9,FIX((SI_Long)100L),FIX((SI_Long)6L),
	    FIX((SI_Long)1L),FIX((SI_Long)5L),FIX((SI_Long)5L),
	    FIX((SI_Long)3L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1453L),Nil);
    add_character_description_1(9,FIX((SI_Long)101L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)102L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)103L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)104L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1864L),Nil);
    add_character_description_1(9,FIX((SI_Long)105L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)106L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)107L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)108L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)109L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)110L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)111L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)112L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)113L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)114L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)115L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)116L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)117L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)118L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)-66L),FIX((SI_Long)6L),
	    FIX((SI_Long)74L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1961L),Nil);
    add_character_description_1(9,FIX((SI_Long)119L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)-67L),FIX((SI_Long)6L),
	    FIX((SI_Long)75L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1961L),Nil);
    add_character_description_1(9,FIX((SI_Long)120L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1961L),Nil);
    add_character_description_1(9,FIX((SI_Long)121L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1888L),Nil);
    add_character_description_1(9,FIX((SI_Long)122L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1390L),Nil);
    add_character_description_1(9,FIX((SI_Long)123L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1771L),Nil);
    add_character_description_1(9,FIX((SI_Long)124L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2098L),Nil);
    add_character_description_1(9,FIX((SI_Long)125L),FIX((SI_Long)4L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)3L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)999L),Nil);
    add_character_description_1(9,FIX((SI_Long)126L),FIX((SI_Long)6L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1432L),Nil);
    add_character_description_1(9,FIX((SI_Long)127L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)128L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2055L),Nil);
    add_character_description_1(9,FIX((SI_Long)129L),FIX((SI_Long)4L),
	    FIX((SI_Long)0L),FIX((SI_Long)4L),FIX((SI_Long)3L),
	    FIX((SI_Long)4L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)999L),Nil);
    add_character_description_1(9,FIX((SI_Long)130L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1774L),Nil);
    add_character_description_1(9,FIX((SI_Long)131L),FIX((SI_Long)6L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1606L),Nil);
    add_character_description_1(9,FIX((SI_Long)132L),FIX((SI_Long)6L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)5L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1613L),Nil);
    add_character_description_1(9,FIX((SI_Long)133L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)134L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2094L),Nil);
    add_character_description_1(9,FIX((SI_Long)135L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)136L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)3L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1228L),Nil);
    add_character_description_1(9,FIX((SI_Long)137L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2001L),Nil);
    add_character_description_1(9,FIX((SI_Long)138L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)139L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1973L),Nil);
    add_character_description_1(9,FIX((SI_Long)140L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1904L),Nil);
    add_character_description_1(9,FIX((SI_Long)141L),FIX((SI_Long)10L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2613L),Nil);
    add_character_description_1(9,FIX((SI_Long)142L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1667L),Nil);
    add_character_description_1(9,FIX((SI_Long)143L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)-3L),FIX((SI_Long)6L),
	    FIX((SI_Long)11L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1916L),Nil);
    add_character_description_1(9,FIX((SI_Long)144L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1774L),Nil);
    add_character_description_1(9,FIX((SI_Long)145L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)8L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2419L),Nil);
    add_character_description_1(9,FIX((SI_Long)146L),FIX((SI_Long)9L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)8L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2239L),Nil);
    add_character_description_1(9,FIX((SI_Long)147L),FIX((SI_Long)3L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)1L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)859L),Nil);
    add_character_description_1(9,FIX((SI_Long)148L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1888L),Nil);
    add_character_description_1(9,FIX((SI_Long)149L),FIX((SI_Long)6L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)4L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1606L),Nil);
    add_character_description_1(9,FIX((SI_Long)150L),FIX((SI_Long)7L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1904L),Nil);
    add_character_description_1(9,FIX((SI_Long)151L),FIX((SI_Long)8L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)10L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2006L),Nil);
}
