/* hshtbl.h -- Header File for hshtbl.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qhash_table;
extern Object Kinitial_element;
extern Object Qinteger;
extern Object Qsequence;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_for_hash_table(Object);
extern Object add_class_to_environment(int,...);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clear_optimized_constants(void);
extern Object clear_user_hash_table_internal(Object);
extern Object clear_user_hash_table_internal_tree(Object);
extern Object copy_evaluation_value_1(Object);
extern Object deactivate_for_hash_table(Object);
extern Object delete_skip_list_entry(Object,Object,Object,Object,Object);
extern Object deleted_hash_table_entry_p(Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_value_eq(Object,Object);
extern Object flatten_skip_list(Object);
extern Object flatten_user_hash_table(Object);
extern Object flatten_user_hash_table_internal(Object);
extern Object flatten_user_hash_table_into_sequence_of_structures(Object);
extern Object g2_hash_table_clear(Object);
extern Object g2_hash_table_clear_value(Object,Object);
extern Object g2_hash_table_get_value(Object,Object);
extern Object g2_hash_table_reset(Object);
extern Object g2_hash_table_set_value(Object,Object,Object);
extern Object g2_hash_table_to_sequence(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object get_g2_hash_table_number_of_entries(Object);
extern Object get_g2_hash_table_sequence(Object);
extern Object get_key_sl_value_list(Object);
extern Object get_property_value_function(int,...);
extern Object get_reference_to_item(Object);
extern Object get_symbol_properties_function(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object hash_wide_string(Object);
extern Object initial_g2_hash_table_number_of_entries(Object);
extern Object initial_g2_hash_table_sequence(Object);
extern Object initialize_hash_table_from_initial_values_attribute(Object);
extern Object make_permanent_user_hash_table_internal_hash_vector_43_vector_internal(void);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_thread_array(Object);
extern Object make_user_hash_table_internal(void);
extern Object make_user_hash_table_internal_hash_vector(void);
extern Object make_user_hash_table_internal_tree_for_hash_skip_list_sentinel(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_user_hash_table_internal_tree_for_hash_skip_list_entry(Object,Object,Object);
extern Object out_user_hash_table_internal_hash_vector_43_vectors(void);
extern Object push_optimized_constant(Object);
extern Object read_element_for_kb(Object);
extern Object read_hash_table_data(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_internal_hash_table_value(Object,Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_user_hash_table_entry(Object);
extern Object reclaim_user_hash_table_internal(Object);
extern Object reclaim_user_hash_table_internal_hash_vector(Object);
extern Object reclaim_user_hash_table_key(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object set_g2_hash_table_sequence(Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object string_eq_w(Object,Object);
extern Object unsquirrel_hash_table_data(Object,Object);
extern Object unwrap_or_copy_for_user_hash_table(Object);
extern Object update_object_pool_meters_list(Object);
extern Object user_hash_comparitor(Object,Object);
extern Object user_hash_function(Object);
extern Object user_hash_table_gethash(Object,Object);
extern Object user_hash_table_internal_hash_vector_43_vector_memory_usage(void);
extern Object user_hash_table_sethash(Object,Object,Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object wrap_or_copy_for_user_hash_table(Object);
extern Object wrapped_item_p(Object);
extern Object write_char_for_kb(Object);
extern Object write_element_for_kb(Object);
extern Object write_fixnum_for_kb(Object);
extern Object write_hash_table_data_for_kb(Object);

#else

extern Object activate_for_hash_table();
extern Object add_class_to_environment();
extern Object add_virtual_attribute();
extern Object allocate_evaluation_sequence();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object bytes_per_typed_simple_array();
extern Object check_if_superior_classes_are_defined();
extern Object clear_optimized_constants();
extern Object clear_user_hash_table_internal();
extern Object clear_user_hash_table_internal_tree();
extern Object copy_evaluation_value_1();
extern Object deactivate_for_hash_table();
extern Object delete_skip_list_entry();
extern Object deleted_hash_table_entry_p();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object evaluation_value_eq();
extern Object flatten_skip_list();
extern Object flatten_user_hash_table();
extern Object flatten_user_hash_table_internal();
extern Object flatten_user_hash_table_into_sequence_of_structures();
extern Object g2_hash_table_clear();
extern Object g2_hash_table_clear_value();
extern Object g2_hash_table_get_value();
extern Object g2_hash_table_reset();
extern Object g2_hash_table_set_value();
extern Object g2_hash_table_to_sequence();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object get_g2_hash_table_number_of_entries();
extern Object get_g2_hash_table_sequence();
extern Object get_key_sl_value_list();
extern Object get_property_value_function();
extern Object get_reference_to_item();
extern Object get_symbol_properties_function();
extern Object getfq_function_no_default();
extern Object hash_wide_string();
extern Object initial_g2_hash_table_number_of_entries();
extern Object initial_g2_hash_table_sequence();
extern Object initialize_hash_table_from_initial_values_attribute();
extern Object make_permanent_user_hash_table_internal_hash_vector_43_vector_internal();
extern Object make_skip_list_element_1();
extern Object make_thread_array();
extern Object make_user_hash_table_internal();
extern Object make_user_hash_table_internal_hash_vector();
extern Object make_user_hash_table_internal_tree_for_hash_skip_list_sentinel();
extern Object mutate_global_property();
extern Object mutate_user_hash_table_internal_tree_for_hash_skip_list_entry();
extern Object out_user_hash_table_internal_hash_vector_43_vectors();
extern Object push_optimized_constant();
extern Object read_element_for_kb();
extern Object read_hash_table_data();
extern Object reclaim_eval_list_1();
extern Object reclaim_evaluation_value();
extern Object reclaim_gensym_list_1();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_internal_hash_table_value();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_user_hash_table_entry();
extern Object reclaim_user_hash_table_internal();
extern Object reclaim_user_hash_table_internal_hash_vector();
extern Object reclaim_user_hash_table_key();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_lookup_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object set_g2_hash_table_sequence();
extern Object set_property_value_function();
extern Object set_skip_list_entry();
extern Object slot_value_cons_1();
extern Object string_eq_w();
extern Object unsquirrel_hash_table_data();
extern Object unwrap_or_copy_for_user_hash_table();
extern Object update_object_pool_meters_list();
extern Object user_hash_comparitor();
extern Object user_hash_function();
extern Object user_hash_table_gethash();
extern Object user_hash_table_internal_hash_vector_43_vector_memory_usage();
extern Object user_hash_table_sethash();
extern Object validate_item_or_evaluation_value();
extern Object wrap_or_copy_for_user_hash_table();
extern Object wrapped_item_p();
extern Object write_char_for_kb();
extern Object write_element_for_kb();
extern Object write_fixnum_for_kb();
extern Object write_hash_table_data_for_kb();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_user_hash_table_internal_hash_vector_43_vectors, Qavailable_user_hash_table_internal_hash_vector_43_vectors);
extern Object Available_user_hash_table_internal_hash_vector_43_vectors_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_user_hash_table_internal_hash_vector_43_vectors, Qcount_of_user_hash_table_internal_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
extern Object Fp_mutate_user_hash_table_internal_tree_for_hash_skip_list_entry;
DECLARE_VARIABLE_WITH_SYMBOL(Left_braket_written_qm, Qleft_braket_written_qm);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Stand_in_marker;
