/* java2.h -- Header File for java2.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qplus;
extern Object Qminus;
extern Object Qslash;
extern Object Qnum_ne;
extern Object Qnum_lt;
extern Object Qnum_le;
extern Object Qnum_eq;
extern Object Qnum_gt;
extern Object Qnum_ge;
extern Object Qbreak;
extern Object Qbyte;
extern Object Qcase;
extern Object Qchar;
extern Object Qdo;
extern Object Qfloat;
extern Object Qimport;
extern Object Qinteger;
extern Object Qpackage_type;
extern Object Qquote;
extern Object Qreturn;
extern Object Qsequence;
extern Object Qstring;
extern Object Ktest;
extern Object Qthrow;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_grammar_rules_function(Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object caret_position_in_javac_problem_line_if_any(Object);
extern Object change_slot_value(int,...);
extern Object character_class_difference(Object,Object);
extern Object clear_optimized_constants(void);
extern Object compile_java_compilation_unit_or_none_for_slot(int,...);
extern Object compile_permanent_lexing_table(Object);
extern Object convert_java_separators_or_operators_to_seq_tokens(Object);
extern Object convert_java_separators_or_operators_to_symbols(Object);
extern Object convert_mixed_case_text_to_hyphenated_symbol(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_as_wide_string(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_out_current_gensym_string(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_symbol_name(int,...);
extern Object copy_symbol_name_of_possible_java_reserved_word(Object,Object);
extern Object copy_symbol_name_parsably(Object,Object);
extern Object copy_text_string(Object);
extern Object copy_wide_string(Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object extend_current_gensym_string(int,...);
extern Object gensym_search_simple(Object,Object);
extern Object get_canonical_java_name_as_new_slot_value(Object);
extern Object get_class_name_symbols_for_external_java_class(Object);
extern Object get_current_evaluation_value(Object,Object);
extern Object get_import_declarations_if_any(Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_next_javac_problem_if_any(Object,Object);
extern Object get_package_declaration_components_if_any(Object);
extern Object get_symbol_properties_function(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object instantiable_secret_java_class_p(Object);
extern Object intern_for_java_grammar(Object);
extern Object intern_java_reserved_word_as_category(Object);
extern Object intern_text_string(int,...);
extern Object java_cons_1(Object,Object);
extern Object java_editing_category_p(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lower_case_alpha_char_pw(Object);
extern Object lower_case_pw(Object);
extern Object make_character_range_from_sorted_list_of_character_codes(Object);
extern Object make_empty_text(void);
extern Object make_g2_name_for_java_class(Object,Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object newline_text_string_character_p(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_text_category_evaluator_interface(Object);
extern Object notify_user(int,...);
extern Object obtain_simple_gensym_string(Object);
extern Object operate_on_javac_frame_notes(Object,Object,Object);
extern Object parse_text_string(int,...);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_3(Object,Object,Object);
extern Object preserve_information_from_former_java_text_slot(Object,Object);
extern Object probable_text_p(Object);
extern Object problem_header_in_javac_problem_p(Object);
extern Object push_optimized_constant(Object);
extern Object put_compilation_unit(Object,Object,Object);
extern Object put_import_declarations(Object,Object,Object);
extern Object put_package_declaration(Object,Object,Object);
extern Object put_type_declarations_where_slot_is_absent(Object,Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_java_list_1(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_text(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_token_cons_1(Object);
extern Object reclaim_token_list_1(Object);
extern Object regenerate_optimized_constant(Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_grammar_transform_can_return_bad_phrase_p(Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object set_token_menu_string_to_display_for_java_reserved_words(void);
extern Object set_token_menu_string_to_display_function(Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object symbol_name_text_string(Object);
extern Object text_category_slot_access_committer(Object,Object,Object);
extern Object text_category_slot_access_extracter(Object,Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object text_string_substring(Object,Object,Object);
extern Object tformat(int,...);
extern Object token_cons_1(Object,Object);
extern Object token_list_2(Object,Object);
extern Object tokenize_bad_java_character_literal(Object,Object,Object);
extern Object tokenize_java_character_literal(Object,Object,Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_character(Object);
extern Object twrite_general_string(Object);
extern Object twrite_java_qualified_name(Object);
extern Object twrite_line_break(void);
extern Object twrite_list_function(Object,Object,Object,Object,Object);
extern Object twrite_symbol(int,...);
extern Object twrite_wide_character(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object unicode_uppercase_if_lowercase(Object);
extern Object unreserved_java_identifier_qm(Object,Object);
extern Object update_g2_side_names_for_external_java_class(Object,Object,Object);
extern Object update_import_declarations_for_external_java_class(Object,Object);
extern Object update_java_side_names_for_external_java_class(Object,Object,Object);
extern Object update_names_for_external_java_class(Object,Object,Object);
extern Object update_package_declaration_for_external_java_class(Object,Object);
extern Object upper_case_alpha_char_pw(Object);
extern Object whitespace_text_string_character_p(Object);
extern Object write_java_class_and_interface_names_from_slot(Object,Object);
extern Object write_java_read_only_import_declarations_from_slot(Object,Object);
extern Object write_java_read_only_package_declaration_from_slot(Object,Object);

#else

extern Object add_grammar_rules_function();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object caret_position_in_javac_problem_line_if_any();
extern Object change_slot_value();
extern Object character_class_difference();
extern Object clear_optimized_constants();
extern Object compile_java_compilation_unit_or_none_for_slot();
extern Object compile_permanent_lexing_table();
extern Object convert_java_separators_or_operators_to_seq_tokens();
extern Object convert_java_separators_or_operators_to_symbols();
extern Object convert_mixed_case_text_to_hyphenated_symbol();
extern Object convert_text_to_text_string();
extern Object copy_as_wide_string();
extern Object copy_constant_wide_string_given_length();
extern Object copy_out_current_gensym_string();
extern Object copy_out_current_wide_string();
extern Object copy_symbol_name();
extern Object copy_symbol_name_of_possible_java_reserved_word();
extern Object copy_symbol_name_parsably();
extern Object copy_text_string();
extern Object copy_wide_string();
extern Object define_type_specification_explicit_complex_type();
extern Object delete_frame_note_if_any();
extern Object eval_cons_1();
extern Object extend_current_gensym_string();
extern Object gensym_search_simple();
extern Object get_canonical_java_name_as_new_slot_value();
extern Object get_class_name_symbols_for_external_java_class();
extern Object get_current_evaluation_value();
extern Object get_import_declarations_if_any();
extern Object get_instance_with_name_if_any();
extern Object get_next_javac_problem_if_any();
extern Object get_package_declaration_components_if_any();
extern Object get_symbol_properties_function();
extern Object getfq_function_no_default();
extern Object instantiable_secret_java_class_p();
extern Object intern_for_java_grammar();
extern Object intern_java_reserved_word_as_category();
extern Object intern_text_string();
extern Object java_cons_1();
extern Object java_editing_category_p();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lower_case_alpha_char_pw();
extern Object lower_case_pw();
extern Object make_character_range_from_sorted_list_of_character_codes();
extern Object make_empty_text();
extern Object make_g2_name_for_java_class();
extern Object memq_function();
extern Object mutate_global_property();
extern Object newline_text_string_character_p();
extern Object note_change_to_block_1();
extern Object note_text_category_evaluator_interface();
extern Object notify_user();
extern Object obtain_simple_gensym_string();
extern Object operate_on_javac_frame_notes();
extern Object parse_text_string();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object phrase_list_3();
extern Object preserve_information_from_former_java_text_slot();
extern Object probable_text_p();
extern Object problem_header_in_javac_problem_p();
extern Object push_optimized_constant();
extern Object put_compilation_unit();
extern Object put_import_declarations();
extern Object put_package_declaration();
extern Object put_type_declarations_where_slot_is_absent();
extern Object reclaim_evaluation_value();
extern Object reclaim_java_list_1();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_text();
extern Object reclaim_text_string();
extern Object reclaim_token_cons_1();
extern Object reclaim_token_list_1();
extern Object regenerate_optimized_constant();
extern Object set_evaluation_value_to_category_function();
extern Object set_grammar_transform_can_return_bad_phrase_p();
extern Object set_property_value_function();
extern Object set_slot_value_to_evaluation_value_function();
extern Object set_token_menu_string_to_display_for_java_reserved_words();
extern Object set_token_menu_string_to_display_function();
extern Object slot_value_cons_1();
extern Object symbol_name_text_string();
extern Object text_category_slot_access_committer();
extern Object text_category_slot_access_extracter();
extern Object text_string_length();
extern Object text_string_p();
extern Object text_string_substring();
extern Object tformat();
extern Object token_cons_1();
extern Object token_list_2();
extern Object tokenize_bad_java_character_literal();
extern Object tokenize_java_character_literal();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_character();
extern Object twrite_general_string();
extern Object twrite_java_qualified_name();
extern Object twrite_line_break();
extern Object twrite_list_function();
extern Object twrite_symbol();
extern Object twrite_wide_character();
extern Object type_error_in_setter();
extern Object type_specification_type_p__with_explanation();
extern Object unicode_uppercase_if_lowercase();
extern Object unreserved_java_identifier_qm();
extern Object update_g2_side_names_for_external_java_class();
extern Object update_import_declarations_for_external_java_class();
extern Object update_java_side_names_for_external_java_class();
extern Object update_names_for_external_java_class();
extern Object update_package_declaration_for_external_java_class();
extern Object upper_case_alpha_char_pw();
extern Object whitespace_text_string_character_p();
extern Object write_java_class_and_interface_names_from_slot();
extern Object write_java_read_only_import_declarations_from_slot();
extern Object write_java_read_only_package_declaration_from_slot();

#endif

/* variables/constants */
extern Object Alphabet_nonsymbol_character_codes_sorted_by_encoding;
extern Object Available_java_conses_tail_vector;
extern Object Available_java_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
extern Object Bad_phrase;
extern Object Caret_replacement_for_javac_problem;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index, Qframe_note_index);
DECLARE_VARIABLE_WITH_SYMBOL(Java_editing_categories, Qjava_editing_categories);
extern Object Java_escape_character_literal_alist;
DECLARE_VARIABLE_WITH_SYMBOL(Java_grammar_stream_qm, Qjava_grammar_stream_qm);
extern Object Java_half_octal_characters;
extern Object Java_identifier_part_character_class;
extern Object Java_identifier_quote_free_part_character_class;
extern Object Java_identifier_quote_free_start_character_class;
extern Object Java_identifier_start_character_class;
extern Object Java_multi_character_operators_as_conglomerated_string;
extern Object Java_octal_character_literal_alist;
extern Object Java_operators_as_categories;
extern Object Java_reserved_expressions_as_lowercase_categories;
extern Object Java_reserved_expressions_as_string;
extern Object Java_reserved_word_p_prop;
extern Object Java_reserved_words_as_lowercase_categories;
extern Object Java_reserved_words_as_string;
extern Object Java_reserved_words_as_uppercase_symbols;
extern Object Java_separators_as_categories;
extern Object Java_separators_as_conglomerated_string;
extern Object Java_single_character_constituent_operators_as_string;
extern Object Java_single_character_nonconstituent_operators_as_string;
extern Object Java_single_character_operators_as_conglomerated_string;
DECLARE_VARIABLE_WITH_SYMBOL(Java_tokenizer, Qjava_tokenizer);
extern Object Java_tokens;
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
extern Object Must_quote_g2_symbol_character_class;
extern Object Newline_chars_for_java_tokens;
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Text_parameter_class_description, Qtext_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
extern Object Unicode_digit_possibly_undefined_character_class;
extern Object Unicode_letter_or_digit_possibly_undefined_character_class;
DECLARE_VARIABLE_WITH_SYMBOL(Valid_token_actions, Qvalid_token_actions);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
