/* java3.h -- Header File for java3.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qerror;
extern Object Qfloat;
extern Object Qinteger;
extern Object Qlist;
extern Object Qnumber;
extern Object Qpackage_type;
extern Object Qsequence;
extern Object Qsubstitute;
extern Object Qsymbol;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_class_export_info_attributes(Object,Object);
extern Object add_newborn_external_static_methods_as_appropriate(Object,Object);
extern Object add_or_delete_as_item_referring_to_name(Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object analyze_export_info_for_parsability(Object,Object);
extern Object analyze_export_methods_for_parsability(Object,Object);
extern Object analyze_export_procedures_for_parsability(Object,Object);
extern Object analyze_exported_executable_for_parsability(Object,Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object bytes_per_simple_vector(Object);
extern Object chase_signaled_class_if_any(Object,Object);
extern Object check_exported_classes(Object,Object);
extern Object check_external_instance_method_info(Object);
extern Object check_external_static_method_info(Object);
extern Object check_external_static_methods(Object,Object,Object);
extern Object clear_optimized_constants(void);
extern Object clear_problem_mapping_g2_to_java_source_particulars(Object,Object);
extern Object clear_unexportable_external_method_frame_note(Object,Object);
extern Object collect_classes_signaled_in_procedure(Object);
extern Object collect_export_info_for_all_classes(Object);
extern Object collect_instance_method_export_info(int,...);
extern Object collect_static_method_export_info(Object,Object);
extern Object collect_subclasses(Object);
extern Object collect_types_into_list_using_gensym_conses(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_gensym_string(Object);
extern Object copy_list_using_slot_value_conses_1(Object);
extern Object copy_out_current_gensym_string(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_text(Object);
extern Object copy_text_string_without_newlines(Object,Object);
extern Object copy_tree_using_slot_value_conses_1(Object);
extern Object decache_implicit_external_instance_method_info_if_any(Object);
extern Object delete_export_frame_if_any(Object);
extern Object delete_frame(Object);
extern Object delete_from_frame_note_particulars_list(Object,Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object ensured_look_up_listed_syntax_tree_binding(Object,Object,Object,Object);
extern Object equalw(Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object eval_list_2(Object,Object);
extern Object expand_comma_series_in_syntax_template_line(Object,Object,Object,Object);
extern Object expand_optional_syntax_tree_lines(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object expand_replicated_syntax_subtree(Object,Object,Object,Object,Object);
extern Object expand_splicable_syntax_template_line(Object,Object,Object,Object,Object);
extern Object expand_syntax_template_given_bindings(Object,Object,Object);
extern Object expand_syntax_template_line(Object,Object,Object,Object);
extern Object expand_syntax_template_within_output_to_java_source_file(Object,Object,Object);
extern Object export_types_in_arguments_or_results_as_sequence(Object);
extern Object extend_current_gensym_string(int,...);
extern Object external_class_info_structure_memory_usage(void);
extern Object external_method_info_structure_memory_usage(void);
extern Object g2_add_class_export_info_attributes(Object);
extern Object g2_stream_close(Object);
extern Object g2_stream_open_for_output(Object);
extern Object g2_switch_fix_for_exported_method_overloading(Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_current_sexp_annotation_hash(void);
extern Object get_evaluation_sequence_from_external_method_info_list(Object);
extern Object get_evaluation_structure_for_one_external_method(Object,Object);
extern Object get_export_definition_and_info_for_class_if_any(Object);
extern Object get_exported_source_for_class_if_possible(Object,Object,Object);
extern Object get_exported_static_methods_if_any(Object,Object);
extern Object get_external_class_specific_methods(Object);
extern Object get_external_instance_method_info_for_class(Object);
extern Object get_external_static_method_info_for_class(Object);
extern Object get_hand_coded_methods_for_class_if_any(Object);
extern Object get_implicit_export_definition_and_info_for_class_if_possible(Object);
extern Object get_instance_or_instances_with_name_if_any(Object,Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_matching_g2_procedure_if_any(Object,Object);
extern Object get_particulars_of_frame_note_from_component_particulars(Object,Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object get_text_conversion_style_structure_per_name(Object);
extern Object get_text_of_attribute(Object,Object,Object);
extern Object get_user_visible_export_definition_and_info_for_class_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object intern_text_string(int,...);
extern Object java_cons_1(Object,Object);
extern Object jemit_class_to_stream(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object joutput_line(Object,Object);
extern Object last_listed_syntax_tree_binding_p(Object,Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object look_up_atomic_syntax_tree_binding(Object,Object);
extern Object look_up_atomic_syntax_tree_binding_if_any(Object,Object);
extern Object look_up_listed_syntax_tree_binding(Object,Object,Object,Object);
extern Object look_up_number_of_listed_bindings(Object,Object);
extern Object look_up_raw_syntax_tree_binding(Object,Object);
extern Object look_up_typical_replicated_binding_if_any(int,...);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_edit_state_1(void);
extern Object make_export_info_for_one_class(Object,Object);
extern Object make_external_class_info_1(Object,Object,Object);
extern Object make_external_method_info(Object,Object,Object,Object,Object,Object);
extern Object make_external_method_info_for_g2_method(Object,Object,Object,Object);
extern Object make_external_method_info_internal_1(Object,Object,Object,Object,Object,Object);
extern Object make_frame(Object);
extern Object make_implicit_export_definition_and_class_info(Object);
extern Object make_listed_external_method_info_if_valid(Object,Object,Object,Object,Object,Object);
extern Object make_permanent_external_class_info_structure_internal(void);
extern Object make_permanent_external_method_info_structure_internal(void);
extern Object make_sexp_annotation_hash(void);
extern Object make_thread_array(Object);
extern Object matching_instance_method_info_p(Object,Object);
extern Object maybe_get_more_external_instance_methods_for_class(Object,Object,Object);
extern Object memq_function(Object,Object);
extern Object multi_line_syntax_template_p(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object new_shared_check_external_method_info(Object,Object);
extern Object new_update_external_instance_method_info(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object nstring_downcasew(Object);
extern Object nstring_downcasew_outside_double_quotes(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object old_analyze_export_methods_for_parsability(Object,Object);
extern Object old_maybe_get_more_external_instance_methods_for_class(Object,Object,Object);
extern Object old_shared_check_external_method_info(Object,Object);
extern Object old_update_external_instance_method_info(Object,Object,Object);
extern Object old_update_instance_methods_attribute(Object);
extern Object outstanding_external_class_info_count(void);
extern Object outstanding_external_method_info_count(void);
extern Object parse_text_for_slot(int,...);
extern Object parse_text_string(int,...);
extern Object pop_listed_syntax_tree_binding_layer(Object,Object);
extern Object push_new_syntax_tree_template_entry(Object,Object);
extern Object push_optimized_constant(Object);
extern Object reclaim_class_export_information_if_any(Object);
extern Object reclaim_edit_state_1(Object);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_external_class_info_1(Object);
extern Object reclaim_external_class_info_list(Object);
extern Object reclaim_external_method_info_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_java_list_1(Object);
extern Object reclaim_list_of_external_methods(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_text_or_gensym_string_if_any(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_wide_string(Object);
extern Object reconcile_exported_classes(Object,Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_installation_cons_pool(void);
extern Object restore_listed_bindings(Object);
extern Object retain_listed_bindings(Object);
extern Object same_definition_text_p(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object shared_check_external_method_info(Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object symbol_name_text_string(Object);
extern Object tformat(int,...);
extern Object try_to_parse_external_method_definition(Object,Object,Object,Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_fixnum(Object);
extern Object twrite_general_string(Object);
extern Object twrite_line_separator(void);
extern Object twrite_syntax_tree_binding_if_found(Object,Object,Object);
extern Object twrite_wide_character(Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object update_all_external_method_info(Object);
extern Object update_external_instance_method_info(Object,Object,Object);
extern Object update_external_method_info(Object,Object,Object);
extern Object update_external_static_method_info(Object,Object,Object,Object);
extern Object update_instance_methods_attribute(Object);
extern Object update_mapping_problem_frame_notes_if_necessary(Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_unexportable_external_method_frame_note_if_appropriate(Object,Object);
extern Object walk_for_signaled_designations(Object,Object);

#else

extern Object add_class_export_info_attributes();
extern Object add_newborn_external_static_methods_as_appropriate();
extern Object add_or_delete_as_item_referring_to_name();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object analyze_export_info_for_parsability();
extern Object analyze_export_methods_for_parsability();
extern Object analyze_export_procedures_for_parsability();
extern Object analyze_exported_executable_for_parsability();
extern Object assq_function();
extern Object bytes_per_simple_vector();
extern Object chase_signaled_class_if_any();
extern Object check_exported_classes();
extern Object check_external_instance_method_info();
extern Object check_external_static_method_info();
extern Object check_external_static_methods();
extern Object clear_optimized_constants();
extern Object clear_problem_mapping_g2_to_java_source_particulars();
extern Object clear_unexportable_external_method_frame_note();
extern Object collect_classes_signaled_in_procedure();
extern Object collect_export_info_for_all_classes();
extern Object collect_instance_method_export_info();
extern Object collect_static_method_export_info();
extern Object collect_subclasses();
extern Object collect_types_into_list_using_gensym_conses();
extern Object convert_text_to_text_string();
extern Object copy_gensym_string();
extern Object copy_list_using_slot_value_conses_1();
extern Object copy_out_current_gensym_string();
extern Object copy_out_current_wide_string();
extern Object copy_text();
extern Object copy_text_string_without_newlines();
extern Object copy_tree_using_slot_value_conses_1();
extern Object decache_implicit_external_instance_method_info_if_any();
extern Object delete_export_frame_if_any();
extern Object delete_frame();
extern Object delete_from_frame_note_particulars_list();
extern Object direct_structure_method();
extern Object ensured_look_up_listed_syntax_tree_binding();
extern Object equalw();
extern Object eval_cons_1();
extern Object eval_list_2();
extern Object expand_comma_series_in_syntax_template_line();
extern Object expand_optional_syntax_tree_lines();
extern Object expand_replicated_syntax_subtree();
extern Object expand_splicable_syntax_template_line();
extern Object expand_syntax_template_given_bindings();
extern Object expand_syntax_template_line();
extern Object expand_syntax_template_within_output_to_java_source_file();
extern Object export_types_in_arguments_or_results_as_sequence();
extern Object extend_current_gensym_string();
extern Object external_class_info_structure_memory_usage();
extern Object external_method_info_structure_memory_usage();
extern Object g2_add_class_export_info_attributes();
extern Object g2_stream_close();
extern Object g2_stream_open_for_output();
extern Object g2_switch_fix_for_exported_method_overloading();
extern Object gensym_cons_1();
extern Object get_current_sexp_annotation_hash();
extern Object get_evaluation_sequence_from_external_method_info_list();
extern Object get_evaluation_structure_for_one_external_method();
extern Object get_export_definition_and_info_for_class_if_any();
extern Object get_exported_source_for_class_if_possible();
extern Object get_exported_static_methods_if_any();
extern Object get_external_class_specific_methods();
extern Object get_external_instance_method_info_for_class();
extern Object get_external_static_method_info_for_class();
extern Object get_hand_coded_methods_for_class_if_any();
extern Object get_implicit_export_definition_and_info_for_class_if_possible();
extern Object get_instance_or_instances_with_name_if_any();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value_given_default();
extern Object get_matching_g2_procedure_if_any();
extern Object get_particulars_of_frame_note_from_component_particulars();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_if_any_function();
extern Object get_text_conversion_style_structure_per_name();
extern Object get_text_of_attribute();
extern Object get_user_visible_export_definition_and_info_for_class_if_any();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object intern_text_string();
extern Object java_cons_1();
extern Object jemit_class_to_stream();
extern Object joutput_line();
extern Object last_listed_syntax_tree_binding_p();
extern Object load_and_initialize_type_description();
extern Object look_up_atomic_syntax_tree_binding();
extern Object look_up_atomic_syntax_tree_binding_if_any();
extern Object look_up_listed_syntax_tree_binding();
extern Object look_up_number_of_listed_bindings();
extern Object look_up_raw_syntax_tree_binding();
extern Object look_up_typical_replicated_binding_if_any();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_edit_state_1();
extern Object make_export_info_for_one_class();
extern Object make_external_class_info_1();
extern Object make_external_method_info();
extern Object make_external_method_info_for_g2_method();
extern Object make_external_method_info_internal_1();
extern Object make_frame();
extern Object make_implicit_export_definition_and_class_info();
extern Object make_listed_external_method_info_if_valid();
extern Object make_permanent_external_class_info_structure_internal();
extern Object make_permanent_external_method_info_structure_internal();
extern Object make_sexp_annotation_hash();
extern Object make_thread_array();
extern Object matching_instance_method_info_p();
extern Object maybe_get_more_external_instance_methods_for_class();
extern Object memq_function();
extern Object multi_line_syntax_template_p();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object new_shared_check_external_method_info();
extern Object new_update_external_instance_method_info();
extern Object note_change_to_block_1();
extern Object nstring_downcasew();
extern Object nstring_downcasew_outside_double_quotes();
extern Object obtain_simple_gensym_string();
extern Object old_analyze_export_methods_for_parsability();
extern Object old_maybe_get_more_external_instance_methods_for_class();
extern Object old_shared_check_external_method_info();
extern Object old_update_external_instance_method_info();
extern Object old_update_instance_methods_attribute();
extern Object outstanding_external_class_info_count();
extern Object outstanding_external_method_info_count();
extern Object parse_text_for_slot();
extern Object parse_text_string();
extern Object pop_listed_syntax_tree_binding_layer();
extern Object push_new_syntax_tree_template_entry();
extern Object push_optimized_constant();
extern Object reclaim_class_export_information_if_any();
extern Object reclaim_edit_state_1();
extern Object reclaim_eval_cons_1();
extern Object reclaim_external_class_info_1();
extern Object reclaim_external_class_info_list();
extern Object reclaim_external_method_info_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_string();
extern Object reclaim_java_list_1();
extern Object reclaim_list_of_external_methods();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_text_or_gensym_string_if_any();
extern Object reclaim_text_string();
extern Object reclaim_wide_string();
extern Object reconcile_exported_classes();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_installation_cons_pool();
extern Object restore_listed_bindings();
extern Object retain_listed_bindings();
extern Object same_definition_text_p();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object shared_check_external_method_info();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object slot_value_list_4();
extern Object symbol_name_text_string();
extern Object tformat();
extern Object try_to_parse_external_method_definition();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_fixnum();
extern Object twrite_general_string();
extern Object twrite_line_separator();
extern Object twrite_syntax_tree_binding_if_found();
extern Object twrite_wide_character();
extern Object unicode_lowercase_if_uppercase();
extern Object update_all_external_method_info();
extern Object update_external_instance_method_info();
extern Object update_external_method_info();
extern Object update_external_static_method_info();
extern Object update_instance_methods_attribute();
extern Object update_mapping_problem_frame_notes_if_necessary();
extern Object update_object_pool_meters_list();
extern Object update_unexportable_external_method_frame_note_if_appropriate();
extern Object walk_for_signaled_designations();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Add_as_item_referring_to_name_qm, Qadd_as_item_referring_to_name_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Analyzing_export_definition_for_consistency_p, Qanalyzing_export_definition_for_consistency_p);
extern Object Available_installation_conses_tail_vector;
extern Object Available_installation_conses_vector;
extern Object Available_java_conses_tail_vector;
extern Object Available_java_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Bypass_add_class_export_info_attributes_p, Qbypass_add_class_export_info_attributes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Bypass_fix_for_exported_method_overloading_p, Qbypass_fix_for_exported_method_overloading_p);
extern Object Cache_implicit_class_export_info_p;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_external_class_infos, Qchain_of_available_external_class_infos);
extern Object Chain_of_available_external_class_infos_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_external_method_infos, Qchain_of_available_external_method_infos);
extern Object Chain_of_available_external_method_infos_vector;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Class_info_attributes, Qclass_info_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Collected_frame_notes_for_class_export_qm, Qcollected_frame_notes_for_class_export_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_exported_method_text_p, Qcollecting_exported_method_text_p);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_frame_notes_for_class_export_p, Qcollecting_frame_notes_for_class_export_p);
extern Object Compiled_items_referring_to_this_name_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_jemit_text_style_qm, Qcurrent_jemit_text_style_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_rpc_icp_socket_qm, Qcurrent_system_rpc_icp_socket_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Delete_as_item_referring_to_name_qm, Qdelete_as_item_referring_to_name_qm);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(External_class_info_count, Qexternal_class_info_count);
DECLARE_VARIABLE_WITH_SYMBOL(External_method_info_count, Qexternal_method_info_count);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index, Qframe_note_index);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_note_index_skip, Qframe_note_index_skip);
extern Object Frame_or_frames_with_this_name_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Generate_source_annotation_info, Qgenerate_source_annotation_info);
DECLARE_VARIABLE_WITH_SYMBOL(Global_output_stream_for_expand_syntax_template, Qglobal_output_stream_for_expand_syntax_template);
DECLARE_VARIABLE_WITH_SYMBOL(Inference_engine_parameters, Qinference_engine_parameters);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Language_parameters, Qlanguage_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_exported_method_texts, Qlist_of_exported_method_texts);
DECLARE_VARIABLE_WITH_SYMBOL(Method_class_description, Qmethod_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
extern Object Syntax_tree_no_binding_tag;
extern Object Syntax_tree_template_registry;
extern Object The_type_description_of_external_class_info;
extern Object The_type_description_of_external_method_info;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
