/* kbld2.h -- Header File for kbld2.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qblock;
extern Object Qdelete;
extern Object Kend;
extern Object Qeq;
extern Object Qmake_string;
extern Object Qsequence;
extern Object Ktest;
extern Object Qunsigned_byte;
extern Object Qvariable;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_g2(int,...);
extern Object abort_on_bad_kb(int,...);
extern Object activate_roots_of_kb_hierarchy_just_read_in(Object,Object);
extern Object add_new_byte_code_body(Object);
extern Object add_new_compiled_byte_code_body(Object);
extern Object add_recent_loaded_kb(Object);
extern Object add_to_relation(Object,Object,Object,Object,Object,Object);
extern Object adjust_direct_superiors_per_class_conflicts(Object);
extern Object aggregate_evaluation_value_p(Object);
extern Object allocate_byte_vector(Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_float_array(int,...);
extern Object allocate_managed_long_box(void);
extern Object allocate_managed_simple_vector(Object);
extern Object allocate_sparse_array_1(void);
extern Object always_instantiate_connection_frame_for_this_class_qm(Object);
extern Object analyze_compiled_items_after_loading(void);
extern Object analyze_compiled_items_after_loading_1(void);
extern Object aref_sparse_array(Object,Object);
extern Object aset_sparse_array(Object,Object,Object);
extern Object assemble_uncached_compound_method_flags(Object,Object,Object,Object);
extern Object assign_index_in_index_space(Object);
extern Object assq_function(Object,Object);
extern Object assure_all_charts_are_modern_1(void);
extern Object assure_all_charts_have_style(void);
extern Object blinking_area_p(Object);
extern Object block_needs_activation_upon_reading_p(Object);
extern Object block_relation_instances_violate_class_type_p(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object center_workspace_background_images(void);
extern Object center_workspace_background_images_after_loading(void);
extern Object change_all_permanently_changed_things_are_marked(Object);
extern Object change_slot_value(int,...);
extern Object change_text_cell_property(Object,Object,Object);
extern Object check_for_table_representing_recycled_definition(Object);
extern Object check_ignore_snap_grid_in_transfer_operations(void);
extern Object check_inconsistent_behavior_of_move_in_configurations(void);
extern Object check_insert_action_duplicate_element_flag(void);
extern Object check_new_get_connection_vertex_behavior_flag(void);
extern Object check_print_means_print_to_server_in_configurations(void);
extern Object check_slash_extension_for_character_sequence(Object);
extern Object chestnut_modf_function(Object,Object);
extern Object classic_kbs_prefer_classic_editor(void);
extern Object classic_kbs_prefer_classic_selection_highlighting(void);
extern Object classic_kbs_prefer_classic_ui_features(void);
extern Object clean_up_orphan_frame_representations(void);
extern Object cleanup_for_block(Object);
extern Object cleanup_g2_cell_array(Object);
extern Object clear_kb(int,...);
extern Object clockwise_polygon_p(Object);
extern Object collect_leaf_vectors(Object,Object);
extern Object collect_subclasses(Object);
extern Object collect_unreprocessed_items(Object);
extern Object collect_warning(Object,Object);
extern Object color_or_metacolor_p(Object);
extern Object compiled_kb_initialization_argument(void);
extern Object complete_definition_p(Object);
extern Object constant_queue_next(Object,Object);
extern Object continue_read_kb(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object convert_alist_to_plist(Object);
extern Object convert_description_list_to_managed_array(int,...);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_illegal_gensym_string_without_bad_characters(Object);
extern Object copy_list_of_relation_instances(Object);
extern Object copy_managed_float(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_unsaved_slots_from_connection_to_connection_frame(Object,Object);
extern Object count_and_fix_invalid_items(void);
extern Object deal_with_class_name_conflicts(Object,Object);
extern Object deal_with_junction_block_class_differences(Object,Object,Object);
extern Object defer_class_definition(Object,Object);
extern Object definition_class_is_subclass_of_obj_conn_mess_definition_p(Object);
extern Object delete_all_frame_notes_for_component_particular(Object,Object);
extern Object delete_all_title_block_workspaces(void);
extern Object delete_bad_connection_structures(void);
extern Object delete_block_after_reading_kb(Object);
extern Object delete_block_after_unsquirreling(Object);
extern Object delete_blocks_and_connections_to_be_deleted_after_reading(void);
extern Object delete_connection(int,...);
extern Object delete_connection_after_reading_kb(Object);
extern Object delete_connection_frames_without_connection_structures(void);
extern Object delete_connection_in_block(Object,Object,Object);
extern Object delete_frame(Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_skip_list_entry(Object,Object,Object,Object,Object);
extern Object delete_slot_value_element_1(Object,Object);
extern Object delete_type_violating_relation_instances(void);
extern Object delete_type_violating_relation_instances_1(Object);
extern Object direct_superiors_are_defined_p(Object);
extern Object do_one_post_loading_function(Object,Object);
extern Object do_post_loading_functions(Object);
extern Object eliminate_procedure_invocation_frame_notes(void);
extern Object empty_layer_in_icon_description_p(Object);
extern Object enlarge_index_space(Object,Object);
extern Object ensure_connections_have_frames_if_necessary(void);
extern Object enter_frame_into_frame_serial_number_map(Object,Object);
extern Object enter_old_things_into_map(void);
extern Object eq_gethash(Object,Object,Object);
extern Object eq_puthash(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_value_value(Object);
extern Object export_text_string(int,...);
extern Object extend_current_gensym_string(int,...);
extern Object find_differences_in_frames_if_any(int,...);
extern Object find_existing_equivalent_format_frame(Object);
extern Object find_frame_for_denotation(int,...);
extern Object find_similar_class_name(Object);
extern Object find_similar_slot_name(Object,Object);
extern Object finish_reading_format_frame_for_kb(Object,Object);
extern Object finish_reading_into_managed_array_for_kb(Object,Object);
extern Object finish_reading_into_managed_float_array_for_kb(Object,Object);
extern Object finish_reading_managed_array_for_kb(Object);
extern Object finish_reading_managed_float_array_for_kb(Object);
extern Object finish_reading_slot_value_float(Object,Object,Object);
extern Object fix_capabilities_of_old_kbs(void);
extern Object fix_icon_description_for_class_slot(Object,Object,Object,Object,Object);
extern Object fix_icon_variables_alists_in_icon_attributes_plist(void);
extern Object fix_kb_workspaces_that_might_be_too_big(void);
extern Object fix_line_drawing_description_for_class(Object,Object);
extern Object fix_module_related_frame_notes_after_loading(void);
extern Object fix_possible_non_symbols_in_g2_user_mode(void);
extern Object fix_subworkspace_names(void);
extern Object fix_unimplemented_definitions(void);
extern Object fix_up_configuration_attribute_error(Object,Object,Object);
extern Object fix_up_default_overrides_for_5_0(Object);
extern Object fix_up_double_click_configuration_clauses(Object);
extern Object fixnum_time_difference_in_seconds(Object,Object);
extern Object fixup_all_author_or_authors(void);
extern Object fixup_all_digital_clocks(void);
extern Object fixup_author_or_authors_value(Object);
extern Object fixup_icon_description_for_class(Object,Object,Object);
extern Object force_process_drawing(void);
extern Object frame_cons_1(Object,Object);
extern Object frame_list_2(Object,Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object g2_stream_close(Object);
extern Object g2_stream_file_length(Object);
extern Object g2_stream_file_non_empty(Object);
extern Object g2_stream_open_for_binary_input(Object);
extern Object g2_stream_read_into_buffer(Object,Object,Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_pathname(Object);
extern Object gensym_probe_file(Object);
extern Object gensym_string_to_wide_string(Object);
extern Object gensym_truename(Object);
extern Object get_frame_given_frame_serial_number(Object);
extern Object get_icon_background_layer_if_any(Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_less_case_sensitive_gensym_pathname_if_any(Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_entry_to_set_of_all_permanent_computation_styles(Object);
extern Object get_quality_and_revision_of_system_version(Object);
extern Object get_reference_to_item(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_slot_name_for_alias_if_any(Object,Object);
extern Object get_slot_represented_by_text_cell_if_any(Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_specialized_definition_class(Object);
extern Object get_system_table_instance_for_module(Object,Object);
extern Object get_updated_edges_from_elements_and_background(Object,Object,Object,Object,Object,Object);
extern Object get_variable_specification_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object ghost_definitions_may_be_saved_in_wrong_order(void);
extern Object has_background_images_p(Object);
extern Object icon_editor_fixed_p_function(void);
extern Object identify_all_permanent_blocks(void);
extern Object identify_all_savable_kb_workspaces(void);
extern Object import_text_string(int,...);
extern Object increment_current_frame_serial_number(void);
extern Object inhibit_restore_detail_pane_p(Object);
extern Object initialize_after_reading_for_block(Object);
extern Object initialize_after_reading_for_definition(Object);
extern Object initialize_after_reading_for_object_definition(Object);
extern Object initialize_after_reading_for_table(Object);
extern Object initialize_for_block(Object);
extern Object initialize_g2_cell_array(Object);
extern Object initialize_g2_cell_array_after_reading(Object);
extern Object initialize_instances_with_default_data_interface_values(void);
extern Object initialize_slot_description_value(Object,Object,Object);
extern Object initialize_slots_of_frame_needing_evaluation(Object);
extern Object initialize_unbound_slots_in_definitions(void);
extern Object install_class_definition(Object,Object,Object,Object,Object);
extern Object install_compiled_byte_code_body(Object,Object);
extern Object install_connection_posts_after_loading(void);
extern Object install_connection_posts_after_loading_1(void);
extern Object install_deferred_class_definitions(void);
extern Object install_external_simulation(void);
extern Object install_external_simulation_1(void);
extern Object instantiated_class_p(Object);
extern Object intern_gensym_string(int,...);
extern Object intern_text_string(int,...);
extern Object launch_compile_to_bring_kb_up_to_date(int,...);
extern Object launch_recompilation_for_this_kb(void);
extern Object legal_gensym_string_p(int,...);
extern Object load_library(Object,Object,Object);
extern Object loading_version_5_or_earlier_kb_p(void);
extern Object lock_to_kb(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_all_indexed_attribute_hash_tables(void);
extern Object make_all_rule_boxes_have_text_box_format(void);
extern Object make_byte_code_body_1(Object,Object,Object,Object,Object);
extern Object make_class_inheritance_path_for_user_defined_class(Object,Object);
extern Object make_connection_1(void);
extern Object make_declaration_clause_for_item_configuration(int,...);
extern Object make_eq_hash_table(Object,Object,Object);
extern Object make_format_frame(Object);
extern Object make_frame_serial_number_to_frame_map(void);
extern Object make_frame_without_computed_initializations(Object,Object,Object);
extern Object make_graphs_opaque(void);
extern Object make_graphs_opaque_1(void);
extern Object make_icon_slot_group_1(void);
extern Object make_index_space_1(Object,Object);
extern Object make_kb_name(Object);
extern Object make_message_board(void);
extern Object make_new_connection_frame_for_connection(Object,Object);
extern Object make_or_clear_complete_kb_name(int,...);
extern Object make_permanent_integer(Object);
extern Object make_slot_value_float(Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_table_wysiwig_if_necessary_after_reading(Object);
extern Object make_text_representation_for_slot_value(int,...);
extern Object make_timestamp_list_1(Object);
extern Object malformed_symbol_name_p(Object);
extern Object map_extended_utf_g_characters_to_unicode(Object,Object);
extern Object map_gensym_han_character_code_to_unicode(Object);
extern Object maybe_normalize_workspace_edges(void);
extern Object memq_function(Object,Object);
extern Object module_name_string_for_xml_object(Object);
extern Object more_than_one_related_item_p(Object);
extern Object most_refined_foundation_class_of_direct_superiors(int,...);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object name_class_with_variant_name(Object,Object);
extern Object namestring_as_gensym_string(Object);
extern Object normalize_kb_workspace(Object,Object);
extern Object normalize_message_properties_for_message_definition(Object);
extern Object note_as_preexisting_frame_if_appropriate(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_connection_1(Object);
extern Object note_crlf_use_in_module_or_file(Object,Object);
extern Object note_frame_with_compilation_removed(Object);
extern Object note_g2_cell_array_runs_while_inactive_change(Object,Object);
extern Object note_runs_while_inactive_change_for_block(Object);
extern Object note_update_to_file_progress(int,...);
extern Object notify_engineer(int,...);
extern Object notify_user(int,...);
extern Object notify_user_1(Object);
extern Object notify_user_at_console(int,...);
extern Object notify_user_at_console_and_on_logbook(int,...);
extern Object obtain_long_enough_adjustable_gensym_string(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object order_ghost_definitions(Object);
extern Object parse_text_for_slot(int,...);
extern Object path_cons_1(Object,Object);
extern Object path_list_2(Object,Object);
extern Object pathname_gt_shared_file_pathname(Object);
extern Object post_analyzer_warning_note_if_necessary(Object);
extern Object post_collected_warnings(Object);
extern Object prepare_for_indexed_attributes_moveage(Object,Object,Object);
extern Object prepare_to_read_backup_if_appropriate(Object);
extern Object prepare_to_read_snapshot_if_appropriate(Object);
extern Object process_pre_4_dot_0_attribute_descriptions_and_default_overrides(Object,Object,Object,Object,Object,Object,Object);
extern Object process_pre_4_dot_0_capabilities_of_class(Object,Object,Object,Object);
extern Object process_slot_group_for_block(Object,Object);
extern Object provide_message_board_after_loading_kb(void);
extern Object put_name_or_names_for_frame(Object,Object,Object);
extern Object put_parent_for_its_indexed_attributes(int,...);
extern Object put_up_file_progress_display(int,...);
extern Object put_wacko_definition_on_kb_workspace(Object);
extern Object raise_image_plane_to_top(int,...);
extern Object read_aggregate_evaluation_value_for_kb(void);
extern Object read_all_top_level_kb_elements(void);
extern Object read_bignum_remainder_of_integer_for_kb(Object,Object);
extern Object read_byte_code_body_for_kb(void);
extern Object read_char_for_kb_past_newline(void);
extern Object read_char_for_kb_past_spaces(void);
extern Object read_character_sequence_as_gensym_string_old_way_1(Object,Object);
extern Object read_character_sequence_as_symbol(Object,Object,Object);
extern Object read_character_sequence_as_text_string(Object,Object);
extern Object read_character_sequence_as_text_string_for_any_recent_version(Object,Object);
extern Object read_character_sequence_as_text_string_old_way(Object,Object);
extern Object read_clear_text_module(Object,Object);
extern Object read_clear_text_module_from_xml_object(Object,Object);
extern Object read_comment_string_if_any_for_kb(void);
extern Object read_connection_for_kb(void);
extern Object read_element_for_kb(Object);
extern Object read_final_block_data_in_old_format_kb(Object,Object);
extern Object read_format_identifier_for_kb(void);
extern Object read_frame_for_kb(Object,Object);
extern Object read_frame_or_connection_reference_for_kb(Object);
extern Object read_ghost_definition_2(Object,Object,Object);
extern Object read_ghost_definitions(void);
extern Object read_ghost_definitions_1(Object);
extern Object read_ghost_definitions_2(Object);
extern Object read_initial_plist(Object,Object,Object);
extern Object read_initial_plist_for_clear_text_kb(void);
extern Object read_initial_plist_for_kb(int,...);
extern Object read_kb(Object,Object,Object,Object,Object,Object,Object);
extern Object read_kb_detail_2(Object);
extern Object read_legacy_long_for_kb(void);
extern Object read_list_element_for_kb(void);
extern Object read_long_for_kb(void);
extern Object read_next_char_for_kb_from_refilled_buffer(void);
extern Object read_past_aggregate_evaluation_value_for_kb(Object);
extern Object read_past_binary_word_for_kb(Object);
extern Object read_past_byte_code_body_for_kb(Object);
extern Object read_past_connection_for_kb(Object);
extern Object read_past_element_for_kb(Object);
extern Object read_past_frame_for_kb(Object,Object);
extern Object read_past_frame_or_connection_reference_for_kb(Object,Object);
extern Object read_past_list_element_for_kb(Object);
extern Object read_past_previous_timestamp_for_kb(Object);
extern Object read_past_readable_element_for_kb(Object);
extern Object read_past_runtime_data_for_block(Object);
extern Object read_past_slot_value_float_for_kb_from_binary(Object,Object);
extern Object read_previous_timestamp_for_kb(void);
extern Object read_readable_element_for_kb(void);
extern Object read_remainder_of_integer_for_kb(Object,Object);
extern Object read_runtime_data_for_block(Object);
extern Object read_slot_value_float_for_kb_from_binary(Object);
extern Object read_top_level_xml_element(Object,Object);
extern Object read_truth_value_for_kb(void);
extern Object read_unencrypted_character_sequence_into_simple_gensym_string(Object,Object);
extern Object read_unencrypted_character_sequence_into_wide_string(Object,Object);
extern Object read_user_mode_alias_for_kb(void);
extern Object reclaim_all_indexed_attribute_hash_tables(void);
extern Object reclaim_bad_connections_of_blocks(Object,Object);
extern Object reclaim_collected_warnings(Object);
extern Object reclaim_connection_1(Object);
extern Object reclaim_eq_hash_table(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_frame_list_1(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_frame_serial_number_map(void);
extern Object reclaim_frame_tree_1(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_index_space_1(Object);
extern Object reclaim_item_and_fsn_list(Object);
extern Object reclaim_items_deleted_since_load_or_save(void);
extern Object reclaim_items_made_incomplete_list(void);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_path_list_1(Object);
extern Object reclaim_pathname_or_string(Object);
extern Object reclaim_relation_instance(Object);
extern Object reclaim_simple_gensym_string(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_sparse_array(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_timestamp_cons_1(Object);
extern Object reclaim_timestamp_list_1(Object);
extern Object reclaim_wide_string(Object);
extern Object recompile_if_compilations_were_removed(void);
extern Object recompile_item_1(Object);
extern Object record_class_name_conflict(int,...);
extern Object record_name_conflict_if_necessary(Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object redisplay_logbook_in_current_workstation(void);
extern Object reformat_as_appropriate(Object,Object);
extern Object reformat_as_appropriate_if_necessary(void);
extern Object reformat_table_in_place(int,...);
extern Object refresh_window(Object);
extern Object reject_gensym_pathname_to_read(Object);
extern Object relation_instances_empty_p(Object);
extern Object remove_as_frame_with_kb_state_changes(Object);
extern Object remove_bogus_parent_property_from_text_cells(Object);
extern Object remove_bogus_stubs_on_frames_in_attributes(void);
extern Object remove_invalid_relation_instances(Object);
extern Object remove_redundant_simulation_formulas_notes(void);
extern Object remove_relations(Object,Object);
extern Object remove_unimplemented_superiors(void);
extern Object rendezvous_frame_denotations_in_relation_instances(void);
extern Object rendezvous_frames_and_denotations_in_aggregate_evaluation_values(void);
extern Object replace_format_using_equivalent_font(Object);
extern Object replace_frame_denotations_in_aggregate_evaluation_value(Object,Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_slot_value_cons_pool(void);
extern Object reset_default_window_style_if_needed(void);
extern Object resolve_class_name_conflicts(void);
extern Object resolve_definitional_name_conflicts(void);
extern Object restore_current_workstation_detail_pane(int,...);
extern Object restore_image_planes_to_pane(int,...);
extern Object restore_image_planes_to_pane_now_or_later(int,...);
extern Object savable_block_p(Object);
extern Object scope_cons(Object,Object);
extern Object set_default_pathname_for_module(Object,Object);
extern Object set_edges_of_block(Object,Object,Object,Object,Object);
extern Object set_gensym_pathname_for_module(Object,Object);
extern Object set_get_connection_vertices_backward_compatibility(void);
extern Object set_ignore_insert_action_duplicate_element(void);
extern Object set_ignore_snap_grid_in_transfer_operations(void);
extern Object set_inconsistent_behavior_of_move_in_configurations(void);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_print_means_print_to_server_in_configurations(void);
extern Object set_reason_module_is_not_editable(Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_description_value_without_noting(Object,Object,Object);
extern Object set_slot_value_function(Object,Object,Object,Object);
extern Object set_up_modules_and_system_tables_a_list_after_reading(void);
extern Object shrink_wrap_workspace_around_maximum_rectangle(Object);
extern Object simple_kb_read(Object,Object,Object,Object);
extern Object simple_kb_read_1(Object,Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object string_eq_w(Object,Object);
extern Object sum_list_lengths(Object);
extern Object system_revision_greater_p(Object,Object);
extern Object system_version_greater_p(Object,Object);
extern Object system_version_major_difference(Object,Object);
extern Object terminate_load_when_definitions_have_changed(void);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object timestamp_cons_1(Object,Object);
extern Object try_to_do_deferred_user_notifications(void);
extern Object twrite(Object);
extern Object twrite_system_version(int,...);
extern Object twrite_wide_character(Object);
extern Object undo_kb_state_changes_for_frame(Object);
extern Object update_attribute_tables(int,...);
extern Object update_extreme_edges_from_background_images(Object);
extern Object update_extreme_edges_from_elements_function(Object,Object);
extern Object update_file_progress_display(int,...);
extern Object update_file_progress_display_after_reading(Object,Object);
extern Object update_file_progress_display_for_newline_in_kb(int,...);
extern Object update_frame_status(Object,Object,Object);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_representations_of_class_specific_attributes_grammar(void);
extern Object update_representations_of_configuration_grammar(void);
extern Object update_representations_of_default_overrides_grammar(void);
extern Object update_representations_of_initial_value_of_variable_or_parameter(void);
extern Object update_representations_of_slot_value(int,...);
extern Object upgrade_block_connections(Object);
extern Object upgrade_block_connections_to_connections_v2(void);
extern Object upgrade_connections(Object);
extern Object upgrade_relation_instances(Object);
extern Object upgrade_subblocks(Object);
extern Object warn_of_undefined_connection_subclass_if_appropriate(Object);
extern Object wide_string_to_string(Object);
extern Object workspace_background_images_are_centered_p(void);

#else

extern Object abort_g2();
extern Object abort_on_bad_kb();
extern Object activate_roots_of_kb_hierarchy_just_read_in();
extern Object add_new_byte_code_body();
extern Object add_new_compiled_byte_code_body();
extern Object add_recent_loaded_kb();
extern Object add_to_relation();
extern Object adjust_direct_superiors_per_class_conflicts();
extern Object aggregate_evaluation_value_p();
extern Object allocate_byte_vector();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_array();
extern Object allocate_managed_float_array();
extern Object allocate_managed_long_box();
extern Object allocate_managed_simple_vector();
extern Object allocate_sparse_array_1();
extern Object always_instantiate_connection_frame_for_this_class_qm();
extern Object analyze_compiled_items_after_loading();
extern Object analyze_compiled_items_after_loading_1();
extern Object aref_sparse_array();
extern Object aset_sparse_array();
extern Object assemble_uncached_compound_method_flags();
extern Object assign_index_in_index_space();
extern Object assq_function();
extern Object assure_all_charts_are_modern_1();
extern Object assure_all_charts_have_style();
extern Object blinking_area_p();
extern Object block_needs_activation_upon_reading_p();
extern Object block_relation_instances_violate_class_type_p();
extern Object bytes_per_double_float_simple_array();
extern Object c_native_clock_ticks_or_cache();
extern Object center_workspace_background_images();
extern Object center_workspace_background_images_after_loading();
extern Object change_all_permanently_changed_things_are_marked();
extern Object change_slot_value();
extern Object change_text_cell_property();
extern Object check_for_table_representing_recycled_definition();
extern Object check_ignore_snap_grid_in_transfer_operations();
extern Object check_inconsistent_behavior_of_move_in_configurations();
extern Object check_insert_action_duplicate_element_flag();
extern Object check_new_get_connection_vertex_behavior_flag();
extern Object check_print_means_print_to_server_in_configurations();
extern Object check_slash_extension_for_character_sequence();
extern Object chestnut_modf_function();
extern Object classic_kbs_prefer_classic_editor();
extern Object classic_kbs_prefer_classic_selection_highlighting();
extern Object classic_kbs_prefer_classic_ui_features();
extern Object clean_up_orphan_frame_representations();
extern Object cleanup_for_block();
extern Object cleanup_g2_cell_array();
extern Object clear_kb();
extern Object clockwise_polygon_p();
extern Object collect_leaf_vectors();
extern Object collect_subclasses();
extern Object collect_unreprocessed_items();
extern Object collect_warning();
extern Object color_or_metacolor_p();
extern Object compiled_kb_initialization_argument();
extern Object complete_definition_p();
extern Object constant_queue_next();
extern Object continue_read_kb();
extern Object convert_alist_to_plist();
extern Object convert_description_list_to_managed_array();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_illegal_gensym_string_without_bad_characters();
extern Object copy_list_of_relation_instances();
extern Object copy_managed_float();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_unsaved_slots_from_connection_to_connection_frame();
extern Object count_and_fix_invalid_items();
extern Object deal_with_class_name_conflicts();
extern Object deal_with_junction_block_class_differences();
extern Object defer_class_definition();
extern Object definition_class_is_subclass_of_obj_conn_mess_definition_p();
extern Object delete_all_frame_notes_for_component_particular();
extern Object delete_all_title_block_workspaces();
extern Object delete_bad_connection_structures();
extern Object delete_block_after_reading_kb();
extern Object delete_block_after_unsquirreling();
extern Object delete_blocks_and_connections_to_be_deleted_after_reading();
extern Object delete_connection();
extern Object delete_connection_after_reading_kb();
extern Object delete_connection_frames_without_connection_structures();
extern Object delete_connection_in_block();
extern Object delete_frame();
extern Object delete_frame_note_if_any();
extern Object delete_skip_list_entry();
extern Object delete_slot_value_element_1();
extern Object delete_type_violating_relation_instances();
extern Object delete_type_violating_relation_instances_1();
extern Object direct_superiors_are_defined_p();
extern Object do_one_post_loading_function();
extern Object do_post_loading_functions();
extern Object eliminate_procedure_invocation_frame_notes();
extern Object empty_layer_in_icon_description_p();
extern Object enlarge_index_space();
extern Object ensure_connections_have_frames_if_necessary();
extern Object enter_frame_into_frame_serial_number_map();
extern Object enter_old_things_into_map();
extern Object eq_gethash();
extern Object eq_puthash();
extern Object eval_cons_1();
extern Object evaluation_value_value();
extern Object export_text_string();
extern Object extend_current_gensym_string();
extern Object find_differences_in_frames_if_any();
extern Object find_existing_equivalent_format_frame();
extern Object find_frame_for_denotation();
extern Object find_similar_class_name();
extern Object find_similar_slot_name();
extern Object finish_reading_format_frame_for_kb();
extern Object finish_reading_into_managed_array_for_kb();
extern Object finish_reading_into_managed_float_array_for_kb();
extern Object finish_reading_managed_array_for_kb();
extern Object finish_reading_managed_float_array_for_kb();
extern Object finish_reading_slot_value_float();
extern Object fix_capabilities_of_old_kbs();
extern Object fix_icon_description_for_class_slot();
extern Object fix_icon_variables_alists_in_icon_attributes_plist();
extern Object fix_kb_workspaces_that_might_be_too_big();
extern Object fix_line_drawing_description_for_class();
extern Object fix_module_related_frame_notes_after_loading();
extern Object fix_possible_non_symbols_in_g2_user_mode();
extern Object fix_subworkspace_names();
extern Object fix_unimplemented_definitions();
extern Object fix_up_configuration_attribute_error();
extern Object fix_up_default_overrides_for_5_0();
extern Object fix_up_double_click_configuration_clauses();
extern Object fixnum_time_difference_in_seconds();
extern Object fixup_all_author_or_authors();
extern Object fixup_all_digital_clocks();
extern Object fixup_author_or_authors_value();
extern Object fixup_icon_description_for_class();
extern Object force_process_drawing();
extern Object frame_cons_1();
extern Object frame_list_2();
extern Object frame_serial_number_setf_helper_1();
extern Object g2_stream_close();
extern Object g2_stream_file_length();
extern Object g2_stream_file_non_empty();
extern Object g2_stream_open_for_binary_input();
extern Object g2_stream_read_into_buffer();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object gensym_namestring();
extern Object gensym_pathname();
extern Object gensym_probe_file();
extern Object gensym_string_to_wide_string();
extern Object gensym_truename();
extern Object get_frame_given_frame_serial_number();
extern Object get_icon_background_layer_if_any();
extern Object get_instance_with_name_if_any();
extern Object get_less_case_sensitive_gensym_pathname_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_entry_to_set_of_all_permanent_computation_styles();
extern Object get_quality_and_revision_of_system_version();
extern Object get_reference_to_item();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_slot_name_for_alias_if_any();
extern Object get_slot_represented_by_text_cell_if_any();
extern Object get_slot_value_function();
extern Object get_specialized_definition_class();
extern Object get_system_table_instance_for_module();
extern Object get_updated_edges_from_elements_and_background();
extern Object get_variable_specification_if_any();
extern Object getfq_function_no_default();
extern Object ghost_definitions_may_be_saved_in_wrong_order();
extern Object has_background_images_p();
extern Object icon_editor_fixed_p_function();
extern Object identify_all_permanent_blocks();
extern Object identify_all_savable_kb_workspaces();
extern Object import_text_string();
extern Object increment_current_frame_serial_number();
extern Object inhibit_restore_detail_pane_p();
extern Object initialize_after_reading_for_block();
extern Object initialize_after_reading_for_definition();
extern Object initialize_after_reading_for_object_definition();
extern Object initialize_after_reading_for_table();
extern Object initialize_for_block();
extern Object initialize_g2_cell_array();
extern Object initialize_g2_cell_array_after_reading();
extern Object initialize_instances_with_default_data_interface_values();
extern Object initialize_slot_description_value();
extern Object initialize_slots_of_frame_needing_evaluation();
extern Object initialize_unbound_slots_in_definitions();
extern Object install_class_definition();
extern Object install_compiled_byte_code_body();
extern Object install_connection_posts_after_loading();
extern Object install_connection_posts_after_loading_1();
extern Object install_deferred_class_definitions();
extern Object install_external_simulation();
extern Object install_external_simulation_1();
extern Object instantiated_class_p();
extern Object intern_gensym_string();
extern Object intern_text_string();
extern Object launch_compile_to_bring_kb_up_to_date();
extern Object launch_recompilation_for_this_kb();
extern Object legal_gensym_string_p();
extern Object load_library();
extern Object loading_version_5_or_earlier_kb_p();
extern Object lock_to_kb();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_all_indexed_attribute_hash_tables();
extern Object make_all_rule_boxes_have_text_box_format();
extern Object make_byte_code_body_1();
extern Object make_class_inheritance_path_for_user_defined_class();
extern Object make_connection_1();
extern Object make_declaration_clause_for_item_configuration();
extern Object make_eq_hash_table();
extern Object make_format_frame();
extern Object make_frame_serial_number_to_frame_map();
extern Object make_frame_without_computed_initializations();
extern Object make_graphs_opaque();
extern Object make_graphs_opaque_1();
extern Object make_icon_slot_group_1();
extern Object make_index_space_1();
extern Object make_kb_name();
extern Object make_message_board();
extern Object make_new_connection_frame_for_connection();
extern Object make_or_clear_complete_kb_name();
extern Object make_permanent_integer();
extern Object make_slot_value_float();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_table_wysiwig_if_necessary_after_reading();
extern Object make_text_representation_for_slot_value();
extern Object make_timestamp_list_1();
extern Object malformed_symbol_name_p();
extern Object map_extended_utf_g_characters_to_unicode();
extern Object map_gensym_han_character_code_to_unicode();
extern Object maybe_normalize_workspace_edges();
extern Object memq_function();
extern Object module_name_string_for_xml_object();
extern Object more_than_one_related_item_p();
extern Object most_refined_foundation_class_of_direct_superiors();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object name_class_with_variant_name();
extern Object namestring_as_gensym_string();
extern Object normalize_kb_workspace();
extern Object normalize_message_properties_for_message_definition();
extern Object note_as_preexisting_frame_if_appropriate();
extern Object note_change_to_block_1();
extern Object note_change_to_connection_1();
extern Object note_crlf_use_in_module_or_file();
extern Object note_frame_with_compilation_removed();
extern Object note_g2_cell_array_runs_while_inactive_change();
extern Object note_runs_while_inactive_change_for_block();
extern Object note_update_to_file_progress();
extern Object notify_engineer();
extern Object notify_user();
extern Object notify_user_1();
extern Object notify_user_at_console();
extern Object notify_user_at_console_and_on_logbook();
extern Object obtain_long_enough_adjustable_gensym_string();
extern Object obtain_simple_gensym_string();
extern Object order_ghost_definitions();
extern Object parse_text_for_slot();
extern Object path_cons_1();
extern Object path_list_2();
extern Object pathname_gt_shared_file_pathname();
extern Object post_analyzer_warning_note_if_necessary();
extern Object post_collected_warnings();
extern Object prepare_for_indexed_attributes_moveage();
extern Object prepare_to_read_backup_if_appropriate();
extern Object prepare_to_read_snapshot_if_appropriate();
extern Object process_pre_4_dot_0_attribute_descriptions_and_default_overrides();
extern Object process_pre_4_dot_0_capabilities_of_class();
extern Object process_slot_group_for_block();
extern Object provide_message_board_after_loading_kb();
extern Object put_name_or_names_for_frame();
extern Object put_parent_for_its_indexed_attributes();
extern Object put_up_file_progress_display();
extern Object put_wacko_definition_on_kb_workspace();
extern Object raise_image_plane_to_top();
extern Object read_aggregate_evaluation_value_for_kb();
extern Object read_all_top_level_kb_elements();
extern Object read_bignum_remainder_of_integer_for_kb();
extern Object read_byte_code_body_for_kb();
extern Object read_char_for_kb_past_newline();
extern Object read_char_for_kb_past_spaces();
extern Object read_character_sequence_as_gensym_string_old_way_1();
extern Object read_character_sequence_as_symbol();
extern Object read_character_sequence_as_text_string();
extern Object read_character_sequence_as_text_string_for_any_recent_version();
extern Object read_character_sequence_as_text_string_old_way();
extern Object read_clear_text_module();
extern Object read_clear_text_module_from_xml_object();
extern Object read_comment_string_if_any_for_kb();
extern Object read_connection_for_kb();
extern Object read_element_for_kb();
extern Object read_final_block_data_in_old_format_kb();
extern Object read_format_identifier_for_kb();
extern Object read_frame_for_kb();
extern Object read_frame_or_connection_reference_for_kb();
extern Object read_ghost_definition_2();
extern Object read_ghost_definitions();
extern Object read_ghost_definitions_1();
extern Object read_ghost_definitions_2();
extern Object read_initial_plist();
extern Object read_initial_plist_for_clear_text_kb();
extern Object read_initial_plist_for_kb();
extern Object read_kb();
extern Object read_kb_detail_2();
extern Object read_legacy_long_for_kb();
extern Object read_list_element_for_kb();
extern Object read_long_for_kb();
extern Object read_next_char_for_kb_from_refilled_buffer();
extern Object read_past_aggregate_evaluation_value_for_kb();
extern Object read_past_binary_word_for_kb();
extern Object read_past_byte_code_body_for_kb();
extern Object read_past_connection_for_kb();
extern Object read_past_element_for_kb();
extern Object read_past_frame_for_kb();
extern Object read_past_frame_or_connection_reference_for_kb();
extern Object read_past_list_element_for_kb();
extern Object read_past_previous_timestamp_for_kb();
extern Object read_past_readable_element_for_kb();
extern Object read_past_runtime_data_for_block();
extern Object read_past_slot_value_float_for_kb_from_binary();
extern Object read_previous_timestamp_for_kb();
extern Object read_readable_element_for_kb();
extern Object read_remainder_of_integer_for_kb();
extern Object read_runtime_data_for_block();
extern Object read_slot_value_float_for_kb_from_binary();
extern Object read_top_level_xml_element();
extern Object read_truth_value_for_kb();
extern Object read_unencrypted_character_sequence_into_simple_gensym_string();
extern Object read_unencrypted_character_sequence_into_wide_string();
extern Object read_user_mode_alias_for_kb();
extern Object reclaim_all_indexed_attribute_hash_tables();
extern Object reclaim_bad_connections_of_blocks();
extern Object reclaim_collected_warnings();
extern Object reclaim_connection_1();
extern Object reclaim_eq_hash_table();
extern Object reclaim_eval_list_1();
extern Object reclaim_frame_list_1();
extern Object reclaim_frame_serial_number();
extern Object reclaim_frame_serial_number_map();
extern Object reclaim_frame_tree_1();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_index_space_1();
extern Object reclaim_item_and_fsn_list();
extern Object reclaim_items_deleted_since_load_or_save();
extern Object reclaim_items_made_incomplete_list();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_path_list_1();
extern Object reclaim_pathname_or_string();
extern Object reclaim_relation_instance();
extern Object reclaim_simple_gensym_string();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_sparse_array();
extern Object reclaim_text_string();
extern Object reclaim_timestamp_cons_1();
extern Object reclaim_timestamp_list_1();
extern Object reclaim_wide_string();
extern Object recompile_if_compilations_were_removed();
extern Object recompile_item_1();
extern Object record_class_name_conflict();
extern Object record_name_conflict_if_necessary();
extern Object record_system_variable();
extern Object redisplay_logbook_in_current_workstation();
extern Object reformat_as_appropriate();
extern Object reformat_as_appropriate_if_necessary();
extern Object reformat_table_in_place();
extern Object refresh_window();
extern Object reject_gensym_pathname_to_read();
extern Object relation_instances_empty_p();
extern Object remove_as_frame_with_kb_state_changes();
extern Object remove_bogus_parent_property_from_text_cells();
extern Object remove_bogus_stubs_on_frames_in_attributes();
extern Object remove_invalid_relation_instances();
extern Object remove_redundant_simulation_formulas_notes();
extern Object remove_relations();
extern Object remove_unimplemented_superiors();
extern Object rendezvous_frame_denotations_in_relation_instances();
extern Object rendezvous_frames_and_denotations_in_aggregate_evaluation_values();
extern Object replace_format_using_equivalent_font();
extern Object replace_frame_denotations_in_aggregate_evaluation_value();
extern Object replenish_lookup_cons_pool();
extern Object replenish_slot_value_cons_pool();
extern Object reset_default_window_style_if_needed();
extern Object resolve_class_name_conflicts();
extern Object resolve_definitional_name_conflicts();
extern Object restore_current_workstation_detail_pane();
extern Object restore_image_planes_to_pane();
extern Object restore_image_planes_to_pane_now_or_later();
extern Object savable_block_p();
extern Object scope_cons();
extern Object set_default_pathname_for_module();
extern Object set_edges_of_block();
extern Object set_gensym_pathname_for_module();
extern Object set_get_connection_vertices_backward_compatibility();
extern Object set_ignore_insert_action_duplicate_element();
extern Object set_ignore_snap_grid_in_transfer_operations();
extern Object set_inconsistent_behavior_of_move_in_configurations();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_print_means_print_to_server_in_configurations();
extern Object set_reason_module_is_not_editable();
extern Object set_skip_list_entry();
extern Object set_slot_description_value_without_noting();
extern Object set_slot_value_function();
extern Object set_up_modules_and_system_tables_a_list_after_reading();
extern Object shrink_wrap_workspace_around_maximum_rectangle();
extern Object simple_kb_read();
extern Object simple_kb_read_1();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object string_eq_w();
extern Object sum_list_lengths();
extern Object system_revision_greater_p();
extern Object system_version_greater_p();
extern Object system_version_major_difference();
extern Object terminate_load_when_definitions_have_changed();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object timestamp_cons_1();
extern Object try_to_do_deferred_user_notifications();
extern Object twrite();
extern Object twrite_system_version();
extern Object twrite_wide_character();
extern Object undo_kb_state_changes_for_frame();
extern Object update_attribute_tables();
extern Object update_extreme_edges_from_background_images();
extern Object update_extreme_edges_from_elements_function();
extern Object update_file_progress_display();
extern Object update_file_progress_display_after_reading();
extern Object update_file_progress_display_for_newline_in_kb();
extern Object update_frame_status();
extern Object update_images_of_block();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_representations_of_class_specific_attributes_grammar();
extern Object update_representations_of_configuration_grammar();
extern Object update_representations_of_default_overrides_grammar();
extern Object update_representations_of_initial_value_of_variable_or_parameter();
extern Object update_representations_of_slot_value();
extern Object upgrade_block_connections();
extern Object upgrade_block_connections_to_connections_v2();
extern Object upgrade_connections();
extern Object upgrade_relation_instances();
extern Object upgrade_subblocks();
extern Object warn_of_undefined_connection_subclass_if_appropriate();
extern Object wide_string_to_string();
extern Object workspace_background_images_are_centered_p();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Add_as_item_referring_to_name_qm, Qadd_as_item_referring_to_name_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Additional_related_blocks, Qadditional_related_blocks);
DECLARE_VARIABLE_WITH_SYMBOL(Automatically_resolve_conflicts_by_default, Qautomatically_resolve_conflicts_by_default);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_path_conses_tail_vector;
extern Object Available_path_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Backup_case_qm, Qbackup_case_qm);
#define Base_modulus FIX((SI_Long)3989L)
DECLARE_VARIABLE_WITH_SYMBOL(Base_reference, Qbase_reference);
DECLARE_VARIABLE_WITH_SYMBOL(Basis_kb_frame_serial_number, Qbasis_kb_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_to_delete_after_reading_kb, Qblocks_to_delete_after_reading_kb);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_to_delete_after_unsquirreling, Qblocks_to_delete_after_unsquirreling);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_with_bad_connections, Qblocks_with_bad_connections);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_with_connections_from_kb_read, Qblocks_with_connections_from_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_with_relation_instances_from_kb_read, Qblocks_with_relation_instances_from_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(Blocks_with_subblocks_from_kb_read, Qblocks_with_subblocks_from_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_unknown_error_string_with_code_qm, Qcached_unknown_error_string_with_code_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
extern Object Class_instance_delta_masks;
DECLARE_VARIABLE_WITH_SYMBOL(Class_name_conflicts, Qclass_name_conflicts);
DECLARE_VARIABLE_WITH_SYMBOL(Class_name_read_while_reading_current_ghost_definition, Qclass_name_read_while_reading_current_ghost_definition);
DECLARE_VARIABLE_WITH_SYMBOL(Classes_needing_data_interface_initialization, Qclasses_needing_data_interface_initialization);
DECLARE_VARIABLE_WITH_SYMBOL(Collected_items_with_warnings_alist, Qcollected_items_with_warnings_alist);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_procedures_to_warn_about_p, Qcollecting_procedures_to_warn_about_p);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_warnings_p, Qcollecting_warnings_p);
DECLARE_VARIABLE_WITH_SYMBOL(Compiling_incomplete_items_after_analyze_p, Qcompiling_incomplete_items_after_analyze_p);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_classes_warned_about_for_this_kb, Qconnection_classes_warned_about_for_this_kb);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_definition_class_description, Qconnection_definition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connections_to_delete_after_reading_kb, Qconnections_to_delete_after_reading_kb);
DECLARE_VARIABLE_WITH_SYMBOL(Create_frames_and_connections_reading_past_qm, Qcreate_frames_and_connections_reading_past_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_extended_utf_g_low_half_character_qm, Qcurrent_extended_utf_g_low_half_character_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number_before_reading, Qcurrent_frame_serial_number_before_reading);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_file_progress_for_modules_qm, Qcurrent_kb_file_progress_for_modules_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_pathname_qm, Qcurrent_kb_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_logbook_qm, Qcurrent_logbook_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_logbook_serial_number_qm, Qcurrent_logbook_serial_number_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_message_board_qm, Qcurrent_message_board_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_rpc_icp_socket_qm, Qcurrent_system_rpc_icp_socket_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Deferred_class_definitions_alist, Qdeferred_class_definitions_alist);
DECLARE_VARIABLE_WITH_SYMBOL(Definition_class_description, Qdefinition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Definitions_read_in_this_module, Qdefinitions_read_in_this_module);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_notify_user_during_kb_load_qm, Qdo_not_notify_user_during_kb_load_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_restore_image_planes_qm, Qdo_not_restore_image_planes_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Dont_load_if_definitions_have_changed_p, Qdont_load_if_definitions_have_changed_p);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_parameters, Qdrawing_parameters);
extern Object Earliest_version_to_allow_kb_loading;
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Embedded_fuzzy_conditionals_list, Qembedded_fuzzy_conditionals_list);
DECLARE_VARIABLE_WITH_SYMBOL(Enable_loading_compiled_kbs_p, Qenable_loading_compiled_kbs_p);
extern Object Evaluator_tradeoff_info;
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_bottom_edge_so_far, Qextreme_bottom_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_left_edge_so_far, Qextreme_left_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_right_edge_so_far, Qextreme_right_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_top_edge_so_far, Qextreme_top_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Format_frame_class_description, Qformat_frame_class_description);
extern Object Format_structure_description;
DECLARE_VARIABLE_WITH_SYMBOL(Forward_referenced_format_frames, Qforward_referenced_format_frames);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_being_read_qm, Qframe_being_read_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_serial_number_map, Qframe_serial_number_map);
DECLARE_VARIABLE_WITH_SYMBOL(Frame_serial_number_of_current_message_board, Qframe_serial_number_of_current_message_board);
DECLARE_VARIABLE_WITH_SYMBOL(Frames_for_rendezvous_in_aggregate_values_qm, Qframes_for_rendezvous_in_aggregate_values_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Frames_with_substitute_classes, Qframes_with_substitute_classes);
DECLARE_VARIABLE_WITH_SYMBOL(G2_stream_error_string_table, Qg2_stream_error_string_table);
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
#define G2_version_6_general_kb_flags FIX((SI_Long)270L)
#define G2_version_82r0_kb_flags FIX((SI_Long)279L)
#define G2_version_8_1_alpha_0_kb_flags FIX((SI_Long)276L)
#define G2_version_8_3_alpha_0_kb_flags FIX((SI_Long)280L)
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_base_time_as_managed_float, Qgensym_base_time_as_managed_float);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_linebreak, Qgensym_char_or_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_paragraph_break, Qgensym_char_or_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_bullet, Qgensym_code_for_bullet);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_capital_ligature_oe, Qgensym_code_for_capital_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_linebreak, Qgensym_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_paragraph_break, Qgensym_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_letter_f_with_hook, Qgensym_code_for_small_letter_f_with_hook);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_ligature_oe, Qgensym_code_for_small_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_trade_mark_sign, Qgensym_code_for_trade_mark_sign);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_linebreak_qm, Qgensym_esc_for_linebreak_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_paragraph_break_qm, Qgensym_esc_for_paragraph_break_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_file_error_occurred_p, Qgensym_file_error_occurred_p);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_at_start, Qgensym_time_at_start);
extern Object Gensym_to_unicode_full_row_map;
DECLARE_VARIABLE_WITH_SYMBOL(Geometric_change_to_connection_is_temporary_p, Qgeometric_change_to_connection_is_temporary_p);
DECLARE_VARIABLE_WITH_SYMBOL(Graph_class_description, Qgraph_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Ignore_kb_flags_in_kbs_qm, Qignore_kb_flags_in_kbs_qm);
extern Object Ignore_process_newline;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_handling_gensym_file_errors_scope_p, Qinside_handling_gensym_file_errors_scope_p);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Internal_status_of_most_recent_file_operation, Qinternal_status_of_most_recent_file_operation);
#define Invalid_unicode_full_row FIX((SI_Long)7L)
DECLARE_VARIABLE_WITH_SYMBOL(Iso_latin1_special_character_code_map, Qiso_latin1_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Items_made_incomplete, Qitems_made_incomplete);
DECLARE_VARIABLE_WITH_SYMBOL(Items_made_incomplete_were_recorded_qm, Qitems_made_incomplete_were_recorded_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_file_progress, Qkb_file_progress);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_file_progress_is_currently_for_modules_p, Qkb_file_progress_is_currently_for_modules_p);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags, Qkb_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags_from_last_kb_read, Qkb_flags_from_last_kb_read);
extern Object Kb_flags_of_software;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_format_identifier_read_qm, Qkb_format_identifier_read_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_load_case_qm, Qkb_load_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_object_index_space, Qkb_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_uses_crlf_p, Qkb_uses_crlf_p);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Keyword_package_1, Qkeyword_package_1);
DECLARE_VARIABLE_WITH_SYMBOL(Launch_recompile_for_compilations_removed_in_this_kb_qm, Qlaunch_recompile_for_compilations_removed_in_this_kb_qm);
extern Object Limit_bignum_inner_loop_cache_p;
DECLARE_VARIABLE_WITH_SYMBOL(List_of_module_pre_conflict_resolution_post_loading_functions, Qlist_of_module_pre_conflict_resolution_post_loading_functions);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_once_only_post_conflict_resolution_post_loading_functions, Qlist_of_once_only_post_conflict_resolution_post_loading_functions);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_once_only_pre_conflict_resolution_post_loading_functions, Qlist_of_once_only_pre_conflict_resolution_post_loading_functions);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_once_only_switched_post_loading_functions, Qlist_of_once_only_switched_post_loading_functions);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_switched_and_module_post_loading_functions, Qlist_of_switched_and_module_post_loading_functions);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_compiled_kb_p, Qloading_compiled_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Locked_to_kb_qm, Qlocked_to_kb_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Logbook_parameters, Qlogbook_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Main_kb_being_read_qm, Qmain_kb_being_read_qm);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
extern Object Maximum_suggested_length_for_simple_gensym_strings;
DECLARE_VARIABLE_WITH_SYMBOL(Message_board_parameters, Qmessage_board_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Message_definition_class_description, Qmessage_definition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
extern Object Module_is_writable_p_kbprop;
extern Object Most_negative_fixnum_as_float;
extern Object Most_positive_fixnum_as_float;
extern Object Most_positive_fixnum_ash_minus_5_minus_1;
DECLARE_VARIABLE_WITH_SYMBOL(Name_of_kb_being_read, Qname_of_kb_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(Name_of_module_being_read_qm, Qname_of_module_being_read_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Name_text_string_for_kb_being_read, Qname_text_string_for_kb_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(Namestring_for_kb_being_read, Qnamestring_for_kb_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(Need_to_check_plist_p, Qneed_to_check_plist_p);
DECLARE_VARIABLE_WITH_SYMBOL(New_byte_code_body_list, Qnew_byte_code_body_list);
DECLARE_VARIABLE_WITH_SYMBOL(New_compiled_byte_code_body_list, Qnew_compiled_byte_code_body_list);
DECLARE_VARIABLE_WITH_SYMBOL(New_saved_kb_format_p, Qnew_saved_kb_format_p);
DECLARE_VARIABLE_WITH_SYMBOL(Newline_characters, Qnewline_characters);
DECLARE_VARIABLE_WITH_SYMBOL(Next_character_for_kb_qm, Qnext_character_for_kb_qm);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_kb_characters_so_far_qm, Qnumber_of_kb_characters_so_far_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_kb_lines_so_far, Qnumber_of_kb_lines_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Object_definition_class_description, Qobject_definition_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Operation_around_record_of_items_made_incomplete, Qoperation_around_record_of_items_made_incomplete);
DECLARE_VARIABLE_WITH_SYMBOL(Original_kb_state_plist_written_qm, Qoriginal_kb_state_plist_written_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Plist_from_end_element_qm, Qplist_from_end_element_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Plist_has_been_checked_p, Qplist_has_been_checked_p);
DECLARE_VARIABLE_WITH_SYMBOL(Post_loading_functions_will_be_executed_again_later_qm, Qpost_loading_functions_will_be_executed_again_later_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Preexisting_frames, Qpreexisting_frames);
DECLARE_VARIABLE_WITH_SYMBOL(Previous_timestamp_qm, Qprevious_timestamp_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_invocation_class_description, Qprocedure_invocation_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Procedures_to_warn_about_p, Qprocedures_to_warn_about_p);
DECLARE_VARIABLE_WITH_SYMBOL(Read_kb_buffer, Qread_kb_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Read_kb_buffer_index, Qread_kb_buffer_index);
DECLARE_VARIABLE_WITH_SYMBOL(Read_kb_buffer_length, Qread_kb_buffer_length);
DECLARE_VARIABLE_WITH_SYMBOL(Read_kb_stream, Qread_kb_stream);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_ghost_definitions_p, Qreading_ghost_definitions_p);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_kb_p, Qreading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Recompile_on_next_load, Qrecompile_on_next_load);
DECLARE_VARIABLE_WITH_SYMBOL(Record_class_name_conflicts_qm, Qrecord_class_name_conflicts_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Recording_items_made_incomplete_qm, Qrecording_items_made_incomplete_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Reference_serial_number_for_saved_detail_pane_description, Qreference_serial_number_for_saved_detail_pane_description);
DECLARE_VARIABLE_WITH_SYMBOL(Reformat_as_appropriate_qm, Qreformat_as_appropriate_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Refresh_all_windows_after_merging_qm, Qrefresh_all_windows_after_merging_qm);
extern Object Refuse_load_at_discrepancy_with_system_clock_message;
#define Release_quality FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Rendezvous_successful_blocks_qm, Qrendezvous_successful_blocks_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Reverse_iso_latin1_special_character_code_map, Qreverse_iso_latin1_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Roman_font_special_character_code_map, Qroman_font_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
extern Object Savable_connection_flags;
DECLARE_VARIABLE_WITH_SYMBOL(Saved_detail_pane_description, Qsaved_detail_pane_description);
DECLARE_VARIABLE_WITH_SYMBOL(Saving_kb_p, Qsaving_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Seconds_from_1900_to_1970;
DECLARE_VARIABLE_WITH_SYMBOL(Separate_imminent_actions_p, Qseparate_imminent_actions_p);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_no_value, Qsimulation_no_value);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Slot_description_for_slot_value_being_read_qm, Qslot_description_for_slot_value_being_read_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Some_module_is_clear_text_p, Qsome_module_is_clear_text_p);
#define Standard_base_reference FIX((SI_Long)27L)
extern Object Substitute_format_name_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
extern Object Switched_once_only_post_loads_are_after_conflict_resolution;
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(System_quality_from_last_kb_read, Qsystem_quality_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_revision_from_last_kb_read, Qsystem_revision_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_tables_read_for_this_module, Qsystem_tables_read_for_this_module);
DECLARE_VARIABLE_WITH_SYMBOL(System_version_from_kb_being_read, Qsystem_version_from_kb_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_version_from_last_kb_read, Qsystem_version_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_version_of_current_gensym_product_line, Qsystem_version_of_current_gensym_product_line);
DECLARE_VARIABLE_WITH_SYMBOL(Table_class_description, Qtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Top_level_error_seen, Qtop_level_error_seen);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_file_being_read, Qtype_of_file_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(Ui_client_interface_in_which_to_launch_recompilation_qm, Qui_client_interface_in_which_to_launch_recompilation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Unevaluated_expression, Qunevaluated_expression);
extern Object Unknown_error_during_file_op_with_code_message;
DECLARE_VARIABLE_WITH_SYMBOL(Update_before_loading_by_default, Qupdate_before_loading_by_default);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
extern Object Verbose_post_loading_p;
DECLARE_VARIABLE_WITH_SYMBOL(Warmboot_current_time, Qwarmboot_current_time);
DECLARE_VARIABLE_WITH_SYMBOL(Warmboot_simulated_time, Qwarmboot_simulated_time);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_qm, Qwarmbooting_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_with_catch_up_qm, Qwarmbooting_with_catch_up_qm);
extern Object Within_side_limits;
DECLARE_VARIABLE_WITH_SYMBOL(Workstation_in_which_to_launch_recompilation_qm, Qworkstation_in_which_to_launch_recompilation_qm);
extern Object Workstations_in_service;
