/* kbld1.h -- Header File for kbld1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qslash;
extern Object Qnum_lt;
extern Object Qnum_gt;
extern Object Qload;
extern Object Qlog;
extern Object Qmerge;
extern Object Knewest;
extern Object Qnot;
extern Object Qnumber;
extern Object Qquote;
extern Object Qreplace;
extern Object Qtype;
extern Object Qunsigned_byte;
extern Object Kwild;
extern Object Qwrite;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abandon_load_or_merge_kb_if_ok(Object,Object);
extern Object abort_current_workstation_context(Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_items_to_edit_workspace_for_kb_load_file_command(Object,Object,Object,Object);
extern Object add_recent_loaded_kb(Object);
extern Object add_source_code_control_grammar(void);
extern Object add_subworkspace(Object,Object);
extern Object add_to_block(int,...);
extern Object add_to_directory_of_names(Object,Object);
extern Object add_to_workspace(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object assq_function(Object,Object);
extern Object bad_4_0_beta_magnifications_in_text_boxes_removed_p_function(void);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object change_edges_of_block(Object,Object,Object,Object,Object);
extern Object change_on_sl_off_switch(Object,Object);
extern Object change_slot_value(int,...);
extern Object check_file_command_for_slot(Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object choose_font_format_per_fonts_table(Object,Object);
extern Object cleanup_for_kb_load_file_command(Object);
extern Object clear_file_and_directory_name_directories(Object);
extern Object clear_load_command_directory_information(Object);
extern Object clear_optimized_constants(void);
extern Object clone_compound_slot_value(Object,Object,Object);
extern Object clone_connections_for_block(Object,Object,Object);
extern Object clone_connections_of_block(Object,Object,Object,Object);
extern Object clone_connections_slot(Object,Object,Object,Object);
extern Object clone_edges_of_block(Object,Object);
extern Object clone_embedded_rule(Object,Object,Object);
extern Object clone_frame(int,...);
extern Object clone_icon_slot_group(Object,Object,Object,Object);
extern Object clone_series_of_values(Object,Object,Object,Object);
extern Object clone_slot_group_for_block_qm(Object,Object,Object,Object);
extern Object clone_subblocks_of_block(Object,Object,Object);
extern Object clone_text_slot_value(Object,Object,Object);
extern Object collect_subclasses(Object);
extern Object compile_file_command_for_slot(int,...);
extern Object compile_init_file_command_for_slot(int,...);
extern Object compile_init_file_or_file_command(Object,Object);
extern Object compute_directory_menu_items(Object,Object,Object,Object);
extern Object connect_to_external_foreign_image(Object);
extern Object connect_to_foreign_image(Object);
extern Object connection_specification_to_foreign_image_function(Object);
extern Object connections_for_class_slot_correct_format_p(void);
extern Object constant_queue_next(Object,Object);
extern Object convert_list_to_series_of_values(Object);
extern Object convert_series_of_values_to_list(int,...);
extern Object convert_text_string_to_text(Object);
extern Object convert_text_to_text_string(int,...);
extern Object convert_to_gensym_pathname(Object,Object,Object);
extern Object copy_for_slot_value(Object);
extern Object copy_gensym_pathname(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_pathname_contents(Object);
extern Object copy_symbol_name(int,...);
extern Object copy_table(int,...);
extern Object copy_text(Object);
extern Object copy_text_string(Object);
extern Object copy_text_string_with_case_conversion(Object,Object);
extern Object copy_tree_using_gensym_conses_1(Object);
extern Object count_and_fix_invalid_items(void);
extern Object delete_frame(Object);
extern Object delete_from_directory_of_names(Object,Object);
extern Object delete_menu(Object);
extern Object denote_slot_using_slot_value_conses(Object,Object);
extern Object determine_extreme_edges_of_block(Object);
extern Object disconnect_from_all_foreign_images(void);
extern Object disconnect_from_external_foreign_image(Object);
extern Object disconnect_from_foreign_image(Object);
extern Object display_editor_notification_1(Object);
extern Object do_pathname_component_conversion(Object,Object,Object);
extern Object do_pathname_component_conversion_if_necessary(Object,Object);
extern Object do_plist_checking(void);
extern Object do_plist_checking_again(void);
extern Object do_scc_command(int,...);
extern Object embedded_rule_qm_function(Object);
extern Object empty_kb_p(void);
extern Object enlarge_workspace_for_block_rectangle_if_necessary(Object,Object);
extern Object enter_dialog(int,...);
extern Object es_c_c(void);
extern Object execute_command_for_file_command(Object);
extern Object execute_command_for_init_file_command(Object);
extern Object execute_file_command(Object);
extern Object external_foreign_function_images_compute_choices(Object);
extern Object external_foreign_image_disconnection_spec_p(Object);
extern Object file_types_for_module(void);
extern Object find_differences_in_frames_if_any(int,...);
extern Object find_end_of_text(int,...);
extern Object finish_executing_file_command(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object force_process_drawing(void);
extern Object foreign_get_user_name(void);
extern Object frame_flags_revised_function(void);
extern Object g2_stream_close(Object);
extern Object g2_stream_directory_p(Object);
extern Object g2_stream_open_for_appending(Object,Object);
extern Object g2_stream_open_for_appending_handling_file_errors(Object,Object);
extern Object g2_stream_open_for_output(Object);
extern Object g2_stream_open_for_output_handling_file_errors(Object);
extern Object g2_stream_terpri(Object);
extern Object g2_write_stats(Object);
extern Object g2gl_variable_compilation_p(Object);
extern Object generate_output_only_table_spot(Object,Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_device_and_directory_namestring(int,...);
extern Object gensym_directory(int,...);
extern Object gensym_directory_and_above_namestring(int,...);
extern Object gensym_directory_and_above_namestring_as_text_string(int,...);
extern Object gensym_directory_as_file(Object);
extern Object gensym_directory_using_cache(int,...);
extern Object gensym_enough_namestring_as_text_string(int,...);
extern Object gensym_file_as_directory(Object);
extern Object gensym_file_namestring(int,...);
extern Object gensym_list_2(Object,Object);
extern Object gensym_make_pathname_with_copied_components(Object,Object,Object,Object,Object,Object,Object);
extern Object gensym_maximum_file_name_length(Object);
extern Object gensym_merge_pathnames_function(Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_namestring_as_text_string(int,...);
extern Object gensym_pathname(Object);
extern Object gensym_pathname_lessp(Object,Object);
extern Object gensym_pathnames_equal_enough_p(Object,Object);
extern Object gensym_probe_file(Object);
extern Object gensym_subdirectories(int,...);
extern Object gensym_wild_pathname_p(Object);
extern Object get_button_settings_for_file_command(Object,Object);
extern Object get_current_user_name(void);
extern Object get_current_workstation_or_ui_client_interface_if_any(void);
extern Object get_directory_for_kb_file_type(int,...);
extern Object get_directory_for_non_kb_file_type(Object,Object,Object,Object);
extern Object get_error_string_for_bad_starting_afterwards_option(Object);
extern Object get_error_string_for_bad_warmbooting_afterwards_option(Object);
extern Object get_error_string_for_file_name_cannot_be_parsed(Object);
extern Object get_error_string_for_illegal_wildcards_in_filename(Object);
extern Object get_file_command_check_box_value(Object,Object);
extern Object get_less_case_sensitive_gensym_pathname_given_directory(Object,Object);
extern Object get_less_case_sensitive_gensym_pathname_if_any(Object);
extern Object get_load_command_directory(Object,Object);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_module_block_is_in(Object);
extern Object get_or_make_default_kb_pathname(int,...);
extern Object get_pathname_for_file_command(Object,Object,Object,Object);
extern Object get_position_of_mouse(void);
extern Object get_primary_name_for_frame_if_any(Object);
extern Object get_recent_loaded_kb(Object);
extern Object get_slot_description(int,...);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_token_menu_class_per_category_overrides_for_file_command(void);
extern Object get_true_pathname_of_module_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_choice_for_directory_menu(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object handle_collected_updates_to_sensor_attributes(void);
extern Object handle_command(Object,Object);
extern Object handle_end_operation_for_kb_load_file_command(Object,Object);
extern Object handle_file_command(int,...);
extern Object handle_update_to_located_sensor_attribute(int,...);
extern Object icon_editor_fixed_p_function(void);
extern Object icp_list_3(Object,Object,Object);
extern Object import_text_string(int,...);
extern Object initialize_frame(Object);
extern Object initialize_slot_description_value(Object,Object,Object);
extern Object initialize_slots_of_frame_needing_evaluation(Object);
extern Object insert_text_string_in_text_being_edited(int,...);
extern Object intern_text_string(int,...);
extern Object lengthw(Object);
extern Object load_attribute_file(Object);
extern Object load_custom_software_file_if_ok(Object,Object);
extern Object load_or_merge_kb_from_file_command(Object,Object);
extern Object load_or_merge_kb_if_ok(int,...);
extern Object loading_version_3_or_earlier_kb_p(void);
extern Object loading_version_5_or_earlier_kb_p(void);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_and_set_up_kb_load_file_command(Object);
extern Object make_attributes_table(int,...);
extern Object make_button(int,...);
extern Object make_command_frame(int,...);
extern Object make_default_file_type(Object);
extern Object make_default_pathname(Object);
extern Object make_empty_gensym_pathname(void);
extern Object make_first_time_default_pathname(Object);
extern Object make_frame_without_computed_initializations(Object,Object,Object);
extern Object make_kb_name(Object);
extern Object make_load_command_items_and_add_to_workspace(Object,Object,Object);
extern Object make_lost_spaces_text_element(Object);
extern Object make_menu_description(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_menu_named_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_or_reformat_ruling_for_meter(Object,Object);
extern Object make_output_only_table_spot_1(void);
extern Object make_permanent_subseries_of_values_64_vector_internal(void);
extern Object make_slot_value_list_1(Object);
extern Object make_subseries_of_values(void);
extern Object make_text_box(Object);
extern Object make_thread_array(Object);
extern Object maybe_modify_confirmation_query_and_default_pathname(Object,Object,Object);
extern Object maybe_supply_home_to_possible_unix_pathname(Object);
extern Object memq_function(Object,Object);
extern Object merge_series_of_pathnames(Object);
extern Object module_exists_p(Object);
extern Object move_block(Object,Object,Object);
extern Object move_file_command_items_if_necessary(Object,Object,Object);
extern Object move_or_delete_from_cursor(int,...);
extern Object mutate_global_property(Object,Object,Object);
extern Object namestring_is_xml_file_p(Object);
extern Object need_to_normalize_message_properties_p_function(void);
extern Object note_change_to_block_1(Object,Object);
extern Object notify_user(int,...);
extern Object nstring_downcasew(Object);
extern Object old_format_for_default_overrides_p_function(void);
extern Object on_sl_off_switch_on_p(Object);
extern Object out_subseries_of_values_64_vectors(void);
extern Object parse_text_for_slot(int,...);
extern Object path_cons_1(Object,Object);
extern Object pathname_of_a_connected_foreign_image_p(Object);
extern Object pathnames_in_directory_compute_choices(Object,Object,Object,Object,Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object post_directory_menu(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object post_menu_function(Object,Object,Object,Object,Object,Object,Object);
extern Object probe_for_kb_named_by_text_string(Object);
extern Object probe_for_kb_pathname(Object);
extern Object push_optimized_constant(Object);
extern Object put_box_translation_and_text(Object,Object,Object);
extern Object put_rule_byte_code_body(Object,Object,Object);
extern Object read_kb_or_group_thereof(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object reclaim_directory_search_cache(Object);
extern Object reclaim_file_command_directory_search_cache_qm_value(Object,Object);
extern Object reclaim_file_system_directory_search_cache(void);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_pathnames_under_current_directory_qm_value(Object,Object);
extern Object reclaim_path_list_1(Object);
extern Object reclaim_path_list_of_gensym_pathnames(Object);
extern Object reclaim_pathname_or_string(Object);
extern Object reclaim_recent_loaded_kbs(Object);
extern Object reclaim_series_of_values(Object);
extern Object reclaim_series_of_values_and_values(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_subseries_of_values(Object);
extern Object reclaim_subseries_of_values_and_values(Object);
extern Object reclaim_text_string(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_vector_pool_cons_pool(void);
extern Object resolve_directory_sl_file_ambiguities_in_kb_load_file_command(Object,Object);
extern Object rule_byte_code_body_function(Object);
extern Object save_kb(int,...);
extern Object save_module_of_kb(int,...);
extern Object schedule_task_to_invoke_existential_rules(Object,Object);
extern Object seize_file_system_directory_search_cache(void);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_up_current_directory_information_text_based_on_other_slots(Object);
extern Object set_up_file_and_directory_name_directories(Object);
extern Object set_up_load_command_directory_information(int,...);
extern Object shift_block(Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_equal_p(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object snapshot_memory_levels(void);
extern Object sort_list(Object,Object,Object);
extern Object spot_generator_for_file_command_info_table_format(Object,Object);
extern Object string_eq_w(Object,Object);
extern Object string_equalw(Object,Object);
extern Object string_lesspw(Object,Object);
extern Object stringw(Object);
extern Object subseries_of_values_64_vector_memory_usage(void);
extern Object symbol_name_text_string(Object);
extern Object symbolic_file_type_for_file_command_qm(Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object text_string_right_trim(Object,Object);
extern Object text_string_search(Object,Object,Object,Object);
extern Object text_string_substring(Object,Object,Object);
extern Object text_string_trim(Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object token_from_text_string(Object,Object,Object);
extern Object transform_load_or_merge_options_if_appropriate(Object,Object,Object);
extern Object twrite_foreign_image_connection_spec(Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object update_attribute_tables(int,...);
extern Object update_frame_status(Object,Object,Object);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_name_directories_per_file_command(Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations(Object);
extern Object workspace_background_images_are_centered_p(void);
extern Object write_directory_contents_statistics_qm_from_slot(Object,Object);
extern Object write_file_command_directory_namestring_as_text_string_qm_from_slot(Object,Object);
extern Object write_g2_stats(Object);
extern Object write_g2_stats_header(Object);

#else

extern Object abandon_load_or_merge_kb_if_ok();
extern Object abort_current_workstation_context();
extern Object add_class_to_environment();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_items_to_edit_workspace_for_kb_load_file_command();
extern Object add_recent_loaded_kb();
extern Object add_source_code_control_grammar();
extern Object add_subworkspace();
extern Object add_to_block();
extern Object add_to_directory_of_names();
extern Object add_to_workspace();
extern Object allocate_byte_vector_16();
extern Object assq_function();
extern Object bad_4_0_beta_magnifications_in_text_boxes_removed_p_function();
extern Object bytes_per_typed_simple_array();
extern Object change_edges_of_block();
extern Object change_on_sl_off_switch();
extern Object change_slot_value();
extern Object check_file_command_for_slot();
extern Object check_if_superior_classes_are_defined();
extern Object choose_font_format_per_fonts_table();
extern Object cleanup_for_kb_load_file_command();
extern Object clear_file_and_directory_name_directories();
extern Object clear_load_command_directory_information();
extern Object clear_optimized_constants();
extern Object clone_compound_slot_value();
extern Object clone_connections_for_block();
extern Object clone_connections_of_block();
extern Object clone_connections_slot();
extern Object clone_edges_of_block();
extern Object clone_embedded_rule();
extern Object clone_frame();
extern Object clone_icon_slot_group();
extern Object clone_series_of_values();
extern Object clone_slot_group_for_block_qm();
extern Object clone_subblocks_of_block();
extern Object clone_text_slot_value();
extern Object collect_subclasses();
extern Object compile_file_command_for_slot();
extern Object compile_init_file_command_for_slot();
extern Object compile_init_file_or_file_command();
extern Object compute_directory_menu_items();
extern Object connect_to_external_foreign_image();
extern Object connect_to_foreign_image();
extern Object connection_specification_to_foreign_image_function();
extern Object connections_for_class_slot_correct_format_p();
extern Object constant_queue_next();
extern Object convert_list_to_series_of_values();
extern Object convert_series_of_values_to_list();
extern Object convert_text_string_to_text();
extern Object convert_text_to_text_string();
extern Object convert_to_gensym_pathname();
extern Object copy_for_slot_value();
extern Object copy_gensym_pathname();
extern Object copy_out_current_wide_string();
extern Object copy_pathname_contents();
extern Object copy_symbol_name();
extern Object copy_table();
extern Object copy_text();
extern Object copy_text_string();
extern Object copy_text_string_with_case_conversion();
extern Object copy_tree_using_gensym_conses_1();
extern Object count_and_fix_invalid_items();
extern Object delete_frame();
extern Object delete_from_directory_of_names();
extern Object delete_menu();
extern Object denote_slot_using_slot_value_conses();
extern Object determine_extreme_edges_of_block();
extern Object disconnect_from_all_foreign_images();
extern Object disconnect_from_external_foreign_image();
extern Object disconnect_from_foreign_image();
extern Object display_editor_notification_1();
extern Object do_pathname_component_conversion();
extern Object do_pathname_component_conversion_if_necessary();
extern Object do_plist_checking();
extern Object do_plist_checking_again();
extern Object do_scc_command();
extern Object embedded_rule_qm_function();
extern Object empty_kb_p();
extern Object enlarge_workspace_for_block_rectangle_if_necessary();
extern Object enter_dialog();
extern Object es_c_c();
extern Object execute_command_for_file_command();
extern Object execute_command_for_init_file_command();
extern Object execute_file_command();
extern Object external_foreign_function_images_compute_choices();
extern Object external_foreign_image_disconnection_spec_p();
extern Object file_types_for_module();
extern Object find_differences_in_frames_if_any();
extern Object find_end_of_text();
extern Object finish_executing_file_command();
extern Object force_process_drawing();
extern Object foreign_get_user_name();
extern Object frame_flags_revised_function();
extern Object g2_stream_close();
extern Object g2_stream_directory_p();
extern Object g2_stream_open_for_appending();
extern Object g2_stream_open_for_appending_handling_file_errors();
extern Object g2_stream_open_for_output();
extern Object g2_stream_open_for_output_handling_file_errors();
extern Object g2_stream_terpri();
extern Object g2_write_stats();
extern Object g2gl_variable_compilation_p();
extern Object generate_output_only_table_spot();
extern Object gensym_cons_1();
extern Object gensym_device_and_directory_namestring();
extern Object gensym_directory();
extern Object gensym_directory_and_above_namestring();
extern Object gensym_directory_and_above_namestring_as_text_string();
extern Object gensym_directory_as_file();
extern Object gensym_directory_using_cache();
extern Object gensym_enough_namestring_as_text_string();
extern Object gensym_file_as_directory();
extern Object gensym_file_namestring();
extern Object gensym_list_2();
extern Object gensym_make_pathname_with_copied_components();
extern Object gensym_maximum_file_name_length();
extern Object gensym_merge_pathnames_function();
extern Object gensym_namestring();
extern Object gensym_namestring_as_text_string();
extern Object gensym_pathname();
extern Object gensym_pathname_lessp();
extern Object gensym_pathnames_equal_enough_p();
extern Object gensym_probe_file();
extern Object gensym_subdirectories();
extern Object gensym_wild_pathname_p();
extern Object get_button_settings_for_file_command();
extern Object get_current_user_name();
extern Object get_current_workstation_or_ui_client_interface_if_any();
extern Object get_directory_for_kb_file_type();
extern Object get_directory_for_non_kb_file_type();
extern Object get_error_string_for_bad_starting_afterwards_option();
extern Object get_error_string_for_bad_warmbooting_afterwards_option();
extern Object get_error_string_for_file_name_cannot_be_parsed();
extern Object get_error_string_for_illegal_wildcards_in_filename();
extern Object get_file_command_check_box_value();
extern Object get_less_case_sensitive_gensym_pathname_given_directory();
extern Object get_less_case_sensitive_gensym_pathname_if_any();
extern Object get_load_command_directory();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_module_block_is_in();
extern Object get_or_make_default_kb_pathname();
extern Object get_pathname_for_file_command();
extern Object get_position_of_mouse();
extern Object get_primary_name_for_frame_if_any();
extern Object get_recent_loaded_kb();
extern Object get_slot_description();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_function();
extern Object get_token_menu_class_per_category_overrides_for_file_command();
extern Object get_true_pathname_of_module_if_any();
extern Object getfq_function_no_default();
extern Object handle_choice_for_directory_menu();
extern Object handle_collected_updates_to_sensor_attributes();
extern Object handle_command();
extern Object handle_end_operation_for_kb_load_file_command();
extern Object handle_file_command();
extern Object handle_update_to_located_sensor_attribute();
extern Object icon_editor_fixed_p_function();
extern Object icp_list_3();
extern Object import_text_string();
extern Object initialize_frame();
extern Object initialize_slot_description_value();
extern Object initialize_slots_of_frame_needing_evaluation();
extern Object insert_text_string_in_text_being_edited();
extern Object intern_text_string();
extern Object lengthw();
extern Object load_attribute_file();
extern Object load_custom_software_file_if_ok();
extern Object load_or_merge_kb_from_file_command();
extern Object load_or_merge_kb_if_ok();
extern Object loading_version_3_or_earlier_kb_p();
extern Object loading_version_5_or_earlier_kb_p();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_and_set_up_kb_load_file_command();
extern Object make_attributes_table();
extern Object make_button();
extern Object make_command_frame();
extern Object make_default_file_type();
extern Object make_default_pathname();
extern Object make_empty_gensym_pathname();
extern Object make_first_time_default_pathname();
extern Object make_frame_without_computed_initializations();
extern Object make_kb_name();
extern Object make_load_command_items_and_add_to_workspace();
extern Object make_lost_spaces_text_element();
extern Object make_menu_description();
extern Object make_menu_named_function();
extern Object make_or_reformat_ruling_for_meter();
extern Object make_output_only_table_spot_1();
extern Object make_permanent_subseries_of_values_64_vector_internal();
extern Object make_slot_value_list_1();
extern Object make_subseries_of_values();
extern Object make_text_box();
extern Object make_thread_array();
extern Object maybe_modify_confirmation_query_and_default_pathname();
extern Object maybe_supply_home_to_possible_unix_pathname();
extern Object memq_function();
extern Object merge_series_of_pathnames();
extern Object module_exists_p();
extern Object move_block();
extern Object move_file_command_items_if_necessary();
extern Object move_or_delete_from_cursor();
extern Object mutate_global_property();
extern Object namestring_is_xml_file_p();
extern Object need_to_normalize_message_properties_p_function();
extern Object note_change_to_block_1();
extern Object notify_user();
extern Object nstring_downcasew();
extern Object old_format_for_default_overrides_p_function();
extern Object on_sl_off_switch_on_p();
extern Object out_subseries_of_values_64_vectors();
extern Object parse_text_for_slot();
extern Object path_cons_1();
extern Object pathname_of_a_connected_foreign_image_p();
extern Object pathnames_in_directory_compute_choices();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object post_directory_menu();
extern Object post_menu_function();
extern Object probe_for_kb_named_by_text_string();
extern Object probe_for_kb_pathname();
extern Object push_optimized_constant();
extern Object put_box_translation_and_text();
extern Object put_rule_byte_code_body();
extern Object read_kb_or_group_thereof();
extern Object reclaim_directory_search_cache();
extern Object reclaim_file_command_directory_search_cache_qm_value();
extern Object reclaim_file_system_directory_search_cache();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_pathnames_under_current_directory_qm_value();
extern Object reclaim_path_list_1();
extern Object reclaim_path_list_of_gensym_pathnames();
extern Object reclaim_pathname_or_string();
extern Object reclaim_recent_loaded_kbs();
extern Object reclaim_series_of_values();
extern Object reclaim_series_of_values_and_values();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_subseries_of_values();
extern Object reclaim_subseries_of_values_and_values();
extern Object reclaim_text_string();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_vector_pool_cons_pool();
extern Object resolve_directory_sl_file_ambiguities_in_kb_load_file_command();
extern Object rule_byte_code_body_function();
extern Object save_kb();
extern Object save_module_of_kb();
extern Object schedule_task_to_invoke_existential_rules();
extern Object seize_file_system_directory_search_cache();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_up_current_directory_information_text_based_on_other_slots();
extern Object set_up_file_and_directory_name_directories();
extern Object set_up_load_command_directory_information();
extern Object shift_block();
extern Object slot_value_cons_1();
extern Object slot_value_equal_p();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object slot_value_list_4();
extern Object snapshot_memory_levels();
extern Object sort_list();
extern Object spot_generator_for_file_command_info_table_format();
extern Object string_eq_w();
extern Object string_equalw();
extern Object string_lesspw();
extern Object stringw();
extern Object subseries_of_values_64_vector_memory_usage();
extern Object symbol_name_text_string();
extern Object symbolic_file_type_for_file_command_qm();
extern Object text_string_length();
extern Object text_string_p();
extern Object text_string_right_trim();
extern Object text_string_search();
extern Object text_string_substring();
extern Object text_string_trim();
extern Object tformat();
extern Object tformat_text_string();
extern Object token_from_text_string();
extern Object transform_load_or_merge_options_if_appropriate();
extern Object twrite_foreign_image_connection_spec();
extern Object unicode_lowercase_if_uppercase();
extern Object update_attribute_tables();
extern Object update_frame_status();
extern Object update_images_of_block();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_name_directories_per_file_command();
extern Object update_object_pool_meters_list();
extern Object update_representations();
extern Object workspace_background_images_are_centered_p();
extern Object write_directory_contents_statistics_qm_from_slot();
extern Object write_file_command_directory_namestring_as_text_string_qm_from_slot();
extern Object write_g2_stats();
extern Object write_g2_stats_header();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_directory_namestrings_in_directory_of_names, Qall_directory_namestrings_in_directory_of_names);
DECLARE_VARIABLE_WITH_SYMBOL(All_external_foreign_function_images_qm, Qall_external_foreign_function_images_qm);
DECLARE_VARIABLE_WITH_SYMBOL(All_file_namestrings_in_directory_of_names, Qall_file_namestrings_in_directory_of_names);
DECLARE_VARIABLE_WITH_SYMBOL(Attempting_save_via_system_procedure_qm, Qattempting_save_via_system_procedure_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Automatically_resolve_conflicts_by_default, Qautomatically_resolve_conflicts_by_default);
DECLARE_VARIABLE_WITH_SYMBOL(Autostart_after_doing_init_file_qm, Qautostart_after_doing_init_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Autostart_reason_in_init_file_qm, Qautostart_reason_in_init_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Available_subseries_of_values_64_vectors, Qavailable_subseries_of_values_64_vectors);
extern Object Available_subseries_of_values_64_vectors_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Break_if_name_inconsistency_qm, Qbreak_if_name_inconsistency_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_unknown_error_string_with_code_qm, Qcached_unknown_error_string_with_code_qm);
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Clear_text_grammar_rules_added_p, Qclear_text_grammar_rules_added_p);
DECLARE_VARIABLE_WITH_SYMBOL(Collected_updates_to_sensor_attributes, Qcollected_updates_to_sensor_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Collecting_updates_to_sensor_attributes_p, Qcollecting_updates_to_sensor_attributes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
DECLARE_VARIABLE_WITH_SYMBOL(Compiled_code_grammar_rules_added_p, Qcompiled_code_grammar_rules_added_p);
DECLARE_VARIABLE_WITH_SYMBOL(Complete_kb_name_qm, Qcomplete_kb_name_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Convert_file_strings_to_uppercase_p, Qconvert_file_strings_to_uppercase_p);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_subseries_of_values_64_vectors, Qcount_of_subseries_of_values_64_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_attribute_file_pathname_qm, Qcurrent_attribute_file_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreign_image_pathname_qm, Qcurrent_foreign_image_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_pathname_qm, Qcurrent_kb_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_statistics_file_pathname_qm, Qcurrent_statistics_file_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Default_kb_pathname_qm, Qdefault_kb_pathname_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Defaults_namestring_for_directory_of_names_qm, Qdefaults_namestring_for_directory_of_names_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Dependent_frame_class_description, Qdependent_frame_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Do_g2_init_file_qm, Qdo_g2_init_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Doing_g2_init_file_p, Qdoing_g2_init_file_p);
extern Object Ellipsis_text_string;
DECLARE_VARIABLE_WITH_SYMBOL(Entity_class_description, Qentity_class_description);
extern Object Evaluation_true_value;
extern Object File_name_punctuation_alist;
extern Object File_operation_succeeded_code;
DECLARE_VARIABLE_WITH_SYMBOL(File_punctuation_mark_grammar_rules, Qfile_punctuation_mark_grammar_rules);
DECLARE_VARIABLE_WITH_SYMBOL(File_system_directory_search_cache, Qfile_system_directory_search_cache);
DECLARE_VARIABLE_WITH_SYMBOL(File_system_directory_search_cache_active_p, Qfile_system_directory_search_cache_active_p);
DECLARE_VARIABLE_WITH_SYMBOL(File_system_directory_search_cache_wildcard_string, Qfile_system_directory_search_cache_wildcard_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Format_frame_class_description, Qformat_frame_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_stream_error_string_table, Qg2_stream_error_string_table);
#define G2_version_2011_kb_flags FIX((SI_Long)281L)
#define G2_version_2015_beta_kb_flags FIX((SI_Long)282L)
#define G2_version_6_general_kb_flags FIX((SI_Long)270L)
#define G2_version_7_beta_0_kb_flags FIX((SI_Long)274L)
#define G2_version_81r0_kb_flags FIX((SI_Long)278L)
#define G2_version_82r0_kb_flags FIX((SI_Long)279L)
#define G2_version_8_1_alpha_0_kb_flags FIX((SI_Long)276L)
#define G2_version_8_1_beta_0_kb_flags FIX((SI_Long)277L)
#define G2_version_8_3_alpha_0_kb_flags FIX((SI_Long)280L)
#define G2_version_8_beta_0_kb_flags FIX((SI_Long)275L)
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_for_save_via_system_procedure_qm, Qg2_window_for_save_via_system_procedure_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Generic_action_button_class_description, Qgeneric_action_button_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_file_error_occurred_p, Qgensym_file_error_occurred_p);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_updating_module_related_frame_notes_for_all_workspaces_qm, Qinhibit_updating_module_related_frame_notes_for_all_workspaces_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Inner_abort_level_tag, Qinner_abort_level_tag);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_handling_gensym_file_errors_scope_p, Qinside_handling_gensym_file_errors_scope_p);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Internal_status_of_most_recent_file_operation, Qinternal_status_of_most_recent_file_operation);
#define Kb_flag_when_specific_procedure_method_died FIX((SI_Long)245L)
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags, Qkb_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags_for_saving, Qkb_flags_for_saving);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags_from_last_kb_read, Qkb_flags_from_last_kb_read);
extern Object Kb_flags_of_software;
#define Kb_format_revision_for_kb_restrictions_reclassification FIX((SI_Long)243L)
DECLARE_VARIABLE_WITH_SYMBOL(Kb_uses_crlf_p, Qkb_uses_crlf_p);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
#define Last_kb_flags_saved_with_item_reference_parameters FIX((SI_Long)272L)
DECLARE_VARIABLE_WITH_SYMBOL(Local_file_system, Qlocal_file_system);
DECLARE_VARIABLE_WITH_SYMBOL(Local_filename_parser, Qlocal_filename_parser);
DECLARE_VARIABLE_WITH_SYMBOL(Local_namestring_generator, Qlocal_namestring_generator);
DECLARE_VARIABLE_WITH_SYMBOL(Match_regular_expression_for_g2_stream_directory_hook, Qmatch_regular_expression_for_g2_stream_directory_hook);
DECLARE_VARIABLE_WITH_SYMBOL(Meter_class_description, Qmeter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Method_class_description, Qmethod_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Module_information, Qmodule_information);
DECLARE_VARIABLE_WITH_SYMBOL(Name_box_class_description, Qname_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Need_to_check_plist_p, Qneed_to_check_plist_p);
DECLARE_VARIABLE_WITH_SYMBOL(New_saved_kb_format_p, Qnew_saved_kb_format_p);
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Plist_has_been_checked_p, Qplist_has_been_checked_p);
#define Plus_max_cached_recent_loaded_kbs_plus FIX((SI_Long)10L)
DECLARE_VARIABLE_WITH_SYMBOL(Process_specific_system_pathname, Qprocess_specific_system_pathname);
DECLARE_VARIABLE_WITH_SYMBOL(Recent_loaded_kbs, Qrecent_loaded_kbs);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Source_code_control_grammar_is_present_p, Qsource_code_control_grammar_is_present_p);
DECLARE_VARIABLE_WITH_SYMBOL(Source_code_control_support_enabled_p, Qsource_code_control_support_enabled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Superior_frame_being_cloned_qm, Qsuperior_frame_being_cloned_qm);
DECLARE_VARIABLE_WITH_SYMBOL(System_quality_from_last_kb_read, Qsystem_quality_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_revision_from_last_kb_read, Qsystem_revision_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(System_statistics_writers, Qsystem_statistics_writers);
DECLARE_VARIABLE_WITH_SYMBOL(System_version_from_last_kb_read, Qsystem_version_from_last_kb_read);
DECLARE_VARIABLE_WITH_SYMBOL(Table_class_description, Qtable_class_description);
extern Object Token_menu_class_per_category_overrides;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
extern Object Unknown_error_during_file_op_with_code_message;
DECLARE_VARIABLE_WITH_SYMBOL(Update_before_loading_by_default, Qupdate_before_loading_by_default);
DECLARE_VARIABLE_WITH_SYMBOL(User_menu_choice_class_description, Quser_menu_choice_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Vms_directory_filenames_can_dangle_p, Qvms_directory_filenames_can_dangle_p);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_qm, Qwarmbooting_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Warmbooting_with_catch_up_qm, Qwarmbooting_with_catch_up_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
