/* lspimg.h -- Header File for lspimg.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kelement_type;
extern Object Qerror;
extern Object Qread;
extern Object Qunsigned_byte;
extern Object Qvector;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_icp_message_handler(Object,Object);
extern Object align_image_scan_line_1(Object,Object,Object);
extern Object allocate_byte_vector(Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_custom_palette(Object,Object,Object);
extern Object allocate_extended_color_palette(Object);
extern Object allocate_extended_gray_palette(Object);
extern Object allocate_extended_gray_palette_1(Object,Object);
extern Object allocate_just_tiled_raster(Object,Object,Object,Object,Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_new_color_for_gensym_window(Object,Object,Object,Object);
extern Object allocate_shredded_raster(int,...);
extern Object allocate_stored_raster_1(Object,Object,Object,Object,Object);
extern Object assign_corresponding_icp_object_index(Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object bytes_allocated_for_image_tiles(void);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_unsigned_byte_8_simple_array(Object);
extern Object c_image_stream_error(Object,Object,Object);
extern Object c_open_image_stream(Object,Object,Object);
extern Object change_image_palette_of_local_window(Object,Object,Object);
extern Object change_image_palette_of_window(Object,Object,Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object clear_all_extended_colors_for_window(Object);
extern Object clear_all_image_renderings_for_window(Object);
extern Object clear_image_renderings_for_image_data(int,...);
extern Object clear_optimized_constants(void);
extern Object compute_alignment(Object);
extern Object compute_bytes_per_scan_line(Object,Object);
extern Object compute_clipped_region_of_rendering_to_draw(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compute_oriented_bounds_of_icon_in_image_coordinates(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compute_oriented_destination_for_image(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compute_percentage(Object,Object);
extern Object compute_rgbquads(Object,Object,Object,Object);
extern Object copy_foreign_string_arg_if_appropriate(Object);
extern Object copy_null_terminated_string_as_gensym_string(Object);
extern Object copy_null_terminated_string_as_text_string(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object create_gray_map_from_color_map(Object);
extern Object create_image_rendering(Object,Object,Object,Object,Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object draw_hollow_rectangle_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_icon_background_image_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_icon_background_image_on_window_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_data_on_local_scratchpad(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_1_to_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_24_to_24(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_8_to_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_8_to_8(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_8_to_8_for_workspace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_8_to_truecolor(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_8_to_truecolor_for_workspace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_tile_for_workspace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_tile_on_printer(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_mask_on_tile(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_mask_on_tile_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_missing_icon_background_image(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_missing_image(int,...);
extern Object draw_missing_image_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_tiled_image_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_valid_image_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object draw_wide_polyline_on_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object emit_icp_read_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object emit_icp_write_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object end_icp_message_group(void);
extern Object enlarge_index_space(Object,Object);
extern Object ensure_image_data_cache(Object);
extern Object ensure_image_data_pixels(Object);
extern Object ensure_image_rendering_color_map(Object);
extern Object ensure_image_tile(Object,Object,Object,Object,Object);
extern Object ensure_shredded_raster_buffer(Object,Object);
extern Object ensure_singleton_image_pixmap(Object,Object);
extern Object establish_new_object_index_for_image_data(int,...);
extern Object file_exists_p(Object);
extern Object find_image_rendering(Object,Object,Object,Object,Object,Object);
extern Object find_nearest_color(Object,Object,Object,Object,Object);
extern Object find_or_create_image_rendering(Object,Object,Object,Object,Object,Object);
extern Object find_suitable_image_tile_to_reuse(Object,Object,Object,Object,Object);
extern Object finished_transmitting_image_data_p(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object gensym_probe_file(Object);
extern Object get_icp_object_index_for_image_data(Object,Object);
extern Object get_images_error_message(Object);
extern Object get_remote_icp_version_info_value(Object,Object,Object);
extern Object get_x11_pixel_value_from_rgb(Object,Object,Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_icp_begin_making_image_data(void);
extern Object handle_icp_begin_making_image_data__body(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object handle_icp_change_image_palette_of_window(void);
extern Object handle_icp_image_data_chunk(void);
extern Object handle_icp_image_data_chunk__body(Object,Object,Object);
extern Object handle_icp_paint_icon_background_image_in_current_window(void);
extern Object handle_icp_paint_image_in_current_scratchpad_raster(void);
extern Object handle_icp_paint_image_in_current_window(void);
extern Object icp_connection_open_p(Object);
extern Object icp_error_internal(Object,Object,Object,Object,Object);
extern Object icp_message_functions_icp_prologue(Object);
extern Object icp_port_shutdown_for_image_data(Object,Object);
extern Object identity_color_map(void);
extern Object image_data_and_raster_dimensional_match_p(Object,Object);
extern Object image_data_complete_p(Object);
extern Object image_data_has_been_transmitted_p(Object);
extern Object image_data_is_gray_scale_p(Object);
extern Object image_data_next_scan_to_send(Object);
extern Object image_data_structure_memory_usage(void);
extern Object image_palette_is_gray_p(Object);
extern Object image_rendering_last_tile_height(Object);
extern Object image_rendering_last_tile_width(Object);
extern Object image_rendering_structure_memory_usage(void);
extern Object image_stream_format(Object);
extern Object image_tile_structure_memory_usage(void);
extern Object images_too_many_buffered_icp_bytes_p(void);
extern Object initialize_icp_object_type(Object,Object,Object,Object);
extern Object initialize_icp_object_type_compile(Object,Object,Object);
extern Object install_lru_element_in_queue(Object,Object);
extern Object instantaneous_icp_reader_byte_count(void);
extern Object instantaneous_icp_writer_byte_count(void);
extern Object invalidate_all_tiles_in_tiled_raster(Object);
extern Object large_byte_vector(void);
extern Object load_and_initialize_type_description(Object,Object);
extern Object make_corresponding_icp_gensym_window(Object);
extern Object make_corresponding_icp_image_data(Object);
extern Object make_corresponding_icp_symbol(Object);
extern Object make_gensym_list_1(Object);
extern Object make_image_data(int,...);
extern Object make_image_data_1_1(void);
extern Object make_image_rendering_1_1(void);
extern Object make_image_tile(Object,Object,Object,Object,Object);
extern Object make_image_tile_1_1(void);
extern Object make_permanent_image_data_structure_internal(void);
extern Object make_permanent_image_rendering_structure_internal(void);
extern Object make_permanent_image_tile_structure_internal(void);
extern Object make_permanent_shredded_raster_structure_internal(void);
extern Object make_shredded_raster_1_1(void);
extern Object make_thread_array(Object);
extern Object map_to_closest_color_value(Object,Object);
extern Object map_to_color_value(Object);
extern Object maximum_bytes_for_image_tiles(void);
extern Object maybe_restart_icp_window_update(Object,Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object note_image_progress(Object,Object,Object,Object,Object);
extern Object note_progress_on_window(Object,Object,Object);
extern Object notify_user_at_console(int,...);
extern Object obtain_simple_gensym_string(Object);
extern Object outstanding_image_data_count(void);
extern Object outstanding_image_rendering_count(void);
extern Object outstanding_image_tile_count(void);
extern Object outstanding_shredded_raster_count(void);
extern Object paint_icon_background_image_in_current_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object paint_image_in_current_scratchpad_raster(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object paint_image_in_current_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object paint_or_tile_image_in_current_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object paint_solid_rectangle_in_current_scratchpad_raster(Object,Object,Object,Object,Object);
extern Object printing_window_p(Object);
extern Object push_optimized_constant(Object);
extern Object read_icp_array_of_unsigned_integers(void);
extern Object read_icp_array_of_unsigned_integers_given_length(Object);
extern Object read_icp_array_of_unsigned_integers_qm(void);
extern Object read_icp_bits(Object);
extern Object read_icp_byte(void);
extern Object read_icp_byte_vector(void);
extern Object read_icp_compressed_image_data_chunk(void);
extern Object read_icp_corresponding_object_index(void);
extern Object read_icp_filtered_text_string(void);
extern Object read_icp_fixnum(void);
extern Object read_icp_image_data_chunk_byte_vector(void);
extern Object read_icp_integer(void);
extern Object read_icp_transparent_color_index(void);
extern Object read_icp_unsigned_integer(void);
extern Object read_icp_unsigned_integer_qm(void);
extern Object read_image_data(int,...);
extern Object read_image_data_header(Object);
extern Object read_raster(int,...);
extern Object really_large_byte_vector(void);
extern Object reclaim_byte_vector(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_icp_object_map(Object,Object,Object);
extern Object reclaim_icp_object_map_for_image_data(Object);
extern Object reclaim_icp_port_entry(Object,Object,Object,Object);
extern Object reclaim_icp_port_entry_for_image_data(Object,Object);
extern Object reclaim_image_data(Object);
extern Object reclaim_image_data_1_1(Object);
extern Object reclaim_image_rendering(Object);
extern Object reclaim_image_rendering_1_1(Object);
extern Object reclaim_image_rendering_color_map(Object);
extern Object reclaim_image_rendering_tiled_raster(Object);
extern Object reclaim_image_tile(Object);
extern Object reclaim_image_tile_1_1(Object);
extern Object reclaim_managed_array(Object);
extern Object reclaim_shredded_raster(Object);
extern Object reclaim_shredded_raster_1_1(Object);
extern Object reclaim_stored_raster_1(Object,Object,Object,Object,Object,Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_tiled_raster(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remote_side_supports_transparent_color_index_p(Object);
extern Object restart_icp_message_group(void);
extern Object resumable_icp_pop(void);
extern Object resumable_icp_pop_list_if_end_marker(void);
extern Object resumable_icp_push(Object);
extern Object reuse_image_tile(Object,Object,Object,Object);
extern Object rotated_by_90_p(Object);
extern Object scalef_function(Object,Object);
extern Object send_all_image_data(Object);
extern Object send_icp_begin_making_image_data(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_image_data_chunk(Object,Object,Object);
extern Object send_some_image_data(Object,Object,Object);
extern Object server_and_client_share_file_system_p(Object);
extern Object set_access_form_for_image_data(Object,Object);
extern Object set_icp_object_index_for_image_data(Object,Object,Object);
extern Object set_image_data_next_scan_to_send(Object,Object);
extern Object set_maximum_bytes_for_image_tiles(Object);
extern Object shredded_raster_p_function(Object);
extern Object shredded_raster_structure_memory_usage(void);
extern Object shredded_raster_to_background_tile(Object);
extern Object slowly_draw_image_data_on_current_scratchpad(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object start_writing_icp_message(Object);
extern Object store_corresponding_icp_object(Object,Object);
extern Object stored_raster_in_regular_pool_qm(Object,Object,Object,Object);
extern Object sync_graphics_on_current_window(void);
extern Object synchronize_icp_on_window_with_drawing(Object,Object,Object,Object,Object);
extern Object telewindows_can_read_image_data_locally_p(Object,Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object trace_images(void);
extern Object trace_images_print(Object,Object,Object);
extern Object untrace_images(void);
extern Object update_object_pool_meters_list(Object);
extern Object window_supports_painting_this_image_data(Object,Object);
extern Object write_icp_array_of_unsigned_integers(Object);
extern Object write_icp_array_of_unsigned_integers_given_length(Object,Object);
extern Object write_icp_array_of_unsigned_integers_qm(Object);
extern Object write_icp_bits(Object,Object);
extern Object write_icp_bits_flush(void);
extern Object write_icp_byte(Object);
extern Object write_icp_byte_vector(Object);
extern Object write_icp_compressed_image_data_chunk(Object);
extern Object write_icp_corresponding_object_index(Object);
extern Object write_icp_filtered_text_string(Object);
extern Object write_icp_fixnum(Object);
extern Object write_icp_image_data_chunk_byte_vector(Object);
extern Object write_icp_integer(Object);
extern Object write_icp_maybe_suspend(void);
extern Object write_icp_transparent_color_index(Object);
extern Object write_icp_unsigned_integer(Object);
extern Object write_icp_unsigned_integer_qm(Object);

#else

extern Object add_icp_message_handler();
extern Object align_image_scan_line_1();
extern Object allocate_byte_vector();
extern Object allocate_byte_vector_16();
extern Object allocate_custom_palette();
extern Object allocate_extended_color_palette();
extern Object allocate_extended_gray_palette();
extern Object allocate_extended_gray_palette_1();
extern Object allocate_just_tiled_raster();
extern Object allocate_managed_array();
extern Object allocate_new_color_for_gensym_window();
extern Object allocate_shredded_raster();
extern Object allocate_stored_raster_1();
extern Object assign_corresponding_icp_object_index();
extern Object assq_function();
extern Object bytes_allocated_for_image_tiles();
extern Object bytes_per_simple_vector();
extern Object bytes_per_unsigned_byte_8_simple_array();
extern Object c_image_stream_error();
extern Object c_open_image_stream();
extern Object change_image_palette_of_local_window();
extern Object change_image_palette_of_window();
extern Object chestnut_floorf_function();
extern Object chestnut_modf_function();
extern Object clear_all_extended_colors_for_window();
extern Object clear_all_image_renderings_for_window();
extern Object clear_image_renderings_for_image_data();
extern Object clear_optimized_constants();
extern Object compute_alignment();
extern Object compute_bytes_per_scan_line();
extern Object compute_clipped_region_of_rendering_to_draw();
extern Object compute_oriented_bounds_of_icon_in_image_coordinates();
extern Object compute_oriented_destination_for_image();
extern Object compute_percentage();
extern Object compute_rgbquads();
extern Object copy_foreign_string_arg_if_appropriate();
extern Object copy_null_terminated_string_as_gensym_string();
extern Object copy_null_terminated_string_as_text_string();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object create_gray_map_from_color_map();
extern Object create_image_rendering();
extern Object delete_gensym_element_1();
extern Object direct_structure_method();
extern Object draw_hollow_rectangle_on_window();
extern Object draw_icon_background_image_on_window();
extern Object draw_icon_background_image_on_window_1();
extern Object draw_image_data_on_local_scratchpad();
extern Object draw_image_on_tile();
extern Object draw_image_on_tile_1_to_1();
extern Object draw_image_on_tile_24_to_24();
extern Object draw_image_on_tile_8_to_1();
extern Object draw_image_on_tile_8_to_8();
extern Object draw_image_on_tile_8_to_8_for_workspace();
extern Object draw_image_on_tile_8_to_truecolor();
extern Object draw_image_on_tile_8_to_truecolor_for_workspace();
extern Object draw_image_on_tile_for_workspace();
extern Object draw_image_on_window();
extern Object draw_image_tile_on_printer();
extern Object draw_mask_on_tile();
extern Object draw_mask_on_tile_1();
extern Object draw_missing_icon_background_image();
extern Object draw_missing_image();
extern Object draw_missing_image_on_window();
extern Object draw_tiled_image_on_window();
extern Object draw_valid_image_on_window();
extern Object draw_wide_polyline_on_window();
extern Object emit_icp_read_trace();
extern Object emit_icp_write_trace();
extern Object end_icp_message_group();
extern Object enlarge_index_space();
extern Object ensure_image_data_cache();
extern Object ensure_image_data_pixels();
extern Object ensure_image_rendering_color_map();
extern Object ensure_image_tile();
extern Object ensure_shredded_raster_buffer();
extern Object ensure_singleton_image_pixmap();
extern Object establish_new_object_index_for_image_data();
extern Object file_exists_p();
extern Object find_image_rendering();
extern Object find_nearest_color();
extern Object find_or_create_image_rendering();
extern Object find_suitable_image_tile_to_reuse();
extern Object finished_transmitting_image_data_p();
extern Object gensym_cons_1();
extern Object gensym_list_4();
extern Object gensym_probe_file();
extern Object get_icp_object_index_for_image_data();
extern Object get_images_error_message();
extern Object get_remote_icp_version_info_value();
extern Object get_x11_pixel_value_from_rgb();
extern Object getfq_function_no_default();
extern Object handle_icp_begin_making_image_data();
extern Object handle_icp_begin_making_image_data__body();
extern Object handle_icp_change_image_palette_of_window();
extern Object handle_icp_image_data_chunk();
extern Object handle_icp_image_data_chunk__body();
extern Object handle_icp_paint_icon_background_image_in_current_window();
extern Object handle_icp_paint_image_in_current_scratchpad_raster();
extern Object handle_icp_paint_image_in_current_window();
extern Object icp_connection_open_p();
extern Object icp_error_internal();
extern Object icp_message_functions_icp_prologue();
extern Object icp_port_shutdown_for_image_data();
extern Object identity_color_map();
extern Object image_data_and_raster_dimensional_match_p();
extern Object image_data_complete_p();
extern Object image_data_has_been_transmitted_p();
extern Object image_data_is_gray_scale_p();
extern Object image_data_next_scan_to_send();
extern Object image_data_structure_memory_usage();
extern Object image_palette_is_gray_p();
extern Object image_rendering_last_tile_height();
extern Object image_rendering_last_tile_width();
extern Object image_rendering_structure_memory_usage();
extern Object image_stream_format();
extern Object image_tile_structure_memory_usage();
extern Object images_too_many_buffered_icp_bytes_p();
extern Object initialize_icp_object_type();
extern Object initialize_icp_object_type_compile();
extern Object install_lru_element_in_queue();
extern Object instantaneous_icp_reader_byte_count();
extern Object instantaneous_icp_writer_byte_count();
extern Object invalidate_all_tiles_in_tiled_raster();
extern Object large_byte_vector();
extern Object load_and_initialize_type_description();
extern Object make_corresponding_icp_gensym_window();
extern Object make_corresponding_icp_image_data();
extern Object make_corresponding_icp_symbol();
extern Object make_gensym_list_1();
extern Object make_image_data();
extern Object make_image_data_1_1();
extern Object make_image_rendering_1_1();
extern Object make_image_tile();
extern Object make_image_tile_1_1();
extern Object make_permanent_image_data_structure_internal();
extern Object make_permanent_image_rendering_structure_internal();
extern Object make_permanent_image_tile_structure_internal();
extern Object make_permanent_shredded_raster_structure_internal();
extern Object make_shredded_raster_1_1();
extern Object make_thread_array();
extern Object map_to_closest_color_value();
extern Object map_to_color_value();
extern Object maximum_bytes_for_image_tiles();
extern Object maybe_restart_icp_window_update();
extern Object memq_function();
extern Object mutate_global_property();
extern Object note_image_progress();
extern Object note_progress_on_window();
extern Object notify_user_at_console();
extern Object obtain_simple_gensym_string();
extern Object outstanding_image_data_count();
extern Object outstanding_image_rendering_count();
extern Object outstanding_image_tile_count();
extern Object outstanding_shredded_raster_count();
extern Object paint_icon_background_image_in_current_window();
extern Object paint_image_in_current_scratchpad_raster();
extern Object paint_image_in_current_window();
extern Object paint_or_tile_image_in_current_window();
extern Object paint_solid_rectangle_in_current_scratchpad_raster();
extern Object printing_window_p();
extern Object push_optimized_constant();
extern Object read_icp_array_of_unsigned_integers();
extern Object read_icp_array_of_unsigned_integers_given_length();
extern Object read_icp_array_of_unsigned_integers_qm();
extern Object read_icp_bits();
extern Object read_icp_byte();
extern Object read_icp_byte_vector();
extern Object read_icp_compressed_image_data_chunk();
extern Object read_icp_corresponding_object_index();
extern Object read_icp_filtered_text_string();
extern Object read_icp_fixnum();
extern Object read_icp_image_data_chunk_byte_vector();
extern Object read_icp_integer();
extern Object read_icp_transparent_color_index();
extern Object read_icp_unsigned_integer();
extern Object read_icp_unsigned_integer_qm();
extern Object read_image_data();
extern Object read_image_data_header();
extern Object read_raster();
extern Object really_large_byte_vector();
extern Object reclaim_byte_vector();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_icp_object_map();
extern Object reclaim_icp_object_map_for_image_data();
extern Object reclaim_icp_port_entry();
extern Object reclaim_icp_port_entry_for_image_data();
extern Object reclaim_image_data();
extern Object reclaim_image_data_1_1();
extern Object reclaim_image_rendering();
extern Object reclaim_image_rendering_1_1();
extern Object reclaim_image_rendering_color_map();
extern Object reclaim_image_rendering_tiled_raster();
extern Object reclaim_image_tile();
extern Object reclaim_image_tile_1_1();
extern Object reclaim_managed_array();
extern Object reclaim_shredded_raster();
extern Object reclaim_shredded_raster_1_1();
extern Object reclaim_stored_raster_1();
extern Object reclaim_text_string();
extern Object reclaim_tiled_raster();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remote_side_supports_transparent_color_index_p();
extern Object restart_icp_message_group();
extern Object resumable_icp_pop();
extern Object resumable_icp_pop_list_if_end_marker();
extern Object resumable_icp_push();
extern Object reuse_image_tile();
extern Object rotated_by_90_p();
extern Object scalef_function();
extern Object send_all_image_data();
extern Object send_icp_begin_making_image_data();
extern Object send_icp_image_data_chunk();
extern Object send_some_image_data();
extern Object server_and_client_share_file_system_p();
extern Object set_access_form_for_image_data();
extern Object set_icp_object_index_for_image_data();
extern Object set_image_data_next_scan_to_send();
extern Object set_maximum_bytes_for_image_tiles();
extern Object shredded_raster_p_function();
extern Object shredded_raster_structure_memory_usage();
extern Object shredded_raster_to_background_tile();
extern Object slowly_draw_image_data_on_current_scratchpad();
extern Object start_writing_icp_message();
extern Object store_corresponding_icp_object();
extern Object stored_raster_in_regular_pool_qm();
extern Object sync_graphics_on_current_window();
extern Object synchronize_icp_on_window_with_drawing();
extern Object telewindows_can_read_image_data_locally_p();
extern Object text_string_p();
extern Object tformat();
extern Object trace_images();
extern Object trace_images_print();
extern Object untrace_images();
extern Object update_object_pool_meters_list();
extern Object window_supports_painting_this_image_data();
extern Object write_icp_array_of_unsigned_integers();
extern Object write_icp_array_of_unsigned_integers_given_length();
extern Object write_icp_array_of_unsigned_integers_qm();
extern Object write_icp_bits();
extern Object write_icp_bits_flush();
extern Object write_icp_byte();
extern Object write_icp_byte_vector();
extern Object write_icp_compressed_image_data_chunk();
extern Object write_icp_corresponding_object_index();
extern Object write_icp_filtered_text_string();
extern Object write_icp_fixnum();
extern Object write_icp_image_data_chunk_byte_vector();
extern Object write_icp_integer();
extern Object write_icp_maybe_suspend();
extern Object write_icp_transparent_color_index();
extern Object write_icp_unsigned_integer();
extern Object write_icp_unsigned_integer_qm();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Abort_for_icp_catcher_qm, Qabort_for_icp_catcher_qm);
DECLARE_VARIABLE_WITH_SYMBOL(All_image_data_structures, Qall_image_data_structures);
DECLARE_VARIABLE_WITH_SYMBOL(All_region_info, Qall_region_info);
extern Object Allocated_byte_vectors;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
#define Black_threshold_in_color_intensity FIX((SI_Long)128L)
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
extern Object Byte_vector_pool_counts;
DECLARE_VARIABLE_WITH_SYMBOL(Bytes_allocated_for_image_tiles, Qbytes_allocated_for_image_tiles);
extern Object Bytes_in_allocated_byte_vectors;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_image_datas, Qchain_of_available_image_datas);
extern Object Chain_of_available_image_datas_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_image_renderings, Qchain_of_available_image_renderings);
extern Object Chain_of_available_image_renderings_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_image_tiles, Qchain_of_available_image_tiles);
extern Object Chain_of_available_image_tiles_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_shredded_rasters, Qchain_of_available_shredded_rasters);
extern Object Chain_of_available_shredded_rasters_vector;
extern Object Color_intensities_for_extended_color_palette;
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_read_trace_level, Qcurrent_icp_read_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_write_trace_level, Qcurrent_icp_write_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster, Qcurrent_scratchpad_raster);
DECLARE_VARIABLE_WITH_SYMBOL(Current_standard_icp_object_index_space, Qcurrent_standard_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_name, Qcurrent_system_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_temporary_icp_object_index_space, Qcurrent_temporary_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_offset_for_stored_raster_qm, Qcurrent_x_offset_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_offset_for_stored_raster_qm, Qcurrent_y_offset_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Do_icp_flow_control_qm, Qdo_icp_flow_control_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_to_printer_p, Qdrawing_to_printer_p);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
#define Free_bits_per_icp_byte FIX((SI_Long)15L)
extern Object Free_bits_per_icp_byte_mask;
DECLARE_VARIABLE_WITH_SYMBOL(Icp_bits_current_bits, Qicp_bits_current_bits);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_bits_current_value, Qicp_bits_current_value);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
extern Object Icp_connection_closed;
DECLARE_VARIABLE_WITH_SYMBOL(Icp_printing_message_handler_array, Qicp_printing_message_handler_array);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_read_trace_cutoff_level_qm, Qicp_read_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_suspend, Qicp_suspend);
#define Icp_window_protocol_supports_24bit_image_painting FIX((SI_Long)23L)
#define Icp_window_protocol_supports_image_tiling FIX((SI_Long)28L)
#define Icp_window_protocol_supports_nms_menus FIX((SI_Long)29L)
#define Icp_window_protocol_supports_scrolling FIX((SI_Long)4L)
DECLARE_VARIABLE_WITH_SYMBOL(Icp_write_trace_cutoff_level_qm, Qicp_write_trace_cutoff_level_qm);
extern Object Identity_color_map;
DECLARE_VARIABLE_WITH_SYMBOL(Image_data_count, Qimage_data_count);
DECLARE_VARIABLE_WITH_SYMBOL(Image_left_offset_in_ws, Qimage_left_offset_in_ws);
DECLARE_VARIABLE_WITH_SYMBOL(Image_rendering_count, Qimage_rendering_count);
DECLARE_VARIABLE_WITH_SYMBOL(Image_tile_count, Qimage_tile_count);
DECLARE_VARIABLE_WITH_SYMBOL(Image_tile_lru_queue, Qimage_tile_lru_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Image_top_offset_in_ws, Qimage_top_offset_in_ws);
extern Object Images_maximum_number_of_icp_bytes_per_message_group;
extern Object Images_maximum_number_of_icp_bytes_to_buffer;
extern Object Images_time_to_sleep_before_clog;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_corresponding_icp_object_making, Qinhibit_corresponding_icp_object_making);
extern Object Inverse_reflection_and_rotation;
DECLARE_VARIABLE_WITH_SYMBOL(Is_icon_mask_drawing, Qis_icon_mask_drawing);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Large_byte_vector, Qlarge_byte_vector);
extern Object Largest_regular_raster_size;
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Max_distance_to_gray;
#define Maximum_background_tile_area FIX((SI_Long)16384L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
extern Object Maximum_size_of_images;
extern Object Minus_of_isqrt_of_most_positive_fixnum;
#define Number_of_bits_of_gray_in_the_extended_gray_palette FIX((SI_Long)6L)
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
extern Object Ordered_dither_16;
DECLARE_VARIABLE_WITH_SYMBOL(Overriding_alignment, Qoverriding_alignment);
#define Ps_solid FIX((SI_Long)0L)
extern Object Read_raster_error_string;
DECLARE_VARIABLE_WITH_SYMBOL(Really_large_byte_vector, Qreally_large_byte_vector);
DECLARE_VARIABLE_WITH_SYMBOL(Resumable_icp_state, Qresumable_icp_state);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Send_image_data_immediately_qm, Qsend_image_data_immediately_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Shredded_raster_count, Qshredded_raster_count);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Standard_gensym_color_alist, Qstandard_gensym_color_alist);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Supports_transparent_color_index, Qsupports_transparent_color_index);
DECLARE_VARIABLE_WITH_SYMBOL(System_window, Qsystem_window);
extern Object The_type_description_of_image_data;
extern Object The_type_description_of_image_rendering;
extern Object The_type_description_of_image_tile;
extern Object The_type_description_of_shredded_raster;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Trace_images, Qtrace_images);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_resumable_icp_messages_p, Qwriting_resumable_icp_messages_p);
#define X11_copy FIX((SI_Long)1L)
