/* mods.h -- Header File for mods.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qstar;
extern Object Qand;
extern Object Kinitial_element;
extern Object Kname;
extern Object Qquote;
extern Object Qsequence;
extern Object Qsymbol;
extern Object Ktest;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_class_to_environment(int,...);
extern Object add_frame_note(int,...);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_newer_system_tables_to_suite_if_necessary(Object);
extern Object add_or_delete_as_workspace_belonging_to_module(Object,Object,Object);
extern Object add_or_delete_module_name_from_directory_of_names(Object,Object);
extern Object add_source_code_control_grammar(void);
extern Object add_to_directory_of_names(Object,Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object assq_function(Object,Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object change_slot_value(int,...);
extern Object check_frame_note_based_modularity_problems(Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object check_module_definition_consistency(Object);
extern Object check_one_frame_note_based_modularity_problem(Object,Object);
extern Object clear_module_required_by_relationships(Object);
extern Object clear_module_required_by_relationships_tree(Object);
extern Object clear_optimized_constants(void);
extern Object clone_frame(int,...);
extern Object clone_system_frame(Object);
extern Object collect_subclasses(Object);
extern Object command_line_process_default_window_style(Object);
extern Object compile_file_name_qm_for_slot(int,...);
extern Object compile_list_of_modules_qm_for_slot(int,...);
extern Object compile_module_annotations_for_slot(int,...);
extern Object compile_module_file_name_qm_for_slot(int,...);
extern Object compile_module_name_for_module_information_qm_for_slot(int,...);
extern Object compile_permanent_lexing_table(Object);
extern Object compute_name_of_system_frame(Object);
extern Object compute_system_table_choices(int,...);
extern Object convert_text_string_to_text(Object);
extern Object copy_as_wide_string(Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_for_phrase(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_gensym_pathname(Object);
extern Object copy_list_using_slot_value_conses_1(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object create_initialized_system_tables_suite(Object);
extern Object create_new_module(Object);
extern Object decache_dynamic_menus(int,...);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object deinstall_currently_installed_system_table_suite(void);
extern Object deinstall_system_table(Object);
extern Object deinstall_system_table_for_module_information(Object);
extern Object deinstall_system_table_suite(Object);
extern Object delete_block_after_reading_kb(Object);
extern Object delete_duplicates_from_list(int,...);
extern Object delete_frame(Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_from_directory_of_names(Object,Object);
extern Object delete_from_frame_note_particulars_list(Object,Object,Object);
extern Object delete_hand_created_module_information_if_appropriate(Object);
extern Object delete_multiple_frame_notes_if_any(Object,Object);
extern Object delete_obsolete_or_duplicate_system_tables_in_suite(Object);
extern Object delete_skip_list_entry(Object,Object,Object,Object,Object);
extern Object delete_slot_value_element_1(Object,Object);
extern Object delete_system_table_suite(int,...);
extern Object delete_top_level_module(void);
extern Object delete_workspaces_of_module(Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object do_deletion_of_module_after_confirmation(Object,Object);
extern Object efficient_get_module_block_is_in(Object);
extern Object emit_kb_modularity_problem(int,...);
extern Object enable_scc_check(void);
extern Object ensure_named_frame_is_first_fetched(Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object exit_current_workstation_context_in_return_function(Object);
extern Object find_all_cycles_in_module_hierarchy(Object);
extern Object find_all_cycles_in_module_hierarchy_1(Object,Object);
extern Object find_currently_installed_system_table_suite(void);
extern Object find_duplicate_system_table_in_list(Object,Object);
extern Object find_system_table_suite_with_module_assignment(Object);
extern Object find_trivial_root_to_root_cycle_if_any(Object);
extern Object finish_setup_of_system_table_suite_for_new_module(Object);
extern Object flatten_module_required_by_relationships(Object);
extern Object flatten_skip_list(Object);
extern Object frame_has_note_p(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_enough_namestring(int,...);
extern Object gensym_file_as_directory(Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_parse_namestring_function(Object,Object,Object);
extern Object gensym_pathname(Object);
extern Object get_alias_for_slot_name_if_any(Object,Object);
extern Object get_command_line_keyword_argument(int,...);
extern Object get_command_line_plist_element_for_default_window_style(void);
extern Object get_enough_pathname_of_module_loaded_if_any(Object);
extern Object get_g2_module_search_path_as_token_list_of_texts(void);
extern Object get_g2_module_search_path_string_from_environment_or_command_line(void);
extern Object get_gensym_environment_variable(Object);
extern Object get_initial_value_for_g2_module_search_path(void);
extern Object get_initial_window_style(void);
extern Object get_kb_default_window_style_override_if_any(void);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_module_assignment_of_system_table_suite_read_in(Object);
extern Object get_module_block_is_in(Object);
extern Object get_module_block_is_within_if_required(Object,Object);
extern Object get_module_for_system_table(Object);
extern Object get_modules_that_require_this_module(Object);
extern Object get_reference_to_item(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_style_for_current_workstation_if_any(void);
extern Object get_symbol_properties_function(Object);
extern Object get_system_table_currently_in_force(Object);
extern Object get_system_table_instance_for_module(Object,Object);
extern Object get_system_table_of_class_for_module_or_nil(Object,Object);
extern Object get_system_table_suite_for_module_or_nil(Object);
extern Object get_true_pathname_of_module_if_any(Object);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace_if_any(Object);
extern Object get_workstation_g2_window_style_in_force(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object inform_ui_client_interfaces_of_module_creation(Object);
extern Object inform_ui_client_interfaces_of_module_deletion(Object);
extern Object initialize_for_server_parameters(Object);
extern Object initialize_modules_and_system_tables_a_list(void);
extern Object install_system_table(Object);
extern Object install_system_table_for_module_information(Object);
extern Object install_system_table_suite(Object);
extern Object instantiable_system_table_subclass_p(Object);
extern Object kb_has_modularity_information_p(void);
extern Object kb_requires_module_p(Object);
extern Object list_of_pathnames_gt_list_of_text_strings(Object);
extern Object list_of_text_strings_gt_list_of_pathnames(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_frame(Object);
extern Object make_fully_fleshed_out_system_table_suite(Object);
extern Object make_module_required_by_relationships(void);
extern Object make_module_required_by_relationships_hash_vector(void);
extern Object make_module_required_by_relationships_tree_for_hash_skip_list_sentinel(Object,Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_permanent_module_required_by_relationships_hash_vector_43_vector_internal(void);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_suite_be_headed_up_by_module_information_system_table(Object);
extern Object make_system_frame(Object);
extern Object make_thread_array(Object);
extern Object memq_function(Object,Object);
extern Object merge_in_system_table_suite_read_in(int,...);
extern Object module_exists_p(Object);
extern Object module_hierarchy_contains_cyclic_dependency_p(Object);
extern Object module_relationship_key_equal(Object,Object);
extern Object module_required_by_relationships_hash_vector_43_vector_memory_usage(void);
extern Object module_required_p_1(Object,Object);
extern Object module_requires_module_p(Object,Object);
extern Object multiple_add_to_results_for_inspect_command(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object mutate_module_required_by_relationships_tree_for_hash_skip_list_entry(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_crlf_use_in_module_or_file(Object,Object);
extern Object notify_user(int,...);
extern Object notify_user_of_autostart_and_reason(Object);
extern Object obsolete_system_table_p(Object);
extern Object out_module_required_by_relationships_hash_vector_43_vectors(void);
extern Object parse_module_map_line_into_parts(Object);
extern Object parse_space_delimited_text_line_into_list_of_text_strings(Object);
extern Object parse_text_for_slot(int,...);
extern Object partition_system_tables_into_separate_module_suites(Object);
extern Object phrase_cons(Object,Object);
extern Object print_classes_not_defined_in_any_module(Object);
extern Object print_classes_whose_superiors_are_not_defined_in_required_modules(Object);
extern Object print_classes_with_instances_in_modules_that_do_not_require_them(Object);
extern Object print_table_in_different_module_than_item_represented(Object);
extern Object propagate_cached_module_is_required_p_1(Object);
extern Object propagate_kb_requires_module_p_to_all_modules(void);
extern Object propagate_module_assignment_throughout_system_table_suite(Object);
extern Object propagate_module_requires_module_p_to_all_modules(Object);
extern Object propagate_modules_to_subworkspaces(void);
extern Object push_optimized_constant(Object);
extern Object put_current_style_if_other_than_default_qm(Object,Object,Object);
extern Object put_directly_required_kb_modules(Object,Object,Object);
extern Object put_module_search_path(Object,Object,Object);
extern Object put_name_or_names_for_frame(Object,Object,Object);
extern Object put_restrict_edits_to_read_only_files(Object,Object,Object);
extern Object put_source_code_control_support_is_enabled(Object,Object,Object);
extern Object put_top_level_kb_module_qm(Object,Object,Object);
extern Object read_symbol_from_text_string(int,...);
extern Object reclaim_directly_required_kb_modules_value(Object,Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_if_gensym_pathname(Object);
extern Object reclaim_if_text_string_function(Object);
extern Object reclaim_modularity_problems(void);
extern Object reclaim_module_required_by_relationships(Object);
extern Object reclaim_module_required_by_relationships_hash_vector(Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_token_list_1(Object);
extern Object reclaim_top_level_kb_module_qm_value(Object,Object);
extern Object reclaim_wide_string(Object);
extern Object recompute_editability_of_modules(void);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_any_trappings_of_installation_in_system_table_suite(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_stack_change_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object report_on_modularity_checking(void);
extern Object reset_current_workstation_new_g2_classic_ui_p(void);
extern Object scope_cons(Object,Object);
extern Object set_block_permanently_changed_function(Object);
extern Object set_default_pathname_for_module(Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_gensym_pathname_for_module(Object,Object);
extern Object set_initial_plist_for_loaded_module(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_module_for_workspace(Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_reason_module_is_not_editable(Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object set_true_pathname_of_module(Object,Object,Object);
extern Object set_up_all_module_to_module_information_instance_backpointers(void);
extern Object set_up_modules_and_system_tables_a_list_after_reading(void);
extern Object slot_value_cons_1(Object,Object);
extern Object sort_slot_value_list_by_example(Object,Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object store_hand_created_module_information_if_appropriate(Object);
extern Object store_system_table_suite(Object);
extern Object superior_frame(Object);
extern Object sxhashw(Object);
extern Object system_table_installed_p(Object);
extern Object system_table_suite_test(Object,Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object tformat_warning_about_modules_that_require_this_if_necessary(Object);
extern Object token_cons_1(Object,Object);
extern Object tokenize_text_string(Object,Object);
extern Object top_level_kb_module_p(Object);
extern Object tprin(Object,Object);
extern Object try_to_do_deferred_user_notifications(void);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_parsably(Object);
extern Object twrite_symbol(int,...);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object unmark_all_module_information_instances(void);
extern Object unpropagate_modules_to_subworkspaces(void);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_frame_name_references(Object);
extern Object update_module_related_circularity_frame_notes(void);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_module_related_frame_notes_of_workspace(Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_slot_value(int,...);
extern Object update_saving_parameters_status_attributes(int,...);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object validate_window_style_command_line_argument(Object,Object);
extern Object within_module_hierarchy_p(Object,Object);
extern Object within_modules_p(Object,Object);
extern Object write_file_name_qm_from_slot(Object,Object);
extern Object write_list_of_modules_qm_from_slot(Object,Object);
extern Object write_module_annotations_from_slot(Object,Object);
extern Object write_module_file_name_qm_from_slot(Object,Object);
extern Object write_module_name_for_module_information_qm_from_slot(Object,Object);
extern Object write_module_search_path_from_slot(Object,Object);
extern Object write_symbol_list(int,...);

#else

extern Object add_class_to_environment();
extern Object add_frame_note();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_newer_system_tables_to_suite_if_necessary();
extern Object add_or_delete_as_workspace_belonging_to_module();
extern Object add_or_delete_module_name_from_directory_of_names();
extern Object add_source_code_control_grammar();
extern Object add_to_directory_of_names();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object assq_function();
extern Object bytes_per_typed_simple_array();
extern Object change_slot_value();
extern Object check_frame_note_based_modularity_problems();
extern Object check_if_superior_classes_are_defined();
extern Object check_module_definition_consistency();
extern Object check_one_frame_note_based_modularity_problem();
extern Object clear_module_required_by_relationships();
extern Object clear_module_required_by_relationships_tree();
extern Object clear_optimized_constants();
extern Object clone_frame();
extern Object clone_system_frame();
extern Object collect_subclasses();
extern Object command_line_process_default_window_style();
extern Object compile_file_name_qm_for_slot();
extern Object compile_list_of_modules_qm_for_slot();
extern Object compile_module_annotations_for_slot();
extern Object compile_module_file_name_qm_for_slot();
extern Object compile_module_name_for_module_information_qm_for_slot();
extern Object compile_permanent_lexing_table();
extern Object compute_name_of_system_frame();
extern Object compute_system_table_choices();
extern Object convert_text_string_to_text();
extern Object copy_as_wide_string();
extern Object copy_evaluation_value_1();
extern Object copy_for_phrase();
extern Object copy_frame_serial_number();
extern Object copy_gensym_pathname();
extern Object copy_list_using_slot_value_conses_1();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object create_initialized_system_tables_suite();
extern Object create_new_module();
extern Object decache_dynamic_menus();
extern Object define_type_specification_explicit_complex_type();
extern Object deinstall_currently_installed_system_table_suite();
extern Object deinstall_system_table();
extern Object deinstall_system_table_for_module_information();
extern Object deinstall_system_table_suite();
extern Object delete_block_after_reading_kb();
extern Object delete_duplicates_from_list();
extern Object delete_frame();
extern Object delete_frame_note_if_any();
extern Object delete_from_directory_of_names();
extern Object delete_from_frame_note_particulars_list();
extern Object delete_hand_created_module_information_if_appropriate();
extern Object delete_multiple_frame_notes_if_any();
extern Object delete_obsolete_or_duplicate_system_tables_in_suite();
extern Object delete_skip_list_entry();
extern Object delete_slot_value_element_1();
extern Object delete_system_table_suite();
extern Object delete_top_level_module();
extern Object delete_workspaces_of_module();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object do_deletion_of_module_after_confirmation();
extern Object efficient_get_module_block_is_in();
extern Object emit_kb_modularity_problem();
extern Object enable_scc_check();
extern Object ensure_named_frame_is_first_fetched();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object exit_current_workstation_context_in_return_function();
extern Object find_all_cycles_in_module_hierarchy();
extern Object find_all_cycles_in_module_hierarchy_1();
extern Object find_currently_installed_system_table_suite();
extern Object find_duplicate_system_table_in_list();
extern Object find_system_table_suite_with_module_assignment();
extern Object find_trivial_root_to_root_cycle_if_any();
extern Object finish_setup_of_system_table_suite_for_new_module();
extern Object flatten_module_required_by_relationships();
extern Object flatten_skip_list();
extern Object frame_has_note_p();
extern Object gensym_cons_1();
extern Object gensym_enough_namestring();
extern Object gensym_file_as_directory();
extern Object gensym_list_2();
extern Object gensym_namestring();
extern Object gensym_parse_namestring_function();
extern Object gensym_pathname();
extern Object get_alias_for_slot_name_if_any();
extern Object get_command_line_keyword_argument();
extern Object get_command_line_plist_element_for_default_window_style();
extern Object get_enough_pathname_of_module_loaded_if_any();
extern Object get_g2_module_search_path_as_token_list_of_texts();
extern Object get_g2_module_search_path_string_from_environment_or_command_line();
extern Object get_gensym_environment_variable();
extern Object get_initial_value_for_g2_module_search_path();
extern Object get_initial_window_style();
extern Object get_kb_default_window_style_override_if_any();
extern Object get_lookup_slot_value();
extern Object get_module_assignment_of_system_table_suite_read_in();
extern Object get_module_block_is_in();
extern Object get_module_block_is_within_if_required();
extern Object get_module_for_system_table();
extern Object get_modules_that_require_this_module();
extern Object get_reference_to_item();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_function();
extern Object get_style_for_current_workstation_if_any();
extern Object get_symbol_properties_function();
extern Object get_system_table_currently_in_force();
extern Object get_system_table_instance_for_module();
extern Object get_system_table_of_class_for_module_or_nil();
extern Object get_system_table_suite_for_module_or_nil();
extern Object get_true_pathname_of_module_if_any();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace_if_any();
extern Object get_workstation_g2_window_style_in_force();
extern Object getfq_function_no_default();
extern Object inform_ui_client_interfaces_of_module_creation();
extern Object inform_ui_client_interfaces_of_module_deletion();
extern Object initialize_for_server_parameters();
extern Object initialize_modules_and_system_tables_a_list();
extern Object install_system_table();
extern Object install_system_table_for_module_information();
extern Object install_system_table_suite();
extern Object instantiable_system_table_subclass_p();
extern Object kb_has_modularity_information_p();
extern Object kb_requires_module_p();
extern Object list_of_pathnames_gt_list_of_text_strings();
extern Object list_of_text_strings_gt_list_of_pathnames();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_frame();
extern Object make_fully_fleshed_out_system_table_suite();
extern Object make_module_required_by_relationships();
extern Object make_module_required_by_relationships_hash_vector();
extern Object make_module_required_by_relationships_tree_for_hash_skip_list_sentinel();
extern Object make_named_dynamic_extent_description();
extern Object make_permanent_module_required_by_relationships_hash_vector_43_vector_internal();
extern Object make_skip_list_element_1();
extern Object make_suite_be_headed_up_by_module_information_system_table();
extern Object make_system_frame();
extern Object make_thread_array();
extern Object memq_function();
extern Object merge_in_system_table_suite_read_in();
extern Object module_exists_p();
extern Object module_hierarchy_contains_cyclic_dependency_p();
extern Object module_relationship_key_equal();
extern Object module_required_by_relationships_hash_vector_43_vector_memory_usage();
extern Object module_required_p_1();
extern Object module_requires_module_p();
extern Object multiple_add_to_results_for_inspect_command();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object mutate_module_required_by_relationships_tree_for_hash_skip_list_entry();
extern Object note_change_to_block_1();
extern Object note_crlf_use_in_module_or_file();
extern Object notify_user();
extern Object notify_user_of_autostart_and_reason();
extern Object obsolete_system_table_p();
extern Object out_module_required_by_relationships_hash_vector_43_vectors();
extern Object parse_module_map_line_into_parts();
extern Object parse_space_delimited_text_line_into_list_of_text_strings();
extern Object parse_text_for_slot();
extern Object partition_system_tables_into_separate_module_suites();
extern Object phrase_cons();
extern Object print_classes_not_defined_in_any_module();
extern Object print_classes_whose_superiors_are_not_defined_in_required_modules();
extern Object print_classes_with_instances_in_modules_that_do_not_require_them();
extern Object print_table_in_different_module_than_item_represented();
extern Object propagate_cached_module_is_required_p_1();
extern Object propagate_kb_requires_module_p_to_all_modules();
extern Object propagate_module_assignment_throughout_system_table_suite();
extern Object propagate_module_requires_module_p_to_all_modules();
extern Object propagate_modules_to_subworkspaces();
extern Object push_optimized_constant();
extern Object put_current_style_if_other_than_default_qm();
extern Object put_directly_required_kb_modules();
extern Object put_module_search_path();
extern Object put_name_or_names_for_frame();
extern Object put_restrict_edits_to_read_only_files();
extern Object put_source_code_control_support_is_enabled();
extern Object put_top_level_kb_module_qm();
extern Object read_symbol_from_text_string();
extern Object reclaim_directly_required_kb_modules_value();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_if_gensym_pathname();
extern Object reclaim_if_text_string_function();
extern Object reclaim_modularity_problems();
extern Object reclaim_module_required_by_relationships();
extern Object reclaim_module_required_by_relationships_hash_vector();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_text_string();
extern Object reclaim_token_list_1();
extern Object reclaim_top_level_kb_module_qm_value();
extern Object reclaim_wide_string();
extern Object recompute_editability_of_modules();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_any_trappings_of_installation_in_system_table_suite();
extern Object replenish_lookup_cons_pool();
extern Object replenish_stack_change_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object report_on_modularity_checking();
extern Object reset_current_workstation_new_g2_classic_ui_p();
extern Object scope_cons();
extern Object set_block_permanently_changed_function();
extern Object set_default_pathname_for_module();
extern Object set_evaluation_value_to_category_function();
extern Object set_gensym_pathname_for_module();
extern Object set_initial_plist_for_loaded_module();
extern Object set_lookup_slot_value_1();
extern Object set_module_for_workspace();
extern Object set_property_value_function();
extern Object set_reason_module_is_not_editable();
extern Object set_slot_value_to_evaluation_value_function();
extern Object set_true_pathname_of_module();
extern Object set_up_all_module_to_module_information_instance_backpointers();
extern Object set_up_modules_and_system_tables_a_list_after_reading();
extern Object slot_value_cons_1();
extern Object sort_slot_value_list_by_example();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object store_hand_created_module_information_if_appropriate();
extern Object store_system_table_suite();
extern Object superior_frame();
extern Object sxhashw();
extern Object system_table_installed_p();
extern Object system_table_suite_test();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object tformat_warning_about_modules_that_require_this_if_necessary();
extern Object token_cons_1();
extern Object tokenize_text_string();
extern Object top_level_kb_module_p();
extern Object tprin();
extern Object try_to_do_deferred_user_notifications();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_parsably();
extern Object twrite_symbol();
extern Object type_error_in_setter();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object unmark_all_module_information_instances();
extern Object unpropagate_modules_to_subworkspaces();
extern Object update_all_representations_of_slot();
extern Object update_frame_name_references();
extern Object update_module_related_circularity_frame_notes();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_module_related_frame_notes_of_workspace();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_slot_value();
extern Object update_saving_parameters_status_attributes();
extern Object validate_item_or_evaluation_value();
extern Object validate_window_style_command_line_argument();
extern Object within_module_hierarchy_p();
extern Object within_modules_p();
extern Object write_file_name_qm_from_slot();
extern Object write_list_of_modules_qm_from_slot();
extern Object write_module_annotations_from_slot();
extern Object write_module_file_name_qm_from_slot();
extern Object write_module_name_for_module_information_qm_from_slot();
extern Object write_module_search_path_from_slot();
extern Object write_symbol_list();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_cycles_found_so_far_in_module_hierarchy, Qall_cycles_found_so_far_in_module_hierarchy);
DECLARE_VARIABLE_WITH_SYMBOL(All_known_command_line_plist_elements, Qall_known_command_line_plist_elements);
DECLARE_VARIABLE_WITH_SYMBOL(All_module_frame_notes_for_workspaces, Qall_module_frame_notes_for_workspaces);
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_module_required_by_relationships_hash_vector_43_vectors, Qavailable_module_required_by_relationships_hash_vector_43_vectors);
extern Object Available_module_required_by_relationships_hash_vector_43_vectors_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Called_within_clear_text_loading, Qcalled_within_clear_text_loading);
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Classes_not_defined_in_any_module, Qclasses_not_defined_in_any_module);
DECLARE_VARIABLE_WITH_SYMBOL(Classes_whose_superiors_are_not_defined_in_required_modules, Qclasses_whose_superiors_are_not_defined_in_required_modules);
DECLARE_VARIABLE_WITH_SYMBOL(Color_parameters, Qcolor_parameters);
extern Object Command_line_arguments;
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_module_required_by_relationships_hash_vector_43_vectors, Qcount_of_module_required_by_relationships_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_modularity_problems, Qcurrent_modularity_problems);
DECLARE_VARIABLE_WITH_SYMBOL(Current_modularity_problems_fatal_qm, Qcurrent_modularity_problems_fatal_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_style_if_other_than_default, Qcurrent_style_if_other_than_default);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_name, Qcurrent_system_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Currently_loading_modules_qm, Qcurrently_loading_modules_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_parameters, Qdata_server_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
extern Object Default_g2_window_style;
extern Object Default_pathname_for_module_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
extern Object Direct_superior_classes_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_parameters, Qdrawing_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fonts, Qfonts);
extern Object Format_args_for_kb_modularity_problem_prop;
extern Object Format_string_for_kb_modularity_problem_prop;
extern Object Fp_mutate_module_required_by_relationships_tree_for_hash_skip_list_entry;
DECLARE_VARIABLE_WITH_SYMBOL(G2_module_file_name_map, Qg2_module_file_name_map);
DECLARE_VARIABLE_WITH_SYMBOL(G2_module_search_path, Qg2_module_search_path);
DECLARE_VARIABLE_WITH_SYMBOL(G2gl_parameters, Qg2gl_parameters);
extern Object Gensym_pathname_for_module_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Inference_engine_parameters, Qinference_engine_parameters);
extern Object Inferior_classes_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Inhibit_updating_module_related_frame_notes_for_all_workspaces_qm, Qinhibit_updating_module_related_frame_notes_for_all_workspaces_qm);
extern Object Initial_plist_for_loaded_module_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Inspect_command_for_modularity_problems_qm, Qinspect_command_for_modularity_problems_qm);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
extern Object Kb_specific_property_names;
DECLARE_VARIABLE_WITH_SYMBOL(Kb_uses_crlf_p, Qkb_uses_crlf_p);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_workspace_class_description, Qkb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Language_parameters, Qlanguage_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Log_file_parameters, Qlog_file_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Logbook_parameters, Qlogbook_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Main_kb_being_read_qm, Qmain_kb_being_read_qm);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
DECLARE_VARIABLE_WITH_SYMBOL(Menu_parameters, Qmenu_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Message_board_parameters, Qmessage_board_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Miscellaneous_parameters, Qmiscellaneous_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Modularity_checking, Qmodularity_checking);
DECLARE_VARIABLE_WITH_SYMBOL(Module_information, Qmodule_information);
extern Object Module_information_instance_for_module_qm_kbprop;
extern Object Module_is_locked_p_kbprop;
extern Object Module_is_writable_p_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Module_required_by_relationships, Qmodule_required_by_relationships);
DECLARE_VARIABLE_WITH_SYMBOL(Module_search_path_tokenizer, Qmodule_search_path_tokenizer);
extern Object Module_search_path_tokens;
extern Object Module_uses_crlf_p_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Modules_and_system_tables_a_list, Qmodules_and_system_tables_a_list);
DECLARE_VARIABLE_WITH_SYMBOL(Modules_that_have_already_been_loaded, Qmodules_that_have_already_been_loaded);
DECLARE_VARIABLE_WITH_SYMBOL(Name_of_module_being_read_qm, Qname_of_module_being_read_qm);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Obsolete_frame_note_types_from_modularity_development, Qobsolete_frame_note_types_from_modularity_development);
extern Object Order_of_system_tables_in_menu;
extern Object Particulars_printer_for_kb_modularity_problem_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Printer_setup, Qprinter_setup);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_kb_p, Qreading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
extern Object Reason_module_is_not_editable_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Releasing_kb_qm, Qreleasing_kb_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Restrict_edits_to_modules_having_read_only_files_p, Qrestrict_edits_to_modules_having_read_only_files_p);
DECLARE_VARIABLE_WITH_SYMBOL(Saving_parameters, Qsaving_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Server_parameters, Qserver_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_parameters, Qsimulation_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Source_code_control_support_enabled_p, Qsource_code_control_support_enabled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(System_tables_read_for_this_module, Qsystem_tables_read_for_this_module);
DECLARE_VARIABLE_WITH_SYMBOL(Timing_parameters, Qtiming_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Version_control_parameters, Qversion_control_parameters);
extern Object Workspaces_belonging_to_this_module_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
