/* moves.h -- Header File for moves.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kabort;
extern Object Qcons;
extern Object Qdelete;
extern Object Qfill;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object add_bend_to_connection(Object,Object);
extern Object add_cursors_to_current_window(Object,Object,Object,Object,Object,Object,Object);
extern Object add_from_pane_cursor_to_current_window(Object,Object,Object,Object,Object,Object,Object);
extern Object add_image_plane_border_as_pane_cursor(Object,Object,Object);
extern Object add_image_plane_cursor(Object,Object);
extern Object add_image_plane_cursors_to_current_window(void);
extern Object add_keymap_to_workstation_context(Object,Object);
extern Object add_mouse_pointer_to_guardians_of_workstation_context(Object,Object);
extern Object add_new_connection_to_block(int,...);
extern Object add_pane_cursor(Object,Object);
extern Object add_plus_sign_as_pane_cursor(Object,Object,Object,Object,Object,Object,Object);
extern Object add_rectangle_to_region(Object,Object,Object,Object,Object);
extern Object add_subblock(Object,Object);
extern Object add_xor_overlay_to_current_image_plane(void);
extern Object adjust_rectangle_edges(Object,Object,Object,Object,Object,Object,Object);
extern Object ancestor_p(Object,Object);
extern Object beep_at_user(void);
extern Object begin_dragging_selection_handle(Object,Object,Object,Object,Object,Object,Object);
extern Object block_of_edit_workspace_p(Object);
extern Object block_transferable_p(int,...);
extern Object blocks_transferable_p(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object car_or_atom(Object);
extern Object change_color_of_selection_highlight(Object,Object,Object);
extern Object change_connection_deltas_for_object_being_dragged(Object,Object,Object,Object);
extern Object change_size_per_bounding_rectangle(int,...);
extern Object check_completion_of_transfer_after_drag(Object,Object);
extern Object check_if_dragging_confined_due_to_superblock(Object);
extern Object clean_up_image_plane_cursor(Object,Object,Object);
extern Object clear_optimized_constants(void);
extern Object compute_connection_vertices(Object);
extern Object compute_movement_contraints(Object,Object,Object,Object);
extern Object compute_movement_limits_for_blocks(Object,Object,Object,Object,Object,Object,Object);
extern Object compute_snap_grid_for_block(int,...);
extern Object compute_snap_grid_for_transfer(int,...);
extern Object compute_stretched_links_of_connection_being_dragged(Object,Object);
extern Object connection_external_to_blocks_p(Object,Object,Object);
extern Object connection_is_straight_qm(Object);
extern Object connections_moved_for_blocks_moved(Object);
extern Object constant_queue_next(Object,Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_list_using_dragging_conses_1(Object);
extern Object copy_list_using_gensym_conses_1(Object);
extern Object copy_list_using_tree_ordering_conses_1(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_tree_using_dragging_conses_1(Object);
extern Object copy_tree_using_gensym_conses_1(Object);
extern Object copy_tree_using_graphics_conses_1(Object);
extern Object create_resize_cursor(Object,Object,Object);
extern Object decode_window_position(Object,Object,Object);
extern Object delete_blocks_from_list_in_limbo(Object,Object);
extern Object delete_dragging_cons_1(Object,Object);
extern Object delete_dragging_element_1(Object,Object);
extern Object delete_frame(Object);
extern Object delete_graphics_element_1(Object,Object);
extern Object delete_last_bend_from_connection(Object,Object);
extern Object delete_pane_cursor(Object,Object);
extern Object detail_pane(Object);
extern Object determine_extreme_edges_for_item_being_moved(Object);
extern Object determine_extreme_edges_of_blocks_and_connections(Object,Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object drag_handle_state_structure_memory_usage(void);
extern Object drag_outline_if_appropriate(Object,Object);
extern Object dragging_cons_1(Object,Object);
extern Object dragging_cons_function(Object,Object);
extern Object dragging_cons_memory_usage(void);
extern Object dragging_list_2(Object,Object);
extern Object dragging_list_3(Object,Object,Object);
extern Object dragging_list_4(Object,Object,Object,Object);
extern Object dragging_list_trace_hook(Object);
extern Object dragging_state_structure_memory_usage(void);
extern Object draw_block(Object);
extern Object draw_block_or_blocks_in_dragging_state(Object,Object);
extern Object draw_block_possibly_with_frame(Object,Object);
extern Object draw_blocks_and_connections_being_moved(Object,Object);
extern Object draw_connection(Object,Object);
extern Object draw_dotted_rectangle(Object,Object,Object,Object,Object);
extern Object draw_icon_from_description(Object,Object,Object,Object,Object,Object,Object);
extern Object draw_image_plane_cursor(Object,Object);
extern Object draw_image_plane_cursor_1(Object);
extern Object draw_or_erase_all_selection_highlights(Object);
extern Object draw_rectangle_outline_in_window(Object,Object,Object,Object,Object,Object,Object);
extern Object draw_resize_cursor(Object);
extern Object draw_selection_handle(Object,Object,Object,Object);
extern Object draw_selection_handles_for_block(Object,Object);
extern Object draw_selection_handles_for_connection(Object,Object);
extern Object draw_selection_handles_for_text_cell(Object,Object);
extern Object draw_selection_highlight(Object);
extern Object draw_selection_highlight_1(Object,Object);
extern Object draw_selection_rectangle_cursor(Object);
extern Object draw_wide_polyline(Object,Object,Object,Object,Object);
extern Object end_icp_message_group(void);
extern Object enlarge_workspace_if_necessary(int,...);
extern Object enter_context_in_current_workstation(int,...);
extern Object enter_dialog(int,...);
extern Object enter_drag_handle_context_function(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object enter_dragging_context_1(int,...);
extern Object enter_image_plane_dragging_context(int,...);
extern Object enter_move_dragging_context(int,...);
extern Object enter_transfer_dragging_context(int,...);
extern Object erase_and_reclaim_all_selection_highlights(Object);
extern Object erase_outline_of_image_plane_being_dragged(int,...);
extern Object erase_transfer_representations_of_block(Object);
extern Object establish_next_workstation_context_continuation(Object,Object,Object,Object);
extern Object event_update_status_of_block_showing(Object,Object,Object);
extern Object find_object_near_loose_end_being_dragged(Object,Object,Object);
extern Object find_object_near_mouse(Object,Object,Object,Object,Object);
extern Object find_selection_highlight(Object,Object);
extern Object find_selection_highlight_position(Object,Object);
extern Object find_selection_highlights(Object,Object);
extern Object finish_connection_dragging(Object);
extern Object finish_drag_handle(Object);
extern Object force_process_drawing_if_appropriate(void);
extern Object force_workspace_drawing(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object frames_currently_being_dragged_have_been_deleted_p(Object);
extern Object gather_connections_for_block(Object,Object);
extern Object generate_float_vector(Object);
extern Object generate_spot_for_selection_handle(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_block_at_other_end_of_connection(Object,Object);
extern Object get_connection_for_loose_end(Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_module_block_is_in(Object);
extern Object get_table_cell_edges(Object,Object);
extern Object get_table_for_cell(Object);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object graphics_cons_1(Object,Object);
extern Object graphics_list_4(Object,Object,Object,Object);
extern Object group_blocks_for_move_or_transfer(Object);
extern Object handle_connection_click_near_last_anchor_point(Object,Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object ignore_snap_grid_in_transfer_operations_p(void);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_selected_p(Object);
extern Object in_order_p(Object);
extern Object install_item_in_model_if_models_used(Object);
extern Object invalidate_region_of_image_plane(Object,Object);
extern Object invalidate_selection_handles(Object,Object);
extern Object inverse_scalef_function(Object,Object);
extern Object invoke_connection_handler_if_any(Object,Object,Object,Object);
extern Object invoke_rules_for_direct_connection_chaining(Object,Object);
extern Object invoke_rules_for_indirect_connection_chaining(Object,Object);
extern Object invoke_rules_for_resizement_chaining(Object,Object);
extern Object invoke_rules_for_user_icon_movement_if_necessary(Object);
extern Object item_to_transfer_connected_stack_error(Object);
extern Object item_x_position(Object);
extern Object item_y_position(Object);
extern Object join_two_connections(Object,Object);
extern Object launch_compile_to_bring_kb_up_to_date(int,...);
extern Object launch_compile_to_bring_kb_up_to_date_and_return_from_transfer_dragging(Object);
extern Object list_external_connections_to_drag(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object loose_end_dragging_outline_p(Object);
extern Object loose_end_near_last_anchor_point_qm(Object,Object,Object);
extern Object make_context_description(Object,Object,Object,Object);
extern Object make_description_of_barrier_to_destabilization(void);
extern Object make_drag_handle_state_1(void);
extern Object make_dragging_list_1(Object);
extern Object make_dragging_state_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_empty_region(void);
extern Object make_gensym_list_1(Object);
extern Object make_graphics_list_1(Object);
extern Object make_junction(Object,Object);
extern Object make_keymap(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_move_dragging_state_1(void);
extern Object make_outline_for_blocks_to_drag(Object,Object);
extern Object make_outline_for_image_plane_to_drag(Object,Object,Object);
extern Object make_permanent_drag_handle_state_structure_internal(void);
extern Object make_permanent_dragging_state_structure_internal(void);
extern Object make_permanent_move_dragging_state_structure_internal(void);
extern Object make_permanent_selection_handle_spot_structure_internal(void);
extern Object make_permanent_transfer_dragging_state_structure_internal(void);
extern Object make_selection_handle_spot_1(void);
extern Object make_thread_array(Object);
extern Object make_transfer_dragging_state_1(void);
extern Object map_to_color_value(Object);
extern Object map_to_color_value_1(Object);
extern Object memq_function(Object,Object);
extern Object mouse_down_in_dragging_state(Object);
extern Object mouse_down_p(void);
extern Object mouse_motion_in_dragging_state(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object mouse_up_in_dragging_state(Object);
extern Object move_all_selection_highlights(Object,Object,Object,Object,Object);
extern Object move_blocks_with_their_external_connections(Object,Object,Object,Object);
extern Object move_connection_vertex_by(Object,Object,Object,Object);
extern Object move_dragging_state_structure_memory_usage(void);
extern Object move_image_plane(Object,Object,Object);
extern Object move_image_plane_upon_continuation_after_dragging(Object);
extern Object move_or_transfer_blocks_being_dragged_if_appropriate(Object,Object,Object,Object);
extern Object move_outline_of_image_plane_being_dragged(Object,Object,Object);
extern Object move_pane_cursor(Object,Object,Object,Object);
extern Object move_resize_cursor(Object,Object,Object,Object,Object,Object);
extern Object move_selection_highlight(Object,Object,Object);
extern Object move_selection_highlights(Object,Object,Object,Object);
extern Object movement_limits_for_block(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object nip_begin_drawing(Object);
extern Object nip_end_drawing(Object);
extern Object no_manual_connections_p(Object);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object note_change_to_superior_of_block_or_blocks(Object);
extern Object note_dependent_or_stable_status_change(Object);
extern Object note_kb_state_change(Object,Object);
extern Object note_modification_of_module_for_clear_text(Object,Object);
extern Object notify_user(int,...);
extern Object offer_to_recompile_after_transfer(void);
extern Object outstanding_drag_handle_state_count(void);
extern Object outstanding_dragging_conses(void);
extern Object outstanding_dragging_state_count(void);
extern Object outstanding_move_dragging_state_count(void);
extern Object outstanding_selection_handle_spot_count(void);
extern Object outstanding_transfer_dragging_state_count(void);
extern Object paint_rectangle_outline_in_window(Object,Object,Object,Object,Object,Object,Object);
extern Object place_connection_if_orthogonal_qm(Object,Object,Object,Object);
extern Object printing_image_plane_p(Object);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object push_selection_handle_spot(Object,Object,Object,Object,Object,Object);
extern Object put_kink_into_connection_if_straight(Object,Object);
extern Object reason_permanent_items_module_is_not_editable(int,...);
extern Object reclaim_drag_handle_state_1(Object);
extern Object reclaim_dragging_cons_1(Object);
extern Object reclaim_dragging_cons_function(Object);
extern Object reclaim_dragging_list_1(Object);
extern Object reclaim_dragging_list_function(Object);
extern Object reclaim_dragging_list_of_pane_cursors(Object);
extern Object reclaim_dragging_list_star_1(Object);
extern Object reclaim_dragging_state_1(Object);
extern Object reclaim_dragging_tree_1(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_list_function(Object);
extern Object reclaim_graphics_list_1(Object);
extern Object reclaim_graphics_tree_1(Object);
extern Object reclaim_image_plane_cursor(Object);
extern Object reclaim_image_plane_cursors(Object);
extern Object reclaim_items_made_incomplete_list(void);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_move_dragging_state_1(Object);
extern Object reclaim_region(Object);
extern Object reclaim_resize_cursor(Object);
extern Object reclaim_selection_handle_spot_1(Object);
extern Object reclaim_selection_highlight(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_structure_if_any(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_transfer_dragging_state_1(Object);
extern Object reclaim_tree_ordering_list_1(Object);
extern Object recompute_external_connections_for_dragging_states(Object);
extern Object recompute_selection_highlights(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object recursive_schedule_task_to_invoke_creation_rules(Object);
extern Object redraw_transfer_representations_of_block(Object,Object);
extern Object reenter_editor_if_not_hand_placed(Object);
extern Object regenerate_optimized_constant(Object);
extern Object release_mouse_pointers(Object);
extern Object remove_as_block_being_dragged(Object);
extern Object remove_as_block_being_moved(Object);
extern Object remove_as_inferior_block(Object,Object);
extern Object remove_as_subblock(Object,Object,Object);
extern Object remove_block_from_xor_overlay(Object);
extern Object remove_image_plane_cursor(Object,Object);
extern Object remove_kink_and_add_bend(Object,Object,Object);
extern Object remove_object_from_dragging_context(Object);
extern Object replace_selection_highlight(Object,Object);
extern Object replenish_dragging_cons_pool(void);
extern Object replenish_dragging_list_pool(Object);
extern Object require_that_image_plane_be_visible(int,...);
extern Object resize_cursor_p(Object);
extern Object resize_items_per_resize_cursor(Object,Object,Object,Object);
extern Object restore_outline_of_image_plane_being_dragged(Object,Object);
extern Object return_from_current_workstation_context(int,...);
extern Object return_from_dragging_context(Object);
extern Object return_from_dragging_context_to_move_image_plane(Object);
extern Object return_from_move_dragging_style(Object);
extern Object return_from_transfer_dragging_style(Object);
extern Object reverse_list_using_gensym_conses(Object);
extern Object scalef_function(Object,Object);
extern Object scope_cons(Object,Object);
extern Object select_objects_after_transfer(Object,Object,Object);
extern Object selection_enabled_p(int,...);
extern Object selection_handle_mouse_cursor(Object);
extern Object selection_handle_positions(Object);
extern Object selection_handle_spot_structure_memory_usage(void);
extern Object selection_handles_visible_p(Object,Object);
extern Object selection_highlight_cursor_p(Object);
extern Object selection_rectangle_cursor_p(Object);
extern Object send_ws_representations_connection_moved(Object);
extern Object send_ws_representations_item_insert_as_subblock(Object,Object,Object);
extern Object set_current_background_color_value(Object);
extern Object shift_and_draw_blocks_being_transferred(Object,Object,Object,Object,Object,Object);
extern Object shift_block(Object,Object,Object);
extern Object shift_blocks_with_their_external_connections(int,...);
extern Object show_selection_handles_p(int,...);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object start_rendering_dragging_state_for_move_or_transfer(Object);
extern Object stop_rendering_dragging_state_for_move_or_transfer(Object);
extern Object sync_graphics_on_current_window(void);
extern Object synchronize_icp_on_window_with_drawing(Object,Object,Object,Object,Object);
extern Object synchronize_transfer_mode(void);
extern Object text_cell_p(Object);
extern Object tformat_text_string(int,...);
extern Object thing_selected_p(Object,Object);
extern Object toggle_side_for_loose_end(Object,Object);
extern Object track_mouse_for_drag_handle(Object);
extern Object transfer_blocks_with_their_external_connections(Object,Object,Object,Object,Object);
extern Object transfer_dragging_state_structure_memory_usage(void);
extern Object transfer_grouped_blocks_with_their_external_connections(Object,Object,Object,Object,Object,Object);
extern Object transfer_workspace_subblock(Object,Object,Object);
extern Object tree_ordering_cons_1(Object,Object);
extern Object trigger_user_icon_movement_rules_for_blocks(Object);
extern Object update_connection_images(Object,Object,Object);
extern Object update_extreme_edges_for_item_being_moved(Object);
extern Object update_extreme_edges_from_block_bounds(Object);
extern Object update_extreme_edges_from_connection(Object);
extern Object update_images(int,...);
extern Object update_images_of_block(Object,Object,Object);
extern Object update_images_of_blocks_and_connections_being_moved(Object,Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_subscriptions_for_add_item_to_workspace(Object,Object);
extern Object valid_image_plane_p(Object);
extern Object workspace_showing_on_ui_client_p(Object);
extern Object workstation_context_specifics_blackboard_function(Object);
extern Object wrap_up_move_after_drag(Object);
extern Object wrap_up_transfer_after_drag(Object);
extern Object wrap_up_transfer_after_drag_1(Object,Object);
extern Object x_in_window_blackboard_function(Object);
extern Object x_in_workspace_blackboard_function(Object);
extern Object x_within_workspace(int,...);
extern Object y_in_window_blackboard_function(Object);
extern Object y_in_workspace_blackboard_function(Object);
extern Object y_within_workspace(int,...);

#else

extern Object abort_current_workstation_context();
extern Object add_bend_to_connection();
extern Object add_cursors_to_current_window();
extern Object add_from_pane_cursor_to_current_window();
extern Object add_image_plane_border_as_pane_cursor();
extern Object add_image_plane_cursor();
extern Object add_image_plane_cursors_to_current_window();
extern Object add_keymap_to_workstation_context();
extern Object add_mouse_pointer_to_guardians_of_workstation_context();
extern Object add_new_connection_to_block();
extern Object add_pane_cursor();
extern Object add_plus_sign_as_pane_cursor();
extern Object add_rectangle_to_region();
extern Object add_subblock();
extern Object add_xor_overlay_to_current_image_plane();
extern Object adjust_rectangle_edges();
extern Object ancestor_p();
extern Object beep_at_user();
extern Object begin_dragging_selection_handle();
extern Object block_of_edit_workspace_p();
extern Object block_transferable_p();
extern Object blocks_transferable_p();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object car_or_atom();
extern Object change_color_of_selection_highlight();
extern Object change_connection_deltas_for_object_being_dragged();
extern Object change_size_per_bounding_rectangle();
extern Object check_completion_of_transfer_after_drag();
extern Object check_if_dragging_confined_due_to_superblock();
extern Object clean_up_image_plane_cursor();
extern Object clear_optimized_constants();
extern Object compute_connection_vertices();
extern Object compute_movement_contraints();
extern Object compute_movement_limits_for_blocks();
extern Object compute_snap_grid_for_block();
extern Object compute_snap_grid_for_transfer();
extern Object compute_stretched_links_of_connection_being_dragged();
extern Object connection_external_to_blocks_p();
extern Object connection_is_straight_qm();
extern Object connections_moved_for_blocks_moved();
extern Object constant_queue_next();
extern Object copy_frame_serial_number();
extern Object copy_list_using_dragging_conses_1();
extern Object copy_list_using_gensym_conses_1();
extern Object copy_list_using_tree_ordering_conses_1();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_tree_using_dragging_conses_1();
extern Object copy_tree_using_gensym_conses_1();
extern Object copy_tree_using_graphics_conses_1();
extern Object create_resize_cursor();
extern Object decode_window_position();
extern Object delete_blocks_from_list_in_limbo();
extern Object delete_dragging_cons_1();
extern Object delete_dragging_element_1();
extern Object delete_frame();
extern Object delete_graphics_element_1();
extern Object delete_last_bend_from_connection();
extern Object delete_pane_cursor();
extern Object detail_pane();
extern Object determine_extreme_edges_for_item_being_moved();
extern Object determine_extreme_edges_of_blocks_and_connections();
extern Object direct_structure_method();
extern Object drag_handle_state_structure_memory_usage();
extern Object drag_outline_if_appropriate();
extern Object dragging_cons_1();
extern Object dragging_cons_function();
extern Object dragging_cons_memory_usage();
extern Object dragging_list_2();
extern Object dragging_list_3();
extern Object dragging_list_4();
extern Object dragging_list_trace_hook();
extern Object dragging_state_structure_memory_usage();
extern Object draw_block();
extern Object draw_block_or_blocks_in_dragging_state();
extern Object draw_block_possibly_with_frame();
extern Object draw_blocks_and_connections_being_moved();
extern Object draw_connection();
extern Object draw_dotted_rectangle();
extern Object draw_icon_from_description();
extern Object draw_image_plane_cursor();
extern Object draw_image_plane_cursor_1();
extern Object draw_or_erase_all_selection_highlights();
extern Object draw_rectangle_outline_in_window();
extern Object draw_resize_cursor();
extern Object draw_selection_handle();
extern Object draw_selection_handles_for_block();
extern Object draw_selection_handles_for_connection();
extern Object draw_selection_handles_for_text_cell();
extern Object draw_selection_highlight();
extern Object draw_selection_highlight_1();
extern Object draw_selection_rectangle_cursor();
extern Object draw_wide_polyline();
extern Object end_icp_message_group();
extern Object enlarge_workspace_if_necessary();
extern Object enter_context_in_current_workstation();
extern Object enter_dialog();
extern Object enter_drag_handle_context_function();
extern Object enter_dragging_context_1();
extern Object enter_image_plane_dragging_context();
extern Object enter_move_dragging_context();
extern Object enter_transfer_dragging_context();
extern Object erase_and_reclaim_all_selection_highlights();
extern Object erase_outline_of_image_plane_being_dragged();
extern Object erase_transfer_representations_of_block();
extern Object establish_next_workstation_context_continuation();
extern Object event_update_status_of_block_showing();
extern Object find_object_near_loose_end_being_dragged();
extern Object find_object_near_mouse();
extern Object find_selection_highlight();
extern Object find_selection_highlight_position();
extern Object find_selection_highlights();
extern Object finish_connection_dragging();
extern Object finish_drag_handle();
extern Object force_process_drawing_if_appropriate();
extern Object force_workspace_drawing();
extern Object frame_serial_number_setf_helper_1();
extern Object frames_currently_being_dragged_have_been_deleted_p();
extern Object gather_connections_for_block();
extern Object generate_float_vector();
extern Object generate_spot_for_selection_handle();
extern Object gensym_cons_1();
extern Object get_block_at_other_end_of_connection();
extern Object get_connection_for_loose_end();
extern Object get_lookup_slot_value_given_default();
extern Object get_module_block_is_in();
extern Object get_table_cell_edges();
extern Object get_table_for_cell();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object graphics_cons_1();
extern Object graphics_list_4();
extern Object group_blocks_for_move_or_transfer();
extern Object handle_connection_click_near_last_anchor_point();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object ignore_snap_grid_in_transfer_operations_p();
extern Object image_plane_blackboard_function();
extern Object image_plane_selected_p();
extern Object in_order_p();
extern Object install_item_in_model_if_models_used();
extern Object invalidate_region_of_image_plane();
extern Object invalidate_selection_handles();
extern Object inverse_scalef_function();
extern Object invoke_connection_handler_if_any();
extern Object invoke_rules_for_direct_connection_chaining();
extern Object invoke_rules_for_indirect_connection_chaining();
extern Object invoke_rules_for_resizement_chaining();
extern Object invoke_rules_for_user_icon_movement_if_necessary();
extern Object item_to_transfer_connected_stack_error();
extern Object item_x_position();
extern Object item_y_position();
extern Object join_two_connections();
extern Object launch_compile_to_bring_kb_up_to_date();
extern Object launch_compile_to_bring_kb_up_to_date_and_return_from_transfer_dragging();
extern Object list_external_connections_to_drag();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object loose_end_dragging_outline_p();
extern Object loose_end_near_last_anchor_point_qm();
extern Object make_context_description();
extern Object make_description_of_barrier_to_destabilization();
extern Object make_drag_handle_state_1();
extern Object make_dragging_list_1();
extern Object make_dragging_state_1();
extern Object make_empty_region();
extern Object make_gensym_list_1();
extern Object make_graphics_list_1();
extern Object make_junction();
extern Object make_keymap();
extern Object make_move_dragging_state_1();
extern Object make_outline_for_blocks_to_drag();
extern Object make_outline_for_image_plane_to_drag();
extern Object make_permanent_drag_handle_state_structure_internal();
extern Object make_permanent_dragging_state_structure_internal();
extern Object make_permanent_move_dragging_state_structure_internal();
extern Object make_permanent_selection_handle_spot_structure_internal();
extern Object make_permanent_transfer_dragging_state_structure_internal();
extern Object make_selection_handle_spot_1();
extern Object make_thread_array();
extern Object make_transfer_dragging_state_1();
extern Object map_to_color_value();
extern Object map_to_color_value_1();
extern Object memq_function();
extern Object mouse_down_in_dragging_state();
extern Object mouse_down_p();
extern Object mouse_motion_in_dragging_state();
extern Object mouse_pointer_blackboard_function();
extern Object mouse_up_in_dragging_state();
extern Object move_all_selection_highlights();
extern Object move_blocks_with_their_external_connections();
extern Object move_connection_vertex_by();
extern Object move_dragging_state_structure_memory_usage();
extern Object move_image_plane();
extern Object move_image_plane_upon_continuation_after_dragging();
extern Object move_or_transfer_blocks_being_dragged_if_appropriate();
extern Object move_outline_of_image_plane_being_dragged();
extern Object move_pane_cursor();
extern Object move_resize_cursor();
extern Object move_selection_highlight();
extern Object move_selection_highlights();
extern Object movement_limits_for_block();
extern Object mutate_global_property();
extern Object nip_begin_drawing();
extern Object nip_end_drawing();
extern Object no_manual_connections_p();
extern Object non_menu_choice_permitted_p();
extern Object note_change_to_superior_of_block_or_blocks();
extern Object note_dependent_or_stable_status_change();
extern Object note_kb_state_change();
extern Object note_modification_of_module_for_clear_text();
extern Object notify_user();
extern Object offer_to_recompile_after_transfer();
extern Object outstanding_drag_handle_state_count();
extern Object outstanding_dragging_conses();
extern Object outstanding_dragging_state_count();
extern Object outstanding_move_dragging_state_count();
extern Object outstanding_selection_handle_spot_count();
extern Object outstanding_transfer_dragging_state_count();
extern Object paint_rectangle_outline_in_window();
extern Object place_connection_if_orthogonal_qm();
extern Object printing_image_plane_p();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object push_selection_handle_spot();
extern Object put_kink_into_connection_if_straight();
extern Object reason_permanent_items_module_is_not_editable();
extern Object reclaim_drag_handle_state_1();
extern Object reclaim_dragging_cons_1();
extern Object reclaim_dragging_cons_function();
extern Object reclaim_dragging_list_1();
extern Object reclaim_dragging_list_function();
extern Object reclaim_dragging_list_of_pane_cursors();
extern Object reclaim_dragging_list_star_1();
extern Object reclaim_dragging_state_1();
extern Object reclaim_dragging_tree_1();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_list_function();
extern Object reclaim_graphics_list_1();
extern Object reclaim_graphics_tree_1();
extern Object reclaim_image_plane_cursor();
extern Object reclaim_image_plane_cursors();
extern Object reclaim_items_made_incomplete_list();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_move_dragging_state_1();
extern Object reclaim_region();
extern Object reclaim_resize_cursor();
extern Object reclaim_selection_handle_spot_1();
extern Object reclaim_selection_highlight();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_structure_if_any();
extern Object reclaim_text_string();
extern Object reclaim_transfer_dragging_state_1();
extern Object reclaim_tree_ordering_list_1();
extern Object recompute_external_connections_for_dragging_states();
extern Object recompute_selection_highlights();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object recursive_schedule_task_to_invoke_creation_rules();
extern Object redraw_transfer_representations_of_block();
extern Object reenter_editor_if_not_hand_placed();
extern Object regenerate_optimized_constant();
extern Object release_mouse_pointers();
extern Object remove_as_block_being_dragged();
extern Object remove_as_block_being_moved();
extern Object remove_as_inferior_block();
extern Object remove_as_subblock();
extern Object remove_block_from_xor_overlay();
extern Object remove_image_plane_cursor();
extern Object remove_kink_and_add_bend();
extern Object remove_object_from_dragging_context();
extern Object replace_selection_highlight();
extern Object replenish_dragging_cons_pool();
extern Object replenish_dragging_list_pool();
extern Object require_that_image_plane_be_visible();
extern Object resize_cursor_p();
extern Object resize_items_per_resize_cursor();
extern Object restore_outline_of_image_plane_being_dragged();
extern Object return_from_current_workstation_context();
extern Object return_from_dragging_context();
extern Object return_from_dragging_context_to_move_image_plane();
extern Object return_from_move_dragging_style();
extern Object return_from_transfer_dragging_style();
extern Object reverse_list_using_gensym_conses();
extern Object scalef_function();
extern Object scope_cons();
extern Object select_objects_after_transfer();
extern Object selection_enabled_p();
extern Object selection_handle_mouse_cursor();
extern Object selection_handle_positions();
extern Object selection_handle_spot_structure_memory_usage();
extern Object selection_handles_visible_p();
extern Object selection_highlight_cursor_p();
extern Object selection_rectangle_cursor_p();
extern Object send_ws_representations_connection_moved();
extern Object send_ws_representations_item_insert_as_subblock();
extern Object set_current_background_color_value();
extern Object shift_and_draw_blocks_being_transferred();
extern Object shift_block();
extern Object shift_blocks_with_their_external_connections();
extern Object show_selection_handles_p();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object start_rendering_dragging_state_for_move_or_transfer();
extern Object stop_rendering_dragging_state_for_move_or_transfer();
extern Object sync_graphics_on_current_window();
extern Object synchronize_icp_on_window_with_drawing();
extern Object synchronize_transfer_mode();
extern Object text_cell_p();
extern Object tformat_text_string();
extern Object thing_selected_p();
extern Object toggle_side_for_loose_end();
extern Object track_mouse_for_drag_handle();
extern Object transfer_blocks_with_their_external_connections();
extern Object transfer_dragging_state_structure_memory_usage();
extern Object transfer_grouped_blocks_with_their_external_connections();
extern Object transfer_workspace_subblock();
extern Object tree_ordering_cons_1();
extern Object trigger_user_icon_movement_rules_for_blocks();
extern Object update_connection_images();
extern Object update_extreme_edges_for_item_being_moved();
extern Object update_extreme_edges_from_block_bounds();
extern Object update_extreme_edges_from_connection();
extern Object update_images();
extern Object update_images_of_block();
extern Object update_images_of_blocks_and_connections_being_moved();
extern Object update_object_pool_meters_list();
extern Object update_subscriptions_for_add_item_to_workspace();
extern Object valid_image_plane_p();
extern Object workspace_showing_on_ui_client_p();
extern Object workstation_context_specifics_blackboard_function();
extern Object wrap_up_move_after_drag();
extern Object wrap_up_transfer_after_drag();
extern Object wrap_up_transfer_after_drag_1();
extern Object x_in_window_blackboard_function();
extern Object x_in_workspace_blackboard_function();
extern Object x_within_workspace();
extern Object y_in_window_blackboard_function();
extern Object y_in_workspace_blackboard_function();
extern Object y_within_workspace();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Available_dragging_conses, Qavailable_dragging_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_dragging_conses_tail, Qavailable_dragging_conses_tail);
extern Object Available_dragging_conses_tail_vector;
extern Object Available_dragging_conses_vector;
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_tree_ordering_conses_tail_vector;
extern Object Available_tree_ordering_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_drag_handle_states, Qchain_of_available_drag_handle_states);
extern Object Chain_of_available_drag_handle_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_dragging_states, Qchain_of_available_dragging_states);
extern Object Chain_of_available_dragging_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_move_dragging_states, Qchain_of_available_move_dragging_states);
extern Object Chain_of_available_move_dragging_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_selection_handle_spots, Qchain_of_available_selection_handle_spots);
extern Object Chain_of_available_selection_handle_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_transfer_dragging_states, Qchain_of_available_transfer_dragging_states);
extern Object Chain_of_available_transfer_dragging_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chart, Qchart);
extern Object Class_description_gkbprop;
extern Object Classes_that_do_not_normally_connect;
DECLARE_VARIABLE_WITH_SYMBOL(Compiled_items_deferred_for_analysis, Qcompiled_items_deferred_for_analysis);
extern Object Cons_pool_conses_to_make_at_a_time;
extern Object Constant_mouse_leeway;
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_color_map, Qcurrent_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(Current_dragging_states, Qcurrent_dragging_states);
DECLARE_VARIABLE_WITH_SYMBOL(Current_draw_document_p, Qcurrent_draw_document_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_draw_paper_p, Qcurrent_draw_paper_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_priority, Qcurrent_drawing_priority);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane_qm, Qcurrent_image_plane_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_image_plane, Qcurrent_native_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_pane, Qcurrent_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_consistency_analysis_qm, Qdefer_consistency_analysis_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Do_icp_flow_control_qm, Qdo_icp_flow_control_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_invoke_rules_for_user_icon_movement_qm, Qdo_not_invoke_rules_for_user_icon_movement_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_update_selection_highlights, Qdo_not_update_selection_highlights);
DECLARE_VARIABLE_WITH_SYMBOL(Drag_handle_state_count, Qdrag_handle_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Dragging_cons_counter, Qdragging_cons_counter);
extern Object Dragging_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Dragging_state_count, Qdragging_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_on_window, Qdrawing_on_window);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_parameters, Qdrawing_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Erase_instead_qm, Qerase_instead_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Explicit_dragger_x_in_window_qm, Qexplicit_dragger_x_in_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Explicit_dragger_y_in_window_qm, Qexplicit_dragger_y_in_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_bottom_edge_so_far, Qextreme_bottom_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_left_edge_so_far, Qextreme_left_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_right_edge_so_far, Qextreme_right_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Extreme_top_edge_so_far, Qextreme_top_edge_so_far);
DECLARE_VARIABLE_WITH_SYMBOL(Flush_graphics_immediately_qm, Qflush_graphics_immediately_qm);
DECLARE_VARIABLE_WITH_SYMBOL(For_image_plane, Qfor_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_v5_mode_windows_p, Qg2_has_v5_mode_windows_p);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
extern Object Icp_connection_closed;
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Items_made_incomplete_were_recorded_qm, Qitems_made_incomplete_were_recorded_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_bottom_edge_of_visible_workspace_area, Qloose_bottom_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_class_description, Qloose_end_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_left_edge_of_visible_workspace_area, Qloose_left_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_right_edge_of_visible_workspace_area, Qloose_right_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_top_edge_of_visible_workspace_area, Qloose_top_edge_of_visible_workspace_area);
extern Object Maximum_x_or_y_separation_allowing_fixnum_vector_distance_calculation;
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Move_dragging_state_count, Qmove_dragging_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
DECLARE_VARIABLE_WITH_SYMBOL(Non_kb_workspace_class_description, Qnon_kb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Note_as_kb_state_change_qm, Qnote_as_kb_state_change_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(On_window_with_drawing, Qon_window_with_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(On_window_without_drawing, Qon_window_without_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Operation_around_record_of_items_made_incomplete, Qoperation_around_record_of_items_made_incomplete);
DECLARE_VARIABLE_WITH_SYMBOL(Outer_native_image_plane, Qouter_native_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Recording_items_made_incomplete_qm, Qrecording_items_made_incomplete_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Region_invalidation_is_preferred, Qregion_invalidation_is_preferred);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Saved_position_or_next_lower_thing, Qsaved_position_or_next_lower_thing);
extern Object Scalable_mouse_leeway;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Selection_handle_hit_distance;
DECLARE_VARIABLE_WITH_SYMBOL(Selection_handle_icon, Qselection_handle_icon);
extern Object Selection_handle_radius;
DECLARE_VARIABLE_WITH_SYMBOL(Selection_handle_spot_count, Qselection_handle_spot_count);
extern Object Selection_highlight_line_width;
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object The_type_description_of_drag_handle_state;
extern Object The_type_description_of_dragging_state;
extern Object The_type_description_of_move_dragging_state;
extern Object The_type_description_of_selection_handle_spot;
extern Object The_type_description_of_transfer_dragging_state;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Transfer_dragging_state_count, Qtransfer_dragging_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Transfer_in_progress, Qtransfer_in_progress);
extern Object Tree_traversal_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Update_images_in_xor_overlay_p, Qupdate_images_in_xor_overlay_p);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_name_box_class_description, Qworkspace_name_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
