/* natvtw.h -- Header File for natvtw.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qclose;
extern Object Qcount;
extern Object Qequal;
extern Object Qerror;
extern Object Qexport;
extern Object Qfill;
extern Object Qfirst;
extern Object Qfloat;
extern Object Kinitial_element;
extern Object Qinteger;
extern Object Qlast;
extern Object Qmember;
extern Object Qposition;
extern Object Qprint;
extern Object Qremove;
extern Object Qset;
extern Object Qsort;
extern Object Qstep;
extern Object Qtype;
extern Object Qunsigned_byte;
extern Object Qvalues;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_color_string_to_menu(Object,Object,Object,Object,Object,Object);
extern Object add_icp_message_handler(Object,Object);
extern Object add_network_info_to_title_if_appropriate(Object,Object);
extern Object add_string_to_menu(Object,Object,Object,Object);
extern Object add_submenu_to_menu(Object,Object,Object,Object);
extern Object adjust_managed_array(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_array(int,...);
extern Object allocate_managed_simple_float_array(Object);
extern Object allocate_offscreen_pixmap(Object,Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object begin_drawing_to_icon_buffer(Object,Object,Object);
extern Object begin_drawing_to_icon_mask(Object,Object,Object);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object c_add_control(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_chart_add_str_to_struct(Object);
extern Object c_chart_set_string(Object,Object,Object,Object,Object);
extern Object c_create_chart_view(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_html_view(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_logbook(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_property_grid(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_shortcut_bar(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_tabular_view(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_create_tree_view(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_get_charting_library_version(Object,Object);
extern Object c_html_help(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_list_directory_response(Object,Object,Object,Object,Object,Object);
extern Object c_list_sys_drives_response(Object);
extern Object c_make_dialog(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_manage_animation(Object,Object,Object,Object,Object);
extern Object c_manage_chart_view(Object,Object,Object,Object,Object,Object);
extern Object c_manage_html_view(Object,Object,Object);
extern Object c_manage_logbook(Object,Object,Object,Object,Object);
extern Object c_manage_notification(Object,Object,Object,Object,Object);
extern Object c_manage_pane(Object,Object,Object,Object,Object,Object,Object);
extern Object c_manage_property_grid(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_manage_shortcut_bar(Object,Object,Object,Object,Object,Object);
extern Object c_manage_status_bar(Object,Object,Object,Object);
extern Object c_manage_tabular_view(Object,Object,Object,Object,Object,Object,Object);
extern Object c_manage_tree_view(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_note_progress(Object,Object);
extern Object c_post_dialog(Object,Object,Object,Object);
extern Object c_print_dialog(Object,Object,Object,Object,Object,Object);
extern Object c_print_window(Object,Object,Object);
extern Object c_start_doc(Object,Object);
extern Object c_start_page(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_x11_draw_string(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object c_x11_set_window_title(Object,Object);
extern Object cajole_into_fixnum(Object,Object);
extern Object cajole_into_float(Object);
extern Object cajole_into_string(Object);
extern Object car_or_atom(Object);
extern Object cdr_or_atom(Object);
extern Object chart_export_format(Object);
extern Object chart_property_p(Object);
extern Object chart_set_double_array(Object,Object,Object,Object,Object,Object);
extern Object chart_set_int_array(Object,Object,Object,Object,Object,Object);
extern Object chart_set_string_array(Object,Object,Object,Object,Object,Object);
extern Object charting_library_version_qm(void);
extern Object clear_nms_menu_for_hmenu(Object);
extern Object clear_nms_menu_for_hmenu_tree(Object);
extern Object clear_optimized_constants(void);
extern Object compute_percentage(Object,Object);
extern Object compute_width_of_text_line(int,...);
extern Object copy_as_wide_string(Object);
extern Object copy_foreign_string_arg_if_appropriate(Object);
extern Object copy_null_terminated_string_as_text_string(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object create_native_menu(Object,Object,Object);
extern Object create_unique_native_menu_item_id(Object,Object);
extern Object delete_balanced_binary_tree_entry(Object,Object,Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object destroy_native_icons(Object);
extern Object destroy_pane_locally(Object,Object);
extern Object dialog_icon_handle(Object);
extern Object direct_structure_method(Object,Object);
extern Object discard_queued_modal_dialogs(void);
extern Object dlg_pack_init_data(Object,Object);
extern Object dlg_unpack_result_data(Object,Object);
extern Object emit_icp_read_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object emit_icp_write_trace(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object encode_dock_and_neighbor(Object,Object,Object);
extern Object end_drawing_to_icon(Object);
extern Object end_icp_message_group(void);
extern Object enlarge_index_space(Object,Object);
extern Object enqueue_local_event(int,...);
extern Object enqueue_native_menu_choice(Object,Object,Object);
extern Object ensure_pixmap_of_size(Object,Object,Object,Object,Object);
extern Object export_chart_view(Object,Object);
extern Object extend_current_gensym_string(int,...);
extern Object find_native_window_by_handle(Object,Object);
extern Object find_nms_menu_for_hmenu(Object,Object);
extern Object flatten_binary_tree(Object);
extern Object flatten_nms_menu_for_hmenu(Object);
extern Object float_to_words(Object);
extern Object flush_icp_output_ports(void);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object gensym_window_has_not_been_reprocessed_p(Object,Object);
extern Object get_button_style(Object);
extern Object get_dock_code(Object);
extern Object get_gensym_window_of_native_window(Object);
extern Object get_local_ui_toolkit_name(void);
extern Object get_neighbor_id(Object,Object);
extern Object get_raw_network_info(void);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_icp_html_help(void);
extern Object handle_icp_html_help__body(Object,Object,Object);
extern Object handle_icp_html_help_ex(void);
extern Object handle_icp_html_help_ex__body(Object,Object);
extern Object handle_icp_list_directory_response(void);
extern Object handle_icp_list_directory_response__body(Object,Object);
extern Object handle_icp_list_sys_drives_response(void);
extern Object handle_icp_list_sys_drives_response__body(Object);
extern Object handle_icp_manage_chart_view(void);
extern Object handle_icp_manage_chart_view__body(Object,Object,Object,Object,Object);
extern Object handle_icp_manage_dialog(void);
extern Object handle_icp_manage_dialog__body(Object,Object,Object,Object);
extern Object handle_icp_manage_html_view(void);
extern Object handle_icp_manage_html_view__body(Object,Object,Object,Object);
extern Object handle_icp_manage_logbook(void);
extern Object handle_icp_manage_logbook__body(Object,Object,Object,Object,Object,Object);
extern Object handle_icp_manage_native_control(void);
extern Object handle_icp_manage_native_control__body(Object,Object,Object,Object);
extern Object handle_icp_manage_native_icons(void);
extern Object handle_icp_manage_native_icons__body(Object,Object,Object,Object,Object);
extern Object handle_icp_manage_pane(void);
extern Object handle_icp_manage_pane__body(Object,Object,Object,Object);
extern Object handle_icp_manage_progress_bar(void);
extern Object handle_icp_manage_progress_bar__body(Object,Object,Object,Object);
extern Object handle_icp_manage_property_grid(void);
extern Object handle_icp_manage_property_grid__body(Object,Object,Object,Object,Object);
extern Object handle_icp_manage_shortcut_bar(void);
extern Object handle_icp_manage_shortcut_bar__body(Object,Object,Object,Object);
extern Object handle_icp_manage_status_bar(void);
extern Object handle_icp_manage_status_bar__body(Object,Object,Object);
extern Object handle_icp_manage_tabular_view(void);
extern Object handle_icp_manage_tabular_view__body(Object,Object,Object,Object);
extern Object handle_icp_manage_tree_view(void);
extern Object handle_icp_manage_tree_view__body(Object,Object,Object,Object);
extern Object handle_icp_manage_ui_properties(void);
extern Object handle_icp_manage_ui_properties__body(Object,Object,Object);
extern Object handle_icp_messages(Object);
extern Object handle_icp_native_printing_control(void);
extern Object handle_icp_native_printing_control__body(Object,Object);
extern Object handle_icp_native_printing_dialog(void);
extern Object handle_icp_native_printing_dialog__body(Object,Object,Object);
extern Object handle_icp_native_printing_ex(void);
extern Object handle_icp_native_printing_ex__body(Object,Object,Object,Object);
extern Object handle_icp_native_printing_start_page(void);
extern Object handle_icp_native_printing_start_page__body(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nms_append_control(void);
extern Object handle_icp_nms_append_control__body(Object,Object,Object);
extern Object handle_icp_nms_append_control_ex(void);
extern Object handle_icp_nms_append_control_ex__body(Object,Object,Object,Object,Object);
extern Object handle_icp_nms_append_menu_item(void);
extern Object handle_icp_nms_append_menu_item__body(Object,Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nms_append_special(void);
extern Object handle_icp_nms_append_special__body(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nms_check_menu_item(void);
extern Object handle_icp_nms_check_menu_item__body(Object,Object,Object,Object);
extern Object handle_icp_nms_check_radio_item(void);
extern Object handle_icp_nms_check_radio_item__body(Object,Object,Object,Object,Object,Object);
extern Object handle_icp_nms_create_control(void);
extern Object handle_icp_nms_create_control__body(Object,Object,Object,Object,Object);
extern Object handle_icp_nms_create_menu(void);
extern Object handle_icp_nms_create_menu__body(Object,Object,Object,Object);
extern Object handle_icp_nms_delete_control(void);
extern Object handle_icp_nms_delete_control__body(Object,Object,Object);
extern Object handle_icp_nms_delete_menu(void);
extern Object handle_icp_nms_delete_menu__body(Object,Object,Object);
extern Object handle_icp_nms_dismiss(void);
extern Object handle_icp_nms_dismiss__body(Object);
extern Object handle_icp_nms_enable_items(void);
extern Object handle_icp_nms_enable_items__body(Object,Object);
extern Object handle_icp_nms_enable_menu_item(void);
extern Object handle_icp_nms_enable_menu_item__body(Object,Object,Object,Object);
extern Object handle_icp_nms_modify_control(void);
extern Object handle_icp_nms_modify_control__body(Object,Object,Object,Object);
extern Object handle_icp_nms_modify_menu_item(void);
extern Object handle_icp_nms_modify_menu_item__body(Object,Object,Object,Object);
extern Object handle_icp_nms_pop_up_menu(void);
extern Object handle_icp_nms_pop_up_menu__body(Object,Object,Object,Object);
extern Object handle_icp_nms_reset(void);
extern Object handle_icp_nms_reset__body(Object,Object);
extern Object handle_icp_nms_set_iconsize(void);
extern Object handle_icp_nms_set_iconsize__body(Object);
extern Object handle_icp_nms_set_menu_bar(void);
extern Object handle_icp_nms_set_menu_bar__body(Object,Object);
extern Object handle_icp_nms_set_menu_flags(void);
extern Object handle_icp_nms_set_menu_flags__body(Object,Object,Object,Object);
extern Object handle_icp_nms_set_theme(void);
extern Object handle_icp_nms_set_theme__body(Object,Object);
extern Object handle_icp_paint_icon_in_current_window(void);
extern Object handle_icp_paint_line_of_text_in_current_window(void);
extern Object handle_icp_post_native_menu(void);
extern Object handle_icp_post_native_menu__body(Object,Object,Object,Object,Object);
extern Object handle_icp_print_native_window(void);
extern Object handle_icp_print_native_window__body(Object,Object);
extern Object handle_icp_reset_native_controls(void);
extern Object handle_icp_reset_native_controls__body(void);
extern Object handle_icp_set_window_title(void);
extern Object handle_icp_set_window_title__body(Object,Object);
extern Object handle_icp_tabbed_mdi_mode(void);
extern Object handle_icp_tabbed_mdi_mode__body(Object,Object,Object);
extern Object handle_print_window_event(Object,Object);
extern Object html_help_ex(int,...);
extern Object icon_mask_pixmap(Object,Object,Object);
extern Object icon_polychrome_pixmap(Object,Object,Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object icp_error_internal(Object,Object,Object,Object,Object);
extern Object icp_list_2(Object,Object);
extern Object icp_list_4(Object,Object,Object,Object);
extern Object icp_message_functions_icp_prologue(Object);
extern Object instantaneous_icp_reader_byte_count(void);
extern Object instantaneous_icp_writer_byte_count(void);
extern Object intern_wide_string(int,...);
extern Object item_number_given_item_id(Object);
extern Object item_uuid(Object);
extern Object lengthw(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object locally_initable_pane_property_p(Object);
extern Object locally_initable_view_property_p(Object);
extern Object make_basic_native_window(Object,Object,Object,Object,Object);
extern Object make_corresponding_icp_gensym_window(Object);
extern Object make_corresponding_icp_symbol(Object);
extern Object make_gensym_list_1(Object);
extern Object make_icp_list_1(Object);
extern Object make_nms_menu_1(void);
extern Object make_nms_menu_for_hmenu(void);
extern Object make_nms_menu_for_hmenu_hash_vector(void);
extern Object make_nms_menu_item_1(void);
extern Object make_permanent_nms_menu_for_hmenu_hash_vector_43_vector_internal(void);
extern Object make_permanent_nms_menu_item_structure_internal(void);
extern Object make_permanent_nms_menu_structure_internal(void);
extern Object make_thread_array(Object);
extern Object manage_animation(int,...);
extern Object manage_animation_1(Object,Object);
extern Object manage_chart_view_1(Object,Object,Object,Object,Object);
extern Object manage_dialog(Object,Object,Object,Object);
extern Object manage_dialog_1(Object,Object,Object,Object);
extern Object manage_dialog_icp(Object,Object,Object,Object,Object);
extern Object manage_logbook_1(int,...);
extern Object manage_native_window_locally(Object,Object,Object);
extern Object manage_notification(int,...);
extern Object manage_notification_1(Object,Object);
extern Object manage_pane_1(Object,Object,Object);
extern Object manage_pane_locally(Object,Object,Object);
extern Object manage_property_grid_1(Object,Object,Object,Object,Object);
extern Object manage_shortcut_bar_1(Object,Object,Object,Object);
extern Object manage_status_bar_1(Object,Object);
extern Object manage_tabular_view_1(Object,Object,Object,Object);
extern Object manage_tree_view_locally(Object,Object,Object);
extern Object manage_ui_properties_1(Object,Object,Object);
extern Object map_to_color_value(Object);
extern Object map_to_color_value_1(Object);
extern Object memq_function(Object,Object);
extern Object menu_handle_given_item_id(Object);
extern Object modify_status_bar_pane_1(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_nms_menu_for_hmenu_tree_for_hash_tree_entry(Object,Object,Object);
extern Object n_32bit_integer_high_part(Object);
extern Object n_32bit_integer_low_part(Object);
extern Object native_animation_control_p(Object);
extern Object native_menu_bar_p(Object);
extern Object native_pop_up_menus_p(Object);
extern Object native_printing_abort_printing(Object);
extern Object native_printing_begin(Object);
extern Object native_printing_end(Object);
extern Object native_printing_end_doc(Object);
extern Object native_printing_end_page(Object);
extern Object native_printing_start_doc(Object);
extern Object native_printing_start_page(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object native_progress_bar_p(Object);
extern Object nms_allocate_control(Object,Object,Object,Object);
extern Object nms_allocate_handle(int,...);
extern Object nms_allocate_menu(int,...);
extern Object nms_allocate_menu_item(int,...);
extern Object nms_append_control_1(Object,Object,Object,Object);
extern Object nms_append_internal(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object nms_built_in_menu_p(Object);
extern Object nms_c_append_menu(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object nms_c_create_combo_box(Object,Object,Object,Object,Object,Object,Object);
extern Object nms_c_create_edit_box(Object,Object,Object,Object);
extern Object nms_c_create_menu(Object,Object);
extern Object nms_c_create_toolbar(Object,Object,Object,Object,Object,Object);
extern Object nms_c_fetch_help_string_result(Object);
extern Object nms_c_manage_control(Object,Object,Object,Object);
extern Object nms_c_modify_menu_item(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object nms_c_set_help(Object,Object,Object);
extern Object nms_control_type_code(Object);
extern Object nms_create_combo_box_2(Object,Object,Object,Object,Object,Object,Object);
extern Object nms_create_edit_box_2(Object,Object,Object,Object);
extern Object nms_deallocate_handle(Object,Object);
extern Object nms_delete_item(Object,Object);
extern Object nms_delete_menu_locally(int,...);
extern Object nms_delete_native_menu(int,...);
extern Object nms_discard_win32_handle(Object);
extern Object nms_ensure_consistent_menu_geometry(Object);
extern Object nms_hard_reset_locally(Object);
extern Object nms_hide_menu_bar(Object);
extern Object nms_lookup_handle(Object,Object);
extern Object nms_lookup_id(Object,Object);
extern Object nms_menu_bar_menu_p(Object);
extern Object nms_menu_bar_menu_type(Object);
extern Object nms_menu_bars_supported_p(Object);
extern Object nms_menu_for_hmenu_hash_vector_43_vector_memory_usage(void);
extern Object nms_menu_handle_to_id(Object);
extern Object nms_menu_id_to_handle(Object,Object);
extern Object nms_menu_item_command_id(Object);
extern Object nms_menu_item_id(Object);
extern Object nms_menu_item_structure_memory_usage(void);
extern Object nms_menu_structure_memory_usage(void);
extern Object nms_menu_table(Object);
extern Object nms_next_handle(Object);
extern Object nms_note_menu_deletion(Object,Object);
extern Object nms_parameter_menu_p(Object);
extern Object nms_pop_up_menu_deferred(Object,Object,Object,Object,Object);
extern Object nms_pop_up_menu_p(Object);
extern Object nms_pop_up_menu_type(Object);
extern Object nms_popup_menus_supported_p(Object);
extern Object nms_push_item(Object,Object);
extern Object nms_reclaim_key(Object);
extern Object nms_reclaim_menu(Object);
extern Object nms_reclaim_menu_1_1(Object);
extern Object nms_reclaim_menu_item(Object);
extern Object nms_reclaim_menu_item_1_1(Object);
extern Object nms_reclaim_menu_or_item(Object);
extern Object nms_record_win32_handle(Object,Object,Object);
extern Object nms_remove_menu_item_locally(Object,Object,Object);
extern Object nms_renumber_items(Object);
extern Object nms_reset_locally(Object,Object);
extern Object nms_revert_to_unconnected_menu_bar(Object);
extern Object nms_set_bit(Object,Object,Object);
extern Object nms_set_theme_1(Object,Object);
extern Object nms_soft_reset_locally(Object);
extern Object nms_supported_on_gensym_window_p(Object);
extern Object nms_toolbar_p(Object);
extern Object nms_wide_menu_p(Object);
extern Object note_progress(int,...);
extern Object note_progress_on_window(Object,Object,Object);
extern Object notify_user_at_console(int,...);
extern Object nstring_upcasew(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object obtain_text_string(Object);
extern Object out_nms_menu_for_hmenu_hash_vector_43_vectors(void);
extern Object outstanding_nms_menu_count(void);
extern Object outstanding_nms_menu_item_count(void);
extern Object paint_icon_in_current_window(Object,Object,Object,Object,Object,Object,Object);
extern Object paint_line_of_text_in_current_window(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object partial_command_p_function(Object);
extern Object pathname_type_as_symbol(Object);
extern Object pct_html_help(int,...);
extern Object pct_manage_property_grid(int,...);
extern Object pct_set_chart_property(Object,Object,Object,Object,Object,Object,Object);
extern Object pechart_enum_value(Object);
extern Object pechart_print_error(Object,Object,Object,Object,Object,Object);
extern Object pechart_property_code(Object);
extern Object pechart_property_type(Object);
extern Object pechart_type_code(int,...);
extern Object plistp(Object);
extern Object populate_property_grid(Object,Object);
extern Object populate_tree_view(Object,Object,Object,Object);
extern Object post_modal_dialog_1(Object,Object,Object,Object,Object,Object,Object);
extern Object post_native_menu(Object,Object,Object,Object,Object,Object);
extern Object print_dialog_1(int,...);
extern Object print_window_1(Object,Object,Object);
extern Object process_property_grid_init_plist(int,...);
extern Object process_shortcut_bar_init_plist(Object,Object);
extern Object process_tabular_view_init_plist(Object,Object);
extern Object process_tree_init_plist(Object,Object);
extern Object process_view_init_plist(int,...);
extern Object process_window_style_options(Object,Object);
extern Object prop_grid_event_name(Object);
extern Object prop_grid_node_opcode(Object);
extern Object prop_grid_opcode(Object);
extern Object prop_grid_sort_code(Object);
extern Object prop_grid_sort_symbol(Object);
extern Object prop_grid_type_code(Object);
extern Object push_optimized_constant(Object);
extern Object queue_insert(Object,Object);
extern Object read_icp_boolean(void);
extern Object read_icp_corresponding_object_index(void);
extern Object read_icp_fixnum(void);
extern Object read_icp_icp_tree(void);
extern Object read_icp_integer(void);
extern Object read_icp_text_string(void);
extern Object read_icp_unsigned_integer(void);
extern Object read_icp_unsigned_integer_qm(void);
extern Object read_icp_wide_string(void);
extern Object reclaim_byte_vector_16(Object);
extern Object reclaim_contents_of_nms_menu_table(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_cons_qm(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_icp_list_1(Object);
extern Object reclaim_icp_tree_1(Object);
extern Object reclaim_icp_tree_of_values(Object);
extern Object reclaim_icp_tree_value(Object);
extern Object reclaim_icp_tree_with_text_strings(Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_managed_array(Object);
extern Object reclaim_managed_simple_float_array(Object);
extern Object reclaim_native_menus(Object,Object,Object);
extern Object reclaim_native_window(Object);
extern Object reclaim_native_window_by_handle(Object,Object);
extern Object reclaim_nms_menu_for_hmenu(Object);
extern Object reclaim_nms_menu_for_hmenu_hash_vector(Object);
extern Object reclaim_partial_command(Object);
extern Object reclaim_pixmap(Object);
extern Object reclaim_raw_network_info(Object,Object);
extern Object reclaim_simple_gensym_string(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_native_menu_c_pointer(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object refresh_native_icon(Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object reset_native_controls(Object);
extern Object resumable_icp_pop(void);
extern Object resumable_icp_pop_list_if_end_marker(void);
extern Object resumable_icp_push(Object);
extern Object rgb_color_p(Object);
extern Object rgb_color_value(Object);
extern Object rgb_from_color(Object);
extern Object save_native_icon(Object,Object,Object,Object);
extern Object sb_fixnum(Object);
extern Object send_icp_html_help(Object,Object,Object);
extern Object send_icp_html_help_ex(Object,Object);
extern Object send_icp_list_directory_response(Object,Object);
extern Object send_icp_list_sys_drives_response(Object);
extern Object send_icp_manage_chart_view(Object,Object,Object,Object,Object);
extern Object send_icp_manage_dialog(Object,Object,Object,Object);
extern Object send_icp_manage_html_view(Object,Object,Object,Object);
extern Object send_icp_manage_logbook(Object,Object,Object,Object,Object,Object);
extern Object send_icp_manage_native_control(Object,Object,Object,Object);
extern Object send_icp_manage_native_icons(Object,Object,Object,Object,Object);
extern Object send_icp_manage_pane(Object,Object,Object,Object);
extern Object send_icp_manage_progress_bar(Object,Object,Object,Object);
extern Object send_icp_manage_property_grid(Object,Object,Object,Object,Object);
extern Object send_icp_manage_shortcut_bar(Object,Object,Object,Object);
extern Object send_icp_manage_status_bar(Object,Object,Object);
extern Object send_icp_manage_tabular_view(Object,Object,Object,Object);
extern Object send_icp_manage_tree_view(Object,Object,Object,Object);
extern Object send_icp_manage_ui_properties(Object,Object,Object);
extern Object send_icp_message(int,...);
extern Object send_icp_native_printing_control(Object,Object);
extern Object send_icp_native_printing_dialog(Object,Object,Object);
extern Object send_icp_native_printing_ex(Object,Object,Object,Object);
extern Object send_icp_native_printing_start_page(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_nms_append_control(Object,Object,Object);
extern Object send_icp_nms_append_control_ex(Object,Object,Object,Object,Object);
extern Object send_icp_nms_append_menu_item(Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_nms_append_special(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object send_icp_nms_check_menu_item(Object,Object,Object,Object);
extern Object send_icp_nms_check_radio_item(Object,Object,Object,Object,Object,Object);
extern Object send_icp_nms_create_control(Object,Object,Object,Object,Object);
extern Object send_icp_nms_create_menu(Object,Object,Object,Object);
extern Object send_icp_nms_delete_control(Object,Object,Object);
extern Object send_icp_nms_delete_menu(Object,Object,Object);
extern Object send_icp_nms_dismiss(Object);
extern Object send_icp_nms_enable_items(Object,Object);
extern Object send_icp_nms_enable_menu_item(Object,Object,Object,Object);
extern Object send_icp_nms_modify_control(Object,Object,Object,Object);
extern Object send_icp_nms_modify_menu_item(Object,Object,Object,Object);
extern Object send_icp_nms_pop_up_menu(Object,Object,Object,Object);
extern Object send_icp_nms_reset(Object,Object);
extern Object send_icp_nms_set_iconsize(Object);
extern Object send_icp_nms_set_menu_bar(Object,Object);
extern Object send_icp_nms_set_menu_flags(Object,Object,Object,Object);
extern Object send_icp_nms_set_theme(Object,Object);
extern Object send_icp_post_native_menu(Object,Object,Object,Object,Object);
extern Object send_icp_print_native_window(Object,Object);
extern Object send_icp_reset_native_controls(void);
extern Object send_icp_set_window_title(Object,Object);
extern Object send_icp_tabbed_mdi_mode(Object,Object,Object);
extern Object set_balanced_binary_tree_entry(Object,Object,Object,Object,Object,Object,Object);
extern Object set_chart_properties(Object,Object);
extern Object set_pane_state_locally(Object,Object,Object);
extern Object set_to_default_window_title(void);
extern Object set_window_title(Object,Object);
extern Object shbar_add_folder(Object,Object,Object,Object);
extern Object shbar_add_item(Object,Object,Object,Object,Object);
extern Object shbar_clear(Object);
extern Object shbar_populate(Object,Object);
extern Object sort_column_value_or_stack_error(Object);
extern Object sorting_order_value_or_stack_error(Object);
extern Object start_writing_icp_message(Object);
extern Object stock_command_id_p(Object);
extern Object string_eq_w(Object,Object);
extern Object stringw(Object);
extern Object sxhashw(Object);
extern Object symbol_namew(Object);
extern Object tabbed_mdi_mode_1(Object,Object,Object);
extern Object tabular_view_add_columns_1(int,...);
extern Object tabular_view_add_rows_1(int,...);
extern Object tabular_view_change_sort_1(Object,Object);
extern Object tabular_view_modify_cells_1(int,...);
extern Object tabular_view_modify_columns_1(int,...);
extern Object tabular_view_modify_rows_1(int,...);
extern Object tabular_view_opcode(Object);
extern Object tbv_fixnum(Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object to_string(Object);
extern Object tree_view_modify_node_1(Object,Object,Object,Object);
extern Object twng_p(Object);
extern Object twrite(Object);
extern Object twrite_long_system_version_string(void);
extern Object twrite_string_and_nul(Object);
extern Object twrite_wide_character(Object);
extern Object ui_stack_error_1(Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object valid_sorting_order_or_stack_error(Object);
extern Object wide_string_substring(Object,Object,Object);
extern Object win32_choice_symbol(Object);
extern Object write_icp_boolean(Object);
extern Object write_icp_corresponding_object_index(Object);
extern Object write_icp_fixnum(Object);
extern Object write_icp_icp_tree(Object);
extern Object write_icp_integer(Object);
extern Object write_icp_list_of_unsigned_integers(Object);
extern Object write_icp_text_string(Object);
extern Object write_icp_unsigned_integer(Object);
extern Object write_icp_unsigned_integer_qm(Object);
extern Object write_icp_wide_string(Object);

#else

extern Object add_color_string_to_menu();
extern Object add_icp_message_handler();
extern Object add_network_info_to_title_if_appropriate();
extern Object add_string_to_menu();
extern Object add_submenu_to_menu();
extern Object adjust_managed_array();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_array();
extern Object allocate_managed_simple_float_array();
extern Object allocate_offscreen_pixmap();
extern Object assq_function();
extern Object begin_drawing_to_icon_buffer();
extern Object begin_drawing_to_icon_mask();
extern Object bytes_per_simple_vector();
extern Object bytes_per_typed_simple_array();
extern Object c_add_control();
extern Object c_chart_add_str_to_struct();
extern Object c_chart_set_string();
extern Object c_create_chart_view();
extern Object c_create_html_view();
extern Object c_create_logbook();
extern Object c_create_property_grid();
extern Object c_create_shortcut_bar();
extern Object c_create_tabular_view();
extern Object c_create_tree_view();
extern Object c_get_charting_library_version();
extern Object c_html_help();
extern Object c_list_directory_response();
extern Object c_list_sys_drives_response();
extern Object c_make_dialog();
extern Object c_manage_animation();
extern Object c_manage_chart_view();
extern Object c_manage_html_view();
extern Object c_manage_logbook();
extern Object c_manage_notification();
extern Object c_manage_pane();
extern Object c_manage_property_grid();
extern Object c_manage_shortcut_bar();
extern Object c_manage_status_bar();
extern Object c_manage_tabular_view();
extern Object c_manage_tree_view();
extern Object c_note_progress();
extern Object c_post_dialog();
extern Object c_print_dialog();
extern Object c_print_window();
extern Object c_start_doc();
extern Object c_start_page();
extern Object c_x11_draw_string();
extern Object c_x11_set_window_title();
extern Object cajole_into_fixnum();
extern Object cajole_into_float();
extern Object cajole_into_string();
extern Object car_or_atom();
extern Object cdr_or_atom();
extern Object chart_export_format();
extern Object chart_property_p();
extern Object chart_set_double_array();
extern Object chart_set_int_array();
extern Object chart_set_string_array();
extern Object charting_library_version_qm();
extern Object clear_nms_menu_for_hmenu();
extern Object clear_nms_menu_for_hmenu_tree();
extern Object clear_optimized_constants();
extern Object compute_percentage();
extern Object compute_width_of_text_line();
extern Object copy_as_wide_string();
extern Object copy_foreign_string_arg_if_appropriate();
extern Object copy_null_terminated_string_as_text_string();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object create_native_menu();
extern Object create_unique_native_menu_item_id();
extern Object delete_balanced_binary_tree_entry();
extern Object delete_gensym_element_1();
extern Object destroy_native_icons();
extern Object destroy_pane_locally();
extern Object dialog_icon_handle();
extern Object direct_structure_method();
extern Object discard_queued_modal_dialogs();
extern Object dlg_pack_init_data();
extern Object dlg_unpack_result_data();
extern Object emit_icp_read_trace();
extern Object emit_icp_write_trace();
extern Object encode_dock_and_neighbor();
extern Object end_drawing_to_icon();
extern Object end_icp_message_group();
extern Object enlarge_index_space();
extern Object enqueue_local_event();
extern Object enqueue_native_menu_choice();
extern Object ensure_pixmap_of_size();
extern Object export_chart_view();
extern Object extend_current_gensym_string();
extern Object find_native_window_by_handle();
extern Object find_nms_menu_for_hmenu();
extern Object flatten_binary_tree();
extern Object flatten_nms_menu_for_hmenu();
extern Object float_to_words();
extern Object flush_icp_output_ports();
extern Object gensym_cons_1();
extern Object gensym_list_4();
extern Object gensym_window_has_not_been_reprocessed_p();
extern Object get_button_style();
extern Object get_dock_code();
extern Object get_gensym_window_of_native_window();
extern Object get_local_ui_toolkit_name();
extern Object get_neighbor_id();
extern Object get_raw_network_info();
extern Object getfq_function_no_default();
extern Object handle_icp_html_help();
extern Object handle_icp_html_help__body();
extern Object handle_icp_html_help_ex();
extern Object handle_icp_html_help_ex__body();
extern Object handle_icp_list_directory_response();
extern Object handle_icp_list_directory_response__body();
extern Object handle_icp_list_sys_drives_response();
extern Object handle_icp_list_sys_drives_response__body();
extern Object handle_icp_manage_chart_view();
extern Object handle_icp_manage_chart_view__body();
extern Object handle_icp_manage_dialog();
extern Object handle_icp_manage_dialog__body();
extern Object handle_icp_manage_html_view();
extern Object handle_icp_manage_html_view__body();
extern Object handle_icp_manage_logbook();
extern Object handle_icp_manage_logbook__body();
extern Object handle_icp_manage_native_control();
extern Object handle_icp_manage_native_control__body();
extern Object handle_icp_manage_native_icons();
extern Object handle_icp_manage_native_icons__body();
extern Object handle_icp_manage_pane();
extern Object handle_icp_manage_pane__body();
extern Object handle_icp_manage_progress_bar();
extern Object handle_icp_manage_progress_bar__body();
extern Object handle_icp_manage_property_grid();
extern Object handle_icp_manage_property_grid__body();
extern Object handle_icp_manage_shortcut_bar();
extern Object handle_icp_manage_shortcut_bar__body();
extern Object handle_icp_manage_status_bar();
extern Object handle_icp_manage_status_bar__body();
extern Object handle_icp_manage_tabular_view();
extern Object handle_icp_manage_tabular_view__body();
extern Object handle_icp_manage_tree_view();
extern Object handle_icp_manage_tree_view__body();
extern Object handle_icp_manage_ui_properties();
extern Object handle_icp_manage_ui_properties__body();
extern Object handle_icp_messages();
extern Object handle_icp_native_printing_control();
extern Object handle_icp_native_printing_control__body();
extern Object handle_icp_native_printing_dialog();
extern Object handle_icp_native_printing_dialog__body();
extern Object handle_icp_native_printing_ex();
extern Object handle_icp_native_printing_ex__body();
extern Object handle_icp_native_printing_start_page();
extern Object handle_icp_native_printing_start_page__body();
extern Object handle_icp_nms_append_control();
extern Object handle_icp_nms_append_control__body();
extern Object handle_icp_nms_append_control_ex();
extern Object handle_icp_nms_append_control_ex__body();
extern Object handle_icp_nms_append_menu_item();
extern Object handle_icp_nms_append_menu_item__body();
extern Object handle_icp_nms_append_special();
extern Object handle_icp_nms_append_special__body();
extern Object handle_icp_nms_check_menu_item();
extern Object handle_icp_nms_check_menu_item__body();
extern Object handle_icp_nms_check_radio_item();
extern Object handle_icp_nms_check_radio_item__body();
extern Object handle_icp_nms_create_control();
extern Object handle_icp_nms_create_control__body();
extern Object handle_icp_nms_create_menu();
extern Object handle_icp_nms_create_menu__body();
extern Object handle_icp_nms_delete_control();
extern Object handle_icp_nms_delete_control__body();
extern Object handle_icp_nms_delete_menu();
extern Object handle_icp_nms_delete_menu__body();
extern Object handle_icp_nms_dismiss();
extern Object handle_icp_nms_dismiss__body();
extern Object handle_icp_nms_enable_items();
extern Object handle_icp_nms_enable_items__body();
extern Object handle_icp_nms_enable_menu_item();
extern Object handle_icp_nms_enable_menu_item__body();
extern Object handle_icp_nms_modify_control();
extern Object handle_icp_nms_modify_control__body();
extern Object handle_icp_nms_modify_menu_item();
extern Object handle_icp_nms_modify_menu_item__body();
extern Object handle_icp_nms_pop_up_menu();
extern Object handle_icp_nms_pop_up_menu__body();
extern Object handle_icp_nms_reset();
extern Object handle_icp_nms_reset__body();
extern Object handle_icp_nms_set_iconsize();
extern Object handle_icp_nms_set_iconsize__body();
extern Object handle_icp_nms_set_menu_bar();
extern Object handle_icp_nms_set_menu_bar__body();
extern Object handle_icp_nms_set_menu_flags();
extern Object handle_icp_nms_set_menu_flags__body();
extern Object handle_icp_nms_set_theme();
extern Object handle_icp_nms_set_theme__body();
extern Object handle_icp_paint_icon_in_current_window();
extern Object handle_icp_paint_line_of_text_in_current_window();
extern Object handle_icp_post_native_menu();
extern Object handle_icp_post_native_menu__body();
extern Object handle_icp_print_native_window();
extern Object handle_icp_print_native_window__body();
extern Object handle_icp_reset_native_controls();
extern Object handle_icp_reset_native_controls__body();
extern Object handle_icp_set_window_title();
extern Object handle_icp_set_window_title__body();
extern Object handle_icp_tabbed_mdi_mode();
extern Object handle_icp_tabbed_mdi_mode__body();
extern Object handle_print_window_event();
extern Object html_help_ex();
extern Object icon_mask_pixmap();
extern Object icon_polychrome_pixmap();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object icp_error_internal();
extern Object icp_list_2();
extern Object icp_list_4();
extern Object icp_message_functions_icp_prologue();
extern Object instantaneous_icp_reader_byte_count();
extern Object instantaneous_icp_writer_byte_count();
extern Object intern_wide_string();
extern Object item_number_given_item_id();
extern Object item_uuid();
extern Object lengthw();
extern Object load_and_initialize_type_description();
extern Object locally_initable_pane_property_p();
extern Object locally_initable_view_property_p();
extern Object make_basic_native_window();
extern Object make_corresponding_icp_gensym_window();
extern Object make_corresponding_icp_symbol();
extern Object make_gensym_list_1();
extern Object make_icp_list_1();
extern Object make_nms_menu_1();
extern Object make_nms_menu_for_hmenu();
extern Object make_nms_menu_for_hmenu_hash_vector();
extern Object make_nms_menu_item_1();
extern Object make_permanent_nms_menu_for_hmenu_hash_vector_43_vector_internal();
extern Object make_permanent_nms_menu_item_structure_internal();
extern Object make_permanent_nms_menu_structure_internal();
extern Object make_thread_array();
extern Object manage_animation();
extern Object manage_animation_1();
extern Object manage_chart_view_1();
extern Object manage_dialog();
extern Object manage_dialog_1();
extern Object manage_dialog_icp();
extern Object manage_logbook_1();
extern Object manage_native_window_locally();
extern Object manage_notification();
extern Object manage_notification_1();
extern Object manage_pane_1();
extern Object manage_pane_locally();
extern Object manage_property_grid_1();
extern Object manage_shortcut_bar_1();
extern Object manage_status_bar_1();
extern Object manage_tabular_view_1();
extern Object manage_tree_view_locally();
extern Object manage_ui_properties_1();
extern Object map_to_color_value();
extern Object map_to_color_value_1();
extern Object memq_function();
extern Object menu_handle_given_item_id();
extern Object modify_status_bar_pane_1();
extern Object mutate_global_property();
extern Object mutate_nms_menu_for_hmenu_tree_for_hash_tree_entry();
extern Object n_32bit_integer_high_part();
extern Object n_32bit_integer_low_part();
extern Object native_animation_control_p();
extern Object native_menu_bar_p();
extern Object native_pop_up_menus_p();
extern Object native_printing_abort_printing();
extern Object native_printing_begin();
extern Object native_printing_end();
extern Object native_printing_end_doc();
extern Object native_printing_end_page();
extern Object native_printing_start_doc();
extern Object native_printing_start_page();
extern Object native_progress_bar_p();
extern Object nms_allocate_control();
extern Object nms_allocate_handle();
extern Object nms_allocate_menu();
extern Object nms_allocate_menu_item();
extern Object nms_append_control_1();
extern Object nms_append_internal();
extern Object nms_built_in_menu_p();
extern Object nms_c_append_menu();
extern Object nms_c_create_combo_box();
extern Object nms_c_create_edit_box();
extern Object nms_c_create_menu();
extern Object nms_c_create_toolbar();
extern Object nms_c_fetch_help_string_result();
extern Object nms_c_manage_control();
extern Object nms_c_modify_menu_item();
extern Object nms_c_set_help();
extern Object nms_control_type_code();
extern Object nms_create_combo_box_2();
extern Object nms_create_edit_box_2();
extern Object nms_deallocate_handle();
extern Object nms_delete_item();
extern Object nms_delete_menu_locally();
extern Object nms_delete_native_menu();
extern Object nms_discard_win32_handle();
extern Object nms_ensure_consistent_menu_geometry();
extern Object nms_hard_reset_locally();
extern Object nms_hide_menu_bar();
extern Object nms_lookup_handle();
extern Object nms_lookup_id();
extern Object nms_menu_bar_menu_p();
extern Object nms_menu_bar_menu_type();
extern Object nms_menu_bars_supported_p();
extern Object nms_menu_for_hmenu_hash_vector_43_vector_memory_usage();
extern Object nms_menu_handle_to_id();
extern Object nms_menu_id_to_handle();
extern Object nms_menu_item_command_id();
extern Object nms_menu_item_id();
extern Object nms_menu_item_structure_memory_usage();
extern Object nms_menu_structure_memory_usage();
extern Object nms_menu_table();
extern Object nms_next_handle();
extern Object nms_note_menu_deletion();
extern Object nms_parameter_menu_p();
extern Object nms_pop_up_menu_deferred();
extern Object nms_pop_up_menu_p();
extern Object nms_pop_up_menu_type();
extern Object nms_popup_menus_supported_p();
extern Object nms_push_item();
extern Object nms_reclaim_key();
extern Object nms_reclaim_menu();
extern Object nms_reclaim_menu_1_1();
extern Object nms_reclaim_menu_item();
extern Object nms_reclaim_menu_item_1_1();
extern Object nms_reclaim_menu_or_item();
extern Object nms_record_win32_handle();
extern Object nms_remove_menu_item_locally();
extern Object nms_renumber_items();
extern Object nms_reset_locally();
extern Object nms_revert_to_unconnected_menu_bar();
extern Object nms_set_bit();
extern Object nms_set_theme_1();
extern Object nms_soft_reset_locally();
extern Object nms_supported_on_gensym_window_p();
extern Object nms_toolbar_p();
extern Object nms_wide_menu_p();
extern Object note_progress();
extern Object note_progress_on_window();
extern Object notify_user_at_console();
extern Object nstring_upcasew();
extern Object obtain_simple_gensym_string();
extern Object obtain_text_string();
extern Object out_nms_menu_for_hmenu_hash_vector_43_vectors();
extern Object outstanding_nms_menu_count();
extern Object outstanding_nms_menu_item_count();
extern Object paint_icon_in_current_window();
extern Object paint_line_of_text_in_current_window();
extern Object partial_command_p_function();
extern Object pathname_type_as_symbol();
extern Object pct_html_help();
extern Object pct_manage_property_grid();
extern Object pct_set_chart_property();
extern Object pechart_enum_value();
extern Object pechart_print_error();
extern Object pechart_property_code();
extern Object pechart_property_type();
extern Object pechart_type_code();
extern Object plistp();
extern Object populate_property_grid();
extern Object populate_tree_view();
extern Object post_modal_dialog_1();
extern Object post_native_menu();
extern Object print_dialog_1();
extern Object print_window_1();
extern Object process_property_grid_init_plist();
extern Object process_shortcut_bar_init_plist();
extern Object process_tabular_view_init_plist();
extern Object process_tree_init_plist();
extern Object process_view_init_plist();
extern Object process_window_style_options();
extern Object prop_grid_event_name();
extern Object prop_grid_node_opcode();
extern Object prop_grid_opcode();
extern Object prop_grid_sort_code();
extern Object prop_grid_sort_symbol();
extern Object prop_grid_type_code();
extern Object push_optimized_constant();
extern Object queue_insert();
extern Object read_icp_boolean();
extern Object read_icp_corresponding_object_index();
extern Object read_icp_fixnum();
extern Object read_icp_icp_tree();
extern Object read_icp_integer();
extern Object read_icp_text_string();
extern Object read_icp_unsigned_integer();
extern Object read_icp_unsigned_integer_qm();
extern Object read_icp_wide_string();
extern Object reclaim_byte_vector_16();
extern Object reclaim_contents_of_nms_menu_table();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_cons_qm();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_icp_list_1();
extern Object reclaim_icp_tree_1();
extern Object reclaim_icp_tree_of_values();
extern Object reclaim_icp_tree_value();
extern Object reclaim_icp_tree_with_text_strings();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_managed_array();
extern Object reclaim_managed_simple_float_array();
extern Object reclaim_native_menus();
extern Object reclaim_native_window();
extern Object reclaim_native_window_by_handle();
extern Object reclaim_nms_menu_for_hmenu();
extern Object reclaim_nms_menu_for_hmenu_hash_vector();
extern Object reclaim_partial_command();
extern Object reclaim_pixmap();
extern Object reclaim_raw_network_info();
extern Object reclaim_simple_gensym_string();
extern Object reclaim_text_string();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_native_menu_c_pointer();
extern Object record_system_variable();
extern Object refresh_native_icon();
extern Object regenerate_optimized_constant();
extern Object replenish_lookup_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object reset_native_controls();
extern Object resumable_icp_pop();
extern Object resumable_icp_pop_list_if_end_marker();
extern Object resumable_icp_push();
extern Object rgb_color_p();
extern Object rgb_color_value();
extern Object rgb_from_color();
extern Object save_native_icon();
extern Object sb_fixnum();
extern Object send_icp_html_help();
extern Object send_icp_html_help_ex();
extern Object send_icp_list_directory_response();
extern Object send_icp_list_sys_drives_response();
extern Object send_icp_manage_chart_view();
extern Object send_icp_manage_dialog();
extern Object send_icp_manage_html_view();
extern Object send_icp_manage_logbook();
extern Object send_icp_manage_native_control();
extern Object send_icp_manage_native_icons();
extern Object send_icp_manage_pane();
extern Object send_icp_manage_progress_bar();
extern Object send_icp_manage_property_grid();
extern Object send_icp_manage_shortcut_bar();
extern Object send_icp_manage_status_bar();
extern Object send_icp_manage_tabular_view();
extern Object send_icp_manage_tree_view();
extern Object send_icp_manage_ui_properties();
extern Object send_icp_message();
extern Object send_icp_native_printing_control();
extern Object send_icp_native_printing_dialog();
extern Object send_icp_native_printing_ex();
extern Object send_icp_native_printing_start_page();
extern Object send_icp_nms_append_control();
extern Object send_icp_nms_append_control_ex();
extern Object send_icp_nms_append_menu_item();
extern Object send_icp_nms_append_special();
extern Object send_icp_nms_check_menu_item();
extern Object send_icp_nms_check_radio_item();
extern Object send_icp_nms_create_control();
extern Object send_icp_nms_create_menu();
extern Object send_icp_nms_delete_control();
extern Object send_icp_nms_delete_menu();
extern Object send_icp_nms_dismiss();
extern Object send_icp_nms_enable_items();
extern Object send_icp_nms_enable_menu_item();
extern Object send_icp_nms_modify_control();
extern Object send_icp_nms_modify_menu_item();
extern Object send_icp_nms_pop_up_menu();
extern Object send_icp_nms_reset();
extern Object send_icp_nms_set_iconsize();
extern Object send_icp_nms_set_menu_bar();
extern Object send_icp_nms_set_menu_flags();
extern Object send_icp_nms_set_theme();
extern Object send_icp_post_native_menu();
extern Object send_icp_print_native_window();
extern Object send_icp_reset_native_controls();
extern Object send_icp_set_window_title();
extern Object send_icp_tabbed_mdi_mode();
extern Object set_balanced_binary_tree_entry();
extern Object set_chart_properties();
extern Object set_pane_state_locally();
extern Object set_to_default_window_title();
extern Object set_window_title();
extern Object shbar_add_folder();
extern Object shbar_add_item();
extern Object shbar_clear();
extern Object shbar_populate();
extern Object sort_column_value_or_stack_error();
extern Object sorting_order_value_or_stack_error();
extern Object start_writing_icp_message();
extern Object stock_command_id_p();
extern Object string_eq_w();
extern Object stringw();
extern Object sxhashw();
extern Object symbol_namew();
extern Object tabbed_mdi_mode_1();
extern Object tabular_view_add_columns_1();
extern Object tabular_view_add_rows_1();
extern Object tabular_view_change_sort_1();
extern Object tabular_view_modify_cells_1();
extern Object tabular_view_modify_columns_1();
extern Object tabular_view_modify_rows_1();
extern Object tabular_view_opcode();
extern Object tbv_fixnum();
extern Object text_string_length();
extern Object text_string_p();
extern Object tformat();
extern Object to_string();
extern Object tree_view_modify_node_1();
extern Object twng_p();
extern Object twrite();
extern Object twrite_long_system_version_string();
extern Object twrite_string_and_nul();
extern Object twrite_wide_character();
extern Object ui_stack_error_1();
extern Object update_object_pool_meters_list();
extern Object valid_sorting_order_or_stack_error();
extern Object wide_string_substring();
extern Object win32_choice_symbol();
extern Object write_icp_boolean();
extern Object write_icp_corresponding_object_index();
extern Object write_icp_fixnum();
extern Object write_icp_icp_tree();
extern Object write_icp_integer();
extern Object write_icp_list_of_unsigned_integers();
extern Object write_icp_text_string();
extern Object write_icp_unsigned_integer();
extern Object write_icp_unsigned_integer_qm();
extern Object write_icp_wide_string();

#endif

/* Externally callable routines */

#ifdef USE_PROTOTYPES

extern SI_Long nms_fetch_help_string(SI_Long,SI_Long);
extern SI_Long nms_handle_if_flag_bit(SI_Long,SI_Long,SI_Long);
extern SI_Long nms_id_for_menu(SI_Long,SI_Long);

#else

extern SI_Long nms_fetch_help_string();
extern SI_Long nms_handle_if_flag_bit();
extern SI_Long nms_id_for_menu();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Abort_for_icp_catcher_qm, Qabort_for_icp_catcher_qm);
extern Object Animation_control_handle;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_nms_menu_for_hmenu_hash_vector_43_vectors, Qavailable_nms_menu_for_hmenu_hash_vector_43_vectors);
extern Object Available_nms_menu_for_hmenu_hash_vector_43_vectors_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Axis, Qaxis);
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
#define Begin_drawing_to_icon_buffer FIX((SI_Long)1L)
#define Begin_drawing_to_icon_mask FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Cell, Qcell);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_nms_menu_items, Qchain_of_available_nms_menu_items);
extern Object Chain_of_available_nms_menu_items_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_nms_menus, Qchain_of_available_nms_menus);
extern Object Chain_of_available_nms_menus_vector;
#define Chart_copy FIX((SI_Long)6L)
#define Chart_destroy FIX((SI_Long)2L)
#define Chart_export FIX((SI_Long)7L)
#define Chart_format_bmp FIX((SI_Long)3L)
#define Chart_format_jpeg FIX((SI_Long)1L)
#define Chart_format_png FIX((SI_Long)2L)
#define Chart_format_svg FIX((SI_Long)5L)
#define Chart_format_wmf FIX((SI_Long)4L)
#define Chart_inappropriate_property FIX((SI_Long)2L)
#define Chart_invalid_array_property FIX((SI_Long)3L)
#define Chart_invalid_float_property FIX((SI_Long)4L)
#define Chart_partial_update FIX((SI_Long)5L)
#define Chart_print FIX((SI_Long)3L)
#define Chart_set_failed FIX((SI_Long)5L)
#define Chart_update FIX((SI_Long)4L)
DECLARE_VARIABLE_WITH_SYMBOL(Charting_library_version_qm, Qcharting_library_version_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
DECLARE_VARIABLE_WITH_SYMBOL(Column_width, Qcolumn_width);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_nms_menu_for_hmenu_hash_vector_43_vectors, Qcount_of_nms_menu_for_hmenu_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_color_map, Qcurrent_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_read_trace_level, Qcurrent_icp_read_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_write_trace_level, Qcurrent_icp_write_trace_level);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster, Qcurrent_scratchpad_raster);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_tiled_p, Qcurrent_scratchpad_raster_tiled_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_scratchpad_raster_type, Qcurrent_scratchpad_raster_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_standard_icp_object_index_space, Qcurrent_standard_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_name, Qcurrent_system_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_temporary_icp_object_index_space, Qcurrent_temporary_icp_object_index_space);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_max_for_stored_raster_qm, Qcurrent_x_max_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_offset_for_stored_raster_qm, Qcurrent_x_offset_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_max_for_stored_raster_qm, Qcurrent_y_max_for_stored_raster_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_offset_for_stored_raster_qm, Qcurrent_y_offset_for_stored_raster_qm);
#define Cw_usedefault FIX((SI_Long)-30000L)
extern Object Default_mdi_child_style;
#define Destroy_native_icons FIX((SI_Long)4L)
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
#define Dlg_cancel_modal FIX((SI_Long)2L)
#define Dlg_post_modal FIX((SI_Long)1L)
#define Dlgm_addstrings FIX((SI_Long)2L)
#define Dlgm_settext FIX((SI_Long)1L)
#define Dlgt_short FIX((SI_Long)1L)
#define Dlgt_string FIX((SI_Long)2L)
#define Dock_code_embedded FIX((SI_Long)9L)
#define Dock_code_mdi_child FIX((SI_Long)7L)
#define Dock_code_top_level FIX((SI_Long)8L)
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_on_window, Qdrawing_on_window);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_to_printer_p, Qdrawing_to_printer_p);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
extern Object Fp_mutate_nms_menu_for_hmenu_tree_for_hash_tree_entry;
#define Hh_display_envar_topic FIX((SI_Long)128L)
#define Html_view_back FIX((SI_Long)3L)
#define Html_view_destroy FIX((SI_Long)2L)
#define Html_view_forward FIX((SI_Long)4L)
#define Html_view_goto FIX((SI_Long)8L)
#define Html_view_home FIX((SI_Long)5L)
#define Html_view_print FIX((SI_Long)9L)
#define Html_view_refresh FIX((SI_Long)7L)
#define Html_view_stop FIX((SI_Long)6L)
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_clip_bottom, Qicon_offset_clip_bottom);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_clip_left, Qicon_offset_clip_left);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_clip_right, Qicon_offset_clip_right);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_clip_top, Qicon_offset_clip_top);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_left, Qicon_offset_left);
DECLARE_VARIABLE_WITH_SYMBOL(Icon_offset_top, Qicon_offset_top);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_printing_message_handler_array, Qicp_printing_message_handler_array);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_read_trace_cutoff_level_qm, Qicp_read_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_suspend, Qicp_suspend);
#define Icp_window_protocol_supports_nms_menus FIX((SI_Long)29L)
DECLARE_VARIABLE_WITH_SYMBOL(Icp_write_trace_cutoff_level_qm, Qicp_write_trace_cutoff_level_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Is_icon_mask_drawing, Qis_icon_mask_drawing);
#define Logbook_append_extended_message FIX((SI_Long)17L)
#define Logbook_create FIX((SI_Long)1L)
#define Lvcfmt_center FIX((SI_Long)2L)
#define Lvcfmt_left FIX((SI_Long)0L)
#define Lvcfmt_right FIX((SI_Long)1L)
#define Lvscw_autosize FIX((SI_Long)-1L)
#define Lvscw_autosize_useheader FIX((SI_Long)-2L)
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
#define Maximum_oversized_managed_simple_float_array_size FIX((SI_Long)1048576L)
extern Object Menu_break_marker;
#define Mf_builtin FIX((SI_Long)32768L)
#define Mf_byposition FIX((SI_Long)1024L)
#define Mf_checked FIX((SI_Long)8L)
#define Mf_disabled FIX((SI_Long)2L)
#define Mf_dynamic FIX((SI_Long)65536L)
#define Mf_grayed FIX((SI_Long)1L)
#define Mf_menubarbreak FIX((SI_Long)32L)
#define Mf_menubreak FIX((SI_Long)64L)
#define Mf_menuselect FIX((SI_Long)262144L)
#define Mf_ownerdraw FIX((SI_Long)256L)
#define Mf_popup FIX((SI_Long)16L)
#define Mf_rightjustify FIX((SI_Long)16384L)
#define Mf_separator FIX((SI_Long)2048L)
#define Mf_unpost FIX((SI_Long)524288L)
#define Mf_wide FIX((SI_Long)131072L)
#define Mf_win32_flags_mask FIX((SI_Long)32767L)
DECLARE_VARIABLE_WITH_SYMBOL(Native_menu_counter, Qnative_menu_counter);
DECLARE_VARIABLE_WITH_SYMBOL(Native_menu_id_to_handle_and_item_number_table, Qnative_menu_id_to_handle_and_item_number_table);
DECLARE_VARIABLE_WITH_SYMBOL(Native_menu_table, Qnative_menu_table);
DECLARE_VARIABLE_WITH_SYMBOL(Native_menu_unique_id_counter, Qnative_menu_unique_id_counter);
DECLARE_VARIABLE_WITH_SYMBOL(Nms_constructing_built_in_menus_p, Qnms_constructing_built_in_menus_p);
extern Object Nms_handle_gap_high;
extern Object Nms_handle_gap_low;
extern Object Nms_maximum_permitted_handle;
DECLARE_VARIABLE_WITH_SYMBOL(Nms_menu_count, Qnms_menu_count);
DECLARE_VARIABLE_WITH_SYMBOL(Nms_menu_hash_table, Qnms_menu_hash_table);
DECLARE_VARIABLE_WITH_SYMBOL(Nms_menu_item_count, Qnms_menu_item_count);
#define Nms_no_choice FIX((SI_Long)1500L)
#define Nms_stock_command_min_id FIX((SI_Long)1001L)
#define Nmsc_addtext FIX((SI_Long)5L)
#define Nmsc_deletetext FIX((SI_Long)6L)
#define Nmsc_hide FIX((SI_Long)2L)
#define Nmsc_setcursel FIX((SI_Long)3L)
#define Nmsc_settext FIX((SI_Long)4L)
#define Nmsc_show FIX((SI_Long)1L)
DECLARE_VARIABLE_WITH_SYMBOL(No_arg, Qno_arg);
extern Object Notification_control_handle;
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
extern Object Obs_default_style;
#define Obs_xt_dragitems FIX((SI_Long)128L)
#define Obs_xt_edititems FIX((SI_Long)8L)
DECLARE_VARIABLE_WITH_SYMBOL(On_monochrome_raster_list_p, Qon_monochrome_raster_list_p);
DECLARE_VARIABLE_WITH_SYMBOL(On_window_without_drawing, Qon_window_without_drawing);
#define Pane_close FIX((SI_Long)10L)
#define Pane_destroy FIX((SI_Long)2L)
#define Pane_dock FIX((SI_Long)6L)
#define Pane_fill FIX((SI_Long)13L)
#define Pane_float FIX((SI_Long)5L)
#define Pane_hide FIX((SI_Long)3L)
#define Pane_redock FIX((SI_Long)11L)
#define Pane_select FIX((SI_Long)4L)
#define Pane_set_autohideable FIX((SI_Long)102L)
#define Pane_set_close_action FIX((SI_Long)106L)
#define Pane_set_closeable FIX((SI_Long)101L)
#define Pane_set_draggable FIX((SI_Long)104L)
#define Pane_set_floatable FIX((SI_Long)103L)
#define Pane_set_icon FIX((SI_Long)9L)
#define Pane_set_title FIX((SI_Long)8L)
#define Pane_set_visible_caption FIX((SI_Long)105L)
#define Pane_show FIX((SI_Long)7L)
#define Pane_toggle_docking FIX((SI_Long)12L)
#define Pct_dot FIX((SI_Long)46L)
extern Object Pechart_types;
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
extern Object Prop_grid_events;
extern Object Prop_grid_node_type;
extern Object Prop_grid_sort_type;
extern Object Property_grid_opcodes;
#define Refresh_native_icon FIX((SI_Long)6L)
DECLARE_VARIABLE_WITH_SYMBOL(Resumable_icp_state, Qresumable_icp_state);
DECLARE_VARIABLE_WITH_SYMBOL(Row_height, Qrow_height);
#define Save_native_icon FIX((SI_Long)3L)
#define Sb_add_pane FIX((SI_Long)6L)
#define Sb_hide FIX((SI_Long)0L)
#define Sb_minheight FIX((SI_Long)4L)
#define Sb_pane_alignment FIX((SI_Long)14L)
#define Sb_pane_background FIX((SI_Long)12L)
#define Sb_pane_borders FIX((SI_Long)17L)
#define Sb_pane_enabled FIX((SI_Long)16L)
#define Sb_pane_foreground FIX((SI_Long)11L)
#define Sb_pane_icon FIX((SI_Long)13L)
#define Sb_pane_text FIX((SI_Long)8L)
#define Sb_pane_tooltip FIX((SI_Long)15L)
#define Sb_pane_visible FIX((SI_Long)10L)
#define Sb_pane_width FIX((SI_Long)9L)
#define Sb_remove_pane FIX((SI_Long)7L)
#define Sb_reset FIX((SI_Long)3L)
#define Sb_show FIX((SI_Long)1L)
#define Sb_text FIX((SI_Long)2L)
#define Sb_update FIX((SI_Long)5L)
#define Shortcut_bar_add_folder FIX((SI_Long)10L)
#define Shortcut_bar_add_item FIX((SI_Long)11L)
#define Shortcut_bar_background_color FIX((SI_Long)21L)
#define Shortcut_bar_clear FIX((SI_Long)12L)
#define Shortcut_bar_destroy FIX((SI_Long)6L)
#define Shortcut_bar_disable_folder FIX((SI_Long)15L)
#define Shortcut_bar_disable_item FIX((SI_Long)18L)
#define Shortcut_bar_enable_folder FIX((SI_Long)14L)
#define Shortcut_bar_enable_item FIX((SI_Long)17L)
#define Shortcut_bar_foreground_color FIX((SI_Long)22L)
#define Shortcut_bar_large_icons FIX((SI_Long)20L)
#define Shortcut_bar_select_folder FIX((SI_Long)13L)
#define Shortcut_bar_select_item FIX((SI_Long)16L)
#define Shortcut_bar_small_icons FIX((SI_Long)19L)
#define Shortcut_bar_style_outlook FIX((SI_Long)1L)
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
#define Sort_column_default FIX((SI_Long)-1L)
#define Sorting_order_default FIX((SI_Long)1L)
#define Stop_drawing_to_icon FIX((SI_Long)5L)
extern Object Tabular_view_opcodes;
DECLARE_VARIABLE_WITH_SYMBOL(Text_value, Qtext_value);
extern Object The_type_description_of_nms_menu;
extern Object The_type_description_of_nms_menu_item;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Tree_view_clear FIX((SI_Long)11L)
#define Tree_view_collapse_all FIX((SI_Long)34L)
#define Tree_view_collapse_item FIX((SI_Long)23L)
#define Tree_view_delete_item FIX((SI_Long)30L)
#define Tree_view_destroy FIX((SI_Long)6L)
#define Tree_view_edit_item FIX((SI_Long)21L)
#define Tree_view_expand_all FIX((SI_Long)33L)
#define Tree_view_expand_item FIX((SI_Long)22L)
#define Tree_view_insert_item FIX((SI_Long)10L)
#define Tree_view_redraw FIX((SI_Long)35L)
#define Tree_view_select_item FIX((SI_Long)24L)
#define Tree_view_select_item_by_name FIX((SI_Long)17L)
#define Tree_view_set_bgcolor FIX((SI_Long)14L)
#define Tree_view_set_indent FIX((SI_Long)12L)
#define Tree_view_set_insert_mark_color FIX((SI_Long)16L)
#define Tree_view_set_item_bold FIX((SI_Long)26L)
#define Tree_view_set_item_height FIX((SI_Long)13L)
#define Tree_view_set_item_icons FIX((SI_Long)28L)
#define Tree_view_set_item_label FIX((SI_Long)27L)
#define Tree_view_set_item_tooltip FIX((SI_Long)25L)
#define Tree_view_set_right_click_selects_node FIX((SI_Long)32L)
#define Tree_view_set_text_color FIX((SI_Long)15L)
#define Tvf_after FIX((SI_Long)32L)
#define Tvf_children FIX((SI_Long)1L)
#define Tvf_first FIX((SI_Long)16L)
DECLARE_VARIABLE_WITH_SYMBOL(Tw_deferred_actions, Qtw_deferred_actions);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
extern Object Win32_choice_symbols;
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
#define Ws_child FIX((SI_Long)16384L)
#define Ws_clipsiblings FIX((SI_Long)1024L)
