/* nwtbls.h -- Header File for nwtbls.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qnum_eq;
extern Object Qand;
extern Object Qblock;
extern Object Qcons;
extern Object Qfunction;
extern Object Qinteger;
extern Object Qmember;
extern Object Kname;
extern Object Qnumber;
extern Object Qquote;
extern Object Qsatisfies;
extern Object Qsequence;
extern Object Qsymbol;
extern Object Qthe;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_for_new_table(Object);
extern Object activate_g2_cell_array(Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object allocate_managed_array(int,...);
extern Object bottom_edge_within_pane(Object,Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object callback_representation_fire_callback(Object,Object,Object);
extern Object cell_annotations_for_class(Object);
extern Object cell_updated(Object,Object,Object,Object);
extern Object cell_updated_in_paint_mode(Object,Object,Object,Object);
extern Object change_annotation(Object,Object,Object,Object,Object,Object);
extern Object change_edges_of_block(Object,Object,Object,Object,Object);
extern Object change_in_freeform_table_dimensions_is_ok_p(Object,Object,Object);
extern Object change_in_freeform_table_is_meaningful_p(Object,Object,Object,Object,Object,Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clear_optimized_constants(void);
extern Object combine_and_reclaim_error_strings(Object,Object);
extern Object compile_a_compiled_cell_expression_from_expression_parse_and_style_description(Object,Object,Object);
extern Object compile_part_description(Object,Object);
extern Object compile_table_dimensions_for_slot(int,...);
extern Object compiled_cell_expression_p(Object);
extern Object convert_path_to_expression(Object,Object);
extern Object convert_text_string_to_text(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_and_format_text(Object,Object);
extern Object copy_as_wide_string(Object);
extern Object copy_evaluation_value_1(Object);
extern Object copy_for_slot_value(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_if_evaluation_value_1(Object);
extern Object copy_managed_float(Object);
extern Object copy_managed_long(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_box_format(Object,Object);
extern Object copy_text_string(Object);
extern Object copy_wide_string(Object);
extern Object create_compiled_cell_expression(Object,Object,Object);
extern Object deactivate_for_new_table(Object);
extern Object deactivate_g2_cell_array(Object);
extern Object def_part_feature_1(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object def_part_type_1(Object,Object,Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object delete_subpart(Object,Object,Object);
extern Object denote_cell_array_element_for_new_table(Object,Object,Object);
extern Object denote_component_of_block(int,...);
extern Object denote_component_of_block_1(Object,Object);
extern Object describe_new_table(void);
extern Object describe_new_table_from_inside_projection(Object);
extern Object describe_part_from_current_extent(Object);
extern Object direct_structure_method(Object,Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object do_new_table_edit(Object,Object,Object,Object,Object);
extern Object draw_for_new_table(Object);
extern Object draw_graphic_element(int,...);
extern Object draw_text_segment_1(Object,Object,Object,Object,Object,Object,Object);
extern Object enlarge_workspace_for_block_rectangle_if_necessary(Object,Object);
extern Object enter_part_description(Object);
extern Object enter_part_feature_cell_contents(Object);
extern Object enter_part_feature_column_maximum(Object);
extern Object enter_part_feature_column_width(Object);
extern Object enter_part_feature_row_height(Object);
extern Object enter_part_feature_row_maximum(Object);
extern Object enter_part_feature_subparts(Object);
extern Object enter_part_feature_text_value(Object);
extern Object enter_subpart_defaults(Object);
extern Object enter_subpart_exceptions(Object);
extern Object erase_entire_annotated_block(Object);
extern Object erase_part_of_block(Object,Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object evaluated_computed_part_feature_p(Object);
extern Object evaluation_sequence_aref(Object,Object);
extern Object evaluation_truth_value_is_true_p(Object);
extern Object evaluation_value_eql(int,...);
extern Object evaluation_value_value(Object);
extern Object exit_part_feature_cell_contents(void);
extern Object exit_part_feature_column_maximum(void);
extern Object exit_part_feature_column_width(void);
extern Object exit_part_feature_row_height(void);
extern Object exit_part_feature_row_maximum(void);
extern Object exit_part_feature_subparts(void);
extern Object exit_part_feature_text_value(void);
extern Object exit_subpart_defaults(void);
extern Object exit_subpart_exceptions(void);
extern Object export_cell_attribute_name(Object);
extern Object expression_cell_index_to_cell_coordinates(int,...);
extern Object expression_cell_updated_for_new_table(Object,Object,Object,Object,Object);
extern Object find_frame_of_class_in_mouse_pointer(Object,Object);
extern Object force_process_drawing(void);
extern Object format_text(int,...);
extern Object generate_float_vector(Object);
extern Object generate_spot_for_new_table(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_current_sexp_annotation_hash(void);
extern Object get_default_computation_style_of_class(void);
extern Object get_default_formatted_part_of_class(void);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_property_value_function(int,...);
extern Object get_reference_to_item(Object);
extern Object get_simple_part_feature(Object,Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_subpart_collection(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_table_cells(Object);
extern Object get_workspace_if_any(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_cell_expression(Object,Object,Object,Object);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_of_mouse_pointer(Object);
extern Object initial_table_cells(Object);
extern Object initialize_after_reading_for_new_table(Object);
extern Object initialize_for_new_table(Object);
extern Object initialize_off_window_color_map(void);
extern Object initialize_slot_description_value(Object,Object,Object);
extern Object insert_subpart_descriptions(Object,Object,Object,Object);
extern Object invalidate_rectangle_of_workspace(Object,Object,Object,Object,Object,Object,Object);
extern Object item_is_either_not_permanent_or_from_an_editable_module_p(Object);
extern Object javalink_versioned_call_data_evaluated_p(Object);
extern Object javalink_versioned_call_data_get_version(Object);
extern Object javalink_versioned_call_data_sendp(Object);
extern Object javalink_versioning_make_arg_list_copy(Object,Object);
extern Object javalink_versioning_reclaim_evaluated_version_bodies(Object);
extern Object left_edge_within_pane(Object,Object);
extern Object lengthw(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_color_map(Object,Object);
extern Object make_edit_state_1(void);
extern Object make_evaluation_long(Object);
extern Object make_evaluation_place_reference_to_place(Object,Object);
extern Object make_evaluation_value_for_expression_cell_index(Object);
extern Object make_format_frame(Object);
extern Object make_frame(Object);
extern Object make_javalink_versioned_data(Object);
extern Object make_monochrome_color_description_plist(Object,Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_new_table_background_spot_1(void);
extern Object make_new_table_cell_spot_1(void);
extern Object make_new_table_spot_1(void);
extern Object make_permanent_new_table_background_spot_structure_internal(void);
extern Object make_permanent_new_table_cell_spot_structure_internal(void);
extern Object make_permanent_new_table_spot_structure_internal(void);
extern Object make_sequence_of_freeform_table_row(Object,Object);
extern Object make_sexp_annotation_hash(void);
extern Object make_slot_value_list_1(Object);
extern Object make_structure_for_cell_contents(Object);
extern Object make_structure_for_cell_format(Object,Object);
extern Object make_table_annotation(Object,Object,Object);
extern Object make_text_for_datum(Object,Object);
extern Object make_thread_array(Object);
extern Object map_over_part_description(Object,Object);
extern Object map_to_color_value(Object);
extern Object map_to_color_value_1(Object);
extern Object memq_function(Object,Object);
extern Object mouse_over_cell_in_new_table_p(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object new_table_background_spot_structure_memory_usage(void);
extern Object new_table_cell_spot_structure_memory_usage(void);
extern Object new_table_spot_structure_memory_usage(void);
extern Object note_change_to_block_1(Object,Object);
extern Object original_x_in_window_blackboard_function(Object);
extern Object original_y_in_window_blackboard_function(Object);
extern Object outstanding_new_table_background_spot_count(void);
extern Object outstanding_new_table_cell_spot_count(void);
extern Object outstanding_new_table_spot_count(void);
extern Object parse_text_string(int,...);
extern Object part_has_feature_p(Object,Object);
extern Object part_stack_cons_1(Object,Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object place_reference_of_cell_for_new_table(Object,Object);
extern Object project_new_table(void);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_cell_annotations(Object,Object,Object);
extern Object put_default_cell_format(Object,Object,Object);
extern Object put_default_evaluation_setting(Object,Object,Object);
extern Object read_number_from_string(Object,Object,Object);
extern Object read_symbol_from_string(Object,Object,Object);
extern Object read_text_string_from_string(Object,Object,Object);
extern Object reclaim_edit_state_1(Object);
extern Object reclaim_evaluation_place_reference(Object);
extern Object reclaim_evaluation_structure(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_new_table_background_spot_1(Object);
extern Object reclaim_new_table_cell_spot_1(Object);
extern Object reclaim_new_table_spot_1(Object);
extern Object reclaim_part_description(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_structure_if_any(Object);
extern Object reclaim_text_string(Object);
extern Object recompile_component_of_part_description(Object,Object,Object);
extern Object recompile_expression_at_component_particulars_for_new_table(Object,Object);
extern Object recompile_item(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object redraw_entire_annotated_block(void);
extern Object redraw_part_of_block(Object);
extern Object regenerate_optimized_constant(Object);
extern Object remote_icp_protocol_version(Object);
extern Object remove_evaluation_structure_attribute(Object,Object);
extern Object remove_simple_part_feature(Object,Object);
extern Object replenish_part_stack_cons_pool(void);
extern Object replenish_stack_change_cons_pool(void);
extern Object representation_address_valid_p(Object);
extern Object right_edge_within_pane(Object,Object);
extern Object row_and_column_index_available_p(Object);
extern Object scalef_function(Object,Object);
extern Object semantic_check_cell_part_type(Object);
extern Object send_versioned_ws_notification_internal(Object,Object,Object);
extern Object send_ws_representations_item_virtual_attribute_change(Object,Object,Object);
extern Object set_current_background_color_value(Object);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_simple_part_feature(Object,Object,Object);
extern Object set_simple_part_feature_without_reclaiming(Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object set_subpart_collection_without_reclaiming(Object,Object,Object,Object);
extern Object set_table_cells(Object,Object);
extern Object set_the_specified_cell_features(Object);
extern Object simple_cell_expression_p(Object);
extern Object simple_eval(Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object slot_value_number_p(Object);
extern Object splice_lists(Object,Object,Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object start_edit_of_annotation_subexpression(int,...);
extern Object table_block_insert_or_delete(Object,Object,Object,Object,Object);
extern Object table_dimension_p(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object top_edge_within_pane(Object,Object);
extern Object track_mouse_for_new_table(Object,Object,Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_frame_name_references(Object);
extern Object update_frame_status_and_notes_for_new_table(Object);
extern Object update_new_table_size(void);
extern Object update_object_pool_meters_list(Object);
extern Object update_part_dependencies_for_new_table(Object,Object,Object);
extern Object update_representations_of_slot_value(int,...);
extern Object v5_tw_item_like_p(Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object workspace_of_connection_qm(Object);
extern Object write_evaluation_value(int,...);
extern Object write_part_description(int,...);
extern Object write_table_dimensions_from_slot(Object,Object);

#else

extern Object activate_for_new_table();
extern Object activate_g2_cell_array();
extern Object add_class_to_environment();
extern Object add_grammar_rules_function();
extern Object add_virtual_attribute();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object allocate_managed_array();
extern Object bottom_edge_within_pane();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object callback_representation_fire_callback();
extern Object cell_annotations_for_class();
extern Object cell_updated();
extern Object cell_updated_in_paint_mode();
extern Object change_annotation();
extern Object change_edges_of_block();
extern Object change_in_freeform_table_dimensions_is_ok_p();
extern Object change_in_freeform_table_is_meaningful_p();
extern Object check_if_superior_classes_are_defined();
extern Object clear_optimized_constants();
extern Object combine_and_reclaim_error_strings();
extern Object compile_a_compiled_cell_expression_from_expression_parse_and_style_description();
extern Object compile_part_description();
extern Object compile_table_dimensions_for_slot();
extern Object compiled_cell_expression_p();
extern Object convert_path_to_expression();
extern Object convert_text_string_to_text();
extern Object convert_text_to_text_string();
extern Object copy_and_format_text();
extern Object copy_as_wide_string();
extern Object copy_evaluation_value_1();
extern Object copy_for_slot_value();
extern Object copy_frame_serial_number();
extern Object copy_if_evaluation_value_1();
extern Object copy_managed_float();
extern Object copy_managed_long();
extern Object copy_out_current_wide_string();
extern Object copy_text_box_format();
extern Object copy_text_string();
extern Object copy_wide_string();
extern Object create_compiled_cell_expression();
extern Object deactivate_for_new_table();
extern Object deactivate_g2_cell_array();
extern Object def_part_feature_1();
extern Object def_part_type_1();
extern Object define_type_specification_explicit_complex_type();
extern Object delete_subpart();
extern Object denote_cell_array_element_for_new_table();
extern Object denote_component_of_block();
extern Object denote_component_of_block_1();
extern Object describe_new_table();
extern Object describe_new_table_from_inside_projection();
extern Object describe_part_from_current_extent();
extern Object direct_structure_method();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object do_new_table_edit();
extern Object draw_for_new_table();
extern Object draw_graphic_element();
extern Object draw_text_segment_1();
extern Object enlarge_workspace_for_block_rectangle_if_necessary();
extern Object enter_part_description();
extern Object enter_part_feature_cell_contents();
extern Object enter_part_feature_column_maximum();
extern Object enter_part_feature_column_width();
extern Object enter_part_feature_row_height();
extern Object enter_part_feature_row_maximum();
extern Object enter_part_feature_subparts();
extern Object enter_part_feature_text_value();
extern Object enter_subpart_defaults();
extern Object enter_subpart_exceptions();
extern Object erase_entire_annotated_block();
extern Object erase_part_of_block();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object evaluated_computed_part_feature_p();
extern Object evaluation_sequence_aref();
extern Object evaluation_truth_value_is_true_p();
extern Object evaluation_value_eql();
extern Object evaluation_value_value();
extern Object exit_part_feature_cell_contents();
extern Object exit_part_feature_column_maximum();
extern Object exit_part_feature_column_width();
extern Object exit_part_feature_row_height();
extern Object exit_part_feature_row_maximum();
extern Object exit_part_feature_subparts();
extern Object exit_part_feature_text_value();
extern Object exit_subpart_defaults();
extern Object exit_subpart_exceptions();
extern Object export_cell_attribute_name();
extern Object expression_cell_index_to_cell_coordinates();
extern Object expression_cell_updated_for_new_table();
extern Object find_frame_of_class_in_mouse_pointer();
extern Object force_process_drawing();
extern Object format_text();
extern Object generate_float_vector();
extern Object generate_spot_for_new_table();
extern Object gensym_cons_1();
extern Object get_current_sexp_annotation_hash();
extern Object get_default_computation_style_of_class();
extern Object get_default_formatted_part_of_class();
extern Object get_instance_with_name_if_any();
extern Object get_lookup_slot_value_given_default();
extern Object get_property_value_function();
extern Object get_reference_to_item();
extern Object get_simple_part_feature();
extern Object get_slot_description_of_class_description_function();
extern Object get_subpart_collection();
extern Object get_symbol_properties_function();
extern Object get_table_cells();
extern Object get_workspace_if_any();
extern Object getfq_function_no_default();
extern Object handle_cell_expression();
extern Object image_plane_blackboard_function();
extern Object image_plane_of_mouse_pointer();
extern Object initial_table_cells();
extern Object initialize_after_reading_for_new_table();
extern Object initialize_for_new_table();
extern Object initialize_off_window_color_map();
extern Object initialize_slot_description_value();
extern Object insert_subpart_descriptions();
extern Object invalidate_rectangle_of_workspace();
extern Object item_is_either_not_permanent_or_from_an_editable_module_p();
extern Object javalink_versioned_call_data_evaluated_p();
extern Object javalink_versioned_call_data_get_version();
extern Object javalink_versioned_call_data_sendp();
extern Object javalink_versioning_make_arg_list_copy();
extern Object javalink_versioning_reclaim_evaluated_version_bodies();
extern Object left_edge_within_pane();
extern Object lengthw();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_color_map();
extern Object make_edit_state_1();
extern Object make_evaluation_long();
extern Object make_evaluation_place_reference_to_place();
extern Object make_evaluation_value_for_expression_cell_index();
extern Object make_format_frame();
extern Object make_frame();
extern Object make_javalink_versioned_data();
extern Object make_monochrome_color_description_plist();
extern Object make_named_dynamic_extent_description();
extern Object make_new_table_background_spot_1();
extern Object make_new_table_cell_spot_1();
extern Object make_new_table_spot_1();
extern Object make_permanent_new_table_background_spot_structure_internal();
extern Object make_permanent_new_table_cell_spot_structure_internal();
extern Object make_permanent_new_table_spot_structure_internal();
extern Object make_sequence_of_freeform_table_row();
extern Object make_sexp_annotation_hash();
extern Object make_slot_value_list_1();
extern Object make_structure_for_cell_contents();
extern Object make_structure_for_cell_format();
extern Object make_table_annotation();
extern Object make_text_for_datum();
extern Object make_thread_array();
extern Object map_over_part_description();
extern Object map_to_color_value();
extern Object map_to_color_value_1();
extern Object memq_function();
extern Object mouse_over_cell_in_new_table_p();
extern Object mutate_global_property();
extern Object new_table_background_spot_structure_memory_usage();
extern Object new_table_cell_spot_structure_memory_usage();
extern Object new_table_spot_structure_memory_usage();
extern Object note_change_to_block_1();
extern Object original_x_in_window_blackboard_function();
extern Object original_y_in_window_blackboard_function();
extern Object outstanding_new_table_background_spot_count();
extern Object outstanding_new_table_cell_spot_count();
extern Object outstanding_new_table_spot_count();
extern Object parse_text_string();
extern Object part_has_feature_p();
extern Object part_stack_cons_1();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object phrase_list_4();
extern Object place_reference_of_cell_for_new_table();
extern Object project_new_table();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_cell_annotations();
extern Object put_default_cell_format();
extern Object put_default_evaluation_setting();
extern Object read_number_from_string();
extern Object read_symbol_from_string();
extern Object read_text_string_from_string();
extern Object reclaim_edit_state_1();
extern Object reclaim_evaluation_place_reference();
extern Object reclaim_evaluation_structure();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_new_table_background_spot_1();
extern Object reclaim_new_table_cell_spot_1();
extern Object reclaim_new_table_spot_1();
extern Object reclaim_part_description();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_structure_if_any();
extern Object reclaim_text_string();
extern Object recompile_component_of_part_description();
extern Object recompile_expression_at_component_particulars_for_new_table();
extern Object recompile_item();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object redraw_entire_annotated_block();
extern Object redraw_part_of_block();
extern Object regenerate_optimized_constant();
extern Object remote_icp_protocol_version();
extern Object remove_evaluation_structure_attribute();
extern Object remove_simple_part_feature();
extern Object replenish_part_stack_cons_pool();
extern Object replenish_stack_change_cons_pool();
extern Object representation_address_valid_p();
extern Object right_edge_within_pane();
extern Object row_and_column_index_available_p();
extern Object scalef_function();
extern Object semantic_check_cell_part_type();
extern Object send_versioned_ws_notification_internal();
extern Object send_ws_representations_item_virtual_attribute_change();
extern Object set_current_background_color_value();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_property_value_function();
extern Object set_simple_part_feature();
extern Object set_simple_part_feature_without_reclaiming();
extern Object set_slot_value_to_evaluation_value_function();
extern Object set_subpart_collection_without_reclaiming();
extern Object set_table_cells();
extern Object set_the_specified_cell_features();
extern Object simple_cell_expression_p();
extern Object simple_eval();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object slot_value_number_p();
extern Object splice_lists();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object start_edit_of_annotation_subexpression();
extern Object table_block_insert_or_delete();
extern Object table_dimension_p();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object top_edge_within_pane();
extern Object track_mouse_for_new_table();
extern Object twrite_beginning_of_wide_string();
extern Object type_error_in_setter();
extern Object type_specification_type_p__with_explanation();
extern Object update_all_representations_of_slot();
extern Object update_frame_name_references();
extern Object update_frame_status_and_notes_for_new_table();
extern Object update_new_table_size();
extern Object update_object_pool_meters_list();
extern Object update_part_dependencies_for_new_table();
extern Object update_representations_of_slot_value();
extern Object v5_tw_item_like_p();
extern Object validate_item_or_evaluation_value();
extern Object workspace_of_connection_qm();
extern Object write_evaluation_value();
extern Object write_part_description();
extern Object write_table_dimensions_from_slot();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_part_stack_conses_tail_vector;
extern Object Available_part_stack_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Background_color_value_from_postponed_erase, Qbackground_color_value_from_postponed_erase);
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Basic_part, Qbasic_part);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Breakpoint_level, Qbreakpoint_level);
DECLARE_VARIABLE_WITH_SYMBOL(Cell, Qcell);
DECLARE_VARIABLE_WITH_SYMBOL(Cell_contents, Qcell_contents);
DECLARE_VARIABLE_WITH_SYMBOL(Cell_index_currently_being_registered, Qcell_index_currently_being_registered);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_new_table_background_spots, Qchain_of_available_new_table_background_spots);
extern Object Chain_of_available_new_table_background_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_new_table_cell_spots, Qchain_of_available_new_table_cell_spots);
extern Object Chain_of_available_new_table_cell_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_new_table_spots, Qchain_of_available_new_table_spots);
extern Object Chain_of_available_new_table_spots_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Changing_colors_of_graphic_elements_qm, Qchanging_colors_of_graphic_elements_qm);
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
DECLARE_VARIABLE_WITH_SYMBOL(Column_maximum, Qcolumn_maximum);
DECLARE_VARIABLE_WITH_SYMBOL(Column_width, Qcolumn_width);
DECLARE_VARIABLE_WITH_SYMBOL(Compiled_cell_expression, Qcompiled_cell_expression);
DECLARE_VARIABLE_WITH_SYMBOL(Computation_style_description, Qcomputation_style_description);
DECLARE_VARIABLE_WITH_SYMBOL(Connection_class_description, Qconnection_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Create_subpart_upon_tracking_p, Qcreate_subpart_upon_tracking_p);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_annotated_frame, Qcurrent_annotated_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_block_of_dependent_frame, Qcurrent_block_of_dependent_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_cell, Qcurrent_cell);
DECLARE_VARIABLE_WITH_SYMBOL(Current_color_map, Qcurrent_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(Current_column, Qcurrent_column);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_style, Qcurrent_computation_style);
DECLARE_VARIABLE_WITH_SYMBOL(Current_description_of_new_table, Qcurrent_description_of_new_table);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_priority, Qcurrent_drawing_priority);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_height_of_formatted_part, Qcurrent_height_of_formatted_part);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kind_of_change, Qcurrent_kind_of_change);
DECLARE_VARIABLE_WITH_SYMBOL(Current_lookup_data, Qcurrent_lookup_data);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_new_table, Qcurrent_new_table);
DECLARE_VARIABLE_WITH_SYMBOL(Current_pane, Qcurrent_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_part_description, Qcurrent_part_description);
DECLARE_VARIABLE_WITH_SYMBOL(Current_projection_function_for_funcall, Qcurrent_projection_function_for_funcall);
DECLARE_VARIABLE_WITH_SYMBOL(Current_row, Qcurrent_row);
DECLARE_VARIABLE_WITH_SYMBOL(Current_text_box_format, Qcurrent_text_box_format);
DECLARE_VARIABLE_WITH_SYMBOL(Current_text_cell_plist, Qcurrent_text_cell_plist);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thing_changed, Qcurrent_thing_changed);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_tracking_subcomponent, Qcurrent_tracking_subcomponent);
DECLARE_VARIABLE_WITH_SYMBOL(Current_tracking_x_in_window, Qcurrent_tracking_x_in_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_tracking_y_in_window, Qcurrent_tracking_y_in_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_width_of_formatted_part, Qcurrent_width_of_formatted_part);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_on_window, Qdrawing_on_window);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_parameters, Qdrawing_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Editing_new_table, Qediting_new_table);
DECLARE_VARIABLE_WITH_SYMBOL(Erase_instead_qm, Qerase_instead_qm);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Expression_cell_index, Qexpression_cell_index);
DECLARE_VARIABLE_WITH_SYMBOL(Expression_source_text, Qexpression_source_text);
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(For_image_plane, Qfor_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Formatted_part, Qformatted_part);
DECLARE_VARIABLE_WITH_SYMBOL(Formatted_part_highlight_flag, Qformatted_part_highlight_flag);
DECLARE_VARIABLE_WITH_SYMBOL(G2_has_v5_mode_windows_p, Qg2_has_v5_mode_windows_p);
DECLARE_VARIABLE_WITH_SYMBOL(Generate_source_annotation_info, Qgenerate_source_annotation_info);
DECLARE_VARIABLE_WITH_SYMBOL(In_suspend_resume_p, Qin_suspend_resume_p);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Javalink_notification_versions, Qjavalink_notification_versions);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_flags, Qkb_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_bottom_edge_of_visible_workspace_area, Qloose_bottom_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_left_edge_of_visible_workspace_area, Qloose_left_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_right_edge_of_visible_workspace_area, Qloose_right_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_top_edge_of_visible_workspace_area, Qloose_top_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Maintain_stack_of_current_part_descriptions_p, Qmaintain_stack_of_current_part_descriptions_p);
#define Managed_array_index_offset FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_height, Qmaximum_height);
extern Object Maximum_in_place_array_size;
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_width, Qmaximum_width);
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(New_table, Qnew_table);
DECLARE_VARIABLE_WITH_SYMBOL(New_table_background_spot_count, Qnew_table_background_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(New_table_cell_spot_count, Qnew_table_cell_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(New_table_spot_count, Qnew_table_spot_count);
DECLARE_VARIABLE_WITH_SYMBOL(Notification_data_version_map, Qnotification_data_version_map);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Off_window_color_map, Qoff_window_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(On_window_without_drawing, Qon_window_without_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Part_feature_exit_methods, Qpart_feature_exit_methods);
DECLARE_VARIABLE_WITH_SYMBOL(Part_feature_recall_stack, Qpart_feature_recall_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Postpone_cell_erase_until_redraw_p, Qpostpone_cell_erase_until_redraw_p);
DECLARE_VARIABLE_WITH_SYMBOL(Projecting_to_collect_description_for_new_table, Qprojecting_to_collect_description_for_new_table);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_computing_path_of_focus, Qprojection_computing_path_of_focus);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_drawing, Qprojection_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_focus_annotation, Qprojection_focus_annotation);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_focus_cell_index, Qprojection_focus_cell_index);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_focus_cell_new_cached_value, Qprojection_focus_cell_new_cached_value);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_focus_method, Qprojection_focus_method);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_focus_path, Qprojection_focus_path);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_funcall_on_focus, Qprojection_funcall_on_focus);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_mode, Qprojection_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_of_new_table_accumulating_size, Qprojection_of_new_table_accumulating_size);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_tracking, Qprojection_tracking);
DECLARE_VARIABLE_WITH_SYMBOL(Projection_update_dependencies, Qprojection_update_dependencies);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Reclaim_text_value_from_postponed_erase_p, Qreclaim_text_value_from_postponed_erase_p);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Row_height, Qrow_height);
DECLARE_VARIABLE_WITH_SYMBOL(Row_maximum, Qrow_maximum);
DECLARE_VARIABLE_WITH_SYMBOL(Scanning_subparts_of_block, Qscanning_subparts_of_block);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_current_part_descriptions, Qstack_of_current_part_descriptions);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Subpart_defaults, Qsubpart_defaults);
DECLARE_VARIABLE_WITH_SYMBOL(Subpart_exceptions, Qsubpart_exceptions);
DECLARE_VARIABLE_WITH_SYMBOL(Subparts, Qsubparts);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Text_value, Qtext_value);
DECLARE_VARIABLE_WITH_SYMBOL(Text_value_from_postponed_erase, Qtext_value_from_postponed_erase);
DECLARE_VARIABLE_WITH_SYMBOL(The_only_dynamic_computation_style, Qthe_only_dynamic_computation_style);
extern Object The_type_description_of_new_table_background_spot;
extern Object The_type_description_of_new_table_cell_spot;
extern Object The_type_description_of_new_table_spot;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Tracing_message_level, Qtracing_message_level);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
DECLARE_VARIABLE_WITH_SYMBOL(Updated_only_qm, Qupdated_only_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Working_on_annotated_frame, Qworking_on_annotated_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Working_on_new_table, Qworking_on_new_table);
