/* parse.h -- Header File for parse.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand;
extern Object Qcar;
extern Object Qcdr;
extern Object Qcons;
extern Object Qeq;
extern Object Qeql;
extern Object Qfloat;
extern Object Kfrom_end;
extern Object Kinitial_element;
extern Object Qinteger;
extern Object Kkey;
extern Object Kname;
extern Object Qnumber;
extern Object Qquote;
extern Object Qsecond;
extern Object Qsymbol;
extern Object Ktest_not;
extern Object Kupcase;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_another_vector_for_phrase_conses(void);
extern Object add_batch_grammar_rule(Object);
extern Object add_category_to_bit_set(Object,Object);
extern Object add_constituent_to_incomplete_phrase_per_transformation(Object,Object,Object);
extern Object add_constituent_to_incomplete_phrases(Object,Object,Object);
extern Object add_grammar_instance_rule(Object,Object,Object);
extern Object add_grammar_phrase_rule(Object,Object,Object);
extern Object add_grammar_rule(Object);
extern Object add_grammar_rule_1(Object);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_kb_specific_symbol_token(Object,Object);
extern Object add_menu_items_for_category(Object,Object,Object,Object);
extern Object add_menu_items_for_not_yet_visited_non_token_category(Object,Object);
extern Object add_menu_items_for_not_yet_visited_token_category(Object,Object,Object);
extern Object add_menu_items_for_parsing_for_category(Object,Object);
extern Object add_semi_open_categories_to_directories(void);
extern Object add_to_directory_of_names(Object,Object);
extern Object add_token_for_parsing_for_category(Object,Object);
extern Object all_token_lists_are_pre_existing_p(Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_simple_vector(Object);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object annotation_structure_memory_usage(void);
extern Object approximate_size_of_token(Object);
extern Object assq_function(Object,Object);
extern Object atomic_phrase_p(Object);
extern Object begin_phrases_addable_to_some_incomplete_phrase_with_agenda(Object,Object,Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object category_for_category_symbol_structure_memory_usage(void);
extern Object category_for_token_structure_memory_usage(void);
extern Object category_set_memq(Object,Object);
extern Object category_set_push_1(Object,Object);
extern Object category_set_structure_memory_usage(void);
extern Object check_range_of_element(Object,Object,Object,Object);
extern Object clear_optimized_constants(void);
extern Object clear_sexp_annotation(Object);
extern Object clear_sexp_annotation_tree(Object);
extern Object clone_annotation(Object);
extern Object compile_grammar(Object);
extern Object convert_to_category_set(Object);
extern Object copy_for_phrase(Object);
extern Object copy_list_using_grammar_conses_1(Object);
extern Object copy_list_using_phrase_conses(Object);
extern Object copy_list_using_phrase_pool_conses_1(Object);
extern Object copy_managed_float(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_tree_using_grammar_conses_1(Object);
extern Object copy_tree_using_phrase_conses(Object);
extern Object copy_tree_using_phrase_pool_conses_1(Object);
extern Object decache_all_strict_subcategory_infos(void);
extern Object def_semi_open_category_1(int,...);
extern Object delete_grammar_cons_1(Object,Object);
extern Object delete_grammar_element_1(Object,Object);
extern Object delete_phrase_pool_cons_1(Object,Object);
extern Object delete_phrase_pool_element_1(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object edit_box_change_structure_memory_usage(void);
extern Object edit_state_structure_memory_usage(void);
extern Object ensure_transform_constituent_array(Object);
extern Object extend_lists_of_following_tokens(Object,Object,Object);
extern Object fill_in_categories_this_can_be_or_begin(Object,Object);
extern Object flatten_sexp_annotation(Object);
extern Object flatten_skip_list(Object);
extern Object format_symbol(int,...);
extern Object frame_has_been_reprocessed_p_function(Object,Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_grammar_structure_memory_usage(void);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object get_category_of_token(Object);
extern Object get_current_annotation_context(Object);
extern Object get_current_sexp_annotation_hash(void);
extern Object get_gensym_grammar(Object);
extern Object get_lists_of_following_tokens(Object,Object,Object);
extern Object get_more_general_categories_and_transformations(Object);
extern Object get_more_general_categories_and_transformations_1(Object,Object);
extern Object get_or_make_category_for_category_symbol(Object);
extern Object get_or_make_category_for_rule_element(Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object grammar_cons_1(Object,Object);
extern Object grammar_cons_memory_usage(void);
extern Object grammar_list_2(Object,Object);
extern Object grammar_list_3(Object,Object,Object);
extern Object grammar_list_4(Object,Object,Object,Object);
extern Object grammar_list_trace_hook(Object);
extern Object have_constituent_to_annotate_p(Object,Object);
extern Object incomplete_phrase_structure_memory_usage(void);
extern Object indices_of_bits_in_category_vector(Object);
extern Object instance_of_category_acceptable_p(Object,Object,Object);
extern Object instance_rule_p(Object);
extern Object lengthw(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_annotation_1(Object,Object);
extern Object make_category_for_category_symbol_1(Object);
extern Object make_category_for_token(Object,Object);
extern Object make_category_for_token_structure_1(Object);
extern Object make_category_instance_menus(Object,Object,Object);
extern Object make_category_set_1(Object,Object);
extern Object make_constituent_per_template(Object,Object,Object,Object);
extern Object make_edit_box_change_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_edit_state_1(void);
extern Object make_gensym_grammar(Object);
extern Object make_gensym_grammar_internal_1(Object);
extern Object make_grammar_list_1(Object);
extern Object make_hfep_hanc_type_function(void);
extern Object make_incomplete_phrase_structure_1(Object,Object,Object,Object);
extern Object make_menu_content_structure_for_character_position(Object,Object,Object);
extern Object make_menu_content_structure_for_token_position(Object,Object);
extern Object make_menu_of_names_from_directory_if_few_enough(Object,Object,Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_permanent_annotation_structure_internal(void);
extern Object make_permanent_category_for_category_symbol_structure_internal(void);
extern Object make_permanent_category_for_token_structure_internal(void);
extern Object make_permanent_category_set_structure_internal(void);
extern Object make_permanent_edit_box_change_structure_internal(void);
extern Object make_permanent_edit_state_structure_internal(void);
extern Object make_permanent_gensym_grammar_structure_internal(void);
extern Object make_permanent_incomplete_phrase_structure_internal(void);
extern Object make_permanent_phrase_rule_completion_structure_internal(void);
extern Object make_permanent_sexp_annotation_hash_vector_43_vector_internal(void);
extern Object make_permanent_strict_subcategory_info_structure_internal(void);
extern Object make_phrase_list(Object);
extern Object make_phrase_pool_list_1(Object);
extern Object make_phrase_rule_completion_1(Object,Object,Object);
extern Object make_sexp_annotation_hash(void);
extern Object make_sexp_annotation_hash_vector(void);
extern Object make_sexp_annotation_tree_for_hash_skip_list_sentinel(Object,Object);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_strict_subcategory_info_1(Object,Object,Object);
extern Object make_thread_array(Object);
extern Object maybe_annotate_constituent(Object,Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object note_use_of_managed_float_in_phrase(Object);
extern Object note_use_of_managed_long_in_phrase(Object);
extern Object note_use_of_text_string_in_phrase(Object);
extern Object of_class_p_function(Object,Object);
extern Object out_sexp_annotation_hash_vector_43_vectors(void);
extern Object outstanding_annotation_count(void);
extern Object outstanding_category_for_category_symbol_count(void);
extern Object outstanding_category_for_token_count(void);
extern Object outstanding_category_set_count(void);
extern Object outstanding_edit_box_change_count(void);
extern Object outstanding_edit_state_count(void);
extern Object outstanding_gensym_grammar_count(void);
extern Object outstanding_grammar_conses(void);
extern Object outstanding_incomplete_phrase_count(void);
extern Object outstanding_phrase_pool_conses(void);
extern Object outstanding_phrase_rule_completion_count(void);
extern Object outstanding_strict_subcategory_info_count(void);
extern Object parsing_context_cursor_token_function(Object);
extern Object parsing_token_incomplete_phrases_function(Object);
extern Object perform_transformation_operations(Object,Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_cons_with_args_reversed(Object,Object);
extern Object phrase_flatten_tree(Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_3(Object,Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object phrase_number_p(Object);
extern Object phrase_pool_cons_1(Object,Object);
extern Object phrase_pool_cons_memory_usage(void);
extern Object phrase_pool_list_2(Object,Object);
extern Object phrase_pool_list_3(Object,Object,Object);
extern Object phrase_pool_list_4(Object,Object,Object,Object);
extern Object phrase_pool_list_trace_hook(Object);
extern Object phrase_rule_completion_structure_memory_usage(void);
extern Object phrase_rule_completions_addable_to_some_incomplete_phrase(Object,Object);
extern Object phrase_rule_completions_addable_to_some_incomplete_phrase_1(Object,Object);
extern Object phrases_addable_to_some_incomplete_phrase_inner_2(Object,Object,Object,Object);
extern Object print_indices_of_bits_in_category_vector(Object,Object);
extern Object process_grammar_rule_for_development_if_appropriate(Object);
extern Object push_optimized_constant(Object);
extern Object reclaim_agenda_of_more_general_categories(Object);
extern Object reclaim_annotation_1(Object);
extern Object reclaim_annotation_qm(Object);
extern Object reclaim_byte_vector_16(Object);
extern Object reclaim_cached_strict_subcategory_info(Object);
extern Object reclaim_category_for_category_symbol_1(Object);
extern Object reclaim_category_for_token_1(Object);
extern Object reclaim_category_set_1(Object);
extern Object reclaim_category_symbols(Object);
extern Object reclaim_chain_of_incomplete_phrases(Object);
extern Object reclaim_edit_box_change_1(Object);
extern Object reclaim_edit_state_1(Object);
extern Object reclaim_edit_undo_or_redo_stack(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_grammar_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_list_if_list(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_gensym_tree_function(Object);
extern Object reclaim_grammar_cons_1(Object);
extern Object reclaim_grammar_list_1(Object);
extern Object reclaim_grammar_list_function(Object);
extern Object reclaim_grammar_list_star_1(Object);
extern Object reclaim_grammar_tree_1(Object);
extern Object reclaim_hfep_hanc_type_function(Object);
extern Object reclaim_incomplete_phrase_1(Object);
extern Object reclaim_managed_floats_in_phrases(Object);
extern Object reclaim_managed_longs_in_phrases(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_managed_simple_long_array_of_length_1(Object);
extern Object reclaim_managed_simple_vector(Object);
extern Object reclaim_menu_content_structure(Object);
extern Object reclaim_most_recent_reason_for_bad_parse_qm(Object);
extern Object reclaim_pending_procedure_signature_workspaces(Object);
extern Object reclaim_phrase_pool_cons_1(Object);
extern Object reclaim_phrase_pool_list_1(Object);
extern Object reclaim_phrase_pool_list_star_1(Object);
extern Object reclaim_phrase_pool_tree_1(Object);
extern Object reclaim_phrase_rule_completion_1(Object);
extern Object reclaim_phrase_rule_completions(Object);
extern Object reclaim_sexp_annotation_hash(Object);
extern Object reclaim_sexp_annotation_hash_qm(Object);
extern Object reclaim_sexp_annotation_hash_vector(Object);
extern Object reclaim_sexp_annotation_tree_for_hash_nodes(Object,Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_strict_subcategory_info_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_text_strings_in_phrases(Object);
extern Object reclaim_tokens_with_specific_categories(Object);
extern Object reclaim_vectors_for_phrase_conses(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object release_mouse_pointers(Object);
extern Object remove_duplicates_from_lists_of_token_lists(Object);
extern Object remove_grammar_plist_element(Object,Object);
extern Object remove_noise_at_head_of_list_phrase(Object);
extern Object replenish_grammar_cons_pool(void);
extern Object replenish_grammar_list_pool(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_phrase_pool_cons_pool(void);
extern Object replenish_phrase_pool_list_pool(Object);
extern Object replenish_vector_pool_cons_pool(void);
extern Object reserve_words(Object);
extern Object semi_open_category_p(int,...);
extern Object set_category_of_token(Object,Object);
extern Object set_current_annotation_context(Object,Object);
extern Object set_current_grammar(Object);
extern Object set_current_subcategory_path(Object,Object);
extern Object set_grammar_transform_can_return_bad_phrase_p(Object);
extern Object set_nth_element_of_variable_length_grammar_list(int,...);
extern Object set_sexp_annotation_hash(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_token_menu_string_to_display_function(Object,Object);
extern Object set_token_menu_string_to_insert_function(Object,Object);
extern Object set_up_agendas_1(Object);
extern Object set_up_agendas_of_more_general_categories_to_search(void);
extern Object set_up_category_visit(void);
extern Object sexp_annotation_hash_vector_43_vector_memory_usage(void);
extern Object simplify_associative_list_operation_all_at_once(Object);
extern Object simplify_associative_operation(Object);
extern Object simplify_last_of_nary_associative_operator(Object);
extern Object skip_menu_items_if_all_are_repeats(Object,Object);
extern Object sole_completion_for_beginning_category_to_category(Object,Object);
extern Object strict_subcategory_info(Object,Object);
extern Object strict_subcategory_info_1(Object,Object);
extern Object strict_subcategory_info_structure_memory_usage(void);
extern Object strict_subcategory_path(Object,Object);
extern Object strict_subcategory_path_1(Object,Object);
extern Object strict_subcategoryp(Object,Object);
extern Object strict_subcategoryp_1(Object,Object);
extern Object string_eq_w(Object,Object);
extern Object subcategoryp(Object,Object);
extern Object symbol_name_text_string(Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object transform_by_template(Object);
extern Object transform_by_template_rec(Object,Object,Object);
extern Object transform_constituent(Object,Object);
extern Object transform_constituent_completely(Object,Object,Object,Object);
extern Object transform_constituent_for_add_constituent_to_incomplete_phrase(Object,Object,Object,Object);
extern Object transform_constituent_for_incomplete_phrase(Object,Object,Object);
extern Object transform_constituent_per_template(Object,Object);
extern Object twrite(Object);
extern Object update_object_pool_meters_list(Object);

#else

extern Object add_another_vector_for_phrase_conses();
extern Object add_batch_grammar_rule();
extern Object add_category_to_bit_set();
extern Object add_constituent_to_incomplete_phrase_per_transformation();
extern Object add_constituent_to_incomplete_phrases();
extern Object add_grammar_instance_rule();
extern Object add_grammar_phrase_rule();
extern Object add_grammar_rule();
extern Object add_grammar_rule_1();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_kb_specific_symbol_token();
extern Object add_menu_items_for_category();
extern Object add_menu_items_for_not_yet_visited_non_token_category();
extern Object add_menu_items_for_not_yet_visited_token_category();
extern Object add_menu_items_for_parsing_for_category();
extern Object add_semi_open_categories_to_directories();
extern Object add_to_directory_of_names();
extern Object add_token_for_parsing_for_category();
extern Object all_token_lists_are_pre_existing_p();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_simple_vector();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object annotation_structure_memory_usage();
extern Object approximate_size_of_token();
extern Object assq_function();
extern Object atomic_phrase_p();
extern Object begin_phrases_addable_to_some_incomplete_phrase_with_agenda();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object bytes_per_typed_simple_array();
extern Object category_for_category_symbol_structure_memory_usage();
extern Object category_for_token_structure_memory_usage();
extern Object category_set_memq();
extern Object category_set_push_1();
extern Object category_set_structure_memory_usage();
extern Object check_range_of_element();
extern Object clear_optimized_constants();
extern Object clear_sexp_annotation();
extern Object clear_sexp_annotation_tree();
extern Object clone_annotation();
extern Object compile_grammar();
extern Object convert_to_category_set();
extern Object copy_for_phrase();
extern Object copy_list_using_grammar_conses_1();
extern Object copy_list_using_phrase_conses();
extern Object copy_list_using_phrase_pool_conses_1();
extern Object copy_managed_float();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_tree_using_grammar_conses_1();
extern Object copy_tree_using_phrase_conses();
extern Object copy_tree_using_phrase_pool_conses_1();
extern Object decache_all_strict_subcategory_infos();
extern Object def_semi_open_category_1();
extern Object delete_grammar_cons_1();
extern Object delete_grammar_element_1();
extern Object delete_phrase_pool_cons_1();
extern Object delete_phrase_pool_element_1();
extern Object direct_structure_method();
extern Object edit_box_change_structure_memory_usage();
extern Object edit_state_structure_memory_usage();
extern Object ensure_transform_constituent_array();
extern Object extend_lists_of_following_tokens();
extern Object fill_in_categories_this_can_be_or_begin();
extern Object flatten_sexp_annotation();
extern Object flatten_skip_list();
extern Object format_symbol();
extern Object frame_has_been_reprocessed_p_function();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_grammar_structure_memory_usage();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object gensym_list_4();
extern Object get_category_of_token();
extern Object get_current_annotation_context();
extern Object get_current_sexp_annotation_hash();
extern Object get_gensym_grammar();
extern Object get_lists_of_following_tokens();
extern Object get_more_general_categories_and_transformations();
extern Object get_more_general_categories_and_transformations_1();
extern Object get_or_make_category_for_category_symbol();
extern Object get_or_make_category_for_rule_element();
extern Object get_slot_value_function();
extern Object getfq_function_no_default();
extern Object grammar_cons_1();
extern Object grammar_cons_memory_usage();
extern Object grammar_list_2();
extern Object grammar_list_3();
extern Object grammar_list_4();
extern Object grammar_list_trace_hook();
extern Object have_constituent_to_annotate_p();
extern Object incomplete_phrase_structure_memory_usage();
extern Object indices_of_bits_in_category_vector();
extern Object instance_of_category_acceptable_p();
extern Object instance_rule_p();
extern Object lengthw();
extern Object load_and_initialize_type_description();
extern Object lookup_kb_specific_property_value();
extern Object make_annotation_1();
extern Object make_category_for_category_symbol_1();
extern Object make_category_for_token();
extern Object make_category_for_token_structure_1();
extern Object make_category_instance_menus();
extern Object make_category_set_1();
extern Object make_constituent_per_template();
extern Object make_edit_box_change_1();
extern Object make_edit_state_1();
extern Object make_gensym_grammar();
extern Object make_gensym_grammar_internal_1();
extern Object make_grammar_list_1();
extern Object make_hfep_hanc_type_function();
extern Object make_incomplete_phrase_structure_1();
extern Object make_menu_content_structure_for_character_position();
extern Object make_menu_content_structure_for_token_position();
extern Object make_menu_of_names_from_directory_if_few_enough();
extern Object make_named_dynamic_extent_description();
extern Object make_permanent_annotation_structure_internal();
extern Object make_permanent_category_for_category_symbol_structure_internal();
extern Object make_permanent_category_for_token_structure_internal();
extern Object make_permanent_category_set_structure_internal();
extern Object make_permanent_edit_box_change_structure_internal();
extern Object make_permanent_edit_state_structure_internal();
extern Object make_permanent_gensym_grammar_structure_internal();
extern Object make_permanent_incomplete_phrase_structure_internal();
extern Object make_permanent_phrase_rule_completion_structure_internal();
extern Object make_permanent_sexp_annotation_hash_vector_43_vector_internal();
extern Object make_permanent_strict_subcategory_info_structure_internal();
extern Object make_phrase_list();
extern Object make_phrase_pool_list_1();
extern Object make_phrase_rule_completion_1();
extern Object make_sexp_annotation_hash();
extern Object make_sexp_annotation_hash_vector();
extern Object make_sexp_annotation_tree_for_hash_skip_list_sentinel();
extern Object make_skip_list_element_1();
extern Object make_strict_subcategory_info_1();
extern Object make_thread_array();
extern Object maybe_annotate_constituent();
extern Object memq_function();
extern Object mutate_global_property();
extern Object mutate_kb_specific_property_value();
extern Object note_use_of_managed_float_in_phrase();
extern Object note_use_of_managed_long_in_phrase();
extern Object note_use_of_text_string_in_phrase();
extern Object of_class_p_function();
extern Object out_sexp_annotation_hash_vector_43_vectors();
extern Object outstanding_annotation_count();
extern Object outstanding_category_for_category_symbol_count();
extern Object outstanding_category_for_token_count();
extern Object outstanding_category_set_count();
extern Object outstanding_edit_box_change_count();
extern Object outstanding_edit_state_count();
extern Object outstanding_gensym_grammar_count();
extern Object outstanding_grammar_conses();
extern Object outstanding_incomplete_phrase_count();
extern Object outstanding_phrase_pool_conses();
extern Object outstanding_phrase_rule_completion_count();
extern Object outstanding_strict_subcategory_info_count();
extern Object parsing_context_cursor_token_function();
extern Object parsing_token_incomplete_phrases_function();
extern Object perform_transformation_operations();
extern Object phrase_cons();
extern Object phrase_cons_with_args_reversed();
extern Object phrase_flatten_tree();
extern Object phrase_list_2();
extern Object phrase_list_3();
extern Object phrase_list_4();
extern Object phrase_number_p();
extern Object phrase_pool_cons_1();
extern Object phrase_pool_cons_memory_usage();
extern Object phrase_pool_list_2();
extern Object phrase_pool_list_3();
extern Object phrase_pool_list_4();
extern Object phrase_pool_list_trace_hook();
extern Object phrase_rule_completion_structure_memory_usage();
extern Object phrase_rule_completions_addable_to_some_incomplete_phrase();
extern Object phrase_rule_completions_addable_to_some_incomplete_phrase_1();
extern Object phrases_addable_to_some_incomplete_phrase_inner_2();
extern Object print_indices_of_bits_in_category_vector();
extern Object process_grammar_rule_for_development_if_appropriate();
extern Object push_optimized_constant();
extern Object reclaim_agenda_of_more_general_categories();
extern Object reclaim_annotation_1();
extern Object reclaim_annotation_qm();
extern Object reclaim_byte_vector_16();
extern Object reclaim_cached_strict_subcategory_info();
extern Object reclaim_category_for_category_symbol_1();
extern Object reclaim_category_for_token_1();
extern Object reclaim_category_set_1();
extern Object reclaim_category_symbols();
extern Object reclaim_chain_of_incomplete_phrases();
extern Object reclaim_edit_box_change_1();
extern Object reclaim_edit_state_1();
extern Object reclaim_edit_undo_or_redo_stack();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_grammar_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_list_if_list();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_gensym_tree_function();
extern Object reclaim_grammar_cons_1();
extern Object reclaim_grammar_list_1();
extern Object reclaim_grammar_list_function();
extern Object reclaim_grammar_list_star_1();
extern Object reclaim_grammar_tree_1();
extern Object reclaim_hfep_hanc_type_function();
extern Object reclaim_incomplete_phrase_1();
extern Object reclaim_managed_floats_in_phrases();
extern Object reclaim_managed_longs_in_phrases();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_managed_simple_long_array_of_length_1();
extern Object reclaim_managed_simple_vector();
extern Object reclaim_menu_content_structure();
extern Object reclaim_most_recent_reason_for_bad_parse_qm();
extern Object reclaim_pending_procedure_signature_workspaces();
extern Object reclaim_phrase_pool_cons_1();
extern Object reclaim_phrase_pool_list_1();
extern Object reclaim_phrase_pool_list_star_1();
extern Object reclaim_phrase_pool_tree_1();
extern Object reclaim_phrase_rule_completion_1();
extern Object reclaim_phrase_rule_completions();
extern Object reclaim_sexp_annotation_hash();
extern Object reclaim_sexp_annotation_hash_qm();
extern Object reclaim_sexp_annotation_hash_vector();
extern Object reclaim_sexp_annotation_tree_for_hash_nodes();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value();
extern Object reclaim_strict_subcategory_info_1();
extern Object reclaim_text_string();
extern Object reclaim_text_strings_in_phrases();
extern Object reclaim_tokens_with_specific_categories();
extern Object reclaim_vectors_for_phrase_conses();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object release_mouse_pointers();
extern Object remove_duplicates_from_lists_of_token_lists();
extern Object remove_grammar_plist_element();
extern Object remove_noise_at_head_of_list_phrase();
extern Object replenish_grammar_cons_pool();
extern Object replenish_grammar_list_pool();
extern Object replenish_lookup_cons_pool();
extern Object replenish_phrase_pool_cons_pool();
extern Object replenish_phrase_pool_list_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object reserve_words();
extern Object semi_open_category_p();
extern Object set_category_of_token();
extern Object set_current_annotation_context();
extern Object set_current_grammar();
extern Object set_current_subcategory_path();
extern Object set_grammar_transform_can_return_bad_phrase_p();
extern Object set_nth_element_of_variable_length_grammar_list();
extern Object set_sexp_annotation_hash();
extern Object set_skip_list_entry();
extern Object set_token_menu_string_to_display_function();
extern Object set_token_menu_string_to_insert_function();
extern Object set_up_agendas_1();
extern Object set_up_agendas_of_more_general_categories_to_search();
extern Object set_up_category_visit();
extern Object sexp_annotation_hash_vector_43_vector_memory_usage();
extern Object simplify_associative_list_operation_all_at_once();
extern Object simplify_associative_operation();
extern Object simplify_last_of_nary_associative_operator();
extern Object skip_menu_items_if_all_are_repeats();
extern Object sole_completion_for_beginning_category_to_category();
extern Object strict_subcategory_info();
extern Object strict_subcategory_info_1();
extern Object strict_subcategory_info_structure_memory_usage();
extern Object strict_subcategory_path();
extern Object strict_subcategory_path_1();
extern Object strict_subcategoryp();
extern Object strict_subcategoryp_1();
extern Object string_eq_w();
extern Object subcategoryp();
extern Object symbol_name_text_string();
extern Object text_string_length();
extern Object text_string_p();
extern Object transform_by_template();
extern Object transform_by_template_rec();
extern Object transform_constituent();
extern Object transform_constituent_completely();
extern Object transform_constituent_for_add_constituent_to_incomplete_phrase();
extern Object transform_constituent_for_incomplete_phrase();
extern Object transform_constituent_per_template();
extern Object twrite();
extern Object update_object_pool_meters_list();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Annotation_count, Qannotation_count);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_grammar_conses, Qavailable_grammar_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_grammar_conses_tail, Qavailable_grammar_conses_tail);
extern Object Available_grammar_conses_tail_vector;
extern Object Available_grammar_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_phrase_pool_conses, Qavailable_phrase_pool_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_phrase_pool_conses_tail, Qavailable_phrase_pool_conses_tail);
extern Object Available_phrase_pool_conses_tail_vector;
extern Object Available_phrase_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_sexp_annotation_hash_vector_43_vectors, Qavailable_sexp_annotation_hash_vector_43_vectors);
extern Object Available_sexp_annotation_hash_vector_43_vectors_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
extern Object Bad_phrase;
extern Object Batch_parsing_engaged_p;
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Category_for_category_symbol_count, Qcategory_for_category_symbol_count);
DECLARE_VARIABLE_WITH_SYMBOL(Category_for_token_count, Qcategory_for_token_count);
DECLARE_VARIABLE_WITH_SYMBOL(Category_set_count, Qcategory_set_count);
DECLARE_VARIABLE_WITH_SYMBOL(Category_symbols_for_non_contributing_categories, Qcategory_symbols_for_non_contributing_categories);
extern Object Category_symbols_for_symbol_token_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Category_visit_vector_qm, Qcategory_visit_vector_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_annotations, Qchain_of_available_annotations);
extern Object Chain_of_available_annotations_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_category_for_category_symbols, Qchain_of_available_category_for_category_symbols);
extern Object Chain_of_available_category_for_category_symbols_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_category_for_tokens, Qchain_of_available_category_for_tokens);
extern Object Chain_of_available_category_for_tokens_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_category_sets, Qchain_of_available_category_sets);
extern Object Chain_of_available_category_sets_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_edit_box_changes, Qchain_of_available_edit_box_changes);
extern Object Chain_of_available_edit_box_changes_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_edit_states, Qchain_of_available_edit_states);
extern Object Chain_of_available_edit_states_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gensym_grammars, Qchain_of_available_gensym_grammars);
extern Object Chain_of_available_gensym_grammars_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_incomplete_phrases, Qchain_of_available_incomplete_phrases);
extern Object Chain_of_available_incomplete_phrases_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_phrase_rule_completions, Qchain_of_available_phrase_rule_completions);
extern Object Chain_of_available_phrase_rule_completions_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_strict_subcategory_infos, Qchain_of_available_strict_subcategory_infos);
extern Object Chain_of_available_strict_subcategory_infos_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Collected_menu_content_structure, Qcollected_menu_content_structure);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_sexp_annotation_hash_vector_43_vectors, Qcount_of_sexp_annotation_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_agenda_accumulating, Qcurrent_agenda_accumulating);
DECLARE_VARIABLE_WITH_SYMBOL(Current_category_visit_stamp, Qcurrent_category_visit_stamp);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_state, Qcurrent_edit_state);
DECLARE_VARIABLE_WITH_SYMBOL(Current_edit_workspace, Qcurrent_edit_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Current_grammar, Qcurrent_grammar);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_symbol_token, Qcurrent_indicator_for_category_of_symbol_token);
DECLARE_VARIABLE_WITH_SYMBOL(Current_indicator_for_category_of_this_name, Qcurrent_indicator_for_category_of_this_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_parsing_context_qm, Qcurrent_parsing_context_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_subcategory_path, Qcurrent_subcategory_path);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_transform_constituent_array, Qcurrent_transform_constituent_array);
DECLARE_VARIABLE_WITH_SYMBOL(Current_transform_constituent_count, Qcurrent_transform_constituent_count);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Currently_tracking_subcategory_path_max, Qcurrently_tracking_subcategory_path_max);
extern Object Directory_of_names_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Edit_box_change_count, Qedit_box_change_count);
DECLARE_VARIABLE_WITH_SYMBOL(Edit_state_count, Qedit_state_count);
DECLARE_VARIABLE_WITH_SYMBOL(Editing_context, Qediting_context);
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Generate_source_annotation_info, Qgenerate_source_annotation_info);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_grammar_count, Qgensym_grammar_count);
extern Object Gensym_grammar_prop;
extern Object Global_grammar;
DECLARE_VARIABLE_WITH_SYMBOL(Grammar_cons_counter, Qgrammar_cons_counter);
extern Object Grammar_cons_counter_vector;
extern Object Grammar_transform_can_return_bad_phrase_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Incomplete_phrase_count, Qincomplete_phrase_count);
DECLARE_VARIABLE_WITH_SYMBOL(Incomplete_phrases_at_frontier, Qincomplete_phrases_at_frontier);
extern Object Kb_specific_property_names;
DECLARE_VARIABLE_WITH_SYMBOL(Keep_edit_workspace_hidden_no_matter_what_qm, Qkeep_edit_workspace_hidden_no_matter_what_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Last_assigned_category_index, Qlast_assigned_category_index);
DECLARE_VARIABLE_WITH_SYMBOL(Last_assigned_grammar_number, Qlast_assigned_grammar_number);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_argument_lists_to_add_menu_items_for_category, Qlist_of_argument_lists_to_add_menu_items_for_category);
extern Object List_phrase_noise_symbols;
#define Max_instance_rule_chaining FIX((SI_Long)512L)
#define Maximum_size_of_category_set_as_list FIX((SI_Long)8L)
extern Object Maximum_size_of_token_sequence;
DECLARE_VARIABLE_WITH_SYMBOL(Menu_items_for_parsing, Qmenu_items_for_parsing);
extern Object Menu_too_many_instances;
extern Object Months_of_the_year;
extern Object Most_positive_fixnum_minus_2;
DECLARE_VARIABLE_WITH_SYMBOL(Names_of_grammars_to_add_rules_to, Qnames_of_grammars_to_add_rules_to);
extern Object Omit_from_quoted_token_menus_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(One_sequence_of_following_tokens_only_p, Qone_sequence_of_following_tokens_only_p);
extern Object Overriding_token_instances_without_specific_categories_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Phrase_copying_needs_annotation_rehashing, Qphrase_copying_needs_annotation_rehashing);
extern Object Phrase_item_denotation_marker;
extern Object Phrase_item_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Phrase_pool_cons_counter, Qphrase_pool_cons_counter);
extern Object Phrase_pool_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Phrase_rule_completion_count, Qphrase_rule_completion_count);
extern Object Phrase_sequence_marker;
extern Object Phrase_structure_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Prune_token_categories_visited_more_than_once_p, Qprune_token_categories_visited_more_than_once_p);
extern Object Registered_abstract_integer_category_p_prop;
extern Object Registered_directory_of_names_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Required_token_types, Qrequired_token_types);
extern Object Reserved_word_p_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Semi_open_category_map, Qsemi_open_category_map);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Strict_subcategory_info_count, Qstrict_subcategory_info_count);
DECLARE_VARIABLE_WITH_SYMBOL(Strict_subcategory_info_last_category_1, Qstrict_subcategory_info_last_category_1);
DECLARE_VARIABLE_WITH_SYMBOL(Strict_subcategory_info_last_category_2, Qstrict_subcategory_info_last_category_2);
DECLARE_VARIABLE_WITH_SYMBOL(Strict_subcategory_info_last_result, Qstrict_subcategory_info_last_result);
DECLARE_VARIABLE_WITH_SYMBOL(Strict_subcategory_infos_exist_p, Qstrict_subcategory_infos_exist_p);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_tokens_for_category_symbol_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Symbols_not_to_add_to_semi_open_category_directories, Qsymbols_not_to_add_to_semi_open_category_directories);
DECLARE_VARIABLE_WITH_SYMBOL(The_transform, Qthe_transform);
extern Object The_type_description_of_annotation;
extern Object The_type_description_of_category_for_category_symbol;
extern Object The_type_description_of_category_for_token;
extern Object The_type_description_of_category_set;
extern Object The_type_description_of_edit_box_change;
extern Object The_type_description_of_edit_state;
extern Object The_type_description_of_gensym_grammar;
extern Object The_type_description_of_incomplete_phrase;
extern Object The_type_description_of_phrase_rule_completion;
extern Object The_type_description_of_strict_subcategory_info;
DECLARE_VARIABLE_WITH_SYMBOL(There_is_a_current_kb_qm, Qthere_is_a_current_kb_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Token_sequence_location_plist, Qtoken_sequence_location_plist);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Write_strings_parsably_qm, Qwrite_strings_parsably_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
