/* rules.h -- Header File for rules.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand;
extern Object Qeval;
extern Object Kinitial_element;
extern Object Qnot;
extern Object Qquote;
extern Object Qsequence;
extern Object Qthe;
extern Object Qwhen;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object activate_for_rule(Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_local_names_for_current_reference_info(Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object assq_function(Object,Object);
extern Object atomic_naming_element_of_role(Object);
extern Object backward_chaining_precedence_function(Object);
extern Object bad_status_compiler_frame_notes_qm(int,...);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object change_slot_value(int,...);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object clean_up_ri_completion_notification_collection_back_pointer(Object);
extern Object cleanup_for_rule(Object);
extern Object clear_cached_explanations(Object);
extern Object clear_hashed_rule_instance(Object);
extern Object clear_hashed_rule_instance_tree(Object);
extern Object clear_optimized_constants(void);
extern Object collect_local_name_reference_info(Object);
extern Object compilations_up_to_date_p(Object);
extern Object compile_focal_classes_for_slot(int,...);
extern Object compile_nupec_extra_action_list_for_slot(int,...);
extern Object compile_rule(Object,Object,Object,Object);
extern Object compile_rule_for_slot(int,...);
extern Object compile_rule_for_stack(Object,Object);
extern Object compile_rule_frame_flags_for_slot(int,...);
extern Object copy_for_phrase(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text(Object);
extern Object deactivate_for_rule(Object);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object deinstall_chaining_links(Object);
extern Object delete_dynamic_rule_displays_for_rule_or_object(Object);
extern Object delete_eval_element_1(Object,Object);
extern Object delete_skip_list_entry(Object,Object,Object,Object,Object);
extern Object designation_operator_or_giver_of_value_p(Object);
extern Object dismiss_rule_instance(Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object equal_rule_context(Object,Object);
extern Object equal_scan_intervals(Object,Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object explanation_related_features_enabled_func_qm(void);
extern Object extract_assignments_section_from_for_rule(Object);
extern Object extract_assignments_section_if_any(Object);
extern Object flatten_hashed_rule_instance(Object);
extern Object flatten_skip_list(Object);
extern Object future_task_schedule_2(Object);
extern Object generate_and_schedule_rule_instances(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object generate_forward_and_backward_chaining_links(Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_explicitly_specified_local_name_of_role_if_any(Object);
extern Object get_kb_parent_information(Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_particulars_of_frame_note_from_component_particulars(Object,Object,Object);
extern Object get_rule_local_name_reference_info(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_completion_of_initial_rule(Object);
extern Object handle_rule_category_completion_notification(Object);
extern Object hashed_rule_instance_hash_vector_43_vector_memory_usage(void);
extern Object ignore_role_in_walk_p(Object);
extern Object initialize_after_reading_for_rule(Object);
extern Object initialize_for_rule(Object);
extern Object install_chaining_links(Object);
extern Object intern_text_string(int,...);
extern Object invertible_designation_p(Object);
extern Object invoke_rule_universally(Object);
extern Object lookup_action_template(Object);
extern Object lookup_function_template(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object make_hashed_rule_instance(void);
extern Object make_hashed_rule_instance_hash_vector(void);
extern Object make_hashed_rule_instance_tree_for_hash_skip_list_sentinel(Object,Object);
extern Object make_permanent_hashed_rule_instance_hash_vector_43_vector_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_phrase_list(Object);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_thread_array(Object);
extern Object manually_disable_for_rule(Object);
extern Object manually_enable_for_rule(Object);
extern Object maybe_add_more_local_names(Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_hashed_rule_instance_tree_for_hash_skip_list_entry(Object,Object,Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_frame_with_compilation_removed(Object);
extern Object note_runs_while_inactive_change_for_rule(Object);
extern Object out_hashed_rule_instance_hash_vector_43_vectors(void);
extern Object parse_text_for_slot(int,...);
extern Object phrase_cons(Object,Object);
extern Object phrase_cons_with_args_reversed(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_list_4(Object,Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_nupec_extra_actions(Object,Object,Object);
extern Object put_rule_byte_code_body(Object,Object,Object);
extern Object put_rule_chaining_links(Object,Object,Object);
extern Object put_rule_scan_interval(Object,Object,Object);
extern Object reclaim_environment_vector(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_evaluation_variables_list(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_hashed_rule_instance(Object);
extern Object reclaim_hashed_rule_instance_hash_vector(Object);
extern Object reclaim_rule_context(Object);
extern Object reclaim_rule_instance_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_compiler_error_and_warning_frame_notes(void);
extern Object remove_rule_instance_from_dynamic_rule_displays(Object);
extern Object remove_rule_instance_from_generic_rule_displays(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_stack_change_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object rule_byte_code_body_function(Object);
extern Object rule_chaining_links_function(Object);
extern Object rule_instance_completed(Object,Object);
extern Object rule_translation_keyword(Object);
extern Object scope_cons(Object,Object);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_slot_value_and_update_representations(int,...);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object shutdown_rule_execution_if_appropriate(Object,Object);
extern Object simple_role_of_role(Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object startup_rule_execution_if_appropriate(Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object truth_value_phrase_p(Object);
extern Object twrite_general_string(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p(Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_backward_chaining_displays_function(Object);
extern Object update_frame_name_references(Object);
extern Object update_frame_status(Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_slot_value(int,...);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object wake_up_code_body_invocation(Object);
extern Object walk_action_body_given_template(Object,Object,Object);
extern Object walk_designation(Object,Object);
extern Object walk_expression(Object,Object);
extern Object walk_expression_given_template(Object,Object,Object);
extern Object walk_rule(Object,Object);
extern Object walk_rule_actions(Object,Object);
extern Object walk_rule_without_copying(Object,Object);
extern Object withdraw_backward_chaining(Object);
extern Object write_rule_frame_flags_from_slot(Object,Object);

#else

extern Object activate_for_rule();
extern Object add_class_to_environment();
extern Object add_grammar_rules_function();
extern Object add_local_names_for_current_reference_info();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object assq_function();
extern Object atomic_naming_element_of_role();
extern Object backward_chaining_precedence_function();
extern Object bad_status_compiler_frame_notes_qm();
extern Object bytes_per_typed_simple_array();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object change_slot_value();
extern Object check_if_superior_classes_are_defined();
extern Object clean_up_ri_completion_notification_collection_back_pointer();
extern Object cleanup_for_rule();
extern Object clear_cached_explanations();
extern Object clear_hashed_rule_instance();
extern Object clear_hashed_rule_instance_tree();
extern Object clear_optimized_constants();
extern Object collect_local_name_reference_info();
extern Object compilations_up_to_date_p();
extern Object compile_focal_classes_for_slot();
extern Object compile_nupec_extra_action_list_for_slot();
extern Object compile_rule();
extern Object compile_rule_for_slot();
extern Object compile_rule_for_stack();
extern Object compile_rule_frame_flags_for_slot();
extern Object copy_for_phrase();
extern Object copy_out_current_wide_string();
extern Object copy_text();
extern Object deactivate_for_rule();
extern Object define_type_specification_explicit_complex_type();
extern Object deinstall_chaining_links();
extern Object delete_dynamic_rule_displays_for_rule_or_object();
extern Object delete_eval_element_1();
extern Object delete_skip_list_entry();
extern Object designation_operator_or_giver_of_value_p();
extern Object dismiss_rule_instance();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object equal_rule_context();
extern Object equal_scan_intervals();
extern Object estructure_slot();
extern Object eval_cons_1();
extern Object explanation_related_features_enabled_func_qm();
extern Object extract_assignments_section_from_for_rule();
extern Object extract_assignments_section_if_any();
extern Object flatten_hashed_rule_instance();
extern Object flatten_skip_list();
extern Object future_task_schedule_2();
extern Object generate_and_schedule_rule_instances();
extern Object generate_forward_and_backward_chaining_links();
extern Object gensym_cons_1();
extern Object get_explicitly_specified_local_name_of_role_if_any();
extern Object get_kb_parent_information();
extern Object get_lookup_slot_value_given_default();
extern Object get_particulars_of_frame_note_from_component_particulars();
extern Object get_rule_local_name_reference_info();
extern Object get_slot_description_of_class_description_function();
extern Object get_symbol_properties_function();
extern Object getfq_function_no_default();
extern Object handle_completion_of_initial_rule();
extern Object handle_rule_category_completion_notification();
extern Object hashed_rule_instance_hash_vector_43_vector_memory_usage();
extern Object ignore_role_in_walk_p();
extern Object initialize_after_reading_for_rule();
extern Object initialize_for_rule();
extern Object install_chaining_links();
extern Object intern_text_string();
extern Object invertible_designation_p();
extern Object invoke_rule_universally();
extern Object lookup_action_template();
extern Object lookup_function_template();
extern Object lookup_global_or_kb_specific_property_value();
extern Object make_hashed_rule_instance();
extern Object make_hashed_rule_instance_hash_vector();
extern Object make_hashed_rule_instance_tree_for_hash_skip_list_sentinel();
extern Object make_permanent_hashed_rule_instance_hash_vector_43_vector_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_phrase_list();
extern Object make_skip_list_element_1();
extern Object make_thread_array();
extern Object manually_disable_for_rule();
extern Object manually_enable_for_rule();
extern Object maybe_add_more_local_names();
extern Object memq_function();
extern Object mutate_global_property();
extern Object mutate_hashed_rule_instance_tree_for_hash_skip_list_entry();
extern Object note_change_to_block_1();
extern Object note_frame_with_compilation_removed();
extern Object note_runs_while_inactive_change_for_rule();
extern Object out_hashed_rule_instance_hash_vector_43_vectors();
extern Object parse_text_for_slot();
extern Object phrase_cons();
extern Object phrase_cons_with_args_reversed();
extern Object phrase_list_2();
extern Object phrase_list_4();
extern Object push_optimized_constant();
extern Object put_nupec_extra_actions();
extern Object put_rule_byte_code_body();
extern Object put_rule_chaining_links();
extern Object put_rule_scan_interval();
extern Object reclaim_environment_vector();
extern Object reclaim_eval_list_1();
extern Object reclaim_evaluation_variables_list();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_hashed_rule_instance();
extern Object reclaim_hashed_rule_instance_hash_vector();
extern Object reclaim_rule_context();
extern Object reclaim_rule_instance_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value();
extern Object reclaim_stack_change_tree_1();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object remove_compiler_error_and_warning_frame_notes();
extern Object remove_rule_instance_from_dynamic_rule_displays();
extern Object remove_rule_instance_from_generic_rule_displays();
extern Object replenish_lookup_cons_pool();
extern Object replenish_stack_change_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object rule_byte_code_body_function();
extern Object rule_chaining_links_function();
extern Object rule_instance_completed();
extern Object rule_translation_keyword();
extern Object scope_cons();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_lookup_slot_value_1();
extern Object set_property_value_function();
extern Object set_slot_value_and_update_representations();
extern Object set_slot_value_to_evaluation_value_function();
extern Object shutdown_rule_execution_if_appropriate();
extern Object simple_role_of_role();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object startup_rule_execution_if_appropriate();
extern Object tformat();
extern Object tformat_text_string();
extern Object truth_value_phrase_p();
extern Object twrite_general_string();
extern Object type_error_in_setter();
extern Object type_specification_type_p();
extern Object type_specification_type_p__with_explanation();
extern Object update_all_representations_of_slot();
extern Object update_backward_chaining_displays_function();
extern Object update_frame_name_references();
extern Object update_frame_status();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_slot_value();
extern Object validate_item_or_evaluation_value();
extern Object wake_up_code_body_invocation();
extern Object walk_action_body_given_template();
extern Object walk_designation();
extern Object walk_expression();
extern Object walk_expression_given_template();
extern Object walk_rule();
extern Object walk_rule_actions();
extern Object walk_rule_without_copying();
extern Object withdraw_backward_chaining();
extern Object write_rule_frame_flags_from_slot();

#endif

/* variables/constants */
extern Object Available_eval_conses_tail_vector;
extern Object Available_eval_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_hashed_rule_instance_hash_vector_43_vectors, Qavailable_hashed_rule_instance_hash_vector_43_vectors);
extern Object Available_hashed_rule_instance_hash_vector_43_vectors_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backward_chaining_displays, Qbackward_chaining_displays);
DECLARE_VARIABLE_WITH_SYMBOL(Backward_chaining_link_class_description, Qbackward_chaining_link_class_description);
extern Object Bad_phrase;
extern Object Cache_data_for_explanation_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Cache_nupec_semantics_graph, Qcache_nupec_semantics_graph);
extern Object Chain_of_available_schedule_tasks_vector;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Compiler_errors, Qcompiler_errors);
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_hashed_rule_instance_hash_vector_43_vectors, Qcount_of_hashed_rule_instance_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_rule_local_name_reference_info, Qcurrent_rule_local_name_reference_info);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Defined_evaluation_value_types, Qdefined_evaluation_value_types);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Forward_chaining_link_class_description, Qforward_chaining_link_class_description);
extern Object Fp_mutate_hashed_rule_instance_tree_for_hash_skip_list_entry;
DECLARE_VARIABLE_WITH_SYMBOL(In_suspend_resume_p, Qin_suspend_resume_p);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
extern Object Invocable_via_backward_chaining_flag;
extern Object Invocable_via_forward_chaining_flag;
DECLARE_VARIABLE_WITH_SYMBOL(Journal_shutout_scan_p, Qjournal_shutout_scan_p);
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object May_cause_data_seeking_flag;
extern Object May_cause_forward_chaining_flag;
DECLARE_VARIABLE_WITH_SYMBOL(New_saved_kb_format_p, Qnew_saved_kb_format_p);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Phrase_sequence_marker;
extern Object Phrase_structure_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_local_name_references, Qrule_local_name_references);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Within_activate_for_kb_workspace, Qwithin_activate_for_kb_workspace);
