/* run.h -- Header File for run.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kabort;
extern Object Qand;
extern Object Qblock;
extern Object Qcar;
extern Object Qeq;
extern Object Qerror;
extern Object Kname;
extern Object Qprint;
extern Object Qquote;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object abort_g2(int,...);
extern Object add_alias_to_configuration(Object,Object,Object,Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_keymap_to_workstation_context(Object,Object);
extern Object add_new_user_encoding_as_needed(Object,Object,Object,Object);
extern Object add_or_delete_mode_name_from_directory_of_names(Object,Object);
extern Object add_subblock(Object,Object);
extern Object add_to_workspace(int,...);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object assemble_uncached_compound_method_flags(Object,Object,Object,Object);
extern Object assign_class_bit_numbers_and_vectors_to_system_classes(void);
extern Object assq_function(Object,Object);
extern Object augment_window_parameters_plist_of_initial_gensym_window(Object);
extern Object authorize_ab(void);
extern Object block_near_mouse_cache_structure_memory_usage(void);
extern Object break_out_of_debug_messages(void);
extern Object bytes_per_simple_vector(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object c_spawn_executable_process(Object);
extern Object c_update_system_tray(Object,Object,Object);
extern Object cache_block_near_mouse(Object,Object,Object,Object);
extern Object cached_block_near_mouse(Object,Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_native_debugger_dialog(Object);
extern Object cancel_native_login_dialog(Object);
extern Object change_edges_of_block(Object,Object,Object,Object,Object);
extern Object change_mode(void);
extern Object change_slot_value(int,...);
extern Object change_user_password_if_appropriate(Object,Object,Object,Object,Object,Object);
extern Object change_users_password_decay_date(Object,Object);
extern Object char_lesspw_function(Object,Object);
extern Object check_alias_for_possible_name(Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object choose_font_format_per_fonts_table(Object,Object);
extern Object clear_cached_block_near_mouse(Object);
extern Object clear_optimized_constants(void);
extern Object close_telewindows_connection(Object);
extern Object collect_subclasses(Object);
extern Object command_permitted_p(Object,Object);
extern Object compare_aliases(Object,Object);
extern Object compare_aliases_restrictions(Object,Object,Object);
extern Object compile_name_qm_for_slot(int,...);
extern Object computation_frame_at_breakpoint_depends_on_block_p(Object);
extern Object compute_category_members(Object);
extern Object compute_minimum_bottom_edge_for_icon_cell(Object);
extern Object compute_minimum_right_edge_for_icon_cell(Object);
extern Object confirm_or_cancel(int,...);
extern Object connection_connected_to_block_p(Object,Object);
extern Object constant_queue_next(Object,Object);
extern Object constant_queue_push_right(Object,Object);
extern Object convert_text_string_to_text(Object);
extern Object convert_text_to_text_string(int,...);
extern Object copy_as_wide_string(Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_for_slot_value(Object);
extern Object copy_foreign_string_arg_if_appropriate(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_gensym_pathname(Object);
extern Object copy_gensym_window_attributes_into_g2_window(Object);
extern Object copy_managed_float(Object);
extern Object copy_of_current_frame_serial_number_function(void);
extern Object copy_out_current_wide_string(void);
extern Object copy_symbol_name(int,...);
extern Object copy_text_string(Object);
extern Object copy_text_string_with_case_conversion(Object,Object);
extern Object copy_wide_string(Object);
extern Object create_blob_edit_box_format(void);
extern Object create_gensym_logo_description(Object);
extern Object current_g2_run_state(void);
extern Object debugger_disable_debugging(void);
extern Object debugger_get_breakpoints(Object);
extern Object debugger_pause(Object);
extern Object decache_dynamic_menus(int,...);
extern Object decode_image_plane_shift_action(Object,Object);
extern Object delete_alias_from_configuration(Object,Object,Object);
extern Object delete_all_title_block_workspaces(void);
extern Object delete_existed_alias(Object);
extern Object delete_frame(Object);
extern Object delete_user(Object);
extern Object describe_keymap(Object,Object);
extern Object describe_keymap_into_table_rows(Object,Object);
extern Object describe_workstation_context_keymaps(Object,Object);
extern Object describe_workstation_context_stack(Object);
extern Object detail_pane(Object);
extern Object direct_structure_method(Object,Object);
extern Object display_credits(int,...);
extern Object do_end_button_for_g2_login(void);
extern Object do_g2_login_button(Object);
extern Object do_g2_login_subcommand(Object);
extern Object do_plist_checking(void);
extern Object do_plist_checking_again(void);
extern Object draw_for_icon_cell(Object);
extern Object dynamic_breakpoint_enabled_p(Object);
extern Object dynamic_breakpoint_line_func(Object);
extern Object edges_of_block_content_plus_frame(Object);
extern Object embedded_image_plane_p(Object);
extern Object enable_or_disable_subcommand(int,...);
extern Object encode_and_check_password_change_information(int,...);
extern Object encode_password_via_md5(Object,Object,Object);
extern Object enter_authorized_user(Object,Object,Object,Object,Object);
extern Object enter_change_password_dialog(void);
extern Object enter_change_user_mode_in_running(Object,Object);
extern Object enter_context_in_current_workstation(int,...);
extern Object enter_dialog(int,...);
extern Object enter_dialog_for_pause_for_internal_error_or_debug(Object,Object);
extern Object enter_dialog_for_t2(int,...);
extern Object enter_editing_context(int,...);
extern Object enter_keys_in_g2_login_state(Object);
extern Object enter_subcommand_context(Object);
extern Object enter_user_settings_editor(Object);
extern Object enter_user_settings_editor_1(int,...);
extern Object establish_next_workstation_context_continuation(Object,Object,Object,Object);
extern Object eval_cons_1(Object,Object);
extern Object eval_list_2(Object,Object);
extern Object eval_list_3(Object,Object,Object);
extern Object event_handler_pretty_name(Object);
extern Object execute_breakpoint_button(Object);
extern Object execute_user_menu_choice_if_possible(Object,Object);
extern Object exhibit_chestnut_catch_reverts_locals_bug(void);
extern Object exhibit_chestnut_unwind_protect_reverts_locals_bug(void);
extern Object existence_depends_on_p(Object,Object);
extern Object extend_current_gensym_string(int,...);
extern Object find_base_plane_in_stack_of_coupled_image_planes(Object);
extern Object find_block_near_mouse_on_workspace(Object,Object,Object);
extern Object find_menu_for_spot(Object);
extern Object find_menu_item(Object,Object,Object,Object);
extern Object find_object_near_mouse(Object,Object,Object,Object,Object);
extern Object find_object_near_mouse_1(Object,Object,Object);
extern Object find_object_near_workstation_event(int,...);
extern Object find_position_in_text(int,...);
extern Object find_ui_command(int,...);
extern Object find_ultimate_superplane_in_stack_of_coupled_image_planes(Object);
extern Object find_vector_length_from_point_to_block_connections_if_within_limit(Object,Object,Object,Object,Object);
extern Object find_workstation_context(int,...);
extern Object finish_dialog_for_pause_for_internal_error_or_debug(Object,Object);
extern Object finish_g2_login(Object,Object,Object);
extern Object first_subblock(Object);
extern Object fixnum_time_interval(Object);
extern Object force_process_drawing(void);
extern Object frame_serial_number_0(void);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object future_task_schedule_2(Object);
extern Object g2_add_alias(Object,Object);
extern Object g2_alias_prompt_message(void);
extern Object g2_delete_alias(Object);
extern Object g2_event_loop(void);
extern Object g2_login_prompt_message(void);
extern Object g2_login_state_structure_memory_usage(void);
extern Object g2_ok_file_probe(void);
extern Object g2_password_change_prompt_message(void);
extern Object g2_reinstall_authorized_users(void);
extern Object g2_set_maximum_login_attempts(Object);
extern Object g2passwd_probe_file(void);
extern Object generate_output_only_table_spot(Object,Object,Object);
extern Object generate_spot_for_selection_handle(Object,Object);
extern Object generate_spot_for_workspace(Object,Object);
extern Object generate_spot_from_frame_if_approprate(Object,Object);
extern Object generate_spot_if_in_workspace_frame(Object,Object);
extern Object generic_name_of_exported_ui_command_qm(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_4(Object,Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_probe_file_for_write(Object);
extern Object get_block_at_other_end_of_connection(Object,Object);
extern Object get_block_layer_position(Object);
extern Object get_command_line_arguments(void);
extern Object get_command_line_flag_argument(int,...);
extern Object get_command_line_keyword_argument(int,...);
extern Object get_connection_layer_position(Object);
extern Object get_decoded_real_time(void);
extern Object get_default_image_x_scale(Object);
extern Object get_default_image_y_scale(Object);
extern Object get_dynamic_breakpoints_internal(int,...);
extern Object get_gensym_environment_variable(Object);
extern Object get_gensym_logo_style(void);
extern Object get_gensym_window_parameter(Object,Object);
extern Object get_instance_with_name_if_any(Object,Object);
extern Object get_language_for_current_workstation_if_any(void);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_connection_frame_and_activate_if_appropriate(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_represented_by_text_cell_if_any(Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object get_ui_parameter(int,...);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object getfq_function_no_default(Object,Object);
extern Object graph_detailed_procedures(int,...);
extern Object handle_image_plane_event(Object,Object,Object,Object);
extern Object handle_image_plane_event_inner(Object,Object,Object,Object,Object);
extern Object handle_shift_image_plane_action(Object,Object,Object);
extern Object has_only_one_subblock_p(Object);
extern Object image_plane_blackboard_function(Object);
extern Object image_plane_fixed_in_place_p(Object);
extern Object image_plane_has_title_block_p(Object);
extern Object immediately_return_from_breakpoint(Object);
extern Object initialize_gensym_time(void);
extern Object initialize_optional_modules(void);
extern Object initialize_scheduler(void);
extern Object intern_text_string(int,...);
extern Object internal_error_given_format_info(Object,Object,Object);
extern Object invalid_user_name_p(Object);
extern Object inverse_scalef_function(Object,Object);
extern Object invisible_optional_module_p(Object);
extern Object is_alias_present(Object);
extern Object is_in_ldap_mode_p(void);
extern Object is_user_mode_present(Object);
extern Object keymap_enabled_p(Object);
extern Object keymap_private_p(Object);
extern Object launch_ab(void);
extern Object launch_system_process(Object);
extern Object lay_out_window(Object);
extern Object leave_dialog_for_pause_for_internal_error_or_debug(Object);
extern Object leave_dialog_for_t2(Object);
extern Object list_callers_of_computation_instance(Object);
extern Object list_loaded_user_visible_modules(void);
extern Object load_and_initialize_type_description(Object,Object);
extern Object log_in_workstation(int,...);
extern Object log_out_workstation(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lookup_key_in_context(Object,Object,Object);
extern Object make_alias_creation_attribute_table(Object);
extern Object make_attributes_table(int,...);
extern Object make_block_near_mouse_cache_internal_1(void);
extern Object make_context_description(Object,Object,Object,Object);
extern Object make_credits_table_spot_1(void);
extern Object make_diacritic_header_table_row(void);
extern Object make_diacritic_help_table_rows(void);
extern Object make_diacritic_table_row(Object,Object);
extern Object make_empty_text(void);
extern Object make_entity(int,...);
extern Object make_eval_list_1(Object);
extern Object make_format_frame(Object);
extern Object make_frame(Object);
extern Object make_g2_login_attributes_table(Object);
extern Object make_g2_login_state_1(Object,Object,Object,Object,Object);
extern Object make_help_workspace(Object);
extern Object make_hex_code_help_table_rows(Object);
extern Object make_icon_cell(Object,Object,Object,Object,Object);
extern Object make_icon_cell_for_entity(Object,Object,Object,Object,Object);
extern Object make_initial_partial_command(Object,Object);
extern Object make_keymap(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_lost_spaces_text_element(Object);
extern Object make_message(int,...);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_new_alias(Object);
extern Object make_or_reformat_table(int,...);
extern Object make_output_only_table_spot_1(void);
extern Object make_password_change_attributes_table(Object);
extern Object make_permanent_block_near_mouse_cache_structure_internal(void);
extern Object make_permanent_g2_login_state_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_user_mode_alias_structure_internal(void);
extern Object make_short_representation(int,...);
extern Object make_special_character_help_table(void);
extern Object make_standalone_header_table_row(void);
extern Object make_standalone_special_character_help_table_rows(void);
extern Object make_standalone_special_character_row_if_necessary(Object);
extern Object make_standalone_special_character_rows(void);
extern Object make_subcommand_menu(int,...);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_text_cell(int,...);
extern Object make_text_for_diacritic_table_row_with_presentations(Object);
extern Object make_text_for_diacritic_table_row_with_type_ins(Object);
extern Object make_text_for_gensym_g2(void);
extern Object make_text_for_local_identification(void);
extern Object make_text_for_product_and_options(void);
extern Object make_text_for_special_character_type_ins(Object);
extern Object make_text_for_type_of_g2_license(void);
extern Object make_thread_array(Object);
extern Object make_timestamp_list_1(Object);
extern Object make_user_mode_alias_1(void);
extern Object make_user_settings_editor_state(int,...);
extern Object make_window_visible(Object);
extern Object make_workspace(int,...);
extern Object make_workspace_background_spot_1(void);
extern Object manage_debugger_dialog(int,...);
extern Object map_to_color_value_1(Object);
extern Object maybe_schedule_service_workstations(Object);
extern Object memq_function(Object,Object);
extern Object most_interesting_frame(Object);
extern Object mouse_down_on_attribute_value_in_g2_login_state(Object);
extern Object mouse_down_on_otherwise_in_g2_login_state(Object);
extern Object mouse_down_on_subcommand_menu_button_in_g2_login_state(Object);
extern Object mouse_leeway_in_workspace(Object);
extern Object mouse_pointer_blackboard_function(Object);
extern Object move_image_plane(Object,Object,Object);
extern Object mutate_gensym_plist(Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object name_of_exported_event_handler_qm(Object);
extern Object name_of_user_menu_choice_qm(Object,Object);
extern Object native_debugger_dialog_p(Object);
extern Object native_login_dialog_p(Object);
extern Object native_menu_bar_really_needs_updating_p(Object);
extern Object no_local_window_p(void);
extern Object non_menu_choice_permitted_p(Object,Object);
extern Object noop_cleanup_form(void);
extern Object note_change_to_block_1(Object,Object);
extern Object nothing(Object);
extern Object notice_tw_disconnect(Object,Object,Object);
extern Object notify_user(int,...);
extern Object notify_user_at_console(int,...);
extern Object notify_user_at_console_and_on_logbook(int,...);
extern Object offer_g2_user_settings_back_to_telewindows(Object,Object);
extern Object outstanding_block_near_mouse_cache_count(void);
extern Object outstanding_g2_login_state_count(void);
extern Object outstanding_user_mode_alias_count(void);
extern Object pass_command_to_g2passwd(Object,Object);
extern Object pause_during_debug(Object);
extern Object pause_for_internal_error(Object);
extern Object pause_for_internal_error_or_debug(Object,Object);
extern Object permit_generic_ui_command_p(Object);
extern Object pick_cell_from_table(int,...);
extern Object poll_workstation(void);
extern Object post_classic_debugger_dialog(Object);
extern Object post_native_debugger_dialog(Object,Object,Object);
extern Object post_native_login_dialog(int,...);
extern Object post_setjmp_status(void);
extern Object post_workspace_in_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object print_decoded_time(Object,Object,Object,Object,Object,Object);
extern Object print_means_print_to_server_in_configurations_p(void);
extern Object procedure_definition_function(Object);
extern Object pursue_partial_command(int,...);
extern Object push_item_to_end_of_current_localization_domains(Object);
extern Object push_last_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_up_aliases_table(Object);
extern Object put_up_long_operation_notification_now(void);
extern Object put_up_special_character_help_workspace(void);
extern Object put_workspace_on_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object quick_clipping_check_of_block_for_picking(Object);
extern Object raise_image_plane_to_top(int,...);
extern Object raw_stack_error_1(Object,Object,Object);
extern Object read_element_for_kb(Object);
extern Object read_ok_file_again(void);
extern Object read_ok_file_just_for_updating_user_data(Object);
extern Object read_user_mode_alias_for_kb(void);
extern Object reclaim_block_near_mouse_cache_1(Object);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_eval_tree_1(Object);
extern Object reclaim_event_interpretation(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_g2_login_state_1(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_halt_info(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_menu_item(Object);
extern Object reclaim_menu_items(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_slot_value_cons_1(Object);
extern Object reclaim_slot_value_list_1(Object);
extern Object reclaim_status_table_frame_serial_number_value(Object,Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_timestamp_cons_1(Object);
extern Object reclaim_timestamp_list_1(Object);
extern Object reclaim_user_mode_alias_1(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reference_mouse_pointer(Object);
extern Object regenerate_optimized_constant(Object);
extern Object register_all_signal_handlers(void);
extern Object register_button_label_for_internationalization(Object);
extern Object reinstall_authorized_users(void);
extern Object release_mouse_pointer_if_any(Object);
extern Object release_mouse_pointers(Object);
extern Object remove_authorized_user(Object);
extern Object remove_character_from_wide_string(Object,Object);
extern Object remove_dialog_info_from_ui_client_interface_dialog_list(Object,Object);
extern Object remove_last_item_in_current_localization_domains(void);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_slot_value_cons_pool(void);
extern Object report_listener_info_to_parent_window(void);
extern Object require_that_image_plane_be_visible(int,...);
extern Object resize_for_icon_cell(Object,Object,Object,Object);
extern Object return_from_breakpoint(int,...);
extern Object return_from_current_workstation_context(int,...);
extern Object return_from_g2_set_g2_state(Object);
extern Object run_ab(Object);
extern Object run_ab_process_top_level(Object);
extern Object run_event_handler(Object,Object);
extern Object run_scheduler_for_breakpoint(void);
extern Object run_system_process(Object,Object,Object);
extern Object run_top_level_event_handler(Object);
extern Object running_as_noninteractive_service_p(void);
extern Object save_new_user_password_in_g2_ok_file(Object,Object,Object,Object);
extern Object saving_new_password_format_control_string(void);
extern Object scalef_function(Object,Object);
extern Object schedule_g2_legacy_heartbeat_tasks_if_necessary(void);
extern Object selection_handles_visible_p(Object,Object);
extern Object sentence_end_punctuation_qm(Object);
extern Object set_cursor_position(Object,Object);
extern Object set_flag_permitting_free_floating_authorization(void);
extern Object set_frame_style_of_block(Object,Object);
extern Object set_icp_tracing_level_from_command_line(void);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_session_info_in_g2_login(Object,Object);
extern Object set_session_info_in_g2_window(Object,Object);
extern Object set_session_info_in_workstation(Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_value_function(Object,Object,Object,Object);
extern Object set_up_workstation(Object);
extern Object set_validity_of_user_password(Object,Object);
extern Object shift_block(Object,Object,Object);
extern Object shut_down_ab_process(int,...);
extern Object shutdown_or_exit(int,...);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object slot_value_list_4(Object,Object,Object,Object);
extern Object sort_list(Object,Object,Object);
extern Object specific_menu_item_for_generic_command_qm(Object,Object);
extern Object spot_generator_for_credits_table_format(Object,Object);
extern Object spot_generator_for_help_table_format(Object,Object);
extern Object start_generic_command(Object,Object);
extern Object start_scheduler_workers(void);
extern Object start_ui_command(int,...);
extern Object string_equalw(Object,Object);
extern Object string_for_localized_symbol(Object);
extern Object stringw(Object);
extern Object subplane_qm(Object);
extern Object switch_to_new_empty_kb(void);
extern Object symbol_namew(Object);
extern Object system_pause(int,...);
extern Object system_resume(void);
extern Object table_visible_in_image_plane_p(Object,Object,Object);
extern Object table_visible_near_mouse_p(Object);
extern Object test_restrictions_for_image_plane_action(Object,Object);
extern Object text_box_visible_near_mouse_p(Object);
extern Object text_box_visible_p(Object,Object,Object);
extern Object text_cell_of_table_blackboard_function(Object);
extern Object text_string_length(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object thing_selected_p(Object,Object);
extern Object throw_to_chestnut_catcher(void);
extern Object timestamp_cons_1(Object,Object);
extern Object title_block_table_p(Object);
extern Object title_block_workspace_p(Object);
extern Object too_many_login_attempts_from_this_source(Object);
extern Object track_mouse_over_frame(Object,Object,Object,Object,Object,Object,Object);
extern Object transform_image(int,...);
extern Object transform_subplanes_per_lead_plane(Object,Object,Object,Object,Object,Object);
extern Object translated_string_for_symbol(int,...);
extern Object translation_for_symbol_qm(int,...);
extern Object trigger_user_icon_movement_rules_for_blocks(Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_current_real_time(void);
extern Object twrite_general_string(Object);
extern Object twrite_help_table_character(Object);
extern Object twrite_key_patterns_and_classes(Object);
extern Object twrite_login_failure_translation_symbol(Object);
extern Object twrite_standard_secure_g2_notification_header(void);
extern Object twrite_system_version_in_g2_title(int,...);
extern Object twrite_unix_time(int,...);
extern Object twrite_wide_character(Object);
extern Object type_of_slot_if_editable(int,...);
extern Object ui_command_name_for_describe_keymap(Object);
extern Object unicode_lowercase_if_uppercase(Object);
extern Object update_ab_side_tw_user_mode(Object,Object,Object);
extern Object update_native_menu_bar(Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_system_tray_icon(void);
extern Object update_user_mode_state(Object,Object);
extern Object user_mode_alias_structure_memory_usage(void);
extern Object valid_password_characters_p(Object);
extern Object validate_as_possible_user_mode(Object);
extern Object validate_executing_statements_and_procedures(void);
extern Object verify_chestnut_catch_reverts_locals_fix(void);
extern Object verify_chestnut_unwind_protect_reverts_locals_fix(void);
extern Object warn_user_of_previously_aborted_g2(void);
extern Object workstation_context_specifics_blackboard_function(Object);
extern Object write_char_for_kb(Object);
extern Object write_element_for_kb(Object);
extern Object write_g2_login_comments_from_slot(Object,Object);
extern Object write_local_identification_info_text_string(void);
extern Object write_symbol_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object write_user_mode_alias_for_kb(Object);
extern Object x_in_window_blackboard_function(Object);
extern Object x_in_workspace_blackboard_function(Object);
extern Object y_in_window_blackboard_function(Object);
extern Object y_in_workspace_blackboard_function(Object);

#else

extern Object abort_current_workstation_context();
extern Object abort_g2();
extern Object add_alias_to_configuration();
extern Object add_class_to_environment();
extern Object add_grammar_rules_function();
extern Object add_keymap_to_workstation_context();
extern Object add_new_user_encoding_as_needed();
extern Object add_or_delete_mode_name_from_directory_of_names();
extern Object add_subblock();
extern Object add_to_workspace();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object assemble_uncached_compound_method_flags();
extern Object assign_class_bit_numbers_and_vectors_to_system_classes();
extern Object assq_function();
extern Object augment_window_parameters_plist_of_initial_gensym_window();
extern Object authorize_ab();
extern Object block_near_mouse_cache_structure_memory_usage();
extern Object break_out_of_debug_messages();
extern Object bytes_per_simple_vector();
extern Object c_native_clock_ticks_or_cache();
extern Object c_spawn_executable_process();
extern Object c_update_system_tray();
extern Object cache_block_near_mouse();
extern Object cached_block_near_mouse();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_native_debugger_dialog();
extern Object cancel_native_login_dialog();
extern Object change_edges_of_block();
extern Object change_mode();
extern Object change_slot_value();
extern Object change_user_password_if_appropriate();
extern Object change_users_password_decay_date();
extern Object char_lesspw_function();
extern Object check_alias_for_possible_name();
extern Object check_if_superior_classes_are_defined();
extern Object choose_font_format_per_fonts_table();
extern Object clear_cached_block_near_mouse();
extern Object clear_optimized_constants();
extern Object close_telewindows_connection();
extern Object collect_subclasses();
extern Object command_permitted_p();
extern Object compare_aliases();
extern Object compare_aliases_restrictions();
extern Object compile_name_qm_for_slot();
extern Object computation_frame_at_breakpoint_depends_on_block_p();
extern Object compute_category_members();
extern Object compute_minimum_bottom_edge_for_icon_cell();
extern Object compute_minimum_right_edge_for_icon_cell();
extern Object confirm_or_cancel();
extern Object connection_connected_to_block_p();
extern Object constant_queue_next();
extern Object constant_queue_push_right();
extern Object convert_text_string_to_text();
extern Object convert_text_to_text_string();
extern Object copy_as_wide_string();
extern Object copy_constant_wide_string_given_length();
extern Object copy_for_slot_value();
extern Object copy_foreign_string_arg_if_appropriate();
extern Object copy_frame_serial_number();
extern Object copy_gensym_pathname();
extern Object copy_gensym_window_attributes_into_g2_window();
extern Object copy_managed_float();
extern Object copy_of_current_frame_serial_number_function();
extern Object copy_out_current_wide_string();
extern Object copy_symbol_name();
extern Object copy_text_string();
extern Object copy_text_string_with_case_conversion();
extern Object copy_wide_string();
extern Object create_blob_edit_box_format();
extern Object create_gensym_logo_description();
extern Object current_g2_run_state();
extern Object debugger_disable_debugging();
extern Object debugger_get_breakpoints();
extern Object debugger_pause();
extern Object decache_dynamic_menus();
extern Object decode_image_plane_shift_action();
extern Object delete_alias_from_configuration();
extern Object delete_all_title_block_workspaces();
extern Object delete_existed_alias();
extern Object delete_frame();
extern Object delete_user();
extern Object describe_keymap();
extern Object describe_keymap_into_table_rows();
extern Object describe_workstation_context_keymaps();
extern Object describe_workstation_context_stack();
extern Object detail_pane();
extern Object direct_structure_method();
extern Object display_credits();
extern Object do_end_button_for_g2_login();
extern Object do_g2_login_button();
extern Object do_g2_login_subcommand();
extern Object do_plist_checking();
extern Object do_plist_checking_again();
extern Object draw_for_icon_cell();
extern Object dynamic_breakpoint_enabled_p();
extern Object dynamic_breakpoint_line_func();
extern Object edges_of_block_content_plus_frame();
extern Object embedded_image_plane_p();
extern Object enable_or_disable_subcommand();
extern Object encode_and_check_password_change_information();
extern Object encode_password_via_md5();
extern Object enter_authorized_user();
extern Object enter_change_password_dialog();
extern Object enter_change_user_mode_in_running();
extern Object enter_context_in_current_workstation();
extern Object enter_dialog();
extern Object enter_dialog_for_pause_for_internal_error_or_debug();
extern Object enter_dialog_for_t2();
extern Object enter_editing_context();
extern Object enter_keys_in_g2_login_state();
extern Object enter_subcommand_context();
extern Object enter_user_settings_editor();
extern Object enter_user_settings_editor_1();
extern Object establish_next_workstation_context_continuation();
extern Object eval_cons_1();
extern Object eval_list_2();
extern Object eval_list_3();
extern Object event_handler_pretty_name();
extern Object execute_breakpoint_button();
extern Object execute_user_menu_choice_if_possible();
extern Object exhibit_chestnut_catch_reverts_locals_bug();
extern Object exhibit_chestnut_unwind_protect_reverts_locals_bug();
extern Object existence_depends_on_p();
extern Object extend_current_gensym_string();
extern Object find_base_plane_in_stack_of_coupled_image_planes();
extern Object find_block_near_mouse_on_workspace();
extern Object find_menu_for_spot();
extern Object find_menu_item();
extern Object find_object_near_mouse();
extern Object find_object_near_mouse_1();
extern Object find_object_near_workstation_event();
extern Object find_position_in_text();
extern Object find_ui_command();
extern Object find_ultimate_superplane_in_stack_of_coupled_image_planes();
extern Object find_vector_length_from_point_to_block_connections_if_within_limit();
extern Object find_workstation_context();
extern Object finish_dialog_for_pause_for_internal_error_or_debug();
extern Object finish_g2_login();
extern Object first_subblock();
extern Object fixnum_time_interval();
extern Object force_process_drawing();
extern Object frame_serial_number_0();
extern Object frame_serial_number_setf_helper_1();
extern Object future_task_schedule_2();
extern Object g2_add_alias();
extern Object g2_alias_prompt_message();
extern Object g2_delete_alias();
extern Object g2_event_loop();
extern Object g2_login_prompt_message();
extern Object g2_login_state_structure_memory_usage();
extern Object g2_ok_file_probe();
extern Object g2_password_change_prompt_message();
extern Object g2_reinstall_authorized_users();
extern Object g2_set_maximum_login_attempts();
extern Object g2passwd_probe_file();
extern Object generate_output_only_table_spot();
extern Object generate_spot_for_selection_handle();
extern Object generate_spot_for_workspace();
extern Object generate_spot_from_frame_if_approprate();
extern Object generate_spot_if_in_workspace_frame();
extern Object generic_name_of_exported_ui_command_qm();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_list_4();
extern Object gensym_namestring();
extern Object gensym_probe_file_for_write();
extern Object get_block_at_other_end_of_connection();
extern Object get_block_layer_position();
extern Object get_command_line_arguments();
extern Object get_command_line_flag_argument();
extern Object get_command_line_keyword_argument();
extern Object get_connection_layer_position();
extern Object get_decoded_real_time();
extern Object get_default_image_x_scale();
extern Object get_default_image_y_scale();
extern Object get_dynamic_breakpoints_internal();
extern Object get_gensym_environment_variable();
extern Object get_gensym_logo_style();
extern Object get_gensym_window_parameter();
extern Object get_instance_with_name_if_any();
extern Object get_language_for_current_workstation_if_any();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_connection_frame_and_activate_if_appropriate();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_represented_by_text_cell_if_any();
extern Object get_slot_value_function();
extern Object get_slot_value_if_any_function();
extern Object get_ui_parameter();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object getfq_function_no_default();
extern Object graph_detailed_procedures();
extern Object handle_image_plane_event();
extern Object handle_image_plane_event_inner();
extern Object handle_shift_image_plane_action();
extern Object has_only_one_subblock_p();
extern Object image_plane_blackboard_function();
extern Object image_plane_fixed_in_place_p();
extern Object image_plane_has_title_block_p();
extern Object immediately_return_from_breakpoint();
extern Object initialize_gensym_time();
extern Object initialize_optional_modules();
extern Object initialize_scheduler();
extern Object intern_text_string();
extern Object internal_error_given_format_info();
extern Object invalid_user_name_p();
extern Object inverse_scalef_function();
extern Object invisible_optional_module_p();
extern Object is_alias_present();
extern Object is_in_ldap_mode_p();
extern Object is_user_mode_present();
extern Object keymap_enabled_p();
extern Object keymap_private_p();
extern Object launch_ab();
extern Object launch_system_process();
extern Object lay_out_window();
extern Object leave_dialog_for_pause_for_internal_error_or_debug();
extern Object leave_dialog_for_t2();
extern Object list_callers_of_computation_instance();
extern Object list_loaded_user_visible_modules();
extern Object load_and_initialize_type_description();
extern Object log_in_workstation();
extern Object log_out_workstation();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lookup_key_in_context();
extern Object make_alias_creation_attribute_table();
extern Object make_attributes_table();
extern Object make_block_near_mouse_cache_internal_1();
extern Object make_context_description();
extern Object make_credits_table_spot_1();
extern Object make_diacritic_header_table_row();
extern Object make_diacritic_help_table_rows();
extern Object make_diacritic_table_row();
extern Object make_empty_text();
extern Object make_entity();
extern Object make_eval_list_1();
extern Object make_format_frame();
extern Object make_frame();
extern Object make_g2_login_attributes_table();
extern Object make_g2_login_state_1();
extern Object make_help_workspace();
extern Object make_hex_code_help_table_rows();
extern Object make_icon_cell();
extern Object make_icon_cell_for_entity();
extern Object make_initial_partial_command();
extern Object make_keymap();
extern Object make_lost_spaces_text_element();
extern Object make_message();
extern Object make_named_dynamic_extent_description();
extern Object make_new_alias();
extern Object make_or_reformat_table();
extern Object make_output_only_table_spot_1();
extern Object make_password_change_attributes_table();
extern Object make_permanent_block_near_mouse_cache_structure_internal();
extern Object make_permanent_g2_login_state_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_user_mode_alias_structure_internal();
extern Object make_short_representation();
extern Object make_special_character_help_table();
extern Object make_standalone_header_table_row();
extern Object make_standalone_special_character_help_table_rows();
extern Object make_standalone_special_character_row_if_necessary();
extern Object make_standalone_special_character_rows();
extern Object make_subcommand_menu();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_text_cell();
extern Object make_text_for_diacritic_table_row_with_presentations();
extern Object make_text_for_diacritic_table_row_with_type_ins();
extern Object make_text_for_gensym_g2();
extern Object make_text_for_local_identification();
extern Object make_text_for_product_and_options();
extern Object make_text_for_special_character_type_ins();
extern Object make_text_for_type_of_g2_license();
extern Object make_thread_array();
extern Object make_timestamp_list_1();
extern Object make_user_mode_alias_1();
extern Object make_user_settings_editor_state();
extern Object make_window_visible();
extern Object make_workspace();
extern Object make_workspace_background_spot_1();
extern Object manage_debugger_dialog();
extern Object map_to_color_value_1();
extern Object maybe_schedule_service_workstations();
extern Object memq_function();
extern Object most_interesting_frame();
extern Object mouse_down_on_attribute_value_in_g2_login_state();
extern Object mouse_down_on_otherwise_in_g2_login_state();
extern Object mouse_down_on_subcommand_menu_button_in_g2_login_state();
extern Object mouse_leeway_in_workspace();
extern Object mouse_pointer_blackboard_function();
extern Object move_image_plane();
extern Object mutate_gensym_plist();
extern Object mutate_global_property();
extern Object name_of_exported_event_handler_qm();
extern Object name_of_user_menu_choice_qm();
extern Object native_debugger_dialog_p();
extern Object native_login_dialog_p();
extern Object native_menu_bar_really_needs_updating_p();
extern Object no_local_window_p();
extern Object non_menu_choice_permitted_p();
extern Object noop_cleanup_form();
extern Object note_change_to_block_1();
extern Object nothing();
extern Object notice_tw_disconnect();
extern Object notify_user();
extern Object notify_user_at_console();
extern Object notify_user_at_console_and_on_logbook();
extern Object offer_g2_user_settings_back_to_telewindows();
extern Object outstanding_block_near_mouse_cache_count();
extern Object outstanding_g2_login_state_count();
extern Object outstanding_user_mode_alias_count();
extern Object pass_command_to_g2passwd();
extern Object pause_during_debug();
extern Object pause_for_internal_error();
extern Object pause_for_internal_error_or_debug();
extern Object permit_generic_ui_command_p();
extern Object pick_cell_from_table();
extern Object poll_workstation();
extern Object post_classic_debugger_dialog();
extern Object post_native_debugger_dialog();
extern Object post_native_login_dialog();
extern Object post_setjmp_status();
extern Object post_workspace_in_pane_function();
extern Object print_decoded_time();
extern Object print_means_print_to_server_in_configurations_p();
extern Object procedure_definition_function();
extern Object pursue_partial_command();
extern Object push_item_to_end_of_current_localization_domains();
extern Object push_last_spot();
extern Object push_optimized_constant();
extern Object put_up_aliases_table();
extern Object put_up_long_operation_notification_now();
extern Object put_up_special_character_help_workspace();
extern Object put_workspace_on_pane_function();
extern Object quick_clipping_check_of_block_for_picking();
extern Object raise_image_plane_to_top();
extern Object raw_stack_error_1();
extern Object read_element_for_kb();
extern Object read_ok_file_again();
extern Object read_ok_file_just_for_updating_user_data();
extern Object read_user_mode_alias_for_kb();
extern Object reclaim_block_near_mouse_cache_1();
extern Object reclaim_eval_cons_1();
extern Object reclaim_eval_list_1();
extern Object reclaim_eval_tree_1();
extern Object reclaim_event_interpretation();
extern Object reclaim_frame_serial_number();
extern Object reclaim_g2_login_state_1();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_halt_info();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_menu_item();
extern Object reclaim_menu_items();
extern Object reclaim_schedule_task_args();
extern Object reclaim_slot_value();
extern Object reclaim_slot_value_cons_1();
extern Object reclaim_slot_value_list_1();
extern Object reclaim_status_table_frame_serial_number_value();
extern Object reclaim_text_string();
extern Object reclaim_timestamp_cons_1();
extern Object reclaim_timestamp_list_1();
extern Object reclaim_user_mode_alias_1();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object reference_mouse_pointer();
extern Object regenerate_optimized_constant();
extern Object register_all_signal_handlers();
extern Object register_button_label_for_internationalization();
extern Object reinstall_authorized_users();
extern Object release_mouse_pointer_if_any();
extern Object release_mouse_pointers();
extern Object remove_authorized_user();
extern Object remove_character_from_wide_string();
extern Object remove_dialog_info_from_ui_client_interface_dialog_list();
extern Object remove_last_item_in_current_localization_domains();
extern Object replenish_lookup_cons_pool();
extern Object replenish_slot_value_cons_pool();
extern Object report_listener_info_to_parent_window();
extern Object require_that_image_plane_be_visible();
extern Object resize_for_icon_cell();
extern Object return_from_breakpoint();
extern Object return_from_current_workstation_context();
extern Object return_from_g2_set_g2_state();
extern Object run_ab();
extern Object run_ab_process_top_level();
extern Object run_event_handler();
extern Object run_scheduler_for_breakpoint();
extern Object run_system_process();
extern Object run_top_level_event_handler();
extern Object running_as_noninteractive_service_p();
extern Object save_new_user_password_in_g2_ok_file();
extern Object saving_new_password_format_control_string();
extern Object scalef_function();
extern Object schedule_g2_legacy_heartbeat_tasks_if_necessary();
extern Object selection_handles_visible_p();
extern Object sentence_end_punctuation_qm();
extern Object set_cursor_position();
extern Object set_flag_permitting_free_floating_authorization();
extern Object set_frame_style_of_block();
extern Object set_icp_tracing_level_from_command_line();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_session_info_in_g2_login();
extern Object set_session_info_in_g2_window();
extern Object set_session_info_in_workstation();
extern Object set_skip_list_entry();
extern Object set_slot_value_function();
extern Object set_up_workstation();
extern Object set_validity_of_user_password();
extern Object shift_block();
extern Object shut_down_ab_process();
extern Object shutdown_or_exit();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object slot_value_list_4();
extern Object sort_list();
extern Object specific_menu_item_for_generic_command_qm();
extern Object spot_generator_for_credits_table_format();
extern Object spot_generator_for_help_table_format();
extern Object start_generic_command();
extern Object start_scheduler_workers();
extern Object start_ui_command();
extern Object string_equalw();
extern Object string_for_localized_symbol();
extern Object stringw();
extern Object subplane_qm();
extern Object switch_to_new_empty_kb();
extern Object symbol_namew();
extern Object system_pause();
extern Object system_resume();
extern Object table_visible_in_image_plane_p();
extern Object table_visible_near_mouse_p();
extern Object test_restrictions_for_image_plane_action();
extern Object text_box_visible_near_mouse_p();
extern Object text_box_visible_p();
extern Object text_cell_of_table_blackboard_function();
extern Object text_string_length();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_text_string();
extern Object thing_selected_p();
extern Object throw_to_chestnut_catcher();
extern Object timestamp_cons_1();
extern Object title_block_table_p();
extern Object title_block_workspace_p();
extern Object too_many_login_attempts_from_this_source();
extern Object track_mouse_over_frame();
extern Object transform_image();
extern Object transform_subplanes_per_lead_plane();
extern Object translated_string_for_symbol();
extern Object translation_for_symbol_qm();
extern Object trigger_user_icon_movement_rules_for_blocks();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_current_real_time();
extern Object twrite_general_string();
extern Object twrite_help_table_character();
extern Object twrite_key_patterns_and_classes();
extern Object twrite_login_failure_translation_symbol();
extern Object twrite_standard_secure_g2_notification_header();
extern Object twrite_system_version_in_g2_title();
extern Object twrite_unix_time();
extern Object twrite_wide_character();
extern Object type_of_slot_if_editable();
extern Object ui_command_name_for_describe_keymap();
extern Object unicode_lowercase_if_uppercase();
extern Object update_ab_side_tw_user_mode();
extern Object update_native_menu_bar();
extern Object update_object_pool_meters_list();
extern Object update_system_tray_icon();
extern Object update_user_mode_state();
extern Object user_mode_alias_structure_memory_usage();
extern Object valid_password_characters_p();
extern Object validate_as_possible_user_mode();
extern Object validate_executing_statements_and_procedures();
extern Object verify_chestnut_catch_reverts_locals_fix();
extern Object verify_chestnut_unwind_protect_reverts_locals_fix();
extern Object warn_user_of_previously_aborted_g2();
extern Object workstation_context_specifics_blackboard_function();
extern Object write_char_for_kb();
extern Object write_element_for_kb();
extern Object write_g2_login_comments_from_slot();
extern Object write_local_identification_info_text_string();
extern Object write_symbol_from_slot();
extern Object write_symbol_list();
extern Object write_user_mode_alias_for_kb();
extern Object x_in_window_blackboard_function();
extern Object x_in_workspace_blackboard_function();
extern Object y_in_window_blackboard_function();
extern Object y_in_workspace_blackboard_function();

#endif

/* variables/constants */
extern Object Alias_creation_attributes_to_show;
DECLARE_VARIABLE_WITH_SYMBOL(All_computation_instances_above_breakpoint, Qall_computation_instances_above_breakpoint);
extern Object All_optional_modules_for_display;
DECLARE_VARIABLE_WITH_SYMBOL(Allow_debugger_pause, Qallow_debugger_pause);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_users_list, Qauthorized_users_list);
DECLARE_VARIABLE_WITH_SYMBOL(Authorizing_ok_pathname, Qauthorizing_ok_pathname);
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_slot_value_conses_tail_vector;
extern Object Available_slot_value_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Block_near_mouse_cache_count, Qblock_near_mouse_cache_count);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_frame, Qbottom_edge_of_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Breakpoints_enabled_p, Qbreakpoints_enabled_p);
extern Object Build_comment_string;
DECLARE_VARIABLE_WITH_SYMBOL(Cache_al_semantics_graph, Qcache_al_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_chinese_semantics_graph, Qcache_chinese_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_embedded_option_semantics_graph, Qcache_embedded_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_ent_semantics_graph, Qcache_ent_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_g1_semantics_graph, Qcache_g1_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_gfi_semantics_graph, Qcache_gfi_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_gsi_semantics_graph, Qcache_gsi_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_icp_semantics_graph, Qcache_icp_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_japanese_semantics_graph, Qcache_japanese_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_jl_semantics_graph, Qcache_jl_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_jp_semantics_graph, Qcache_jp_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_korean_semantics_graph, Qcache_korean_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_nupec_semantics_graph, Qcache_nupec_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_restricted_use_option_semantics_graph, Qcache_restricted_use_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Cache_runtime_option_semantics_graph, Qcache_runtime_option_semantics_graph);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_block_near_mouse_caches, Qchain_of_available_block_near_mouse_caches);
extern Object Chain_of_available_block_near_mouse_caches_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_g2_login_states, Qchain_of_available_g2_login_states);
extern Object Chain_of_available_g2_login_states_vector;
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_user_mode_aliass, Qchain_of_available_user_mode_aliass);
extern Object Chain_of_available_user_mode_aliass_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Class_definition_class_description, Qclass_definition_class_description);
extern Object Class_description_gkbprop;
extern Object Class_instance_delta_masks;
DECLARE_VARIABLE_WITH_SYMBOL(Classes_of_objects_to_not_consider_qm, Qclasses_of_objects_to_not_consider_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Computation_frame_at_breakpoint, Qcomputation_frame_at_breakpoint);
DECLARE_VARIABLE_WITH_SYMBOL(Computation_instance_at_breakpoint, Qcomputation_instance_at_breakpoint);
DECLARE_VARIABLE_WITH_SYMBOL(Consistency_tree_focus_shifts, Qconsistency_tree_focus_shifts);
extern Object Constant_mouse_leeway;
DECLARE_VARIABLE_WITH_SYMBOL(Copyright_boilerplate_lines_of_text_1, Qcopyright_boilerplate_lines_of_text_1);
DECLARE_VARIABLE_WITH_SYMBOL(Copyright_boilerplate_lines_of_text_2, Qcopyright_boilerplate_lines_of_text_2);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_color_map, Qcurrent_color_map);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_instance, Qcurrent_computation_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Current_draw_paper_p, Qcurrent_draw_paper_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_plane, Qcurrent_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_serial_number, Qcurrent_kb_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_localization_purpose_qm, Qcurrent_localization_purpose_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_long_operation_notification_workspace, Qcurrent_long_operation_notification_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Current_native_window_qm, Qcurrent_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_pane, Qcurrent_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_system_name, Qcurrent_system_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_window, Qcurrent_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
extern Object Debug_clear_text_checksums;
#define Debugger_dialog_cancel FIX((SI_Long)2L)
#define Debugger_dialog_create FIX((SI_Long)1L)
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Default_language, Qdefault_language);
extern Object Do_error_trapping_qm;
DECLARE_VARIABLE_WITH_SYMBOL(Doing_long_operation_with_notification_qm, Qdoing_long_operation_with_notification_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Doing_password_change_p, Qdoing_password_change_p);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_on_window, Qdrawing_on_window);
DECLARE_VARIABLE_WITH_SYMBOL(Edit_type_alias_mapping, Qedit_type_alias_mapping);
#define Editor_disabled_breakpoint_flag FIX((SI_Long)1048576L)
DECLARE_VARIABLE_WITH_SYMBOL(Editor_parameters, Qeditor_parameters);
extern Object Editor_special_character_alist;
DECLARE_VARIABLE_WITH_SYMBOL(Embedded_fuzzy_conditionals_list, Qembedded_fuzzy_conditionals_list);
extern Object Embedded_g2_with_windows_goodbye_message;
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Event_handler_args, Qevent_handler_args);
#define External_version FIX((SI_Long)2015L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Finding_object_near_mouse, Qfinding_object_near_mouse);
DECLARE_VARIABLE_WITH_SYMBOL(Fixnum_time_at_start_of_current_long_notification, Qfixnum_time_at_start_of_current_long_notification);
DECLARE_VARIABLE_WITH_SYMBOL(For_image_plane, Qfor_image_plane);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
extern Object Format_structure_description;
extern Object G2_login_attributes_to_show;
DECLARE_VARIABLE_WITH_SYMBOL(G2_login_class_description, Qg2_login_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_login_state_count, Qg2_login_state_count);
extern Object G2_system_time_too_early_goodbye_message;
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2passwdexe, Qg2passwdexe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_argument_list, Qgensym_error_argument_list);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_format_string, Qgensym_error_format_string);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_sure_of_format_info_p, Qgensym_error_sure_of_format_info_p);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_logo_style, Qgensym_logo_style);
DECLARE_VARIABLE_WITH_SYMBOL(Get_object_on_kb_workspace_for_item, Qget_object_on_kb_workspace_for_item);
DECLARE_VARIABLE_WITH_SYMBOL(Gfi_list_of_converters, Qgfi_list_of_converters);
extern Object Height_for_prominent_notification_workspaces;
#define Higher_than_any_priority FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Icon_cell_class_description, Qicon_cell_class_description);
extern Object Illegal_key_index;
DECLARE_VARIABLE_WITH_SYMBOL(Image_plane_for_finding_object_near_mouse, Qimage_plane_for_finding_object_near_mouse);
DECLARE_VARIABLE_WITH_SYMBOL(Image_x_scale_for_finding_object_near_mouse, Qimage_x_scale_for_finding_object_near_mouse);
DECLARE_VARIABLE_WITH_SYMBOL(Image_y_scale_for_finding_object_near_mouse, Qimage_y_scale_for_finding_object_near_mouse);
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_open_windows, Qindex_of_open_windows);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Initial_java_class, Qinitial_java_class);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
extern Object Instances_specific_to_this_class_kbprop;
extern Object Interrim_no_mark_logo_p;
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Journal_shutout_scan_p, Qjournal_shutout_scan_p);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_configuration, Qkb_configuration);
DECLARE_VARIABLE_WITH_SYMBOL(Kb_restrictions, Qkb_restrictions);
extern Object Key_index_bits;
DECLARE_VARIABLE_WITH_SYMBOL(Language_parameters, Qlanguage_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Learned_list_to_expedite_ui, Qlearned_list_to_expedite_ui);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_frame, Qleft_edge_of_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Listed_continuation_servers, Qlisted_continuation_servers);
DECLARE_VARIABLE_WITH_SYMBOL(Listed_print_to_server_command, Qlisted_print_to_server_command);
DECLARE_VARIABLE_WITH_SYMBOL(Localization_context, Qlocalization_context);
DECLARE_VARIABLE_WITH_SYMBOL(Long_operation_notification_has_been_put_up_qm, Qlong_operation_notification_has_been_put_up_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_bottom_edge_of_visible_workspace_area, Qloose_bottom_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_end_class_description, Qloose_end_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_left_edge_of_visible_workspace_area, Qloose_left_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_right_edge_of_visible_workspace_area, Qloose_right_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Loose_top_edge_of_visible_workspace_area, Qloose_top_edge_of_visible_workspace_area);
DECLARE_VARIABLE_WITH_SYMBOL(Master_hierarchy_reconciliation_switches, Qmaster_hierarchy_reconciliation_switches);
#define Maximum_g2_password_length FIX((SI_Long)499L)
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
extern Object Maximum_number_of_login_attempts_permitted_per_window;
DECLARE_VARIABLE_WITH_SYMBOL(May_return_from_breakpoint, Qmay_return_from_breakpoint);
DECLARE_VARIABLE_WITH_SYMBOL(Minimal_fragmentation_seeds, Qminimal_fragmentation_seeds);
#define Minimum_g2_password_length FIX((SI_Long)4L)
extern Object Minimum_width_or_height_for_picking_in_window_units;
extern Object Minimum_x_scale_for_picking;
extern Object Minus_of_isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Mouse_x_in_workspace, Qmouse_x_in_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Mouse_y_in_workspace, Qmouse_y_in_workspace);
DECLARE_VARIABLE_WITH_SYMBOL(Name_box_class_description, Qname_box_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(Non_kb_workspace_class_description, Qnon_kb_workspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Objects_to_not_consider_qm, Qobjects_to_not_consider_qm);
extern Object Old_eval_cons_list;
DECLARE_VARIABLE_WITH_SYMBOL(On_window_without_drawing, Qon_window_without_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Overflow_byte_count, Qoverflow_byte_count);
DECLARE_VARIABLE_WITH_SYMBOL(Pane_for_debugger_pause, Qpane_for_debugger_pause);
extern Object Password_change_attributes_to_show;
DECLARE_VARIABLE_WITH_SYMBOL(Pop_fonts_stack, Qpop_fonts_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Popup_frames_available, Qpopup_frames_available);
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Radio_button_status_flags, Qradio_button_status_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Radio_button_status_flags_1, Qradio_button_status_flags_1);
DECLARE_VARIABLE_WITH_SYMBOL(Reclaim_fonts_stack, Qreclaim_fonts_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Redo_saved_changes, Qredo_saved_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Relations_tag_list, Qrelations_tag_list);
DECLARE_VARIABLE_WITH_SYMBOL(Result_of_enter_dialog_for_t2_for_pause_for_internal_error_or_debug, Qresult_of_enter_dialog_for_t2_for_pause_for_internal_error_or_debug);
DECLARE_VARIABLE_WITH_SYMBOL(Return_from_breakpoint_task, Qreturn_from_breakpoint_task);
#define Revision_number_of_current_gensym_product_line FIX((SI_Long)9L)
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_frame, Qright_edge_of_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Rule_class_description, Qrule_class_description);
extern Object Scalable_mouse_leeway;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Seconds_from_1900_to_1970;
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Show_procedure_invocation_hierarchy_on_debugger_pause_p, Qshow_procedure_invocation_hierarchy_on_debugger_pause_p);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Source_stepping_level, Qsource_stepping_level);
DECLARE_VARIABLE_WITH_SYMBOL(Sparse_known_pathnames_list, Qsparse_known_pathnames_list);
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_window, Qsystem_window);
DECLARE_VARIABLE_WITH_SYMBOL(Table_class_description, Qtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Task_to_warn_user_of_previously_aborted_g2, Qtask_to_warn_user_of_previously_aborted_g2);
DECLARE_VARIABLE_WITH_SYMBOL(Temporary_workspace_class_description, Qtemporary_workspace_class_description);
extern Object The_type_description_of_block_near_mouse_cache;
extern Object The_type_description_of_g2_login_state;
extern Object The_type_description_of_user_mode_alias;
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_frame, Qtop_edge_of_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Top_level_error_catcher_tag, Qtop_level_error_catcher_tag);
DECLARE_VARIABLE_WITH_SYMBOL(Top_level_error_seen, Qtop_level_error_seen);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Transform_image_operation_hint, Qtransform_image_operation_hint);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_window, Qtype_of_current_window);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Ui_command_context, Qui_command_context);
#define Unicode_bit FIX((SI_Long)16777216L)
extern Object Unicode_character_bits;
extern Object Unselectable_classes_of_objects;
#define Use_full_size_of_with_output_wide_string_cutoff FIX((SI_Long)256L)
DECLARE_VARIABLE_WITH_SYMBOL(User_mode_alias_count, Quser_mode_alias_count);
#define Wide_string_list_maximum_length FIX((SI_Long)1024L)
extern Object Width_for_prominent_notification_workspaces;
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_console_p, Qwrite_console_p);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(X11_preinitialized_p, Qx11_preinitialized_p);
DECLARE_VARIABLE_WITH_SYMBOL(X_in_window_for_finding_object_near_mouse, Qx_in_window_for_finding_object_near_mouse);
DECLARE_VARIABLE_WITH_SYMBOL(Y_in_window_for_finding_object_near_mouse, Qy_in_window_for_finding_object_near_mouse);
