/* schdle.h -- Header File for schdle.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Klock;
extern Object Qmost_positive_fixnum;
extern Object Kname;
extern Object Qunsigned_byte;
extern Object Qvector;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object adjust_task_times_after_clock_discontinuity(Object,Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_initial_managed_simple_vector_pool_array(Object);
extern Object allocate_initial_vector_of_simple_float_array_pools(void);
extern Object allocate_managed_float_box(void);
extern Object allocate_managed_simple_float_array(Object);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object allocated_named_gensym_structure_p(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object c_native_clock_ticks_or_cache(Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_g2_running_tasks(void);
extern Object clear_g2_schedule(void);
extern Object clear_optimized_constants(void);
extern Object command_line_process_legacy(Object);
extern Object command_line_process_threads(Object);
extern Object constant_queue_delete(int,...);
extern Object constant_queue_next(Object,Object);
extern Object constant_queue_pop_left(int,...);
extern Object constant_queue_push_right(Object,Object);
extern Object constant_queue_read(int,...);
extern Object copy_out_current_wide_string(void);
extern Object current_g2_run_state(void);
extern Object defer_current_g2_running_tasks(void);
extern Object delete_future_task_queue_for_task(Object);
extern Object delete_future_task_queue_for_task_inner(Object,Object,Object);
extern Object dequeue_and_execute_next_task(void);
extern Object dequeue_next_task(void);
extern Object direct_structure_method(Object,Object);
extern Object enqueue_scheduler_events_if_necessary(Object);
extern Object execute_task_and_reschedule(Object);
extern Object execute_task_out_of_order_1(Object);
extern Object exit_current_profiling_context(Object);
extern Object extend_current_gensym_string(int,...);
extern Object future_task_queue_find(Object,Object,Object,Object,Object);
extern Object future_task_queue_holder_structure_memory_usage(void);
extern Object future_task_schedule_2(Object);
extern Object g2_event_ready_p(void);
extern Object g2_worker_loop(void);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object get_command_line_flag_argument(int,...);
extern Object get_command_line_keyword_argument(int,...);
extern Object get_command_line_keyword_argument_as_integer(int,...);
extern Object get_command_line_plist_element_for_legacy(void);
extern Object get_command_line_plist_element_for_threads(void);
extern Object get_name_for_function(Object);
extern Object get_or_create_future_task_queue_for_task(Object);
extern Object get_pending_network_events(void);
extern Object get_workers_from_command_line(void);
extern Object getfq_function_no_default(Object,Object);
extern Object initialize_scheduler(void);
extern Object legacy_mode_p(void);
extern Object load_and_initialize_type_description(Object,Object);
extern Object make_byte_vector_16_pools(Object);
extern Object make_duplicates_check_hash_table(void);
extern Object make_empty_constant_queue(void);
extern Object make_future_task_priority_queue(void);
extern Object make_future_task_queue_holder_1_1(void);
extern Object make_future_task_queue_holder_sentinel(Object,Object);
extern Object make_gensym_list_1(Object);
extern Object make_gensym_time_array(void);
extern Object make_partition_float_or_long_union(void);
extern Object make_permanent_future_task_queue_holder_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_schedule_task_1(Object);
extern Object make_thread_array(Object);
extern Object merge_constant_queues(Object,Object);
extern Object milliseconds_to_next_scheduler_event(void);
extern Object milliseconds_to_next_task(void);
extern Object minimum_scheduling_interval_function(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object name_and_class_for_computation_instance(Object);
extern Object new_partial_buffer_gensym_string_vector(Object);
extern Object new_short_simple_gensym_string_vector(Object);
extern Object next_scheduled_task_for_function(Object,Object);
extern Object note_scheduling_task_1(Object,Object);
extern Object outstanding_future_task_queue_holder_count(void);
extern Object outstanding_schedule_task_count(void);
extern Object posit_profiling_structure(Object);
extern Object print_random_object_prefix(Object,Object);
extern Object print_random_object_suffix(Object,Object);
extern Object print_schedule_task(Object,Object,Object);
extern Object print_schedule_to_string_list(Object);
extern Object push_optimized_constant(Object);
extern Object random_level(Object);
extern Object reclaim_constant_queue(Object);
extern Object reclaim_future_task_queue_holder(Object);
extern Object reclaim_future_task_queue_holder_1_1(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_managed_simple_vector_for_skip_list(Object);
extern Object reclaim_schedule_task_1(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_simple_gensym_string(Object);
extern Object reclaim_text_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object requeue_deferred_running_tasks(void);
extern Object requeue_queue_element(Object,Object,Object);
extern Object schedule_task_structure_memory_usage(void);
extern Object scheduler_mode_function(Object);
extern Object scheduler_time_lag(Object);
extern Object scheduler_worker_function(Object);
extern Object scheduler_worker_loop(void);
extern Object start_scheduler_workers(void);
extern Object task_queue_descriptions(Object);
extern Object tasks_deferred_until_resumption_qm(void);
extern Object tasks_enqueued_for_current_execution_qm(void);
extern Object text_string_length(Object);
extern Object tformat(int,...);
extern Object tick_the_clock(Object);
extern Object time_slice_expired_p(void);
extern Object time_slice_expired_p_given_time(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_debug_computation_instance_or_object(Object);
extern Object twrite_debug_object(Object);
extern Object twrite_general_string(Object);
extern Object twrite_schedule_task(Object);
extern Object twrite_schedule_task_header(void);
extern Object twrite_wide_character(Object);
extern Object type_name_of_named_simple_vector(Object);
extern Object unpack_future_tasks_into_current_task_queues(Object);
extern Object unpack_one_future_task_queue(Object);
extern Object update_object_pool_meters_list(Object);
extern Object write_floating_point_number(int,...);

#else

extern Object adjust_task_times_after_clock_discontinuity();
extern Object allocate_byte_vector_16();
extern Object allocate_initial_managed_simple_vector_pool_array();
extern Object allocate_initial_vector_of_simple_float_array_pools();
extern Object allocate_managed_float_box();
extern Object allocate_managed_simple_float_array();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object allocated_named_gensym_structure_p();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object c_native_clock_ticks_or_cache();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_g2_running_tasks();
extern Object clear_g2_schedule();
extern Object clear_optimized_constants();
extern Object command_line_process_legacy();
extern Object command_line_process_threads();
extern Object constant_queue_delete();
extern Object constant_queue_next();
extern Object constant_queue_pop_left();
extern Object constant_queue_push_right();
extern Object constant_queue_read();
extern Object copy_out_current_wide_string();
extern Object current_g2_run_state();
extern Object defer_current_g2_running_tasks();
extern Object delete_future_task_queue_for_task();
extern Object delete_future_task_queue_for_task_inner();
extern Object dequeue_and_execute_next_task();
extern Object dequeue_next_task();
extern Object direct_structure_method();
extern Object enqueue_scheduler_events_if_necessary();
extern Object execute_task_and_reschedule();
extern Object execute_task_out_of_order_1();
extern Object exit_current_profiling_context();
extern Object extend_current_gensym_string();
extern Object future_task_queue_find();
extern Object future_task_queue_holder_structure_memory_usage();
extern Object future_task_schedule_2();
extern Object g2_event_ready_p();
extern Object g2_worker_loop();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object get_command_line_flag_argument();
extern Object get_command_line_keyword_argument();
extern Object get_command_line_keyword_argument_as_integer();
extern Object get_command_line_plist_element_for_legacy();
extern Object get_command_line_plist_element_for_threads();
extern Object get_name_for_function();
extern Object get_or_create_future_task_queue_for_task();
extern Object get_pending_network_events();
extern Object get_workers_from_command_line();
extern Object getfq_function_no_default();
extern Object initialize_scheduler();
extern Object legacy_mode_p();
extern Object load_and_initialize_type_description();
extern Object make_byte_vector_16_pools();
extern Object make_duplicates_check_hash_table();
extern Object make_empty_constant_queue();
extern Object make_future_task_priority_queue();
extern Object make_future_task_queue_holder_1_1();
extern Object make_future_task_queue_holder_sentinel();
extern Object make_gensym_list_1();
extern Object make_gensym_time_array();
extern Object make_partition_float_or_long_union();
extern Object make_permanent_future_task_queue_holder_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_schedule_task_1();
extern Object make_thread_array();
extern Object merge_constant_queues();
extern Object milliseconds_to_next_scheduler_event();
extern Object milliseconds_to_next_task();
extern Object minimum_scheduling_interval_function();
extern Object mutate_global_property();
extern Object name_and_class_for_computation_instance();
extern Object new_partial_buffer_gensym_string_vector();
extern Object new_short_simple_gensym_string_vector();
extern Object next_scheduled_task_for_function();
extern Object note_scheduling_task_1();
extern Object outstanding_future_task_queue_holder_count();
extern Object outstanding_schedule_task_count();
extern Object posit_profiling_structure();
extern Object print_random_object_prefix();
extern Object print_random_object_suffix();
extern Object print_schedule_task();
extern Object print_schedule_to_string_list();
extern Object push_optimized_constant();
extern Object random_level();
extern Object reclaim_constant_queue();
extern Object reclaim_future_task_queue_holder();
extern Object reclaim_future_task_queue_holder_1_1();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_managed_simple_vector_for_skip_list();
extern Object reclaim_schedule_task_1();
extern Object reclaim_schedule_task_args();
extern Object reclaim_simple_gensym_string();
extern Object reclaim_text_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_lookup_cons_pool();
extern Object requeue_deferred_running_tasks();
extern Object requeue_queue_element();
extern Object schedule_task_structure_memory_usage();
extern Object scheduler_mode_function();
extern Object scheduler_time_lag();
extern Object scheduler_worker_function();
extern Object scheduler_worker_loop();
extern Object start_scheduler_workers();
extern Object task_queue_descriptions();
extern Object tasks_deferred_until_resumption_qm();
extern Object tasks_enqueued_for_current_execution_qm();
extern Object text_string_length();
extern Object tformat();
extern Object tick_the_clock();
extern Object time_slice_expired_p();
extern Object time_slice_expired_p_given_time();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_debug_computation_instance_or_object();
extern Object twrite_debug_object();
extern Object twrite_general_string();
extern Object twrite_schedule_task();
extern Object twrite_schedule_task_header();
extern Object twrite_wide_character();
extern Object type_name_of_named_simple_vector();
extern Object unpack_future_tasks_into_current_task_queues();
extern Object unpack_one_future_task_queue();
extern Object update_object_pool_meters_list();
extern Object write_floating_point_number();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_string_counts, Qadjustable_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_strings, Qadjustable_gensym_strings);
DECLARE_VARIABLE_WITH_SYMBOL(All_known_command_line_plist_elements, Qall_known_command_line_plist_elements);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_workstation_contexts, Qavailable_workstation_contexts);
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
DECLARE_VARIABLE_WITH_SYMBOL(Byte_vector_16_pool_counts, Qbyte_vector_16_pool_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Byte_vector_16_pool_number_to_malloc, Qbyte_vector_16_pool_number_to_malloc);
DECLARE_VARIABLE_WITH_SYMBOL(Byte_vector_16_pools, Qbyte_vector_16_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_future_task_queue_holders, Qchain_of_available_future_task_queue_holders);
extern Object Chain_of_available_future_task_queue_holders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_schedule_tasks, Qchain_of_available_schedule_tasks);
extern Object Chain_of_available_schedule_tasks_vector;
extern Object Constant_queue_head_marker;
extern Object Constant_queue_tail_marker;
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icon_untransformed_height, Qcurrent_icon_untransformed_height);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icon_untransformed_width, Qcurrent_icon_untransformed_width);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icon_variables_override_plist, Qcurrent_icon_variables_override_plist);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icon_variables_plist, Qcurrent_icon_variables_plist);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_saving_context_qm, Qcurrent_saving_context_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_transform_constituent_array, Qcurrent_transform_constituent_array);
DECLARE_VARIABLE_WITH_SYMBOL(Current_transform_constituent_count, Qcurrent_transform_constituent_count);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Duplicates_check_hash, Qduplicates_check_hash);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
extern Object Future_g2_time_tasks;
extern Object Future_real_time_tasks;
DECLARE_VARIABLE_WITH_SYMBOL(Future_task_queue_holder_count, Qfuture_task_queue_holder_count);
extern Object Future_task_queue_marker;
#define Future_task_queue_max_level FIX((SI_Long)15L)
extern Object G2_main_thread;
extern Object G2_max_threads;
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_base_time_as_managed_float, Qgensym_base_time_as_managed_float);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_array, Qgensym_time_array);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nms_menu_choiced_item_id, Qglobal_nms_menu_choiced_item_id);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nmsci_id_for_attributes_pane, Qglobal_nmsci_id_for_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_nmsci_id_for_hidden_attributes_pane, Qglobal_nmsci_id_for_hidden_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_attributes_pane, Qglobal_table_of_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_attributes_pane_pointer, Qglobal_table_of_attributes_pane_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_hidden_attributes_pane, Qglobal_table_of_hidden_attributes_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Global_table_of_hidden_attributes_pane_pointer, Qglobal_table_of_hidden_attributes_pane_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Gsi_maximum_idle_interval, Qgsi_maximum_idle_interval);
#define Higher_than_any_priority FIX((SI_Long)-1L)
#define Highest_system_priority FIX((SI_Long)0L)
#define Highest_user_priority FIX((SI_Long)1L)
#define How_many_priorities_qm FIX((SI_Long)10L)
extern Object Immediate_task_queue;
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
extern Object Legacy_mode_p;
DECLARE_VARIABLE_WITH_SYMBOL(List_of_generated_contexts, Qlist_of_generated_contexts);
DECLARE_VARIABLE_WITH_SYMBOL(List_of_generated_contexts_tail, Qlist_of_generated_contexts_tail);
DECLARE_VARIABLE_WITH_SYMBOL(Long_simple_gensym_string_counts, Qlong_simple_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Long_simple_gensym_strings, Qlong_simple_gensym_strings);
#define Lower_than_any_priority FIX((SI_Long)12L)
#define Lowest_system_priority FIX((SI_Long)11L)
extern Object Max_number_of_cores;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
DECLARE_VARIABLE_WITH_SYMBOL(Maximum_time_slice_size, Qmaximum_time_slice_size);
extern Object Multicore_p;
DECLARE_VARIABLE_WITH_SYMBOL(Next_continuation_function_qm, Qnext_continuation_function_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Next_info, Qnext_info);
DECLARE_VARIABLE_WITH_SYMBOL(Next_info_reclaimer_qm, Qnext_info_reclaimer_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Next_old_style_return_function_qm, Qnext_old_style_return_function_qm);
extern Object Number_of_all_threads;
extern Object Number_of_scheduler_workers;
DECLARE_VARIABLE_WITH_SYMBOL(Optimized_constant_op_codes, Qoptimized_constant_op_codes);
DECLARE_VARIABLE_WITH_SYMBOL(Optimized_constant_pc, Qoptimized_constant_pc);
DECLARE_VARIABLE_WITH_SYMBOL(Optimized_constant_vector, Qoptimized_constant_vector);
DECLARE_VARIABLE_WITH_SYMBOL(Optimized_constant_vector_index, Qoptimized_constant_vector_index);
#define Optimized_constant_vector_length FIX((SI_Long)1300L)
DECLARE_VARIABLE_WITH_SYMBOL(Partition_float_union, Qpartition_float_union);
DECLARE_VARIABLE_WITH_SYMBOL(Partition_long_union, Qpartition_long_union);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_current_task, Qpriority_of_current_task);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Return_from_breakpoint_task, Qreturn_from_breakpoint_task);
#define Schedule_task_arg_limit FIX((SI_Long)4L)

/* slot offset for SCHEDULE-TASK-ARG-1 in structure SCHEDULE-TASK */
#define Schedule_task_arg_offset FIX((SI_Long)13L)
DECLARE_VARIABLE_WITH_SYMBOL(Schedule_task_count, Qschedule_task_count);
extern Object Scheduler_event_done;
extern Object Scheduler_event_lock;
extern Object Scheduler_event_ready;
DECLARE_VARIABLE_WITH_SYMBOL(Scheduler_has_been_initialized_p, Qscheduler_has_been_initialized_p);
extern Object Scheduler_task;
extern Object Scheduler_task_priority;
extern Object Scheduler_task_time;
#define Scheduler_worker_loop_interval FIX((SI_Long)1L)
extern Object Scheduler_worker_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Seconds_from_1900_to_1970;
DECLARE_VARIABLE_WITH_SYMBOL(Short_simple_gensym_string_counts, Qshort_simple_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Short_simple_gensym_strings, Qshort_simple_gensym_strings);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
#define Size_of_string_for_returning_floats FIX((SI_Long)100L)
DECLARE_VARIABLE_WITH_SYMBOL(Skip_list_find_preds, Qskip_list_find_preds);
DECLARE_VARIABLE_WITH_SYMBOL(Skip_list_find_succs, Qskip_list_find_succs);
#define Skip_list_global_max_level FIX((SI_Long)32L)
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(String_for_returning_floats, Qstring_for_returning_floats);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_aborted, Qsystem_has_aborted);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(The_g2_defstruct_package, Qthe_g2_defstruct_package);
extern Object The_type_description_of_future_task_queue_holder;
extern Object The_type_description_of_schedule_task;
DECLARE_VARIABLE_WITH_SYMBOL(Things_that_affect_this_formula, Qthings_that_affect_this_formula);
DECLARE_VARIABLE_WITH_SYMBOL(Time_slice_start_time, Qtime_slice_start_time);
DECLARE_VARIABLE_WITH_SYMBOL(Time_to_check_network_events, Qtime_to_check_network_events);
DECLARE_VARIABLE_WITH_SYMBOL(Timing_parameters, Qtiming_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_oversized_simple_float_array_pools, Qvector_of_oversized_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_oversized_simple_vector_pools, Qvector_of_oversized_simple_vector_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_vector_pools, Qvector_of_simple_vector_pools);
