/* slvc24.c
 * Input file:  slavic24.lisp
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */

#include "user.h"
#include "slvc24.h"


void slavic24_INIT()
{
    Object string_constant, Qroman, Qslavic24, AB_package;

    x_note_fn_call(70,0);
    SET_PACKAGE("AB");
    AB_package = STATIC_PACKAGE("AB");
    Qslavic24 = STATIC_SYMBOL("SLAVIC24",AB_package);
    Qroman = STATIC_SYMBOL("ROMAN",AB_package);
    define_ab_font(16,Qslavic24,Qroman,FIX((SI_Long)24L),FIX((SI_Long)19L),
	    FIX((SI_Long)31L),FIX((SI_Long)29L),Nil,Nil,Nil,
	    FIX((SI_Long)24L),FIX((SI_Long)70L),FIX((SI_Long)70L),
	    FIX((SI_Long)5973L),FIX((SI_Long)5973L),FIX((SI_Long)-3L),
	    FIX((SI_Long)-5L));
    string_constant = STATIC_STRING("0");
    add_character_description_1(9,FIX((SI_Long)33L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)34L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4211L),Nil);
    add_character_description_1(9,FIX((SI_Long)35L),FIX((SI_Long)14L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3685L),Nil);
    add_character_description_1(9,FIX((SI_Long)36L),FIX((SI_Long)17L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)37L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)38L),FIX((SI_Long)7L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)2L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1690L),Nil);
    add_character_description_1(9,FIX((SI_Long)39L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1822L),Nil);
    add_character_description_1(9,FIX((SI_Long)40L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3022L),Nil);
    add_character_description_1(9,FIX((SI_Long)41L),FIX((SI_Long)23L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)21L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5770L),Nil);
    add_character_description_1(9,FIX((SI_Long)42L),FIX((SI_Long)24L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)21L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)6146L),Nil);
    add_character_description_1(9,FIX((SI_Long)43L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4211L),Nil);
    add_character_description_1(9,FIX((SI_Long)44L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)46L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4032L),Nil);
    add_character_description_1(9,FIX((SI_Long)47L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)-2L),FIX((SI_Long)14L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)48L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3990L),Nil);
    add_character_description_1(9,FIX((SI_Long)49L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)50L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)51L),FIX((SI_Long)14L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3685L),Nil);
    add_character_description_1(9,FIX((SI_Long)52L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)-2L),FIX((SI_Long)15L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4127L),Nil);
    add_character_description_1(9,FIX((SI_Long)53L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)54L),FIX((SI_Long)21L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)18L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5394L),Nil);
    add_character_description_1(9,FIX((SI_Long)55L),FIX((SI_Long)14L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3482L),Nil);
    add_character_description_1(9,FIX((SI_Long)56L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)57L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)21L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)58L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)59L),FIX((SI_Long)15L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3942L),Nil);
    add_character_description_1(9,FIX((SI_Long)60L),FIX((SI_Long)20L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5011L),Nil);
    add_character_description_1(9,FIX((SI_Long)61L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)62L),FIX((SI_Long)18L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4683L),Nil);
    add_character_description_1(9,FIX((SI_Long)63L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)64L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)65L),FIX((SI_Long)17L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4348L),Nil);
    add_character_description_1(9,FIX((SI_Long)66L),FIX((SI_Long)14L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)14L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3685L),Nil);
    add_character_description_1(9,FIX((SI_Long)67L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4032L),Nil);
    add_character_description_1(9,FIX((SI_Long)68L),FIX((SI_Long)20L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5083L),Nil);
    add_character_description_1(9,FIX((SI_Long)69L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)14L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)70L),FIX((SI_Long)17L),
	    FIX((SI_Long)2L),FIX((SI_Long)-2L),FIX((SI_Long)15L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4468L),Nil);
    add_character_description_1(9,FIX((SI_Long)71L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4056L),Nil);
    add_character_description_1(9,FIX((SI_Long)72L),FIX((SI_Long)21L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)18L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5394L),Nil);
    add_character_description_1(9,FIX((SI_Long)73L),FIX((SI_Long)21L),
	    FIX((SI_Long)2L),FIX((SI_Long)-2L),FIX((SI_Long)19L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5495L),Nil);
    add_character_description_1(9,FIX((SI_Long)74L),FIX((SI_Long)16L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4211L),Nil);
    add_character_description_1(9,FIX((SI_Long)75L),FIX((SI_Long)20L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5059L),Nil);
    add_character_description_1(9,FIX((SI_Long)76L),FIX((SI_Long)16L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4020L),Nil);
    add_character_description_1(9,FIX((SI_Long)77L),FIX((SI_Long)17L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)15L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4366L),Nil);
    add_character_description_1(9,FIX((SI_Long)78L),FIX((SI_Long)21L),
	    FIX((SI_Long)2L),FIX((SI_Long)0L),FIX((SI_Long)18L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5370L),Nil);
    add_character_description_1(9,FIX((SI_Long)79L),FIX((SI_Long)15L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3805L),Nil);
    add_character_description_1(9,FIX((SI_Long)80L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)81L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)18L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)82L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3106L),Nil);
    add_character_description_1(9,FIX((SI_Long)83L),FIX((SI_Long)10L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2503L),Nil);
    add_character_description_1(9,FIX((SI_Long)84L),FIX((SI_Long)14L),
	    FIX((SI_Long)0L),FIX((SI_Long)-2L),FIX((SI_Long)12L),
	    FIX((SI_Long)14L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3458L),Nil);
    add_character_description_1(9,FIX((SI_Long)85L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)86L),FIX((SI_Long)18L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4677L),Nil);
    add_character_description_1(9,FIX((SI_Long)87L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3010L),Nil);
    add_character_description_1(9,FIX((SI_Long)88L),FIX((SI_Long)14L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3464L),Nil);
    add_character_description_1(9,FIX((SI_Long)89L),FIX((SI_Long)14L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3464L),Nil);
    add_character_description_1(9,FIX((SI_Long)90L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3118L),Nil);
    add_character_description_1(9,FIX((SI_Long)91L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3196L),Nil);
    add_character_description_1(9,FIX((SI_Long)92L),FIX((SI_Long)17L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)14L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4307L),Nil);
    add_character_description_1(9,FIX((SI_Long)93L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3351L),Nil);
    add_character_description_1(9,FIX((SI_Long)94L),FIX((SI_Long)13L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)95L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3351L),Nil);
    add_character_description_1(9,FIX((SI_Long)96L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)-5L),FIX((SI_Long)11L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)97L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3022L),Nil);
    add_character_description_1(9,FIX((SI_Long)98L),FIX((SI_Long)11L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2915L),Nil);
    add_character_description_1(9,FIX((SI_Long)99L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)-5L),FIX((SI_Long)12L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3076L),Nil);
    add_character_description_1(9,FIX((SI_Long)100L),FIX((SI_Long)19L),
	    FIX((SI_Long)1L),FIX((SI_Long)-5L),FIX((SI_Long)16L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4820L),Nil);
    add_character_description_1(9,FIX((SI_Long)101L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3022L),Nil);
    add_character_description_1(9,FIX((SI_Long)102L),FIX((SI_Long)14L),
	    FIX((SI_Long)1L),FIX((SI_Long)-2L),FIX((SI_Long)12L),
	    FIX((SI_Long)14L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3512L),Nil);
    add_character_description_1(9,FIX((SI_Long)103L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3202L),Nil);
    add_character_description_1(9,FIX((SI_Long)104L),FIX((SI_Long)20L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5005L),Nil);
    add_character_description_1(9,FIX((SI_Long)105L),FIX((SI_Long)20L),
	    FIX((SI_Long)1L),FIX((SI_Long)-2L),FIX((SI_Long)18L),
	    FIX((SI_Long)14L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)5149L),Nil);
    add_character_description_1(9,FIX((SI_Long)106L),FIX((SI_Long)13L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3393L),Nil);
    add_character_description_1(9,FIX((SI_Long)107L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)13L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4056L),Nil);
    add_character_description_1(9,FIX((SI_Long)108L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)9L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3058L),Nil);
    add_character_description_1(9,FIX((SI_Long)109L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3148L),Nil);
    add_character_description_1(9,FIX((SI_Long)110L),FIX((SI_Long)16L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)14L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4151L),Nil);
    add_character_description_1(9,FIX((SI_Long)111L),FIX((SI_Long)13L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3285L),Nil);
    add_character_description_1(9,FIX((SI_Long)113L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3357L),Nil);
    add_character_description_1(9,FIX((SI_Long)114L),FIX((SI_Long)14L),
	    FIX((SI_Long)0L),FIX((SI_Long)-5L),FIX((SI_Long)12L),
	    FIX((SI_Long)24L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3458L),Nil);
    add_character_description_1(9,FIX((SI_Long)115L),FIX((SI_Long)10L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)7L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)2503L),Nil);
    add_character_description_1(9,FIX((SI_Long)116L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3088L),Nil);
    add_character_description_1(9,FIX((SI_Long)117L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)10L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3022L),Nil);
    add_character_description_1(9,FIX((SI_Long)118L),FIX((SI_Long)5L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)2L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1368L),Nil);
    add_character_description_1(9,FIX((SI_Long)119L),FIX((SI_Long)7L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)6L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1702L),Nil);
    add_character_description_1(9,FIX((SI_Long)120L),FIX((SI_Long)5L),
	    FIX((SI_Long)0L),FIX((SI_Long)-5L),FIX((SI_Long)4L),
	    FIX((SI_Long)22L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)1356L),Nil);
    add_character_description_1(9,FIX((SI_Long)121L),FIX((SI_Long)17L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4468L),Nil);
    add_character_description_1(9,FIX((SI_Long)122L),FIX((SI_Long)18L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)16L),
	    FIX((SI_Long)12L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)4713L),Nil);
    add_character_description_1(9,FIX((SI_Long)123L),FIX((SI_Long)14L),
	    FIX((SI_Long)0L),FIX((SI_Long)0L),FIX((SI_Long)12L),
	    FIX((SI_Long)19L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3458L),Nil);
    add_character_description_1(9,FIX((SI_Long)124L),FIX((SI_Long)12L),
	    FIX((SI_Long)1L),FIX((SI_Long)0L),FIX((SI_Long)11L),
	    FIX((SI_Long)17L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3118L),Nil);
    add_character_description_1(9,FIX((SI_Long)126L),FIX((SI_Long)12L),
	    FIX((SI_Long)0L),FIX((SI_Long)-5L),FIX((SI_Long)12L),
	    FIX((SI_Long)22L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3076L),Nil);
    add_character_description_1(9,FIX((SI_Long)127L),FIX((SI_Long)13L),
	    FIX((SI_Long)1L),FIX((SI_Long)-2L),FIX((SI_Long)10L),
	    FIX((SI_Long)14L),
	    regenerate_optimized_constant(string_constant),
	    FIX((SI_Long)3351L),Nil);
}
