/* sqncs2.h -- Header File for sqncs2.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand;
extern Object Qcons;
extern Object Kelement_type;
extern Object Kerror;
extern Object Qfirst;
extern Object Qfixnum;
extern Object Qinteger;
extern Object Kkey;
extern Object Qlist;
extern Object Qmake_string;
extern Object Qmember;
extern Object Kname;
extern Object Knewest;
extern Object Qnot;
extern Object Qnull;
extern Object Qpackage_type;
extern Object Qquote;
extern Object Qsequence;
extern Object Qstring;
extern Object Qsymbol;
extern Object Ktest;
extern Object Qtime;
extern Object Qunsigned_byte;
extern Object Qvariable;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_for_nupec_after_authorization(Object);
extern Object add_grammar_rules_function(Object);
extern Object add_to_frame_note_particulars_list_if_necessary(Object,Object,Object);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_simple_vector(Object);
extern Object allocate_new_nonce(void);
extern Object allocate_new_nonce_internal(void);
extern Object already_is_a_named_ui_session_from_this_client(Object,Object);
extern Object analyze_authorized_packages(Object,Object,Object);
extern Object assq_function(Object,Object);
extern Object attribute_appears_more_than_once_ok_message(void);
extern Object attribute_appears_more_than_once_ok_message_1(Object);
extern Object authentificate_user_ldap(Object,Object);
extern Object authorization_incorrect_ok_message(void);
extern Object authorization_incorrect_when_already_authorized_ok_message(void);
extern Object authorization_missing_ok_message(void);
extern Object authorize_ab(void);
extern Object authorize_nupec(void);
extern Object authorized_modes_for_user(Object);
extern Object authorized_user_p(Object);
extern Object button_down_handler(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object c_nsleep(Object);
extern Object c_substatus_run_command_line(Object);
extern Object call_post_prominent_notification(Object,Object,Object,Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object change_slot_value(int,...);
extern Object character_cannot_start_token_ok_message(void);
extern Object check_code_space_2(void);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object check_ok_token_against_type(Object,Object);
extern Object check_password_setup_and_notify_user_if_necessary(void);
extern Object check_pulse_rate_limit(Object);
extern Object check_user_ldap(Object,Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object choose_keytab(void);
extern Object choose_pulse_rate_multiplier(void);
extern Object cleanup_for_kb_workspace(Object);
extern Object clear_optimized_constants(void);
extern Object clear_slot_pad(void);
extern Object clear_t2_nonce_hash_tree(Object);
extern Object close_telewindows_connection(Object);
extern Object coerce_token_to_lisp(Object);
extern Object collect_subclasses(Object);
extern Object color_match_p(Object);
extern Object compact_cons_pools_now(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compact_cons_pools_now_if_necessary(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compact_rpc_scratch_space(Object,Object,Object,Object);
extern Object compact_rpc_scratch_space_if_necessary(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object compile_authorized_packages_for_slot(int,...);
extern Object compile_id_or_whole_string_qm_for_slot(int,...);
extern Object compile_non_negative_integer_or_none_for_slot(int,...);
extern Object compile_number_of_processes_for_slot(int,...);
extern Object compile_permitted_mode_list_for_slot(int,...);
extern Object compile_products_qm_for_slot(int,...);
extern Object compile_symbol_list(Object);
extern Object compile_user_password_for_slot(int,...);
extern Object completely_shut_down_g2(int,...);
extern Object compute_process_initial_value_for_pad_for_ok_file_reader(void);
extern Object constant_queue_length(Object);
extern Object constant_queue_next(Object,Object);
extern Object constant_queue_push_right(Object,Object);
extern Object convert_input_to_universal_date(Object);
extern Object convert_md5_result_string_to_hex_string(Object,Object);
extern Object convert_to_gensym_pathname(Object,Object,Object);
extern Object convert_uuid_string_to_hex_string(Object,Object);
extern Object convert_valid_date_expressions_to_universal_dates(Object,Object,Object,Object,Object,Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_foreign_string_arg_if_appropriate(Object);
extern Object copy_list_using_gensym_conses_1(Object);
extern Object copy_list_using_ok_file_token_conses_1(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_tree_using_gensym_conses_1(Object);
extern Object copy_tree_using_ok_file_token_conses_1(Object);
extern Object copy_wide_string(Object);
extern Object could_not_open_stream_ok_message(void);
extern Object count_available_floating_telewindows(void);
extern Object count_available_floating_tw2s(void);
extern Object count_floating_telewindows_in_service(void);
extern Object count_floating_tw2_in_service(void);
extern Object data_for_valid_nonce(Object);
extern Object decode_universal_date(Object);
extern Object defragment_rpc_mapping_table(Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object delete_balanced_binary_tree_entry(Object,Object,Object,Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_ok_file_token_cons_1(Object,Object);
extern Object delete_ok_file_token_element_1(Object,Object);
extern Object digit_char_pw_function(Object,Object);
extern Object direct_structure_method(Object,Object);
extern Object disallow_ui_client_session(Object);
extern Object empty_kb_p(void);
extern Object encode_and_check_password_change_information(int,...);
extern Object encode_password_via_md5(Object,Object,Object);
extern Object enter_authorized_user(Object,Object,Object,Object,Object);
extern Object entry_started_while_still_inside_entry_ok_message(void);
extern Object eof_in_middle_of_statement_ok_message(void);
extern Object error_broke_rule_reading_ok_file(int,...);
extern Object eval_sequence_2(Object);
extern Object evaluation_sequence_aref(Object,Object);
extern Object extend_current_gensym_string(int,...);
extern Object file_attribute_not_initial_ok_message(void);
extern Object file_format_attribute_duplicated_ok_message(void);
extern Object file_format_value_not_an_integer_ok_message(void);
extern Object file_version_higher_than_image_version_ok_message_1(Object,Object);
extern Object finalize_indexed_md5_context(Object,Object);
extern Object formulate_ok_error_message(int,...);
extern Object fourth_element_of_statement_not_a_semicolon_ok_message(void);
extern Object frequently_typed_characters(Object,Object);
extern Object from_date_earlier_than_to_date_ok_message(void);
extern Object future_task_schedule_2(Object);
extern Object g2_check_authentification_ldap_in_c(Object,Object);
extern Object g2_check_user_ldap_in_c(Object,Object,Object);
extern Object g2_enterprise_p(void);
extern Object g2_equiv(Object,Object);
extern Object g2_ok_file_probe(void);
extern Object g2_ok_file_probe_for_write(void);
extern Object g2_ok_file_readable_p(void);
extern Object g2_ok_file_writeable_p(void);
extern Object g2_release_ui_client_session(Object);
extern Object g2_stream_close(Object);
extern Object g2_stream_open_for_input(Object);
extern Object g2_stream_read_into_buffer(Object,Object,Object);
extern Object g2_window_mode_is_valid_function(Object);
extern Object g2_window_user_is_valid_function(Object);
extern Object g2passwd_probe_file(void);
extern Object generate_float_vector(Object);
extern Object generate_large_random(void);
extern Object generate_simulation_of_printing_ok_frame(void);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object gensym_merge_pathnames_function(Object,Object,Object);
extern Object gensym_namestring(int,...);
extern Object gensym_probe_file(Object);
extern Object gensym_probe_file_for_truth_value(Object);
extern Object gensym_probe_file_for_write(Object);
extern Object get_appropriate_ok_pathname(int,...);
extern Object get_floater_license_if_available_for_window(Object);
extern Object get_g2_is_secure(Object);
extern Object get_g2_license_level(void);
extern Object get_gensym_window_parameter(Object,Object);
extern Object get_local_machine_ids_as_gensym_list(void);
extern Object get_lookup_slot_value(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_particulars_of_frame_note_from_component_particulars(Object,Object,Object);
extern Object get_property_value_function(int,...);
extern Object get_slot_init_form(int,...);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_telewindows_license_level(Object);
extern Object get_telewindows_product_name_from_level(Object);
extern Object get_universal_date(void);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object hash_nonce_with_password_hash(Object,Object);
extern Object header_for_file_entry_missing_ok_message(void);
extern Object hyphen_not_followed_by_another_hyphen_ok_message(void);
extern Object identify_all_savable_kb_workspaces(void);
extern Object illegal_attribute_value_ok_message(void);
extern Object illegal_attribute_value_ok_message_1(Object,Object);
extern Object illegal_character_in_string_ok_message(void);
extern Object implant_string_into_array(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object in_directory_of_names_p(Object,Object);
extern Object in_order_p(Object);
extern Object incorrect_authorization_for_package_ok_message(void);
extern Object inform_ui_client_interfaces_of_top_level_workspace_assignment_change(Object,Object,Object);
extern Object initial_g2_is_secure(Object);
extern Object initialize_for_asian_languages(void);
extern Object initialize_g2passwdexe(void);
extern Object initialize_g2passwdexe_is_executable_p(void);
extern Object inner_multiply(Object,Object);
extern Object integer_contains_non_digit_character_ok_message(void);
extern Object integer_too_long_ok_message(void);
extern Object intern_wide_string(int,...);
extern Object invoke_interlace_abstraction_if_offered(void);
extern Object issue_mgs_notifications(void);
extern Object lengthw(Object);
extern Object licence_on_this_machine_expires_today_ok_message(void);
extern Object license_on_this_machine_has_expired_ok_message(void);
extern Object limited_true_list_p(Object,Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object machine_id_missing_ok_message(void);
extern Object machine_model(void);
extern Object maintain_authorized_user(Object);
extern Object make_array_from_strings(Object,Object);
extern Object make_authorization_file_status_string(Object,Object);
extern Object make_constant_token(Object);
extern Object make_gensym_list_1(Object);
extern Object make_illegal_token(Object);
extern Object make_integer_ok_file_token(Object,Object);
extern Object make_integer_ok_file_token_from_text(Object);
extern Object make_list_token(Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_ok_file_token(Object,Object);
extern Object make_ok_file_token_1_1(Object,Object);
extern Object make_ok_file_token_list_1(Object);
extern Object make_permanent_list(Object);
extern Object make_permanent_ok_file_token_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_t2_nonce_data_structure_internal(void);
extern Object make_proprietary_now(void);
extern Object make_proprietary_now_1(Object,Object);
extern Object make_t2_nonce_data_1(void);
extern Object make_thread_array(Object);
extern Object make_ui_client_session_internal(void);
extern Object make_user_ok_entry(Object,Object,Object,Object);
extern Object map_scratch_space_blocks(Object,Object,Object,Object);
extern Object match_machine_id_for_this_machine_online(Object,Object);
extern Object memq_function(Object,Object);
extern Object mixin_class_attributes(Object,Object,Object);
extern Object modulo_string_hash(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_t2_nonce_hash_tree_entry(Object,Object,Object);
extern Object negotiate_telewindows_licensing(Object);
extern Object new_analyze_authorized_packages(Object,Object);
extern Object new_reformat_line_from_left(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object no_authorization_found_for_this_machine_multiple_entries_ok_message(void);
extern Object no_authorization_found_for_this_machine_one_entry_ok_message(void);
extern Object no_filename_provided_ok_message(void);
extern Object no_machine_authorization_in_file_ok_message(void);
extern Object no_user_modes_specified_ok_message(void);
extern Object nonce_is_not_in_a_valid_state(Object);
extern Object normalize_kb_workspace(Object,Object);
extern Object normalized_string_equal(int,...);
extern Object not_permitted_to_connect_to_development_g2_ok_message(void);
extern Object note_change_to_block_1(Object,Object);
extern Object note_that_session_has_been_successfully_logged_in(Object);
extern Object note_that_session_has_logged_out(Object);
extern Object notify_user(int,...);
extern Object notify_user_at_console(int,...);
extern Object nstring_upcasew(Object);
extern Object number_of_floating_telewindows_limit_exceeded_ok_message(void);
extern Object obtain_floating_telewindows_for_workstation_if_possible(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object obtain_text_string(Object);
extern Object ok_file_is_incompatible_with_image(Object);
extern Object ok_file_sanity_check(Object);
extern Object ok_file_token_cons_1(Object,Object);
extern Object ok_file_token_cons_memory_usage(void);
extern Object ok_file_token_list_2(Object,Object);
extern Object ok_file_token_list_3(Object,Object,Object);
extern Object ok_file_token_list_4(Object,Object,Object,Object);
extern Object ok_file_token_list_trace_hook(Object);
extern Object ok_file_token_structure_memory_usage(void);
extern Object optimize_telewindows_z_layer_model(void);
extern Object outstanding_ok_file_token_conses(void);
extern Object outstanding_ok_file_token_count(void);
extern Object outstanding_t2_nonce_data_count(void);
extern Object parent(Object);
extern Object password_still_valid_qm(Object);
extern Object pointer_to_first_string_in_pool_group(void);
extern Object post_prominent_notification(int,...);
extern Object print_decoded_date(Object,Object,Object);
extern Object print_frame(int,...);
extern Object print_list_without_message(Object);
extern Object print_message_with_list(Object,Object);
extern Object print_universal_date_as_decoded_date(Object);
extern Object procedure_recursive(Object,Object,Object,Object,Object,Object);
extern Object process_attribute_of_entity(Object,Object,Object);
extern Object process_slot_text_for_customer(Object);
extern Object propagate_changes_in_authorization_to_logged_in_users(Object,Object);
extern Object proprietary_mode_specified_ok_message(void);
extern Object push_optimized_constant(Object);
extern Object put_authorized_kb_packages(Object,Object,Object);
extern Object put_authorized_products(Object,Object,Object);
extern Object put_code_1(Object,Object,Object);
extern Object put_code_2(Object,Object,Object);
extern Object put_code_3(Object,Object,Object);
extern Object put_code_4(Object,Object,Object);
extern Object put_code_5(Object,Object,Object);
extern Object put_expiration_date_qm(Object,Object,Object);
extern Object put_expiration_date_where_slot_is_absent(Object,Object);
extern Object put_machine_id(Object,Object,Object);
extern Object put_make_g2_secure_qm(Object,Object,Object);
extern Object put_maximum_number_of_concurrent_floating_telewindows_allowed(Object,Object,Object);
extern Object put_number_of_processes_authorized(Object,Object,Object);
extern Object put_ok_slot_coordinator(Object,Object,Object);
extern Object put_permitted_user_modes(Object,Object,Object);
extern Object put_proprietary_package(Object,Object,Object);
extern Object put_user_password(Object,Object,Object);
extern Object reached_eof_while_inside_an_entry_ok_message(void);
extern Object read_char_from_ok_file(void);
extern Object read_g2_ok_file_entity(void);
extern Object read_g2_ok_file_entity_just_for_users(void);
extern Object read_integer_from_ok_file(Object);
extern Object read_list_from_ok_file(void);
extern Object read_machine_ok_file_entry(void);
extern Object read_ok_file(int,...);
extern Object read_ok_file_just_for_updating_user_data(Object);
extern Object read_statement_from_ok_file(void);
extern Object read_string_from_ok_file(void);
extern Object read_symbol_from_ok_file(Object);
extern Object read_token_from_ok_file(void);
extern Object read_user_ok_file_entry(void);
extern Object read_user_ok_file_entry_for_updates(void);
extern Object reclaim_contour_of_ok_file_tokens(void);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_pathname(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_gensym_tree_with_text_strings(Object);
extern Object reclaim_managed_simple_vector(Object);
extern Object reclaim_nonce(Object);
extern Object reclaim_ok_file_token_1(Object);
extern Object reclaim_ok_file_token_cons_1(Object);
extern Object reclaim_ok_file_token_list_1(Object);
extern Object reclaim_ok_file_token_list_star_1(Object);
extern Object reclaim_ok_file_token_tree_1(Object);
extern Object reclaim_ok_file_value(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_simple_gensym_string(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_t2_nonce_data_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_wide_string(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object redraw_solid_rectangles_without_overlap(Object);
extern Object redraw_solid_rectangles_without_overlap_1(Object);
extern Object reformat_line_from_left(Object);
extern Object regenerate_optimized_constant(Object);
extern Object remove_authorized_user(Object);
extern Object remove_gaps_from_cons_pool(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object replace_format_using_equivalent_font(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_ok_file_token_cons_pool(void);
extern Object replenish_ok_file_token_list_pool(Object);
extern Object reposition_cons_pool_fragments(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object reverse_list_search(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object revert_rpc_bounds_now(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object run_al_for_recursive_descent(Object,Object);
extern Object run_chinese_for_recursive_descent(Object,Object);
extern Object run_embedded_option_for_recursive_descent(Object,Object);
extern Object run_ent_for_recursive_descent(Object,Object);
extern Object run_g1_for_recursive_descent(Object,Object);
extern Object run_gfi_for_recursive_descent(Object,Object);
extern Object run_gsi_for_recursive_descent(Object,Object);
extern Object run_gspan_for_recursive_descent(Object,Object);
extern Object run_icp_for_recursive_descent(Object,Object);
extern Object run_japanese_for_recursive_descent(Object,Object);
extern Object run_jl_for_recursive_descent(Object,Object);
extern Object run_jp_for_recursive_descent(Object,Object);
extern Object run_kfep_for_recursive_descent(Object,Object);
extern Object run_korean_for_recursive_descent(Object,Object);
extern Object run_nupec_for_recursive_descent(Object,Object);
extern Object run_restricted_use_option_for_recursive_descent(Object,Object);
extern Object run_runtime_option_for_recursive_descent(Object,Object);
extern Object sanity_check_on_initial_characters_of_file_ok_message(void);
extern Object scan_rpc_scratch_space(Object,Object,Object,Object);
extern Object schedule_tw_modernization_tasks_if_necessary(void);
extern Object session_has_successfully_logged_in_p(Object);
extern Object session_licensing_level_compatible_with_g2_level(Object);
extern Object set_authorizing_ok_pathname(Object);
extern Object set_balanced_binary_tree_entry(Object,Object,Object,Object,Object,Object,Object);
extern Object set_first_string_in_pool_group(Object);
extern Object set_flag_permitting_free_floating_authorization(void);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_ui_client_session_license_level(Object,Object);
extern Object set_ui_client_session_status(Object,Object);
extern Object set_user_mode_validity_of_g2_window(Object,Object);
extern Object set_user_password(Object,Object,Object);
extern Object set_user_validity_of_g2_window(Object,Object);
extern Object set_validity_of_user_password(Object,Object);
extern Object shunned_machine_id_ok_message(void);
extern Object shunned_machine_id_string_p(Object);
extern Object skip_ok_statements_until_end_of_entry(Object);
extern Object some_floating_telewindows_available_p(void);
extern Object some_floating_tw2_available_p(void);
extern Object sort_scheduled_priorities(Object);
extern Object start_adaptive_font_fallback(void);
extern Object string_eq_w(Object,Object);
extern Object string_equalw(Object,Object);
extern Object string_too_long_ok_message(void);
extern Object stringw(Object);
extern Object sxhashw(Object);
extern Object symbol_name_text_string(Object);
extern Object symbol_token_match(Object,Object);
extern Object symbol_too_long_ok_message(void);
extern Object syntax_error_in_attribute_value_ok_message(void);
extern Object syntax_error_in_attribute_value_ok_message_1(Object,Object,Object);
extern Object system_version_greater_p(Object,Object);
extern Object t2_nonce_data_structure_memory_usage(void);
extern Object telewindows_license_level_from_product(Object);
extern Object text_string_hash_with_modulus(Object,Object);
extern Object text_string_length(Object);
extern Object text_string_of_pad_for_ok_file_reader(Object);
extern Object text_string_p(Object);
extern Object text_string_substring(Object,Object,Object);
extern Object text_string_trim(Object,Object);
extern Object tformat(int,...);
extern Object tformat_text_string(int,...);
extern Object token_kind_is(Object,Object);
extern Object too_many_elements_in_list_ok_message(void);
extern Object tprin(Object,Object);
extern Object transform_type_specification_2(Object,Object,Object);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_character(Object);
extern Object twrite_fixnum(Object);
extern Object twrite_general_string(Object);
extern Object twrite_ok_token(Object,Object);
extern Object twrite_standard_secure_g2_notification_header(void);
extern Object twrite_wide_character(Object);
extern Object ui_client_session_for_nonce(Object);
extern Object ui_client_session_is_not_unauthorized_p(Object);
extern Object ui_client_session_is_self_authorized_p(Object);
extern Object ui_client_session_license_level_qm_function(Object);
extern Object ui_client_session_nonce_function(Object);
extern Object ui_client_session_status_function(Object);
extern Object ui_client_session_valid_p(Object);
extern Object undefined_entry_type_ok_message(void);
extern Object undefined_file_attribute_ok_message(void);
extern Object unknown_problem_parsing_entry_ok_message(void);
extern Object unknown_problem_parsing_file_ok_message(void);
extern Object unknown_problem_parsing_statement_ok_message(void);
extern Object unread_char_from_ok_file(Object);
extern Object unrecognized_attribute_ok_message(void);
extern Object unrecognized_attribute_ok_message_1(Object);
extern Object update_frames_needing_icp_callback(Object,Object);
extern Object update_indexed_md5_context(Object,Object);
extern Object update_module_related_frame_notes_for_all_workspaces(int,...);
extern Object update_object_pool_meters_list(Object);
extern Object update_ok_user_data(void);
extern Object update_representations_of_slot_value(int,...);
extern Object users_authorized_password(Object);
extern Object valid_back_door_p(Object);
extern Object valid_universal_date_elements_p(Object,Object,Object);
extern Object valid_user_and_password_p(Object,Object);
extern Object validate_as_possible_user_mode(Object);
extern Object validate_user_and_password(int,...);
extern Object validate_user_mode_for_user(Object,Object);
extern Object validity_of_users_password(Object);
extern Object warn_upon_start_or_resume(void);
extern Object warning_while_reading_ok_file(int,...);
extern Object wide_character_member(Object,Object);
extern Object write_authorization_interval_qm_from_slot(Object,Object);
extern Object write_authorized_packages_from_slot(Object,Object);
extern Object write_id_or_whole_string_qm_from_slot(Object,Object);
extern Object write_non_negative_integer_or_none_from_slot(Object,Object);
extern Object write_number_of_processes_from_slot(Object,Object);
extern Object write_number_or_unlimited_from_slot(Object,Object);
extern Object write_pad_slot(Object);
extern Object write_part_description_to_stream(Object,Object);
extern Object write_part_description_value_to_stream(Object,Object,Object);
extern Object write_permitted_mode_list_from_slot(Object,Object);
extern Object write_products_qm_from_slot(Object,Object);
extern Object write_proprietary_package_from_slot(Object,Object);
extern Object write_symbol_list(int,...);
extern Object write_text_string_to_stream(Object,Object);
extern Object write_user_password_from_slot(Object,Object);
extern Object wrong_label_on_end_statement_ok_message(void);
extern Object wrong_label_on_file_level_end_statement_ok_message(void);
extern Object wrong_number_of_authorization_codes_ok_message(void);

#else

extern Object add_class_to_environment();
extern Object add_grammar_rules_for_nupec_after_authorization();
extern Object add_grammar_rules_function();
extern Object add_to_frame_note_particulars_list_if_necessary();
extern Object add_virtual_attribute();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_simple_vector();
extern Object allocate_new_nonce();
extern Object allocate_new_nonce_internal();
extern Object already_is_a_named_ui_session_from_this_client();
extern Object analyze_authorized_packages();
extern Object assq_function();
extern Object attribute_appears_more_than_once_ok_message();
extern Object attribute_appears_more_than_once_ok_message_1();
extern Object authentificate_user_ldap();
extern Object authorization_incorrect_ok_message();
extern Object authorization_incorrect_when_already_authorized_ok_message();
extern Object authorization_missing_ok_message();
extern Object authorize_ab();
extern Object authorize_nupec();
extern Object authorized_modes_for_user();
extern Object authorized_user_p();
extern Object button_down_handler();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object c_nsleep();
extern Object c_substatus_run_command_line();
extern Object call_post_prominent_notification();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object change_slot_value();
extern Object character_cannot_start_token_ok_message();
extern Object check_code_space_2();
extern Object check_if_superior_classes_are_defined();
extern Object check_ok_token_against_type();
extern Object check_password_setup_and_notify_user_if_necessary();
extern Object check_pulse_rate_limit();
extern Object check_user_ldap();
extern Object chestnut_modf_function();
extern Object choose_keytab();
extern Object choose_pulse_rate_multiplier();
extern Object cleanup_for_kb_workspace();
extern Object clear_optimized_constants();
extern Object clear_slot_pad();
extern Object clear_t2_nonce_hash_tree();
extern Object close_telewindows_connection();
extern Object coerce_token_to_lisp();
extern Object collect_subclasses();
extern Object color_match_p();
extern Object compact_cons_pools_now();
extern Object compact_cons_pools_now_if_necessary();
extern Object compact_rpc_scratch_space();
extern Object compact_rpc_scratch_space_if_necessary();
extern Object compile_authorized_packages_for_slot();
extern Object compile_id_or_whole_string_qm_for_slot();
extern Object compile_non_negative_integer_or_none_for_slot();
extern Object compile_number_of_processes_for_slot();
extern Object compile_permitted_mode_list_for_slot();
extern Object compile_products_qm_for_slot();
extern Object compile_symbol_list();
extern Object compile_user_password_for_slot();
extern Object completely_shut_down_g2();
extern Object compute_process_initial_value_for_pad_for_ok_file_reader();
extern Object constant_queue_length();
extern Object constant_queue_next();
extern Object constant_queue_push_right();
extern Object convert_input_to_universal_date();
extern Object convert_md5_result_string_to_hex_string();
extern Object convert_to_gensym_pathname();
extern Object convert_uuid_string_to_hex_string();
extern Object convert_valid_date_expressions_to_universal_dates();
extern Object copy_constant_wide_string_given_length();
extern Object copy_foreign_string_arg_if_appropriate();
extern Object copy_list_using_gensym_conses_1();
extern Object copy_list_using_ok_file_token_conses_1();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_tree_using_gensym_conses_1();
extern Object copy_tree_using_ok_file_token_conses_1();
extern Object copy_wide_string();
extern Object could_not_open_stream_ok_message();
extern Object count_available_floating_telewindows();
extern Object count_available_floating_tw2s();
extern Object count_floating_telewindows_in_service();
extern Object count_floating_tw2_in_service();
extern Object data_for_valid_nonce();
extern Object decode_universal_date();
extern Object defragment_rpc_mapping_table();
extern Object delete_balanced_binary_tree_entry();
extern Object delete_frame_note_if_any();
extern Object delete_gensym_element_1();
extern Object delete_ok_file_token_cons_1();
extern Object delete_ok_file_token_element_1();
extern Object digit_char_pw_function();
extern Object direct_structure_method();
extern Object disallow_ui_client_session();
extern Object empty_kb_p();
extern Object encode_and_check_password_change_information();
extern Object encode_password_via_md5();
extern Object enter_authorized_user();
extern Object entry_started_while_still_inside_entry_ok_message();
extern Object eof_in_middle_of_statement_ok_message();
extern Object error_broke_rule_reading_ok_file();
extern Object eval_sequence_2();
extern Object evaluation_sequence_aref();
extern Object extend_current_gensym_string();
extern Object file_attribute_not_initial_ok_message();
extern Object file_format_attribute_duplicated_ok_message();
extern Object file_format_value_not_an_integer_ok_message();
extern Object file_version_higher_than_image_version_ok_message_1();
extern Object finalize_indexed_md5_context();
extern Object formulate_ok_error_message();
extern Object fourth_element_of_statement_not_a_semicolon_ok_message();
extern Object frequently_typed_characters();
extern Object from_date_earlier_than_to_date_ok_message();
extern Object future_task_schedule_2();
extern Object g2_check_authentification_ldap_in_c();
extern Object g2_check_user_ldap_in_c();
extern Object g2_enterprise_p();
extern Object g2_equiv();
extern Object g2_ok_file_probe();
extern Object g2_ok_file_probe_for_write();
extern Object g2_ok_file_readable_p();
extern Object g2_ok_file_writeable_p();
extern Object g2_release_ui_client_session();
extern Object g2_stream_close();
extern Object g2_stream_open_for_input();
extern Object g2_stream_read_into_buffer();
extern Object g2_window_mode_is_valid_function();
extern Object g2_window_user_is_valid_function();
extern Object g2passwd_probe_file();
extern Object generate_float_vector();
extern Object generate_large_random();
extern Object generate_simulation_of_printing_ok_frame();
extern Object gensym_cons_1();
extern Object gensym_list_3();
extern Object gensym_merge_pathnames_function();
extern Object gensym_namestring();
extern Object gensym_probe_file();
extern Object gensym_probe_file_for_truth_value();
extern Object gensym_probe_file_for_write();
extern Object get_appropriate_ok_pathname();
extern Object get_floater_license_if_available_for_window();
extern Object get_g2_is_secure();
extern Object get_g2_license_level();
extern Object get_gensym_window_parameter();
extern Object get_local_machine_ids_as_gensym_list();
extern Object get_lookup_slot_value();
extern Object get_lookup_slot_value_given_default();
extern Object get_particulars_of_frame_note_from_component_particulars();
extern Object get_property_value_function();
extern Object get_slot_init_form();
extern Object get_slot_value_function();
extern Object get_symbol_properties_function();
extern Object get_telewindows_license_level();
extern Object get_telewindows_product_name_from_level();
extern Object get_universal_date();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object hash_nonce_with_password_hash();
extern Object header_for_file_entry_missing_ok_message();
extern Object hyphen_not_followed_by_another_hyphen_ok_message();
extern Object identify_all_savable_kb_workspaces();
extern Object illegal_attribute_value_ok_message();
extern Object illegal_attribute_value_ok_message_1();
extern Object illegal_character_in_string_ok_message();
extern Object implant_string_into_array();
extern Object in_directory_of_names_p();
extern Object in_order_p();
extern Object incorrect_authorization_for_package_ok_message();
extern Object inform_ui_client_interfaces_of_top_level_workspace_assignment_change();
extern Object initial_g2_is_secure();
extern Object initialize_for_asian_languages();
extern Object initialize_g2passwdexe();
extern Object initialize_g2passwdexe_is_executable_p();
extern Object inner_multiply();
extern Object integer_contains_non_digit_character_ok_message();
extern Object integer_too_long_ok_message();
extern Object intern_wide_string();
extern Object invoke_interlace_abstraction_if_offered();
extern Object issue_mgs_notifications();
extern Object lengthw();
extern Object licence_on_this_machine_expires_today_ok_message();
extern Object license_on_this_machine_has_expired_ok_message();
extern Object limited_true_list_p();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object machine_id_missing_ok_message();
extern Object machine_model();
extern Object maintain_authorized_user();
extern Object make_array_from_strings();
extern Object make_authorization_file_status_string();
extern Object make_constant_token();
extern Object make_gensym_list_1();
extern Object make_illegal_token();
extern Object make_integer_ok_file_token();
extern Object make_integer_ok_file_token_from_text();
extern Object make_list_token();
extern Object make_named_dynamic_extent_description();
extern Object make_ok_file_token();
extern Object make_ok_file_token_1_1();
extern Object make_ok_file_token_list_1();
extern Object make_permanent_list();
extern Object make_permanent_ok_file_token_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_t2_nonce_data_structure_internal();
extern Object make_proprietary_now();
extern Object make_proprietary_now_1();
extern Object make_t2_nonce_data_1();
extern Object make_thread_array();
extern Object make_ui_client_session_internal();
extern Object make_user_ok_entry();
extern Object map_scratch_space_blocks();
extern Object match_machine_id_for_this_machine_online();
extern Object memq_function();
extern Object mixin_class_attributes();
extern Object modulo_string_hash();
extern Object mutate_global_property();
extern Object mutate_t2_nonce_hash_tree_entry();
extern Object negotiate_telewindows_licensing();
extern Object new_analyze_authorized_packages();
extern Object new_reformat_line_from_left();
extern Object no_authorization_found_for_this_machine_multiple_entries_ok_message();
extern Object no_authorization_found_for_this_machine_one_entry_ok_message();
extern Object no_filename_provided_ok_message();
extern Object no_machine_authorization_in_file_ok_message();
extern Object no_user_modes_specified_ok_message();
extern Object nonce_is_not_in_a_valid_state();
extern Object normalize_kb_workspace();
extern Object normalized_string_equal();
extern Object not_permitted_to_connect_to_development_g2_ok_message();
extern Object note_change_to_block_1();
extern Object note_that_session_has_been_successfully_logged_in();
extern Object note_that_session_has_logged_out();
extern Object notify_user();
extern Object notify_user_at_console();
extern Object nstring_upcasew();
extern Object number_of_floating_telewindows_limit_exceeded_ok_message();
extern Object obtain_floating_telewindows_for_workstation_if_possible();
extern Object obtain_simple_gensym_string();
extern Object obtain_text_string();
extern Object ok_file_is_incompatible_with_image();
extern Object ok_file_sanity_check();
extern Object ok_file_token_cons_1();
extern Object ok_file_token_cons_memory_usage();
extern Object ok_file_token_list_2();
extern Object ok_file_token_list_3();
extern Object ok_file_token_list_4();
extern Object ok_file_token_list_trace_hook();
extern Object ok_file_token_structure_memory_usage();
extern Object optimize_telewindows_z_layer_model();
extern Object outstanding_ok_file_token_conses();
extern Object outstanding_ok_file_token_count();
extern Object outstanding_t2_nonce_data_count();
extern Object parent();
extern Object password_still_valid_qm();
extern Object pointer_to_first_string_in_pool_group();
extern Object post_prominent_notification();
extern Object print_decoded_date();
extern Object print_frame();
extern Object print_list_without_message();
extern Object print_message_with_list();
extern Object print_universal_date_as_decoded_date();
extern Object procedure_recursive();
extern Object process_attribute_of_entity();
extern Object process_slot_text_for_customer();
extern Object propagate_changes_in_authorization_to_logged_in_users();
extern Object proprietary_mode_specified_ok_message();
extern Object push_optimized_constant();
extern Object put_authorized_kb_packages();
extern Object put_authorized_products();
extern Object put_code_1();
extern Object put_code_2();
extern Object put_code_3();
extern Object put_code_4();
extern Object put_code_5();
extern Object put_expiration_date_qm();
extern Object put_expiration_date_where_slot_is_absent();
extern Object put_machine_id();
extern Object put_make_g2_secure_qm();
extern Object put_maximum_number_of_concurrent_floating_telewindows_allowed();
extern Object put_number_of_processes_authorized();
extern Object put_ok_slot_coordinator();
extern Object put_permitted_user_modes();
extern Object put_proprietary_package();
extern Object put_user_password();
extern Object reached_eof_while_inside_an_entry_ok_message();
extern Object read_char_from_ok_file();
extern Object read_g2_ok_file_entity();
extern Object read_g2_ok_file_entity_just_for_users();
extern Object read_integer_from_ok_file();
extern Object read_list_from_ok_file();
extern Object read_machine_ok_file_entry();
extern Object read_ok_file();
extern Object read_ok_file_just_for_updating_user_data();
extern Object read_statement_from_ok_file();
extern Object read_string_from_ok_file();
extern Object read_symbol_from_ok_file();
extern Object read_token_from_ok_file();
extern Object read_user_ok_file_entry();
extern Object read_user_ok_file_entry_for_updates();
extern Object reclaim_contour_of_ok_file_tokens();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_pathname();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_gensym_tree_with_text_strings();
extern Object reclaim_managed_simple_vector();
extern Object reclaim_nonce();
extern Object reclaim_ok_file_token_1();
extern Object reclaim_ok_file_token_cons_1();
extern Object reclaim_ok_file_token_list_1();
extern Object reclaim_ok_file_token_list_star_1();
extern Object reclaim_ok_file_token_tree_1();
extern Object reclaim_ok_file_value();
extern Object reclaim_schedule_task_args();
extern Object reclaim_simple_gensym_string();
extern Object reclaim_slot_value();
extern Object reclaim_t2_nonce_data_1();
extern Object reclaim_text_string();
extern Object reclaim_wide_string();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object redraw_solid_rectangles_without_overlap();
extern Object redraw_solid_rectangles_without_overlap_1();
extern Object reformat_line_from_left();
extern Object regenerate_optimized_constant();
extern Object remove_authorized_user();
extern Object remove_gaps_from_cons_pool();
extern Object replace_format_using_equivalent_font();
extern Object replenish_lookup_cons_pool();
extern Object replenish_ok_file_token_cons_pool();
extern Object replenish_ok_file_token_list_pool();
extern Object reposition_cons_pool_fragments();
extern Object reverse_list_search();
extern Object revert_rpc_bounds_now();
extern Object run_al_for_recursive_descent();
extern Object run_chinese_for_recursive_descent();
extern Object run_embedded_option_for_recursive_descent();
extern Object run_ent_for_recursive_descent();
extern Object run_g1_for_recursive_descent();
extern Object run_gfi_for_recursive_descent();
extern Object run_gsi_for_recursive_descent();
extern Object run_gspan_for_recursive_descent();
extern Object run_icp_for_recursive_descent();
extern Object run_japanese_for_recursive_descent();
extern Object run_jl_for_recursive_descent();
extern Object run_jp_for_recursive_descent();
extern Object run_kfep_for_recursive_descent();
extern Object run_korean_for_recursive_descent();
extern Object run_nupec_for_recursive_descent();
extern Object run_restricted_use_option_for_recursive_descent();
extern Object run_runtime_option_for_recursive_descent();
extern Object sanity_check_on_initial_characters_of_file_ok_message();
extern Object scan_rpc_scratch_space();
extern Object schedule_tw_modernization_tasks_if_necessary();
extern Object session_has_successfully_logged_in_p();
extern Object session_licensing_level_compatible_with_g2_level();
extern Object set_authorizing_ok_pathname();
extern Object set_balanced_binary_tree_entry();
extern Object set_first_string_in_pool_group();
extern Object set_flag_permitting_free_floating_authorization();
extern Object set_lookup_slot_value_1();
extern Object set_property_value_function();
extern Object set_ui_client_session_license_level();
extern Object set_ui_client_session_status();
extern Object set_user_mode_validity_of_g2_window();
extern Object set_user_password();
extern Object set_user_validity_of_g2_window();
extern Object set_validity_of_user_password();
extern Object shunned_machine_id_ok_message();
extern Object shunned_machine_id_string_p();
extern Object skip_ok_statements_until_end_of_entry();
extern Object some_floating_telewindows_available_p();
extern Object some_floating_tw2_available_p();
extern Object sort_scheduled_priorities();
extern Object start_adaptive_font_fallback();
extern Object string_eq_w();
extern Object string_equalw();
extern Object string_too_long_ok_message();
extern Object stringw();
extern Object sxhashw();
extern Object symbol_name_text_string();
extern Object symbol_token_match();
extern Object symbol_too_long_ok_message();
extern Object syntax_error_in_attribute_value_ok_message();
extern Object syntax_error_in_attribute_value_ok_message_1();
extern Object system_version_greater_p();
extern Object t2_nonce_data_structure_memory_usage();
extern Object telewindows_license_level_from_product();
extern Object text_string_hash_with_modulus();
extern Object text_string_length();
extern Object text_string_of_pad_for_ok_file_reader();
extern Object text_string_p();
extern Object text_string_substring();
extern Object text_string_trim();
extern Object tformat();
extern Object tformat_text_string();
extern Object token_kind_is();
extern Object too_many_elements_in_list_ok_message();
extern Object tprin();
extern Object transform_type_specification_2();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_character();
extern Object twrite_fixnum();
extern Object twrite_general_string();
extern Object twrite_ok_token();
extern Object twrite_standard_secure_g2_notification_header();
extern Object twrite_wide_character();
extern Object ui_client_session_for_nonce();
extern Object ui_client_session_is_not_unauthorized_p();
extern Object ui_client_session_is_self_authorized_p();
extern Object ui_client_session_license_level_qm_function();
extern Object ui_client_session_nonce_function();
extern Object ui_client_session_status_function();
extern Object ui_client_session_valid_p();
extern Object undefined_entry_type_ok_message();
extern Object undefined_file_attribute_ok_message();
extern Object unknown_problem_parsing_entry_ok_message();
extern Object unknown_problem_parsing_file_ok_message();
extern Object unknown_problem_parsing_statement_ok_message();
extern Object unread_char_from_ok_file();
extern Object unrecognized_attribute_ok_message();
extern Object unrecognized_attribute_ok_message_1();
extern Object update_frames_needing_icp_callback();
extern Object update_indexed_md5_context();
extern Object update_module_related_frame_notes_for_all_workspaces();
extern Object update_object_pool_meters_list();
extern Object update_ok_user_data();
extern Object update_representations_of_slot_value();
extern Object users_authorized_password();
extern Object valid_back_door_p();
extern Object valid_universal_date_elements_p();
extern Object valid_user_and_password_p();
extern Object validate_as_possible_user_mode();
extern Object validate_user_and_password();
extern Object validate_user_mode_for_user();
extern Object validity_of_users_password();
extern Object warn_upon_start_or_resume();
extern Object warning_while_reading_ok_file();
extern Object wide_character_member();
extern Object write_authorization_interval_qm_from_slot();
extern Object write_authorized_packages_from_slot();
extern Object write_id_or_whole_string_qm_from_slot();
extern Object write_non_negative_integer_or_none_from_slot();
extern Object write_number_of_processes_from_slot();
extern Object write_number_or_unlimited_from_slot();
extern Object write_pad_slot();
extern Object write_part_description_to_stream();
extern Object write_part_description_value_to_stream();
extern Object write_permitted_mode_list_from_slot();
extern Object write_products_qm_from_slot();
extern Object write_proprietary_package_from_slot();
extern Object write_symbol_list();
extern Object write_text_string_to_stream();
extern Object write_user_password_from_slot();
extern Object wrong_label_on_end_statement_ok_message();
extern Object wrong_label_on_file_level_end_statement_ok_message();
extern Object wrong_number_of_authorization_codes_ok_message();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
#define Alphabetic_character_for_g2_ok_file FIX((SI_Long)9L)
DECLARE_VARIABLE_WITH_SYMBOL(Alternate_chaining_queue, Qalternate_chaining_queue);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_products_of_this_machine, Qauthorized_products_of_this_machine);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_user_class_description, Qauthorized_user_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_user_records_of_g2_ok_file, Qauthorized_user_records_of_g2_ok_file);
DECLARE_VARIABLE_WITH_SYMBOL(Authorized_users_list, Qauthorized_users_list);
DECLARE_VARIABLE_WITH_SYMBOL(Authorizing_ok_pathname, Qauthorizing_ok_pathname);
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_gensym_conses, Qavailable_gensym_conses);
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_ok_file_token_conses, Qavailable_ok_file_token_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_ok_file_token_conses_tail, Qavailable_ok_file_token_conses_tail);
extern Object Available_ok_file_token_conses_tail_vector;
extern Object Available_ok_file_token_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Buffer_index_of_ok_file_reader, Qbuffer_index_of_ok_file_reader);
DECLARE_VARIABLE_WITH_SYMBOL(Buffer_length_of_ok_file_reader, Qbuffer_length_of_ok_file_reader);
DECLARE_VARIABLE_WITH_SYMBOL(Buffer_of_ok_file_reader, Qbuffer_of_ok_file_reader);
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Cached_machine_id_qm, Qcached_machine_id_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_matching_machine_id_qm, Qcached_matching_machine_id_qm);
extern Object Can_create_additional_users_and_then_save_ok_file_message_1;
extern Object Can_create_additional_users_and_then_save_ok_file_message_2;
extern Object Can_create_additional_users_and_then_save_ok_file_message_format_control_string;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_ok_file_tokens, Qchain_of_available_ok_file_tokens);
extern Object Chain_of_available_ok_file_tokens_vector;
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_t2_nonce_datas, Qchain_of_available_t2_nonce_datas);
extern Object Chain_of_available_t2_nonce_datas_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chaining_refresh_list, Qchaining_refresh_list);
DECLARE_VARIABLE_WITH_SYMBOL(Chaining_refresh_version, Qchaining_refresh_version);
extern Object Character_table_for_g2_ok_file;
DECLARE_VARIABLE_WITH_SYMBOL(Characters_in_buffer_of_ok_file_reader_qm, Qcharacters_in_buffer_of_ok_file_reader_qm);
extern Object Class_description_gkbprop;
#define Close_paren_character_for_g2_ok_file FIX((SI_Long)4L)
#define Colon_character_for_g2_ok_file FIX((SI_Long)5L)
DECLARE_VARIABLE_WITH_SYMBOL(Color_code_differences, Qcolor_code_differences);
extern Object Command_line_arguments;
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Consider_asian_language_initializations_qm, Qconsider_asian_language_initializations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Contour_of_ok_file_tokens, Qcontour_of_ok_file_tokens);
DECLARE_VARIABLE_WITH_SYMBOL(Control_sequence_record, Qcontrol_sequence_record);
DECLARE_VARIABLE_WITH_SYMBOL(Convert_file_strings_to_uppercase_p, Qconvert_file_strings_to_uppercase_p);
#define Cr_character_for_g2_ok_file FIX((SI_Long)10L)
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Ctlc_cons_count, Qctlc_cons_count);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_component_particulars, Qcurrent_computation_component_particulars);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_machine_ids_of_g2_ok_file_qm, Qcurrent_machine_ids_of_g2_ok_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Daily_countdown, Qdaily_countdown);
#define Dash_character_for_g2_ok_file FIX((SI_Long)7L)
DECLARE_VARIABLE_WITH_SYMBOL(Default_format_structure, Qdefault_format_structure);
#define Development_lic_level FIX((SI_Long)3L)
#define Digit_character_for_g2_ok_file FIX((SI_Long)8L)
#define Embedded_lic_level FIX((SI_Long)0L)
extern Object End_of_recovery_list;
DECLARE_VARIABLE_WITH_SYMBOL(Entity_class_description, Qentity_class_description);
#define Eof_character_for_g2_ok_file FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Error_of_ok_file_reader_qm, Qerror_of_ok_file_reader_qm);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
extern Object Expiration_date_for_display_in_title;
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Feature_blt, Qfeature_blt);
DECLARE_VARIABLE_WITH_SYMBOL(File_format_version_of_g2_ok_file_qm, Qfile_format_version_of_g2_ok_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
#define Floating_lic_level FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Floating_telewindows_limit, Qfloating_telewindows_limit);
DECLARE_VARIABLE_WITH_SYMBOL(Floating_tw2_limit, Qfloating_tw2_limit);
DECLARE_VARIABLE_WITH_SYMBOL(Font_feature_list, Qfont_feature_list);
extern Object Format_structure_description;
extern Object Fp_mutate_t2_nonce_hash_tree_entry;
DECLARE_VARIABLE_WITH_SYMBOL(Free_floater_allowed_qm, Qfree_floater_allowed_qm);
extern Object G2_development_option;
extern Object G2_embedded_option;
extern Object G2_not_authorized_because_cannot_register_process_license_message;
extern Object G2_not_authorized_because_fails_process_count_message;
extern Object G2_product;
extern Object G2_restricted_use_option;
extern Object G2_runtime_option;
DECLARE_VARIABLE_WITH_SYMBOL(G2_stream_of_ok_file_reader, Qg2_stream_of_ok_file_reader);
DECLARE_VARIABLE_WITH_SYMBOL(G2passwdexe, Qg2passwdexe);
extern Object G2passwdexe_areyouthere_arg;
#define G2passwdexe_areyouthere_good_result FIX((SI_Long)111L)
DECLARE_VARIABLE_WITH_SYMBOL(G2passwdexe_is_executable_p, Qg2passwdexe_is_executable_p);
DECLARE_VARIABLE_WITH_SYMBOL(Grammar_rules_to_add_for_nupec_after_authorization, Qgrammar_rules_to_add_for_nupec_after_authorization);
#define Higher_than_any_priority FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Hour_of_last_message, Qhour_of_last_message);
DECLARE_VARIABLE_WITH_SYMBOL(Hourly_countdown, Qhourly_countdown);
#define Illegal_character_for_g2_ok_file FIX((SI_Long)0L)
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Installation_code_in_ok_file, Qinstallation_code_in_ok_file);
extern Object Instances_specific_to_this_class_kbprop;
#define Jan_1_1990 FIX((SI_Long)32872L)
#define Jan_1_1998 FIX((SI_Long)35794L)
#define Jan_1_1999 FIX((SI_Long)36159L)
#define Jan_1_2006 FIX((SI_Long)38716L)
#define Jan_1_2009 FIX((SI_Long)39812L)
#define Jan_1_2015 FIX((SI_Long)42003L)
DECLARE_VARIABLE_WITH_SYMBOL(Journal_shutout_scan_p, Qjournal_shutout_scan_p);
DECLARE_VARIABLE_WITH_SYMBOL(Keytab1, Qkeytab1);
extern Object Keytab_backbone;
extern Object Keytab_interface_inset;
extern Object Keytab_interface_linkage;
#define Lf_character_for_g2_ok_file FIX((SI_Long)11L)
DECLARE_VARIABLE_WITH_SYMBOL(Line_number_of_ok_file_reader, Qline_number_of_ok_file_reader);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Local_filename_parser, Qlocal_filename_parser);
DECLARE_VARIABLE_WITH_SYMBOL(Local_namestring_generator, Qlocal_namestring_generator);
extern Object Local_recovery_list;
DECLARE_VARIABLE_WITH_SYMBOL(Locked_to_kb_qm, Qlocked_to_kb_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Machine_model_var, Qmachine_model_var);
extern Object Mm1;
extern Object Mm2;
extern Object Mm3;
extern Object Mm4;
extern Object N_1_2_version;
extern Object N_4_0_version;
DECLARE_VARIABLE_WITH_SYMBOL(Name_of_customer_in_ok_file, Qname_of_customer_in_ok_file);
extern Object New_modulus;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Object_class_description, Qobject_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_authorized_packages, Qok_authorized_packages);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_authorized_products, Qok_authorized_products);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_class_description, Qok_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_expiration_date_qm, Qok_expiration_date_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_file_token_cons_counter, Qok_file_token_cons_counter);
extern Object Ok_file_token_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Ok_file_token_count, Qok_file_token_count);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_make_g2_secure_qm, Qok_make_g2_secure_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_maximum_number_of_concurrent_floating_telewindows_allowed, Qok_maximum_number_of_concurrent_floating_telewindows_allowed);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_maximum_number_of_concurrent_floating_tw2_allowed, Qok_maximum_number_of_concurrent_floating_tw2_allowed);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_modified, Qok_modified);
DECLARE_VARIABLE_WITH_SYMBOL(Ok_number_of_processes_authorized, Qok_number_of_processes_authorized);
extern Object Ok_to_run_g2_message;
#define Open_paren_character_for_g2_ok_file FIX((SI_Long)3L)
#define Open_string_character_for_g2_ok_file FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Operative_task_list, Qoperative_task_list);
DECLARE_VARIABLE_WITH_SYMBOL(Optional_modules_map, Qoptional_modules_map);
DECLARE_VARIABLE_WITH_SYMBOL(Pad_for_ok_file_reader, Qpad_for_ok_file_reader);
#define Period_character_for_g2_ok_file FIX((SI_Long)14L)
DECLARE_VARIABLE_WITH_SYMBOL(Procedure_class_description, Qprocedure_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Pulse_rate_multiplier, Qpulse_rate_multiplier);
DECLARE_VARIABLE_WITH_SYMBOL(Pulse_rate_options, Qpulse_rate_options);
#define Question_mark_character_for_g2_ok_file FIX((SI_Long)13L)
DECLARE_VARIABLE_WITH_SYMBOL(Random_state_array, Qrandom_state_array);
DECLARE_VARIABLE_WITH_SYMBOL(Random_state_array_24_pointer, Qrandom_state_array_24_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Random_state_array_current_pointer, Qrandom_state_array_current_pointer);
DECLARE_VARIABLE_WITH_SYMBOL(Read_ok_file_buffer_1, Qread_ok_file_buffer_1);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_ok_file, Qreading_ok_file);
DECLARE_VARIABLE_WITH_SYMBOL(Redef_class_instance, Qredef_class_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Reference_date_for_interval_encoding, Qreference_date_for_interval_encoding);
DECLARE_VARIABLE_WITH_SYMBOL(Relations_tag_list, Qrelations_tag_list);
extern Object Required_delay_between_calls_to_set_password;
#define Restricted_use_lic_level FIX((SI_Long)2L)
DECLARE_VARIABLE_WITH_SYMBOL(Revert_to_fuzzy_cache_p, Qrevert_to_fuzzy_cache_p);
DECLARE_VARIABLE_WITH_SYMBOL(Roman_character_map, Qroman_character_map);
#define Runtime_lic_level FIX((SI_Long)1L)
DECLARE_VARIABLE_WITH_SYMBOL(Saved_initial_status, Qsaved_initial_status);
DECLARE_VARIABLE_WITH_SYMBOL(Saw_more_than_one_machine_authorization_qm, Qsaw_more_than_one_machine_authorization_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
#define Semicolon_character_for_g2_ok_file FIX((SI_Long)6L)
DECLARE_VARIABLE_WITH_SYMBOL(Serial_number_in_ok_file, Qserial_number_in_ok_file);
DECLARE_VARIABLE_WITH_SYMBOL(Server_parameters, Qserver_parameters);
extern Object Should_create_users_and_then_save_ok_file_message_1;
extern Object Should_create_users_and_then_save_ok_file_message_2;
extern Object Should_create_users_and_then_save_ok_file_message_3;
extern Object Should_create_users_and_then_save_ok_file_message_format_control_string;
extern Object Should_save_ok_file_message;
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Simulate_proprietary_qm, Qsimulate_proprietary_qm);
#define Size_of_local_machine_id FIX((SI_Long)256L)
extern Object Slot_pad_descriptions_of_machine_authorization;
extern Object Slot_pad_descriptions_of_user;
DECLARE_VARIABLE_WITH_SYMBOL(Slot_pad_of_ok_file_reader, Qslot_pad_of_ok_file_reader);
DECLARE_VARIABLE_WITH_SYMBOL(Smoothed_subsecond_adjustment, Qsmoothed_subsecond_adjustment);
DECLARE_VARIABLE_WITH_SYMBOL(Statement_class_description, Qstatement_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Subworkspace_currently_being_deleted_qm, Qsubworkspace_currently_being_deleted_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Success_of_ok_file_reader_qm, Qsuccess_of_ok_file_reader_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Supported_ok_file_format_version, Qsupported_ok_file_format_version);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
#define Symbol_token_match_should_be_case_sensitive_p Qnil
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(System_slot_accessor, Qsystem_slot_accessor);
DECLARE_VARIABLE_WITH_SYMBOL(System_version_from_kb_being_read, Qsystem_version_from_kb_being_read);
DECLARE_VARIABLE_WITH_SYMBOL(T2_nonce_data_count, Qt2_nonce_data_count);
DECLARE_VARIABLE_WITH_SYMBOL(T2_nonce_table, Qt2_nonce_table);
DECLARE_VARIABLE_WITH_SYMBOL(Telewindows_license_level, Qtelewindows_license_level);
DECLARE_VARIABLE_WITH_SYMBOL(Text_representation_of_our_ok_object, Qtext_representation_of_our_ok_object);
extern Object The_type_description_of_ok_file_token;
extern Object The_type_description_of_t2_nonce_data;
DECLARE_VARIABLE_WITH_SYMBOL(Time_of_last_call_to_set_user_password, Qtime_of_last_call_to_set_user_password);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
#define Truth FIX((SI_Long)1000L)
#define Unauthorized_lic_level FIX((SI_Long)-2L)
DECLARE_VARIABLE_WITH_SYMBOL(Unbound_value_for_ok_reader, Qunbound_value_for_ok_reader);
#define Underscore_character_for_g2_ok_file FIX((SI_Long)12L)
DECLARE_VARIABLE_WITH_SYMBOL(Unevaluated_expression, Qunevaluated_expression);
extern Object Unlimited_backtracking_in_internal_truth_maintenance_p;
DECLARE_VARIABLE_WITH_SYMBOL(Unread_char_of_ok_file_reader_qm, Qunread_char_of_ok_file_reader_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Updated_users_list, Qupdated_users_list);
DECLARE_VARIABLE_WITH_SYMBOL(Useful_machine_authorization_info, Quseful_machine_authorization_info);
extern Object Using_g2_ok_file_message;
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Verbosity_level, Qverbosity_level);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
#define Whitespace_character_for_g2_ok_file FIX((SI_Long)1L)
extern Object Within_side_limits;
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_class_description, Qworkspace_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Workspace_image_plane_per_window, Qworkspace_image_plane_per_window);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Write_console_p, Qwrite_console_p);
DECLARE_VARIABLE_WITH_SYMBOL(Write_proprietary_package_while_saving_xml_kb, Qwrite_proprietary_package_while_saving_xml_kb);
