/* trnscd.h -- Header File for trnscd.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kelement_type;
extern Object Kfill_pointer;
extern Object Kinitial_element;
extern Object Qquote;
extern Object Qstring_char;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object allocate_byte_vector_16(Object);
extern Object asian_double_byte_structure_memory_usage(void);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object clear_8859_reverse_unicode_map(Object);
extern Object clear_8859_reverse_unicode_map_tree(Object);
extern Object clear_optimized_constants(void);
extern Object copy_out_current_gensym_string(void);
extern Object copy_out_current_wide_string(void);
extern Object create_transcode_text_conversion_style(Object,Object,Object,Object,Object,Object,Object);
extern Object create_transcoder_for_gb_2312(void);
extern Object create_transcoder_for_gb_2312_euc(void);
extern Object create_transcoder_for_gensym(void);
extern Object create_transcoder_for_gensym_with_ascii_as_much_as_possible(void);
extern Object create_transcoder_for_iso_2022(void);
extern Object create_transcoder_for_iso_646(void);
extern Object create_transcoder_for_iso_8859_1(void);
extern Object create_transcoder_for_iso_8859_10(void);
extern Object create_transcoder_for_iso_8859_2(void);
extern Object create_transcoder_for_iso_8859_3(void);
extern Object create_transcoder_for_iso_8859_4(void);
extern Object create_transcoder_for_iso_8859_5(void);
extern Object create_transcoder_for_iso_8859_6(void);
extern Object create_transcoder_for_iso_8859_7(void);
extern Object create_transcoder_for_iso_8859_8(void);
extern Object create_transcoder_for_iso_8859_9(void);
extern Object create_transcoder_for_jis_x_0208(void);
extern Object create_transcoder_for_jis_x_0208_euc(void);
extern Object create_transcoder_for_ks_c_5601(void);
extern Object create_transcoder_for_ks_c_5601_euc(void);
extern Object create_transcoder_for_shift_jis_x_0208(void);
extern Object create_transcoder_for_unicode(void);
extern Object create_transcoder_for_unicode_byte_swapped(void);
extern Object create_transcoder_for_unicode_ucs_2(void);
extern Object create_transcoder_for_unicode_ucs_2_byte_swapped(void);
extern Object create_transcoder_for_unicode_utf_7(void);
extern Object create_transcoder_for_unicode_utf_8(void);
extern Object direct_structure_method(Object,Object);
extern Object emit_buffered_octets_as_unicodes(Object,Object);
extern Object emit_buffered_octets_as_utf_7_base64_to_transcoder(Object,Object);
extern Object emit_buffered_unicodes_as_utf_7_base64_to_transcoder(Object,Object);
extern Object emit_buffered_utf_7_base64_sextets_as_unicodes(Object,Object);
extern Object encode_utf_8_octets_for_transcoder(Object,Object,Object,Object,Object,Object);
extern Object export_and_emit_character(Object,Object,Object);
extern Object export_and_emit_text_line(Object,Object,Object);
extern Object export_and_emit_text_string(Object,Object,Object);
extern Object export_as_string_function(Object);
extern Object export_character_function(Object);
extern Object export_text_string(int,...);
extern Object export_text_string_per_text_conversion_style(int,...);
extern Object export_utf_7_base64(Object,Object);
extern Object extend_current_gensym_string(int,...);
extern Object flatten_8859_reverse_unicode_map(Object);
extern Object flatten_binary_tree(Object);
extern Object g2_stream_write_char(Object,Object);
extern Object g2_stream_write_from_buffer(Object,Object,Object);
extern Object g2_stream_write_from_wide_string_buffer(Object,Object,Object);
extern Object g2_stream_write_line_terminator_using_text_conversion_style(Object,Object);
extern Object g2_stream_write_line_with_end_character_sequence(Object,Object,Object);
extern Object g2_stream_write_string(Object,Object);
extern Object g2_stream_write_trailing_bytes_of_wide_string(Object,Object);
extern Object g2_stream_write_ucs_2_character(Object,Object,Object);
extern Object g2_stream_write_unicode_ucs_2_line(Object,Object,Object,Object);
extern Object g2_stream_write_unicode_ucs_2_string(Object,Object,Object);
extern Object g2_stream_write_wide_string_using_text_conversion_style(Object,Object,Object);
extern Object gb_2312_euc_in_text_sequence_to_unicode(Object,Object);
extern Object gb_2312_in_text_sequence_to_unicode(Object,Object);
extern Object gb_2312_structure_memory_usage(void);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_jis_code_to_contiguous(Object);
extern Object gensym_ksc_code_to_contiguous(Object);
extern Object gensym_ksc_to_ksc(Object);
extern Object gensym_string_length(Object);
extern Object gensym_string_text_sequence_structure_memory_usage(void);
extern Object gensym_string_to_wide_string(Object);
extern Object get_line_end_sequence_from_style(Object);
extern Object get_transcoder_character(Object);
extern Object get_transcoder_character_if_any(Object);
extern Object get_utf_8_as_unicode_from_text_sequence(Object);
extern Object get_utf_g_transcoder_code(Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object graphic_character_set_structure_memory_usage(void);
extern Object handle_iso_2022_escape(Object);
extern Object import_text_string(int,...);
extern Object import_text_string_per_text_conversion_style(int,...);
extern Object initialize_text_sequence_string_function(Object,Object,Object,Object);
extern Object install_text_transcode_purpose(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object intern_and_upcase_simple_symbol_portion_of_wide_string(Object,Object,Object,Object);
extern Object intern_gensym_string(int,...);
extern Object intern_simple_symbol_portion_of_wide_string(Object,Object,Object,Object);
extern Object intern_using_string_buffer(Object,Object,Object);
extern Object intern_wide_string(int,...);
extern Object intern_wide_string_no_reclaim(int,...);
extern Object iso_2022_transcoder_structure_memory_usage(void);
extern Object iso_646_structure_memory_usage(void);
extern Object iso_8859_10_structure_memory_usage(void);
extern Object iso_8859_1_structure_memory_usage(void);
extern Object iso_8859_2_structure_memory_usage(void);
extern Object iso_8859_3_structure_memory_usage(void);
extern Object iso_8859_4_structure_memory_usage(void);
extern Object iso_8859_5_structure_memory_usage(void);
extern Object iso_8859_6_structure_memory_usage(void);
extern Object iso_8859_7_structure_memory_usage(void);
extern Object iso_8859_8_structure_memory_usage(void);
extern Object iso_8859_9_structure_memory_usage(void);
extern Object iso_8859_abstract_structure_memory_usage(void);
extern Object iso_8859_transcoder_structure_memory_usage(void);
extern Object jis_x_0208_euc_in_text_sequence_to_unicode(Object,Object);
extern Object jis_x_0208_in_text_sequence_to_unicode(Object,Object);
extern Object jis_x_0208_structure_memory_usage(void);
extern Object ks_c_5601_euc_in_text_sequence_to_unicode(Object,Object);
extern Object ks_c_5601_in_text_sequence_to_unicode(Object,Object);
extern Object ks_c_5601_structure_memory_usage(void);
extern Object ksc_to_gensym_ksc(Object);
extern Object lengthw(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object make_8859_reverse_unicode_map(void);
extern Object make_8859_reverse_unicode_map_hash_vector(void);
extern Object make_asian_double_byte_1(void);
extern Object make_gb_2312_1(void);
extern Object make_gensym_string_text_sequence_1(void);
extern Object make_graphic_character_set_1(void);
extern Object make_iso_2022_transcoder_1(void);
extern Object make_iso_646_1(void);
extern Object make_iso_8859_10_1(void);
extern Object make_iso_8859_1_1(void);
extern Object make_iso_8859_2_1(void);
extern Object make_iso_8859_3_1(void);
extern Object make_iso_8859_4_1(void);
extern Object make_iso_8859_5_1(void);
extern Object make_iso_8859_6_1(void);
extern Object make_iso_8859_7_1(void);
extern Object make_iso_8859_8_1(void);
extern Object make_iso_8859_9_1(void);
extern Object make_iso_8859_abstract_1(void);
extern Object make_iso_8859_transcoder_1(Object,Object);
extern Object make_jis_x_0208_1(void);
extern Object make_ks_c_5601_1(void);
extern Object make_permanent_8859_reverse_unicode_map_hash_vector_43_vector_internal(void);
extern Object make_permanent_asian_double_byte_structure_internal(void);
extern Object make_permanent_gb_2312_structure_internal(void);
extern Object make_permanent_gensym_string_text_sequence_structure_internal(void);
extern Object make_permanent_graphic_character_set_structure_internal(void);
extern Object make_permanent_iso_2022_transcoder_structure_internal(void);
extern Object make_permanent_iso_646_structure_internal(void);
extern Object make_permanent_iso_8859_10_structure_internal(void);
extern Object make_permanent_iso_8859_1_structure_internal(void);
extern Object make_permanent_iso_8859_2_structure_internal(void);
extern Object make_permanent_iso_8859_3_structure_internal(void);
extern Object make_permanent_iso_8859_4_structure_internal(void);
extern Object make_permanent_iso_8859_5_structure_internal(void);
extern Object make_permanent_iso_8859_6_structure_internal(void);
extern Object make_permanent_iso_8859_7_structure_internal(void);
extern Object make_permanent_iso_8859_8_structure_internal(void);
extern Object make_permanent_iso_8859_9_structure_internal(void);
extern Object make_permanent_iso_8859_abstract_structure_internal(void);
extern Object make_permanent_iso_8859_transcoder_structure_internal(void);
extern Object make_permanent_jis_x_0208_structure_internal(void);
extern Object make_permanent_ks_c_5601_structure_internal(void);
extern Object make_permanent_shift_jis_transcoder_structure_internal(void);
extern Object make_permanent_text_sequence_structure_internal(void);
extern Object make_permanent_transcode_text_conversion_style_structure_internal(void);
extern Object make_permanent_transcoder_structure_internal(void);
extern Object make_permanent_unicode_byte_swapped_transcoder_structure_internal(void);
extern Object make_permanent_unicode_transcoder_structure_internal(void);
extern Object make_permanent_unicode_ucs_2_transcoder_structure_internal(void);
extern Object make_permanent_utf_7_transcoder_structure_internal(void);
extern Object make_permanent_utf_8_transcoder_structure_internal(void);
extern Object make_permanent_utf_g_ascii_as_much_as_possible_transcoder_structure_internal(void);
extern Object make_permanent_utf_g_transcoder_structure_internal(void);
extern Object make_permanent_wide_string_text_sequence_structure_internal(void);
extern Object make_shift_jis_transcoder_1(void);
extern Object make_shift_jis_transcoder_function(void);
extern Object make_text_sequence(Object,Object,Object);
extern Object make_text_sequence_internal_1(void);
extern Object make_thread_array(Object);
extern Object make_transcode_text_conversion_style_1(void);
extern Object make_transcoder_1(void);
extern Object make_transcoder_per_text_conversion_style(Object,Object);
extern Object make_unicode_byte_swapped_transcoder_1(void);
extern Object make_unicode_transcoder_1(void);
extern Object make_unicode_ucs_2_transcoder_1(void);
extern Object make_utf_7_transcoder_1(void);
extern Object make_utf_8_transcoder_1(void);
extern Object make_utf_g_ascii_as_much_as_possible_transcoder_1(void);
extern Object make_utf_g_transcoder_1(void);
extern Object make_wide_string_text_sequence_1(void);
extern Object map_code_to_unicode_function(Object,Object);
extern Object map_extended_utf_g_characters_to_unicode(Object,Object);
extern Object map_gb_2312_bytes_to_unicode_character(Object,Object);
extern Object map_gensym_han_character_code_to_unicode(Object);
extern Object map_jis_x_0208_bytes_to_unicode_character(Object,Object);
extern Object map_ks_c_5601_bytes_to_unicode_character(Object,Object);
extern Object map_shift_jis_bytes_to_unicode_character(Object,Object);
extern Object map_shift_jis_half_width_katakana_to_unicode(Object);
extern Object map_unicode_to_code_if_any_function(Object,Object);
extern Object map_unicode_to_gensym_han_character_code(Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object n_8859_reverse_unicode_map_hash_vector_43_vector_memory_usage(void);
extern Object newline_p(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object out_8859_reverse_unicode_map_hash_vector_43_vectors(void);
extern Object outstanding_asian_double_byte_count(void);
extern Object outstanding_gb_2312_count(void);
extern Object outstanding_gensym_string_text_sequence_count(void);
extern Object outstanding_graphic_character_set_count(void);
extern Object outstanding_iso_2022_transcoder_count(void);
extern Object outstanding_iso_646_count(void);
extern Object outstanding_iso_8859_10_count(void);
extern Object outstanding_iso_8859_1_count(void);
extern Object outstanding_iso_8859_2_count(void);
extern Object outstanding_iso_8859_3_count(void);
extern Object outstanding_iso_8859_4_count(void);
extern Object outstanding_iso_8859_5_count(void);
extern Object outstanding_iso_8859_6_count(void);
extern Object outstanding_iso_8859_7_count(void);
extern Object outstanding_iso_8859_8_count(void);
extern Object outstanding_iso_8859_9_count(void);
extern Object outstanding_iso_8859_abstract_count(void);
extern Object outstanding_iso_8859_transcoder_count(void);
extern Object outstanding_jis_x_0208_count(void);
extern Object outstanding_ks_c_5601_count(void);
extern Object outstanding_shift_jis_transcoder_count(void);
extern Object outstanding_text_sequence_count(void);
extern Object outstanding_transcode_text_conversion_style_count(void);
extern Object outstanding_transcoder_count(void);
extern Object outstanding_unicode_byte_swapped_transcoder_count(void);
extern Object outstanding_unicode_transcoder_count(void);
extern Object outstanding_unicode_ucs_2_transcoder_count(void);
extern Object outstanding_utf_7_transcoder_count(void);
extern Object outstanding_utf_8_transcoder_count(void);
extern Object outstanding_utf_g_ascii_as_much_as_possible_transcoder_count(void);
extern Object outstanding_utf_g_transcoder_count(void);
extern Object outstanding_wide_string_text_sequence_count(void);
extern Object push_optimized_constant(Object);
extern Object read_character_from_text_sequence_function(Object);
extern Object read_iso_2022_escape_from_wide_string(Object,Object);
extern Object reclaim_8859_reverse_unicode_map(Object);
extern Object reclaim_8859_reverse_unicode_map_hash_vector(Object);
extern Object reclaim_8859_reverse_unicode_map_tree_for_hash_leaves(Object);
extern Object reclaim_asian_double_byte_1(Object);
extern Object reclaim_binary_tree_element_1(Object);
extern Object reclaim_gb_2312_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_string_text_sequence_1(Object);
extern Object reclaim_graphic_character_set_1(Object);
extern Object reclaim_iso_2022_transcoder_1(Object);
extern Object reclaim_iso_646_1(Object);
extern Object reclaim_iso_8859_10_1(Object);
extern Object reclaim_iso_8859_1_1(Object);
extern Object reclaim_iso_8859_2_1(Object);
extern Object reclaim_iso_8859_3_1(Object);
extern Object reclaim_iso_8859_4_1(Object);
extern Object reclaim_iso_8859_5_1(Object);
extern Object reclaim_iso_8859_6_1(Object);
extern Object reclaim_iso_8859_7_1(Object);
extern Object reclaim_iso_8859_8_1(Object);
extern Object reclaim_iso_8859_9_1(Object);
extern Object reclaim_iso_8859_abstract_1(Object);
extern Object reclaim_iso_8859_transcoder_1(Object);
extern Object reclaim_jis_x_0208_1(Object);
extern Object reclaim_ks_c_5601_1(Object);
extern Object reclaim_shift_jis_transcoder_1(Object);
extern Object reclaim_text_sequence_internal_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_transcode_text_conversion_style_1(Object);
extern Object reclaim_transcoder_1(Object);
extern Object reclaim_unicode_byte_swapped_transcoder_1(Object);
extern Object reclaim_unicode_transcoder_1(Object);
extern Object reclaim_unicode_ucs_2_transcoder_1(Object);
extern Object reclaim_utf_7_transcoder_1(Object);
extern Object reclaim_utf_8_transcoder_1(Object);
extern Object reclaim_utf_g_ascii_as_much_as_possible_transcoder_1(Object);
extern Object reclaim_utf_g_transcoder_1(Object);
extern Object reclaim_wide_string(Object);
extern Object reclaim_wide_string_text_sequence_1(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object set_up_iso_2022_transcoder_for_gb_2312(Object);
extern Object set_up_iso_2022_transcoder_for_gb_2312_euc(Object);
extern Object set_up_iso_2022_transcoder_for_jis_x_0208(Object);
extern Object set_up_iso_2022_transcoder_for_jis_x_0208_euc(Object);
extern Object set_up_iso_2022_transcoder_for_ks_c_5601(Object);
extern Object set_up_iso_2022_transcoder_for_ks_c_5601_euc(Object);
extern Object set_up_iso_2022_transcoder_for_us_ascii(Object);
extern Object set_up_iso_2022_transcoder_for_x_compound_text(Object);
extern Object shift_jis_transcoder_structure_memory_usage(void);
extern Object shift_jis_x_0208_in_text_sequence_to_unicode(Object,Object);
extern Object stringw(Object);
extern Object sxhashw(Object);
extern Object text_sequence_structure_memory_usage(void);
extern Object text_string_length(Object);
extern Object transcode_as_text_string_function(Object);
extern Object transcode_character_function(Object);
extern Object transcode_iso_2022_c1_character(Object,Object);
extern Object transcode_iso_2022_graphic_character(Object,Object,Object);
extern Object transcode_text_conversion_style_structure_memory_usage(void);
extern Object transcode_unhandled_character(Object,Object);
extern Object transcode_utf_7_base64(Object);
extern Object transcoder_structure_memory_usage(void);
extern Object transform_utf_8_to_ucs_4(int,...);
extern Object twrite_ascii_from_wide_string(Object);
extern Object twrite_for_export_from_transcoder_function(Object);
extern Object twrite_intern_string_buffer_as_gensym_characters(Object);
extern Object twrite_spaces_for_tabs(Object);
extern Object twrite_unicode_as_utf_8(Object);
extern Object twrite_unicode_from_transcoder_function(Object);
extern Object twrite_utf_8_from_text_string(Object);
extern Object twrite_utf_8_octets(Object,Object,Object,Object,Object);
extern Object twrite_utf_g_from_text_string(Object);
extern Object twrite_wide_character(Object);
extern Object unicode_byte_swapped_transcoder_structure_memory_usage(void);
extern Object unicode_known_iso_latin1_to_gensym_string(Object);
extern Object unicode_to_utf_8_gensym_string(Object);
extern Object unicode_to_utf_8_wide_string(Object);
extern Object unicode_to_utf_g_gensym_string(Object);
extern Object unicode_to_utf_g_wide_string(Object);
extern Object unicode_transcoder_structure_memory_usage(void);
extern Object unicode_ucs_2_transcoder_structure_memory_usage(void);
extern Object update_object_pool_meters_list(Object);
extern Object utf_7_base64_digit_char_code_p(Object);
extern Object utf_7_base64_digit_char_p(Object);
extern Object utf_7_transcoder_structure_memory_usage(void);
extern Object utf_8_transcoder_structure_memory_usage(void);
extern Object utf_g_ascii_as_much_as_possible_transcoder_structure_memory_usage(void);
extern Object utf_g_transcoder_structure_memory_usage(void);
extern Object wide_string_text_sequence_structure_memory_usage(void);
extern Object wide_string_to_gensym_string(Object);

#else

extern Object allocate_byte_vector_16();
extern Object asian_double_byte_structure_memory_usage();
extern Object bytes_per_simple_vector();
extern Object bytes_per_typed_simple_array();
extern Object chestnut_floorf_function();
extern Object clear_8859_reverse_unicode_map();
extern Object clear_8859_reverse_unicode_map_tree();
extern Object clear_optimized_constants();
extern Object copy_out_current_gensym_string();
extern Object copy_out_current_wide_string();
extern Object create_transcode_text_conversion_style();
extern Object create_transcoder_for_gb_2312();
extern Object create_transcoder_for_gb_2312_euc();
extern Object create_transcoder_for_gensym();
extern Object create_transcoder_for_gensym_with_ascii_as_much_as_possible();
extern Object create_transcoder_for_iso_2022();
extern Object create_transcoder_for_iso_646();
extern Object create_transcoder_for_iso_8859_1();
extern Object create_transcoder_for_iso_8859_10();
extern Object create_transcoder_for_iso_8859_2();
extern Object create_transcoder_for_iso_8859_3();
extern Object create_transcoder_for_iso_8859_4();
extern Object create_transcoder_for_iso_8859_5();
extern Object create_transcoder_for_iso_8859_6();
extern Object create_transcoder_for_iso_8859_7();
extern Object create_transcoder_for_iso_8859_8();
extern Object create_transcoder_for_iso_8859_9();
extern Object create_transcoder_for_jis_x_0208();
extern Object create_transcoder_for_jis_x_0208_euc();
extern Object create_transcoder_for_ks_c_5601();
extern Object create_transcoder_for_ks_c_5601_euc();
extern Object create_transcoder_for_shift_jis_x_0208();
extern Object create_transcoder_for_unicode();
extern Object create_transcoder_for_unicode_byte_swapped();
extern Object create_transcoder_for_unicode_ucs_2();
extern Object create_transcoder_for_unicode_ucs_2_byte_swapped();
extern Object create_transcoder_for_unicode_utf_7();
extern Object create_transcoder_for_unicode_utf_8();
extern Object direct_structure_method();
extern Object emit_buffered_octets_as_unicodes();
extern Object emit_buffered_octets_as_utf_7_base64_to_transcoder();
extern Object emit_buffered_unicodes_as_utf_7_base64_to_transcoder();
extern Object emit_buffered_utf_7_base64_sextets_as_unicodes();
extern Object encode_utf_8_octets_for_transcoder();
extern Object export_and_emit_character();
extern Object export_and_emit_text_line();
extern Object export_and_emit_text_string();
extern Object export_as_string_function();
extern Object export_character_function();
extern Object export_text_string();
extern Object export_text_string_per_text_conversion_style();
extern Object export_utf_7_base64();
extern Object extend_current_gensym_string();
extern Object flatten_8859_reverse_unicode_map();
extern Object flatten_binary_tree();
extern Object g2_stream_write_char();
extern Object g2_stream_write_from_buffer();
extern Object g2_stream_write_from_wide_string_buffer();
extern Object g2_stream_write_line_terminator_using_text_conversion_style();
extern Object g2_stream_write_line_with_end_character_sequence();
extern Object g2_stream_write_string();
extern Object g2_stream_write_trailing_bytes_of_wide_string();
extern Object g2_stream_write_ucs_2_character();
extern Object g2_stream_write_unicode_ucs_2_line();
extern Object g2_stream_write_unicode_ucs_2_string();
extern Object g2_stream_write_wide_string_using_text_conversion_style();
extern Object gb_2312_euc_in_text_sequence_to_unicode();
extern Object gb_2312_in_text_sequence_to_unicode();
extern Object gb_2312_structure_memory_usage();
extern Object gensym_cons_1();
extern Object gensym_jis_code_to_contiguous();
extern Object gensym_ksc_code_to_contiguous();
extern Object gensym_ksc_to_ksc();
extern Object gensym_string_length();
extern Object gensym_string_text_sequence_structure_memory_usage();
extern Object gensym_string_to_wide_string();
extern Object get_line_end_sequence_from_style();
extern Object get_transcoder_character();
extern Object get_transcoder_character_if_any();
extern Object get_utf_8_as_unicode_from_text_sequence();
extern Object get_utf_g_transcoder_code();
extern Object getfq_function_no_default();
extern Object graphic_character_set_structure_memory_usage();
extern Object handle_iso_2022_escape();
extern Object import_text_string();
extern Object import_text_string_per_text_conversion_style();
extern Object initialize_text_sequence_string_function();
extern Object install_text_transcode_purpose();
extern Object intern_and_upcase_simple_symbol_portion_of_wide_string();
extern Object intern_gensym_string();
extern Object intern_simple_symbol_portion_of_wide_string();
extern Object intern_using_string_buffer();
extern Object intern_wide_string();
extern Object intern_wide_string_no_reclaim();
extern Object iso_2022_transcoder_structure_memory_usage();
extern Object iso_646_structure_memory_usage();
extern Object iso_8859_10_structure_memory_usage();
extern Object iso_8859_1_structure_memory_usage();
extern Object iso_8859_2_structure_memory_usage();
extern Object iso_8859_3_structure_memory_usage();
extern Object iso_8859_4_structure_memory_usage();
extern Object iso_8859_5_structure_memory_usage();
extern Object iso_8859_6_structure_memory_usage();
extern Object iso_8859_7_structure_memory_usage();
extern Object iso_8859_8_structure_memory_usage();
extern Object iso_8859_9_structure_memory_usage();
extern Object iso_8859_abstract_structure_memory_usage();
extern Object iso_8859_transcoder_structure_memory_usage();
extern Object jis_x_0208_euc_in_text_sequence_to_unicode();
extern Object jis_x_0208_in_text_sequence_to_unicode();
extern Object jis_x_0208_structure_memory_usage();
extern Object ks_c_5601_euc_in_text_sequence_to_unicode();
extern Object ks_c_5601_in_text_sequence_to_unicode();
extern Object ks_c_5601_structure_memory_usage();
extern Object ksc_to_gensym_ksc();
extern Object lengthw();
extern Object load_and_initialize_type_description();
extern Object make_8859_reverse_unicode_map();
extern Object make_8859_reverse_unicode_map_hash_vector();
extern Object make_asian_double_byte_1();
extern Object make_gb_2312_1();
extern Object make_gensym_string_text_sequence_1();
extern Object make_graphic_character_set_1();
extern Object make_iso_2022_transcoder_1();
extern Object make_iso_646_1();
extern Object make_iso_8859_10_1();
extern Object make_iso_8859_1_1();
extern Object make_iso_8859_2_1();
extern Object make_iso_8859_3_1();
extern Object make_iso_8859_4_1();
extern Object make_iso_8859_5_1();
extern Object make_iso_8859_6_1();
extern Object make_iso_8859_7_1();
extern Object make_iso_8859_8_1();
extern Object make_iso_8859_9_1();
extern Object make_iso_8859_abstract_1();
extern Object make_iso_8859_transcoder_1();
extern Object make_jis_x_0208_1();
extern Object make_ks_c_5601_1();
extern Object make_permanent_8859_reverse_unicode_map_hash_vector_43_vector_internal();
extern Object make_permanent_asian_double_byte_structure_internal();
extern Object make_permanent_gb_2312_structure_internal();
extern Object make_permanent_gensym_string_text_sequence_structure_internal();
extern Object make_permanent_graphic_character_set_structure_internal();
extern Object make_permanent_iso_2022_transcoder_structure_internal();
extern Object make_permanent_iso_646_structure_internal();
extern Object make_permanent_iso_8859_10_structure_internal();
extern Object make_permanent_iso_8859_1_structure_internal();
extern Object make_permanent_iso_8859_2_structure_internal();
extern Object make_permanent_iso_8859_3_structure_internal();
extern Object make_permanent_iso_8859_4_structure_internal();
extern Object make_permanent_iso_8859_5_structure_internal();
extern Object make_permanent_iso_8859_6_structure_internal();
extern Object make_permanent_iso_8859_7_structure_internal();
extern Object make_permanent_iso_8859_8_structure_internal();
extern Object make_permanent_iso_8859_9_structure_internal();
extern Object make_permanent_iso_8859_abstract_structure_internal();
extern Object make_permanent_iso_8859_transcoder_structure_internal();
extern Object make_permanent_jis_x_0208_structure_internal();
extern Object make_permanent_ks_c_5601_structure_internal();
extern Object make_permanent_shift_jis_transcoder_structure_internal();
extern Object make_permanent_text_sequence_structure_internal();
extern Object make_permanent_transcode_text_conversion_style_structure_internal();
extern Object make_permanent_transcoder_structure_internal();
extern Object make_permanent_unicode_byte_swapped_transcoder_structure_internal();
extern Object make_permanent_unicode_transcoder_structure_internal();
extern Object make_permanent_unicode_ucs_2_transcoder_structure_internal();
extern Object make_permanent_utf_7_transcoder_structure_internal();
extern Object make_permanent_utf_8_transcoder_structure_internal();
extern Object make_permanent_utf_g_ascii_as_much_as_possible_transcoder_structure_internal();
extern Object make_permanent_utf_g_transcoder_structure_internal();
extern Object make_permanent_wide_string_text_sequence_structure_internal();
extern Object make_shift_jis_transcoder_1();
extern Object make_shift_jis_transcoder_function();
extern Object make_text_sequence();
extern Object make_text_sequence_internal_1();
extern Object make_thread_array();
extern Object make_transcode_text_conversion_style_1();
extern Object make_transcoder_1();
extern Object make_transcoder_per_text_conversion_style();
extern Object make_unicode_byte_swapped_transcoder_1();
extern Object make_unicode_transcoder_1();
extern Object make_unicode_ucs_2_transcoder_1();
extern Object make_utf_7_transcoder_1();
extern Object make_utf_8_transcoder_1();
extern Object make_utf_g_ascii_as_much_as_possible_transcoder_1();
extern Object make_utf_g_transcoder_1();
extern Object make_wide_string_text_sequence_1();
extern Object map_code_to_unicode_function();
extern Object map_extended_utf_g_characters_to_unicode();
extern Object map_gb_2312_bytes_to_unicode_character();
extern Object map_gensym_han_character_code_to_unicode();
extern Object map_jis_x_0208_bytes_to_unicode_character();
extern Object map_ks_c_5601_bytes_to_unicode_character();
extern Object map_shift_jis_bytes_to_unicode_character();
extern Object map_shift_jis_half_width_katakana_to_unicode();
extern Object map_unicode_to_code_if_any_function();
extern Object map_unicode_to_gensym_han_character_code();
extern Object mutate_global_property();
extern Object n_8859_reverse_unicode_map_hash_vector_43_vector_memory_usage();
extern Object newline_p();
extern Object obtain_simple_gensym_string();
extern Object out_8859_reverse_unicode_map_hash_vector_43_vectors();
extern Object outstanding_asian_double_byte_count();
extern Object outstanding_gb_2312_count();
extern Object outstanding_gensym_string_text_sequence_count();
extern Object outstanding_graphic_character_set_count();
extern Object outstanding_iso_2022_transcoder_count();
extern Object outstanding_iso_646_count();
extern Object outstanding_iso_8859_10_count();
extern Object outstanding_iso_8859_1_count();
extern Object outstanding_iso_8859_2_count();
extern Object outstanding_iso_8859_3_count();
extern Object outstanding_iso_8859_4_count();
extern Object outstanding_iso_8859_5_count();
extern Object outstanding_iso_8859_6_count();
extern Object outstanding_iso_8859_7_count();
extern Object outstanding_iso_8859_8_count();
extern Object outstanding_iso_8859_9_count();
extern Object outstanding_iso_8859_abstract_count();
extern Object outstanding_iso_8859_transcoder_count();
extern Object outstanding_jis_x_0208_count();
extern Object outstanding_ks_c_5601_count();
extern Object outstanding_shift_jis_transcoder_count();
extern Object outstanding_text_sequence_count();
extern Object outstanding_transcode_text_conversion_style_count();
extern Object outstanding_transcoder_count();
extern Object outstanding_unicode_byte_swapped_transcoder_count();
extern Object outstanding_unicode_transcoder_count();
extern Object outstanding_unicode_ucs_2_transcoder_count();
extern Object outstanding_utf_7_transcoder_count();
extern Object outstanding_utf_8_transcoder_count();
extern Object outstanding_utf_g_ascii_as_much_as_possible_transcoder_count();
extern Object outstanding_utf_g_transcoder_count();
extern Object outstanding_wide_string_text_sequence_count();
extern Object push_optimized_constant();
extern Object read_character_from_text_sequence_function();
extern Object read_iso_2022_escape_from_wide_string();
extern Object reclaim_8859_reverse_unicode_map();
extern Object reclaim_8859_reverse_unicode_map_hash_vector();
extern Object reclaim_8859_reverse_unicode_map_tree_for_hash_leaves();
extern Object reclaim_asian_double_byte_1();
extern Object reclaim_binary_tree_element_1();
extern Object reclaim_gb_2312_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_string_text_sequence_1();
extern Object reclaim_graphic_character_set_1();
extern Object reclaim_iso_2022_transcoder_1();
extern Object reclaim_iso_646_1();
extern Object reclaim_iso_8859_10_1();
extern Object reclaim_iso_8859_1_1();
extern Object reclaim_iso_8859_2_1();
extern Object reclaim_iso_8859_3_1();
extern Object reclaim_iso_8859_4_1();
extern Object reclaim_iso_8859_5_1();
extern Object reclaim_iso_8859_6_1();
extern Object reclaim_iso_8859_7_1();
extern Object reclaim_iso_8859_8_1();
extern Object reclaim_iso_8859_9_1();
extern Object reclaim_iso_8859_abstract_1();
extern Object reclaim_iso_8859_transcoder_1();
extern Object reclaim_jis_x_0208_1();
extern Object reclaim_ks_c_5601_1();
extern Object reclaim_shift_jis_transcoder_1();
extern Object reclaim_text_sequence_internal_1();
extern Object reclaim_text_string();
extern Object reclaim_transcode_text_conversion_style_1();
extern Object reclaim_transcoder_1();
extern Object reclaim_unicode_byte_swapped_transcoder_1();
extern Object reclaim_unicode_transcoder_1();
extern Object reclaim_unicode_ucs_2_transcoder_1();
extern Object reclaim_utf_7_transcoder_1();
extern Object reclaim_utf_8_transcoder_1();
extern Object reclaim_utf_g_ascii_as_much_as_possible_transcoder_1();
extern Object reclaim_utf_g_transcoder_1();
extern Object reclaim_wide_string();
extern Object reclaim_wide_string_text_sequence_1();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_lookup_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object set_up_iso_2022_transcoder_for_gb_2312();
extern Object set_up_iso_2022_transcoder_for_gb_2312_euc();
extern Object set_up_iso_2022_transcoder_for_jis_x_0208();
extern Object set_up_iso_2022_transcoder_for_jis_x_0208_euc();
extern Object set_up_iso_2022_transcoder_for_ks_c_5601();
extern Object set_up_iso_2022_transcoder_for_ks_c_5601_euc();
extern Object set_up_iso_2022_transcoder_for_us_ascii();
extern Object set_up_iso_2022_transcoder_for_x_compound_text();
extern Object shift_jis_transcoder_structure_memory_usage();
extern Object shift_jis_x_0208_in_text_sequence_to_unicode();
extern Object stringw();
extern Object sxhashw();
extern Object text_sequence_structure_memory_usage();
extern Object text_string_length();
extern Object transcode_as_text_string_function();
extern Object transcode_character_function();
extern Object transcode_iso_2022_c1_character();
extern Object transcode_iso_2022_graphic_character();
extern Object transcode_text_conversion_style_structure_memory_usage();
extern Object transcode_unhandled_character();
extern Object transcode_utf_7_base64();
extern Object transcoder_structure_memory_usage();
extern Object transform_utf_8_to_ucs_4();
extern Object twrite_ascii_from_wide_string();
extern Object twrite_for_export_from_transcoder_function();
extern Object twrite_intern_string_buffer_as_gensym_characters();
extern Object twrite_spaces_for_tabs();
extern Object twrite_unicode_as_utf_8();
extern Object twrite_unicode_from_transcoder_function();
extern Object twrite_utf_8_from_text_string();
extern Object twrite_utf_8_octets();
extern Object twrite_utf_g_from_text_string();
extern Object twrite_wide_character();
extern Object unicode_byte_swapped_transcoder_structure_memory_usage();
extern Object unicode_known_iso_latin1_to_gensym_string();
extern Object unicode_to_utf_8_gensym_string();
extern Object unicode_to_utf_8_wide_string();
extern Object unicode_to_utf_g_gensym_string();
extern Object unicode_to_utf_g_wide_string();
extern Object unicode_transcoder_structure_memory_usage();
extern Object unicode_ucs_2_transcoder_structure_memory_usage();
extern Object update_object_pool_meters_list();
extern Object utf_7_base64_digit_char_code_p();
extern Object utf_7_base64_digit_char_p();
extern Object utf_7_transcoder_structure_memory_usage();
extern Object utf_8_transcoder_structure_memory_usage();
extern Object utf_g_ascii_as_much_as_possible_transcoder_structure_memory_usage();
extern Object utf_g_transcoder_structure_memory_usage();
extern Object wide_string_text_sequence_structure_memory_usage();
extern Object wide_string_to_gensym_string();

#endif

/* variables/constants */
#define Ascii_replacement_character FIX((SI_Long)63L)
DECLARE_VARIABLE_WITH_SYMBOL(Asian_double_byte_count, Qasian_double_byte_count);
DECLARE_VARIABLE_WITH_SYMBOL(Available_8859_reverse_unicode_map_hash_vector_43_vectors, Qavailable_8859_reverse_unicode_map_hash_vector_43_vectors);
extern Object Available_8859_reverse_unicode_map_hash_vector_43_vectors_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_asian_double_bytes, Qchain_of_available_asian_double_bytes);
extern Object Chain_of_available_asian_double_bytes_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gb_2312s, Qchain_of_available_gb_2312s);
extern Object Chain_of_available_gb_2312s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_gensym_string_text_sequences, Qchain_of_available_gensym_string_text_sequences);
extern Object Chain_of_available_gensym_string_text_sequences_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_graphic_character_sets, Qchain_of_available_graphic_character_sets);
extern Object Chain_of_available_graphic_character_sets_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_2022_transcoders, Qchain_of_available_iso_2022_transcoders);
extern Object Chain_of_available_iso_2022_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_646s, Qchain_of_available_iso_646s);
extern Object Chain_of_available_iso_646s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_10s, Qchain_of_available_iso_8859_10s);
extern Object Chain_of_available_iso_8859_10s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_1s, Qchain_of_available_iso_8859_1s);
extern Object Chain_of_available_iso_8859_1s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_2s, Qchain_of_available_iso_8859_2s);
extern Object Chain_of_available_iso_8859_2s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_3s, Qchain_of_available_iso_8859_3s);
extern Object Chain_of_available_iso_8859_3s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_4s, Qchain_of_available_iso_8859_4s);
extern Object Chain_of_available_iso_8859_4s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_5s, Qchain_of_available_iso_8859_5s);
extern Object Chain_of_available_iso_8859_5s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_6s, Qchain_of_available_iso_8859_6s);
extern Object Chain_of_available_iso_8859_6s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_7s, Qchain_of_available_iso_8859_7s);
extern Object Chain_of_available_iso_8859_7s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_8s, Qchain_of_available_iso_8859_8s);
extern Object Chain_of_available_iso_8859_8s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_9s, Qchain_of_available_iso_8859_9s);
extern Object Chain_of_available_iso_8859_9s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_abstracts, Qchain_of_available_iso_8859_abstracts);
extern Object Chain_of_available_iso_8859_abstracts_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_iso_8859_transcoders, Qchain_of_available_iso_8859_transcoders);
extern Object Chain_of_available_iso_8859_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_jis_x_0208s, Qchain_of_available_jis_x_0208s);
extern Object Chain_of_available_jis_x_0208s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_ks_c_5601s, Qchain_of_available_ks_c_5601s);
extern Object Chain_of_available_ks_c_5601s_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_shift_jis_transcoders, Qchain_of_available_shift_jis_transcoders);
extern Object Chain_of_available_shift_jis_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_text_sequences, Qchain_of_available_text_sequences);
extern Object Chain_of_available_text_sequences_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_transcode_text_conversion_styles, Qchain_of_available_transcode_text_conversion_styles);
extern Object Chain_of_available_transcode_text_conversion_styles_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_transcoders, Qchain_of_available_transcoders);
extern Object Chain_of_available_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_unicode_byte_swapped_transcoders, Qchain_of_available_unicode_byte_swapped_transcoders);
extern Object Chain_of_available_unicode_byte_swapped_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_unicode_transcoders, Qchain_of_available_unicode_transcoders);
extern Object Chain_of_available_unicode_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_unicode_ucs_2_transcoders, Qchain_of_available_unicode_ucs_2_transcoders);
extern Object Chain_of_available_unicode_ucs_2_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_utf_7_transcoders, Qchain_of_available_utf_7_transcoders);
extern Object Chain_of_available_utf_7_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_utf_8_transcoders, Qchain_of_available_utf_8_transcoders);
extern Object Chain_of_available_utf_8_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_utf_g_ascii_as_much_as_possible_transcoders, Qchain_of_available_utf_g_ascii_as_much_as_possible_transcoders);
extern Object Chain_of_available_utf_g_ascii_as_much_as_possible_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_utf_g_transcoders, Qchain_of_available_utf_g_transcoders);
extern Object Chain_of_available_utf_g_transcoders_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_wide_string_text_sequences, Qchain_of_available_wide_string_text_sequences);
extern Object Chain_of_available_wide_string_text_sequences_vector;
extern Object Chinese_han_x_compound_text_character_set_selection_list;
DECLARE_VARIABLE_WITH_SYMBOL(Column, Qcolumn);
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_8859_reverse_unicode_map_hash_vector_43_vectors, Qcount_of_8859_reverse_unicode_map_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Current_extended_utf_g_low_half_character_qm, Qcurrent_extended_utf_g_low_half_character_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
extern Object Default_han_x_compound_text_character_set_selection_list;
DECLARE_VARIABLE_WITH_SYMBOL(Default_text_conversion_style, Qdefault_text_conversion_style);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(G2_operating_system, Qg2_operating_system);
extern Object Gb_2312_character_set_selection_list;
DECLARE_VARIABLE_WITH_SYMBOL(Gb_2312_count, Qgb_2312_count);
extern Object Gb_2312_euc_character_set_selection_list;
extern Object Gb_2312_to_unicode_map;
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_linebreak, Qgensym_char_or_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_char_or_code_for_paragraph_break, Qgensym_char_or_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_bullet, Qgensym_code_for_bullet);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_capital_ligature_oe, Qgensym_code_for_capital_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_linebreak, Qgensym_code_for_linebreak);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_paragraph_break, Qgensym_code_for_paragraph_break);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_letter_f_with_hook, Qgensym_code_for_small_letter_f_with_hook);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_small_ligature_oe, Qgensym_code_for_small_ligature_oe);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_code_for_trade_mark_sign, Qgensym_code_for_trade_mark_sign);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_linebreak_qm, Qgensym_esc_for_linebreak_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_esc_for_paragraph_break_qm, Qgensym_esc_for_paragraph_break_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_string_text_sequence_count, Qgensym_string_text_sequence_count);
extern Object Gensym_to_unicode_full_row_map;
DECLARE_VARIABLE_WITH_SYMBOL(Graphic_character_set_count, Qgraphic_character_set_count);
extern Object Graphic_character_set_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Intern_string_buffer, Qintern_string_buffer);
#define Intern_string_buffer_length FIX((SI_Long)32L)
#define Invalid_gensym_full_row FIX((SI_Long)246L)
#define Invalid_unicode_full_row FIX((SI_Long)7L)
DECLARE_VARIABLE_WITH_SYMBOL(Iso_2022_transcoder_count, Qiso_2022_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_646_count, Qiso_646_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_10_count, Qiso_8859_10_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_1_count, Qiso_8859_1_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_2_count, Qiso_8859_2_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_3_count, Qiso_8859_3_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_4_count, Qiso_8859_4_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_5_count, Qiso_8859_5_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_6_count, Qiso_8859_6_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_7_count, Qiso_8859_7_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_8_count, Qiso_8859_8_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_9_count, Qiso_8859_9_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_abstract_count, Qiso_8859_abstract_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_8859_transcoder_count, Qiso_8859_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Iso_latin1_special_character_code_map, Qiso_latin1_special_character_code_map);
extern Object Japanese_han_x_compound_text_character_set_selection_list;
extern Object Jis_x_0208_character_set_selection_list;
DECLARE_VARIABLE_WITH_SYMBOL(Jis_x_0208_count, Qjis_x_0208_count);
extern Object Jis_x_0208_euc_character_set_selection_list;
extern Object Jis_x_0208_to_unicode_map;
extern Object Korean_han_x_compound_text_character_set_selection_list;
extern Object Ks_c_5601_character_set_selection_list;
DECLARE_VARIABLE_WITH_SYMBOL(Ks_c_5601_count, Qks_c_5601_count);
extern Object Ks_c_5601_euc_character_set_selection_list;
extern Object Ks_c_5601_to_unicode_map;
extern Object No_han_x_compound_text_character_set_selection_list;
#define Pct_bs FIX((SI_Long)92L)
#define Pct_tl FIX((SI_Long)126L)
DECLARE_VARIABLE_WITH_SYMBOL(Reverse_iso_latin1_special_character_code_map, Qreverse_iso_latin1_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Row, Qrow);
DECLARE_VARIABLE_WITH_SYMBOL(Shift_jis_transcoder_count, Qshift_jis_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Standard_8_bit_non_graphic_characters_skip_spec, Qstandard_8_bit_non_graphic_characters_skip_spec);
extern Object Text_conversion_style_for_purpose_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Text_conversion_style_for_transcoder_being_created, Qtext_conversion_style_for_transcoder_being_created);
DECLARE_VARIABLE_WITH_SYMBOL(Text_sequence_count, Qtext_sequence_count);
extern Object The_type_description_of_asian_double_byte;
extern Object The_type_description_of_gb_2312;
extern Object The_type_description_of_gensym_string_text_sequence;
extern Object The_type_description_of_graphic_character_set;
extern Object The_type_description_of_iso_2022_transcoder;
extern Object The_type_description_of_iso_646;
extern Object The_type_description_of_iso_8859_1;
extern Object The_type_description_of_iso_8859_10;
extern Object The_type_description_of_iso_8859_2;
extern Object The_type_description_of_iso_8859_3;
extern Object The_type_description_of_iso_8859_4;
extern Object The_type_description_of_iso_8859_5;
extern Object The_type_description_of_iso_8859_6;
extern Object The_type_description_of_iso_8859_7;
extern Object The_type_description_of_iso_8859_8;
extern Object The_type_description_of_iso_8859_9;
extern Object The_type_description_of_iso_8859_abstract;
extern Object The_type_description_of_iso_8859_transcoder;
extern Object The_type_description_of_jis_x_0208;
extern Object The_type_description_of_ks_c_5601;
extern Object The_type_description_of_shift_jis_transcoder;
extern Object The_type_description_of_text_sequence;
extern Object The_type_description_of_transcode_text_conversion_style;
extern Object The_type_description_of_transcoder;
extern Object The_type_description_of_unicode_byte_swapped_transcoder;
extern Object The_type_description_of_unicode_transcoder;
extern Object The_type_description_of_unicode_ucs_2_transcoder;
extern Object The_type_description_of_utf_7_transcoder;
extern Object The_type_description_of_utf_8_transcoder;
extern Object The_type_description_of_utf_g_ascii_as_much_as_possible_transcoder;
extern Object The_type_description_of_utf_g_transcoder;
extern Object The_type_description_of_wide_string_text_sequence;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Transcode_text_conversion_style_count, Qtranscode_text_conversion_style_count);
DECLARE_VARIABLE_WITH_SYMBOL(Transcoder_count, Qtranscoder_count);
extern Object Transcoder_creation_function_prop;
DECLARE_VARIABLE_WITH_SYMBOL(Ucs_4_to_utf_8_1st_octet_table, Qucs_4_to_utf_8_1st_octet_table);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_byte_swapped_transcoder_count, Qunicode_byte_swapped_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_offset_for_gensym_cyrillic, Qunicode_offset_for_gensym_cyrillic);
#define Unicode_replacement_character FIX((SI_Long)65533L)
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_to_gb_2312_map, Qunicode_to_gb_2312_map);
extern Object Unicode_to_gensym_full_row_map;
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_to_jis_x_0208_map, Qunicode_to_jis_x_0208_map);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_to_ks_c_5601_map, Qunicode_to_ks_c_5601_map);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_transcoder_count, Qunicode_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Unicode_ucs_2_transcoder_count, Qunicode_ucs_2_transcoder_count);
extern Object Us_ascii_character_set_selection_list;
extern Object Utf_7_delimit_encoded_sequences_p;
extern Object Utf_7_modified_base64_characters;
DECLARE_VARIABLE_WITH_SYMBOL(Utf_7_transcoder_count, Qutf_7_transcoder_count);
extern Object Utf_7_ultraconservative_p;
DECLARE_VARIABLE_WITH_SYMBOL(Utf_8_transcoder_count, Qutf_8_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Utf_g_ascii_as_much_as_possible_conversion_style, Qutf_g_ascii_as_much_as_possible_conversion_style);
DECLARE_VARIABLE_WITH_SYMBOL(Utf_g_ascii_as_much_as_possible_transcoder_count, Qutf_g_ascii_as_much_as_possible_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Utf_g_transcoder_count, Qutf_g_transcoder_count);
DECLARE_VARIABLE_WITH_SYMBOL(Wide_string_text_sequence_count, Qwide_string_text_sequence_count);
