/* utlts1.h -- Header File for utlts1.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Kadjustable;
extern Object Qchar_eq;
extern Object Qcons;
extern Object Kelement_type;
extern Object Kfill_pointer;
extern Object Kinitial_contents;
extern Object Kinitial_element;
extern Object Kname;
extern Object Qstring;
extern Object Qstring_char;
extern Object Ktest;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object allocate_managed_simple_vector(Object);
extern Object allocate_new_adjustable_gensym_string(Object);
extern Object allocate_new_simple_gensym_string(Object,Object);
extern Object allocate_small_2d_array(Object);
extern Object allocated_named_gensym_structure_p(Object);
extern Object assq_function(Object,Object);
extern Object begins_with_vowel_qm(Object);
extern Object block_p_function(Object);
extern Object buffer_size_and_pool_for_partial_buffer(Object,Object);
extern Object buffer_size_for_partial_buffer(Object,Object);
extern Object bytes_per_simple_string(Object);
extern Object charw_function(Object,Object);
extern Object check_keyword_list_syntax(Object,Object);
extern Object clear_optimized_constants(void);
extern Object compute_memory_used_by_adjustable_gensym_strings(void);
extern Object compute_memory_used_by_simple_gensym_strings(void);
extern Object copy_current_gensym_string(Object);
extern Object copy_gensym_string(Object);
extern Object copy_gensym_string_into_simple_or_adjustable_gensym_string(Object);
extern Object copy_gensym_string_portion(Object,Object,Object);
extern Object copy_gensym_tree_with_text_strings(Object);
extern Object copy_illegal_gensym_string_without_bad_characters(Object);
extern Object copy_list_using_string_pool_conses_1(Object);
extern Object copy_null_terminated_string_as_gensym_string(Object);
extern Object copy_out_current_gensym_string(void);
extern Object copy_partial_gensym_string(Object,Object);
extern Object copy_portion_of_string_into_gensym_string(Object,Object,Object,Object,Object);
extern Object copy_portion_of_string_into_simple_gensym_string(Object,Object,Object,Object,Object);
extern Object copy_string_filtering_out_non_gensym_characters(Object);
extern Object copy_text_string(Object);
extern Object copy_tree_using_string_pool_conses_1(Object);
extern Object db_format(int,...);
extern Object delete_string_pool_cons_1(Object,Object);
extern Object delete_string_pool_element_1(Object,Object);
extern Object denote_component_of_block(int,...);
extern Object extend_current_gensym_string(int,...);
extern Object find_gensym_character_in_list(Object,Object);
extern Object find_gensym_character_in_sequence(Object,Object);
extern Object find_in_gensym_string(Object,Object);
extern Object framep_function(Object);
extern Object free_malloced_strings(void);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_string_substring(Object,Object,Object);
extern Object get_or_make_up_designation_for_block(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object length_of_null_terminated_string(Object);
extern Object lengthw(Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_partial_buffer_info(Object,Object,Object,Object);
extern Object make_string_pool_list_1(Object);
extern Object make_structure_method_table(Object);
extern Object maximum_gensym_string_length_error(Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object new_partial_buffer_gensym_string_vector(Object);
extern Object new_short_simple_gensym_string_vector(Object);
extern Object obtain_adjustable_gensym_string(void);
extern Object obtain_long_enough_adjustable_gensym_string(Object);
extern Object obtain_simple_gensym_string(Object);
extern Object obtain_simple_gensym_string_of_quantized_length(Object);
extern Object outstanding_adjustable_gensym_strings(void);
extern Object outstanding_simple_gensym_strings(void);
extern Object outstanding_string_pool_conses(void);
extern Object parse_ascii_text_line_given_grouping_bag(Object,Object,Object,Object,Object,Object);
extern Object parse_ascii_text_line_into_list_of_ascii_strings_function(Object,Object,Object,Object,Object,Object);
extern Object parse_colon_delimited_ascii_text_line_into_list_of_ascii_strings(Object);
extern Object parse_space_delimited_ascii_text_line_into_list_of_ascii_strings(Object);
extern Object partial_buffer_pool_index_given_length(Object,Object);
extern Object pm_prin1(Object);
extern Object position_in_gensym_string(Object,Object);
extern Object position_of_ascii_character_in_bag_function(Object,Object,Object,Object);
extern Object position_of_ascii_character_not_in_bag_from_end_function(Object,Object,Object,Object);
extern Object position_of_ascii_character_not_in_bag_function(Object,Object,Object,Object);
extern Object print_constant(int,...);
extern Object print_designation(Object);
extern Object push_optimized_constant(Object);
extern Object reclaim_adjustable_gensym_string(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_string(Object);
extern Object reclaim_gensym_strings_in_list(Object);
extern Object reclaim_gensym_tree_with_text_strings(Object);
extern Object reclaim_if_gensym_string_function(Object);
extern Object reclaim_simple_gensym_string(Object);
extern Object reclaim_string_pool_cons_1(Object);
extern Object reclaim_string_pool_list_1(Object);
extern Object reclaim_string_pool_list_star_1(Object);
extern Object reclaim_string_pool_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object replenish_string_pool_cons_pool(void);
extern Object replenish_string_pool_list_pool(Object);
extern Object report_simple_string_allocation(Object);
extern Object report_simple_string_reclamation(Object,Object);
extern Object require_simple_gensym_string(Object);
extern Object set_malloced_string_threshhold(Object);
extern Object string_pool_cons_1(Object,Object);
extern Object string_pool_cons_memory_usage(void);
extern Object string_pool_list_2(Object,Object);
extern Object string_pool_list_3(Object,Object,Object);
extern Object string_pool_list_4(Object,Object,Object,Object);
extern Object string_pool_list_trace_hook(Object);
extern Object subtype_p_using_type_descriptions(Object,Object);
extern Object sum_reclaimed_strings(Object);
extern Object supply_a_or_an(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_gensym_string(int,...);
extern Object tprin(Object,Object);
extern Object twrite(Object);
extern Object twrite_character(Object);
extern Object twrite_designation_for_item(Object);
extern Object twrite_fixnum(Object);
extern Object twrite_general_string(Object);
extern Object twrite_line_break(void);
extern Object twrite_line_separator(void);
extern Object twrite_list_function(Object,Object,Object,Object,Object);
extern Object twrite_n_spaces(Object);
extern Object twrite_parsably(Object);
extern Object twrite_positive_bignum(Object);
extern Object twrite_positive_bignum_in_radix(Object,Object);
extern Object twrite_positive_fixnum_in_radix(Object,Object);
extern Object twrite_spaces_if_necessary(Object,Object);
extern Object twrite_symbol(int,...);
extern Object twrite_wide_character(Object);
extern Object type_description_of(Object);
extern Object undefined_structure_method_function(int,...);
extern Object update_object_pool_meters_list(Object);
extern Object wide_character_member(Object,Object);
extern Object write_block_or_evaluation_value(int,...);
extern Object write_error_text(Object);
extern Object write_evaluation_value(int,...);
extern Object write_expression(Object);
extern Object write_floating_point_number_simple_c_format(int,...);
extern Object write_gensym_pathname(Object);
extern Object write_name_denotation(Object);
extern Object write_name_denotation_components(Object,Object);
extern Object write_name_denotation_for_slot(Object,Object);
extern Object write_random_s_expression(Object);
extern Object write_s_expression(Object);
extern Object write_symbol_list(int,...);
extern Object write_type_specification(Object);

#else

extern Object allocate_managed_simple_vector();
extern Object allocate_new_adjustable_gensym_string();
extern Object allocate_new_simple_gensym_string();
extern Object allocate_small_2d_array();
extern Object allocated_named_gensym_structure_p();
extern Object assq_function();
extern Object begins_with_vowel_qm();
extern Object block_p_function();
extern Object buffer_size_and_pool_for_partial_buffer();
extern Object buffer_size_for_partial_buffer();
extern Object bytes_per_simple_string();
extern Object charw_function();
extern Object check_keyword_list_syntax();
extern Object clear_optimized_constants();
extern Object compute_memory_used_by_adjustable_gensym_strings();
extern Object compute_memory_used_by_simple_gensym_strings();
extern Object copy_current_gensym_string();
extern Object copy_gensym_string();
extern Object copy_gensym_string_into_simple_or_adjustable_gensym_string();
extern Object copy_gensym_string_portion();
extern Object copy_gensym_tree_with_text_strings();
extern Object copy_illegal_gensym_string_without_bad_characters();
extern Object copy_list_using_string_pool_conses_1();
extern Object copy_null_terminated_string_as_gensym_string();
extern Object copy_out_current_gensym_string();
extern Object copy_partial_gensym_string();
extern Object copy_portion_of_string_into_gensym_string();
extern Object copy_portion_of_string_into_simple_gensym_string();
extern Object copy_string_filtering_out_non_gensym_characters();
extern Object copy_text_string();
extern Object copy_tree_using_string_pool_conses_1();
extern Object db_format();
extern Object delete_string_pool_cons_1();
extern Object delete_string_pool_element_1();
extern Object denote_component_of_block();
extern Object extend_current_gensym_string();
extern Object find_gensym_character_in_list();
extern Object find_gensym_character_in_sequence();
extern Object find_in_gensym_string();
extern Object framep_function();
extern Object free_malloced_strings();
extern Object gensym_cons_1();
extern Object gensym_string_substring();
extern Object get_or_make_up_designation_for_block();
extern Object getfq_function_no_default();
extern Object length_of_null_terminated_string();
extern Object lengthw();
extern Object make_named_dynamic_extent_description();
extern Object make_partial_buffer_info();
extern Object make_string_pool_list_1();
extern Object make_structure_method_table();
extern Object maximum_gensym_string_length_error();
extern Object memq_function();
extern Object mutate_global_property();
extern Object new_partial_buffer_gensym_string_vector();
extern Object new_short_simple_gensym_string_vector();
extern Object obtain_adjustable_gensym_string();
extern Object obtain_long_enough_adjustable_gensym_string();
extern Object obtain_simple_gensym_string();
extern Object obtain_simple_gensym_string_of_quantized_length();
extern Object outstanding_adjustable_gensym_strings();
extern Object outstanding_simple_gensym_strings();
extern Object outstanding_string_pool_conses();
extern Object parse_ascii_text_line_given_grouping_bag();
extern Object parse_ascii_text_line_into_list_of_ascii_strings_function();
extern Object parse_colon_delimited_ascii_text_line_into_list_of_ascii_strings();
extern Object parse_space_delimited_ascii_text_line_into_list_of_ascii_strings();
extern Object partial_buffer_pool_index_given_length();
extern Object pm_prin1();
extern Object position_in_gensym_string();
extern Object position_of_ascii_character_in_bag_function();
extern Object position_of_ascii_character_not_in_bag_from_end_function();
extern Object position_of_ascii_character_not_in_bag_function();
extern Object print_constant();
extern Object print_designation();
extern Object push_optimized_constant();
extern Object reclaim_adjustable_gensym_string();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_string();
extern Object reclaim_gensym_strings_in_list();
extern Object reclaim_gensym_tree_with_text_strings();
extern Object reclaim_if_gensym_string_function();
extern Object reclaim_simple_gensym_string();
extern Object reclaim_string_pool_cons_1();
extern Object reclaim_string_pool_list_1();
extern Object reclaim_string_pool_list_star_1();
extern Object reclaim_string_pool_tree_1();
extern Object reclaim_text_string();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object replenish_string_pool_cons_pool();
extern Object replenish_string_pool_list_pool();
extern Object report_simple_string_allocation();
extern Object report_simple_string_reclamation();
extern Object require_simple_gensym_string();
extern Object set_malloced_string_threshhold();
extern Object string_pool_cons_1();
extern Object string_pool_cons_memory_usage();
extern Object string_pool_list_2();
extern Object string_pool_list_3();
extern Object string_pool_list_4();
extern Object string_pool_list_trace_hook();
extern Object subtype_p_using_type_descriptions();
extern Object sum_reclaimed_strings();
extern Object supply_a_or_an();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_gensym_string();
extern Object tprin();
extern Object twrite();
extern Object twrite_character();
extern Object twrite_designation_for_item();
extern Object twrite_fixnum();
extern Object twrite_general_string();
extern Object twrite_line_break();
extern Object twrite_line_separator();
extern Object twrite_list_function();
extern Object twrite_n_spaces();
extern Object twrite_parsably();
extern Object twrite_positive_bignum();
extern Object twrite_positive_bignum_in_radix();
extern Object twrite_positive_fixnum_in_radix();
extern Object twrite_spaces_if_necessary();
extern Object twrite_symbol();
extern Object twrite_wide_character();
extern Object type_description_of();
extern Object undefined_structure_method_function();
extern Object update_object_pool_meters_list();
extern Object wide_character_member();
extern Object write_block_or_evaluation_value();
extern Object write_error_text();
extern Object write_evaluation_value();
extern Object write_expression();
extern Object write_floating_point_number_simple_c_format();
extern Object write_gensym_pathname();
extern Object write_name_denotation();
extern Object write_name_denotation_components();
extern Object write_name_denotation_for_slot();
extern Object write_random_s_expression();
extern Object write_s_expression();
extern Object write_symbol_list();
extern Object write_type_specification();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_string_byte_use_counter, Qadjustable_gensym_string_byte_use_counter);
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_string_counter, Qadjustable_gensym_string_counter);
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_string_counts, Qadjustable_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Adjustable_gensym_strings, Qadjustable_gensym_strings);
DECLARE_VARIABLE_WITH_SYMBOL(Available_string_pool_conses, Qavailable_string_pool_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Available_string_pool_conses_tail, Qavailable_string_pool_conses_tail);
extern Object Available_string_pool_conses_tail_vector;
extern Object Available_string_pool_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
extern Object Bytes_per_rtl_ptr;
DECLARE_VARIABLE_WITH_SYMBOL(Calling_tformat_for_give_warning_qm, Qcalling_tformat_for_give_warning_qm);
extern Object Cons_pool_conses_to_make_at_a_time;
DECLARE_VARIABLE_WITH_SYMBOL(Current_custom_reclamation_stamp_qm, Qcurrent_custom_reclamation_stamp_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
extern Object Extend_current_gensym_string_error_message;
DECLARE_VARIABLE_WITH_SYMBOL(Filename_of_module_being_loaded_qm, Qfilename_of_module_being_loaded_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Free_malloced_arrays, Qfree_malloced_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(In_text_for_item_or_value_p, Qin_text_for_item_or_value_p);
DECLARE_VARIABLE_WITH_SYMBOL(Largest_non_malloced_string_pool_index, Qlargest_non_malloced_string_pool_index);
DECLARE_VARIABLE_WITH_SYMBOL(Log_simple_string_data, Qlog_simple_string_data);
DECLARE_VARIABLE_WITH_SYMBOL(Log_simple_string_reclaims, Qlog_simple_string_reclaims);
DECLARE_VARIABLE_WITH_SYMBOL(Long_simple_gensym_string_counts, Qlong_simple_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Long_simple_gensym_strings, Qlong_simple_gensym_strings);
extern Object Maximum_gensym_string_length;
extern Object Maximum_gensym_string_length_exceeded_message;
#define Maximum_length_for_user_gensym_strings FIX((SI_Long)400000000L)
#define Maximum_managed_simple_vector_size FIX((SI_Long)1024L)
extern Object Maximum_number_of_structure_methods;
extern Object Maximum_suggested_length_for_simple_gensym_strings;
DECLARE_VARIABLE_WITH_SYMBOL(Min_string_length_to_report, Qmin_string_length_to_report);
extern Object Most_negative_int64;
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
DECLARE_VARIABLE_WITH_SYMBOL(Outputting_to_gensym_string, Qoutputting_to_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Roman_font_special_character_code_map, Qroman_font_special_character_code_map);
DECLARE_VARIABLE_WITH_SYMBOL(Short_simple_gensym_string_counts, Qshort_simple_gensym_string_counts);
DECLARE_VARIABLE_WITH_SYMBOL(Short_simple_gensym_strings, Qshort_simple_gensym_strings);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_gensym_string_byte_use_counter, Qsimple_gensym_string_byte_use_counter);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_gensym_string_counter, Qsimple_gensym_string_counter);
extern Object String_allocation_schemes;
DECLARE_VARIABLE_WITH_SYMBOL(String_allocations_until_next_report, Qstring_allocations_until_next_report);
DECLARE_VARIABLE_WITH_SYMBOL(String_chars_to_print, Qstring_chars_to_print);
DECLARE_VARIABLE_WITH_SYMBOL(String_pool_cons_counter, Qstring_pool_cons_counter);
extern Object String_pool_cons_counter_vector;
DECLARE_VARIABLE_WITH_SYMBOL(String_pool_number_to_malloc, Qstring_pool_number_to_malloc);
DECLARE_VARIABLE_WITH_SYMBOL(String_reclaims_until_next_report, Qstring_reclaims_until_next_report);
DECLARE_VARIABLE_WITH_SYMBOL(String_report_frequency, Qstring_report_frequency);
DECLARE_VARIABLE_WITH_SYMBOL(Table_to_map_structure_id_to_method_name, Qtable_to_map_structure_id_to_method_name);
DECLARE_VARIABLE_WITH_SYMBOL(Tformat_fresh_line_is_newline_p, Qtformat_fresh_line_is_newline_p);
DECLARE_VARIABLE_WITH_SYMBOL(The_g2_defstruct_package, Qthe_g2_defstruct_package);
DECLARE_VARIABLE_WITH_SYMBOL(The_type_description_of_t, Qthe_type_description_of_t);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
extern Object Type_description_of_type_prop;
extern Object Type_description_of_unique_type_name_of_gensym_structure_prop;
extern Object Undefined_structure_method_message;
DECLARE_VARIABLE_WITH_SYMBOL(Write_strings_parsably_qm, Qwrite_strings_parsably_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_in_lower_case_qm, Qwrite_symbols_in_lower_case_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Write_symbols_parsably_qm, Qwrite_symbols_parsably_qm);
