/* vrbls.h -- Header File for vrbls.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qnum_eq;
extern Object Qand;
extern Object Qblock;
extern Object Qcount;
extern Object Qdouble_float;
extern Object Qeq;
extern Object Qeval;
extern Object Qfloat;
extern Object Kinitial_element;
extern Object Qinteger;
extern Object Qlist;
extern Object Qnumber;
extern Object Qquote;
extern Object Qthe;
extern Object Qunsigned_byte;
extern Object Qvariable;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object absorb_data_server_aliases(Object,Object);
extern Object activate_subclass_of_entity_for_parameter(Object);
extern Object activate_subclass_of_entity_for_variable(Object);
extern Object add_class_to_environment(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_indexed_attribute_properties(Object,Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_managed_simple_vector(Object);
extern Object allocate_managed_simple_vector_for_skip_list(Object);
extern Object assq_function(Object,Object);
extern Object attempt_new_variable_value_collection(Object,Object,Object);
extern Object begin_collecting_data_for_inference_engine(Object,Object);
extern Object break_out_of_debug_messages(void);
extern Object buffer_size_for_partial_buffer(Object,Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object bytes_per_typed_simple_array(Object,Object);
extern Object cache_explanation(Object);
extern Object cache_explanation_variables(Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object cancel_formula_for_backward_chaining(Object);
extern Object change_slot_description_value_function(Object,Object,Object,Object,Object);
extern Object change_slot_value(int,...);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object circular_variable_interests_1(Object,Object);
extern Object clean_up_wake_ups_state_if_any(void);
extern Object cleanup_for_generic_formula(Object);
extern Object cleanup_for_object(Object);
extern Object cleanup_for_parameter(Object);
extern Object cleanup_for_variable(Object);
extern Object clear_currently_evaluating_formula_after_bombout(void);
extern Object clear_histories(Object);
extern Object clear_indexed_attribute_defining_classes_skip_list(Object);
extern Object clear_indexed_attribute_hash_table(Object);
extern Object clear_indexed_attribute_parent_objects(Object);
extern Object clear_indexed_attribute_parent_objects_tree(Object);
extern Object clear_items_needing_initialization_tree(Object);
extern Object clear_optimized_constants(void);
extern Object clear_pending_wake_ups(void);
extern Object collect_all_indexed_attributes_for_class(Object);
extern Object collect_all_indexed_attributes_for_object(Object);
extern Object collect_subclasses(Object);
extern Object compilations_up_to_date_p(Object);
extern Object compile_data_server_aliases_for_slot(int,...);
extern Object compute_newer_value_of_variable(Object,Object);
extern Object compute_text_hash_code(Object);
extern Object constant_queue_push_right(Object,Object);
extern Object copy_data_server(Object);
extern Object copy_data_servers_for_process(void);
extern Object copy_evaluation_value_1(Object);
extern Object copy_explanation_variables(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_list_using_eval_conses_1(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_tree_using_eval_conses_1(Object);
extern Object copy_wide_string(Object);
extern Object data_server_requests_accept_data_calls(Object);
extern Object data_server_structure_memory_usage(void);
extern Object data_type_of_variable_or_parameter_function(Object);
extern Object deactivate_subclass_of_entity_for_parameter(Object);
extern Object deactivate_subclass_of_entity_for_variable(Object);
extern Object def_bombout_clean_up_function(Object);
extern Object def_data_server(int,...);
extern Object def_data_server_pretty_printer(Object,Object);
extern Object deinstall_system_table_for_data_server_parameters(Object);
extern Object delete_backward_chaining_display_if_any_for_variable(Object);
extern Object delete_dynamic_rule_displays_for_rule_or_object(Object);
extern Object delete_eval_element_1(Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_skip_list_entry(Object,Object,Object,Object,Object);
extern Object denote_cell_array_element_for_generic_formula(Object,Object,Object);
extern Object denote_cell_array_element_for_variable(Object,Object,Object);
extern Object denote_component_of_block_1(Object,Object);
extern Object designation_operator_or_giver_of_value_p(Object);
extern Object direct_structure_method(Object,Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object eval_cons_1(Object,Object);
extern Object evaluation_value_eql(int,...);
extern Object evaluation_value_equal_p(Object,Object);
extern Object evaluation_value_of_type_p(Object,Object);
extern Object evaluation_value_type(Object);
extern Object evaluation_value_value(Object);
extern Object exit_computation_context_for_variable_formula(Object);
extern Object expression_cell_updated_for_generic_formula(Object,Object,Object,Object,Object);
extern Object expression_cell_updated_for_variable(Object,Object,Object,Object,Object);
extern Object expression_may_use_indexed_attribute_p(Object);
extern Object extend_current_gensym_string(int,...);
extern Object find_generic_formula(Object,Object);
extern Object fix_up_initial_value_of_variable_or_parameter(int,...);
extern Object flatten_indexed_attribute_parent_objects(Object);
extern Object flatten_skip_list(Object);
extern Object formula_invocation_structure_memory_usage(void);
extern Object frame_hash_function(Object);
extern Object frame_serial_number_equal_function(Object,Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object future_task_schedule_2(Object);
extern Object g2_cell_array_managed_array_function(Object);
extern Object g2_enterprise_p(void);
extern Object g2_expression_cell_byte_code_body_function(Object);
extern Object g2_list_empty_p(Object);
extern Object g2_list_insert_at_end(int,...);
extern Object g2_priority_of_data_service_function(void);
extern Object generate_float_vector(Object);
extern Object generate_standard_error_message(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_list_2(Object,Object);
extern Object gensym_list_3(Object,Object,Object);
extern Object get_and_validate_indexed_attribute_value(Object);
extern Object get_class_feature_if_any(Object,Object);
extern Object get_current_evaluation_value(Object,Object);
extern Object get_current_value(Object,Object);
extern Object get_data_type_of_variable_or_parameter_from_frame(int,...);
extern Object get_defining_class_for_parent_attribute_if_any(Object);
extern Object get_item_or_item_list_for_uuid(Object);
extern Object get_kb_parent_information(Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_or_make_history_buffer(Object,Object);
extern Object get_or_make_simulation_runtime_cache(Object,Object,Object);
extern Object get_pretty_slot_name_for_parent_attribute_if_any(Object);
extern Object get_slot_description(int,...);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_description_value(Object,Object);
extern Object get_slot_init_form(int,...);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_slot_value_if_any_function(Object,Object,Object);
extern Object getfq_function_no_default(Object,Object);
extern Object give_warning_1(int,...);
extern Object handle_formula_invocation_error(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object handle_update_to_indexed_attribute(Object,Object,Object,Object,Object,Object);
extern Object handle_update_to_sensor_data_type(Object);
extern Object increment_profiling_calls(Object);
extern Object indexed_attribute_or_inherited_attribute_for_class_p(Object,Object);
extern Object indexed_attribute_or_inherited_attribute_p(Object,Object,Object);
extern Object indexed_attribute_parent_objects_hash_vector_43_vector_memory_usage(void);
extern Object inference_background_collection_structure_memory_usage(void);
extern Object initialize_after_reading_for_variable_or_parameter(Object);
extern Object initialize_data_server_properties(void);
extern Object initialize_for_generic_formula(Object);
extern Object initialize_for_parameter(Object);
extern Object initialize_for_variable_or_parameter(Object);
extern Object initialize_or_shut_down_g2_meter_data_server(Object);
extern Object insert_indexed_attribute_items_in_list(Object,Object,Object,Object);
extern Object install_system_table_for_data_server_parameters(Object);
extern Object install_true_value_update(Object,Object,Object,Object,Object);
extern Object invoke_rules_for_backward_chaining(Object);
extern Object invoke_rules_for_failure_chaining(Object);
extern Object invoke_rules_for_forward_chaining(Object,Object,Object,Object,Object);
extern Object invoke_update_functions_for_expired_value(Object,Object);
extern Object invoke_update_functions_for_put_has_no_current_value(Object,Object);
extern Object invoke_user_defined_default_error_handler(Object,Object);
extern Object is_a_formula_invocation_qm(Object);
extern Object item_to_profile_of_formula_invocation(Object);
extern Object load_and_initialize_type_description(Object,Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object make_all_indexed_attribute_hash_tables(void);
extern Object make_data_server_1(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object make_empty_expression_cell(Object);
extern Object make_evaluation_value_1(Object,Object);
extern Object make_formula_invocation_1(Object,Object,Object);
extern Object make_frame(Object);
extern Object make_indexed_attribute_defining_classes_skip_list_sentinel(Object,Object);
extern Object make_indexed_attribute_hash_table(Object);
extern Object make_indexed_attribute_parent_objects(void);
extern Object make_indexed_attribute_parent_objects_hash_vector(void);
extern Object make_indexed_attribute_parent_objects_tree_for_hash_skip_list_sentinel(Object,Object);
extern Object make_inference_background_collection_1(Object);
extern Object make_items_needing_initialization_skip_list_sentinel(Object,Object);
extern Object make_permanent_data_server_structure_internal(void);
extern Object make_permanent_formula_invocation_structure_internal(void);
extern Object make_permanent_indexed_attribute_parent_objects_hash_vector_43_vector_internal(void);
extern Object make_permanent_inference_background_collection_structure_internal(void);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_simulation_info_structure_internal(void);
extern Object make_permanent_variable_simulation_runtime_structure_structure_internal(void);
extern Object make_simulation_info_1(void);
extern Object make_skip_list_element_1(Object,Object,Object,Object);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_thread_array(Object);
extern Object make_variable_simulation_runtime_structure_1(void);
extern Object maximize_priority_of_rule_instance(Object,Object);
extern Object maximize_priority_of_variable(Object,Object);
extern Object memq_function(Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object mutate_indexed_attribute_defining_classes_skip_list_entry(Object,Object,Object);
extern Object mutate_indexed_attribute_parent_objects_tree_for_hash_skip_list_entry(Object,Object,Object);
extern Object mutate_items_needing_initialization_skip_list_entry(Object,Object,Object);
extern Object mutate_kb_specific_property_value(Object,Object,Object);
extern Object normalize_to_gensym_float(Object);
extern Object note_change_to_block_1(Object,Object);
extern Object note_change_to_runtime_data_for_block_1(Object);
extern Object note_frame_with_compilation_removed(Object);
extern Object note_item_needing_initialization_function(Object);
extern Object notify_data_server_of_start_or_reset(Object);
extern Object notify_engineer(int,...);
extern Object notify_user_1(Object);
extern Object notify_user_at_console_and_on_logbook(int,...);
extern Object obtain_newer_value(Object,Object);
extern Object of_valid_indexed_attribute_class_p(Object);
extern Object open_wake_up_collection_function(Object);
extern Object out_indexed_attribute_parent_objects_hash_vector_43_vectors(void);
extern Object outstanding_data_server_count(void);
extern Object outstanding_formula_invocation_count(void);
extern Object outstanding_inference_background_collection_count(void);
extern Object outstanding_simulation_info_count(void);
extern Object outstanding_variable_simulation_runtime_structure_count(void);
extern Object p_get_item_of_class_by_attribute_value(Object,Object,Object);
extern Object parent_variable_function(Object);
extern Object perform_background_collection_for_inference_engine(Object,Object);
extern Object perform_postponed_clean_ups(Object,Object);
extern Object propagate_variable_value_expiration(Object);
extern Object push_optimized_constant(Object);
extern Object put_current_evaluation_value(Object,Object,Object,Object,Object);
extern Object put_current_value(int,...);
extern Object put_data_server_aliases(Object,Object,Object);
extern Object put_data_server_map(Object,Object,Object);
extern Object put_data_type_of_variable_or_parameter(Object,Object,Object);
extern Object put_data_type_of_variable_where_slot_is_absent(Object,Object);
extern Object put_formula_qm(Object,Object,Object);
extern Object put_formula_specified_time_increment_for_update_qm_where_slot_is_absent(Object,Object);
extern Object put_g2_meter_data_service_on_qm(Object,Object,Object);
extern Object put_generic_formula_byte_code_body_where_slot_is_absent(Object,Object);
extern Object put_has_no_current_value(Object);
extern Object put_has_no_value(Object);
extern Object put_indexed_attribute_parent(Object,Object,Object,Object);
extern Object put_initial_simulated_value_qm_where_slot_is_absent(Object,Object);
extern Object put_initial_value_for_simulation_qm_where_slot_is_absent(Object,Object);
extern Object put_initial_value_of_variable_or_parameter(Object,Object,Object);
extern Object put_interval_at_which_to_send_value_to_inference_engine_where_slot_is_absent(Object,Object);
extern Object put_k1_value_where_slot_is_absent(Object,Object);
extern Object put_k2_value_where_slot_is_absent(Object,Object);
extern Object put_k3_value_where_slot_is_absent(Object,Object);
extern Object put_k4_value_where_slot_is_absent(Object,Object);
extern Object put_last_time_value_sent_to_inference_engine_where_slot_is_absent(Object,Object);
extern Object put_new_simulation_value_step_where_slot_is_absent(Object,Object);
extern Object put_new_simulation_value_time_where_slot_is_absent(Object,Object);
extern Object put_new_simulation_value_where_slot_is_absent(Object,Object);
extern Object put_parent_for_its_indexed_attributes(int,...);
extern Object put_parent_if_indexed_attribute(Object,Object,Object,Object,Object);
extern Object put_priority_of_continued_data_service_where_slot_is_absent(Object,Object);
extern Object put_rule_to_invoke_when_sensor_fails_qm_where_slot_is_absent(Object,Object);
extern Object put_rule_to_invoke_when_value_arrives_qm_where_slot_is_absent(Object,Object);
extern Object put_simulation_category_qm_where_slot_is_absent(Object,Object);
extern Object put_simulation_class_where_slot_is_absent(Object,Object);
extern Object put_simulation_frame_qm_where_slot_is_absent(Object,Object);
extern Object put_simulation_value_time_where_slot_is_absent(Object,Object);
extern Object put_simulation_value_where_slot_is_absent(Object,Object);
extern Object put_time_of_next_update_where_slot_is_absent(Object,Object);
extern Object put_variable_stored_history_specification_qm_where_slot_is_absent(Object,Object);
extern Object raw_stack_error_named_error(Object,Object);
extern Object reclaim_all_indexed_attribute_hash_tables(void);
extern Object reclaim_cached_explanation(Object);
extern Object reclaim_data_server_1(Object);
extern Object reclaim_environment_vector(Object);
extern Object reclaim_error_text(Object);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_eval_list_1(Object);
extern Object reclaim_eval_tree_1(Object);
extern Object reclaim_evaluation_value(Object);
extern Object reclaim_explanation_variables(void);
extern Object reclaim_formula_invocation_1(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_g2_internal_cached_explanation_value(Object,Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_gensym_tree_1(Object);
extern Object reclaim_if_evaluation_value_1(Object);
extern Object reclaim_indexed_attribute_hash_table(Object);
extern Object reclaim_indexed_attribute_parent_objects(Object);
extern Object reclaim_indexed_attribute_parent_objects_hash_vector(Object);
extern Object reclaim_inference_background_collection_1(Object);
extern Object reclaim_list_of_block_snapshots(Object);
extern Object reclaim_managed_number_or_value_function(Object);
extern Object reclaim_managed_simple_float_array_of_length_1(Object);
extern Object reclaim_managed_simple_long_array_of_length_1(Object);
extern Object reclaim_possible_managed_float(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_simulation_info_1(Object);
extern Object reclaim_simulation_runtime_cache(Object);
extern Object reclaim_skip_list_element(Object);
extern Object reclaim_slot_value(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_variable_simulation_runtime_structure_internal_1(Object);
extern Object record_block_for_tformat(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object regenerate_optimized_constant(Object);
extern Object registered_and_active_default_error_handler_p(void);
extern Object remove_indexed_attribute_parent(Object,Object,Object,Object);
extern Object remove_indexed_attribute_properties(Object,Object,Object,Object);
extern Object remove_parent_for_its_indexed_attributes(Object);
extern Object remove_parent_if_indexed_attribute(Object,Object,Object,Object);
extern Object remove_request_for_rule_instance_invocation(Object,Object);
extern Object remove_rule_instances_from_variable_interests(Object);
extern Object remove_wake_ups_postponing_clean_up(Object,Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_stack_change_cons_pool(void);
extern Object replenish_vector_pool_cons_pool(void);
extern Object report_bad_initial_value_of_variable_or_parameter(Object);
extern Object schedule_computation_instance_execution(Object,Object,Object);
extern Object schedule_formula_for_backward_chaining(Object,Object);
extern Object schedule_update_for_variable_expiration(Object);
extern Object scope_cons(Object,Object);
extern Object set_external_variable_for_simulator(int,...);
extern Object set_last_time_value_sent_to_inference_engine(Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_pending_wake_ups(Object,Object);
extern Object set_simulation_environment_vector(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_wake_ups_function(Object);
extern Object simple_role_of_role(Object);
extern Object simulation_info_structure_memory_usage(void);
extern Object slot_value_number_p(Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object stop_collecting_data_for_inference_engine(Object);
extern Object store_history_value(Object,Object,Object,Object,Object);
extern Object store_managed_number_or_value_function(Object,Object);
extern Object string_eq_w(Object,Object);
extern Object symbolic_type_specification_subtype_p(Object,Object);
extern Object system_table_installed_p(Object);
extern Object task_to_detect_failure(Object);
extern Object task_to_probe_failed_variable(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object tformat_stack_error_text_string(int,...);
extern Object tformat_text_string(int,...);
extern Object twrite(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_wide_character(Object);
extern Object type_specification_of_variable_or_parameter_value(Object);
extern Object update_all_indexed_attribute_hash_tables(void);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_frame_name_references(Object);
extern Object update_generic_simulation_formula_for_variable_or_parameter(Object);
extern Object update_indexed_attribute_hash_table(Object);
extern Object update_indexed_attribute_properties(Object,Object,Object,Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_representations_of_variable_or_parameter_value(Object);
extern Object update_subscriptions_from_variable_change(Object);
extern Object valid_indexed_attribute_value_p(Object);
extern Object valid_initial_value_p(Object);
extern Object validate_all_generic_formula_invocations(void);
extern Object validate_generic_formula_invocation_environment(Object,Object,Object);
extern Object validate_item_or_evaluation_value(Object,Object,Object);
extern Object var_count(Object);
extern Object var_type_from_index_function(Object,Object);
extern Object variable_has_received_a_value(Object,Object);
extern Object variable_is_no_longer_available(Object,Object);
extern Object variable_simulation_runtime_structure_structure_memory_usage(void);
extern Object wake_up_inference_background_collection(Object);
extern Object wake_up_variable(Object);
extern Object warn_of_undefined_data_server(Object,Object);
extern Object withdraw_backward_chaining(Object);
extern Object write_circular_path_warning(Object,Object);
extern Object write_data_server_aliases_from_slot(Object,Object);
extern Object write_data_server_map_from_slot(Object,Object);
extern Object write_list_in_chicago_style(int,...);
extern Object write_major_trace_message_for_sensor_data_seek(Object);
extern Object write_major_trace_message_function(Object);
extern Object write_wake_up_list_lossage_warning(void);
extern Object write_warning_message_header(Object);

#else

extern Object absorb_data_server_aliases();
extern Object activate_subclass_of_entity_for_parameter();
extern Object activate_subclass_of_entity_for_variable();
extern Object add_class_to_environment();
extern Object add_grammar_rules_function();
extern Object add_indexed_attribute_properties();
extern Object alias_slot_name();
extern Object allocate_byte_vector_16();
extern Object allocate_managed_simple_vector();
extern Object allocate_managed_simple_vector_for_skip_list();
extern Object assq_function();
extern Object attempt_new_variable_value_collection();
extern Object begin_collecting_data_for_inference_engine();
extern Object break_out_of_debug_messages();
extern Object buffer_size_for_partial_buffer();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object bytes_per_typed_simple_array();
extern Object cache_explanation();
extern Object cache_explanation_variables();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object cancel_formula_for_backward_chaining();
extern Object change_slot_description_value_function();
extern Object change_slot_value();
extern Object check_if_superior_classes_are_defined();
extern Object circular_variable_interests_1();
extern Object clean_up_wake_ups_state_if_any();
extern Object cleanup_for_generic_formula();
extern Object cleanup_for_object();
extern Object cleanup_for_parameter();
extern Object cleanup_for_variable();
extern Object clear_currently_evaluating_formula_after_bombout();
extern Object clear_histories();
extern Object clear_indexed_attribute_defining_classes_skip_list();
extern Object clear_indexed_attribute_hash_table();
extern Object clear_indexed_attribute_parent_objects();
extern Object clear_indexed_attribute_parent_objects_tree();
extern Object clear_items_needing_initialization_tree();
extern Object clear_optimized_constants();
extern Object clear_pending_wake_ups();
extern Object collect_all_indexed_attributes_for_class();
extern Object collect_all_indexed_attributes_for_object();
extern Object collect_subclasses();
extern Object compilations_up_to_date_p();
extern Object compile_data_server_aliases_for_slot();
extern Object compute_newer_value_of_variable();
extern Object compute_text_hash_code();
extern Object constant_queue_push_right();
extern Object copy_data_server();
extern Object copy_data_servers_for_process();
extern Object copy_evaluation_value_1();
extern Object copy_explanation_variables();
extern Object copy_frame_serial_number();
extern Object copy_list_using_eval_conses_1();
extern Object copy_out_current_wide_string();
extern Object copy_tree_using_eval_conses_1();
extern Object copy_wide_string();
extern Object data_server_requests_accept_data_calls();
extern Object data_server_structure_memory_usage();
extern Object data_type_of_variable_or_parameter_function();
extern Object deactivate_subclass_of_entity_for_parameter();
extern Object deactivate_subclass_of_entity_for_variable();
extern Object def_bombout_clean_up_function();
extern Object def_data_server();
extern Object def_data_server_pretty_printer();
extern Object deinstall_system_table_for_data_server_parameters();
extern Object delete_backward_chaining_display_if_any_for_variable();
extern Object delete_dynamic_rule_displays_for_rule_or_object();
extern Object delete_eval_element_1();
extern Object delete_gensym_element_1();
extern Object delete_skip_list_entry();
extern Object denote_cell_array_element_for_generic_formula();
extern Object denote_cell_array_element_for_variable();
extern Object denote_component_of_block_1();
extern Object designation_operator_or_giver_of_value_p();
extern Object direct_structure_method();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object eval_cons_1();
extern Object evaluation_value_eql();
extern Object evaluation_value_equal_p();
extern Object evaluation_value_of_type_p();
extern Object evaluation_value_type();
extern Object evaluation_value_value();
extern Object exit_computation_context_for_variable_formula();
extern Object expression_cell_updated_for_generic_formula();
extern Object expression_cell_updated_for_variable();
extern Object expression_may_use_indexed_attribute_p();
extern Object extend_current_gensym_string();
extern Object find_generic_formula();
extern Object fix_up_initial_value_of_variable_or_parameter();
extern Object flatten_indexed_attribute_parent_objects();
extern Object flatten_skip_list();
extern Object formula_invocation_structure_memory_usage();
extern Object frame_hash_function();
extern Object frame_serial_number_equal_function();
extern Object frame_serial_number_setf_helper_1();
extern Object future_task_schedule_2();
extern Object g2_cell_array_managed_array_function();
extern Object g2_enterprise_p();
extern Object g2_expression_cell_byte_code_body_function();
extern Object g2_list_empty_p();
extern Object g2_list_insert_at_end();
extern Object g2_priority_of_data_service_function();
extern Object generate_float_vector();
extern Object generate_standard_error_message();
extern Object gensym_cons_1();
extern Object gensym_list_2();
extern Object gensym_list_3();
extern Object get_and_validate_indexed_attribute_value();
extern Object get_class_feature_if_any();
extern Object get_current_evaluation_value();
extern Object get_current_value();
extern Object get_data_type_of_variable_or_parameter_from_frame();
extern Object get_defining_class_for_parent_attribute_if_any();
extern Object get_item_or_item_list_for_uuid();
extern Object get_kb_parent_information();
extern Object get_lookup_slot_value_given_default();
extern Object get_or_make_history_buffer();
extern Object get_or_make_simulation_runtime_cache();
extern Object get_pretty_slot_name_for_parent_attribute_if_any();
extern Object get_slot_description();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_description_value();
extern Object get_slot_init_form();
extern Object get_slot_value_function();
extern Object get_slot_value_if_any_function();
extern Object getfq_function_no_default();
extern Object give_warning_1();
extern Object handle_formula_invocation_error();
extern Object handle_update_to_indexed_attribute();
extern Object handle_update_to_sensor_data_type();
extern Object increment_profiling_calls();
extern Object indexed_attribute_or_inherited_attribute_for_class_p();
extern Object indexed_attribute_or_inherited_attribute_p();
extern Object indexed_attribute_parent_objects_hash_vector_43_vector_memory_usage();
extern Object inference_background_collection_structure_memory_usage();
extern Object initialize_after_reading_for_variable_or_parameter();
extern Object initialize_data_server_properties();
extern Object initialize_for_generic_formula();
extern Object initialize_for_parameter();
extern Object initialize_for_variable_or_parameter();
extern Object initialize_or_shut_down_g2_meter_data_server();
extern Object insert_indexed_attribute_items_in_list();
extern Object install_system_table_for_data_server_parameters();
extern Object install_true_value_update();
extern Object invoke_rules_for_backward_chaining();
extern Object invoke_rules_for_failure_chaining();
extern Object invoke_rules_for_forward_chaining();
extern Object invoke_update_functions_for_expired_value();
extern Object invoke_update_functions_for_put_has_no_current_value();
extern Object invoke_user_defined_default_error_handler();
extern Object is_a_formula_invocation_qm();
extern Object item_to_profile_of_formula_invocation();
extern Object load_and_initialize_type_description();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object make_all_indexed_attribute_hash_tables();
extern Object make_data_server_1();
extern Object make_empty_expression_cell();
extern Object make_evaluation_value_1();
extern Object make_formula_invocation_1();
extern Object make_frame();
extern Object make_indexed_attribute_defining_classes_skip_list_sentinel();
extern Object make_indexed_attribute_hash_table();
extern Object make_indexed_attribute_parent_objects();
extern Object make_indexed_attribute_parent_objects_hash_vector();
extern Object make_indexed_attribute_parent_objects_tree_for_hash_skip_list_sentinel();
extern Object make_inference_background_collection_1();
extern Object make_items_needing_initialization_skip_list_sentinel();
extern Object make_permanent_data_server_structure_internal();
extern Object make_permanent_formula_invocation_structure_internal();
extern Object make_permanent_indexed_attribute_parent_objects_hash_vector_43_vector_internal();
extern Object make_permanent_inference_background_collection_structure_internal();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_simulation_info_structure_internal();
extern Object make_permanent_variable_simulation_runtime_structure_structure_internal();
extern Object make_simulation_info_1();
extern Object make_skip_list_element_1();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_thread_array();
extern Object make_variable_simulation_runtime_structure_1();
extern Object maximize_priority_of_rule_instance();
extern Object maximize_priority_of_variable();
extern Object memq_function();
extern Object mutate_global_property();
extern Object mutate_indexed_attribute_defining_classes_skip_list_entry();
extern Object mutate_indexed_attribute_parent_objects_tree_for_hash_skip_list_entry();
extern Object mutate_items_needing_initialization_skip_list_entry();
extern Object mutate_kb_specific_property_value();
extern Object normalize_to_gensym_float();
extern Object note_change_to_block_1();
extern Object note_change_to_runtime_data_for_block_1();
extern Object note_frame_with_compilation_removed();
extern Object note_item_needing_initialization_function();
extern Object notify_data_server_of_start_or_reset();
extern Object notify_engineer();
extern Object notify_user_1();
extern Object notify_user_at_console_and_on_logbook();
extern Object obtain_newer_value();
extern Object of_valid_indexed_attribute_class_p();
extern Object open_wake_up_collection_function();
extern Object out_indexed_attribute_parent_objects_hash_vector_43_vectors();
extern Object outstanding_data_server_count();
extern Object outstanding_formula_invocation_count();
extern Object outstanding_inference_background_collection_count();
extern Object outstanding_simulation_info_count();
extern Object outstanding_variable_simulation_runtime_structure_count();
extern Object p_get_item_of_class_by_attribute_value();
extern Object parent_variable_function();
extern Object perform_background_collection_for_inference_engine();
extern Object perform_postponed_clean_ups();
extern Object propagate_variable_value_expiration();
extern Object push_optimized_constant();
extern Object put_current_evaluation_value();
extern Object put_current_value();
extern Object put_data_server_aliases();
extern Object put_data_server_map();
extern Object put_data_type_of_variable_or_parameter();
extern Object put_data_type_of_variable_where_slot_is_absent();
extern Object put_formula_qm();
extern Object put_formula_specified_time_increment_for_update_qm_where_slot_is_absent();
extern Object put_g2_meter_data_service_on_qm();
extern Object put_generic_formula_byte_code_body_where_slot_is_absent();
extern Object put_has_no_current_value();
extern Object put_has_no_value();
extern Object put_indexed_attribute_parent();
extern Object put_initial_simulated_value_qm_where_slot_is_absent();
extern Object put_initial_value_for_simulation_qm_where_slot_is_absent();
extern Object put_initial_value_of_variable_or_parameter();
extern Object put_interval_at_which_to_send_value_to_inference_engine_where_slot_is_absent();
extern Object put_k1_value_where_slot_is_absent();
extern Object put_k2_value_where_slot_is_absent();
extern Object put_k3_value_where_slot_is_absent();
extern Object put_k4_value_where_slot_is_absent();
extern Object put_last_time_value_sent_to_inference_engine_where_slot_is_absent();
extern Object put_new_simulation_value_step_where_slot_is_absent();
extern Object put_new_simulation_value_time_where_slot_is_absent();
extern Object put_new_simulation_value_where_slot_is_absent();
extern Object put_parent_for_its_indexed_attributes();
extern Object put_parent_if_indexed_attribute();
extern Object put_priority_of_continued_data_service_where_slot_is_absent();
extern Object put_rule_to_invoke_when_sensor_fails_qm_where_slot_is_absent();
extern Object put_rule_to_invoke_when_value_arrives_qm_where_slot_is_absent();
extern Object put_simulation_category_qm_where_slot_is_absent();
extern Object put_simulation_class_where_slot_is_absent();
extern Object put_simulation_frame_qm_where_slot_is_absent();
extern Object put_simulation_value_time_where_slot_is_absent();
extern Object put_simulation_value_where_slot_is_absent();
extern Object put_time_of_next_update_where_slot_is_absent();
extern Object put_variable_stored_history_specification_qm_where_slot_is_absent();
extern Object raw_stack_error_named_error();
extern Object reclaim_all_indexed_attribute_hash_tables();
extern Object reclaim_cached_explanation();
extern Object reclaim_data_server_1();
extern Object reclaim_environment_vector();
extern Object reclaim_error_text();
extern Object reclaim_eval_cons_1();
extern Object reclaim_eval_list_1();
extern Object reclaim_eval_tree_1();
extern Object reclaim_evaluation_value();
extern Object reclaim_explanation_variables();
extern Object reclaim_formula_invocation_1();
extern Object reclaim_frame_serial_number();
extern Object reclaim_g2_internal_cached_explanation_value();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_gensym_tree_1();
extern Object reclaim_if_evaluation_value_1();
extern Object reclaim_indexed_attribute_hash_table();
extern Object reclaim_indexed_attribute_parent_objects();
extern Object reclaim_indexed_attribute_parent_objects_hash_vector();
extern Object reclaim_inference_background_collection_1();
extern Object reclaim_list_of_block_snapshots();
extern Object reclaim_managed_number_or_value_function();
extern Object reclaim_managed_simple_float_array_of_length_1();
extern Object reclaim_managed_simple_long_array_of_length_1();
extern Object reclaim_possible_managed_float();
extern Object reclaim_schedule_task_args();
extern Object reclaim_simulation_info_1();
extern Object reclaim_simulation_runtime_cache();
extern Object reclaim_skip_list_element();
extern Object reclaim_slot_value();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_text_string();
extern Object reclaim_variable_simulation_runtime_structure_internal_1();
extern Object record_block_for_tformat();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object regenerate_optimized_constant();
extern Object registered_and_active_default_error_handler_p();
extern Object remove_indexed_attribute_parent();
extern Object remove_indexed_attribute_properties();
extern Object remove_parent_for_its_indexed_attributes();
extern Object remove_parent_if_indexed_attribute();
extern Object remove_request_for_rule_instance_invocation();
extern Object remove_rule_instances_from_variable_interests();
extern Object remove_wake_ups_postponing_clean_up();
extern Object replenish_lookup_cons_pool();
extern Object replenish_stack_change_cons_pool();
extern Object replenish_vector_pool_cons_pool();
extern Object report_bad_initial_value_of_variable_or_parameter();
extern Object schedule_computation_instance_execution();
extern Object schedule_formula_for_backward_chaining();
extern Object schedule_update_for_variable_expiration();
extern Object scope_cons();
extern Object set_external_variable_for_simulator();
extern Object set_last_time_value_sent_to_inference_engine();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_pending_wake_ups();
extern Object set_simulation_environment_vector();
extern Object set_skip_list_entry();
extern Object set_wake_ups_function();
extern Object simple_role_of_role();
extern Object simulation_info_structure_memory_usage();
extern Object slot_value_number_p();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object stop_collecting_data_for_inference_engine();
extern Object store_history_value();
extern Object store_managed_number_or_value_function();
extern Object string_eq_w();
extern Object symbolic_type_specification_subtype_p();
extern Object system_table_installed_p();
extern Object task_to_detect_failure();
extern Object task_to_probe_failed_variable();
extern Object text_string_p();
extern Object tformat();
extern Object tformat_stack_error_text_string();
extern Object tformat_text_string();
extern Object twrite();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_wide_character();
extern Object type_specification_of_variable_or_parameter_value();
extern Object update_all_indexed_attribute_hash_tables();
extern Object update_all_representations_of_slot();
extern Object update_frame_name_references();
extern Object update_generic_simulation_formula_for_variable_or_parameter();
extern Object update_indexed_attribute_hash_table();
extern Object update_indexed_attribute_properties();
extern Object update_object_pool_meters_list();
extern Object update_representations_of_variable_or_parameter_value();
extern Object update_subscriptions_from_variable_change();
extern Object valid_indexed_attribute_value_p();
extern Object valid_initial_value_p();
extern Object validate_all_generic_formula_invocations();
extern Object validate_generic_formula_invocation_environment();
extern Object validate_item_or_evaluation_value();
extern Object var_count();
extern Object var_type_from_index_function();
extern Object variable_has_received_a_value();
extern Object variable_is_no_longer_available();
extern Object variable_simulation_runtime_structure_structure_memory_usage();
extern Object wake_up_inference_background_collection();
extern Object wake_up_variable();
extern Object warn_of_undefined_data_server();
extern Object withdraw_backward_chaining();
extern Object write_circular_path_warning();
extern Object write_data_server_aliases_from_slot();
extern Object write_data_server_map_from_slot();
extern Object write_list_in_chicago_style();
extern Object write_major_trace_message_for_sensor_data_seek();
extern Object write_major_trace_message_function();
extern Object write_wake_up_list_lossage_warning();
extern Object write_warning_message_header();

#endif

/* variables/constants */
DECLARE_VARIABLE_WITH_SYMBOL(Attribute_nesting_depth, Qattribute_nesting_depth);
extern Object Available_eval_conses_tail_vector;
extern Object Available_eval_conses_vector;
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_gensym_conses_tail_vector;
extern Object Available_gensym_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Available_indexed_attribute_parent_objects_hash_vector_43_vectors, Qavailable_indexed_attribute_parent_objects_hash_vector_43_vectors);
extern Object Available_indexed_attribute_parent_objects_hash_vector_43_vectors_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
extern Object Available_vector_pool_conses_tail_vector;
extern Object Available_vector_pool_conses_vector;
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Breakpoint_level, Qbreakpoint_level);
DECLARE_VARIABLE_WITH_SYMBOL(Cached_top_of_stack, Qcached_top_of_stack);
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_data_servers, Qchain_of_available_data_servers);
extern Object Chain_of_available_data_servers_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_formula_invocations, Qchain_of_available_formula_invocations);
extern Object Chain_of_available_formula_invocations_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_inference_background_collections, Qchain_of_available_inference_background_collections);
extern Object Chain_of_available_inference_background_collections_vector;
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_simulation_infos, Qchain_of_available_simulation_infos);
extern Object Chain_of_available_simulation_infos_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_variable_simulation_runtime_structures, Qchain_of_available_variable_simulation_runtime_structures);
extern Object Chain_of_available_variable_simulation_runtime_structures_vector;
extern Object Class_definition_gkbprop;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_indexed_attribute_parent_objects_hash_vector_43_vectors, Qcount_of_indexed_attribute_parent_objects_hash_vector_43_vectors);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_block_of_dependent_frame, Qcurrent_block_of_dependent_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_flags, Qcurrent_computation_flags);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_frame, Qcurrent_computation_frame);
DECLARE_VARIABLE_WITH_SYMBOL(Current_computation_instance, Qcurrent_computation_instance);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_gensym_string, Qcurrent_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Currently_automatically_resolving_class_name_conflicts_qm, Qcurrently_automatically_resolving_class_name_conflicts_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_count, Qdata_server_count);
extern Object Data_server_kbprop;
extern Object Data_server_or_alias_qm_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_parameters, Qdata_server_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Data_server_pretty_name_alist, Qdata_server_pretty_name_alist);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_parameters, Qdebugging_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Debugging_reset, Qdebugging_reset);
DECLARE_VARIABLE_WITH_SYMBOL(Defer_notifications_qm, Qdefer_notifications_qm);
extern Object Deferred_task_queue_vector;
extern Object Environment_allocation_schemes;
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
DECLARE_VARIABLE_WITH_SYMBOL(Explanation_variables, Qexplanation_variables);
#define Falsity FIX((SI_Long)-1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_gensym_string, Qfill_pointer_for_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Float_parameter_class_description, Qfloat_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Float_variable_class_description, Qfloat_variable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Formula_invocation_count, Qformula_invocation_count);
extern Object Formulas_for_this_role_kbprop;
extern Object Fp_mutate_indexed_attribute_defining_classes_skip_list_entry;
extern Object Fp_mutate_indexed_attribute_parent_objects_tree_for_hash_skip_list_entry;
extern Object Fp_mutate_items_needing_initialization_skip_list_entry;
DECLARE_VARIABLE_WITH_SYMBOL(G2_cell_array_class_description, Qg2_cell_array_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(G2_time_at_start, Qg2_time_at_start);
#define G2_version_2011_kb_flags FIX((SI_Long)281L)
DECLARE_VARIABLE_WITH_SYMBOL(Generic_formula_class_description, Qgeneric_formula_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Generic_simulation_formula_class_description, Qgeneric_simulation_formula_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Generic_simulation_formulas_used_p, Qgeneric_simulation_formulas_used_p);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time, Qgensym_time);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_time_at_start, Qgensym_time_at_start);
DECLARE_VARIABLE_WITH_SYMBOL(Global_list_of_all_data_servers, Qglobal_list_of_all_data_servers);
#define Higher_than_any_priority FIX((SI_Long)-1L)
#define Highest_system_priority FIX((SI_Long)0L)
#define How_many_priorities_qm FIX((SI_Long)10L)
extern Object Indexed_attribute_classes_kbprop;
extern Object Indexed_attribute_hash_table_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Indexed_attributes, Qindexed_attributes);
DECLARE_VARIABLE_WITH_SYMBOL(Inference_background_collection_count, Qinference_background_collection_count);
DECLARE_VARIABLE_WITH_SYMBOL(Inference_engine_parameters, Qinference_engine_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Inside_breakpoint_p, Qinside_breakpoint_p);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Integer_parameter_class_description, Qinteger_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Integer_variable_class_description, Qinteger_variable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Items_needing_initialization_tree, Qitems_needing_initialization_tree);
DECLARE_VARIABLE_WITH_SYMBOL(Just_update_representations_of_slot_value, Qjust_update_representations_of_slot_value);
extern Object Kb_specific_property_names;
DECLARE_VARIABLE_WITH_SYMBOL(List_of_all_data_servers, Qlist_of_all_data_servers);
DECLARE_VARIABLE_WITH_SYMBOL(Loading_kb_p, Qloading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Logical_parameter_class_description, Qlogical_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Logical_variable_class_description, Qlogical_variable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Long_variable_class_description, Qlong_variable_class_description);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Most_negative_fixnum_as_float;
extern Object Most_positive_fixnum_as_float;
DECLARE_VARIABLE_WITH_SYMBOL(New_value_computed_in_formula_qm, Qnew_value_computed_in_formula_qm);
extern Object No_specific_property_value;
DECLARE_VARIABLE_WITH_SYMBOL(No_value, Qno_value);
DECLARE_VARIABLE_WITH_SYMBOL(Note_blocks_in_tformat, Qnote_blocks_in_tformat);
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Numeric_data_type_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Parameter_class_description, Qparameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_current_task, Qpriority_of_current_task);
extern Object Priority_of_expiration_update_task;
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Put_current_evaluation_value_old_value_qm, Qput_current_evaluation_value_old_value_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Put_current_evaluation_value_return_value, Qput_current_evaluation_value_return_value);
DECLARE_VARIABLE_WITH_SYMBOL(Put_current_value_called_from_simulator_p, Qput_current_value_called_from_simulator_p);
DECLARE_VARIABLE_WITH_SYMBOL(Quantitative_parameter_class_description, Qquantitative_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Quantitative_variable_class_description, Qquantitative_variable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Record_fixnum_time_units_of_sleep_this_clock_tick_qm, Qrecord_fixnum_time_units_of_sleep_this_clock_tick_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_info_count, Qsimulation_info_count);
DECLARE_VARIABLE_WITH_SYMBOL(Simulation_subtable_class_description, Qsimulation_subtable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Snapshots_of_related_blocks, Qsnapshots_of_related_blocks);
extern Object Some_time_ago;
DECLARE_VARIABLE_WITH_SYMBOL(Stack_eval_qm, Qstack_eval_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_expiration, Qstack_expiration);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_warning_message_header_qm, Qsuppress_warning_message_header_qm);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(Symbolic_parameter_class_description, Qsymbolic_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Symbolic_variable_class_description, Qsymbolic_variable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(System_has_paused, Qsystem_has_paused);
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(Text_parameter_class_description, Qtext_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Text_variable_class_description, Qtext_variable_class_description);
extern Object The_type_description_of_data_server;
extern Object The_type_description_of_formula_invocation;
extern Object The_type_description_of_inference_background_collection;
extern Object The_type_description_of_simulation_info;
extern Object The_type_description_of_variable_simulation_runtime_structure;
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_gensym_string, Qtotal_length_of_current_gensym_string);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Tracing_message_level, Qtracing_message_level);
#define Truth FIX((SI_Long)1000L)
DECLARE_VARIABLE_WITH_SYMBOL(Variable_class_description, Qvariable_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_or_parameter_class_description, Qvariable_or_parameter_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Variable_simulation_runtime_structure_count, Qvariable_simulation_runtime_structure_count);
DECLARE_VARIABLE_WITH_SYMBOL(Variables_that_did_not_have_values, Qvariables_that_did_not_have_values);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(Warning_message_level, Qwarning_message_level);
DECLARE_VARIABLE_WITH_SYMBOL(Within_backward_chaining_task, Qwithin_backward_chaining_task);
