/* wrkstn.h -- Header File for wrkstn.c
 * Copyright (C) 1986-2017 Gensym Corporation.  All Rights Reserved.
 */


/* Symbol Definitions */
extern Object Qand;
extern Object Kdowncase;
extern Object Qeq;
extern Object Qfloat;
extern Object Qinteger;
extern Object Qmember;
extern Object Kname;
extern Object Qnumber;
extern Object Qquote;
extern Object Qsecond;
extern Object Qsequence;
extern Object Qsymbol;
extern Object Qunsigned_byte;

extern Object Pclos;
extern Object Pclos_run;
extern Object Pclosx;
extern Object Pcl;
extern Object Pcl_user;
extern Object Pkeyword;
extern Object Ptrun;
extern Object Ptx;

/* function declarations */

#ifdef USE_PROTOTYPES

extern Object abort_current_workstation_context(Object);
extern Object absorb_local_event_ab_side(Object);
extern Object absorb_local_event_ab_side_1(Object,Object,Object,Object,Object,Object);
extern Object add_class_to_environment(int,...);
extern Object add_frame_note(int,...);
extern Object add_grammar_rules_for_list(int,...);
extern Object add_grammar_rules_function(Object);
extern Object add_or_delete_as_language_contributor(Object,Object,Object);
extern Object add_virtual_attribute(Object,Object,Object,Object,Object,Object,Object);
extern Object adjust_scheduling_interval(Object);
extern Object advanced_button_state(Object,Object,Object);
extern Object alias_slot_name(int,...);
extern Object alignment_grid_spacing_phrase(Object);
extern Object allocate_byte_vector_16(Object);
extern Object allocate_evaluation_sequence(Object);
extern Object allocate_evaluation_structure(Object);
extern Object bytes_per_double_float_simple_array(Object);
extern Object bytes_per_simple_vector(Object);
extern Object call_twng_disconnect_callbacks(Object);
extern Object cancel_and_reclaim_scheduled_queue_element_1(Object);
extern Object canonicalize_key_code(Object);
extern Object car_or_atom(Object);
extern Object change_slot_value(int,...);
extern Object check_for_pending_drawing_on_window(Object);
extern Object check_if_superior_classes_are_defined(Object,Object);
extern Object chestnut_floorf_function(Object,Object);
extern Object chestnut_modf_function(Object,Object);
extern Object cleanup_for_drawing_parameters(Object);
extern Object cleanup_for_g2_native_window(Object);
extern Object clear_optimized_constants(void);
extern Object close_telewindows_callback(Object,Object);
extern Object collect_subclasses(Object);
extern Object compile_g2_window_style_override_for_slot(int,...);
extern Object compile_language_qm_for_slot(int,...);
extern Object compile_millisecond_sleep_interval_for_slot(int,...);
extern Object compile_minimum_scheduling_interval_qm_for_slot(int,...);
extern Object constant_queue_push_right(Object,Object);
extern Object continue_refreshing_image_plane(Object);
extern Object control_event_uses_main_window_relative_coordinates_p(Object,Object,Object);
extern Object copy_constant_wide_string_given_length(Object,Object);
extern Object copy_event_plist(Object);
extern Object copy_frame_serial_number(Object);
extern Object copy_out_current_wide_string(void);
extern Object copy_text_string(Object);
extern Object copy_tree_using_slot_value_conses_1(Object);
extern Object copy_workstation_event(Object);
extern Object create_native_window_item(Object);
extern Object current_modifier_bits_for_workstation(Object);
extern Object current_workstation_has_pending_events_p(void);
extern Object decache_dynamic_menus(int,...);
extern Object decode_window_position(Object,Object,Object);
extern Object default_value_for_image_palette(void);
extern Object define_type_specification_explicit_complex_type(Object,Object);
extern Object deinstall_system_table_for_drawing_parameters(Object);
extern Object delete_frame(Object);
extern Object delete_frame_note_if_any(Object,Object);
extern Object delete_gensym_element_1(Object,Object);
extern Object delete_image_plane(Object);
extern Object delete_native_window_item(Object);
extern Object detail_pane(Object);
extern Object detail_pane_for_workstation(Object);
extern Object direct_structure_method(Object,Object);
extern Object do_deferred_updates_to_representations_in_tables(void);
extern Object do_g2_kb_load_at_launch(void);
extern Object do_some_icp_processing(void);
extern Object drain_current_workstation_drawing_queue(void);
extern Object draw_alignment_grid(Object,Object,Object,Object);
extern Object draw_patterned_line(Object,Object,Object,Object,Object,Object,Object);
extern Object dummy_workstation_p(Object);
extern Object enable_scc_check(void);
extern Object end_icp_message_group(void);
extern Object enqueue_workstation_event(int,...);
extern Object ensure_native_window_item(Object);
extern Object enter_user_settings_editor(Object);
extern Object estructure_slot(Object,Object,Object);
extern Object eval_list_2(Object,Object);
extern Object eval_list_4(Object,Object,Object,Object);
extern Object evaluation_truth_value_is_true_p(Object);
extern Object event_handler_refreshes_image_plane_p(Object);
extern Object event_time_difference(Object,Object);
extern Object extend_parsing_or_exit_editor_as_appropriate(void);
extern Object find_event_interpretation(Object,Object);
extern Object find_image_named(Object);
extern Object find_native_window(int,...);
extern Object finish_changing_kb_for_workstations(void);
extern Object fixnum_time_interval(Object);
extern Object flush_icp_output_ports(void);
extern Object flush_pending_mouse_motion_events(Object);
extern Object flush_workstation(Object);
extern Object force_process_drawing(void);
extern Object force_process_drawing_if_appropriate(void);
extern Object force_some_process_drawing(void);
extern Object force_workstation_drawing(Object);
extern Object frame_serial_number_setf_helper_1(Object,Object);
extern Object future_task_schedule_2(Object);
extern Object g2_cause_asynchronous_abort(void);
extern Object g2_cause_synchronous_abort(void);
extern Object g2_do_abort_workspace(void);
extern Object g2_global_paint_mode_p(void);
extern Object g2_show_schedule(Object,Object);
extern Object g2_stream_close(Object);
extern Object g2_stream_open_for_output(Object);
extern Object g2_stream_terpri(Object);
extern Object g2_window_for_gensym_window_qm(Object);
extern Object g2_window_mode_is_valid_function(Object);
extern Object g2_window_of_native_window_item_qm(Object);
extern Object g2_window_user_is_valid_function(Object);
extern Object generate_float_vector(Object);
extern Object gensym_cons_1(Object,Object);
extern Object gensym_decode_unix_time(Object);
extern Object get_g2_window_given_icp_socket(Object);
extern Object get_g2_window_of_view(Object);
extern Object get_gensym_window_for_g2_window(Object);
extern Object get_global_snap_grid(void);
extern Object get_i_am_alive_info_for_g2_window_if_any(Object);
extern Object get_icp_socket_for_g2_window(Object);
extern Object get_image_plane_by_frame(Object,Object);
extern Object get_lookup_slot_value_given_default(Object,Object,Object);
extern Object get_pending_network_events(void);
extern Object get_property_value_function(int,...);
extern Object get_scale_of_view(Object);
extern Object get_slot_description_of_class_description_function(Object,Object,Object);
extern Object get_slot_value_function(Object,Object,Object);
extern Object get_symbol_properties_function(Object);
extern Object get_value_for_current_workstation_new_g2_classic_ui_p(void);
extern Object get_view_preference(Object,Object);
extern Object get_workspace_of_view(Object);
extern Object getfq_function_no_default(Object,Object);
extern Object handle_native_window_event(Object,Object,Object);
extern Object hide_logbook_in_g2_window(Object);
extern Object icp_connection_being_shutdown_qm(Object);
extern Object icp_connection_open_p(Object);
extern Object idle_time_when_polling(void);
extern Object image_definition_data_qm(Object);
extern Object image_palette_color_map_qm(Object);
extern Object image_plane_of_workspace(Object);
extern Object image_plane_of_workspace_on_window(Object,Object);
extern Object image_plane_of_workspace_on_workstation(Object,Object);
extern Object image_plane_of_workspace_view_qm(Object);
extern Object image_plane_x_scale_mf(Object);
extern Object image_plane_y_scale_mf(Object);
extern Object initial_g2_window_of_view(Object);
extern Object initial_scale_of_view(Object);
extern Object initial_workspace_of_view(Object);
extern Object initialize_after_reading_for_drawing_parameters(Object);
extern Object initialize_for_drawing_parameters(Object);
extern Object initialize_image_palette_of_new_gensym_window(Object);
extern Object initialize_mouse_pointer_tracking_for_window(Object,Object,Object,Object);
extern Object install_system_table_for_drawing_parameters(Object);
extern Object interesting_input_event_p(Object);
extern Object internal_error_given_format_info(Object,Object,Object);
extern Object interpret_workstation_event(Object,Object);
extern Object invalidate_all_image_renderings(void);
extern Object invalidate_image_plane(Object);
extern Object invalidate_mouse_pointer(Object,Object);
extern Object inverse_scalef_function(Object,Object);
extern Object invert_adjusted_scheduling_interval(Object);
extern Object launch_recompilation_for_this_kb(void);
extern Object load_and_initialize_type_description(Object,Object);
extern Object loading_version_3_or_earlier_kb_p(void);
extern Object log_out_workstation(Object);
extern Object logged_in_workstation_session_p(Object);
extern Object lookup_global_or_kb_specific_property_value(Object,Object);
extern Object lookup_kb_specific_property_value(Object,Object);
extern Object lookup_stock_line_pattern_element(Object);
extern Object make_description_box(Object);
extern Object make_entire_g2_window_spot_1(void);
extern Object make_eval_list_1(Object);
extern Object make_event_interpretation(Object,Object,Object);
extern Object make_invalid_spot_1(void);
extern Object make_mouse_pointer_1(Object,Object,Object,Object,Object);
extern Object make_named_dynamic_extent_description(Object,Object,Object,Object,Object,Object,Object);
extern Object make_next_event_mouse_pointer(Object,Object,Object,Object,Object);
extern Object make_permanent_item(Object);
extern Object make_permanent_schedule_task_structure_internal(void);
extern Object make_permanent_workstation_event_structure_internal(void);
extern Object make_symbol_properties_hash_table_skip_list_sentinel(Object,Object);
extern Object make_thread_array(Object);
extern Object make_workspace(int,...);
extern Object make_workstation_1(Object);
extern Object make_workstation_event_1(void);
extern Object map_to_color_value(Object);
extern Object maybe_defer_refreshing_image_plane_1(Object);
extern Object maybe_defer_refreshing_image_plane_2(Object,Object);
extern Object maybe_reclaim_some_mouse_pointers(Object);
extern Object maybe_schedule_service_workstation(Object,Object);
extern Object maybe_schedule_service_workstations(Object);
extern Object maybe_schedule_service_workstations_final(void);
extern Object maybe_schedule_task_to_run_propagate_all_workspace_changes_to_image_planes(void);
extern Object memq_function(Object,Object);
extern Object mouse_down_p(void);
extern Object mouse_key_code_button_name_symbol(Object);
extern Object mouse_motion_key_code(Object);
extern Object mouse_still_down_p(void);
extern Object move_native_image_plane_to(Object,Object,Object);
extern Object mutate_global_property(Object,Object,Object);
extern Object native_menu_bar_really_needs_updating_p(Object);
extern Object native_window_item_class(Object);
extern Object no_local_window_p(void);
extern Object note_change_to_block_1(Object,Object);
extern Object notify_user_at_console(int,...);
extern Object outstanding_workstation_event_count(void);
extern Object pct_set_native_window_size(Object,Object,Object);
extern Object pending_drawing_for_workstation_p(Object);
extern Object phrase_cons(Object,Object);
extern Object phrase_list_2(Object,Object);
extern Object phrase_number_p(Object);
extern Object poll_workstation(void);
extern Object print_constant(int,...);
extern Object print_schedule(void);
extern Object print_schedule_on_temporary_workspace(Object);
extern Object print_schedule_to_file(Object,Object);
extern Object print_schedule_to_string(Object);
extern Object print_schedule_to_string_list(Object);
extern Object printing_window_p(Object);
extern Object propagate_all_workspace_changes_to_image_planes(void);
extern Object propagate_allow_scheduled_drawing(Object);
extern Object propagate_allow_scheduled_drawing_1(Object);
extern Object propagate_drawing_transfer_mode_to_all_gensym_windows(Object);
extern Object propagate_image_palette_to_all_gensym_windows(Object);
extern Object propagate_show_selection_handles_to_all_gensym_windows(int,...);
extern Object push_back_mouse_motion_event(void);
extern Object push_last_spot(Object,Object,Object);
extern Object push_more_detailed_spot(Object,Object,Object);
extern Object push_optimized_constant(Object);
extern Object put_alignment_grid(Object,Object,Object);
extern Object put_allow_scheduled_drawing_qm(Object,Object,Object);
extern Object put_control_request_for_g2_extension_where_slot_is_absent(Object,Object);
extern Object put_default_primary_selection_color(Object,Object,Object);
extern Object put_default_secondary_selection_color(Object,Object,Object);
extern Object put_drawing_in_paint_mode_p(Object,Object,Object);
extern Object put_drawing_priority_where_slot_is_absent(Object,Object);
extern Object put_drawing_transfer_mode_where_slot_is_absent(Object,Object);
extern Object put_g2_connection_request_where_slot_is_absent(Object,Object);
extern Object put_g2_connection_status(Object,Object,Object);
extern Object put_g2_user_mode(Object,Object,Object);
extern Object put_g2_window_style(Object,Object,Object);
extern Object put_image_palette(Object,Object,Object);
extern Object put_image_rendering_quality_where_slot_is_absent(Object,Object);
extern Object put_show_operator_logbook_in_this_window_qm(Object,Object,Object);
extern Object put_show_selection_handles(Object,Object,Object);
extern Object put_specific_language_for_this_g2_window_qm(Object,Object,Object);
extern Object put_specific_language_for_this_ui_client_session_qm(Object,Object,Object);
extern Object put_ui_client_session_user_mode(Object,Object,Object);
extern Object put_workspace_on_pane_function(Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object,Object);
extern Object queue_empty_p(Object);
extern Object queue_insert(Object,Object);
extern Object queue_length(Object);
extern Object queue_non_empty_p(Object);
extern Object queue_peek(Object);
extern Object queue_pop(Object);
extern Object queue_push(Object,Object);
extern Object reclaim_dynamic_dialogs_call_dismissed(Object);
extern Object reclaim_eval_cons_1(Object);
extern Object reclaim_event_interpretation(Object);
extern Object reclaim_event_plist(Object);
extern Object reclaim_frame_serial_number(Object);
extern Object reclaim_gensym_cons_1(Object);
extern Object reclaim_gensym_list_1(Object);
extern Object reclaim_icp_object_map_for_workstation(Object);
extern Object reclaim_mouse_pointer_1(Object);
extern Object reclaim_non_kb_workspaces_for_this_workstation_only(Object);
extern Object reclaim_queue(Object);
extern Object reclaim_schedule_task_args(Object);
extern Object reclaim_slot_value_tree_1(Object);
extern Object reclaim_stack_change_tree_1(Object);
extern Object reclaim_text_string(Object);
extern Object reclaim_workstation(Object);
extern Object reclaim_workstation_event(Object);
extern Object reclaim_workstation_event_1_1(Object);
extern Object reclaim_workstation_event_queue(Object);
extern Object record_direct_structure_method(Object,Object,Object);
extern Object record_system_variable(Object,Object,Object,Object,Object,Object,Object);
extern Object reference_mouse_pointer(Object);
extern Object refresh_alignment_grid(Object);
extern Object refresh_alignment_grid_on_all_windows(void);
extern Object refresh_window(Object);
extern Object regenerate_optimized_constant(Object);
extern Object release_mouse_pointer_if_any(Object);
extern Object remember_last_active_mouse_button(int,...);
extern Object remove_image_plane_pointers_in_workstation_event_queue(Object,Object);
extern Object replenish_lookup_cons_pool(void);
extern Object replenish_stack_change_cons_pool(void);
extern Object requeue_workstation_event(Object,Object);
extern Object reset_paint_mode_if_needed(Object);
extern Object run_event_handler(Object,Object);
extern Object scalef_function(Object,Object);
extern Object search_items_a_little(Object,Object);
extern Object selection_style_mouse_tracking_p(Object);
extern Object selection_style_of_workstation_context(Object);
extern Object selection_style_with_focus_p(Object);
extern Object selection_ui_p(Object);
extern Object send_icp_telewindows_start_mouse_tracking(void);
extern Object send_icp_telewindows_stop_mouse_tracking(void);
extern Object service_background_processes(void);
extern Object service_workstation(Object);
extern Object service_workstation_main(Object);
extern Object service_workstations_final(void);
extern Object set_evaluation_structure_slot(Object,Object,Object);
extern Object set_evaluation_value_to_category_function(Object,Object);
extern Object set_image_palette_of_gensym_window(Object,Object,Object);
extern Object set_lookup_slot_value_1(Object,Object,Object);
extern Object set_non_savable_lookup_slot_value(Object,Object,Object);
extern Object set_property_value_function(Object,Object,Object);
extern Object set_skip_list_entry(Object,Object,Object,Object,Object,Object,Object,Object);
extern Object set_slot_value_to_evaluation_value_function(Object,Object);
extern Object set_up_workstation(Object);
extern Object set_up_workstation_on_ab_side(Object,Object,Object);
extern Object set_view_preference_1(Object,Object,Object);
extern Object set_visible_grid_p(Object,Object);
extern Object shift_lexical_analysis_of_current_workstation_qm(void);
extern Object show_logbook_in_g2_window(Object);
extern Object show_selection_handles_p(int,...);
extern Object simple_trace_workstation_event(Object,Object,Object);
extern Object slot_value_cons_1(Object,Object);
extern Object slot_value_list_2(Object,Object);
extern Object slot_value_list_3(Object,Object,Object);
extern Object stack_change_cons_1(Object,Object);
extern Object stack_change_list_2(Object,Object);
extern Object start_mouse_tracking(Object);
extern Object start_mouse_tracking_in_window(Object);
extern Object start_or_restart_native_window_heartbeat(void);
extern Object start_tracking_mouse_in_current_workstation_context(void);
extern Object stop_mouse_tracking_in_local_window(Object);
extern Object stop_mouse_tracking_in_window(Object);
extern Object stop_tracking_mouse_in_current_workstation_context(void);
extern Object symbol_from_key_code(Object);
extern Object sync_graphics_on_current_window(void);
extern Object synchronize_native_window_item(Object);
extern Object synchronize_selection_style(Object,Object);
extern Object system_start(void);
extern Object system_table_installed_p(Object);
extern Object text_string_p(Object);
extern Object tformat(int,...);
extern Object time_slice_expired_p(void);
extern Object toggle_visible_grid(Object);
extern Object trace_events(void);
extern Object trace_workstation_event(Object,Object,Object);
extern Object track_mouse_pointer_till_done(Object);
extern Object transform_alist_into_plist(Object);
extern Object twng_window_p(Object);
extern Object twrite(Object);
extern Object twrite_alignment_grid_spacing(Object);
extern Object twrite_beginning_of_wide_string(Object,Object);
extern Object twrite_line_pattern_element(Object);
extern Object twrite_symbol(int,...);
extern Object twrite_unix_time(int,...);
extern Object type_description_of(Object);
extern Object type_error_in_setter(Object,Object,Object,Object,Object,Object,Object);
extern Object type_specification_type_p__with_explanation(Object,Object);
extern Object unpack_alignment_grid_value(Object);
extern Object untrace_events(void);
extern Object unwind_all_workstation_contexts(Object);
extern Object update_all_representations_of_slot(Object,Object,Object,Object);
extern Object update_all_selection_highlights(Object);
extern Object update_frame_name_references(Object);
extern Object update_frame_status(Object,Object,Object);
extern Object update_frame_status_and_notes_for_drawing_parameters(Object);
extern Object update_native_menu_bar(Object);
extern Object update_object_pool_meters_list(Object);
extern Object update_selection_highlights_on_workstation(Object,Object);
extern Object update_subscriptions_from_virtual_attribute_change(Object,Object,Object);
extern Object update_window(int,...);
extern Object valid_workstation_context_p_function(Object);
extern Object validate_mouse_pointers(Object);
extern Object visible_grid_p(Object);
extern Object visible_grid_permitted_p(Object);
extern Object work_on_drawing_window(Object,Object);
extern Object workspace_of_workspace_view_qm(Object);
extern Object workstation_dead_p(Object);
extern Object workstation_event_structure_memory_usage(void);
extern Object workstation_for_g2_window_qm_function(Object);
extern Object write_alignment_grid_from_slot(Object,Object);
extern Object write_g2_window_style_override_from_slot(Object,Object);
extern Object write_image_palette_from_slot(Object,Object);
extern Object write_language_qm_from_slot(Object,Object);
extern Object write_millisecond_sleep_interval_from_slot(Object,Object);
extern Object write_minimum_scheduling_interval_qm_from_slot(Object,Object);
extern Object write_text_string_to_stream(Object,Object);
extern Object write_unix_time_qm_from_slot(Object,Object);
extern Object x_in_workspace_coordinates(Object,Object);
extern Object y_in_workspace_coordinates(Object,Object);

#else

extern Object abort_current_workstation_context();
extern Object absorb_local_event_ab_side();
extern Object absorb_local_event_ab_side_1();
extern Object add_class_to_environment();
extern Object add_frame_note();
extern Object add_grammar_rules_for_list();
extern Object add_grammar_rules_function();
extern Object add_or_delete_as_language_contributor();
extern Object add_virtual_attribute();
extern Object adjust_scheduling_interval();
extern Object advanced_button_state();
extern Object alias_slot_name();
extern Object alignment_grid_spacing_phrase();
extern Object allocate_byte_vector_16();
extern Object allocate_evaluation_sequence();
extern Object allocate_evaluation_structure();
extern Object bytes_per_double_float_simple_array();
extern Object bytes_per_simple_vector();
extern Object call_twng_disconnect_callbacks();
extern Object cancel_and_reclaim_scheduled_queue_element_1();
extern Object canonicalize_key_code();
extern Object car_or_atom();
extern Object change_slot_value();
extern Object check_for_pending_drawing_on_window();
extern Object check_if_superior_classes_are_defined();
extern Object chestnut_floorf_function();
extern Object chestnut_modf_function();
extern Object cleanup_for_drawing_parameters();
extern Object cleanup_for_g2_native_window();
extern Object clear_optimized_constants();
extern Object close_telewindows_callback();
extern Object collect_subclasses();
extern Object compile_g2_window_style_override_for_slot();
extern Object compile_language_qm_for_slot();
extern Object compile_millisecond_sleep_interval_for_slot();
extern Object compile_minimum_scheduling_interval_qm_for_slot();
extern Object constant_queue_push_right();
extern Object continue_refreshing_image_plane();
extern Object control_event_uses_main_window_relative_coordinates_p();
extern Object copy_constant_wide_string_given_length();
extern Object copy_event_plist();
extern Object copy_frame_serial_number();
extern Object copy_out_current_wide_string();
extern Object copy_text_string();
extern Object copy_tree_using_slot_value_conses_1();
extern Object copy_workstation_event();
extern Object create_native_window_item();
extern Object current_modifier_bits_for_workstation();
extern Object current_workstation_has_pending_events_p();
extern Object decache_dynamic_menus();
extern Object decode_window_position();
extern Object default_value_for_image_palette();
extern Object define_type_specification_explicit_complex_type();
extern Object deinstall_system_table_for_drawing_parameters();
extern Object delete_frame();
extern Object delete_frame_note_if_any();
extern Object delete_gensym_element_1();
extern Object delete_image_plane();
extern Object delete_native_window_item();
extern Object detail_pane();
extern Object detail_pane_for_workstation();
extern Object direct_structure_method();
extern Object do_deferred_updates_to_representations_in_tables();
extern Object do_g2_kb_load_at_launch();
extern Object do_some_icp_processing();
extern Object drain_current_workstation_drawing_queue();
extern Object draw_alignment_grid();
extern Object draw_patterned_line();
extern Object dummy_workstation_p();
extern Object enable_scc_check();
extern Object end_icp_message_group();
extern Object enqueue_workstation_event();
extern Object ensure_native_window_item();
extern Object enter_user_settings_editor();
extern Object estructure_slot();
extern Object eval_list_2();
extern Object eval_list_4();
extern Object evaluation_truth_value_is_true_p();
extern Object event_handler_refreshes_image_plane_p();
extern Object event_time_difference();
extern Object extend_parsing_or_exit_editor_as_appropriate();
extern Object find_event_interpretation();
extern Object find_image_named();
extern Object find_native_window();
extern Object finish_changing_kb_for_workstations();
extern Object fixnum_time_interval();
extern Object flush_icp_output_ports();
extern Object flush_pending_mouse_motion_events();
extern Object flush_workstation();
extern Object force_process_drawing();
extern Object force_process_drawing_if_appropriate();
extern Object force_some_process_drawing();
extern Object force_workstation_drawing();
extern Object frame_serial_number_setf_helper_1();
extern Object future_task_schedule_2();
extern Object g2_cause_asynchronous_abort();
extern Object g2_cause_synchronous_abort();
extern Object g2_do_abort_workspace();
extern Object g2_global_paint_mode_p();
extern Object g2_show_schedule();
extern Object g2_stream_close();
extern Object g2_stream_open_for_output();
extern Object g2_stream_terpri();
extern Object g2_window_for_gensym_window_qm();
extern Object g2_window_mode_is_valid_function();
extern Object g2_window_of_native_window_item_qm();
extern Object g2_window_user_is_valid_function();
extern Object generate_float_vector();
extern Object gensym_cons_1();
extern Object gensym_decode_unix_time();
extern Object get_g2_window_given_icp_socket();
extern Object get_g2_window_of_view();
extern Object get_gensym_window_for_g2_window();
extern Object get_global_snap_grid();
extern Object get_i_am_alive_info_for_g2_window_if_any();
extern Object get_icp_socket_for_g2_window();
extern Object get_image_plane_by_frame();
extern Object get_lookup_slot_value_given_default();
extern Object get_pending_network_events();
extern Object get_property_value_function();
extern Object get_scale_of_view();
extern Object get_slot_description_of_class_description_function();
extern Object get_slot_value_function();
extern Object get_symbol_properties_function();
extern Object get_value_for_current_workstation_new_g2_classic_ui_p();
extern Object get_view_preference();
extern Object get_workspace_of_view();
extern Object getfq_function_no_default();
extern Object handle_native_window_event();
extern Object hide_logbook_in_g2_window();
extern Object icp_connection_being_shutdown_qm();
extern Object icp_connection_open_p();
extern Object idle_time_when_polling();
extern Object image_definition_data_qm();
extern Object image_palette_color_map_qm();
extern Object image_plane_of_workspace();
extern Object image_plane_of_workspace_on_window();
extern Object image_plane_of_workspace_on_workstation();
extern Object image_plane_of_workspace_view_qm();
extern Object image_plane_x_scale_mf();
extern Object image_plane_y_scale_mf();
extern Object initial_g2_window_of_view();
extern Object initial_scale_of_view();
extern Object initial_workspace_of_view();
extern Object initialize_after_reading_for_drawing_parameters();
extern Object initialize_for_drawing_parameters();
extern Object initialize_image_palette_of_new_gensym_window();
extern Object initialize_mouse_pointer_tracking_for_window();
extern Object install_system_table_for_drawing_parameters();
extern Object interesting_input_event_p();
extern Object internal_error_given_format_info();
extern Object interpret_workstation_event();
extern Object invalidate_all_image_renderings();
extern Object invalidate_image_plane();
extern Object invalidate_mouse_pointer();
extern Object inverse_scalef_function();
extern Object invert_adjusted_scheduling_interval();
extern Object launch_recompilation_for_this_kb();
extern Object load_and_initialize_type_description();
extern Object loading_version_3_or_earlier_kb_p();
extern Object log_out_workstation();
extern Object logged_in_workstation_session_p();
extern Object lookup_global_or_kb_specific_property_value();
extern Object lookup_kb_specific_property_value();
extern Object lookup_stock_line_pattern_element();
extern Object make_description_box();
extern Object make_entire_g2_window_spot_1();
extern Object make_eval_list_1();
extern Object make_event_interpretation();
extern Object make_invalid_spot_1();
extern Object make_mouse_pointer_1();
extern Object make_named_dynamic_extent_description();
extern Object make_next_event_mouse_pointer();
extern Object make_permanent_item();
extern Object make_permanent_schedule_task_structure_internal();
extern Object make_permanent_workstation_event_structure_internal();
extern Object make_symbol_properties_hash_table_skip_list_sentinel();
extern Object make_thread_array();
extern Object make_workspace();
extern Object make_workstation_1();
extern Object make_workstation_event_1();
extern Object map_to_color_value();
extern Object maybe_defer_refreshing_image_plane_1();
extern Object maybe_defer_refreshing_image_plane_2();
extern Object maybe_reclaim_some_mouse_pointers();
extern Object maybe_schedule_service_workstation();
extern Object maybe_schedule_service_workstations();
extern Object maybe_schedule_service_workstations_final();
extern Object maybe_schedule_task_to_run_propagate_all_workspace_changes_to_image_planes();
extern Object memq_function();
extern Object mouse_down_p();
extern Object mouse_key_code_button_name_symbol();
extern Object mouse_motion_key_code();
extern Object mouse_still_down_p();
extern Object move_native_image_plane_to();
extern Object mutate_global_property();
extern Object native_menu_bar_really_needs_updating_p();
extern Object native_window_item_class();
extern Object no_local_window_p();
extern Object note_change_to_block_1();
extern Object notify_user_at_console();
extern Object outstanding_workstation_event_count();
extern Object pct_set_native_window_size();
extern Object pending_drawing_for_workstation_p();
extern Object phrase_cons();
extern Object phrase_list_2();
extern Object phrase_number_p();
extern Object poll_workstation();
extern Object print_constant();
extern Object print_schedule();
extern Object print_schedule_on_temporary_workspace();
extern Object print_schedule_to_file();
extern Object print_schedule_to_string();
extern Object print_schedule_to_string_list();
extern Object printing_window_p();
extern Object propagate_all_workspace_changes_to_image_planes();
extern Object propagate_allow_scheduled_drawing();
extern Object propagate_allow_scheduled_drawing_1();
extern Object propagate_drawing_transfer_mode_to_all_gensym_windows();
extern Object propagate_image_palette_to_all_gensym_windows();
extern Object propagate_show_selection_handles_to_all_gensym_windows();
extern Object push_back_mouse_motion_event();
extern Object push_last_spot();
extern Object push_more_detailed_spot();
extern Object push_optimized_constant();
extern Object put_alignment_grid();
extern Object put_allow_scheduled_drawing_qm();
extern Object put_control_request_for_g2_extension_where_slot_is_absent();
extern Object put_default_primary_selection_color();
extern Object put_default_secondary_selection_color();
extern Object put_drawing_in_paint_mode_p();
extern Object put_drawing_priority_where_slot_is_absent();
extern Object put_drawing_transfer_mode_where_slot_is_absent();
extern Object put_g2_connection_request_where_slot_is_absent();
extern Object put_g2_connection_status();
extern Object put_g2_user_mode();
extern Object put_g2_window_style();
extern Object put_image_palette();
extern Object put_image_rendering_quality_where_slot_is_absent();
extern Object put_show_operator_logbook_in_this_window_qm();
extern Object put_show_selection_handles();
extern Object put_specific_language_for_this_g2_window_qm();
extern Object put_specific_language_for_this_ui_client_session_qm();
extern Object put_ui_client_session_user_mode();
extern Object put_workspace_on_pane_function();
extern Object queue_empty_p();
extern Object queue_insert();
extern Object queue_length();
extern Object queue_non_empty_p();
extern Object queue_peek();
extern Object queue_pop();
extern Object queue_push();
extern Object reclaim_dynamic_dialogs_call_dismissed();
extern Object reclaim_eval_cons_1();
extern Object reclaim_event_interpretation();
extern Object reclaim_event_plist();
extern Object reclaim_frame_serial_number();
extern Object reclaim_gensym_cons_1();
extern Object reclaim_gensym_list_1();
extern Object reclaim_icp_object_map_for_workstation();
extern Object reclaim_mouse_pointer_1();
extern Object reclaim_non_kb_workspaces_for_this_workstation_only();
extern Object reclaim_queue();
extern Object reclaim_schedule_task_args();
extern Object reclaim_slot_value_tree_1();
extern Object reclaim_stack_change_tree_1();
extern Object reclaim_text_string();
extern Object reclaim_workstation();
extern Object reclaim_workstation_event();
extern Object reclaim_workstation_event_1_1();
extern Object reclaim_workstation_event_queue();
extern Object record_direct_structure_method();
extern Object record_system_variable();
extern Object reference_mouse_pointer();
extern Object refresh_alignment_grid();
extern Object refresh_alignment_grid_on_all_windows();
extern Object refresh_window();
extern Object regenerate_optimized_constant();
extern Object release_mouse_pointer_if_any();
extern Object remember_last_active_mouse_button();
extern Object remove_image_plane_pointers_in_workstation_event_queue();
extern Object replenish_lookup_cons_pool();
extern Object replenish_stack_change_cons_pool();
extern Object requeue_workstation_event();
extern Object reset_paint_mode_if_needed();
extern Object run_event_handler();
extern Object scalef_function();
extern Object search_items_a_little();
extern Object selection_style_mouse_tracking_p();
extern Object selection_style_of_workstation_context();
extern Object selection_style_with_focus_p();
extern Object selection_ui_p();
extern Object send_icp_telewindows_start_mouse_tracking();
extern Object send_icp_telewindows_stop_mouse_tracking();
extern Object service_background_processes();
extern Object service_workstation();
extern Object service_workstation_main();
extern Object service_workstations_final();
extern Object set_evaluation_structure_slot();
extern Object set_evaluation_value_to_category_function();
extern Object set_image_palette_of_gensym_window();
extern Object set_lookup_slot_value_1();
extern Object set_non_savable_lookup_slot_value();
extern Object set_property_value_function();
extern Object set_skip_list_entry();
extern Object set_slot_value_to_evaluation_value_function();
extern Object set_up_workstation();
extern Object set_up_workstation_on_ab_side();
extern Object set_view_preference_1();
extern Object set_visible_grid_p();
extern Object shift_lexical_analysis_of_current_workstation_qm();
extern Object show_logbook_in_g2_window();
extern Object show_selection_handles_p();
extern Object simple_trace_workstation_event();
extern Object slot_value_cons_1();
extern Object slot_value_list_2();
extern Object slot_value_list_3();
extern Object stack_change_cons_1();
extern Object stack_change_list_2();
extern Object start_mouse_tracking();
extern Object start_mouse_tracking_in_window();
extern Object start_or_restart_native_window_heartbeat();
extern Object start_tracking_mouse_in_current_workstation_context();
extern Object stop_mouse_tracking_in_local_window();
extern Object stop_mouse_tracking_in_window();
extern Object stop_tracking_mouse_in_current_workstation_context();
extern Object symbol_from_key_code();
extern Object sync_graphics_on_current_window();
extern Object synchronize_native_window_item();
extern Object synchronize_selection_style();
extern Object system_start();
extern Object system_table_installed_p();
extern Object text_string_p();
extern Object tformat();
extern Object time_slice_expired_p();
extern Object toggle_visible_grid();
extern Object trace_events();
extern Object trace_workstation_event();
extern Object track_mouse_pointer_till_done();
extern Object transform_alist_into_plist();
extern Object twng_window_p();
extern Object twrite();
extern Object twrite_alignment_grid_spacing();
extern Object twrite_beginning_of_wide_string();
extern Object twrite_line_pattern_element();
extern Object twrite_symbol();
extern Object twrite_unix_time();
extern Object type_description_of();
extern Object type_error_in_setter();
extern Object type_specification_type_p__with_explanation();
extern Object unpack_alignment_grid_value();
extern Object untrace_events();
extern Object unwind_all_workstation_contexts();
extern Object update_all_representations_of_slot();
extern Object update_all_selection_highlights();
extern Object update_frame_name_references();
extern Object update_frame_status();
extern Object update_frame_status_and_notes_for_drawing_parameters();
extern Object update_native_menu_bar();
extern Object update_object_pool_meters_list();
extern Object update_selection_highlights_on_workstation();
extern Object update_subscriptions_from_virtual_attribute_change();
extern Object update_window();
extern Object valid_workstation_context_p_function();
extern Object validate_mouse_pointers();
extern Object visible_grid_p();
extern Object visible_grid_permitted_p();
extern Object work_on_drawing_window();
extern Object workspace_of_workspace_view_qm();
extern Object workstation_dead_p();
extern Object workstation_event_structure_memory_usage();
extern Object workstation_for_g2_window_qm_function();
extern Object write_alignment_grid_from_slot();
extern Object write_g2_window_style_override_from_slot();
extern Object write_image_palette_from_slot();
extern Object write_language_qm_from_slot();
extern Object write_millisecond_sleep_interval_from_slot();
extern Object write_minimum_scheduling_interval_qm_from_slot();
extern Object write_text_string_to_stream();
extern Object write_unix_time_qm_from_slot();
extern Object x_in_workspace_coordinates();
extern Object y_in_workspace_coordinates();

#endif

/* variables/constants */
extern Object Alignment_grid_default_line_color;
extern Object Alignment_grid_default_line_pattern;
extern Object Alignment_grid_default_spacing;
DECLARE_VARIABLE_WITH_SYMBOL(All_virtual_attributes, Qall_virtual_attributes);
#define Alternate_bit FIX((SI_Long)524288L)
extern Object Available_float_array_conses_tail_vector;
extern Object Available_float_array_conses_vector;
extern Object Available_lookup_conses_tail_vector;
extern Object Available_lookup_conses_vector;
extern Object Available_stack_change_conses_tail_vector;
extern Object Available_stack_change_conses_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Background_processes, Qbackground_processes);
DECLARE_VARIABLE_WITH_SYMBOL(Backtrace_stack_for_internal_error, Qbacktrace_stack_for_internal_error);
extern Object Bad_phrase;
DECLARE_VARIABLE_WITH_SYMBOL(Block_class_description, Qblock_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Bottom_edge_of_draw_area, Qbottom_edge_of_draw_area);
extern Object Chain_of_available_schedule_tasks_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Chain_of_available_workstation_events, Qchain_of_available_workstation_events);
extern Object Chain_of_available_workstation_events_vector;
extern Object Class_description_gkbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Context_of_type_failure, Qcontext_of_type_failure);
#define Control_bit FIX((SI_Long)8388608L)
DECLARE_VARIABLE_WITH_SYMBOL(Count_of_pending_workspace_drawing, Qcount_of_pending_workspace_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Created_simple_float_array_pool_arrays, Qcreated_simple_float_array_pool_arrays);
DECLARE_VARIABLE_WITH_SYMBOL(Current_background_color_value, Qcurrent_background_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_draw_paper_p, Qcurrent_draw_paper_p);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_priority, Qcurrent_drawing_priority);
DECLARE_VARIABLE_WITH_SYMBOL(Current_drawing_transfer_mode, Qcurrent_drawing_transfer_mode);
DECLARE_VARIABLE_WITH_SYMBOL(Current_foreground_color_value, Qcurrent_foreground_color_value);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_serial_number, Qcurrent_frame_serial_number);
DECLARE_VARIABLE_WITH_SYMBOL(Current_frame_transform_qm, Qcurrent_frame_transform_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_time, Qcurrent_g2_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_user_mode_qm, Qcurrent_g2_user_mode_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_g2_window_for_this_workstation_qm, Qcurrent_g2_window_for_this_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_buffer, Qcurrent_icp_buffer);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_port, Qcurrent_icp_port);
DECLARE_VARIABLE_WITH_SYMBOL(Current_icp_socket, Qcurrent_icp_socket);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_x_scale, Qcurrent_image_x_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_image_y_scale, Qcurrent_image_y_scale);
DECLARE_VARIABLE_WITH_SYMBOL(Current_kb_specific_property_list_property_name, Qcurrent_kb_specific_property_list_property_name);
DECLARE_VARIABLE_WITH_SYMBOL(Current_real_time, Qcurrent_real_time);
DECLARE_VARIABLE_WITH_SYMBOL(Current_schedule_task, Qcurrent_schedule_task);
extern Object Current_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Current_task_to_run_propagate_all_workspace_changes_to_image_planes, Qcurrent_task_to_run_propagate_all_workspace_changes_to_image_planes);
DECLARE_VARIABLE_WITH_SYMBOL(Current_thread_index, Qcurrent_thread_index);
DECLARE_VARIABLE_WITH_SYMBOL(Current_twriting_output_type, Qcurrent_twriting_output_type);
DECLARE_VARIABLE_WITH_SYMBOL(Current_ui_client_session, Qcurrent_ui_client_session);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string, Qcurrent_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Current_wide_string_list, Qcurrent_wide_string_list);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation, Qcurrent_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_context, Qcurrent_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_detail_pane, Qcurrent_workstation_detail_pane);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_event, Qcurrent_workstation_event);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_native_window_qm, Qcurrent_workstation_native_window_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Current_workstation_window, Qcurrent_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Current_write_icp_byte_position, Qcurrent_write_icp_byte_position);
DECLARE_VARIABLE_WITH_SYMBOL(Current_x_origin_of_drawing, Qcurrent_x_origin_of_drawing);
DECLARE_VARIABLE_WITH_SYMBOL(Current_y_origin_of_drawing, Qcurrent_y_origin_of_drawing);
extern Object Deferred_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(Delete_corresponding_object_qm, Qdelete_corresponding_object_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Disable_resumability, Qdisable_resumability);
DECLARE_VARIABLE_WITH_SYMBOL(Do_g2_init_file_qm, Qdo_g2_init_file_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Do_not_note_permanent_changes_p, Qdo_not_note_permanent_changes_p);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_is_locked_qm, Qdrawing_is_locked_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Drawing_parameters, Qdrawing_parameters);
extern Object Evaluation_false_value;
extern Object Evaluation_true_value;
#define Event_time_mask FIX((SI_Long)268435455L)
DECLARE_VARIABLE_WITH_SYMBOL(Fill_pointer_for_current_wide_string, Qfill_pointer_for_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation, Qfor_workstation);
DECLARE_VARIABLE_WITH_SYMBOL(For_workstation_polling, Qfor_workstation_polling);
DECLARE_VARIABLE_WITH_SYMBOL(Future_task_to_run_propagate_all_workspace_changes_to_image_planes, Qfuture_task_to_run_propagate_all_workspace_changes_to_image_planes);
DECLARE_VARIABLE_WITH_SYMBOL(G2_window_class_description, Qg2_window_class_description);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_argument_list, Qgensym_error_argument_list);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_format_string, Qgensym_error_format_string);
DECLARE_VARIABLE_WITH_SYMBOL(Gensym_error_sure_of_format_info_p, Qgensym_error_sure_of_format_info_p);
#define Higher_than_any_priority FIX((SI_Long)-1L)
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffer_of_start_of_message_series_qm, Qicp_buffer_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_buffers_for_message_group, Qicp_buffers_for_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_byte_position_of_start_of_message_series_qm, Qicp_byte_position_of_start_of_message_series_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Icp_output_ports_to_flush, Qicp_output_ports_to_flush);
#define Icp_window_protocol_supports_scrolling FIX((SI_Long)4L)
#define Icp_window_protocol_supports_v4_mouse_messages FIX((SI_Long)5L)
#define Illegal_key_code FIX((SI_Long)-1L)
extern Object Illegal_key_index;
extern Object Immediate_task_queue_vector;
DECLARE_VARIABLE_WITH_SYMBOL(In_edit_warning_context_p, Qin_edit_warning_context_p);
DECLARE_VARIABLE_WITH_SYMBOL(Index_of_top_of_backtrace_stack, Qindex_of_top_of_backtrace_stack);
extern Object Instances_specific_to_this_class_kbprop;
DECLARE_VARIABLE_WITH_SYMBOL(Intentionally_bogus_vector_for_g2_cause_asynchronous_abort, Qintentionally_bogus_vector_for_g2_cause_asynchronous_abort);
extern Object Isqrt_of_most_positive_fixnum;
DECLARE_VARIABLE_WITH_SYMBOL(Items_warned_in_edit_warning_context, Qitems_warned_in_edit_warning_context);
extern Object Key_index_bits;
extern Object Key_modifier_bits;
DECLARE_VARIABLE_WITH_SYMBOL(Last_slot_checked_of_type_failure, Qlast_slot_checked_of_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Last_workstation_serviced, Qlast_workstation_serviced);
extern Object Least_common_multiple_of_stock_line_pattern_lengths;
DECLARE_VARIABLE_WITH_SYMBOL(Left_edge_of_draw_area, Qleft_edge_of_draw_area);
#define Managed_array_index_offset FIX((SI_Long)2L)
extern Object Maximum_in_place_array_size;
extern Object Maximum_index_in_backtrace_stack_for_internal_error;
#define Meta_bit FIX((SI_Long)4194304L)
#define Minimum_minimum_fixnum_scheduling_interval FIX((SI_Long)2L)
extern Object Minimum_minimum_float_scheduling_interval;
extern Object Minus_of_isqrt_of_most_positive_fixnum;
extern Object N_2_to_31_plus_62_years;
extern Object Need_call_system_start;
DECLARE_VARIABLE_WITH_SYMBOL(New_g2_classic_ui_p, Qnew_g2_classic_ui_p);
extern Object No_specific_property_value;
extern Object Normal_workstation_servicing_time_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Noting_changes_to_kb_p, Qnoting_changes_to_kb_p);
extern Object Number_of_all_threads;
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_for_message_series, Qnumber_of_icp_bytes_for_message_series);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_in_message_group, Qnumber_of_icp_bytes_in_message_group);
DECLARE_VARIABLE_WITH_SYMBOL(Number_of_icp_bytes_to_fill_buffer, Qnumber_of_icp_bytes_to_fill_buffer);
extern Object Prefer_interfaces_workstation_servicing_time_limit;
DECLARE_VARIABLE_WITH_SYMBOL(Priority_of_next_task, Qpriority_of_next_task);
DECLARE_VARIABLE_WITH_SYMBOL(Profiling_enabled_qm, Qprofiling_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Reading_kb_p, Qreading_kb_p);
DECLARE_VARIABLE_WITH_SYMBOL(Reason_for_type_failure, Qreason_for_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Right_edge_of_draw_area, Qright_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Scheduler_enabled_qm, Qscheduler_enabled_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Scope_conses, Qscope_conses);
extern Object Service_workstation_interval;
extern Object Service_workstations_final_interval;
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_event, Qservicing_workstation_event);
DECLARE_VARIABLE_WITH_SYMBOL(Servicing_workstation_qm, Qservicing_workstation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Simple_float_array_pool_memory_usage, Qsimple_float_array_pool_memory_usage);
#define Size_of_basic_backtrace_information FIX((SI_Long)3L)
DECLARE_VARIABLE_WITH_SYMBOL(Specific_structure_for_current_workstation_context, Qspecific_structure_for_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Stack_of_slot_value_changes, Qstack_of_slot_value_changes);
extern Object Stock_line_pattern_type;
DECLARE_VARIABLE_WITH_SYMBOL(Structure_being_reclaimed, Qstructure_being_reclaimed);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_updating_of_slot_value_representations_qm, Qsuppress_updating_of_slot_value_representations_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Suppress_use_of_stack_of_slot_value_changes_p, Qsuppress_use_of_stack_of_slot_value_changes_p);
extern Object Symbol_properties_table;
DECLARE_VARIABLE_WITH_SYMBOL(System_is_running, Qsystem_is_running);
DECLARE_VARIABLE_WITH_SYMBOL(System_window, Qsystem_window);
DECLARE_VARIABLE_WITH_SYMBOL(Task_to_run_service_workstations_final, Qtask_to_run_service_workstations_final);
extern Object The_type_description_of_image_plane_spot;
extern Object The_type_description_of_kb_workspace_image_plane_spot;
extern Object The_type_description_of_non_kb_workspace_image_plane_spot;
extern Object The_type_description_of_workstation_context_with_selection_focus;
extern Object The_type_description_of_workstation_event;
DECLARE_VARIABLE_WITH_SYMBOL(Timing_parameters, Qtiming_parameters);
DECLARE_VARIABLE_WITH_SYMBOL(Top_edge_of_draw_area, Qtop_edge_of_draw_area);
DECLARE_VARIABLE_WITH_SYMBOL(Total_length_of_current_wide_string, Qtotal_length_of_current_wide_string);
DECLARE_VARIABLE_WITH_SYMBOL(Trace_reshape_events, Qtrace_reshape_events);
DECLARE_VARIABLE_WITH_SYMBOL(Trace_workstation_events, Qtrace_workstation_events);
DECLARE_VARIABLE_WITH_SYMBOL(Type_at_type_failure, Qtype_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_context, Qtype_of_current_workstation_context);
DECLARE_VARIABLE_WITH_SYMBOL(Type_of_current_workstation_window, Qtype_of_current_workstation_window);
DECLARE_VARIABLE_WITH_SYMBOL(Unevaluated_expression, Qunevaluated_expression);
#define Unicode_bit FIX((SI_Long)16777216L)
extern Object Unicode_character_bits;
DECLARE_VARIABLE_WITH_SYMBOL(Value_at_type_failure, Qvalue_at_type_failure);
DECLARE_VARIABLE_WITH_SYMBOL(Vector_of_simple_float_array_pools, Qvector_of_simple_float_array_pools);
DECLARE_VARIABLE_WITH_SYMBOL(With_icp_buffer_coelescing_scope_qm, Qwith_icp_buffer_coelescing_scope_qm);
extern Object Within_side_limits;
DECLARE_VARIABLE_WITH_SYMBOL(Workstation_event_count, Qworkstation_event_count);
DECLARE_VARIABLE_WITH_SYMBOL(Workstation_in_which_to_launch_recompilation_qm, Qworkstation_in_which_to_launch_recompilation_qm);
DECLARE_VARIABLE_WITH_SYMBOL(Workstation_with_image_plane_being_refreshed, Qworkstation_with_image_plane_being_refreshed);
extern Object Workstations_in_service;
DECLARE_VARIABLE_WITH_SYMBOL(Writing_icp_message_group, Qwriting_icp_message_group);
