
#define IDD_DIALOG1                    101
#define IDD_GENSYMTESTHARNESS_DIALOG   102
#define IDD_ABOUTBOX                   103
#define IDS_APP_TITLE                  103
#define IDM_ABOUT                      104
#define IDS_BACK                       104
#define IDM_EXIT                       105
#define IDS_UP                         105
#define IDS_VIEW                       106
#define IDI_GENSYMTESTHARNESS          107
#define IDI_SMALL                      108
#define IDC_GENSYMTESTHARNESS          109
#define IDD_DYNAMIC_DLG                110
#define IDD_DIALOG2                    111
#define IDD_TAB_DLG                    112
#define IDD_DIALOG_LISTVIEW            113
#define IDD_GRID_DEMO_DLG              114
#define IDD_MSG_BROWSE_DLG             115
#define IDR_MAINFRAME                  128
#define IDD_GENSYM_OPENFILE_DLG        129
#define IDB_FOLDER                     130
#define IDB_FOLDER_MASK                131
#define IDR_MENU1                      132
#define IDR_POPUP                      132
#define IDB_VIEWS_BITMAP               135
#define IDC_SPIN_BUTTON                202
#define IDC_SHOW_DAYS                  203
#define IDC_SHOW_HOURS_MINUTES         204
#define IDC_DAYS_LABEL                 205
#define IDC_HOURS_LABEL                206
#define IDC_MINUTES_LABEL              207
#define IDC_ENABLED                    208

#define IDC_FILE_LIST                 1000
#define IDC_LOOKIN_COMBO              1001
#define IDC_SCROLLBAR1                1001
#define IDC_EDIT2                     1002
#define IDC_FILENAME_COMBO            1002
#define IDC_CHECK1                    1003
#define IDC_FILETYPES_COMBO           1003
#define IDC_LOOKIN_COMBO_REBAR        1004
#define IDC_RADIO1                    1004
#define IDC_RADIO2                    1005
#define IDC_STATIC1                   1005
#define IDC_RADIO3                    1006
#define IDC_STATIC2                   1006
#define IDC_COMBOBOXEX1               1007
#define IDC_RADIO4                    1007
#define IDC_EDIT3                     1008
#define IDC_CHECK2                    1009
#define IDC_EDIT4                     1010
#define IDC_BUTTON3                   1015
#define IDC_EDIT5                     1016
#define IDC_EDIT_COL                  1016
#define IDC_LIST1                     1018
#define IDC_BTN_APPLY                 1019
#define IDC_SPIN_COL                  1021
#define IDC_STATIC_ROLE               1030
#define IDC_STATIC_SEQ_NUM            1032
#define IDC_STATIC_ORDER_METHOD       1033
#define IDC_STATIC_SOURCE_TYPE        1034
#define IDC_STATIC_DELIVERY_TYPE      1035
#define IDC_STATIC_METRICS            1036
#define IDC_STATIC_END_PRODUCTS       1037
#define IDC_STATIC_LOGGING_GB         1038
#define IDC_STATIC_LOGGING            1039
#define IDC_BTN_GET_SELS              1040

#define ID_FILE_OPENFILE             32771
#define IDM_DYNAMIC_DIALOG1          32776

#define IDM_DYNAMIC_DIALOG2          40001
#define IDM_DYNAMIC_DIALOG3          40002
#define IDM_UPDATE_DLG               40003
#define IDM_DD_GRIDDLG               40004
#define IDM_DYNDLGS_GRID_DEMO        40005
#define IDM_DYNDLGS_MSG_BROWSER      40006
#define IDM_QUERY_DLG_ITEM           40007
