package com.gensym.beanbuilder;
import java.awt.*;
import java.awt.Button;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Label;
import java.awt.FlowLayout;
import java.net.URL;
import java.util.Locale;
import com.gensym.message.Resource;

import com.gensym.beanbuilder.ImageDisplay;
public class AttentionDialog extends Dialog
{

	private static Resource i18nSettings =
        Resource.getBundle("com.gensym.beanbuilder.text.AttentionDlg", Locale.getDefault() );

	public AttentionDialog(Frame parent, String title, String message, URL iconURL)
	{
		super(parent, title, true);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setVisible(false);
		setSize(insets().left + insets().right + 479,insets().top + insets().bottom + 159);
		setBackground(java.awt.Color.lightGray);
		attentionDialogOkayButton = new java.awt.Button();
		attentionDialogOkayButton.setLabel("OK");
		attentionDialogOkayButton.setBounds(insets().left + 203,insets().top + 119,60,25);
		attentionDialogOkayButton.setFont(new Font("Dialog", Font.PLAIN, 12));
		add(attentionDialogOkayButton);
		imageDisplay1 = new com.gensym.beanbuilder.ImageDisplay();
		imageDisplay1.setStyle(4);
		try {
			imageDisplay1.setFileName("pling64.jpg");
		}
		catch(java.beans.PropertyVetoException e) { }
		imageDisplay1.setBounds(insets().left + 12,insets().top + 27,68,72);
		add(imageDisplay1);
		attentionDialogText = new java.awt.TextArea("",5,0,TextArea.SCROLLBARS_NONE);
		attentionDialogText.setEditable(false);
		attentionDialogText.setBounds(insets().left + 83,insets().top + 24,374,75);
		add(attentionDialogText);
		setTitle("Important");
		//}}

		attentionDialogText.setText(message);



		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		attentionDialogOkayButton.addActionListener(lSymAction);
		//}}
	}

	public AttentionDialog(Frame parent)
	{
		this(parent, i18nSettings.getString("important"), "Event", null);
	}

	// Add a constructor for Interactions (ignoring modal)
	public AttentionDialog(Frame parent, boolean modal)
	{
		this(parent);
	}

	// Add a constructor for Interactions (ignoring modal)
	public AttentionDialog(Frame parent, String message, boolean modal)
	{
		this(parent, i18nSettings.getString("important"), message, null);
	}

    /**
     * Makes this component visible.
     * <p>
     * This is a standard Java AWT method which gets called to show this
     * component. If this component was invisible due to a previous hide()
     * call it makes this component visible again.
     */
    @Override
    public synchronized void show() {
        Rectangle bounds = getParent().bounds();
        Rectangle abounds = bounds();

        move(bounds.x + (bounds.width - abounds.width) / 2,
             bounds.y + (bounds.height - abounds.height) /2);
        attentionDialogOkayButton.setLabel(i18nSettings.getString("okay"));
        super.show();
    }

	@Override
	public void addNotify()
	{
	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		setSize(insets().left + insets().right + d.width, insets().top + insets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets().left, insets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

    // Used for addNotify check.
	boolean fComponentsAdjusted = false;

	//{{DECLARE_CONTROLS
	java.awt.Button attentionDialogOkayButton;
	com.gensym.beanbuilder.ImageDisplay imageDisplay1;
	java.awt.TextArea attentionDialogText;
	//}}

	class SymAction implements java.awt.event.ActionListener
	{
		@Override
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object.equals(attentionDialogOkayButton))
				okButton_Action(event);
		}
	}

	void okButton_Action(java.awt.event.ActionEvent event)
	{
		    hide();
		    //dispose();
	}
}

