// g2opc.idl : IDL source for g2opc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (g2opc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(EDB27B37-D657-410A-9DBC-827B5168D87A),
	version(1.0),
	helpstring("g2opc 1.0 Type Library")
]
library G2OPCLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
