#!/bin/csh -f
#
# Args for the mkisofs pre-mastering program
#
#
# OPTIONS
#      -a   Include all files on the iso9660 filesystem.  Normally files that
#           contain the characters '~' or '#' will not be included (these are
#           typically backup files for editors under unix).
#
#      -A application_id
#           Specifies a text string that will be written into the volume
#           header.  This should describe the application that will be on the
#           disc.  There is space on the disc for 128 characters of
#           information.  This parameter can also be set in the file
#           .mkisofsrc with APPI=id.  If specified in both places, the
#           command line version is used.
#
#      -b boot_image
#           Specifies the path and filename of the boot image to be used when
#           making an "El Torito" bootable CD. The pathname must be relative
#           to the source path specified to mkisofs. This option is required
#           to make a bootable CD.  The boot image must be exactly the size
#           of either a 1.2, 1.44, or a 2.88 meg floppy, and mkisofs will use
#           this size when creating the output iso9660 filesystem. It is
#           assumed that the first 512 byte sector should be read from the
#           boot image (it is essentially emulating a normal floppy drive).
#           This will work, for example, if the boot image is a LILO based
#           boot floppy.
#
#      -c boot_catalog
#           Specifies the path and filename of the boot catalog to be used
#           when making an "El Torito" bootable CD. The pathname must be
#           relative to the source path specified to mkisofs. This option is
#           required to make a bootable CD.  This file will be created by
#           mkisofs in the source filesystem, so be sure the specified
#           filename does not conflict with an existing file, as it will be
#           quietly overwritten! Usually a name like "boot.catalog" is
#           chosen.
#
#      -d   Omit trailing period from files that do not have a period.  This
#           violates the ISO9660 standard, but it happens to work on many
#           systems.  Use with caution.
#
#      -D   Do not use deep directory relocation, and instead just pack them
#           in the way we see them.  This violates the ISO9660 standard, but
#           it works on many systems.  Use with caution.
#
#      -f   Follow symbolic links when generating the filesystem.  When this
#           option is not in use, symbolic links will be entered using Rock
#           Ridge if enabled, otherwise the file will be ignored.
#
#      -i include-list
#           Use the specified file as a list of files to add to the directory
#           tree.  This is useful for quickly repacking a CD while adding
#           files to it.  The format of this file is path1/file=path2 where
#           path1 is the directory in the ISO9660 file system where file
#           should appear and path2 is the where to find the file.  NOTE:
#           This option doesn't work well, and needs to be compltely redone
#           so that integration with the rest of mkisofs is handled in a
#           cleaner fashion.
#
#      -l   Allow full 32 character filenames.  Normally the ISO9660 filename
#           will be in an 8.3 format which is compatible with MS-DOS, even
#           though the ISO9660 standard allows filenames of up to 32
#           characters.  If you use this option, the disc may be difficult to
#           use on a MS-DOS system, but this comes in handy on some other
#           systems (such as the Amiga).  Use with caution.
#
#      -L   Allow filenames to begin with a period.  Usually, a leading dot
#           is replaced with an underscore in order to maintain MS-DOS
#           compatibility.
#
#      -m glob
#           Exclude glob from being written to CDROM.  glob is a shell wild-
#           card-style pattern that must match part of the filename (not the
#           path as with option -x).  Technically glob is matched against the
#           d->d_name part of the directory entry.  Multiple globs may be
#           excluded (up to 1000).  Example:
#
#           mkisofs -o rom -m '*.o' -m core -m foobar
#
#           would exclude all files ending in ".o", called "core" or "foobar"
#           to be copied to CDROM. Note that if you had a directory called
#           "foobar" it too (and of course all its descendants) would be
#           excluded.
#
#      -M path
#           Specifies path to existing iso9660 image to be merged.  The
#           output of mkisofs will be a new session which should get written
#           to the end of the image specified in -M.  Typically this requires
#           multi-session capability for the recorder and cdrom drive that
#           you are attempting to write this image to.  Support for this is
#           not yet 100% complete, because some handshaking is required
#           between mkisofs and cdwrite in order to determine the next
#           writable address on the cdrom.
#
#      -N   Omit version numbers from ISO9660 file names.  This may violate
#           the ISO9660 standard, but no one really uses the version numbers
#           anyway.  Use with caution.
#
#      -o filename
#           is the name of the file to which the iso9660 filesystem image
#           should be written.  This can be a disk file, a tape drive, or it
#           can correspond directly to the device name of the optical disc
#           writer.  If not specified, stdout is used.  Note that the output
#           can also be a block special device for a regular disk drive, in
#           which case the disk partition can be mounted and examined to
#           ensure that the premastering was done correctly.
#
#      -P publisher_id
#           Specifies a text string that will be written into the volume
#           header.  This should describe the publisher of the CDROM, usually
#           with a mailing address and phone number.  There is space on the
#           disc for 128 characters of information.  This parameter can also
#           be set in the file .mkisofsrc with PUBL=.  If specified in both
#           places, the command line version is used.
#
#      -p preparer_id
#           Specifies a text string that will be written into the volume
#           header.  This should describe the preparer of the CDROM, usually
#           with a mailing address and phone number.  There is space on the
#           disc for 128 characters of information.  This parameter can also
#           be set in the file .mkisofsrc with PREP=.  If specified in both
#           places, the command line version is used.
#
#      -R   Generate SUSP and RR records using the Rock Ridge protocol to
#           further describe the files on the iso9660 filesystem.
#
#      -r   This is like the -R option, but file ownership and modes are set
#           to more useful values.  The uid and gid are set to zero, because
#           they are usually only useful on the author's system, and not
#           useful to the client.  All the file read bits are set true, so
#           that files and directories are globally readable on the client.
#           If any execute bit is set for a file, set all of the execute
#           bits, so that executables are globally executable on the client.
#           If any search bit is set for a directory, set all of the search
#           bits, so that directories are globally searchable on the client.
#           All write bits are cleared, because the CD-Rom will be mounted
#           read-only in any case.  If any of the special mode bits are set,
#           clear them, because file locks are not useful on a read-only file
#           system, and set-id bits are not desirable for uid 0 or gid 0.
#
#      -T   Generate a file TRANS.TBL in each directory on the CDROM, which
#           can be used on non-Rock Ridge capable systems to help establish
#           the correct file names.  There is also information present in the
#           file that indicates the major and minor numbers for block and
#           character devices, and each symlink has the name of the link file
#           given.
#
#      -V volid
#           Specifies the volume ID to be written into the master block.
#           This parameter can also be set in the file .mkisofsrc with
#           VOLI=id.  If specified in both places, the command line version
#           is used.
#
#      -v   Verbose execution.
#
#      -x path
#           Exclude path from being written to CDROM.  path must be the
#           complete pathname that results from concatenating the pathname
#           given as command line argument and the path relative to this
#           directory.  Multiple paths may be excluded (up to 1000).
#           Example:
#
#           mkisofs -o cd -x /local/dir1 -x /local/dir2 /local
#
#      -z   Generate special SUSP records for transparently compressed files.
#           This is only of use and interest for hosts that support
#           transparent decompression.  This is an experimental feature, and
#           no hosts yet support this, but there are ALPHA patches for Linux
#           that can make use of this feature.
#
#
#


/home/kj/cdb/mkisofs-1.11.3/mkisofs -o /home/cdtransfer/bridgeCD.iso -d -l -D -N -r -R -V "GENSYM BRIDGES" -P "GENSYM CORPORATION" -A "GENSYM BRIDGES"  /mnt/sd1c/cdrom/premaster
